### ISSUE TITLE
allow to define install prefix manually

### ISSUE THREAD

**Issue by doits** [osxfuse/osxfuse#1]
hello,

I'd like to specify the install prefix of the libs etc. manually. Then this could be easily integrated into macports.

Now the prefix is hardcoded (I think) to "/usr/local". Would be great to have a variable in build.sh to define the prefix to something own.

Tried to replace the "/usr/local" with my own prefix ("/opt/local") in the two files "build.sh" and "fuse/libmacfuse.xcodeproj/project.pbxproj", but that seems not to be enough - still creating "/usr/local" prefix.

Regards,
Markus

**Comment by bfleischer** [comment]
I've completely rewritten the build script for version 3 of FUSE for OS X. The new build system contains a new target for package managers like Homebrew or MacPorts. This should eliminate the need for patching the osxfuse build script (as MacPorts did the last time I checked).

Please note that for now version 2.x remains the latest stable release. Once version 3 become the stable release the following commands should work for Homebrew and MacPorts.

Homebrew

    ./build.sh -v 5 -t packagemanager -a build -- --library-prefix="${prefix}"
    ./build.sh -v 5 -t packagemanager -a install -- "${prefix}"

MacPorts

    ./build.sh -v 5 --build-directory="${workpath}" -t packagemanager -a build -- \
               [-a i386] [-a x86_64] \
               --framework-prefix="${prefix}" \
               --fsbundle-prefix="${prefix}" \
               --library-prefix="${prefix}"
    ./build.sh -v 5 -t packagemanager -a install -- "${destroot}"
