### ISSUE TITLE
Macfuse 4.6.0 not working macOS Sonoma 14.3.1

### ISSUE THREAD

**Issue by benoitballester** [osxfuse/osxfuse#1000]
Hi,

I have done all what has been described in the different posts, and I still don't have that "Allow" button in the "Privacy & Security" system preferences.
I am on sonoma 14.3.1, and installed macFUSE 4.6.0.
And my MacBook Pro is literally brand new (meaning that I don't have tons of cr*p preinstalled). 

```
benoit@cubix ~ % sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
benoit@cubix ~ % 
```

If I run this 
<img width="857" alt="Screenshot 2024-02-15 at 14 05 13" src="https://github.com/osxfuse/osxfuse/assets/4662116/c4a45968-ad81-41fb-a602-6a85ff3eb66e">

I get that, like everyone
<img width="372" alt="Screenshot 2024-02-15 at 14 05 55" src="https://github.com/osxfuse/osxfuse/assets/4662116/b7c9cf8a-ea70-4bb3-93db-4f8be3728af3">

I have followed your instructions, wihout much luck

<img width="991" alt="Screenshot 2024-02-15 at 12 53 50" src="https://github.com/osxfuse/osxfuse/assets/4662116/0d66b95c-3521-450b-8d68-f449c15a07f3">

<img width="827" alt="Screenshot 2024-02-15 at 12 54 17" src="https://github.com/osxfuse/osxfuse/assets/4662116/0f1783e9-f2ed-4bef-94df-82e9c747a989">

But I do have the macFUSE pane
<img width="996" alt="Screenshot 2024-02-15 at 14 02 43" src="https://github.com/osxfuse/osxfuse/assets/4662116/84ae88e7-3e0e-42a3-8051-25e91810619a">

_Originally posted by @benoitballester in https://github.com/osxfuse/osxfuse/issues/992#issuecomment-1945955823_

**Comment by benoitballester** [comment]
I have even disabled SIP and reanabled it. Without luck

**Comment by benoitballester** [comment]
The details button gives me this, so no Benjamin Fleischer to be seen anywhere. Where are you hidding Benjamin Fleischer ;-)

<img width="827" alt="Screenshot 2024-02-16 at 09 05 09" src="https://github.com/osxfuse/osxfuse/assets/4662116/6efd15fc-f324-4e54-b262-5158f538153a">

**Comment by agreenbhm** [comment]
Try this command to accomplish the same without the gui: sudo /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext

**Comment by benoitballester** [comment]
> Try this command to accomplish the same without the gui: sudo /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext

Thanks, but I've tried this already. (see terminal screenshot above).
I actually tried a dozen of times. 
Still there is no way to accept Benjamin Fleischer app in the security pane

**Comment by agreenbhm** [comment]
Sorry, missed your screenshot of the CLI.  I tested that on an Intel MBP an hour ago and it worked fine.  I'm also setting up a brand new MBP and, while I did see the expected button in Privacy & Security, when I clicked it I was prompted with a message I've not seen before (perhaps new to Apple Silicon in combination with Sonoma?).  I'm going to try what it's saying and report back.
<img width="295" alt="image" src="https://github.com/osxfuse/osxfuse/assets/622379/4d3a6a8d-079c-4ce4-865c-7d699b3a057b">

**Comment by benoitballester** [comment]
I have done that what your prompt says, modify the security settings in recovery mode to "Enable kernel extension from identified develelopers". 
![8PMSGHuy3jN2-nDYgYLxzHdmDWrXB-sOsg](https://github.com/osxfuse/osxfuse/assets/4662116/3d636a8f-a24e-4156-aa83-f3735cb74d70)



Now I can activate the Benjamin Fleischer app.
<img width="827" alt="Screenshot 2024-02-20 at 17 20 59" src="https://github.com/osxfuse/osxfuse/assets/4662116/59a083a0-c69d-4778-b9f3-73a4a78f27f6">

However after (each) reboot my mac says (see screenshot) which looks like some instability 
<img width="372" alt="Screenshot 2024-02-20 at 17 18 45" src="https://github.com/osxfuse/osxfuse/assets/4662116/4175cfa8-d2be-430f-ad6e-f41e1245eee2">

After many reboot, I had this message above. Then it stopped.

**Comment by benoitballester** [comment]
Right, after many many rounds of restarts, I managed to mount a folder from a distant server (sshfs). 
`sshfs benoit@SERVER-IP:/path/to/mount/           ~/mount/folder -o volname=folder_mounted`

Which induced my finder and terminal to **freeze**. I had to force-restart my laptop.
After restart,  I remounted the same folder from a distant server (same command as above), and now it seems to work. 

**_I have never encountered such instability before._** 

What _seems_ to have solved the problem is to start in recovery mode, then open the `startup system security` , and select the option as shown below:

![8PMSGHuy3jN2-nDYgYLxzHdmDWrXB-sOsg](https://github.com/osxfuse/osxfuse/assets/4662116/e01dfd9e-d664-4345-abe0-e7961b04861d)

I don't know if I have to select both options or not. any advices welcome. 

I would be happy to have feedback frrom the developper, as I doubt I am the only one with such issues.

**Comment by bfleischer** [comment]
@benoitballester The macFUSE installer directs you to the following "Getting Started" document which outlines the necessary steps to install and load the macFUSE kernel extension.

https://github.com/macfuse/macfuse/wiki/Getting-Started

**Comment by mjonsson1986** [comment]
i assume this project are no longer developed or something. the goole groups seems e.g no longer active

**Comment by agreenbhm** [comment]
> i assume this project are no longer developed or something. the goole groups seems e.g no longer active

This thread is discussing a release from a couple of months ago. Why would you say it's no longer developed?

**Comment by bfleischer** [comment]
@benoitballester, @agreenbhm It looks like both your issues are resolved, so I'm going to close the ticket.
