### ISSUE TITLE
SSHFS: No permission when sshfs (terminal and finder) even though I have read permissions when directly ssh-ing

### ISSUE THREAD

**Issue by Mateusz-Jaskolowski** [osxfuse/osxfuse#1001]
I have a directory that I mount using sshfs. Here is my command (need to jump jump thru another server):

sshfs -o ssh_command='ssh -J me@proxy-computer' me@main-computer:path/ mount-path/ -o volname=directory

Unfortunately, when mounted in such a way, there are some sub-directories that I cannot access, with a message that I lack the permissions. That's the case when I try to access them either via terminal or finder.
However, I do have read permissions for these subdirectories (as a group) and can access them when I directly connect (via ssh) to the main-computer. 

Any reason for such a behaviour? What am I doing wrong?

**Comment by bfleischer** [comment]
Have a look at the `defer_permissions` option: https://github.com/macfuse/macfuse/wiki/Mount-Options#default_permissions-and-defer_permissions

> If the file system doesn't implement the access function, macFUSE will perform permission checks entirely itself based on the attributes of file system objects. The default_permissions option also enables this behavior, wherein the kernel will attempt to do the "right thing" based on what it can "see" (the permission bits as reported by the file system). The file system may not always do the right thing itself though--for example, if the file system retrieves file information from another computer and reports user/group IDs as is, the kernel will not see any alien IDs as belonging to the user that mounted the volume. (This can happen if user ID translation is not enabled or sometimes doesn't work with sshfs.) 

Alternatively, you can map remote UIDs and GIDs to local UIDs and GIDs using the sshfs options `uidfile` and `gidfile`.
