### ISSUE TITLE
sshfs command hangs at random, cant be killed

### ISSUE THREAD

**Issue by srydontgetit** [osxfuse/osxfuse#1003]
Sometimes (from what I can tell right now at random) when I execute a command to mount something from an Ubuntu Server, the command hangs indefinitely and confuses my Mac to a point where I need to hold down the power button to restart it.
Nothing gets mounted.

I have "circumvented" this in some cases by using a relative instead of an absolute Path to declare the local mountpoint.
In other cases neither will work. It also seems to be random from day to day, sometiems both will work sometimes neither, sometimes fine with VPN sometiems not. I have always unmounted any remaining sshfs stuff before trying, thus (from my understanding) starting with a clean slate.

When someting fails I can't SIGTERM or SIGKILL the sshfs process using htop or top and I can't Control-C it. 
Sometimes when I run the command with -d enabled I can Control-C it, sometimes not.
I can post the debug stuff if needed. 

Running FUSE library version: 2.9.9
on M1 MacbookPro with Sonoma 14.0

Thanks in advance for any insights into what might be causing this, what I'm doing wrong or suggestions on how to phrase / explain my issue in a better way.

**Comment by bfleischer** [comment]
This is a know issue. The next macFUSE update will address possible hangs when mounting volume.

**Comment by srydontgetit** [comment]
Okay, thanks for the info. Is there a known way to circumvent this or at least decrease the chance of it happening?

**Comment by bfleischer** [comment]
The new 4.6.2 release addresses the issue. Please let me know in case you are still seeing hangs when mounting macFUSE volumes.
