### ISSUE TITLE
Help wanted:  Set files only be seen in my fuse file system

### ISSUE THREAD

**Issue by E6ren** [osxfuse/osxfuse#1004]
There will be some template files when user using my virtual filesystem. I don't want the user see these files, because there are some decrypted template files. 

I can hide these files by return empty in Fuse callback `contentsOfDirectoryAtPath` in my Fuse filesystem, but when I access the directory by Finder, these files still visible. 

One way I thought to fix this is to create a virtual folder under Fuse filesystem. I create the virtual foder by return "tmpFolder" name in Fuse callback `contentsOfDirectoryAtPath` and return the folder attributes `NSFileType:NSFileTypeDirectory` in Fuse callback `attributesOfItemAtPath`. Thus I can only see the "tmpFolder" from Fuse filesystem.

However, when I try to call NSFileManager to create files in the virtual folder, it always failed.

What I need is to find a way to see/read/write file only in my Fuse filesystem, when outside of my Fuse filesystem, the file will  be invisible. Anyone can help?

**Comment by bfleischer** [comment]
I'm not sure I understand what you are trying to accomplish, but you need to present a consistent file system view. Hiding files or directories from specific users or processes is almost never a good idea.

Maybe you could elaborate on what you are trying to do. It think it might be best to store your template files outside of your virtual file system.

**Comment by E6ren** [comment]
> I'm not sure I understand what you are trying to accomplish, but you need to present a consistent file system view. Hiding files or directories from specific users or processes is almost never a good idea.
> 
> Maybe you could elaborate on what you are trying to do. It think it might be best to store your template files outside of your virtual file system.

Yes, it's not a good idea(or maybe impossible?) to store files under 'virtual folder'.  I am developing a encrypt&decrypt program, so I need find a place to stroe the template decrypted files. Now I find another way to deal with this problem: using an Endpoint client to deny all view requests to the decrypted folder, it works, however, maybe too heavy.
