### ISSUE TITLE
Pre-release 4.6.2 is not popping Security Grant in Security panel 

### ISSUE THREAD

**Issue by maxblax360** [osxfuse/osxfuse#1006]
Hi, 
Installing macFuse pre-release 4.6.2 on Sonoma 14.1.1 M1, the security grant "Allow Benjamin..." does not appear at install finalisation. 

It works with 4.6.1

Thx for opensource support of essential tools

Best
Max

**Comment by bfleischer** [comment]
Was a FUSE volume still mounted when you installed the 4.6.2 update?

Did you try rebooting your Mac after installing 4.6.2 and then mounting a FUSE volume?

**Comment by maxblax360** [comment]
Yes, the volume what still mounted. 
As a matter of fact, it was a fresh install. 

Rebooting yes, but after the install it did pop an error on installer final. Sorry I don't remember exactly the message on the installer final panel. 
No I did not try to mount a FUSE since the install did not reported completed. 

Sorry I can't help more. Thank you a lot for your tool and work! You are helping me every day!

**Comment by bfleischer** [comment]
> Yes, the volume what still mounted.

When a volume is still mounted, the installer is unable to attempt to load the new version of the kernel extension and thereby trigger the "Allow" prompt. You should see the prompt the next time you try to mount a macFUSE volume after unmounting all macFUSE volumes first or restarting your Mac first.
