### ISSUE TITLE
Kernal panic because of invalid size measuring in mac

### ISSUE THREAD

**Issue by MalinrRuwan** [osxfuse/osxfuse#1009]
### Stack Trace

`panic(cpu 6 caller 0xfffffe001be66330): vm_page_validate_no_references: page 0x1028496c000 is referenced @vm_resident.c:3452
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 23E224
Kernel version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
Fileset Kernelcache UUID: A5DBC30112639C0125B0F8101083FBF5
Kernel UUID: D3BBDD1F-7813-3F26-9F94-41BAABDA6E33
Boot session UUID: 9A916EFA-CF88-4506-A200-4829233EABA5
iBoot version: iBoot-10151.101.3
secure boot?: YES
roots installed: 0
Paniclog version: 14
KernelCache slide: 0x0000000013798000
KernelCache base:  0xfffffe001a79c000
Kernel slide:      0x00000000137a0000
Kernel text base:  0xfffffe001a7a4000
Kernel text exec slide: 0x0000000014d10000
Kernel text exec base:  0xfffffe001bd14000
mach_absolute_time: 0x6b38b6e43bc
Epoch Time:        sec       usec
  Boot    : 0x66096549 0x000abbbd
  Sleep   : 0x660b6658 0x000d7056
  Wake    : 0x660b6674 0x000e33c3
  Calendar: 0x660f47de 0x00087814

Zone info:
  Zone map: 0xfffffe10368d8000 - 0xfffffe30368d8000
  . VM    : 0xfffffe10368d8000 - 0xfffffe15035a4000
  . RO    : 0xfffffe15035a4000 - 0xfffffe169cf3c000
  . GEN0  : 0xfffffe169cf3c000 - 0xfffffe1b69c08000
  . GEN1  : 0xfffffe1b69c08000 - 0xfffffe20368d4000
  . GEN2  : 0xfffffe20368d4000 - 0xfffffe25035a0000
  . GEN3  : 0xfffffe25035a0000 - 0xfffffe29d026c000
  . DATA  : 0xfffffe29d026c000 - 0xfffffe30368d8000
  Metadata: 0xfffffe1016680000 - 0xfffffe101e680000
  Bitmaps : 0xfffffe101e680000 - 0xfffffe102143c000
  Extra   : 0 - 0

TPIDRx_ELy = {1: 0xfffffe2032e367a8  0: 0x0000000000001006  0ro: 0x000000016b3fb0e0 }
CORE 0 PVH locks held: None
CORE 1 PVH locks held: None
CORE 2 PVH locks held: None
CORE 3 PVH locks held: None
CORE 4 PVH locks held: None
CORE 5 PVH locks held: None
CORE 6 PVH locks held: None
CORE 7 PVH locks held: None
CORE 8 PVH locks held: None
CORE 9 PVH locks held: None
CORE 0: PC=0xfffffe001bda59f4, LR=0xfffffe001bda59f4, FP=0xfffffe3a4cb93ef0
CORE 1: PC=0x000000019e4062fc, LR=0x000000019633a428, FP=0x000000016d97e380
CORE 2: PC=0xfffffe001bda59f4, LR=0xfffffe001bda59f4, FP=0xfffffe3a4dc4fef0
CORE 3: PC=0xfffffe001bda59f4, LR=0xfffffe001bda59f4, FP=0xfffffe3a4e623ef0
CORE 4: PC=0x000000019e4ce0c4, LR=0x000000019e4ccf94, FP=0x000000016db22440
CORE 5: PC=0x00000001a55725e4, LR=0x00000001a5557120, FP=0x000000016da09d00
CORE 6 is the one that panicked. Check the full backtrace for details.
CORE 7: PC=0xfffffe001c58ef6c, LR=0xfffffe001bd1c080, FP=0xfffffe3a4e4b7df0
CORE 8: PC=0xfffffe001bd82b50, LR=0xfffffe001be67ee4, FP=0xfffffe3a4e1e7b70
CORE 9: PC=0xfffffe001bd82c58, LR=0xfffffe001be66080, FP=0xfffffe3a4e45fa20
Compressor Info: 8% of compressed pages limit (OK) and 6% of segments limit (OK) with 2 swapfiles and OK swap space
Panicked task 0xfffffe29ce5fddc8: 28755 pages, 21 threads: pid 68063: Ventura
Panicked thread: 0xfffffe2032e367a8, backtrace: 0xfffffe3a4dc13470, tid: 2996384
		  lr: 0xfffffe001bd6b1c0  fp: 0xfffffe3a4dc13500
		  lr: 0xfffffe001beb6a4c  fp: 0xfffffe3a4dc13570
		  lr: 0xfffffe001beb4f18  fp: 0xfffffe3a4dc13640
		  lr: 0xfffffe001bd1b8cc  fp: 0xfffffe3a4dc13650
		  lr: 0xfffffe001bd6aab4  fp: 0xfffffe3a4dc13a00
		  lr: 0xfffffe001c57175c  fp: 0xfffffe3a4dc13a20
		  lr: 0xfffffe001be66330  fp: 0xfffffe3a4dc13aa0
		  lr: 0xfffffe001be68118  fp: 0xfffffe3a4dc13ae0
		  lr: 0xfffffe001be15fe4  fp: 0xfffffe3a4dc13da0
		  lr: 0xfffffe001beb5b08  fp: 0xfffffe3a4dc13e40
		  lr: 0xfffffe001beb51ac  fp: 0xfffffe3a4dc13f10
		  lr: 0xfffffe001bd1b8cc  fp: 0xfffffe3a4dc13f20
		  lr: 0xfffffe001bd1b894  fp: 0x0000000000000000

last started kext at 6136343582355: io.macfuse.filesystems.macfuse	2144.20 (addr 0xfffffe001a69c000, size 6288)
loaded kexts:
io.macfuse.filesystems.macfuse	2144.20
com.apple.iokit.SCSITaskUserClient	495
com.apple.driver.AppleUSBMassStorageInterfaceNub	556
com.apple.filesystems.smbfs	5.1
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleTopCaseHIDEventDriver	7440.8
com.apple.driver.AppleBiometricServices	1
com.apple.driver.CoreKDL	1
com.apple.driver.BCMWLANFirmware4388.Hashstore	1
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.filesystems.nfs	1
com.apple.filesystems.lifs	1
com.apple.filesystems.apfs	2236.101.1
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	650.0.2
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.AppleAOPVoiceTrigger	340.42
com.apple.driver.ApplePMP	1
com.apple.driver.AppleSmartIO2	1
com.apple.driver.SEPHibernation	1
com.apple.driver.ApplePMPFirmware	1
com.apple.driver.AppleCS42L84Audio	740.41
com.apple.driver.AppleTypeCRetimer	1.0.0
com.apple.driver.AppleSDXC	3.5.1
com.apple.driver.AppleAVE2	760.23.1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.AppleJPEGDriver	6.6.2
com.apple.driver.AppleProResHW	350.47.0
com.apple.AGXG14X	280.3.9
com.apple.driver.AppleAVD	740
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.driver.AppleSN012776Amp	740.41
com.apple.driver.AppleT6020CLPC	1
com.apple.driver.AppleT6020SOCTuner	1
com.apple.driver.AppleDPDisplayTCON	1
com.apple.driver.AppleMobileDispT602X-DCP	140.0
com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleSerialShim	1
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleEventLogHandler	1
com.apple.driver.AppleT6020PMGR	1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.AppleInterruptControllerV2	1.0.0d1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AudioDMAController-T602x	340.58
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleT8110DART	1
com.apple.driver.AppleT6020	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.usb.AppleUSBUserHCI	1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleUIO	1
com.apple.driver.AppleDiskImages2	276.100.16
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	404
com.apple.kec.InvalidateHmac	1
com.apple.kec.AppleEncryptedArchive	1
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.AppleUSBAudio	640.12
com.apple.iokit.IOAudioFamily	540.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.driverkit.serial	6.0.0
com.apple.iokit.IOAVBFamily	1220.1
com.apple.driver.AppleHSBluetoothDriver	7440.8
com.apple.driver.IOBluetoothHIDDriver	9.0.0
com.apple.driver.AppleHIDKeyboard	7440.3
com.apple.driver.AppleActuatorDriver	7440.9
com.apple.driver.AppleMultitouchDriver	7440.9
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.driver.AppleXsanScheme	3
com.apple.driver.usb.networking	5.0.0
com.apple.nke.ppp	1.9
com.apple.driver.AppleBSDKextStarter	3
com.apple.kext.triggers	1.0
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleSyntheticGameController	11.4.11
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.IOHIDPowerSource	1
com.apple.driver.AppleCallbackPowerSource	1
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.driver.AppleAOPAudio	340.4
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.driver.AppleThunderboltDPInAdapter	8.5.1
com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.1
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.AGXFirmwareKextG14XRTBuddy	1
com.apple.AGXFirmwareKextRTBuddy64	280.3.9
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.driver.AppleTrustedAccessory	1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.DCPDPFamilyProxy	1
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.plugin.IOgPTPPlugin	1240.15
com.apple.driver.AppleCSEmbeddedAudio	740.41
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.iokit.IOGPUFamily	93.40.3
com.apple.driver.AppleMobileApNonce	1
com.apple.driver.DCPAVFamilyProxy	1
com.apple.driver.AppleEmbeddedAudio	740.41
com.apple.iokit.AppleARMIISAudio	340.16
com.apple.driver.IISAudioIsolatedStreamECProxy	340.16
com.apple.driver.ExclavesAudioKext	1
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleHIDTransportFIFO	7440.1
com.apple.driver.AppleHIDTransport	7440.1
com.apple.driver.AppleSPU	1
com.apple.driver.AppleInputDeviceSupport	7440.1
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.AppleSPMI	1.0.1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleSynopsysUSBXHCI	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleT8112TypeCPhy	1
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleSART	1
com.apple.driver.ApplePMGR	1
com.apple.driver.AppleARMWatchdogTimer	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211Family	1200.13.0
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.AppleOLYHAL	1
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleA7IOP-MXWrap-v1	1.0.2
com.apple.driver.AppleThunderboltNHI	7.2.81
com.apple.driver.AppleT6000PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.3
com.apple.iokit.IOPortFamily	1.0
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT602xPCIe	1
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleMCA2-T602x	840.3
com.apple.driver.AppleEmbeddedAudioLibs	340.8
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleH13CameraInterface	8.500.0
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleA7IOP-ASCWrap-v4	1.0.2
com.apple.driver.AppleDockChannel	1
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOTimeSyncFamily	1240.15
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	598
com.apple.iokit.IOBluetoothFamily	9.0.0
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	556
com.apple.iokit.IOUSBMassStorageDriver	245
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOSCSIBlockCommandsDevice	495
com.apple.iokit.IOSCSIArchitectureModelFamily	495
com.apple.driver.AppleRSMChannel	1
com.apple.iokit.IORSMFamily	1
com.apple.driver.AppleLockdownMode	1
com.apple.driver.AppleIPAppender	1.0
com.apple.iokit.IOSkywalkFamily	1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleANELoadBalancer	7.400.0
com.apple.driver.AppleH11ANEInterface	7.400.0
com.apple.driver.IODARTFamily	1
com.apple.AUC	1.0
com.apple.iokit.IOSurface	352.41.7
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleIISController	340.1
com.apple.driver.AppleAudioClockLibs	340.8
com.apple.driver.FairPlayIOKit	71.10.0
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.security.AppleImage4	6.3.0
com.apple.kext.CoreTrust	1
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.Compression	1.0
com.apple.kec.corecrypto	14.0

** Stackshot Succeeded ** Bytes Traced 604166 (Uncompressed 1527840) **
`

### Context

> The issue was macOS sonoma measured invalid amount of capacity(48GB) when coping a file to a NTFS drive mounted with macFUSE when the real size was around only 6GB.  After the 6GB was finished copying a kernal panic occured and the system got restarted automatically.

**Comment by bfleischer** [comment]
The volume capacity is provided by the file system daemon, i.e. NTFS in your case. macFUSE just passes the provided value to the macOS kernel. I assume you are using NTFS-3G. Is that correct?

The backtrace does not hold any evidence that macFUSE might be to blame for the panic. In fact, the backtrace does not contain any macFUSE kernel code. 

Can you reproduce the panic reliably?

**Comment by bfleischer** [comment]
I ran a quick test with the loopback reference file system. As backing storage I used a 1 GB disk image and modified loopback to report a volume size of 10 GB. Then I tried copying a 4 GB test file to the loopback volume. The copy process fails gracefully after around 1 GB has been copied. It makes no difference whether I use Finder or `cp` in Terminal to copy the file.

I don't think the panic was caused by macFUSE. Even if reporting a wrong volume size to the macOS kernel could trigger a panic like this, this would be more of a macOS issue than a macFUSE issue. Unexpectedly running out of disk space during a copy operation is very common.

**Comment by MalinrRuwan** [comment]
> this would be more of a macOS issue than a macFUSE issue.

Your correct it looks like a macOS issue because the wrong amount of volume was determined by macOS. I reproduced it with a EXFat drive and it determined the wrong amount of volume again.
