### ISSUE TITLE
Cannot allow macFUSE 4.6.2 on Intel MacBook Pro on macOS 14.4.1 (23E224)

### ISSUE THREAD

**Issue by needfulthing** [osxfuse/osxfuse#1011]
No matter what I try I'm in an infinite loop with macFUSE not being allowed to execute. Kernel extensions and identified developers are allowed. I installed macFUSE, I allowed the extension, I reboot. The notice in "Privacy & Security" is gone. When I start Cryptomator and enter the vault password, I get an error that the macFUSE extension is not allowed. When I switch to "Privacy & Security", the "System software from 'Benjamin Fleischer' has been updated - Allow" notice re-appeared...

**Comment by bfleischer** [comment]
Please see the troubleshooting guide in the Getting Started document

 https://github.com/macfuse/macfuse/wiki/Getting-Started#troubleshooting-guide

> In case you are prompted to allow loading the macFUSE kernel extension again and again even though you clicked the "Allow" button and restarted your Mac when prompted to, you are running into a macOS bug.
>
> The macFUSE file system bundle contains several kernel extensions to support a wide range of macOS releases. In rare cases macOS picks the wrong extension. As a workaround you can strip the unused extensions from the macFUSE file system bundle by running the following command in Terminal.
>
> /bin/bash <(curl -Ls https://gist.github.com/bfleischer/46dde8226a47f218b4d4eb8a51c50136/raw)
>
> Please note, your user account needs administrative permissions and you will be prompted to enter your login password. Then try mounting the volume again and follow the instructions above.

**Comment by needfulthing** [comment]
Thank you so much, this fixed it. My mistake, somehow I overlooked that part of the troubleshooting guide.
