### ISSUE TITLE
MacFuse on UTM Virtual Guest

### ISSUE THREAD

**Issue by matthiasschroder** [osxfuse/osxfuse#1012]
Hi,

I try to install MacFuse on a VM under UTM, but I get the annoying restart loop ("sytem extension has been changed and needs to be authorised"). I already run the script that is supposed to fix this, but that did not solve the issue.

M2 Pro, macOS 13.6.6, macFuse 4.6.2

**Comment by bfleischer** [comment]
macOS does not support third-party kernel extensions on Apple Silicon Macs in virtual machines using Apple's virtualization framework. In case UTM relies on Apple's frameworks using macFUSE in your VM won't work. This is a limitation of macOS.

**Comment by matthiasschroder** [comment]
Hi Benjamin,

as far as I know UTM does indeed use Apple's virtualization framework. I suspected the issue might be a limitation of the framework, but wanted to make sure that it's not a simple bug somewhere.  Thanks for clarifying this, and also thanks for MacFuse :)

Cheers
