### ISSUE TITLE
Macos 14.4.1 (Apple Silicon) 2 extensions being loaded - authorisation loop

### ISSUE THREAD

**Issue by rysio74** [osxfuse/osxfuse#1013]
Have tried both 4.7.1 and 4.7.2 releases on an M2 Macbook running Sonoma 14.4.1.  Two extensions added as per screenshot, result is infinte loop trying to authorise and rebooting to be presented with same authorisation request.

<img width="451" alt="Screenshot 2024-04-24 at 11 34 56" src="https://github.com/osxfuse/osxfuse/assets/147975144/0ef2d9a9-7e63-4ad0-abb3-35eb9a607125">

**Comment by bfleischer** [comment]
Are you by any chance booting from an external volume or trying to install macFUSE in a virtual machine?

**Comment by rysio74** [comment]
> Are you by any chance booting from an external volume or trying to install macFUSE in a virtual machine?

No to both.  Was working fine on Macos 14.4 but has stopped working on 14.4.1.  Have tried removing all previous extensions  except for 14 in /Library/Filesystems/macfuse.fs/Contents/Extensions but this simply shows the extension with your name and results in same authorisation loop

Rolling back to 4.6.0 seems to have fixed things.  I am guessing this is more down to me updating to a new build of Macfuse.  

From another site - "macFUSE 4.6.0 was not affected because there was only a single kernel extension for Apple Silicon, since macFUSE 4.6.1 there are three."

**Comment by bfleischer** [comment]
You could try having a look at the KextManager logs. They might provide some insights. To access the logs, run `kmutil log show` in Terminal. It will print a ton of logging information. 

macFUSE 4.6.1 addressed a bug which required shipping separate kernel extensions for macOS 11, macOS 12 and macOS 14. Reverting to macFUSE 4.6.0 is not a good option.

**Comment by rysio74** [comment]
[kmutil1.txt](https://github.com/osxfuse/osxfuse/files/15108599/kmutil1.txt)

So this is the output, I have checked and the .kext files are definitely there so not sure what is happening?

**Comment by bfleischer** [comment]
I don't get why the macOS 13 version of the macFUSE kernel extension shows up in your logs. You are running macOS 14, right? Did you try loading the macOS 13 kernel extension manually?

**Comment by rysio74** [comment]
Nope, in fact used the Macos System Settings Macfuse panel to do the upgrade to 4.7.1.

**Comment by GeneralT82** [comment]
Hello together,
I seem to have the same issue as rysio74.
Since I updated to IOS 14.4.1 I have no chance to reactivate the macfuse (Benjamin Fleischer) authorisation. Request pops up again and again.
Is there a solution meanwhile?

**Comment by bfleischer** [comment]
Have you already tried the following instructions from the Getting Started [Troubleshooting Guide](https://github.com/macfuse/macfuse/wiki/Getting-Started#troubleshooting-guide)?

> * In case you are prompted to allow loading the macFUSE kernel extension again and again even though you clicked the "Allow" button and restarted your Mac when prompted to, you are running into a macOS bug. Starting with version 4.7.1, macFUSE contains a workaround for this issue.
>  
>   The macFUSE file system bundle contains several kernel extensions to support a wide range of macOS releases. In rare cases macOS picks the wrong extension. As a workaround you can strip the unused extensions from the macFUSE file system bundle by running the following command in Terminal.
>
>   ```
>   /bin/bash <(curl -Ls https://gist.github.com/bfleischer/46dde8226a47f218b4d4eb8a51c50136/raw)
>   ```
>
>   Please note, your user account needs administrative permissions and you will be prompted to enter your login password. Then try mounting the volume again and follow the instructions above.

**Comment by GeneralT82** [comment]
Thank you @bfleischer :)
After running your command in Terminal it is working!!

**Comment by bfleischer** [comment]
@rysio74 I assume the issue was resolved, so I'm closing the ticket.
