### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by DarrenPIngram** [osxfuse/osxfuse#1014]
Are you, or might you consider, accepting personal donations (however small) for your work which I am using daily?

I did not find an option, but would encourage you to consider it - especially if Github or similar do not make it unviable for you.

**Comment by bfleischer** [comment]
Let's give this try. macFUSE is now on GitHub Sponsors. There should be a sponsor button in the top right corner on https://github.com/macfuse.

**Comment by bfleischer** [comment]
Duplicate of #910

**Comment by DarrenPIngram** [comment]
Seems to work! :)
