### ISSUE TITLE
fuse3 not found while trying to build sshfs with Meson

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [osxfuse/osxfuse#1016]
i have macfuse 4.7.2 installed

![image](https://github.com/osxfuse/osxfuse/assets/30082863/0ed0c1cf-c999-47b8-9d60-e2c472eb169e)

however, when i try to build sshfs with meson;

![image](https://github.com/osxfuse/osxfuse/assets/30082863/756531e4-4674-44eb-8e65-0796d91783cf)

please help

**Comment by bfleischer** [comment]
macFUSE ships libfuse 2.9.9, not libfuse 3.x. Use sshfs 2.10 or an older release.
