### ISSUE TITLE
Unable to install sshfs.

### ISSUE THREAD

**Issue by PiyushX23** [osxfuse/osxfuse#1017]
Hi!

I am new with this but I want to mount my ssh remote server on my finder in macbook. As per the suggestions found on internet. I successfully installed macFUSE by enabling kernel extension to work. macFUSE has installed via brew. In the next part, when I tried to install sshfs via brew. It gives me an error about requirement of Linux.

```
 brew install sshfs
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#################################################################################### 100.0%
sshfs: Linux is required for this software.
libfuse: Linux is required for this software.
Error: sshfs: Unsatisfied requirements failed this build.
```

Please help me with this. Thank you in advance.

**Comment by PiyushX23** [comment]
I got a solution so I am closing the issue.

**Comment by psibre** [comment]
@PiyuSat Could you please post a comment with details on your solution? I'm sure others are running into this issue as well and could benefit from your info. Thanks!
