### ISSUE TITLE
Finder Drag and Drop of files from outside the filesystem inside the filesystem doesn't work/ reading from macFUSE FD returns EIO once

### ISSUE THREAD

**Issue by marius-enlock** [osxfuse/osxfuse#1018]
Hello,

I am using macFUSE version 4.7.2 on OS: Sonoma 14.4.1.

I have two issues that I am trying to solve. I use github.com/hanwen/go-fuse for my custom filesystem, and this is the issue opened on that project: https://github.com/hanwen/go-fuse/issues/516

On my custom filesystem when I use Finder and drag and drop a file from outside of the filesystem inside of the filesystem the above go library fuse server exists because it encounters a syscall.EIO while reading from the file descriptor used to communicate with the macFUSE process. However, if I modify the server code, and simply retry the read once from the FD, I avoid the crash and everything is usable, except that the dragged and dropped file doesn't get copied. Finder returns error code -36. If I try to `command + c` and `command + v` a file in finder, I get error code `-8062` - which I can't seem to find anywhere what it means (the other error codes I could find). 

My first question is: what could cause the syscall.EIO while reading from the FUSE FD? (it happens only in the above scenario).

The second part: While using the loopback FS example from the above go-fuse library, in the exact Finder drag and drop scenario I do not encounter any syscall.EIO, however, the "copied" file has 0 bytes. Finder returns error code -50.

I tried to build the osxfuse/filesystems examples, but they don't support macFUSE, they require osxFUSE.

Is there any example loopback/ passthrough filesystem for macFUSE that you recommend, such that I can pinpoint/ reproduce the Finder drag and drop issue?

Edit:
I have found the demo for macFUSE: https://github.com/macfuse/demo
However I can't perform filesystem writes to the loopback FS.

**Comment by marius-enlock** [comment]
I have managed to use the macfuse/demo loopback fs and copy files with my above scenario (dragging and dropping into the mounted filesystem). It seems I cannot reproduce the issue I am experiencing using the go library.

I am closing the issue.

**Comment by bfleischer** [comment]
Error -36 is sometimes returned when a file's extended attributes cannot be copied. However, there are probably more error conditions resulting in Finder returning error -36.

**Comment by marius-enlock** [comment]
> Error -36 is sometimes returned when a file's extended attributes cannot be copied. However, there are probably more error conditions resulting in Finder returning error -36.

This is eye opening, as I thought it is generic I/O error.
I don't support extended attributes in my implementation.
