### ISSUE TITLE
unsure if macfuse is working (with Humanware package)

### ISSUE THREAD

**Issue by bexgray01** [osxfuse/osxfuse#1019]
hi, i'm not sure if macfuse is working correctly, i've installed both it and the humanware package multiple times following all the steps that i can find, but the folder "Humanware Device" just always appears as empty when i'm sure that it isn't.
Can anyone help please? I'm also a voiceover user if that is causing the issue.
Kind Regards

**Comment by bfleischer** [comment]
I'm sorry, but I have never heard of the Humanware software before. I recommend raising the issue with the Humanware support staff. 

For installing macFUSE, I recommend looking into the Getting Started wiki document at https://github.com/macfuse/macfuse/wiki/Getting-Started. In case you are using an Apple Silicon powered Mac, the most important step is enabling support for third-party kernel extensions in the recovery environment.

**Comment by bexgray01** [comment]
Hi 
Thanks, that’s okay. I’ve contacted them and they said that it should all work but I’ll go into the recovery and check the third party kernel support in the recovery. Hopefully this works 
Thanks so much
:)

**Comment by bexgray01** [comment]
Hi 
I just wanted to let you know that I was able to get it working - I had accidentally not fully set the settings within recovery correctly, I had the “limited security” selected but only one of the two options within that ticked. Enabling both of them has made it work now.
Thanks so much for all your help
