### ISSUE TITLE
Issues w/ loading MacFuse 4.7.2 on MacOSX 14.5

### ISSUE THREAD

**Issue by jmgurney** [osxfuse/osxfuse#1020]
M1 Pro
14.5 (23F79)

I'm seeing similar issue to #1013 , but even after running the script:
```
amac,ttys036,~,501$ls -lR /Library/Filesystems/macfuse.fs/Contents/Extensions
total 0
drwxr-xr-x  3 root  wheel  96 May 18 03:49 14

/Library/Filesystems/macfuse.fs/Contents/Extensions/14:
total 0
drwxr-xr-x  3 root  wheel  96 May 18 03:49 macfuse.kext

/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext:
total 0
drwxr-xr-x  5 root  wheel  160 May 25 19:46 Contents

/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext/Contents:
total 4
-rw-r--r--  1 root  wheel  1634 Apr 23 12:54 Info.plist
drwxr-xr-x  3 root  wheel    96 May 25 19:46 MacOS
drwxr-xr-x  3 root  wheel    96 May 25 19:46 _CodeSignature

/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext/Contents/MacOS:
total 332
-rwxr-xr-x  1 root  wheel  339504 Apr 23 12:54 macfuse

/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext/Contents/_CodeSignature:
total 4
-rw-r--r--  1 root  wheel  2200 Apr 23 12:54 CodeResources
```

I'm still getting issues loading the extension.  I keep getting:
<img width="252" alt="Screenshot 2024-05-25 at 7 54 49 PM" src="https://github.com/osxfuse/osxfuse/assets/13141125/0d198c14-254e-41f6-a50b-8f75959729ab">

The output from `kmutil log show` is 
[kmutil.txt](https://github.com/osxfuse/osxfuse/files/15445912/kmutil.txt)

Note: I have not tried previous versions, but will likely try 4.6.0 since it worked in #1013 .

Thoughts?

**Comment by bfleischer** [comment]
Looking through your log I see many entries about legacy kernel extensions that don‘t even support Apple Silicon Macs. I don‘t think the issue you are running into is caused by macFUSE. Try to remove all unsupported kernel extensions mentioned in the log and then try again.

**Comment by jmgurney** [comment]
Ok, VERY wierd as it appears that removing the old extensions did fix it.  Guess Apple introduced some bugs in their software.
