### ISSUE TITLE
How to sync the content in the mounted folder

### ISSUE THREAD

**Issue by E6ren** [osxfuse/osxfuse#1021]
I mounted fuse file system to mirror a local folder, when file is created or deleted from the local folder, the mounted folder's content should be synchronized. 

I can monitor the contents updated in the local folder, but which method should I call to refresh the fuse folder?

**Comment by marius-enlock** [comment]
Readdir displays the entries in the folder (I am unsure if this the exact method from macFUSE, but it should be similar).
readdir is called when you do `ls` or open Finder and navigate to a folder

You can check here: https://github.com/macfuse/demo/blob/ca5d4b94d97f3b595cbf4975fff03a186305f323/LoopbackFS-C/loopback/loopback.c#L981

Did you implement your custom filesystem, or are you using one of the examples?

**Comment by bfleischer** [comment]
@E6ren The notify function to call depends on the API you are using. Are you using the macFUSE Objective-C API, the high level FUSE API or the low level FUSE API?

**Comment by E6ren** [comment]
> @E6ren The notify function to call depends on the API you are using. Are you using the macFUSE Objective-C API, the high level FUSE API or the low level FUSE API?

I use the macFUSE high level swift API.

**Comment by E6ren** [comment]
> Readdir displays the entries in the folder (I am unsure if this the exact method from macFUSE, but it should be similar). readdir is called when you do `ls` or open Finder and navigate to a folder
> 
> You can check here: https://github.com/macfuse/demo/blob/ca5d4b94d97f3b595cbf4975fff03a186305f323/LoopbackFS-C/loopback/loopback.c#L981
> 
> Did you implement your custom filesystem, or are you using one of the examples?

The Readdir method should be the callback method from macFuse kernel to display the content of a folder. In the loopbackFS demo, I wonder to know when the original file is deleted, how can I sync the content of the mounted mirror folder in time.

**Comment by marius-enlock** [comment]
How I would approach it (without using notify - notify might be the better way but I am not familiar with the method):
Inside your Readdir/ Lookup/ Getattr/Access try to stat the folder on the underlying folder on each call, if there is a path error, then remove the folder from your VFT and return ENOENT

**Comment by E6ren** [comment]
> Readdir displays the entries in the folder (I am unsure if this the exact method from macFUSE, but it should be similar). readdir is called when you do `ls` or open Finder and navigate to a folder
> 
> You can check here: https://github.com/macfuse/demo/blob/ca5d4b94d97f3b595cbf4975fff03a186305f323/LoopbackFS-C/loopback/loopback.c#L981
> 
> Did you implement your custom filesystem, or are you using one of the examples?

The Readdir method should be the callback method from macFuse kernel to display the content of a folder. In the loopbackFS demo, I wonder to know when the original file is deleted, how can I sync the content of the mounted mirror folder in time.

**Comment by marius-enlock** [comment]
I do not know how you built your filesystem. The lookup method is called quite a lot before accessing nodes. If you populate your filesystem tree on the lookup call, you can stat the underlying folder to see if the requested folder name exists. I think what notify does (I might be wrong about macFUSE notify) is to notify the kernel to forget your node and to issue a new lookup call. You can also populate the nodes on the Readdir method - an example of Readdir is to read the entries in the underlying folder (the one where you delete your folder) and return the entries found - the downside of this, is that it is only called when you do `ls` or open the folder in Finder (when syscall.Readdir is called on your mounted folder).

I think in the demo (there is no lookup), readdir enumerates the entries, and then Getattr is called which stats the path.

**Comment by bfleischer** [comment]
@E6ren 

`-[GMUserFileSystem invalidateItemAtPath:error:]` notifies the macOS kernel (and by extension Finder) of remote changes. 

```
/*!
 * @abstract Invalidate caches and post file system event.
 * @discussion Invalidate caches for the specified path and post a file system
 * event to notify subscribed processes, e.g. Finder, of remote file changes.
 * @param path The path to the specified file.
 * @param error Should be filled with a POSIX error in case of failure.
 * @result YES if the caches were successfully invalidated.
 */
- (BOOL)invalidateItemAtPath:(NSString *)path
                       error:(NSError **)error GM_AVAILABLE(3_8);
```

**Comment by E6ren** [comment]
Hi @bfleischer , the `-[GMUserFileSystem invalidateItemAtPath:error:]` parameter path, should I pass the mounted path or the really path? In order to make things simple(maybe less efficient), if I monitored a file was updated under a folder, can I pass the folder's path as the path parameter?
