### ISSUE TITLE
Are there any uninstall instructions?

### ISSUE THREAD

**Issue by flavorgold1** [osxfuse/osxfuse#1023]
I'm looking to uninstall this for now, from one of my machines.

I'm on the latest macOS (14.5 (23F79)).

How do I go about doing this in a clean fashion that doesn't leave behind any remnants?

**Comment by bfleischer** [comment]
Please see https://github.com/macfuse/macfuse/wiki/Frequently-Asked-Questions:

> In order to uninstall macFUSE, download the current macFUSE installer disk image from https://macfuse.io/ or https://github.com/macfuse/macfuse/releases and open it. Then run the Uninstaller app from the Extras folder on the disk image. This will remove macFUSE completely.
