### ISSUE TITLE
Version 4.7.2 incompatible with macOS 15.0 Sequoia (Beta)

### ISSUE THREAD

**Issue by The-Tripper** [osxfuse/osxfuse#1024]
FYI: Sequoia doesn't like macFuse 4.7.2. Is there a way to put it into debug? There's nothing in the logs.

<img width="655" alt="Screenshot 2024-06-11 at 10 18 07 AM" src="https://github.com/osxfuse/osxfuse/assets/134705665/5b14f412-f596-41c1-bb66-565be294331d">

**Comment by bfleischer** [comment]
macFUSE 4.8.0 supports macOS 15.
