### ISSUE TITLE
How to disable file descriptor reuse

### ISSUE THREAD

**Issue by E6ren** [osxfuse/osxfuse#1026]
When use the macFUSE, there is  file descriptor reuse logic, so sometimes the Open callback won't be called. 
But I want to monitor every Open operations to a file, is there anyway to disable the reuse of file descriptor?

**Comment by bfleischer** [comment]
File descriptors are being reused on macOS for technical reasons. This is due to differences between the macOS and Linux kernels. Unfortunately, there is no way to opt out of this behavior.
