### ISSUE TITLE
Is it possible to disable VOL_CAP_INT_EXCHANGEDATA/VOL_CAP_INT_RENAME_SWAP?

### ISSUE THREAD

**Issue by marius-enlock** [osxfuse/osxfuse#1027]
Hello,

Is it possible to set VOL_CAP_INT_EXCHANGEDATA/VOL_CAP_INT_RENAME_SWAP to false and let the system know to not attempt a rename with swap? By returning ENOSYS/ ENOTSUP for calls that have this flags set doesn't seem to help, nor passing to macFUSE the above arguments with the value false.

**Comment by bfleischer** [comment]
Which FUSE API are you using? In case you are using the high-level FUSE API make sure the `renamex` callback is not implemented.

* `VOL_CAP_INT_RENAME_SWAP` is only declared when the file system sets the FUSE init flag `FUSE_RENAME_SWAP`. This happens automatically when the `renamex` callback is implemented.
* macFUSE will only declare `VOL_CAP_INT_EXCHANGEDATA` in case the FUSE init flag `FUSE_EXCHANGE_DATA`  is set. Starting with macOS 11 macFUSE does no longer support (and no longer declare) `VOL_CAP_INT_EXCHANGEDATA`.

**Comment by marius-enlock** [comment]
Hello,

I am unsure what API I am using, I am using a go-library, the mount binary is here:
```
/Library/Filesystems/macfuse.fs/Contents/Resources/mount_macfuse
```
And this is the "library" mount command: https://github.com/hanwen/go-fuse/blob/master/fuse/mount_darwin.go#L29

I suspect I am using the low level API,

I think the opcodes are defined here: https://github.com/hanwen/go-fuse/blob/master/fuse/opcode.go
There is one for Rename2, and I see there is a flag for CAP_RENAME_SWAP - I will try to ~set it to 0~ remove it

**Comment by bfleischer** [comment]
If it does not work, please raise the issue with the go-fuse developer. libfuse (the library shipping with macFUSE) supports opting out of `VOL_CAP_INT_RENAME_SWAP`.

`FUSE_RENAME_SWAP` needs to be set (or not set) in the response to the `FUSE_INIT` message received by go-fuse when mounting the volume.

**Comment by marius-enlock** [comment]
Thank you for the clarification
