### ISSUE TITLE
FR: F2FS support

### ISSUE THREAD

**Issue by catleeball** [osxfuse/osxfuse#1030]
Hi team,

I know this is probably a tall ask, but I wanted to float the idea of adding support for [F2FS](https://en.wikipedia.org/wiki/F2FS).

My particular use case is removable flash media (USB drives and SD cards) that I'd like to format with F2FS to improve lifespan and avoid excessive writes.

The filesystem also has some nice performance characteristics for flash-based storage (see [1](https://www.usenix.org/system/files/atc21-liao.pdf) and [2](https://www.phoronix.com/review/bcachefs-benchmarks-linux67/3) although note that both sources mention F2FS as in comparison to another filesystem), although I'm not sure how relevant that is for a userspace implementation.

Thanks!
Cat

**Comment by bfleischer** [comment]
Hi Cat,

macFUSE is an implementation of the FUSE mechanism for macOS. macFUSE does not ship with any file system implementations. F2FS support would need to be implemented by a third party. If done in form of a FUSE file system, it should work on macOS, Linux and possibly even Windows.

**Comment by catleeball** [comment]
Understood, thank you!
