### ISSUE TITLE
Try to install ext4fuse (Big Sur, fink)

### ISSUE THREAD

**Issue by ouboub** [osxfuse/osxfuse#1031]
I am on Big Sur, running fink. I since I have had bad experience with hfs+ (no journaled) on external disks, I wanted to give ext4 a try and followed the explanations found in [mounting-ext4-linux-usb-drive-on-macos-2024](https://www.jeffgeerling.com/blog/2024/mounting-ext4-linux-usb-drive-on-macos-2024). His instruction are for `brew` which indeed seems to install something additional to just simply download MacFuse from [MacFuse Download](https://osxfuse.github.io/)

In any case I did install MacFuse via the above download (see the screenshot)
<img width="603" alt="MacFuse" src="https://github.com/user-attachments/assets/36ca57bc-f37a-4a26-8807-09da1075370b">

So I have cloned `git clone https://github.com/gerard/ext4fuse.git` and run `make`

However I obtain the following error:

```
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
cc -o ext4fuse fuse-main.o logging.o extents.o disk.o super.o inode.o dcache.o op_read.o op_readdir.o op_readlink.o op_init.o op_getattr.o op_open.o 
Undefined symbols for architecture x86_64:
  "_fuse_main_real", referenced from:
      _main in fuse-main.o
  "_fuse_opt_free_args", referenced from:
      _main in fuse-main.o
  "_fuse_opt_parse", referenced from:
      _main in fuse-main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ext4fuse] Error 1
```

my problem is: I don't know where fuse, is located, `which fuse` did not return anything.

Any suggestions?

Thanks

Uwe Brauer

**Comment by bfleischer** [comment]
You need to set the `PKG_CONFIG_PATH` environment variable as stated in the error message. The following should do the trick.

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```
