### ISSUE TITLE
Installation on virtual machine running macOS 15 beta fails

### ISSUE THREAD

**Issue by 46lupo** [osxfuse/osxfuse#1032]
Great work - have been using osxfuse/macfuse for many years now. Keep it up.

Is there a way to test macfuse on a macos15 Beta (24A5327a) running on a VM (on UTM)? 
KEXT ist prohibited by systemkernel - therefore after startup it loops in authorization request.
The workaround found on #1013 doesn't work for me. Manual attempt to load the KEXT also errors ...

**Comment by bfleischer** [comment]
Third party kernel extensions are unsupported on virtual machines. This is a macOS limitation, not a macFUSE limitation. You'll have to install the macOS 15 Beta on an actual Mac to test macFUSE on macOS 15.
