### ISSUE TITLE
macFUSE 4.7.1 on new MACOS

### ISSUE THREAD

**Issue by perhansen2** [osxfuse/osxfuse#1034]
Will macFUSE 4.7.1 work on the new macOS Sequoia ?

**Comment by bfleischer** [comment]
No, but macFUSE 4.8.0 does. Why would you like to stay on 4.7.1?

**Comment by perhansen2** [comment]
Thank you for  your  prompt responding. I have upgraded to 4.8.0 today. Wanted to postpone leaving 4.7 as I had some difficulties with last upgrade. This one worked like a charm.
