### ISSUE TITLE
not find system file after install 

### ISSUE THREAD

**Issue by liangxiwei** [osxfuse/osxfuse#1035]
mac M1 
system: max OS 13.4

I install osxfuse with release dmg file and it look like installed.

when I input command: pkgutil --pkgs | grep fuse
`io.macfuse.installer.components.core
io.macfuse.installer.components.preferencepane`

but my filesystem dose not have any file about osxfuse,why?
<img width="719" alt="image" src="https://github.com/user-attachments/assets/603b628a-c278-4a0e-b661-4db40501a49d">

**Comment by bfleischer** [comment]
macFUSE lives in `/Library/Filesystems` not `/System/Library/Filesystems`
