### ISSUE TITLE
How to get notification when unmount failed

### ISSUE THREAD

**Issue by E6ren** [osxfuse/osxfuse#1036]
Now in macFUSE already have notification `kGMUserFileSystemMountFailed` to notify the client mount failed, but how about unmount failed, e.g., I keep a file opened in the mounted file system and try to unmount the file system, the unmount operation will failed, but there is no way to know.

**Comment by bfleischer** [comment]
There is no "unmount failed" notification. Can you explain the motivation for such a notification and maybe provide one or two examples of how you would use it? How would you react to failed unmount attempts?

**Comment by E6ren** [comment]
I create a APP that allow user mount his filesystem when he login. But when he logout, I need unmount all filesystem he has mounted, so I will call `GMUserFileSystem unmount` to unmount them. But sometimes, it will be failed, such as a file is open in the filesystem, then I will tell the user to check if file in filesystem not closed, and try logout again.

**Comment by bfleischer** [comment]
You could use the `unmount(2)` command instead of `[GMUserFileSystem unmount]`. `umount(2)` returns an error code in case the unmount operation fails.
