### ISSUE TITLE
[iMac M3 - MacOS 14.6 -  MacFUSE 4.8.2] Does not have the "Security Policy…" button when starting the Recovery environment 

### ISSUE THREAD

**Issue by QuynhNhuNGUYEN** [osxfuse/osxfuse#1040]
Hi all,

When I restart my Mac and press the power button, I can Select the macOS volume but I don't have the "Security Policy…" button. So I can't select "Reduced Security" and enable "Allow user management of kernel extensions from identified developers". 

Could you please tell me what is wrong and how to fix it.

Regards

**Comment by ghost** [comment]
hi. have you already gotten an answer? I can´t seem to find utilities neither other than disk utilities which I have no use for in this regard.

https://www.youtube.com/watch?v=OOrANuPJH_k

comprehensive guide seemingly.

**Comment by QuynhNhuNGUYEN** [comment]
Hi @Suxxilly ,
Unfortunately, I have not gotten any answer!
Many thanks for the Youtube guide!

**Comment by bfleischer** [comment]
@QuynhNhuNGUYEN After selecting the volume you want to enable the reduced security mode on and entering your admin credentials when prompted to, there should be a "Utilities" menu in the menu bar of the recovery environment. In the "Utilities" menu should be an entry "Startup Security Utility".

You can find a Getting Started guide in the wiki: https://github.com/macfuse/macfuse/wiki/Getting-Started

**Comment by ghost** [comment]
When the menu bar isn’t visible , like with my screen it is not so obvious. Happy where I can help.

**Comment by bfleischer** [comment]
@QuynhNhuNGUYEN I assume you were able to resolve the issue. If not, feel free to reopen the issue.

**Comment by QuynhNhuNGUYEN** [comment]
Dear @Suxxilly and @bfleischer ,

Sorry I couldn't answer you sooner because I was out of office. 

I have just followed the instructions step by step. That works like a charm now.

I am really grateful for your help. Thanks!
