### ISSUE TITLE
Bug System Extension BlockedSystem Extension Blocked

### ISSUE THREAD

**Issue by noah8627** [osxfuse/osxfuse#1041]
My machine is Macmini M4,System Version is sequoia15.1
When I completed the relevant settings and executed the mount command, I was repeatedly reminded that the system extension needed to be updated. When I authorized a restart, the same message still popped up.

**Comment by noah8627** [comment]
![image](https://github.com/user-attachments/assets/4182f352-eb48-44a6-a4d6-121973c8da97)

**Comment by bfleischer** [comment]
Are you trying to use macFUSE in a virtual machine or did you maybe boot from an external volume?

**Comment by noah8627** [comment]
Yes, I installed the Mac system on a mobile hard drive. Will this affect the use of the software?

**Comment by noah8627** [comment]
But I already have it in the mobile hard drive reduced security.This may be affected by the system version? I have seen that many applications are not compatible with the latest version of Mac.

**Comment by bfleischer** [comment]
macOS does not support loading third party kernel extensions when booting from an external volume. This is a macOS limitation, not a macFUSE limitation.

**Comment by noah8627** [comment]
Ok, it was my mistake, thanks for your reply
