### ISSUE TITLE
Invalid `crtime` value provided in `fuse_setattr_in`

### ISSUE THREAD

**Issue by FirelightFlagboy** [osxfuse/osxfuse#1042]
## Version used

```
macFuse: 4.8.3
macOS: 14.7.1
```

## Prelude

I'm investigating a bug where during a Drag&Drop file to a mount point, it raise a SetAttr event with an invalid `crtime` value.
I was able to detect that bug used a Rust program using the [`fuser`](https://crates.io/crates/fuser)

That crate interact with macFuse using the low-level file descriptor.

## My investigation

I've added trace log to see the value receive by `fuser` from the mount point, I get the following raw value:

```
00000000: 0000 0010 0000 0000 0000 0000 0000 0000  ................
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 804f da83 ffff ffff  .........O......
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

If mapped to `fuse_setattr_in`, we get that `.valid` is set to the value `0x10000000` (which correspond to setting the flag `FATTR_CRTIME`) 
and `.crtime` to the value `0xffff83da4f80` (which correspond to the value `18446744071626706816`, that translate to the date `2554-07-21T23:34:31.626Z`)

The value `0xffff83da4f80` seems to be consistent between different files.

> If required, I can provide additional information

## What I'm expecting

I would expect that either `macfuse`:

- do not raise the `setattr` event
- raise it with a valid `crtime`
- raise it with `FATTR_CRTIME` unset in `.valid`

**Comment by bfleischer** [comment]
I don't think this is a macFUSE issue, at least not with regard to the `FUSE_SETATTR` message sent by the kernel extension.

The macFUSE kernel extensions simply passes the `crtime` value received from the kernel to the file systems daemon running in user space. The seconds part of the `crtime` value is not altered in any way. The nanosecond part might be truncated, due to the kernel using a 64bit integer internally, but the FUSE ABI only providing a  32bit integer to pass the value to user space.

I did a quick test with the LoopbackFS reference file system and the `crtime` is correct after dragging a file to the virtual volume. Assuming `crtime` is not already off before dragging the file to your virtual volume it might be worth investigating the `FUSE_GETATTR` response sent from user space.

**Comment by FirelightFlagboy** [comment]
Hello, thank you for your feedback.

Following your reply, I've added some more log to see the `fuse_attr` that will be returned to macFuse.

I get the following attribute during the file creation and the following `getattr` prior to the bugeous `setattr`:

```rust
fuse_attr { 
  ino: 3, 
  size: 0, 
  blocks: 0,
  atime: 1732615774,
  mtime: 1732615774,
  ctime: 1732615774,
  crtime: 1732615774,
  atimensec: 919269000,
  mtimensec: 919269000,
  ctimensec: 919269000,
  crtimensec: 919269000,
  mode: 33188,
  nlink: 1,
  uid: 505,
  gid: 20,
  rdev: 0,
  flags: 0,
  blksize: 1048576,
  padding: 0 
}
```

> Everything looks to be in order here 🤔

**Comment by bfleischer** [comment]
Are you able to reproduce the issue with the LoopbackFS-C reference file system (https://github.com/macfuse/demo)?

**Comment by bfleischer** [comment]
Do you see a `fuse_getxtimes_out` message sent from user space to the kernel? There are two ways of passing the create time to the kernel. One is `fuse_getattr_out` and the other is `fuse_getxtimes_out` (`FUSE_GETXTIMES`).

**Comment by FirelightFlagboy** [comment]
> Are you able to reproduce the issue with the LoopbackFS-C reference file system (https://github.com/macfuse/demo)?

I'm able to run the demo on my side, but since it uses the high level API I cannot inspect the `struct fuse_attr`

> Do you see a `fuse_getxtimes_out` message sent from user space to the kernel? There are two ways of passing the create time to the kernel. One is `fuse_getattr_out` and the other is `fuse_getxtimes_out` (`FUSE_GETXTIMES`).

I have run the demo with the flag debug set (`-d`), I'm seeing notably the `CREATE`, `GET{X,}ATTR`, `SET{X,}ATTR` from the stderr output.
But the debug information displayed doesn't contain the `crtime`

**Comment by FirelightFlagboy** [comment]
I've added some debug print in the setattr method in the demo and I get the following output

```
Setting crtime for /[redacted]/foobar to -2082844800.0 (ffffffff83da4f80.0)
```

> I'm getting the same value as with my example using the `fuser` crate

**Comment by bfleischer** [comment]
Apple timestamps are the time elapsed after Jan 1, 1904 in seconds. 2,082,844,800 seconds is the time difference between  Jan 1, 1904 and Jan 1, 1970 UTC in seconds (UNIX timestamps). I still don't know where the value I coming from, though.

**Comment by bfleischer** [comment]
From what I can tell, the macFUSE kernel extension works as expected. When dragging a file to the FUSE volume a `DesktopServicesHelper` process is launched by macOS. This process creates the file on the FUSE volume, then sets the file's `crtime` to the begin of the macOS epoch which is -2,082,844,800 in UNIX time. Before terminating, the `DesktopServicesHelper` sets the file's `crtime` to the expected value.

**Comment by FirelightFlagboy** [comment]
That's an explanation that I find satisfactory :smile: 

That explain the first setattr that I find "bugeous" 

Thanks you for your time :+1:
