### ISSUE TITLE
Where is SSHFS 2.10 (3ea4c59) from?

### ISSUE THREAD

**Issue by cross** [osxfuse/osxfuse#1044]
I'm concerned to see a new SSHFS listed at https://macfuse.github.io, with _no_ information about what SSHFS that is or where it comes from.  I can find am abandoned SSHFS at https://github.com/libfuse/sshfs/releases/ but it's clearly not from there.  I also see the ancient 2.5.0 at https://github.com/osxfuse/sshfs/releases which is what's still linked on the wiki page here.

Where does this particular 2.10 come from?  Please provide information about the source, so we can evaluate who owns and is maintaining it before installing it on our systems.  Thank you.

**Comment by bfleischer** [comment]
The official SSHFS repository is https://github.com/libfuse/sshfs. All macOS specific modifications from the old https://github.com/osxfuse/sshfs repository have been merged into the upstream repository. 

The SSHFS 2.10 binary listed on https://macfuse.github.io has been built and signed by me. The build is notarized. It is hosted in the upstream repository at https://github.com/libfuse/sshfs/releases/tag/sshfs-2.10. 3ea4c59 stands for [commit 3ea4c59](http://github.com/libfuse/sshfs/commit/3ea4c59) in [branch sshfs_2.x](https://github.com/libfuse/sshfs/tree/sshfs_2.x). 

The old repository https://github.com/osxfuse/sshfs will be archived eventually. I'm in the process of closing issues. Future development will continue in the upstream repository.

I'm an outside collaborator on the upstream repository. As far as I know it is owned by @Nikratio. However, I don't know if there are other members in the libfuse organization as the member list is not public. I do not have a list of all outside collaborators on the repository.

**Comment by bfleischer** [comment]
I've update the wiki: https://github.com/macfuse/macfuse/wiki/File-Systems-%E2%80%90-SSHFS

Feel free to ask, in case you have more questions.

**Comment by cross** [comment]
Thanks.  It's still a little confusing, as when I went there I found 3.7.3 (nothing like 2.10), and it was posted in 2022 with a statement that it was the last release and the maintainer was not going to continue.
https://github.com/libfuse/sshfs/releases/tag/sshfs-3.7.3
So, that repository _looks_ dead, just from a "see when the last release was" approach.

Looking at the updated wiki, thank you.  However you do mention that primary repos releases section has this, but it does not.  If you look at the releases there, it's only 3.x stuff.  If I _search_ for 2.10 I'm unfortunately met with this discouraged maintenance release from 2017.  ;-)

https://github.com/libfuse/sshfs/releases?q=2.10&expanded=true

It's a little unclear, and while I'm not worried now that I have the explanation above, I think that it may still be a little confusing and/or concerning to anyone looking carefully.

**Comment by bfleischer** [comment]
SSHFS 3.x requires libfuse 3. libfuse 3 has not been ported to macOS, yet. This means the latest version of SSHFS that is compatible with macOS is SSHFS 2.10 (as of writing this). SSHFS 2.10 has been released in 2017.

The current SSHFS maintainer is looking to step down as maintainer of the project. The project is not dead, though.

**Comment by cross** [comment]
> SSHFS 2.10 has been released in 2017

I hear what you're saying, but "last released in 2017" just sounds eerily similar to "dead". ;-). Thanks again for all your info.
