### ISSUE TITLE
Lion Error -36

### ISSUE THREAD

**Issue by chudux** [osxfuse/osxfuse#13]
I'm trying to configure OSXFUSE and MacFusion to mount FTP shares on the desktop.
Everything works fine up to the point of writing to the FTP.  I get an Error -36.  After the error a file file shows up with the correct name, but it has a files size of 0.
OSXFUSE and MacFusion seemed to only mount the shares when OSXFUSE is  installed with the compatibility layer.

Thanks!

**Comment by ahl** [comment]
I wanted to confirm for any other unhappy souls out there that @jav4 was dead on. I was seeing error -36 from the Finder when copying files. Implementing chown/chmod/utimes fixed the problem for me.
