### ISSUE TITLE
Please serve binaries from GitHub, not SourceForge.

### ISSUE THREAD

**Issue by manastungare** [osxfuse/osxfuse#134]
SourceForge’s download servers are extremely slow, and require users to sit through a forced delay of 10+ seconds and watch a video ad.

sshfs-\*.pkg is already being served from GitHub, so hopefully it should be easy to serve osxfuse-\*.pkg from here too.

Thanks for your consideration.

**Comment by gabriel** [comment]
Sourceforge is kind of shady and it's not serving over https. Given that fuse installs a kernel module this doesn't seem safe?

http://arstechnica.com/information-technology/2015/06/sourceforge-locked-in-projects-of-fleeing-users-cashed-in-on-malvertising/

**Comment by bfleischer** [comment]
osxfuse 3 will be back on GitHub. The first pre-release version is  already available in GitHub's releases section.

> Sourceforge is kind of shady and it's not serving over https. Given that fuse installs a kernel module this doesn't seem safe?

The SHA1 of each binary release can be found on the osxfuse website. For version 2.7.5 see http://osxfuse.github.io/2015/02/07/OSXFUSE-2.7.5.html. 

In addition to that the included installer package is digitally signed. You can check the signature after opening the installer by clicking on the lock symbol in the upper right corner of the installer window. It should read "Developer ID Installer: Benjamin Fleischer". If it does not, don't install the package.

If you check the SHA1 or the signature of the installer package you should be reasonably safe.

osxfuse's update mechanism (preference pane) verifies updates before installing them. It is the easiest way to make sure you get unaltered and authentic updates.

**Comment by bfleischer** [comment]
Starting with osxfuse 3 releases are back on GitHub.
