### ISSUE TITLE
OSX Mavericks cannot copy large files

### ISSUE THREAD

**Issue by ivenhov** [osxfuse/osxfuse#136]
My filesystem fails under Mavericks with error when trying to copy 6GB file
The item “xyz” can’t be copied because it is too large for the volume's format.
The same file can be copied on OSX 10.7.5 with no problems.

My mount options
"-oiosize=" + (128 * 1024), 
"-oallow_other", 
"-odefer_permissions", 
"-oping_diskarb", 
"-ofsname=VOLUME_NAME", 
"-ovolname=VOLUME_NAME,volicon=VOLUME_ICON",

**Comment by bfleischer** [comment]
I just performed a quick test with osxfuse 2.7.5 and the loopback file system on OS X 10.10. Copying a 6 GB file to the loopback volume worked fine. Please reopen the ticket if this is still an issue.
