### ISSUE TITLE
Used space not updated in Finder

### ISSUE THREAD

**Issue by ivenhov** [osxfuse/osxfuse#137]
I'm using higher level of OSXFUSE on Mavericks
After writing 3GB file I don't see changes of capacity in GetInfo for the volume. Opened window shows original used capacity.
I launched df -h on Terminal and that shows updated values.
I hacked my filesystem in statfs to return half of the previous used capacity and those changes are visible via df -h but not in Finder's Get Info window.

Any idea what s going on? I think it was working pre-Maverick
I'm using OSXFuse 2.6.2.

**Comment by bfleischer** [comment]
A lot has changed since version 2.6.2, so I'm going to close this ticket. Feel free to re-open it if you are still seeing the issue with osxfuse 3.2.0.
