### ISSUE TITLE
Finder "Application can't be found" error

### ISSUE THREAD

**Issue by alisookasa** [osxfuse/osxfuse#140]
Sometimes I get "The application can't be found" error message right after mounting an OSXFUSE local volume. Restarting finder solves the issue. 

Have you seen this before?

When the problem happens, the only calls I see in the FS callbacks are for attributesOfItemAtPath() followed by a finder pop-up message saying "The application can't be found".

If I try to open the file from the application directly (for example, opening a png file directly from preview app) it works fine.

I also looked into dmesg output, I see the following:

> ```
>     0 [Level 3] [Facility com.apple.system.fs] [ErrType IO] [ErrNo 3] [IOType Read] [PBlkNum 0] [LBlkNum 0] 
>     0 [Level 3] [Facility com.apple.system.fs] [DevNode Sookasa@osxfuse0] [MountPt /Users/ali/Dropbox (Sookasa)/Sookasa] [Path /Users/ali/Dropbox (Sookasa)/Sookasa/data/20120417151741/18333fig0105-tn.png]
> ```

We use the following arguments to mount (objective-c, XCODE 5.1.1)

> ```
> NSString* volArg = [NSString stringWithFormat:@"volicon=%@", [[NSBundle mainBundle] pathForResource:@"folder_icon" ofType:@"icns"]];
> [options addObject:volArg];
> [options addObject:[NSString stringWithFormat:@"volname=%@", [mountPath lastPathComponent]]];
> [options addObject:@"entry_timeout=0.0"];
> [options addObject:@"attr_timeout=0.0"];
> [options addObject:@"negative_timeout=0.0"];
> [options addObject:@"novncache"];
> [options addObject:@"auto_cache"];
> [options addObject:@"local"]; // also tried non-local drive, I got the same error
> ```

Machine info: OSX 10.9.3
OSXFUSE: 2.6.4

**Comment by bfleischer** [comment]
Please re-open the ticket if this is still an issue on a recent version of macOS with the latest version of FUSE.
