### ISSUE TITLE
sshfs requires libfuse.2.dylib

### ISSUE THREAD

**Issue by theschles** [osxfuse/osxfuse#15]
Hi there,

I installed OSXFuse on my Snow Leopard.  When I then try to use sshfs, it complains that I need libfuse.2.dylib:

$ sshfs
dyld: Library not loaded: /usr/local/lib/libfuse.2.dylib
  Referenced from: /usr/local/bin/sshfs
  Reason: image not found
Trace/BPT trap

Here is my /usr/local/lib:

$ ls -l /usr/local/lib/
total 1392
drwxr-xr-x  84 theschles  access_bpf    2856 Sep 11 08:56 codecs
lrwxr-xr-x   1 root       wheel           26 Dec  5 11:17 libosxfuse.2.7.3.dylib -> libosxfuse_i64.2.7.3.dylib
lrwxr-xr-x   1 root       wheel           22 Dec  5 11:17 libosxfuse.2.dylib -> libosxfuse_i64.2.dylib
lrwxr-xr-x   1 root       wheel           20 Dec  5 11:17 libosxfuse.dylib -> libosxfuse_i64.dylib
lrwxr-xr-x   1 root       wheel           17 Dec  5 11:17 libosxfuse.la -> libosxfuse_i64.la
lrwxr-xr-x   1 root       wheel           22 Dec  5 11:17 libosxfuse_i32.2.7.3.dylib -> libosxfuse_i32.2.dylib
-rwxr-xr-x   1 root       wheel       334600 Sep  7 14:00 libosxfuse_i32.2.dylib
lrwxr-xr-x   1 root       wheel           22 Dec  5 11:17 libosxfuse_i32.dylib -> libosxfuse_i32.2.dylib
-rwxr-xr-x   1 root       wheel          990 Sep  7 14:00 libosxfuse_i32.la
lrwxr-xr-x   1 root       wheel           22 Dec  5 11:17 libosxfuse_i64.2.7.3.dylib -> libosxfuse_i64.2.dylib
-rwxr-xr-x   1 root       wheel       334632 Sep  7 14:00 libosxfuse_i64.2.dylib
lrwxr-xr-x   1 root       wheel           22 Dec  5 11:17 libosxfuse_i64.dylib -> libosxfuse_i64.2.dylib
-rwxr-xr-x   1 root       wheel          990 Sep  7 14:00 libosxfuse_i64.la
drwxr-xr-x   4 root       wheel          136 Dec  5 11:17 pkgconfig

I tried symlinking libosxfuse.2.dylib as libfuse.2.dylib, but then whenever I mount using sshfs, the mounted directory (/Volumes/blah) disappears.  I can see it with "ls", but "ls -l" complains the file or directory does not exist.

Help?!

**Comment by NesheR16** [comment]
+1
worked for me
