### ISSUE TITLE
Raising max OSXFUSE_NDEVICES ? 

### ISSUE THREAD

**Issue by paulp** [osxfuse/osxfuse#152]
I am using [afuse](https://github.com/pcarrier/afuse) in conjunction with [fuse-zip](https://code.google.com/p/fuse-zip) to auto-fuse-mount a directory full of jars. Somewhat to my surprise, this works. At least, it does for the first 24 or so jars, after which it's
```
ls: logc.jar: Device not configured
ls: lombok-1.12.5.jar: Device not configured
...
```
This appears to be a consequence of this fixed limit:
```
/*
 * This is the number of /dev/osxfuse<n> nodes we will create. <n> goes from
 * 0 to (OSXFUSE_NDEVICES - 1).
 */
#define OSXFUSE_NDEVICES                        24
```
Can this limit be raised or circumvented? Simply doing an ls in the automount directory leads to all the corresponding jars being mounted and the subsequent errors. I can see why 24 sounds like a lot of filesystems to be fuse-mounting from a traditional "each one is a physical disk" standpoint, but file systems in user-space are typically virtual and it's easy to have a lot of virtual entities.

I am hoping to avoid having to write a meta-filesystem to do the same job.

**Comment by rkrug** [comment]
Is there any chance that this can be addressed? I am in a similar situation and would like to mount a few hundred squashfs?

**Comment by ratson** [comment]
Is there any workaround about this? or it has to be changed in compile time?

**Comment by misku** [comment]
Unfortunately compile time only at the moment. It's easy however to make it a mount parameter, but I'm not sure how osxfuse would behave with hundreds of heavily used mounts. Each mount requires a new device.

**Comment by ratson** [comment]
It will be good enough if it could be done during mount.
I think the limit should not be strictly imposed unless it is limited by the system.
24 seems a arbitrary constant (correct me if I am wrong), it should be worth to find out a correct limit.

**Comment by paulp** [comment]
> how osxfuse would behave with hundreds of heavily used mounts

Is that really the question? I would expect the dominant use case to be hundreds of *working* mounts, of which a handful are being used at any given time. If someone needs hundreds of heavily used filesystems and osxfuse can't handle it, well they will have run into that new limitation, but it would still represent significant progress for those with more modest requirements.
