### ISSUE TITLE
pref. pane says "osxfuse does not appear to be installed" after apparently successful installation

### ISSUE THREAD

**Issue by TimFH** [osxfuse/osxfuse#156]
I just installed osxfuse 2.7.0 on a PowerPC running 10.5.8, and it says the install was successful, but even after a reboot on opening the Preference Pane it says "osxfuse does not appear to be installed". Installing from the Preference Pane also appears to be successful, but does not help. And of course it does not see the ext4 disk I want to mount over USB. Help!

**Comment by bfleischer** [comment]
OSXFUSE 2.7.4 restores G5 support. Please check again with the new version and reopen the issue if the preference pane keeps telling you that osxfuse does not seem to be installed.
