### ISSUE TITLE
Not enough space left on SSHFS mount

### ISSUE THREAD

**Issue by serbani** [osxfuse/osxfuse#157]
Hi,

I'm using OSXFUSE 2.7.0 with SSHFS 2.5.0 to mount a remote directory under OSX 10.9.4 from a NAS using the command:

sshfs user@host:/ Nas/ -o allow_root,auto_cache,reconnect,defer_permissions,noappledouble,workaround=rename,volname=Nas

When I try to copy a set of files using Finder or command line cp I get an error saying that there's not enough space. The free space on the remote is around several TB and I try to copy something under 1 GB.

df -h reports:
Filesystem     Size   Used  Avail Capacity iused    ifree     %iused  Mounted on
user@host:/  2.3Gi  1.9Gi  335Mi    86%   49642   106006   32%   /Users/user/Nas

I know that sftp doesn't support the reporting free space but the FAQ says something about a 1TB hardcoded value which in this case seems to be 2.3Gi. I'm using the SSHFS for a while but this is the first time I see this issue. Is there anything I can do about it, some mount option that I'm missing?

I've tried mounting without any options or in a different directory but I get the same results.

Let me know if I can provide any other information about this.

Thanks,
Serban

**Comment by loom1** [comment]
I am having the same problem where finder reports that "there isn’t enough free space."
The directory I have mounted is a scratch filesystem with 10PB free space, but Get Info
shows Zero bytes.
I am using:
sshfs myname@example.ca:/scratch/myname MountFolder -o auto_cache,reconnect,defer_permissions,noappledouble -o allow_other
