### ISSUE TITLE
Spotlight does not start indexing automatically

### ISSUE THREAD

**Issue by loderunner** [osxfuse/osxfuse#158]
OSXFUSE-based filesystems can be indexed with Spotlight but the indexing does not start automatically like it does for HFS+ or FAT.

I can enable the indexing using
```
sudo mdutil -i on /Volumes/Volname
```
and it works perfectly.

Can OSXFUSE be built to automatically be indexed upon mount?

**Comment by bfleischer** [comment]
To my knowledge there is no specific flag osxfuse could set to get Spotlight to start indexing automatically. By default indexing is disabled for third-party file systems.

osxfuse can be used to build all kinds of file systems. It might not be a good idea to enable indexing for network file systems automatically. I think it would be best to let the user or the developer of a specific file system decide whether to enable Spotlight or not.
