### ISSUE TITLE
Remove button seems to miss some files

### ISSUE THREAD

**Issue by hamiltont** [osxfuse/osxfuse#160]
This may be just my setup, but it also may not so here's a bug report ;-). I still had files left over in `/usr/local/include/osxfuse` after using the remove button, which is problematic because that's exactly where Homebrew is looking to see if osxfuse is installed. 

Also, does the remove button not unload + delete the kernel extension?

**Comment by bfleischer** [comment]
The uninstall script tries to unload the kernel extension. However, unloading will not work unless all FUSE volume have been unmounted before.

I do not know why `/usr/local/include/osxfuse` has not been removed. It certainly should have been. Many osxfuse updates have been released in the meantime, so I'm going to close the issue. Feel free to re-open it if you are still running into the issue with the most recent version of osxfuse.
