### ISSUE TITLE
Does OSXFUSE support character files?

### ISSUE THREAD

**Issue by royvandewater** [osxfuse/osxfuse#164]
I noticed the https://github.com/osxfuse/fuse/ master branch contains the https://github.com/osxfuse/fuse/blob/master/include/cuse_lowlevel.h file, but that the 2.7 branch used in osxfuse does not. Is it still possible to create character files (http://en.wikipedia.org/wiki/Device_file#Character_devices) without that?

**Comment by bfleischer** [comment]
CUSE is not supported.

**Comment by andlabs** [comment]
What would be needed to add support for it? I'd like to be able to make a character device for various reasons, and I'm not quite sure where to start with building such a kernel extension myself (I bought the Amit Singh book at least). Thanks!
