### ISSUE TITLE
realpath(2) on OSXFuse volume

### ISSUE THREAD

**Issue by christianpraher** [osxfuse/osxfuse#165]
Hi everyone,

when I do a realpath(2) on my OSXFuse volume the realpath call does not "fully normalize" the entire path. Although the basic realpath functionality like symlink resolution, etc. works as expected the case (lower- uppercase) is not as on the underlying file system (I'm using the subdir module).

As an example:
- My file system is mounted on "/Volumes/myfs" which points to (via the subdir module) "/dir"
- There is a sub directory on "/dir" named "subdir" (all lower case)
- Now if a do a realpath("/dir/SUBDIR") I get "/dir/subdir" (the directory is in lower case)
- If I do this via the mount point with realpath("/Volumes/myfs/SUBDIR") it returns "/Volumes/myfs/SUBDIR" without correctly considering the case.

The underlying file system is "MacOS Extended (Journaled)" (so not case sensitive). 
I also tested with other commercial grade OSXFuse based applications and noticed that they "suffer" from the same condition.

Is there an operation the file system must implement in order for this to work (maybe getattrlist(2))?
Or is there a FUSE option that may fix this?

Also I read that OSXFuse 2.7.1 added support for case-(in)senstive file systems. Could this help here?

Thanks,

Christian

**Comment by bfleischer** [comment]
Is this issue still reproducible with the latest version of FUSE for macOS?

**Comment by torarnv** [comment]
I can reproduce this with sshfs on macOS 10.15

**Comment by torarnv** [comment]
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.8.2
FUSE library version: 2.9.7

**Comment by torarnv** [comment]
```
❯ cat ./realpath.c
// realpath.c: display the absolute path to a file or directory.
// Adam Liss, August, 2007
// This program is provided "as-is" to the public domain, without express or
// implied warranty, for any non-profit use, provided this notice is maintained.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libgen.h>
#include <limits.h>

static char *s_pMyName;
void usage(void);

int main(int argc, char *argv[])
{
    char
        sPath[PATH_MAX];


    s_pMyName = strdup(basename(argv[0]));

    if (argc < 2)
        usage();

    printf("%s\n", realpath(argv[1], sPath));
    return 0;
}

void usage(void)
{
    fprintf(stderr, "usage: %s PATH\n", s_pMyName);
    exit(1);
}

❯ ls -l
total 40
-rw-r--r--  1 torarne  staff      0 Jan 16 16:36 UPPERCASE.txt
-rw-r--r--  1 torarne  staff      0 Jan 16 16:36 lowercase.txt
-rwxr-xr-x  1 torarne  wheel  13068 Jan 16 16:38 realpath
-rw-r--r--  1 torarne  wheel    701 Jan 16 16:38 realpath.c

❯ ./realpath uppercase.txt
/Users/torarne/tmp/realpath-test/UPPERCASE.txt

❯ mkdir ~/tmp/realpath-mount

❯ sshfs localhost:/Users/torarne/tmp/realpath-test ~/tmp/realpath-mount

❯ ./realpath ~/tmp/realpath-mount/uppercase.txt
/Users/torarne/tmp/realpath-mount/uppercase.txt

❯ sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.10.3
FUSE library version: 2.9.7
fuse: no mount point
```

**Comment by torarnv** [comment]
Is this a problem in OSXFUSE, or in sshfs?
