### ISSUE TITLE
No Sample/guide for cloud filesystem ?

### ISSUE THREAD

**Issue by vishnu-sharma** [osxfuse/osxfuse#166]
Hello,
In the sample of OSXFuse there is a sample loofbackFS that mount a local file system and load data from there.  This sample just pick the content list from the local FS and passes it to OSXFuse when the FS ask for attribute for any item it just take the attribute of local physical location of item and pass it. This process is very basic and simple. There should be a sample that mount the FS from cloud. For example a FileSystem that get the list of file/folders from goolgle drive or dropbox. Main scope of the OSXFuse can be in a project that load the data from cloud.
 I am working on creating a sample like this and I will share as I am able to do so. If someone have sample or something they should share and should be added in sample.

Vishnu Sharma

**Comment by irzyxa** [comment]
Do you have any examples at the moment?
