### ISSUE TITLE
OSXFuse crashes with SIGSEGV in volicon module on unmount

### ISSUE THREAD

**Issue by christianpraher** [osxfuse/osxfuse#167]
Hi everyone,
occasionally I get a segfault inside the ```volicon_flush``` method of the volicon module when my file system is unmounted. Apparently the path that is supposed to be flushed is NULL inside the ```volicon_is_icon_magic_file``` function in ```volicon.c```.

Here is an excerpt from a crash dump I see in such cases:
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Thread 3 Crashed:
0   libsystem_platform.dylib      	0x00007fff9ac2db50 _platform_strcmp + 80
1   libosxfuse_i64.2.dylib        	0x0000000109c44262 volicon_flush + 34
2   libosxfuse_i64.2.dylib        	0x0000000109c327cb fuse_fs_flush + 70
3   libosxfuse_i64.2.dylib        	0x0000000109c3520b fuse_flush_common + 171
4   libosxfuse_i64.2.dylib        	0x0000000109c35364 fuse_lib_flush + 142
5   libosxfuse_i64.2.dylib        	0x0000000109c3a8d0 do_flush + 88
6   libosxfuse_i64.2.dylib        	0x0000000109c3a05f fuse_ll_process + 634
7   libosxfuse_i64.2.dylib        	0x0000000109c3c1a8 fuse_session_process + 13
8   libosxfuse_i64.2.dylib        	0x0000000109c391f8 fuse_do_work + 210
9   libsystem_pthread.dylib       	0x00007fff9becc2fc _pthread_body + 131
10  libsystem_pthread.dylib       	0x00007fff9becc279 _pthread_start + 176
11  libsystem_pthread.dylib       	0x00007fff9beca4b1 thread_start + 13
```
Maybe the code in ```volicon_is_icon_magic_file``` should be written more defensively to check for a null pointer before calling ```strcmp```? 
But then again I saw that non of the modules like e.g. subdir do check for null on the given path. How can the path be NULL anyways that seems to me like an assertion exception?

One other thing that makes me wonder is that I am also using the threadid as well as the subdir module but their respective flush methods are not on the stack of the crashed thread although I provided a module order of threadid->subdir->volicon->myfs?

The crash happens especially frequently when the user logs out and the osxfuse volume gets unmounted in course of the session tear down. 
This is no big problem in general since the volume is unmounted anyways but it leaves nasty crash dump reports in the console at least. 
Also I have to mention that I am mounting my file system with the local option. Could this be related to this problem?

Thx for any help/replies.

**Comment by bfleischer** [comment]
This should be fixed in osxfuse 3. Feel free to re-open the ticket if you are still running into the issue.
