### ISSUE TITLE
`sysctl -w osxfuse.tunables.allow_other=1` required for automount to work

### ISSUE THREAD

**Issue by alugowski** [osxfuse/osxfuse#171]
Assume that you can mount a remote filesystem with sshfs. You'd like it to automount. There are many guides on the internet on how to do that. One is to set up a direct map with osx's autofs, another to use /etc/fstab. All of these result in an apparent freeze, or "Operation not permitted" or similar error when entering the autofs mount point.

The fix is to run:
sudo sysctl -w osxfuse.tunables.allow_other=1

then the auto mount succeeds. This is non-obvious and does not survive a reboot.

Can osxfuse.tunables.allow_other=1 be the default?

**Comment by raptwa** [comment]
Try the following:

To make the `osxfuse.tunables.allow_other change` survive a reboot:

Put the following in `/Library/LaunchDaemons/sysctl.plist`:

```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
 <key>Label</key>
 <string>sysctl</string>
 <key>ProgramArguments</key>
 <array>
   <string>/bin/bash</string>
   <string>-c</string>
   <string>/Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs; /usr/sbin/sysctl -w osxfuse.tunables.allow_other=1</string>
 </array>
 <key>RunAtLoad</key>
 <true/>
</dict>
</plist>
```

Load the plist with:

`launchctl load /Library/LaunchDaemons/sysctl.plist`

**Comment by bfleischer** [comment]
Enabling allow_other like this is a security risk. If you enable allow_other globally any badly written (or malicious) auto-mounting FUSE file system can block your whole system and leave OS X in a non-functional state.

I'm not saying that enabling allow_other globally is inherently bad but I wanted to make sure you know what you are getting into.

**Comment by alugowski** [comment]
So is there an alternative way or is automounting officially unsupported?

(yes, I'm using the plist workaround as well. It's the only way I could get automount to work at all.)

**Comment by bfleischer** [comment]
There is no official way of doing this but there might be a less risky workaround. You could `chown` the file system binary to be owned by a user that has admin rights (i.e. is in the admin group) and set the file's setuid bit. As a result the file system binary will be run with admin rights. This means even unprivileged users can use `-o allow_other` to allow file system access for all users. The difference to the sysctl approach is that `allow_other` is only enabled for trustworthy file systems. I have not tested this with autofs of fstab mounts but I think it is worth a shot.

**Comment by bfleischer** [comment]
Since there has not been any further feedback I going to close the issue.
