### ISSUE TITLE
Please add Swift support in the SDK

### ISSUE THREAD

**Issue by Emasoft** [osxfuse/osxfuse#172]
If I read the docs correctly, currently OSXFUSE comes only with C-based and Objective-C-based SDKs, right? Can you provide support for Swift too? I'm developing some tools for OSX in Swift and I would really like to use OSXFUSE. I don't know Objective-C (I usually work with Java) but like many people I'm now embracing Swift. An Osxfuse SDK Swift-based is really necessary for people like me. Thanks!

**Comment by gavineadie** [comment]
My understanding is that Swift will happily make use of Objective-C APIs ..

**Comment by kainjow** [comment]
yep, Swift should be able to use it just fine. Maybe an example would be helpful, but in the meantime you should read up on Apple's docs for interacting with Objective-C from Swift.

**Comment by nep** [comment]
Do you know of any example code available online of Swift using Objective-C interactions with FUSE for macOS?

**Comment by bfleischer** [comment]
The [filesystems repository](https://github.com/osxfuse/filesystems) now contains a Swift version of the LoopbackFS file system.
