### ISSUE TITLE
large_read support? List of mount-time options?

### ISSUE THREAD

**Issue by corydolphin** [osxfuse/osxfuse#173]
Hello,

I am migrating an existing script from an Ubuntu machine and found that my mount script fails as large_read is not supported in osxfuse. Is there such functionality by another name? Or, alternatively, is there a list of all supported options?

Thanks!
Cory

**Comment by bfleischer** [comment]
A list of mount options can be found in the wiki: https://github.com/osxfuse/osxfuse/wiki/Mount-options
