### ISSUE TITLE
Yosemite Finder Sidebar

### ISSUE THREAD

**Issue by mischievous** [osxfuse/osxfuse#174]
After updating to Yosemite I can no longer able to drag a mounted volume to the finder sidebar.  For some reason this completely breaks my work flow when I have to think about where I have to go to get to the mounted volume.

**Comment by synec** [comment]
Had the same problem and after some searching I've found https://code.google.com/p/macfuse/wiki/FAQ

Please see "Q 4.1. Why do MacFUSE volumes show up with "server" (or "network volume") icons?"

The solution is to add the option `-o local`

For example:

    mkdir -p /Volumes/localVolumnName && sshfs -o local -o volname=localVolumnName remoteUsername@vpn:/remote/path /Volumes/localVolumnName

Works for me on OSX 10.10.2 (14C109) with
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.7.2

**Comment by mischievous** [comment]
It works!   Yea!   Now I just have to wait for the next shoe to drop....   Eek!

**Comment by mralexgray** [comment]
@synec you should get a Nobel peace prize (for restoring my sanity) for THAT one-liner.  BIG ups.  💃🏾

**Comment by lmarcini** [comment]
**@synec : ** Thank! Your tip works with El Capitan too.

**Comment by janstieler** [comment]
@synec thanks for your tipp. But how can I use this on the GUI?
