### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by OlegPoliukhovych** [osxfuse/osxfuse#185]
Hi. I want to ask if can I make some feature like lazy loading? For now it seems like directory loads files by calling (GMUserFileSystem):
- (NSArray *)contentsOfDirectoryAtPath:(NSString *)aPath error:(NSError **)anError

 and then loads this files (if any), by calling 
- (NSData *)contentsAtPath:(NSString *)aPath

 Also "- (NSData *)contentsAtPath:(NSString *)aPath" is invoked if I make double click on file.
So, can you explain me, please, what should I do if I want to load file into the directory inside FUSE only if the user makes double click on file preview icon?
Thanks, and sorry for my English)

**Comment by bfleischer** [comment]
There is no way of knowing what caused the `contentsAtPath:` callback and it should not really matter. You only know that some process requested the file's contents. This could be the result of the user double-clicking the file, Quick Look generating a preview icon, Spotlight indexing the file, or countless other thngs.
