### ISSUE TITLE
10.10.2 kext not loading

### ISSUE THREAD

**Issue by istvan-d** [osxfuse/osxfuse#193]
Hi,

I have a MBA 13" mid2011, OS X 10.10.2 upgraded from 10.9 upgraded from 10.7. I installed OSXfuse 2.7.4 today, restarted, then built ntfs-3g from source and the wanted to mount a NTFS partition on the same internal drive:
```sudo mkdir /Volumes/m```
```sudo mount -t ntfs-3g /dev/disk0s4 /Volumes/m```
I get an error:
```mount: exec /System/Library/Filesystems/ntfs-3g.fs/Contents/Resources/mount_ntfs-3g for /Volumes/m: No such file or directory```
okay, let's try the other way round:
```sudo ntfs-3g /dev/disk0s4 /Volumes/m```
different error:
```Cannot load kext from /Library/Extensions/fuse4x.kext
fuse4x kernel extension was not loaded. Please check /var/log/{system|kernel|debug}.log for more information.```
okay, maybe I built ntfs-3g the wrong way, let's just try and load the kext:
```sudo kextload /Library/Extensions/fuse4x.kext/```
but no:
```/Library/Extensions/fuse4x.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).```
a last hope:
```sudo kextutil -load-only /Library/Extensions/fuse4x.kext/```
hm, interesting:
```Diagnostics for /Library/Extensions/fuse4x.kext:```
```Code Signing Failure: not code signed```
```ERROR: invalid signature for org.fuse4x.kext.fuse4x, will not load```

okay, maybe something wrong with the latest release, but no, 2.7.3 and 2.7.2 give the same error.
Any ideas?

**Comment by bfleischer** [comment]
Your version of ntfs-3g uses fuse4x, not osxfuse. Despite fuse4x and osxfuse both being FUSE ports for OS X they are not binary compatible. This means you cannot swap one for the other without recompiling your FUSE file systems. You can read more about fuse4x on http://fuse4x.github.io.

To load the osxfuse kernel extension try running

    kextload /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext

This should work just fine on OS X 10.10.
