### ISSUE TITLE
Availability of Filesystems?

### ISSUE THREAD

**Issue by johntrandall** [osxfuse/osxfuse#195]
The wiki here indicates that OSXFuse is compatible with the following: 

* procfs	
* AccessibilityFS	
* LoopbackFS	
* SpotlightFS	
* YouTubeFs	
* Codex VFS

Is there and easy way to install them? Do they need to be extracted from MacFuse? (http://macfuse.googlecode.com/svn/tags/macfuse-2.0.3%7c2/filesystems/)

**Comment by johntrandall** [comment]
I'd love to help work on this... Can anyone point me in the right direction?

**Comment by bfleischer** [comment]
The file systems repository can be found at https://github.com/osxfuse/filesystems.

loopback, LoopbackFS and sshfs are being maintained. The remaining file systems might not build with newer OS X SDKs. Most of the file systems have been written for 10.4 or 10.5.

**Comment by bfleischer** [comment]
The list in the wiki is not exhaustive. osxfuse is compatible with many more FUSE file systems.
