### ISSUE TITLE
Problem with mounting disk

### ISSUE THREAD

**Issue by fvgennip** [osxfuse/osxfuse#196]
Hi,

I'm trying to read the individual disks of a RAID/JBOD system (the network interface died, the disks are still ok!). Now I want to access the data of the individual drives by connecting these one-by-one to my macbook via usb. To do this, I found the following instructions on CNET (http://www.cnet.com/how-to/how-to-manage-ext2ext3-disks-in-os-x/)::
====
FUSE has been available for OS X in the MacFUSE project, but development for this has halted and FUSE is now available in the "FUSE for OS X" or "OSXFUSE" project, which derived from MacFUSE and shares much of its code base. To use the FUSE system to mount and manage Ext2 and Ext3 filesystems, you will need to install the FUSE system along with a plug-in for Ext2/Ext3, and then mount the drives manually within your user account.

01 Install either MacFUSE or OSXFUSE (the latter is preferred).
02 Install the Ext2 FUSE module.
03 Attach your Ext2/Ext3 disk and Use Disk Utility to locate the device name of the drive. This can be done by enabling the viewing of all drive partitions, and then selecting the Ext2/Ext3 partition and getting information on it to get its device name, which will be something like "disk2s2."
04 Create a new folder somewhere to use as a mount point (a folder in the hidden /Volumes directory is recommended, but it can be anywhere you desire).
05 Mount the Ext2/Ext3 drive using the following Terminal command, and replacing the device name and mount path with that of your disk and your specified path:
fuse-ext2 /dev/disk2s2 /Volumes/mountpoint
====

Installing went ok, but the "fuse-ext2" command returned an error:

====
MacBook-Pro-van-JWMH:mp fvgennip$ fuse-ext2 /dev/disk1s4 /Users/fvgennip/Desktop/mp
dyld: Library not loaded: /usr/local/lib/libfuse.2.dylib
  Referenced from: /usr/local/bin/fuse-ext2
  Reason: image not found
Trace/BPT trap: 5
====

Is this a know bug? What am I during wrong?

Thanks for helping out,
    Frank

**Comment by bfleischer** [comment]
You need to check the "MacFUSE compatibility layer" option when installing FUSE for OS X. See https://github.com/osxfuse/osxfuse/wiki/Ext.
