### ISSUE TITLE
installing osxfuse on osx 10.4.11

### ISSUE THREAD

**Issue by nitrofurano** [osxfuse/osxfuse#197]
how can i install osxfuse on osx 10.4.11?
this is the last osx version i could upgrade, the cd driver got busted, i can't boot from usb sticks (and i can't have rEFInd installed, and the rEFIt i have installed seems to be not enough), and ext2fs can only access ext2 and ext3 as read only - i lost grub (got in a blinking cursor situation - and i wanted to try to recover grub anyway), and at least i wanted to access what i have on the ext4 partitions (where i have Xubuntu and Crunchbang installed) - any idea of how to fix this situation would be excellent! thanks!

**Comment by bfleischer** [comment]
Mac OS X 10.4 is not supported by osxfuse. MacFUSE (https://code.google.com/p/macfuse/) however supports 10.4 and works with fuse-ext2.
