### ISSUE TITLE
Can't find fusermount as per encfs man page

### ISSUE THREAD

**Issue by purecanuck** [osxfuse/osxfuse#198]
I'm trying to use encfs, but I'm having an issue finding out how to
unmount. I'm using encfs version 1.7.5 and osx fuse 2.7.5. I've mounted
crypt successfully as per the man page. I'm following the steps from the
man page to umount it:

$ fusermount -u ~/crypt
-bash: fusermount: command not found

$ mount | grep crypt
encfs@osxfuse0 on /Users/example/crypt (osxfusefs, nodev, nosuid,
synchronous, mounted by example)

$ brew list encfs
/usr/local/Cellar/encfs/1.7.5_1/bin/encfs
/usr/local/Cellar/encfs/1.7.5_1/bin/encfsctl
/usr/local/Cellar/encfs/1.7.5_1/bin/encfssh
/usr/local/Cellar/encfs/1.7.5_1/lib/libencfs.6.dylib
/usr/local/Cellar/encfs/1.7.5_1/lib/libencfs.dylib
/usr/local/Cellar/encfs/1.7.5_1/share/man/ (2 files)

Please advise.

p.s. You might also consider adding encfs to the list of popular projects using osxfuse.

**Comment by bfleischer** [comment]
fusermount is Linux-only. On OS X you can unmount volumes using the umount command.
