### ISSUE TITLE
Multiple O_RDONLY opens result in a single fuse lookup/open pair on OS X

### ISSUE THREAD

**Issue by jacobsa** [osxfuse/osxfuse#199]
[Here](https://gist.github.com/jacobsa/0d6797301ff2615a16b2) is a Go program that does the following:

* Set up a minimal fuse file system type that can respond to `open` requests for a file named "foo" within the root directory, and logs the `open` request it receives. All entries and attributes are set as non-cacheable.

* Mount an instance of the file system.

* Open the file named "foo" with `O_RDONLY` twice.

The program is written in Go using a particular fuse library, but you should be able to write the equivalent in C using the official C library without too much trouble.

On Linux, the output is as expected:

    File system: returning inode ID 17 for name: foo
    File system: opened inode 17. Handle ID: 16
    Main thread opened file with FD: 3
    File system: returning inode ID 17 for name: foo
    File system: opened inode 17. Handle ID: 17
    Main thread opened file with FD: 4

In particular, note that each call to `open` resulted in a fuse lookup request followed by a fuse open request.

In contrast, this is the output I see on OS X 10.10.2:

    File system: returning inode ID 17 for name: foo
    File system: opened inode 17. Handle ID: 16
    Main thread opened file with FD: 4
    Main thread opened file with FD: 5

The first `open` results in a fuse lookup and fuse open, but the second one causes no requests to the program at all. This is unexpected—since the inode attributes are uncacheable, there should be a lookup. And I am led to believe that I should expect a fuse open request for each user call to `open`. If I change the second user `open` to use `O_RDWR`, then I get a fuse open request but not a fuse lookup request.

I don't know where to start looking to figure out if this is a problem with FUSE for OS X or with OS X itself. Help?

**Comment by jacobsa** [comment]
Note that mounting with the `novncache` option causes additional lookups to happen, but no second open request:

    File system: returning inode ID 17 for name: foo
    File system: returning inode ID 17 for name: foo
    File system: opened inode 17. Handle ID: 16
    Main thread opened file with FD: 4
    File system: returning inode ID 17 for name: foo
    File system: returning inode ID 17 for name: foo
    Main thread opened file with FD: 5

But the original program sets the entry timeout for the inodes it returns to zero, so I expect the vnode cache to not be in the way.

So I guess there are two questions here:

 *  Why does the vnode cache get in the way if I set the entry timeout to zero?
 *  Regardless of whether the vnode cache hits, why doesn't a second open request come through? Isn't fuse supposed to send one open request per user `open`?

**Comment by bfleischer** [comment]
> * Why does the vnode cache get in the way if I set the entry timeout to zero?

The entry_valid field is currently ignored by osxfuse. OS X does not support specifying timeouts for individual vnode name cache entries. This is usually only an issue if the file system can change remotely. In this case you need to disable the vnode name caching for the whole file system using option `novncache`. 

> * Regardless of whether the vnode cache hits, why doesn't a second open request come through? Isn't fuse supposed to send one open request per user open?

Let me start by saying that OS X is not Linux. The VFS layer differs significantly in some places. On OS X file handles do not make their way to the VFS layer. This means on OS X VFS plugins like osxfuse have no way of knowing which file handle was used to perform a particular read or write operation.

We deal with this by "multiplexing" FUSE file handles. osxfuse will reuse open FUSE file handles provided that they are compatible. As a result you will only see one open callback when opening the same file twice (with `O_RDONLY`) without closing the first handle before the second open.

**Comment by jacobsa** [comment]
Thank you so much for the quick and detailed response—it answers all of my questions. I have only one follow-up: are these things (no support for `entry_valid`, multiplexing of file handles) documented somewhere that I should look next time before filing a bug?

**Comment by jacobsa** [comment]
Oh sorry, one more follow-up: does osxfuse honor `attr_valid`?

**Comment by bfleischer** [comment]
> Thank you so much for the quick and detailed response—it answers all of my questions. I have only one follow-up: are these things (no support for entry_valid, multiplexing of file handles) documented somewhere that I should look next time before filing a bug?

Unfortunately there is not much documentation on the differences between FUSE on OS X and Linux. I believe this has not been documented before. 

> Oh sorry, one more follow-up: does osxfuse honor attr_valid?

Yes, `attr_valid` is honored on OS X.

**Comment by jacobsa** [comment]
Great, thanks for the reply. I will link to this thread when I need to cite documentation. :-)
