### ISSUE TITLE
Please support fuse >= 2.8.0 so that llfuse works

### ISSUE THREAD

**Issue by ThomasWaldmann** [osxfuse/osxfuse#200]
http://www.rath.org/llfuse-docs/index.html - 2.7.x is not enough for llfuse.

https://attic-backup.org/ uses llfuse to mount the backup archives.

With osxfuse 2.7.5, this happens:
```
Python 3.4.3 (default, Mar 7 2015, 01:46:30)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import llfuse
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/Homebrew/lib/python3.4/site-packages/llfuse/__init__.py", line 13, in <module>
from llfuse.capi import *
ImportError: dlopen(/usr/local/Homebrew/lib/python3.4/site-packages/llfuse/capi.so, 2): Library not loaded: /usr/local/lib/libosxfuse.2.dylib
Referenced from: /usr/local/Homebrew/lib/python3.4/site-packages/llfuse/capi.so
Reason: Incompatible library version: capi.so requires version 12.0.0 or later, but libosxfuse.2.dylib provides version 10.0.0
```

**Comment by alexreg** [comment]
osxfuse developers: So how close are you to a working 2.8.0 implementation? Seems like 2.8.0 is already more than a few years old...

**Comment by ThomasWaldmann** [comment]
anybody alive?

**Comment by alexreg** [comment]
Doesn't look like it, sadly. :(

**Comment by ThomasWaldmann** [comment]
interesting, master branch has version 3.x. does this mean llfuse stuff would work now?

**Comment by bfleischer** [comment]
You can download the latest pre-release version of FUSE for OS X from https://github.com/osxfuse/osxfuse/releases. Version 3.0.3 is based on libfuse 2.9.3. Please note that not all features of libfuse 2.9.3 are supported. So there is no guarantee that llfuse will work.

**Comment by alexreg** [comment]
Thanks!

**Comment by ThomasWaldmann** [comment]
Thanks!
