### ISSUE TITLE
Documentation for mount options

### ISSUE THREAD

**Issue by jacobsa** [osxfuse/osxfuse#201]
Is there an up to date reference akin to [this](https://code.google.com/p/macfuse/wiki/OPTIONS) one for macfuse that lists and discusses the supported mount options in osxfuse? I've looked, but haven't found it.

**Comment by bfleischer** [comment]
The mount options are the same. Currently there is no separate document for osxfuse.

**Comment by jacobsa** [comment]
Would you accept a pull request that sticks it in the osxfuse repo as a Markdown file, so that it's clear it hasn't rotted?

**Comment by bfleischer** [comment]
Thanks. I think the wiki (https://github.com/osxfuse/osxfuse/wiki) would be a better place, though. Feel free to add a mount options page.

**Comment by jacobsa** [comment]
Done, [here](https://github.com/osxfuse/osxfuse/wiki/Mount-options). You may want to read it over; I tried to update where necessary but who knows what I got wrong.
