### ISSUE TITLE
Please let me know which version of FUSE is used for 'OSXFUSE 2.7.5'

### ISSUE THREAD

**Issue by jungsim9** [osxfuse/osxfuse#207]
I installed 'OSXFUSE 2.7.5' below.
http://osxfuse.github.io/2015/02/07/OSXFUSE-2.7.5.html

I would like to know the version of the FUSE which is used for ''OSXFUSE 2.7.5'.

**Comment by bfleischer** [comment]
osxfuse 2.7.5 is based on lib fuse 2.7.3.
