### ISSUE TITLE
Re-use of "unique" request IDs, and interrupt requests

### ISSUE THREAD

**Issue by jacobsa** [osxfuse/osxfuse#208]
I'm working on a [Go package](https://github.com/jacobsa/fuse) for writing fuse file systems, and am having trouble with keeping state for interrupt requests.

On Linux, [`fuse_in_header::unique`](https://github.com/torvalds/linux/blob/6c09e94a32e1094983d39879b9e8ccf9ffdcfa36/include/uapi/linux/fuse.h#L676), the request ID seen by userspace, appears to actually be unique—it will never be repeated for the lifetime of the mount. This is implemented by [setting it](https://github.com/torvalds/linux/blob/6c09e94a32e1094983d39879b9e8ccf9ffdcfa36/fs/fuse/dev.c#L319) to the current value of [`fuse_conn::reqctr`](https://github.com/torvalds/linux/blob/6c09e94a32e1094983d39879b9e8ccf9ffdcfa36/fs/fuse/fuse_i.h#L473), and only ever [incrementing](https://github.com/torvalds/linux/blob/6c09e94a32e1094983d39879b9e8ccf9ffdcfa36/fs/fuse/dev.c#L314) that value.

In contrast, the osxfuse kext appears to aggressively re-use the "unique" IDs. My assumption is that the guarantee is the following:

> From the time that a request with ID `x` is read from the fuse device by the userspace program to the time that a reply with ID `x` is written to the device, no other request will be observed with ID `x`.

My questions:

1. Is the assumption above correct?

2. It seems that not all requests have replies associated with them. In Linux, for example, [`FUSE_FORGET` has no reply](https://github.com/torvalds/linux/blob/6c09e94a32e1094983d39879b9e8ccf9ffdcfa36/include/uapi/linux/fuse.h#L319). For these requests, how does the guarantee about IDs work?

3. Is `FUSE_FORGET` the only request without a reply associated?

4. Is [the advice](https://github.com/torvalds/linux/blob/6c09e94a32e1094983d39879b9e8ccf9ffdcfa36/Documentation/filesystems/fuse.txt#L148-L186) about the kernel <-> userspace protocol for interrupts in the Linux kernel approximately correct for osxfuse? In particular, the last paragraph's advice about `EAGAIN`?

**Comment by bfleischer** [comment]
Reusing request IDs dates back to the old MacFUSE days. To be honest I do not know why IDs are not being discarded like it is done on Linux. For sure this would have made interrupt handling much less complex. I remember spending quite some time on this.

> From the time that a request with ID x is read from the fuse device by the userspace program to the time that a reply with ID x is written to the device, no other request will be observed with ID x.

Sounds about right.

* Request IDs of interrupt requests are never being reused.
* The request ID of an interrupted request will only be reused if the request has been answered by the FUSE server before the interrupt occurred. In this case no interrupt would be sent to the FUSE server. If an interrupted request has not been answered before the interrupt its ID is discarded.

libfuse has not been modified to support  reusing request IDs. This worked out of the box.

> It seems that not all requests have replies associated with them. In Linux, for example, FUSE_FORGET has no reply. For these requests, how does the guarantee about IDs work?

As soon as the request has been read by the user space daemon its ID might/will be reused by the kernel extension.

> Is the advice about the kernel <-> userspace protocol for interrupts in the Linux kernel approximately correct for osxfuse? In particular, the last paragraph's advice about EAGAIN?

osxfuse does not differentiate between fatal and non-fatal interrupts. If a request is interrupted before it is sent to user-space it will never reach user-space. Paragraph 2 ("If the request is not yet sent to userspace AND the signal is not fatal ...") does not apply to osxfuse.

Other than that there should be no difference. The EAGAIN paragraph is correct for osxfuse as well.

**Comment by bfleischer** [comment]
> Is FUSE_FORGET the only request without a reply associated?

Yes, currently FUSE_FORGET is the only request we don't expect a reply for.

Back in the MacFUSE days not all FUSE_RELEASE and FUSE_RELEASEDIR requests did expect a reply, but this has changed since then.

**Comment by jacobsa** [comment]
Thank you very much for answering. Would it make sense to kill the reuse of IDs altogether, or is that too risky at this point?

A few notes, mostly for my future reference:

*   As [confirmed](http://comments.gmane.org/gmane.comp.file-systems.fuse.devel/14675) by Miklos Szeredi, the `EAGAIN` advice is only relevant on Linux when the server processes requests concurrently. In the stream of requests seen on /dev/fuse, the original always comes before the interrupt.

    It sounds like you are saying the same is true of osxfuse ("If a request is interrupted before it is sent to user-space it will never reach user-space" might imply this).
    
*   As far as I can tell, my package is doing the safe thing here.
    *   We [register requests](https://github.com/jacobsa/fuse/blob/438929753fe46c5f49bb3190b6865e21d89e3564/connection.go#L226-L238) and [handle interrupts](https://github.com/jacobsa/fuse/blob/438929753fe46c5f49bb3190b6865e21d89e3564/connection.go#L333-L337) inline when reading requests, so concurrency can't cause the `EAGAIN` issues we discussed above.
    
    *   We [clean up](https://github.com/jacobsa/fuse/blob/438929753fe46c5f49bb3190b6865e21d89e3564/connection.go#L243-L273) after a request, removing it from the ID map [before](https://github.com/jacobsa/fuse/blob/438929753fe46c5f49bb3190b6865e21d89e3564/fuseops/common_op.go#L124-L145) responding to the kernel, so our view of the ID lifetime is a subset of the kernel's view.
    
    *   We [don't register](https://github.com/jacobsa/fuse/blob/438929753fe46c5f49bb3190b6865e21d89e3564/connection.go#L234) forget requests.
    
    *   If an interrupt for an unknown ID comes in, we [ignore it](https://github.com/jacobsa/fuse/blob/438929753fe46c5f49bb3190b6865e21d89e3564/connection.go#L291-L294). This should be safe because as discussed above the interrupt can't be for a future request, and therefore it must be for a previous request that we have already finished processing.

**Comment by bfleischer** [comment]
> Thank you very much for answering. Would it make sense to kill the reuse of IDs altogether, or is that too risky at this point?

It would certainly be possible to stop reusing request IDs, but it would require some work to get things right. Currently my top priority is finishing osxfuse 3. Don't expect any changes in the foreseeable future.

**Comment by jacobsa** [comment]
No worries, thanks for being clear.
