### ISSUE TITLE
resourceAttributesAtPath:error not called when attributesOfItemAtPath:userData:error is implemented

### ISSUE THREAD

**Issue by ricobeck** [osxfuse/osxfuse#210]
I want to have custom icons for some folders so i had to start by implementing
```objc
- (NSDictionary *)attributesOfItemAtPath:(NSString *)path userData:(id)userData error:(NSError **)error > {
    return @{NSFileType: NSFileTypeDirectory};
}
```
After that
```objc
- (NSDictionary *)resourceAttributesAtPath:(NSString *)path error:(NSError **)error
```
is not called anymore.
You can test this with the HelloFS-Example by adding the method to HelloFuseFileSystem.m.

Did i understand this totally wrong and there is another way of getting custom icons for folders – or is this a bug?

**Comment by bfleischer** [comment]
On OS X directory Icons are stored as special (invisible) files named "Icon\r" within the directory itself. So you need to add an "Icon\r" file to your file system.

**Comment by ricobeck** [comment]
Ah, thank you very much. I did not find this in the documentation.
