### ISSUE TITLE
Paragon's ExtFS and osxfuse conflict when mounting volumes with iExplorer

### ISSUE THREAD

**Issue by 1-61803** [osxfuse/osxfuse#211]
I have installed
- osxfuse 2.7.5
- Paragon ExtFS 9.7.109
- iExplorer 3.6.7.0

When I mount my iPhone volume with iExplorer i get the log below. This doesn't happen when I uninstall Paragon kext. Is there any way to solve this without uninstalling it? Btw, I use OS X 10.8.5.

Jun  1 12:59:03 iExplorer[5251]: previewFileSystemItem: Media
Jun  1 12:59:03 iExplorer[5251]: IEPreviewVC setHeaderLabelsWithFSI: Media
Jun  1 12:59:03 iExplorer[5251]: [IEMainControlVC hideProgressOverlay]
Jun  1 12:59:07 iExplorer[5251]: mountAtPath: /Volumes/iPhone Media
Jun  1 12:59:07 iExplorer[5251]: Current app kit version: 1187.4
Jun  1 12:59:07 iExplorer[5251]:     ...not past 1200, so it must not be 10.8.....?
Jun  1 12:59:07 com.apple.kextd[12]: /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext - no compatible dependency found for com.apple.kpi.mach.
Jun  1 12:59:07 com.apple.kextd[12]: /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext - no compatible dependency found for com.apple.kpi.unsupported.
Jun  1 12:59:07 com.apple.kextd[12]: /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext - no compatible dependency found for com.apple.kpi.iokit.
Jun  1 12:59:07 com.apple.kextd[12]: /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext - no compatible dependency found for com.apple.kpi.libkern.
Jun  1 12:59:07 com.apple.kextd[12]: /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext - no compatible dependency found for com.apple.kpi.bsd.
Jun  1 12:59:07 com.apple.kextd[12]: Can't load /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext - failed to resolve dependencies.
Jun  1 12:59:26 iExplorer[5251]: unmount /Volumes/iPhone Media
Jun  1 12:59:46 iExplorer[5251]: previewFileSystemItem: (null)
Jun  1 12:59:46 iExplorer[5251]: IEPreviewVC setHeaderLabelsWithFSI: (null)
Jun  1 12:59:46 iExplorer[5251]: [IEMainControlVC hideProgressOverlay]
Jun  1 13:00:00 iExplorer[5251]: unmount /Volumes/iPhone Media
Jun  1 13:00:22 iExplorer[5251]: unmount /Volumes/iPhone Media
Jun  1 13:00:29 iExplorer[5251]: [IEMainControlVC hideProgressOverlay]
Jun  1 13:00:33 iExplorer[5251]: previewFileSystemItem: (null)
Jun  1 13:00:33 iExplorer[5251]: IEPreviewVC setHeaderLabelsWithFSI: (null)
Jun  1 13:00:33 iExplorer[5251]: [IEMainControlVC hideProgressOverlay]
Jun  1 13:00:38 iExplorer[5251]: unmount /Volumes/iPhone Media
Jun  1 13:00:38 iExplorer[5251]: [IEDoubleProgressIndicator parentWillBeDestroyed]
Jun  1 13:00:38 iExplorer[5251]: [IEBottomBarVC parentWillBeDestroyed]
Jun  1 13:00:38 iExplorer[5251]: [IETabView parentWillBeDestroyed]
Jun  1 13:00:38 iExplorer[5251]: [IEPreviewVC parentWillBeDestroyed]
Jun  1 13:00:38 iExplorer[5251]: [IERootColumnVC parentWillBeDestroyed]
Jun  1 13:00:38 iExplorer[5251]: [IEExplorerCoverFlowVC parentWillBeDestroyed]
Jun  1 13:00:38 iExplorer[5251]: [IEExplorerVC parentWillBeDestroyed]
Jun  1 13:00:38 iExplorer[5251]: [IEExplorerListVC parentWillBeDestroyed]

**Comment by bfleischer** [comment]
How did you install osxfuse? MacPorts, Homebrew, other package manager? If so please uninstall and re-install using the official installer package from http://osxfuse.github.io.

"no compatible dependency found for com.apple.kpi.mach" suggests that you are using a version of osxfuse that does not support your running kernel. The official osxfuse 2.7.5 release does support 10.8.

Please raise this issue with Paragon. If your setup works without the Paragon software present it could be a bug on their end.

**Comment by 1-61803** [comment]
I redownloaded and reinstalled osxfuse, same version. "no compatible dependency" doesn't show anymore, but now the volume is mounted and 3" later unmounted. I opened a ticket with Paragon a couple of months ago, they said "We will have to investigate possible interferences with FUSE. ", but never heard from them again. Since it's not clear on which end the problem is, I can give you the ticket number in case you want to check this up with them, or them this issue reference.

2.6.15 8:27:29.000 PM kernel[0]: OSXFUSE: starting (version 2.7.5, Feb  7 2015, 00:35:45)
2.6.15 8:27:32.030 PM iExplorer[2341]: unmount /Volumes/MyPhone Media
2.6.15 8:27:32.056 PM iExplorer[2341]: 
Mounted disks:
(
    "/",
    "/home",
    "/net"
)
2.6.15 8:27:32.096 PM iExplorer[2341]: Removing classic device /Volumes/MyPhone Media

**Comment by bfleischer** [comment]
There can be many reasons for a FUSE volume being unmounted automatically. Many of which are the result of of a faulty file system implementation. This is something the iExplorer team would need to investigate.

Judging from your bug report it is not obvious that osxfuse is to blame for the issue. The kernel extension loads fine now and the volume can be mounted, even if it is only for a brief period of time. Have you raised the issue with the iExplorer team?

**Comment by 1-61803** [comment]
I raised the issue first with the iExplorer team, then with Paragon and lastly with osxfuse. There seems to be some conflict between osxfuse and ExtFS, since the problem doesn't happen when I uninstall the latter. This doesn't necessarily mean though that the problem is on ExtFS side. If you install ExtFS trial and mount a volume, you could tell on which end it happens, I guess.
