### ISSUE TITLE
Installer 2.7.5 doesn't work On OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by brunomerindol** [osxfuse/osxfuse#212]
We can't run OSX FUSE installer version 2.7.5 on Mac OS X 10.11 El Capitan Developer Preview.

**Comment by bfleischer** [comment]
Version 2.8.0 adds *experimental* support for OS X El Capitan: http://osxfuse.github.io/2015/06/14/OSXFUSE-2.8.0.html

Please report back if you run into any compatibility issues.
