### ISSUE TITLE
3.x: fuse_create_in.mode existed before protocol 7.12

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#214]
Hi. I may be reading this wrong, but as far as I can understand, the code in https://github.com/osxfuse/kext/blob/21329eddc9abf182f7e5cc143ea8b9a82dbe3077/fuse_ipc.h#L1926-L1950 acts as if fuse_create_in.mode was only added in protocol 7.12. It existed before that.

In https://github.com/torvalds/linux/commit/e0a43ddcc08c34dbd666d93600fd23914505f4aa , which bumps the protocol 7.11->7.12, fuse_create_open switches from using fuse_open_in to fuse_create_in. Before that, fuse_open_in had the mode field, perfectly in place. The diff makes it a little bit confusing to read, though.

I think this means create requests with userspace components <=7.11 with osxfuse 3.x cause the /dev/fuse read for the fuse_create_in to have wrong length, which is what lead me down this road.

I think what's needed is just removing the #if from fuse_create_in_get_mode and fuse_create_in_set_mode.

**Comment by tv42** [comment]
Actually not wrong length, but just mode 0.

**Comment by bfleischer** [comment]
Thanks @tv42, nice find.

> I think what's needed is just removing the #if from fuse_create_in_get_mode and fuse_create_in_set_mode.

I agree.
