### ISSUE TITLE
Hangs with fusecloop

### ISSUE THREAD

**Issue by kainjow** [osxfuse/osxfuse#215]
I am experimenting with [fusecloop](https://github.com/vi/fusecloop/) which allows mounting of Knoppix cloop files, the equivalent to OS X compressed disk images.

I've done a basic port of the software to OS X, but in my testing I am seeing hangs from software that tries to access the file after a certain state, or it appears to be accessing the file.

I built fusecloop using Xcode with:

```
mkdir build
cd build
cmake -GXcode ..
open *.xcodeproj # build and run with Xcode
```

I [downloaded](http://knoppix.net/get.php) the Knoppix ISO, mounted it, created ~/mytest as the mount directory, and ran:

```
fusecloop /Volumes/KNOPPIX/KNOPPIX/KNOPPIX ~/mytest
```

The Knoppix uncompressed ISO is about 10GB. I can open the file and scroll through it all with Hex Fiend and run md5 on it several times and those all work fine. When I mount the uncompressed ISO I can browse the files and view them. However, this is where the problems begin. It is intermittent, but sometimes just opening a directory will cause Finder to hang. Other times I can open several files (I usually look at include files and open in TextMate) and they'll open fine but once I eject the uncompressed ISO I begin to get problems, or I get problems when trying to remount it. Basically, I can't seem to get a pattern except it involves mounting the uncompressed ISO.

I saw in fusecloop it is using "direct_io" and according to #26 it is unrecommended, and #187 shows there were bugs with short direct_io writes. I noted in fusecloop that it was slightly buggy and was returning short reads, so I believe I fixed that (changed use of `cloop_read` to `cloop_read_all`). I also tried with removing direct_io and rebooted but I was still able to reproduce the hang.

So, at this point, I'm not sure if there is a bug in fusecloop, or a bug in OS X Fuse. Unfortunately I haven't found any other cloop images that can be mounted besides the Knoppix one, so my testing is limited, and having to (force) reboot often makes it frustrating to test.

I am using version 2.7.5.

**Comment by bfleischer** [comment]
Is this still an issue with the latest version of FUSE for macOS?

**Comment by kainjow** [comment]
I've abandoned fusecloop and have no further plans to use it.
