### ISSUE TITLE
How to install latest NTFS-3G on OS X?

### ISSUE THREAD

**Issue by Coeur** [osxfuse/osxfuse#216]
If we follow the guide from OSXFuse... https://github.com/osxfuse/osxfuse/wiki/NTFS-3G

...We are told to install old NTFS-3G from 2010 because someone made a .pkg out of it. But what if we want to install latest NTFS-3G from 2015? Available at https://www.tuxera.com/community/open-source-ntfs-3g/

[edit] I found a way in the answer to this question:
http://stackoverflow.com/questions/30979396/compiling-ntfs-3g-for-os-x

**Comment by bfleischer** [comment]
The easiest way to install an up-to-date version of NTFS-3G would be to use a package manager like MacPorts or Homebrew.

**Comment by Coeur** [comment]
You could have updated the wiki before closing the issue.
Well, I will do it.
