### ISSUE TITLE
The FUSE user space binaries were NOT installed with root directory executable prefix

### ISSUE THREAD

**Issue by Coeur** [osxfuse/osxfuse#220]
I installed osxfuse-2.8.0.dmg with MacFuse compatibility layer.
Then, I attempted to installed latest NTFS-3G (from 23rd June 2015) and I got this during `./configure` of NTFS-3G:

****************************************************************************
* WARNING  WARNING  WARNING  WARNING  WARNING  WARNING  WARNING  WARNING   *
* The FUSE user space binaries were NOT installed with root directory      *
* executable prefix. This means that automounting NTFS volumes during boot *
* could fail. This can be fixed the below way by reinstalling FUSE using   *
* the right 'configure' option during FUSE compilation:                    *
* 	./configure --exec-prefix=/                                        *
* 	make && sudo make install                                          *
* WARNING  WARNING  WARNING  WARNING  WARNING  WARNING  WARNING  WARNING   *
****************************************************************************

**Comment by bfleischer** [comment]
Please raise this issue with the NTFS-3G team. Last time I checked NTFS-3G required some patching before it could be built with osxfuse.

If you want to use the latest version of NTFS-3G I recommend using a package manager like MacPorts or Homebrew to instal it.
