### ISSUE TITLE
veracrypt freeze on unmount

### ISSUE THREAD

**Issue by phirestalker** [osxfuse/osxfuse#222]
I have tried 2 different volumes with the same result. I cannot kill the process and I cannot unload the osxfuse kernel module. I have tried 2.7.5 and 2.8.0 of osxfuse. The application that is unmounting the volume freezes as well as disk utility if I try to open it.

I can mount the volumes just fine, it is only when I try to unmount that this happens.

I am running OSX 10.10.4. please let me know what if anything I can post. I have no crash logs because it freezes instead of crashing.

**Comment by phirestalker** [comment]
I have checked and there are no processes using the volume before unmounting. The program I am using is Veracrypt, although I had the same problem with truecrypt.

I believe this problem started when I upgraded to osx 10.10.4 from 10.10.3

**Comment by suy** [comment]
Do you know for sure that this is an OSXFUSE bug? Could it be that the file system is doing something wrong. Have you checked with them?

**Comment by phirestalker** [comment]
No I do not know for sure. I have found that the behavior is inconsistent
with test volumes but always with mine, although my volume is 250GB.
Another user with my same OS version and software version doesn't have the
same issue, so I guess it is conflicting software, I just don't know where
to start. I have uninstalled paragon extfs as that has caused other people
conflicts. I don't know what else to try.

I thought it was my volumes because the first few times with the test
volumes that another user sent me were able to be unmounted, but then a few
times they weren't, so now not really sure.

**Comment by bfleischer** [comment]
This is definitely something the VeraCrypt team would need to look into. To my knowledge VeraCrypt is still being built for MacFUSE. See https://github.com/veracrypt/VeraCrypt/issues/11.

Should this issue persist after VeraCrypt has switched to osxfuse we can re-open the issue, until then im closing it.
