### ISSUE TITLE
v3.0.4 kext does not set umask in fuse_create_in, fuse_mkdir_in, fuse_mknod_in

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#225]
FUSE protocol changelog says

```
 * 7.12
 *  - add umask flag to input argument of open, mknod and mkdir
 *  - add notification messages for invalidation of inodes and
 *    directory entries
```

OSXFUSE claims support for protocol 7.12, but doesn't fill those fields.

**Comment by bfleischer** [comment]
Umask procesing in user space is not supported and would require a new kludge to access vfs_context_proc(context)->p_fd->fd_cmask (private API). Therefore umask is set to 0. This is another case of OS X is not Linux.
