### ISSUE TITLE
3.0.4 invalidate notifications do not update size until getattr is called

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#229]
Supporting files are at https://gist.github.com/tv42/b6aa442e79c2f3514475

`clockfs` is an example FUSE filesystem that uses cache invalidate notifications to update the contents of a file, containing an update counter and a timestamp. The point is that the file content can be cached in between the updates.

https://github.com/bazil/fuse/blob/ad1470dabe5811dae6e49a45c6d4da39fc879f95/examples/clockfs/clockfs.go

The size of the file changes as more digits are added to the update counter, and sometimes due to the fractional seconds needing different amount of digits.

With OSXFUSE 3.0.4, the file content changes, but the size is "stuck". Calling Getattr (via `stat(2)` etc) causes the size to update. This is similar to https://github.com/osxfuse/osxfuse/issues/224 but slightly different.

This does not reproduce 100% of the time. If you are having trouble, I can write a more aggressive demonstration; I just happened to have `clockfs` ready.

How to reproduce:

```console
### terminal A
$ ./clockfs -fuse.debug mnt
### terminal B
$ while sleep 0.1; do cat ~/mnt/clock|hexdump -C; done
```

Note how at some point, the content change causes the newline at the end to go missing.
The other way, with extra zero padding, is invisible in the terminal. To make it visible,
try:

```console
$ while sleep 0.1; do cat ~/mnt/clock|hexdump -C; done
```

The `cat` seems to be needed to ensure `hexdump` does not do a `stat(2)` and hide the bug.

Example output:

```console
$ while sleep 0.1; do cat ~/mnt/clock; done
4       2015-08-19 17:20:31.328868336 -0700 PDT
4       2015-08-19 17:20:31.328868336 -0700 PDT
4       2015-08-19 17:20:31.328868336 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
5       2015-08-19 17:20:32.328791091 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
6       2015-08-19 17:20:33.328626129 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
7       2015-08-19 17:20:34.327974147 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
8       2015-08-19 17:20:35.328813319 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
9       2015-08-19 17:20:36.328796398 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
10      2015-08-19 17:20:37.32877384 -0700 PDT
11      2015-08-19 17:20:38.328894971 -0700 PDT11       2015-08-19 17:20:38.328894971 -0700 PDT11       2015-08-19 17:20:38.328894971 -0700 PDT11       2015-08-19 17:20:38.328894971 -0700 PDT11       2015-08-19 17:20:38.328894971 -0700 PDT11       2015-08-19 17:20:38.328894971 -0700 PDT11       2015-08-19 17:20:38.328894971 -0700 PDT11       2015-08-19 17:20:38.328894971 -0700 PDT11       2015-08-19 17:20:38.328894971 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT12       2015-08-19 17:20:39.328992325 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT13       2015-08-19 17:20:40.328788466 -0700 PDT14       2015-08-19 17:20:41.328581728 -0700 PDT14       2015-08-19 17:20:41.328581728 -0700 PDT14       2015-08-19 17:20:41.328581728 -0700 PDT14       2015-08-19 17:20:41.328581728 -0700 PDT14       2015-08-19 17:20:41.328581728 -0700 PDT14       2015-08-19 17:20:41.328581728 -0700 PDT14       2015-08-19 17:20:41.328581728 -0700 PDT14       2015-08-19 17:20:41.328581728 -0700 PDT^C
```

**Comment by bfleischer** [comment]
The FUSE kernel extension needs to know the correct file size for every vnode. `fuse_notify_inval_inode_out` only tells the kernel that the cached file contents (and by extension the file size itself) is no longer valid. What it does not tell the kernel is the new file size. This is a major problem.

osxfuse has supported invalidating vnodes for a long time through the `fuse_purge_np` function in libosxfuse. `fuse_purge_np ` tells the kernel the new file size.

Supporting `fuse_notify_inval_inode_out` might require a lot of work.

**Comment by tv42** [comment]
How is the state of the node after invalidation different from one where `attr_valid` has expired? The size is unknown, in either case.

**Comment by bfleischer** [comment]
From the perspective of the osxfuse kernel extension the size is never unknown even after a file's attributes have expired. As long as the kernel does not receive a new file size value from user-space it will assume the last known file size is still valid. Obviously this might cause issues in case a file is altered remotely without osxfuse knowing about it. This is why `fuse_purge_np` has been introduced back in the MacFUSE days.

The correct file size is required for using the cluster I/O layer of the OS X kernel. The cluster I/O layer takes care of kernel-side file caching. For read requests, for example, we are calling the `cluser_read` function, which requires us to specify the file's size:

```
int
cluster_read(vnode_t vp, struct uio *uio, off_t filesize, int xflags)
{
        ...
}

````

Let's assume the kernel thinks file A has a size of n Bytes. If you issue a read request for the (n+1)-th byte the kernel will return an error without even forwarding the read request to the user space daemon. That's why the line break is missing from the example output above.

**Comment by tv42** [comment]
But you are calling `cluster_read`, in `fuse_vnop_read`. You can add logic there. It actually doesn't sound very different from the logic in Linux. Linux keeps an attribute cache expiry time on an inode, invalidate sets expiry to ancient past, and in e.g. serving a read past EOF (in `fuse_file_read_iter`), it checks the size, and if the attributes are expired it makes a getattr request first to update them.

https://github.com/torvalds/linux/blob/f5db4b31b31504a1058339bc00488bf56ad1f0aa/fs/fuse/file.c#L908-L910

**Comment by bfleischer** [comment]
I do not think this would be the best approach from a performance standpoint. We would need to update file attributes very often. The following functions need to know the correct file size.

* fuse_vnop_read
* fuse_vnop_write
* fuse_vnop_pagein
* fuse_vnop_pageout
* fuse_vnop_allocate
* fuse_vnop_blockmap

What about updating the file attributes directly after receiving `FUSE_NOTIFY_INVAL_INODE`? As long as the user space daemon notifies the kernel when the file size changes this approach should be safe.

**Comment by tv42** [comment]
As far as I can read it, Linux FUSE does that only when the attribute cache has expired *and* the read goes past previous EOF. Given that the default attribute validity tends to be on the order of 1 minute, that doesn't happen very much.

**Comment by bfleischer** [comment]
The issue should be fixed in https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.0.5. Please reopen the ticket if it does not work for you.

> As far as I can read it, Linux FUSE does that only when the attribute cache has expired and the read goes past previous EOF. Given that the default attribute validity tends to be on the order of 1 minute, that doesn't happen very much.

I think the Linux approach for reads should work on OS X, too. But I have not had time to look into the other vnops. Version 3.0.5 send a `FUSE_GETATTR` request to user space directly after receiving `FUSE_NOTIFY_INVAL_INODE`. This is very close to way `fuse_purge_np` used to work and should not introduce regressions.

**Comment by tv42** [comment]
Looks good so far.

**Comment by bfleischer** [comment]
Great. Thanks for the feedback.
