### ISSUE TITLE
Cannot build OSXFUSE in osx 10.10

### ISSUE THREAD

**Issue by HTKT** [osxfuse/osxfuse#231]
As the instruction,
git clone --recursive -b master git://github.com/osxfuse/osxfuse.git osxfuse
Run the following command in the cloned repository to build FUSE for OS X from source:

./build.sh -t distribution

But i received Failed to configure target:

T:distribution       | Clean target
T:distribution       | Build target for OS X 10.10
T:fsbundle           | Clean target
T:fsbundle           | Build target for OS X 10.10
T:kext               | Clean target
T:kext               | Build target for OS X 10.10
T:kext               | Install target
T:fsbundle           | Install target
T:library            | Clean target
T:library            | Build target for OS X 10.10
T:library            | Failed to configure target
Terminated: 15

I installed homebrew and marport. please help to fix. Thanks

**Comment by bfleischer** [comment]
You can increase the verbosity of the build script by adding the `-v` parameter:

```
./build.sh -v 5 -t distribution
```

> I installed homebrew and marport. please help to fix. Thanks

Did you install the autoconf, automake, libtool and gettext ports?

Please note that you will not be able to load the osxfuse kernel extension on 10.10 unless it is properly signed (or you you disable kext signature checks). The official binary release is properly signed.

**Comment by HTKT** [comment]
@bfleischer : Thanks for your answer.

 Did you install the autoconf, automake, libtool and gettext ports?
How can I install these things?

**Comment by bfleischer** [comment]
Run the following command in Terminal after installing MacPorts:

```
sudo port install autoconf automake libtool gettext
```

**Comment by HTKT** [comment]
I run this command but it failed
It shows: sudo: port: command not found

Thanks

**Comment by bfleischer** [comment]
MacPorts should have added `/opt/local/bin/` to your `PATH` environment variable. You can check the value of `PATH` by running:

```
echo $PATH
```

In case `/opt/local/bin` is not in your `PATH` try running

```
sudo /opt/local/bin/port install autoconf automake libtool gettext
```

**Comment by HTKT** [comment]
When i try echo $PATH
I received:  /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin

I need to use this to call the install command ?

**Comment by bfleischer** [comment]
Are you sure you installed MacPorts (https://www.macports.org)? It does not look like MacPorts is installed.

I recommend using the osxfuse installer package instead of building osxfuse yourself.

**Comment by HTKT** [comment]
@bfleischer : DO you know how to implement SSHFS in Cocoa app (in Mac OS) ?
