### ISSUE TITLE
Mounted SSHFS with capacity size in OSX

### ISSUE THREAD

**Issue by HTKT** [osxfuse/osxfuse#235]
I want to mount the drive use SSHFS with the capacity size. I can mount the drive successfully but the capacity always is 207GB. How can I set the capacity when mounting drive. Any suggestion would be appreciate. Thanks.

**Comment by bfleischer** [comment]
Please do not double-post your questions as it is considered spamming. This issue tracker should only be used for reporting bugs.

Corresponding topic on Google group: https://groups.google.com/forum/#!topic/osxfuse-group/s70kj6ANUWs
