### ISSUE TITLE
Won't install on OS X El Capitan without prior installation 

### ISSUE THREAD

**Issue by markuswinter** [osxfuse/osxfuse#236]
Current version is 2.8.1 BUT won't install on OS X El Capitan unless it has been installed before upgrading.

The problem seems to be that El Capitan does not allow the creation of the necessary folders in usr. 

If you installed it BEFORE updating to El Capitan then there is no problem.

I tried to disable rootless but still no luck (though as I'm running 10.11.1 beta I'm not sure rootless was really disabled).

**Comment by bfleischer** [comment]
> Current version is 2.8.1 BUT won't install on OS X El Capitan unless it has been installed before upgrading.

It works perfectly fine for me on a fresh install of the OS X 10.11 GM candidate. Rootless has not been disabled.

Are you getting any useful error messages? Did you install the binary package from https://osxfuse.github.io or did you build osxfuse yourself?

> The problem seems to be that El Capitan does not allow the creation of the necessary folders in usr.

`/usr/local` is no locked down by OS X 10.11 and should be writeable by root like before.

**Comment by markuswinter** [comment]
Ok, should have been more precise.

I upgraded an iMac which had MacOS X 10.6.8 Snow Leo installed straight up to MacOS X 10.11.1 El Capitan (yes, the new beta).

Had some problems with Mail and iPhotos but solved them in the end.

However some apps would no longer install, namely I could not install the libdvdcss.pkg (required by Handbrake to rip copy-protected DVDs to my Mediathek), nor OSXfuse.

I tried to directly copy libdvdcss.2.dylib to the /usr/local/lib folder but found that it did not exist.

I tried to create it via the Finder as well as via the terminal (trying su and sudo) but was told I do not have permission (even as administrator).

I tried to copy it over from a different Mac but again without success (as expected).

The way I finally solved it was to install Yosemite on an external hard disk, started up from the external, set up Handbrake and OSXfuse on there, and use Migration Assistant to import a user with all his settings from that external hardest (funnily enough trying to put the user onto the iMac FROM the external did not work).

I did not have any such problems on my other Macs where I installed libdvdcss.pgk and OSXfuse before upgrading to El Capitan.

The files are now where they are supposed to be, with SYSTEM being the owner. I still do not have write permission to /usr.

So my conclusion was that there is a permission problem with creating the folders.

**Comment by bfleischer** [comment]
> So my conclusion was that there is a permission problem with creating the folders.

I agree, this is most likely the reason for the installation failure. I suppose this has something to do with the difficult upgrade process from Snow Leopard.

Once you get the permission issue resolved you should be able to install osxfuse. This does not look like a osxfuse bug, so I'm closing the ticket.

**Comment by markuswinter** [comment]
Hi Benjamin,

From the Ars Technica review:

The file and directory protections are the part of SIP that users are most likely to actually encounter. To start with, SIP drops an impenetrable curtain around the following four locations:

/System
/bin
/usr
/sbin
See http://arstechnica.com/apple/2015/09/os-x-10-11-el-capitan-the-ars-technica-review/8/

So it might well become a problem for OSXfuse if it can no longer create the required folders in /usr

MfG

Markus

**Comment by markuswinter** [comment]
P.S. usr/local is whitelisted as being writeable, but only if it already exists. I would call the inability to create /usr/local after the fact a bug, but I haven't thought about what the security implications of that would be...

In almost all cases, the installers shouldn't have been writing there in the first place. Apple's been pushing things out of /System for years now …

Take care

MfG

Markus

Sent from my iPad

**Comment by bfleischer** [comment]
By default `/usr/local` does not exist on fresh installs of OS X 10.5 to 10.10.  

When upgrading from Yosemite (without the `/usr/local` directory) to El Capitan, `/usr/local` is created automatically, I checked. So there should be no problem at all.

I do not know what went wrong in your case. There might be a bug in the El Capitan installer or it could be related to your system. But the fact that the osxfuse installer fails to create `/usr/local` on your system is, at least from my point of view, not a osxfuse bug. From the osxfuse end there is nothing that can be done to fix this. You would need to temporarily disable rootless, create the directory, make sure the "restricted" flag ist not set, and re-enable rootless.

> In almost all cases, the installers shouldn't have been writing there in the first place. Apple's been pushing things out of /System for years now …

osxfuse is not in `/System`, it never has been. `/usr/local` is a perfectly valid location to install shared libraries to. That's why Apple specifically whitelisted it in El Capitan.

**Comment by markuswinter** [comment]
Thanks for the explanation. I'm learning quite a bit here ;-)

Take care

MfG

Markus
