### ISSUE TITLE
range invalidate to grow file sees zero content

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#237]
This bug happens with OSXFUSE 3.0.6.

`grow.go` is a filesystem with a single file, `hello`. The initial
contents of the file are `hello, world\n`. 5 seconds after it has been
read, it grows by appending `goodbye\n`, and sending an invalidation
(offset=13, size=8). Future reads will see `hello, world\ngoodbye\n`.

Here's a sample session from Linux:

```console
$ cat mnt/hello
hello, world
$ cat mnt/hello
hello, world
goodbye
```

Here's the observed behavior on OSXFUSE 3.0.6:

```console
$ cat mnt/hello
hello, world
$ cat mnt/hello
hello, world
$ cat mnt/hello|hexdump -C
00000000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 0a 00 00 00  |hello, world....|
00000010  00 00 00 00 00                                    |.....|
00000015
```

This seems to be related specifically to range invalidations. If I
invalidate all of the data (offset=0, size=-1), I see the correct
contents.

As you can see from the debug logs, there are no `Read` calls seen
after the invalidation; OSXFUSE thinks the cache contents are valid.

Extra files at https://gist.github.com/tv42/699e01290ad91f5903e7

- [`grow.go`](https://gist.github.com/tv42/699e01290ad91f5903e7#file-grow-go): Go source code to reproduce
- [`grow`](https://gist.github.com/tv42/699e01290ad91f5903e7#file-grow): prebuilt binary
- [`linux.log`](https://gist.github.com/tv42/699e01290ad91f5903e7#file-linux-log): debug log for Linux
- [`osxfuse.log`](https://gist.github.com/tv42/699e01290ad91f5903e7#file-osxfuse-log): debug log for OSXFUSE
- [`osxfuse-invalidate-all.log`](https://gist.github.com/tv42/699e01290ad91f5903e7#file-osxfuse-invalidate-all-log): debug log when invalidating all data

**Comment by bfleischer** [comment]
Thanks for the bug report. The problem seem to be that the last page in the ubc cache (before extending the file) is not invalidated automatically when extending the file. This page contains "hello world\n" and is padded with zeros.

If `farewell` is greater than 4 KB the ubc cache allocates a second page and another read request is issued for that page.

**Comment by bfleischer** [comment]
Please check again with the following build. Unless the file ends on a page boundary the new build will invalidate the last page of the file's unified buffer cache (before expanding the file). This fixes the issue for me. In my opinion it is kind of odd that the kernel invalidates the last page when shrinking files but not when expanding files. 

https://www.dropbox.com/s/5gsfzh6c98dq04d/osxfuse-3.0.6_1.dmg?dl=0

**Comment by tv42** [comment]
That one passes the test, thanks!
