### ISSUE TITLE
Mac OS X 10.11 El Captain - error?

### ISSUE THREAD

**Issue by rdewolff** [osxfuse/osxfuse#238]
Hi all

Am having problems to mount SFTP drive. Am using the following command : 
```
sshfs user@host:/[remote_dir] /path/[local_dir] -ocache=no -onolocalcaches -ovolname=[local_dir]
```

But then I get the following error :

```
/Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
the OSXFUSE file system is not available (71)
```

Any idea of the problem and a solution? Have searched through web without success.

**Comment by rdewolff** [comment]
Maybe you know any other way to mount an SFTP drive on Mac OS X ?
(Transmit doesn't work, finder mount either, WebDrive not) 
Bug seems like a system wide problem?

**Comment by duanemoody** [comment]
El Capitan's System Integrity Protection framework requires all extensions to be signed now and no longer permits users to override this at the command line:

http://arstechnica.com/apple/2015/09/os-x-10-11-el-capitan-the-ars-technica-review/9/
> Going hand-in-hand with the runtime protection is mandatory signing for kernel extensions. As of El Cap, the methods for working around KEXT signing (like using sudo nvram boot-args='kext-dev-mode=1') have been removed, and KEXT signing enforcement is now under SIP control. El Cap will refuse to load any kernel extensions that aren’t signed by a valid Apple developer ID.
>
> OS X users who depend upon unsigned KEXTs for extra functionality—be it third-party hardware with unsigned drivers or software like OSXFuse that depends upon unsigned kernel extensions—will have precisely two alternatives: stop using the applications or hardware until the developers provide signed KEXTs, or disable SIP altogether.

SIP is embedded at the kernel level so even root is unable to get past it. 

Going to https://developer.apple.com/contact/kext to obtain a Developer ID Certificate requires being a [paid member of Apple's developer program](https://developer.apple.com/support/compare-memberships/); SIP apparently isn't satisfied with other signing certs you might already have.

**Comment by bfleischer** [comment]
@duanemoody The arstechnica article you are citing is plain wrong. All official osxfuse releases since version 2.6.1 (13 Aug 2013) have been properly signed. The osxfuse kernel extension has been among the first kernel extensions that were signed after Apple introduced the new security feature two years ago. Unofficial releases, like those installed by package managers like Homebrew in the past, are most likely not signed. osxfuse 2.8.0, that has been released on 14 Jun 2015, added support for El Capitan.

**Comment by Lethos** [comment]
Still, I get a very similar failure message when trying to use a NTFS disk via Tuxera NTFS (2015 version).

/Library/Filesystems/fusefs_txantfs.fs//Contents/Resources/Support/10.9/tufs/tufsfs.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).

An from a terminal:
bash-3.2# kextutil -t /Library/Filesystems/fusefs_txantfs.fs//Contents/Resources/Support/10.9/tufs/tufsfs.kext
Can't create kext: invalid CFBundleVersion in identifier cache entry entry 10.
Diagnostics for /Library/Filesystems/fusefs_txantfs.fs//Contents/Resources/Support/10.9/tufs/tufsfs.kext:
Code Signing Failure: code signature is invalid
Can't create kext: invalid CFBundleVersion in identifier cache entry entry 10.
Untrusted kexts are not allowed
ERROR: invalid signature for com.tuxera.filesystems.tufsfs.fusefs_txantfs, will not load

**Comment by duanemoody** [comment]
Thank you for correcting me. I will remember to install directly from this repository and advise others to do the same. Again, apologies for disseminating false information.

**Comment by bfleischer** [comment]
@rdewolff Are you using an official release from https://osxfuse.github.io or did you build osxfuse yourself or install it using a package manager like Homebrew of MacPorts?

**Comment by rdewolff** [comment]
I used an official release.

**Comment by kastork** [comment]
I just tried it on two different machines running El Capitan.  I used the 2.8x installer on the osx fuse website.

On both machines (one that had an older fuse on it originally, and one that has never had fuse on it)  I get the same error when Transmit attempts to mount an S3 bucket.

11/8/15 11:15:01.294 AM com.apple.kextd[47]: Untrusted kexts are not allowed
11/8/15 11:15:01.294 AM com.apple.kextd[47]: ERROR: invalid signature for com.panic.TransmitDisk.transmitdiskfs, will not load

**Comment by bfleischer** [comment]
@kastork Panic uses a custom version of FUSE for Transmit Disk. Please contact Panic for assistance.

**Comment by francwalter** [comment]
I did so and am waiting for the answer.
As me too have the maybe same problem, Transmit not mounting the volume.

**Comment by kastork** [comment]
It turns out there's a separate release of Transmit Desktop they are distributing seperately from Transmit.  It is in their downloads area.

**Comment by francwalter** [comment]
You mean Transmit **Disk** in this artikel [OS X El Capitan (10.11) Compatibility](https://library.panic.com/general/mac/el-capitan/) with the download of [Transmit Disk 4.4.9](https://download.panic.com/transmit/Transmit%20Disk%204.4.9.pkg) ?
This didnet work on me :(

**Comment by JamesKyburz** [comment]
Trying to build on El Capitan with no joy (got Xcode 7.2 (7C68) 

➜  osxfuse git:(master) ./build.sh -t distribution
T:distribution       | Clean target
T:distribution       | Build target for OS X 10.11
T:fsbundle           | Clean target
T:fsbundle           | Build target for OS X 10.11
T:kext               | Clean target
T:kext               | Build target for OS X 10.11
T:kext               | Install target
T:fsbundle           | Install target
T:library            | Clean target
T:library            | Build target for OS X 10.11
T:library            | Failed to configure target
Terminated: 15

**Comment by bfleischer** [comment]
@JamesKyburz It looks like you did not install the required MacPorts packages autoconf, automake, libtool, and gettext. To get a more verbose build log run the build command with verbose set to 5:

    ./build.sh -v 5 -t distribution

**Comment by JamesKyburz** [comment]
@bfleischer thx!

Using brew and brew install autoconf  automake  libtool  gettext stated
```
Warning: autoconf-2.69 already installed
Warning: automake-1.15 already installed
Warning: libtool-2.4.6 already installed
Warning: gettext-0.19.5.1 already installed
```

The more verbose output shows a possible issue with gettext 

```
Running autoreconf...
configure.ac:76: warning: macro 'AM_ICONV' not found in library
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:76: warning: macro 'AM_ICONV' not found in library
configure.ac:76: error: possibly undefined macro: AM_ICONV
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
To compile run './configure', and then 'make'.
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
T:library            | Failed to configure target
```

**Comment by bfleischer** [comment]
The issue is caused by the way Homebrew installs gettext. If you install those packages using MacPorts all should work fine.

When installing gettext, brew states:

    This formula is keg-only, which means it was not symlinked into /usr/local.

 You can force link gettext by running

    brew link --force gettext

After doing so osxfuse should build fine.

**Comment by JamesKyburz** [comment]
@bfleischer Thx for the help `brew link --force` did the trick for me.
