### ISSUE TITLE
Imac does not start after installing osx fuse

### ISSUE THREAD

**Issue by synapsco** [osxfuse/osxfuse#239]
hello everyone, 
osx fuse has been installed ysterday on our collective imac,
and after reboot, the computer remains at the apple and does not want to go further..
any idea, i even dont know it fuse might be involve in this bug, but since it's a low level software why not.. on this Imac, we also have a dual boot linux and hitting the 'alt' key to boot on it, the Imac is able to boot on linux. So this is just the mac side which is not reachable.. If you could help us to understand and fix it, that would be wonderful! Thx
magali

**Comment by synapsco** [comment]
The Imac finally started again. Can osxfuse be a cause of system instability?

**Comment by bfleischer** [comment]
I do not think osxfuse is to blame for this. osxfuse is not a background process. It is not something that launches automatically at boot time or any other time. It does not configure, reconfigure, or modify the normal working of OS X by itself. It does not alter settings of any OS X components besides placing its preference pane for System Preferences to use.

FUSE for OS X is a bunch of libraries and headers along with a kernel extension. The osxfuse kernel extension is not loaded automatically at boot time or any other time. It is dynamically loaded when a FUSE-based application runs. Even when loaded, the kernel extension just occupies some memory - its code does not kick in until you actually mount a FUSE-based file system.
