### ISSUE TITLE
Optimizing osxfuse for fast storage (SAN)

### ISSUE THREAD

**Issue by misku** [osxfuse/osxfuse#240]
Hi,
This is not really an issue, but an optimization question. I'm using osxfuse with fast (W/R 600MB/s / 600MB/s) storages and I would be grateful for any tips that could increase writing/reading performance when using osxfuse. The block size of the storage is usually 256K.

I've tried increasing the following constants (common/fuse_param.h):
* `FUSE_DEFAULT_BLOCKSIZE`
* `FUSE_MIN_BLOCKSIZE`
* `FUSE_DEFAULT_IOSIZE`
* `FUSE_MIN_IOSIZE`
* `FUSE_MIN_IOSIZE`
* `FUSE_DEFAULT_USERKERNEL_BUFSIZE`
* `FUSE_MIN_USERKERNEL_BUFSIZE`
* `FUSE_MIN_READ_BUFFER` (fuse/include/fuse_kernel.h)

The performance seemed to be sensitive to `FUSE_DEFAULT_IOSIZE`. Increasing it, bumped the speeds a lot. Increasing other constants did not affect the performance in a significant way.

Up until now I'm getting around 70%-100% of the non-fuse **writing** speeds (depending on the block size used with testing) which is quite ok.
Yet **reading** speeds can sometimes drop to around 35% of the non-fuse speeds (also depending on the block size used). Is there any way to try to improve this?

Tests were done with `dd` and `bonnie++` using blocks from 4K up to 1M.

Thank you for your help,
Tom

**Comment by bfleischer** [comment]
In the upcoming version 3.x (https://github.com/osxfuse/osxfuse/releases) the maximum I/O size has been increased from 1 MiB to 32 MiB on OS X 10.7 and later, and 16 MiB on Mac OS X 10.6 and earlier . To use the full 32 MiB you need to mount the file system with `-o iosize=33554432`. Changing constants in `fuse_param.h` is not the right way of doing this.

Using an I/O size of 32 MiB means that (under the condition that the writing process uses a chunk size of 32 MiB) there will be only a single round trip from kernel mode to user space and back. When mounting the volume with the default block size there will be 512 round trips to user space to write those 32 MiB. As a general rule, less context switches will make the file system faster.

**Comment by misku** [comment]
Thank you Benjamin. Good tip.
