### ISSUE TITLE
Handling local symbomlic links on a client should include the mount path

### ISSUE THREAD

**Issue by jonalmeida** [osxfuse/osxfuse#241]
I'm not entirely sure if this is feasible or a good idea to implement, but hopefully my use case might shed some light on why it might be useful:

I'm trying to use my ide (IntelliJ IDEA) on a project that is built on a linux remote box. The project includes a `build.gradle` file (which is a build script) that in my case, is symlinked to a different location with it's full path (i.e. `/home/jonalmeida/..`).

When I try to import the project after mounting the drive, the symlink can be seen from my finder, but not from my IDE since the link points to `/home/..` which doesn't exist on my Mac.

Would it make sense to append the mounted to the end of the full path of a symlink?

**Comment by bfleischer** [comment]
The `jail_symlinks` mount-time option prefixes the symlink's source path with the mount point's path. See https://github.com/osxfuse/osxfuse/wiki/Mount-options#jail_symlinks.
