### ISSUE TITLE
Cannot write on NTFS hd

### ISSUE THREAD

**Issue by invasionofsmallcubes** [osxfuse/osxfuse#242]
Hi, after upgrading to OSX El Capitan I cannot longer write on a NTFS hd. I've installed the latest version of osxfuse but I'm still can't copy anything on it. I've installed a trial version of Tuxera 2015 and I can write again.
Do I have to do something to let osxfuse work again?

**Comment by smagaz** [comment]
Same problem here!
anything new ?

**Comment by BIG1** [comment]
In the meantime, use tuxera?

**Comment by bfleischer** [comment]
This is most likely a NTFS-3G issue. osxfuse works fine on OS X 10.11. You need to get in touch with the NTFS-3G team.
