### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by BIG1** [osxfuse/osxfuse#243]
How to completely uninstall this? This no longer work with el capitan 10.11.

**Comment by bfleischer** [comment]
osxfuse 2.8 works fine on OS X 10.11. Maybe the actual file system you are using does not.

Please refer to https://github.com/osxfuse/osxfuse/wiki/FAQ#23-how-can-i-uninstall-fuse-for-os-x for uninstalling osxfuse.
