### ISSUE TITLE
Write data corruption

### ISSUE THREAD

**Issue by ivenhov** [osxfuse/osxfuse#244]
I have a strange corruption problem on our FS using OSXFUSE 2.7.5, also reproducible on 2.8.2.

We have a file system mounted as a local drive, we also enable Spotlight indexing on. This may not be relevant but so far we were able to reproduce the problem only in that configuration.

When writing large file 100MB+ with small block size data corruption occurs.
Problem is reproducible quite easily and happens on Mavericks and Yosemite.

When corruption happens in the file I can see blocks of zeroes in some places.
I did a write to a local filesystem at the same time and it looks like data is passed to our FS implementation  occasionally with some leading zeroes in the byte buffer.

Added some logging to OSXFUSE in fuse.c (from github tags/2.7.5) in fuse_lib_write() method and looks like every now and then buf array contains leading zeroes I should not have.

What is interesting is that my filesystem receives 4 calls for the same offset 

offset=9469952, size: 1048
offset=9469952, size: 2048
offset=9469952, size: 3048
offset=9469952, size: 4048
offset=9469952, size: 5048
offset=9474048, size: 1952
offset=9474048, size: 2952
offset=9474048, size: 3952
offset=9474048, size: 4952

which is already strange because I'm writing to file system sequentially.
To me it looks like there is some missing parameter, like position in buf array that would indicate where data really starts (and everything before is garbage that should be ignored)

This makes me think there is a bug somewhere in OSXFUSE but of course I might be wrong here.

Looking at master branch now I can see in fuse.c there are new methods handling write fuse_lib_write_buf() fuse_fs_write() and fuse_fs_write_buf() which means things have changed.

BTW. I managed to reproduce problem with files as small as 10MB when writing with 1000 bytes of data.

Any help greatly appreciated

**Comment by bfleischer** [comment]
Can you reproduce the issue with the loopback reference file system? 

> When writing large file 100MB+ with small block size data corruption occurs.

What is the exact block size?

**Comment by ivenhov** [comment]
Hi Benjamin

Thanks for prompt reply.

TO answer your question.
I'm mounting with 

[c7d](Java_fuse_FuseMount_mount) '-odaemon_timeout=60'
[c7d](Java_fuse_FuseMount_mount) '-oiosize=131072'
[c7d](Java_fuse_FuseMount_mount) '-oallow_other'
[c7d](Java_fuse_FuseMount_mount) '-odefer_permissions'
[c7d](Java_fuse_FuseMount_mount) '-oping_diskarb'
[c7d](Java_fuse_FuseMount_mount) '-ofsname=myfs'
[c7d](Java_fuse_FuseMount_mount) '-ovolname=MyVol,volicon=diskIconOnline.icns'
[c7d](Java_fuse_FuseMount_mount) '-olocal'
[c7d](Java_fuse_FuseMount_mount) '/Volumes/myvol'

In my test I'm writing to the filesystem as a sequential stream, 1000 bytes each time;

So far I haven't been able to reproduce it with loopback.
What I see on loopback is similar access pattern:

unique: 21, opcode: WRITE (16), nodeid: 10, insize: 1474
WRITE[5] 1410 bytes to 9031680 path /test
fuse.c fuse_fs_write() at offset 9031680
fuse.c fuse_fs_write() at offset 9031680
fuse.c fuse_fs_write() at offset 9031680
   WRITE[5] 1410 bytes
   unique: 21, error: 0 (Undefined error: 0), outsize: 24
unique: 22, opcode: WRITE (16), nodeid: 10, insize: 2497
WRITE[5] 2433 bytes to 9031680 path /test
fuse.c fuse_fs_write() at offset 9031680
fuse.c fuse_fs_write() at offset 9031680
fuse.c fuse_fs_write() at offset 9031680
   WRITE[5] 2433 bytes
   unique: 22, error: 0 (Undefined error: 0), outsize: 24
unique: 23, opcode: WRITE (16), nodeid: 10, insize: 3520
WRITE[5] 3456 bytes to 9031680 path /test
fuse.c fuse_fs_write() at offset 9031680
fuse.c fuse_fs_write() at offset 9031680
fuse.c fuse_fs_write() at offset 9031680
   WRITE[5] 3456 bytes
   unique: 23, error: 0 (Undefined error: 0), outsize: 24
unique: 24, opcode: WRITE (16), nodeid: 10, insize: 4543
WRITE[5] 4479 bytes to 9031680 path /test
fuse.c fuse_fs_write() at offset 9031680
fuse.c fuse_fs_write() at offset 9031680
fuse.c fuse_fs_write() at offset 9031680
   WRITE[5] 4479 bytes
   unique: 24, error: 0 (Undefined error: 0), outsize: 24

Then similar sizes on offset 9035776

What I don't get is 
- why there are 4 write calls for each offset, each time with bigger sizes, why not just single call to offset 9031680 with size 4479
- why fuse.c fuse_fs_write() logs 3 times for every WRITE[5]

Few key differences between loopback and my FS implementation
- My FS in in Java and I'm using JNI to marry it with OSXFUSE
- My FS does access to remote storage over Ethernet
- Spotlight indexing is really quick on my HDD with loopback. I tried to use slower USB stick as a loopback target to simulate slower storage

As for JNI layer, write looks something like

static int javafs_write(const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *ffi) {
      ......
      jBuf = (*env)->NewDirectByteBuffer(env, (void *)buf, (jlong)size);
jerrno = (*env)->CallIntMethod(env, params->fuseFS, FuseFS->method.write__Ljava_nio_ByteBuffer_Ljava_lang_Object_ZLjava_nio_ByteBuffer_J, jPath, read_file_handle(ffi), (ffi->writepage)? JNI_TRUE : JNI_FALSE, jBuf, (jlong)offset);
    ....
}

**Comment by ivenhov** [comment]
Small correction.

Write in this test was done using 1023 bytes, which is a difference between sizes above: 1410, 2433, 3456 and 4479 bytes. Also offset is always aligned to the page size (4096 bytes) 9031680 then 9035776.
Looks like some page alignment issues?

**Comment by bfleischer** [comment]
I have not been able to reproduce the issue with loopback. It would be very helpful if you could provide a stripped down file system and more detailed repro steps. 

> What is interesting is that my filesystem receives 4 calls for the same offset
>
> offset=9469952, size: 1048
> offset=9469952, size: 2048
> offset=9469952, size: 3048
> offset=9469952, size: 4048
> offset=9469952, size: 5048
> offset=9474048, size: 1952
> offset=9474048, size: 2952
> offset=9474048, size: 3952
> offset=9474048, size: 4952
>
> which is already strange because I'm writing to file system sequentially.
> To me it looks like there is some missing parameter, like position in buf array that would indicate where > data really starts (and everything before is garbage that should be ignored)

This is perfectly normal behavior. Read an write operations pass through the kernel's Cluster I/O layer. The Cluster I/O layer then issues the write requests you see in your file system implementation. Requests issued by the Cluster I/O layer are always page-aligned. The smallest memory unit is 4096 byte (PAGE_SIZE). That's why you are seeing multiple writes for the same offset. The first bytes of each page are actually written multiple times.

Issuing I/O in chunk sizes smaller than the file system's block size is very inefficient.

**Comment by ivenhov** [comment]
Thanks for your explanations.
Initially we were using 17kB as a block size in our test, just to 'use something inefficient and try to break it'. Now we change it to even more awkward 1000 bytes as it allows us to have higher failure rate.

At the moment it looks like problem is in our code. I think what is happening is that OS drops some pages from memory and during write, because writes are not aligned to pages it needs to reconstruct buffers for next write. It calls read method on our FS which returns garbage (zeroes). Those zeroes are part of next write and were logged by me in fuse.c

I managed to log read operation in fuse just before corruption happens

unique: 10, opcode: WRITE (16), nodeid: 87, insize: 1976
WRITE[140627627149064] 1912 bytes to 8921088 path /testfile
fuse.c fuse_fs_write() thread: 4660760576 at offset 8921088, bytes 1912, buff addr: 0x114c57040
fuse.c fuse_fs_write() thread: 4660760576 at offset 8921088, bytes 1912, buff addr: 0x114c57040
done fuse.c fuse_fs_write() thread: 4660760576 at offset 8921088, bytes 1912, buff addr: 0x114c57040
done fuse.c fuse_fs_write() thread: 4660760576 at offset 8921088, bytes 1912, buff addr: 0x114c57040
   WRITE[140627627149064] 1912 bytes
   unique: 10, error: 0 (Undefined error: 0), outsize: 24
   
unique: 21, opcode: WRITE (16), nodeid: 87, insize: 2976
WRITE[140627627149064] 2912 bytes to 8921088 path /testfile
fuse.c fuse_fs_write() thread: 4748410880 at offset 8921088, bytes 2912, buff addr: 0x119fee040
fuse.c fuse_fs_write() thread: 4748410880 at offset 8921088, bytes 2912, buff addr: 0x119fee040
done fuse.c fuse_fs_write() thread: 4748410880 at offset 8921088, bytes 2912, buff addr: 0x119fee040
done fuse.c fuse_fs_write() thread: 4748410880 at offset 8921088, bytes 2912, buff addr: 0x119fee040
   WRITE[140627627149064] 2912 bytes
   unique: 21, error: 0 (Undefined error: 0), outsize: 24
   
unique: 9, opcode: RELEASEDIR (29), nodeid: 86, insize: 64
   unique: 9, error: 0 (Undefined error: 0), outsize: 16
unique: 16, opcode: GETATTR (3), nodeid: 87, insize: 40
   unique: 16, error: 0 (Undefined error: 0), outsize: 128
   
unique: 15, opcode: WRITE (16), nodeid: 87, insize: 3976
WRITE[140627627149064] 3912 bytes to 8921088 path /testfile
fuse.c fuse_fs_write() thread: 4765728768 at offset 8921088, bytes 3912, buff addr: 0x11b072040
fuse.c fuse_fs_write() thread: 4765728768 at offset 8921088, bytes 3912, buff addr: 0x11b072040
unique: 13, opcode: GETATTR (3), nodeid: 1, insize: 40
done fuse.c fuse_fs_write() thread: 4765728768 at offset 8921088, bytes 3912, buff addr: 0x11b072040
done fuse.c fuse_fs_write() thread: 4765728768 at offset 8921088, bytes 3912, buff addr: 0x11b072040
   WRITE[140627627149064] 3912 bytes
   unique: 15, error: 0 (Undefined error: 0), outsize: 24

   unique: 13, error: 0 (Undefined error: 0), outsize: 128
unique: 17, opcode: READ (15), nodeid: 87, insize: 64
unique: 25, opcode: GETXATTR (22), nodeid: 1, insize: 77
READ[140627629244352] 4096 bytes from 8921088
fuse.c fuse_fs_read() thread: 4783046656 at offset 8921088, bytes 4096 into buff addr: 0x7fe66f993c00
fuse.c fuse_fs_read() thread: 4783046656 at offset 8921088, bytes 4096 into buff addr: 0x7fe66f993c00
   unique: 25, error: 0 (Undefined error: 0), outsize: 48
unique: 24, opcode: GETXATTR (22), nodeid: 1, insize: 77
   unique: 24, error: 0 (Undefined error: 0), outsize: 48
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 50
LOOKUP /.DS_Store
done fuse.c fuse_fs_read() thread: 4783046656 at offset 8921088, bytes 4096 into buff addr: 0x7fe66f993c00, res: 0
done fuse.c fuse_fs_read() thread: 4783046656 at offset 8921088, bytes 4096 into buff addr: 0x7fe66f993c00, res: 0
   READ[140627629244352] 0 bytes
   unique: 17, error: 0 (Undefined error: 0), outsize: 16
   
unique: 5, opcode: WRITE (16), nodeid: 87, insize: 4976
Potentially corrupted data on path /testfile at offset: 8921088, write size: 4912, buff address: 0x119fee040
WRITE[140627627149064] 4912 bytes to 8921088 path /testfile
fuse.c fuse_fs_write() thread: 4748410880 at offset 8921088, bytes 4912, buff addr: 0x119fee040
fuse.c fuse_fs_write() thread: 4748410880 at offset 8921088, bytes 4912, buff addr: 0x119fee040
done fuse.c fuse_fs_write() thread: 4748410880 at offset 8921088, bytes 4912, buff addr: 0x119fee040
done fuse.c fuse_fs_write() thread: 4748410880 at offset 8921088, bytes 4912, buff addr: 0x119fee040
   WRITE[140627627149064] 4912 bytes
   unique: 5, error: 0 (Undefined error: 0), outsize: 24

So although my app writes sequentially there are potentially internal reads from OS that can mess everything up.

Does this theory sounds plausible to you?
Thanks

**Comment by bfleischer** [comment]
> So although my app writes sequentially there are potentially internal reads from OS that can mess everything up.
>
> Does this theory sounds plausible to you?

Your conclusion is correct. In case the cluster layer dropped the last page from the file's cache it will need to read the last page before appending new data, unless of course the file did end on a page boundary.

> Also, why do I see duplicated messages like:
>
> fuse.c fuse_fs_write() thread: 4660760576 at offset 8921088, bytes 1912, buff addr: 0x114c57040
> fuse.c fuse_fs_write() thread: 4660760576 at offset 8921088, bytes 1912, buff addr: 0x114c57040

You are mounting the FUSE volume with the `volicon`option. This means there are actually two layers in the libosxfuse file system stack: the `volicon` module and your file system implementation. The `volicon` layer sits ontop of your implementation and handles all requests related to the volume icon. `fuse_fs_write` is called for each layer in the file system stack. If you mount your file system without the `volicon` option you should see only one log entry for `fuse_fs_write `. The data is only written once in either case.

**Comment by bfleischer** [comment]
Can this ticket be closed?

**Comment by ivenhov** [comment]
Yes. I'm closing it now.
The problem was not related to OSXFUSE in any way but a bug in my FS as discussed above.
Thanks for your help Benjamin and congrats on great work with OSXFUSE
