### ISSUE TITLE
I can't copy file in external disk NTSF

### ISSUE THREAD

**Issue by palcoleas** [osxfuse/osxfuse#245]
I have installed osxfuse in my mac to copy files to external disk ntsf, but i tried to copy files and permission is still "you can only read". How can I fix this issue?
Thanks,

**Comment by bfleischer** [comment]
What you need is an actual NTFS file system driver! osxfuse is a framework that can be used by third-party developers to build file system drivers like NTFS-3G. NTFS-3G is the most popular open-source NTFS file system implementation. If you search the internet you will find many howtos explaining how to install NTFS-3G on OS X.
