### ISSUE TITLE
How to enable trashes in OSX

### ISSUE THREAD

**Issue by dakkusingh** [osxfuse/osxfuse#246]
Hi All,
I am using encfs and using osxfuse to mount my folder as fllows

```
encfs -f encrypted mount -oallow_root -olocal -onolocalcaches 
```

I am unable to get trash working on 10.11.1. When trying to delete a file I get notification that file will be deleted immediately.

Any ideas how i can get this working?

**Comment by bfleischer** [comment]
You need to create the `.Trashes` folder on the FUSE volume yourself. After doing so files should not longer be deleted immediately. I have not verified this for EncFS, but it works for the loopback reference file system.

**Comment by dakkusingh** [comment]
thank you, that worked :dancers:

**Comment by blueredcat** [comment]
On sierra 10.12.2 this isn't working.

I mounted using encfs -f encrypted mount -oallow_root -olocal -onolocalcaches 

and created a .Trashes folder. Any suggestions?
