### ISSUE TITLE
NTFS-3G PrefPane?

### ISSUE THREAD

**Issue by FuriousZahn** [osxfuse/osxfuse#249]
Hi.
I installed "Fuse for OSX" with the compatibility layer, then installed NTFS-3G as in the wiki. Now my question is if it is possible to have a PrefPane ins System Preferences. Would be handy.
Thanks in advance.
Z

**Comment by bfleischer** [comment]
Hi,
NTFS-3G is maintained by Tuxera Inc. (https://www.tuxera.com). Tuxera offers a commercial version of NTFS-3G, called NTFS for Mac, which includes a preference pane and other additional features.
