### ISSUE TITLE
Spotlight issue #3781

### ISSUE THREAD

**Issue by dave-mcd** [osxfuse/osxfuse#252]
Despite a number of users who can get spotlight to work quite easily, I can't really get it to work, even with the loopback fs from the examples.

What I have so far:
* Downloaded loopback fs from the examples
* Added some static FUSE options:
 * `fuse_opt_add_arg(&args, "-olocal");`
 * `fuse_opt_add_arg(&args, "-okill_on_unmount");`
 * `fuse_opt_add_arg(&args, "-oextended_security");`
 * `fuse_opt_add_arg(&args, "-onative_xattr");`
 * `fuse_opt_add_arg(&args, "-oallow_other");`
 * `fuse_opt_add_arg(&args, "-odefault_permissions");`
 * `fuse_opt_add_arg(&args, "-omodules=subdir");`
* Started the file system: 
 * `mkdir ~/.fuse ~/fuse`
 * `loopback ~/.fuse ~/fuse`
* Spotlight is off by default - confirm with `mdutil -a -s`
* Enable spotlight on the volume: `mdutil -i on ~/fuse`
* I can see the `.Spotlight-V100` directory being created and populated on the volume 
* Create a bunch of text files with TextEdit
* Searching:
 * `mdfind` finds filename, content, color tag
 * Finder using ⌘  -  F finds filename and content, no color tags
 * Spotlight Search using ⌘  -  Space finds nothing
* If I re-start the loopback fs, I can't find my old files anymore, only new ones

So from my experience if something GUI related doesn't work on OSX with OSXFUSE, it's mostly due to some xattr not being handled correctly, but I double and triple checked everything. I have `com.apple.FinderInfo` as well as `com.apple.metadata`.

I also exhumed one of my 10.9 VMs and tried with TrueCrypt. Same result, although the color tags are working. The only other FS I could find that's reasonable new is BoxCryptor which supports Spotlight quite well (⌘  -  Space for files and content + Finder color tags in sidebar). But I also noticed they switched to bcfs so I'm kinda stuck there.

I don't even know if this issue is osxfuse related, wouldn't be the first time that something is buggy on osx, but maybe other users have the same experience and find this report. Any help is highly appreciated.

Dave

**Comment by bfleischer** [comment]
Spotlight works fine for me using loopback with osxfuse 3.1.0 on OS X 10.11:

```
mkdir /tmp/dir
mkdir /Volumes/loop
./loopback /Volumes/loop -omodules=threadid:subdir,subdir=/tmp/dir -oallow_other,native_xattr,volname=LoopbackFS -olocal
mdutil -i on /Volumes/loop
```

**Comment by ChristianPraherKoeppl** [comment]
Hi Dave,
I think I know the reason why Spotlight did not work for you: It seems as if you could only add volumes to the Spotlight index that are mounted underneath the "/Volumes" directory. 
I have tested this with mounts in the users home directory "~", the opt directory "/opt" and "/Volumes". Mount points have been treated exactly the same way with the same set of FUSE flags being set. 
It works like a charm inside "/Volumes" the other two locations "~" and "/opt" are plainly ignored by Spotlight.
So far I did also not find any documentation on how to tell Spotlight to also index volumes not mounted in the "/Volumes" directory. 
This also explains why it worked for Benjamin but not for you. 
=> Seems as if there was no Spotlight support for OSXFuse if the volume is mounted outside of "/Volumes"!

**Comment by bfleischer** [comment]
No feedback by original poster, closed

**Comment by blueredcat** [comment]
I had this issue
