### ISSUE TITLE
Where is /etc/fuse.conf?

### ISSUE THREAD

**Issue by hoonkai** [osxfuse/osxfuse#253]
I'm trying to use the `allow_other` option, but I believe I'd need to add `user_allow_other` to /etc/fuse.conf. I haven't got such a file, so could one be created manually?

Otherwise, how to use `allow_other` properly?

Thanks

**Comment by romjean** [comment]
Hi,
You should find or create the fuse.conf file into the /private/etc/ directory.
Cheers
RomJean

**Comment by bfleischer** [comment]
There is no `fuse.conf` file on OS X. As far as I know `fuse.conf` is read by the Linux `fusermount` tool, which does not exist on OS X.
