### ISSUE TITLE
kext cannot be loaded when VMware Fusion is running 

### ISSUE THREAD

**Issue by bitfrickler** [osxfuse/osxfuse#254]
osxfuse and VMware Fusion Professional 8.1.0 cannot peacefully coexist.

I start a machine in Fusion. Then I do:
```shell
sshfs root@alia:/ /Users/jarod/.mnt/alia -o auto,noappledouble,defer_permissions,volname=alia
```

This results in:
```
22.12.15 22:26:27,000 kernel[0]: Kext com.github.osxfuse.filesystems.osxfusefs start failed (result 0x5).
22.12.15 22:26:27,000 kernel[0]: Kext com.github.osxfuse.filesystems.osxfusefs failed to load (0xdc008017).
22.12.15 22:26:27,000 kernel[0]: Failed to load kext com.github.osxfuse.filesystems.osxfusefs (error 0xdc008017).
22.12.15 22:26:27,194 com.apple.kextd[50]: Failed to load /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext - (libkern/kext) kext (kmod) start/stop routine failed.
```

After I terminate VMware Fusion i can successfully mount via sshfs.
Now that the osxfuse kext is loaded, the following is logged when I try to start the machine again:

```
22.12.15 22:32:52,000 kernel[0]: vmmon: Loaded com.vmware.kext.vmx86 Version 0327.22.37 Build 3272237 (Nov 25 2015 16:30:27)
22.12.15 22:32:52,000 kernel[0]: vmmon: Warning: Failed to register the major device number.
22.12.15 22:32:52,000 kernel[0]: Kext com.vmware.kext.vmx86 start failed (result 0x5).
22.12.15 22:32:52,000 kernel[0]: Kext com.vmware.kext.vmx86 failed to load (0xdc008017).
22.12.15 22:32:52,000 kernel[0]: Failed to load kext com.vmware.kext.vmx86 (error 0xdc008017).
22.12.15 22:32:52,997 com.apple.kextd[50]: Failed to load /Applications/VMware Fusion.app/Contents/Library/kexts/vmmon.kext - (libkern/kext) kext (kmod) start/stop routine failed.
```

**Comment by bfleischer** [comment]
Can you reproduce this reliably? I'm using VMware Fusion 8.1.0 myself but have never run into the issue. Have you tried restarting your Mac?

**Comment by bitfrickler** [comment]
Well I'll be damned. I did reboot yesterday. To no avail. I just rebooted again. Now everything works fine.
Could this be a general problem with OSX?

Googling the message
```
Failed to register the major device number
```
tells me that those device numbers are limited.
Unfortunately I didn't save the output of kextstat yesterday so I can't compare with the current situation.

**Comment by bfleischer** [comment]
It looks like your Mac is running out of free device slots. It would be interesting to know which kexts are actually occupying all the slots. According to the kernel sources there are 20 free slots reserved to the user on OS X 10.5 to 10.8, but only 8 free slots on OS X 10.8 and later.

I'm going to close the ticket because this is issue is caused by a technical limitation of OS X rather than a bug in osxfuse. Should you run into this issue again, please post the output of kextstat.

**Comment by bitfrickler** [comment]
Ran into the issue again. I've attached output of kextstat.
[kextstat.txt](https://github.com/osxfuse/osxfuse/files/76417/kextstat.txt)

**Comment by rwohleb** [comment]
Bleh. I appear to have run into this same issue. Between VirtualBox and a couple of VPN clients, it appears I ran out of major device numbers. Killing off one of the VPN clients allowed Keybase to start up normally.
