### ISSUE TITLE
Cannot install from instructions on main README

### ISSUE THREAD

**Issue by blairg23** [osxfuse/osxfuse#255]
The instructions for installing from brew: 

***brew install homebrew/fuse/ntfs-3g*** sometimes result in the error **

**==> Installing ntfs-3g from homebrew/fuse**
**osxfuse: Building this formula from source isn't possible due to OS X**
**Yosemite and above's strict unsigned kext ban.**

**You can install with Homebrew Cask:**
**  brew install Caskroom/cask/osxfuse**

**You can download from:**
**  http://sourceforge.net/projects/osxfuse/files/**
**Error: An unsatisfied requirement failed this build.**

As the error mentions, using the command ***brew install Caskroom/cask/osxfuse*** will fix this problem.

**Comment by bfleischer** [comment]
This is not a bug in osxfuse.

Starting with OS X 10.10 all kernel extensions need to be digitally signed with a Apple Developer ID certificate. OS X refuses to load unsigned kernel extensions. As a result building osxfuse from source is no longer a viable option for Homebrew on OS X 10.10 and 10.11.

However, official pre-built osxfuse releases are digitally signed and will work on OS X 10.10 and 10.11. Hombrew Cask is a (unsupported) way of installing official releases.
