### ISSUE TITLE
warning: argument unused during compilation: '-pthread'

### ISSUE THREAD

**Issue by relan** [osxfuse/osxfuse#256]
LLVM linker does not support `-pthread` [option](https://github.com/osxfuse/fuse/blob/master/osxfuse.pc.in#L9):

```
clang -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse -g -O2   -o mount.exfat-fuse mount_exfat_fuse-main.o ../libexfat/libexfat.a -L/usr/local/lib -losxfuse -pthread -liconv 
clang: warning: argument unused during compilation: '-pthread'
```

This is a problem because I cannot use `-Werror`. Also, `_FILE_OFFSET_BITS` is excessive on OS X where `off_t` has always been 64-bit.

OSXFUSE 2.8.2; OS X 10.11.2; Xcode 7.2 (7C68); Apple LLVM version 7.0.2 (clang-700.1.81).

**Comment by bfleischer** [comment]
Thanks for the bug report.

**Comment by relan** [comment]
Thank you for the fast fix!
