### ISSUE TITLE
Can't build on El Capitan - working on Swift integration

### ISSUE THREAD

**Issue by wildthink** [osxfuse/osxfuse#263]
While the installed framework appears to work OK with the examples, I am trying to clean up some Swift integration issues and I can't build the framework locally (on El Capitan). What might I be missing?

Some of the errors I have encountered are...

➜  osxfuse git:(support/osxfuse-3) ./build.sh -t framework
T:framework          | Clean target
T:framework          | Build target for OS X 10.11
T:framework          | Failed to build target
Terminated: 15
➜  osxfuse git:(support/osxfuse-3) ./build.sh -t release
T:release            | Clean target
T:release            | Build target
T:distribution       | OS X 10.5 SDK not found
Terminated: 15
➜  osxfuse git:(support/osxfuse-3) ./build.sh -t library
T:library            | Clean target
T:library            | Build target for OS X 10.11
T:library            | Failed to make configuration

**Comment by bfleischer** [comment]
Try following the build instructions outlined in README.md. First you need to install autoconf, automake, libtool, and gettext. Then build the distribution target.

**Comment by misku** [comment]
You could also add `-v5` parameter, so you'll get more detailed information, why the build failed.

**Comment by wildthink** [comment]
I am able to do a "distribution" build after installing autoconf, automaker, lib tool and get text.

**Comment by busyBmitchell** [comment]
wow this developing stuff is off the rector. Its boring but when you don't get a brand new laptop its necessary to learn if your broke
