### ISSUE TITLE
Need to trigger Finder refresh

### ISSUE THREAD

**Issue by wildthink** [osxfuse/osxfuse#264]
What do I need to do to trigger a Finder refresh?
Specifically, when I change the name of a file "under the hood" how do I make sure this is "seen" in the filesystem in a way that the Finder or other system mechanisms will recognize that the update has occurred?

**Comment by wildthink** [comment]
umm, apparently the way to do this is to

`[[NSWorkspace sharedWorkspace] noteFileSystemChanged:changedFilePath];`

This does this the trick but I do (still) wonder if there isn't a low-level (via fuse) way this should be done.

**Comment by bfleischer** [comment]
For osxfuse 2.x the (non portable) libosxfuse function `fuse_purge_np()` can be used to purge the cached file contents for a specific file. This is useful if the file has been changed remotely. 

For osxfuse 3.x there are the standard functions `fuse_lowlevel_notify_inval_inode()` and `fuse_lowlevel_notify_inval_entry()`.

* `fuse_lowlevel_notify_inval_inode ()` is the new `fuse_purge_np()` 
* `fuse_lowlevel_notify_inval_entry()` should be what you are looking for.

You might still need to call `-[NSWorkspace noteFileSystemChanged:]` to get Finder to refresh the currently open window.
