### ISSUE TITLE
readdir ignores errors

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#265]
If reading directory contents returns an error to kernel, OSXFUSE (observed here v3.0.9) ignores it and falsely shows an empty directory, with directory listing not giving an error:

```console
capfuse3x:~ qa$ ls mnt
capfuse3x:~ qa$ echo $?
0
```

Log snippet:

```
2016/01/24 15:20:02 FUSE: <- Open [ID=0x2 Node=0x1 Uid=501 Gid=20 Pid=5201] dir=true fl=OpenReadOnly
2016/01/24 15:20:02 FUSE: -> [ID=0x2] Open 0x1 fl=0
2016/01/24 15:20:02 FUSE: <- Statfs [ID=0x3 Node=0x1 Uid=501 Gid=20 Pid=5201]
2016/01/24 15:20:02 FUSE: -> [ID=0x3] Statfs blocks=0/0/0 files=0/0 bsize=0 frsize=0 namelen=0
2016/01/24 15:20:02 FUSE: <- Access [ID=0x4 Node=0x1 Uid=501 Gid=20 Pid=5201] mask=0x1
2016/01/24 15:20:02 FUSE: -> [ID=0x4] Access
2016/01/24 15:20:02 FUSE: <- Read [ID=0x2 Node=0x1 Uid=501 Gid=20 Pid=5201] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2016/01/24 15:20:02 FUSE: -> [ID=0x2] Read error=file name too long
```

On Linux:

```console
$ ls mnt
ls: reading directory mnt: File name too long
```

Demonstrator program, OS X binary in [demo.zip](https://github.com/osxfuse/osxfuse/files/124127/demo.zip):

```go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"syscall"

	"bazil.org/fuse"
	"bazil.org/fuse/fs"
	_ "bazil.org/fuse/fs/fstestutil"
	"golang.org/x/net/context"
)

func usage() {
	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
	fmt.Fprintf(os.Stderr, "  %s MOUNTPOINT\n", os.Args[0])
	flag.PrintDefaults()
}

func main() {
	flag.Usage = usage
	flag.Parse()

	if flag.NArg() != 1 {
		usage()
		os.Exit(2)
	}
	mountpoint := flag.Arg(0)

	c, err := fuse.Mount(mountpoint)
	if err != nil {
		log.Fatal(err)
	}
	defer c.Close()

	err = fs.Serve(c, FS{})
	if err != nil {
		log.Fatal(err)
	}

	// check if the mount process has an error to report
	<-c.Ready
	if err := c.MountError; err != nil {
		log.Fatal(err)
	}
}

type FS struct{}

func (FS) Root() (fs.Node, error) {
	return Dir{}, nil
}

// Dir implements both Node and Handle for the root directory.
type Dir struct{}

func (Dir) Attr(ctx context.Context, a *fuse.Attr) error {
	a.Inode = 1
	a.Mode = os.ModeDir | 0555
	return nil
}

func (Dir) Lookup(ctx context.Context, name string) (fs.Node, error) {
	return nil, fuse.ENOENT
}

func (Dir) ReadDirAll(ctx context.Context) ([]fuse.Dirent, error) {
	// a silly error on purpose
	return nil, fuse.Errno(syscall.ENAMETOOLONG)
}
```

**Comment by bfleischer** [comment]
Thanks for the bug report! The error is received by the FUSE kernel extension but seemingly not reported to OS X. I'll look into it.

**Comment by bfleischer** [comment]
As far as I can tell the error is propagated from kernel back to user space. The following `readdir` application reports the error correctly.

```c
#include <dirent.h>
#include <errno.h>
#include <stdio.h>

int
main(int argc, char *argv[])
{
    int err = 0;
    DIR *dp;
    struct dirent *entry;
    
    dp = opendir(argv[1]);
    
    while (1) {
        entry = readdir(dp);
        if (!entry) {
            err = errno;
            break;
        }
        
        printf("%s\n", entry->d_name);
        
        telldir(dp);
    }
    
    closedir(dp);
    return err;
}
```

**Comment by tv42** [comment]
Oh damn, I had an eerie sense of having seen this before, and now I remember -- it's OS X (bsd?) `ls` that ignores the error! I didn't dig more into whether it's `libc` to blame or `ls` itself, but I remember looking at this before.

**Comment by tv42** [comment]
http://www.opensource.apple.com/source/file_cmds/file_cmds-242/ls/ls.c has an interesting comment,

```c
	/*
	 * If list is NULL there are two possibilities: that the parent
	 * directory p has no children, or that fts_children() returned an
	 * error.  We ignore the error case since it will be replicated
	 * on the next call to fts_read() on the post-order visit to the
	 * directory p, and will be signaled in traverse().
	 */
```

I wonder if that isn't actually true.

**Comment by tv42** [comment]
Yeah I'd like to just confirm one more round that I'm seeing weird results only when userspace is ignoring errors. Doesn't look like an OSXFUSE bug, at best FAQ fodder. Sorry and thanks.

**Comment by bfleischer** [comment]
> http://www.opensource.apple.com/source/file_cmds/file_cmds-242/ls/ls.c has an interesting comment,
> 
> ```c
> 	/*
> 	 * If list is NULL there are two possibilities: that the parent
> 	 * directory p has no children, or that fts_children() returned an
> 	 * error.  We ignore the error case since it will be replicated
> 	 * on the next call to fts_read() on the post-order visit to the
> 	 * directory p, and will be signaled in traverse().
> 	 */
> ```
> 
> I wonder if that isn't actually true.

I was wondering that, too. On the post-order visit `fts_read()` (`fts_info == FTS_DP`) does not set `errno`. As a result the actual error is not being reported. To do this right `ls` would need to check `errno` in case of `fts_children()` returning `NULL`.

So I guess we can close this issue.

**Comment by misku** [comment]
I've recently came across this issue. Thank you guys for explaining the problem and thanks Benjamin for adding the log line.
