### ISSUE TITLE
Still can't write to NTFS volume

### ISSUE THREAD

**Issue by tdenta** [osxfuse/osxfuse#267]
Hello,

I followed the instructions for ntfs-3g installation [here](https://github.com/osxfuse/osxfuse/wiki/NTFS-3G), but I'm still unable to write on NTFS partitions.

I have FUSE 3.2.0 installed ([from here](https://github.com/osxfuse/osxfuse/releases)).
Before installing ntfs-3g, I : 

- disabled SIP as I'm running El Capitan (OSX10.11.13)
- updated homebrew

Now, just as before, my NTFS volume appears on my desktop when I plug my external drive in, I can also see it in the Finder, but I can only read its content and not paste files for example.

I'm out of ideas, any help would be strongly appreciated !

Thanks in advance.

**Comment by bfleischer** [comment]
I've updated the NTFS-3G installation instructions on https://github.com/osxfuse/osxfuse/wiki/NTFS-3G. The old document contained outdated information.

Please note that there is no need to disable SIP on El Capitan to get NTFS-3G working. I recommend re-enabling it.
