### ISSUE TITLE
3.2.0 - VeraCrypt 1.16/1.17 unable to detect version number correctly

### ISSUE THREAD

**Issue by jerrycopus** [osxfuse/osxfuse#268]
With version 3.2.0, both version 1.16 and the the current version 1.17 of VeraCrypt throw error "VeraCrypt requires OSXFUSE 2.3 or later with MacFUSE compatibility layer installer. Please ensure that you have selected this compatibility layer during OSXFUSE installation." during a container mount. Version 2.8.3 of OSXFUSE works as expected. This is using the installer linked on https://osxfuse.github.io/.

The MacFUSE framework is installed. Confirmed by manually deleting \Library\Frameworks\MacFUSE.framework (and OSXFUSE.framework) before installation.
![veracrypt116error](https://cloud.githubusercontent.com/assets/17318530/13149352/df8a2d3e-d626-11e5-869e-174fdb8e23f9.png)
![veracrypt117error](https://cloud.githubusercontent.com/assets/17318530/13149353/df8efb02-d626-11e5-8459-eb469f337696.png)

**Comment by bfleischer** [comment]
Please report this issue to the VeryCrypt team. VeryCrypt relies on the `osxfuse.version.number` sysctl to check the version number of osxfuse. In osxfuse 3.x the sysctl has moved to `vfs.generic.osxfuse.version.number`.

**Comment by pdomineaux** [comment]
Hello,

Does a solution exists to make VeraCrypt work with this OSXFuse 3.x ?

**Comment by michaelansel** [comment]
Just discovered this is actually fixed in https://github.com/veracrypt/VeraCrypt/commit/faf00ca1e093f0240f3cc668532f38b15e268da3 and available in the 1.18 nightly builds: https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/

**Comment by bfleischer** [comment]
@michaelansel Thanks for the update!
