### ISSUE TITLE
access() call not issued to the file system

### ISSUE THREAD

**Issue by smessmer** [osxfuse/osxfuse#269]
Osxfuse 2.8.3 (installed with home-brew cask) on OS X 10.11.3 El Capitan.

I have a test file system that just logs all requests coming in (and returns reasonable defaults). Then, I issue an access(2) syscall to the mountpoint at /myfile. The call never reaches my application. Here is the debug output (there are two kinds of [Log] lines. The [Log] [info] lines happen in the outer code making the access syscall, the [Log] [debug] lines happen in the inner code responding to calls from fuse. The other lines are debug output from osxfuse.)

```
[2016-02-19 20:49:12.154] [Log] [info] Starting access syscall to /myfile
unique: 3, opcode: ACCESS (34), nodeid: 1, insize: 48
ACCESS / 01
[2016-02-19 20:49:12.155] [Log] [debug] fuse: Incoming access("/", 1)
[2016-02-19 20:49:12.155] [Log] [debug] fuse: Incoming access("/", 1) returns 0
   unique: 3, error: 0 (Undefined error: 0), outsize: 16
   unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 47
LOOKUP /myfile
[2016-02-19 20:49:12.155] [Log] [debug] fuse: Incoming getattr("/myfile", _, _)
[2016-02-19 20:49:12.155] [Log] [debug] fuse: Incoming getattr("/myfile", _, _) returns S_IFDIR | S_IRUSR | S_IRGRP | S_IROTH | S_IXUSR | S_IXGRP | S_IXOTH
  NODEID: 2
   unique: 2, error: 0 (Undefined error: 0), outsize: 152
[2016-02-19 20:49:12.155] [Log] [info] Access syscall to /myfile returned 0
```

Why is osxfuse sending me a getattr() to /myfile, but never an access() (neither before nor after the getattr)? I'm only issuing an access() syscall, not a getattr() one. I tried mounting with "-o default_permissions", but that did't change the behavior, it produced the same output.

Note: On libfuse Linux (2.9.4), everything works fine and I get an access() call from fuse.

**Comment by pdautry** [comment]
Hi smessmer !

I had the same problem. Then I realized I was linking against **libfuse** directly via `-lfuse` and not **libosxfuse** with `-losxfuse`.
Since I changed my Makefile it works very well. It might be your solution.

Regards

**Comment by bfleischer** [comment]
Please reopen the ticket if this is still an issue with FUSE for macOS 3.x.
