### ISSUE TITLE
Can't install NTFS -3G

### ISSUE THREAD

**Issue by alosauruss** [osxfuse/osxfuse#270]
I can't install NTFS-3G in Terminal HomeBrew. When I enter the command, this is what I get 

sALs-Mac-mini:~ selaursa$ brew install homebrew/fuse/ntfs-3g
-bash: brew: command not found

**Comment by bfleischer** [comment]
It looks like Homebrew is not installed. You can find detailed installation instructions for NTFS-3G here: https://github.com/osxfuse/osxfuse/wiki/NTFS-3G
