### ISSUE TITLE
3.2.0 offers update to 2.8.3

### ISSUE THREAD

**Issue by noyannus** [osxfuse/osxfuse#271]
...puzzling. 

![screenshot 2016-02-22 um 14 11 10](https://cloud.githubusercontent.com/assets/6339921/13219134/4f2ca0d2-d96e-11e5-8682-68ba4ba83484.png)

**Comment by bfleischer** [comment]
3.2.0 is currently in developer preview, 2.8.3 is the latest stable release. If the "beta" checkbox in the preference pane is unchecked (which seems to be the case) you are offered to "update" to the latest stable release.
