### ISSUE TITLE
Odd problem since OS X fuse installed

### ISSUE THREAD

**Issue by deannerene** [osxfuse/osxfuse#272]
I have a large tape library (Quantum i500) with 4 LTO drives,  We also have an external LTO drive connected via SAS.  We use the system mainly for archiving and backup.  It is run by Archiware P5 software that manages the tape library, drives and robot.  It has run fine since we installed it.  Then we started getting requests for LTFS exports of the data.  The P5 sales pitch included LTFS so we though this would be okay.  

The system has LTFS as an "add on" and required the installation of fuse.  They installed an older version than was currently available but we complied with their recommendation.  The first test was to read an LTFS tape.  Using the external drive things worked fine.  Our problem starts with making LTFS tapes.  The system requires us to "Label" the tape.  This is a process like formatting.  Then the system tests the tape by trying to mount the tape.  In our system this usually but not always fails.

The support folks at Archiware have been helpful but not overly quick.  And they support their software but not the computer part of the equation.  The thing that I have noticed is that there is an error that crops up is tied to one or more of the fiber connected devices IOCreatePlugInInterfaceForService.  While this error doesn't stop any other process involving the tape drives, it is present when the LTFS tapes fail.

I am unable to test the LTFS tapes without Fuse but I am able to say the above error is not present when I uninstall fuse and run other tests.  Does anybody have a suggestion as to how I track this sown?

**Comment by bfleischer** [comment]
Your issue goes way beyond osxfuse. I do not know how I could be of assistance.

osxfuse does not use I/O Kit so I do not think it is to blame for the IOCreatePlugInInterfaceForService error you are seeing. I cannot speak for LTFS, though.

You could try posting this issue on the osxfuse Google Group at https://groups.google.com/forum/#!forum/osxfuse-group. This might give you a bigger audience, but I think Archiware's support team might be best equipped to help you.

By the way, Archiware's MediaLTFS package includes an unofficial version of osxfuse. They seem to be shipping a modified version of osxfuse 2.5.6 that is 3 years old. The latest version of OS X supported by the official osxfuse 2.5.6 release is OS X 10.8. Using 2.5.6 on any later version of OS X can cause kernel panics and result in data corruption or loss.
