### ISSUE TITLE
osxfuse causes boot freeze after 10.11.3 upgrade

### ISSUE THREAD

**Issue by chriswiggins** [osxfuse/osxfuse#273]
Just a note that having osxfuse caused my 10.11.3 upgrade on my rMBP 15" to fail TWICE over the course of a month. 

First time around I was able to recover from Time Machine and went back to 10.11.2 and put it down to freak accident. Enter yesterday afternoon when I decided to do the update again, same problem happened. Basically when starting in Verbose mode the mac doesn't get past **Waiting for DSMOS**

Extensive searching around Apple forums suggests a few things, and one of them is to `rm -rf /Library/Filesystems/*fuse*` - doing this resolved my problem and all I had installed was osxfuse.

Has this problem been encountered by anyone else? Thought I'd report in case there's something funny going on with osxfuse somewhere?

Happy bug hunting ;-)

**Comment by bfleischer** [comment]
Could you add the links to the Apple forum posts?

**Comment by chriswiggins** [comment]
[Main discussion link](https://discussions.apple.com/message/29059688#29059688)

**Comment by bfleischer** [comment]
Did you execute only the `rm -rf /Library/Filesystems/*fuse*` part or did you execute all those commands from the post?

I'm assuming you were updating from OS X 10.11.2 to 10.11.3, correct? Which version of osxfuse were you using when the update failed?

On its own osxfuse will not be loaded automatically when OS X starts. Are you using any auto-mounting FUSE file systems like NTFS-3G?

**Comment by bfleischer** [comment]
No feedback in months, closed.
