### ISSUE TITLE
No more MacFUSE compatibility layer with source build? (For VeraCrypt)

### ISSUE THREAD

**Issue by Creaturo** [osxfuse/osxfuse#275]
Hi,

Looks like the MacFUSE compatiblity layer support got dropped recently, guessing from the commit messages and the absence of a install option for it in the source built distribution package.
<img width="732" alt="bildschirmfoto 2016-03-04 um 03 43 32" src="https://cloud.githubusercontent.com/assets/4442056/13516526/4fa93462-e1bb-11e5-9ca1-9932386a5ff2.png">

I am on OS X 10.11.3 and thus can't install version 2.8.3 over brew and I try to avoid the 'unsecure' SourceForge downloads over HTTP.

How can I install FUSE for OS X with MacFUSE compatiblity layer support to satisfy VeraCrypt's dependencies?

**Comment by bfleischer** [comment]
There are currently three branches in the osxfuse repository:

* master: Will eventually become osxfuse 4.x but this is not happening anytime soon. It will no longer contain the MacFUSE compatibility layer.
* support/osxfuse-2: osxfuse 2.x releases. Includes the MacFUSE compatibility layer 
* support/osxfuse-3: osxfuse 3.x releases. Includes the MacFUSE compatibility layer 

So, if you build any of the support branches (and use the correct build options) you will get a version of osxfuse with the MacFUSE compatibility layer. To build the osxfuse 3 distribution target with the MacFUSE compatibility layer run the following commands:

    git clone --recursive -b support/osxfuse-3 git://github.com/osxfuse/osxfuse.git osxfuse
    cd osxfuse
    git checkout osxfuse-3.2.0
    git submodule update
    ./build.sh -v5 -t distribution -- --macfuse

Don't forget to install the build dependencies first. See README.md for details.

Once the build is done the resulting distribution package will be located at `/tmp/osxfuse/distribution/Distribution.pkg` 

> I am on OS X 10.11.3 and thus can't install version 2.8.3 over brew and I try to avoid the 'unsecure' SourceForge downloads over HTTP.

Why can't you install osxfuse 2.8.3 over brew? `brew install Caskroom/cask/osxfuse` works for me on 10.11.3.

Let me say that SourceForge has never touched osxfuse downloads and I do not have reason to believe they would. Bun nonetheless you can find SHA1 checksums for every osxfuse download on http://osxfuse.github.io, so you can easily verify that no one has tampered with the file you downloaded. On top of that every official osxfuse installer package is digitally signed by me. You can verify the signature when clicking on the certificate symbol in the top right corner of the installer. Tampering with the installer package would invalidate the signature.

osxfuse 3.x downloads have moved back to GitHub. You can download the latest release from https://github.com/osxfuse/osxfuse/releases.
