### ISSUE TITLE
encfs breaks on high IO

### ISSUE THREAD

**Issue by axet** [osxfuse/osxfuse#276]
It may be actually osxfuse bug.

Hello!

I'm using encfs @1.8.1_1 (osxfuse @2.8.2) on Mac Yosimite 10.10.5 with my private folder. This folder includes a lot of small files (source code). And working with eclipse or git on encrupted folder can cause a file lost/lock/corrupt file system.

This bug easy to reproduce. Just create encfs folder and clone a source tree into it. You will get a few errros, then removing a folder cause another on encfs space.

```
# git clone http://github.com/golang/go gg
```

* https://trac.macports.org/ticket/48705
* https://github.com/vgough/encfs/issues/109

**Comment by bfleischer** [comment]
This was fixed in osxfuse 3.0.9. See osxfuse/osxfuse#228 for details.
