### ISSUE TITLE
finder not fresh filename  if other remote client rename a file

### ISSUE THREAD

**Issue by shenwen2012** [osxfuse/osxfuse#279]
When I modify the file name of a file in a remote terminal, click enter a directory in the finder, through the tracking code found that did not receive the opendir and readdir requests. But I execute the LS command in the terminal, can receive the opendir and readdir request, and can refresh the file name.

**Comment by bfleischer** [comment]
It is the responsibility of the file system to communicate remote changes back to OS X. If the file system does not support this you could try to disable all local caching when mounting the volume. you can find a list of all available mount options on https://github.com/osxfuse/osxfuse/wiki/Mount-options.

Which file system are you using?

**Comment by shenwen2012** [comment]
the file system by myself develop.I found the reason, because I used option “local”，so it will be a problem. But in my application，must be use this option.Is there a way to use this“local”option ，can also solve this problem?

**Comment by bfleischer** [comment]
As I said you could try to disable al local caching using the mount option `nolocalcaches `. If this is not enough you could try looking into the libosxfuse functions `fuse_lowlevel_notify_inval_inode()` and `fuse_lowlevel_notify_inval_entry()` to notify the osxfuse kernel extension of remote changes.

Please note that `fuse_lowlevel_notify_inval_inode()` and `fuse_lowlevel_notify_inval_entry()` are not available in osxfuse 2.x. You will need osxfuse 3.x.

**Comment by shenwen2012** [comment]
thanks,i try.
