### ISSUE TITLE
v3.2.0 is not compatible with LaCie Private-Public.app

### ISSUE THREAD

**Issue by Squibob** [osxfuse/osxfuse#280]
Try to open Private-Public.app and get the following message:

_OSXFUSE with MacFUSE Compatibility Layer is required for LaCie Private-Public.  Click Install to continue and start using LaCie Private-Public. (Administrator privileges are required  to perform this installation)._

When I hit the Install button, a request for the Administrative password appears.  After entering the password, I get the following Error Message:

_Error while installing OSXFuse.
Please try again later._

Will downgrade back to 2.8.3 for now.

**Comment by Squibob** [comment]
An update:

I still cannot use Private-Public after downgrading to v 2.8.3.  Yes, I restarted the computer.

Will remove OSXFUSE outright and see what happens.

**Comment by Squibob** [comment]
LaCie requires OSXFUSE v2.8.3 with MacFuse still incorporated. So when you have OSXFUSE installed you have to make sure MacFuse is included.  FYI when Private0-Public is installed it has OSXFUSE v2.7.2 in its Package Contents,

**Comment by bfleischer** [comment]
There are some differences between osxfuse 2.x and 3.x. Lacie Private-Public seems to be unable to detect if osxfuse 3.x is installed and prompts to install its bundled version of osxfuse (2.8.0 as far as I can tell). 

Private-Public is closed source, so I do not know how LaCie tries to detect if osxfuse is installed or not. This is something that needs to be fixed by LaCie. Please raise the issue with LaCie.

**Comment by kilokoloko** [comment]
hi everybody

i have the same problem.
After upgrading fuse and tuxera to the newest version on mac high sierra, private-public hasn't been working.

need help pls

<img width="616" alt="capture d ecran 2018-05-11 a 11 29 36" src="https://user-images.githubusercontent.com/39187150/39917675-feaf180c-5516-11e8-8b5f-18b6e280c40b.png">
<img width="455" alt="capture d ecran 2018-05-11 a 11 29 47" src="https://user-images.githubusercontent.com/39187150/39917691-06c1ec18-5517-11e8-9158-000439d2232f.png">

i downloaded new version of Privatepublic-1.9.9.dmg
it will be working only on macs hard drive

how to re-install ht private-public application directly on hard drive ?

<img width="748" alt="capture d ecran 2018-05-11 a 12 32 52" src="https://user-images.githubusercontent.com/39187150/39917853-7846a18a-5517-11e8-9df0-a6971cc9c93d.png">
