### ISSUE TITLE
Available Space is wrong

### ISSUE THREAD

**Issue by aspetko** [osxfuse/osxfuse#281]
Hi, 
I connect to a linux fileserver with approx. 65 TB of free space. I am connecting to the fileserver using sshfs and osxfuse, Instead of seeing the 65 TB, I see only 10GB of free space. Finder uses the wrong amount to calculate if I can move files to the fileserver or not. 

The problem is not the Mac or finder because using scp I can transfer the files. 

Cheers Alexander

**Comment by bfleischer** [comment]
Have you checked that 10 GB is not the quote for this user?

**Comment by aspetko** [comment]
Hi, 

yes this is not the problem. Since I have reported the problem I have moved approx. 16 TB using this user. By the way, the user we are talking about is the root!

After the space was used up, finder declined me to move additional files. I have rebooted and it showed me 10 TB are free. The truth is, that a df -h displays 57 TB of free space.

As a work around, I am using a mac port of midnight commander. mc does not decline moving files.

Cheers Alexander

**Comment by bfleischer** [comment]
Does sshfs on Linux report the correct free space? As far as i know reporting free volume space is an ssh extension that need server support to work.

**Comment by bfleischer** [comment]
Could you check if you are still seeing this issue with osxfuse 3.3.0. The new version supports a wider range of block sizes. Mounting a file system with an unsupported block size could result in wrong size calculations.

**Comment by aspetko** [comment]
Sorry, I am on a business trip at the moment. I will check, as soon as I am back.

**Comment by bfleischer** [comment]
Can this issue be closed?
