### ISSUE TITLE
not mount disk by add "local" option

### ISSUE THREAD

**Issue by chengelvis** [osxfuse/osxfuse#282]
I am using FUSE to development a YunFile client，when I add “local” option for mounting，sometimes can not mount disk.
who can help you what is happen?
thanks~~

**Comment by chengelvis** [comment]
I see "fseventsd[48]: failed to make the directory /Volumes/AnyShare/.fseventsd (6/Device not configured)" in the console log,but I don't know what happen,who can help me?

**Comment by bfleischer** [comment]
You should really ask questions like these in our Google group https://groups.google.com/forum/#!forum/osxfuse-group. This way you get a wider audience.

Please see https://github.com/osxfuse/osxfuse/wiki/Mount-options#local regarding "local" mounts. "local" mounts are known to cause issues for some users but there is not much that can be done from the osxfuse end of things. "local" is simply a flag that can be set for volumes. How it is handled by Finder and friends is pretty much undocumented. Mounting the loopback reference file system with the "local" flag set works for me fine, though.

**Comment by chengelvis** [comment]
much thanks to bfleischer, I discovered that adding  "local" option work fine in OSX 10.10,but sometimes not work in OSX 10.11. Maybe has compatibility problem.
