### ISSUE TITLE
Update Checker uses insecure HTTP

### ISSUE THREAD

**Issue by willneumob** [osxfuse/osxfuse#283]
When opening the FUSE control panel, it tries to make a connection over port 80 to `osxfuse.github.com`.

While I haven't verified that the actual software download occurs over insecure HTTP, even the update check should use TLS. Using HTTP allows the binary content of the application to be modified by a MiTM attack.

<img width="922" alt="screen shot 2016-05-21 at 2 40 00 pm" src="https://cloud.githubusercontent.com/assets/17169241/15450998/96da3404-1f63-11e6-8749-8b1cf29f44fd.png">

**Comment by bfleischer** [comment]
The update checker downloads a digitally signed property list containing the download link and the hash value of the update itself. The property list's signature is checked before downloading the update. After downloading the update its hash value is checked, too.

It does not really matter if the files are loaded over http or https. A man in the middle would not be able to alter the update without being detected.

Nonetheless osxfuse 3.x loads updates over https, version 2.x uses http.
