### ISSUE TITLE
3.3.0 does not work on ML

### ISSUE THREAD

**Issue by takovej** [osxfuse/osxfuse#284]
I've upgraded from version 3.2.0 to 3.3.0, installer end up with success however Fuse pref. pane says that OSXFUSE does not appear to be installed. Running ML 10.8.5 with latest updates. Downgrading back to 3.2.0 works fine again.

**Comment by bfleischer** [comment]
Thanks for the bug report. The version number check in the preference pane is broken in 3.3.0. Mounting file FUSE file systems should work fine though. 3.3.1 fixes the bug.
