### ISSUE TITLE
Update version incorrect

### ISSUE THREAD

**Issue by plguidez** [osxfuse/osxfuse#285]
I have 3.3.2 installed but the Preference Pane tells me I have an update available which is really a downgrade to 2.8.3. When I select "Show beta version", I correctly see "No updates available at this time"

**Comment by bfleischer** [comment]
This has been reported a couple of times before. The text displayed by the preference pane might be a bit confusion but the behavior is correct.

When you are on the beta channel the currently newest version is 3.3.2. On the "stable" channel it is 2.8.3. The preference pane tells you that you are not using the latest stable version and offers to install it. It does not care if this is an upgrade or a downgrade.
