### ISSUE TITLE
lookup() not called when readdir() returns inode with lowest 32bits set to 0

### ISSUE THREAD

**Issue by korczis** [osxfuse/osxfuse#286]
Hi,
I am experiencing strange behavior when readdir returns entry which has lowest 32bits set to zero.

Not working inode number
- `3659174697238528` - `1101000010100000000000000000000000000000000000000000b`

**Application Log**

```
GoodDataFS::readdir() - Reading inode 3659174697238528 - Inode { project: 13, category: 0, item: 0, reserved: 0 }
GoodDataFS::readdir() - Adding inode 3670169813516288 - Inode { project: 13, category: 10, item: 0, reserved: 0 }, project 12, path metadata
```
Working inode number
- `3670169813516289` - `1101000010100000000000000000000000000000000000000001b`

**Application Log**

```
GoodDataFS::readdir() - Reading inode 3659174697238528 - Inode { project: 13, category: 0, item: 0, reserved: 0 }
GoodDataFS::readdir() - Adding inode 3670169813516289 - Inode { project: 13, category: 10, item: 0, reserved: 1 }, project 12, path metadata
GoodDataFS::lookup() - Reading parent 3659174697238528 - Inode { project: 13, category: 0, item: 0, reserved: 0 }, path "metadata"
```

**Environment**
- Mac OS X El capitan 64 bit

**node id format**

| Bits | Offset | Description  | Limit            |
|------|--------|--------------|------------------|
| 16   | 48     | Project ID   | 65535 projects   |
| 8    | 40     | Category ID  | 256 [categories](https://github.com/korczis/gooddata-fs/blob/master/doc/Filesystem.md#category-id)   |
| 32   | 8      | Item ID      | 4294967295 items |
| 8    | 0      | Reserved     | 256 reserves ;-) |

For more info see [documentation](https://github.com/korczis/gooddata-fs/blob/master/doc/Filesystem.md#i-node-id-format)

PS: I tried to compile same code on linux and it works without any problems.

Am I missing something? Am I doing something wrong? I tried to search if there are any requirements for inode format but I found nothing.

**Comment by bfleischer** [comment]
Which version of osxfuse are you using?

**Comment by korczis** [comment]
I firmly believe that I am using 2.8.3

**Comment by bfleischer** [comment]
Version 2.8.3 does not support 64 bit inodes in readdir. However, version 3.0.3 and later do. Could you check if you are still seeing the issue with version 3.3.2?

**Comment by korczis** [comment]
@bfleischer Yop, it works with 3.0.3+. Closing.

**Comment by bfleischer** [comment]
Thanks for the update
