### ISSUE TITLE
SSHFS: OSX 10.11 (El Capitan): read failures when accessing too many file concurrently

### ISSUE THREAD

**Issue by Dev0Null** [osxfuse/osxfuse#287]
Using the most recent OSXFUSE/SSHFS, I'm noticing some interesting issues when compiling applications which have headers, libraries, and other dependencies on SSHFS shares. If I compile a simple application via `make' with a single thread/job (ie: `make -j1'), all is well. Same with 2 jobs. As I increase the number of jobs though, I randomly start encountering issues where I get read errors while make/gcc attempts to read various header files (ie: Operation not permitted).

As I increase the number of jobs, the chances of this issue increase significantly. 4 jobs gives a 50% chance of the issue arising when building a project with roughly 100 `.cpp' files, and is a guarantee with 6 jobs.

This issue did not occur on the exact same machine several months back with (presumably) an older version of OSXFUSE/SSHFS, so I'm assuming this is either a regression in SSHFS, or a discovered issue using a newer version of El Capitan (ie: from a system update).

If any log files or traces are needed, please let me know, and I can setup a debug build to attempt to re-create the issue.

Cheers!

**Comment by bfleischer** [comment]
Which versions of osxfuse and sshfs are you using?

**Comment by Dev0Null** [comment]
sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.8.3


============================================================
Matthew Giassa, MASc, BASc, EIT
Security and Embedded Systems Specialist
linkedin: https://ca.linkedin.com/in/giassa
e-mail:   matthew@giassa.net
website:  www.giassa.net

**Comment by bfleischer** [comment]
sshfs 2.5.0 has been released in February 2014, osxfuse 2.8.3 in January 2016. I have not received similar bug reports before. Could you check if the issue is sever-related? Maybe the ssh server process tries to open too many files at the same time.

**Comment by Dev0Null** [comment]
After considering your comment, I dug depper. It turns out the file server which hosts the files accessed by client machines via SSHFS had been upgrade, but </etc/ssh/sshd_config> had not been updated to accommodate the large number of connections normally expected. This is not an issue in SSHFS. Thanks for the heads-up.
