### ISSUE TITLE
borgbackup files are not accessible with the finder

### ISSUE THREAD

**Issue by tristan-k** [osxfuse/osxfuse#288]
> BorgBackup (short: Borg) is a deduplicating backup program.

Mounting the [borg](http://borgbackup.readthedocs.io) repo works just fine but the actual files stored inside are not accessible. In the mac os x finder (file browser) they all have a size of 0 Byte. Trying to copy files outside the fuse volume results in a `Error -36`. This must be related to the `Finder`. Editing and copying the files with the `Terminal` works.

```
$ borg --version
borg 1.0.4.dev273+ngbf5406d

$  brew cask info osxfuse-beta
osxfuse-beta: 3.3.2
OSXFUSE
https://osxfuse.github.io/
/opt/homebrew-cask/Caskroom/osxfuse-beta/3.3.2 (25 files, 6,8M)
https://github.com/caskroom/homebrew-versions/blob/master/Casks/osxfuse-beta.rb
==> Contents
  Extras/FUSE for OS X 3.3.2.pkg (pkg)
==> Caveats

$ borg mount --foreground ~/Desktop/borg-repo ~/Desktop/BorgBackup
```

**Comment by bfleischer** [comment]
I think this is something the Borg team needs to investigate. The loopback reference file system works fine with osxfuse 3.3.2. Finder acting up can mean that the root user does not have access to the volume.

**Comment by ThomasWaldmann** [comment]
Looks like one needs `-o allow_other` mount option to make it available for root (didn't try finder, but this makes it work for root user on the shell).

Somehow unexpected, usually root can see / do anything.

Thanks for the hint about root, didn't know that finder runs as root.

**Comment by tristan-k** [comment]
Just tried `borg mount -o allow_other ~/Desktop/borg-repo ~/Desktop/BorgBackup` without success.

**Comment by bfleischer** [comment]
Finder relies on helper processes that run as root. osxfuse already has exceptions built in that allow file system requests by Finder even if `allow_root` and `allow_other` are not set. I don't know borg but does it implement its own access control mechanism?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/master/src/borg/fuse.py

It reflects user, group, mode and xattrs as they were stored into the backup archive.
AFAICS, there are no special checks beyond that.

**Comment by bfleischer** [comment]
Ok, let's try to approach this from another angle: Do you know when borg last worked with Finder and which version of osxfuse you were using at that time?

**Comment by ThomasWaldmann** [comment]
I've never tested it myself with finder as I only have ssh access to an OS X machine.

**Comment by bfleischer** [comment]
@tristan-k Do you know if Borg worked with Finder before? To me it looks like this might be a Borg issue after all.

**Comment by tristan-k** [comment]
@bfleischer I was never able to access files through Finder. Not with osxfuse 3.2.0 and precompiled borg binary nor with osxfuse 3.3.2 and self compiled borg from git.

**Comment by bfleischer** [comment]
I think it is safe to assume that this is a Borg issue. Maybe some file system callbacks are not implemented. The issue might be related to extended attributes. Finder relies on them heavily. But without knowing Borg or the Python FUSE bindings this is just a wild guess.

I'm going to close the issue. Please feel free to reopen it if you find evidence that suggests osxfuse is to blame.
