### ISSUE TITLE
After Mac sleep: "status changed for fs" "Failed to Mount"

### ISSUE THREAD

**Issue by nottoseethesun** [osxfuse/osxfuse#29]
Using MacFusion with OSXFuse with SSHFS, and clicking on MacFusion 'mount' after waking MacBook Pro Snow Leopard up-to-date (but in 32-bit mode) from sleep, I get a GUI window that says, "Could not mount filesystem: Authentication has failed."  

However, the log (below) says authentication succeeded but the filesystem could not be mounted:

```
  "Note status changed for fs" "Failed to Mount".  
```

Otherwise, my MacFusion/OSXFuse/sshfs set-up works fine: For example, if I reboot, I am then able to connect.

This could be caused by not unmounting before putting the Mac to sleep.    If so then a hook would be needed to cleanly unmount on sleep.

Log:

(SSHServerFS, cbalz_rhel_box_...n, 5/2/12 9:35 40AM) debug1: Authentication succeeded (password).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.

(SSHServerFS, cbalz_rhel_box_...n, 5/2/12 9:35 40AM) debug1: Sending subsystem: sftp

(MFClient, cbalz_rhel_box_...n, 5/2/12 9:35 40AM) Note status changed for fs <MFClientFS: 0x20008b9e0> (cbalz_rhel_box_...n) to Failed to Mount

(SSHServerFS, cbalz_rhel_box_...n, 5/2/12 9:35 40AM) debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
debug1: fd 2 clearing O_NONBLOCK
Transferred: sent 2256, received 2072 bytes, in 0.0 seconds
Bytes per second: sent 163253.7, received 149938.7
debug1: Exit status 0

Steps to Reproduce:

1) Install MacFusion with OSXFuse, using sshfs, on MacBook Pro with up-to-date Snow Leopard (Mac OS X 10.6.8 (10K531), Darwin 10.8.0, 64-bit Kernel and Extensions:No, Secure Virtual Memory:Enabled, Boot Mode:Normal) and follow all the instructions on the set-up page.  
2) Verify installation working correctly with an sshfs mount (not sftp).
3) Put Mac to sleep (sleep mode - e.g., close lid)
4) Wake Mac (open lid)
5) Bring MacFusion to focus
6) Click "Mount"

**Comment by evisong** [comment]
https://github.com/osxfuse/osxfuse/issues/45#issuecomment-217083726

In my case, osxfuse/macfusion cannot resume after Mac wake up from a sleep, moreover I always fail to re-mount unless I reboot the Mac.

hdiutil eject -force <full mount path>
This solution works for me, I can re-mount after that.
