### ISSUE TITLE
OS X Fuse 2.8.3 can't be installed on macOS Sierra

### ISSUE THREAD

**Issue by bmerindol** [osxfuse/osxfuse#290]
OS X fuse installer doesn't allow to be ran on macOS Sierra 10.12 (Beta)

**Comment by bfleischer** [comment]
Please check out the new 3.4.0 release. I do not plan on releasing a new osxfuse 2.x build for macOS 10.12.

**Comment by leames** [comment]
3.5.2 also doesn't install on Sierra. Just saying.

**Comment by bfleischer** [comment]
@leames The official 3.5.2 release works just fine on Sierra. Are you using a third-party build?

**Comment by leames** [comment]
Hmm. I thought I was. I'll take a look.

**Comment by leames** [comment]
My mistake. Fuse works great. It's the ext package that won't install. :-(
