### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by catwell** [osxfuse/osxfuse#291]
Hello,

I have a few patches I would like to submit to you. What is the prefered way for this? Pull requests against `support/osxfuse-3`? Against `master`?

You may want to [add a CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file to make this explicit too.

**Comment by bfleischer** [comment]
Hi,

It depends on the nature of the patches. Bugfixes should go in `support/osxfuse-3`, changes that break backward compatibility in `master` (the next major release).

**Comment by catwell** [comment]
Thank you, closing this, I have my answer!
