### ISSUE TITLE
The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

### ISSUE THREAD

**Issue by sunk818** [osxfuse/osxfuse#292]
I'm using macOS 10.10.5. I was getting an error in the installation. It seems I needed a /private/tmp directory. I had to `sudo mkdir /private/tmp` and then re-do the installation.

Jun 25 21:22:31 Suns-MacBook-Pro.local installd[479]: PackageKit: Install Failed: Error Domain=NSPOSIXErrorDomain Code=2 "The operation couldn’t be completed. No such file or directory" UserInfo=0x7fd2b2e0bb90 {NSFilePath=/private/tmp/PKInstallSandbox.XXXXXX} {
	    NSFilePath = "/private/tmp/PKInstallSandbox.XXXXXX";
	}
Jun 25 21:22:31 Suns-MacBook-Pro.local installd[479]: PackageKit: Running idle tasks
Jun 25 21:22:31 Suns-MacBook-Pro.local installd[479]: PackageKit: Done with sandbox removals
Jun 25 21:22:31 Suns-MacBook-Pro.local installd[479]: PackageKit: Removing client PKInstallDaemonClient pid=956, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Jun 25 21:22:31 Suns-MacBook-Pro.local Installer[956]: install:didFailWithError:Error Domain=NSPOSIXErrorDomain Code=2 "The operation couldn’t be completed. No such file or directory" UserInfo=0x7fda71ee4d70 {NSFilePath=/private/tmp/PKInstallSandbox.XXXXXX}
Jun 25 21:22:31 Suns-MacBook-Pro.local Installer[956]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jun 25 21:22:31 Suns-MacBook-Pro.local Installer[956]: IFDInstallController 71E59AB0 state = 8
Jun 25 21:22:31 Suns-MacBook-Pro.local Installer[956]: Displaying 'Install Failed' UI.
Jun 25 21:22:31 Suns-MacBook-Pro.local Installer[956]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by bfleischer** [comment]
The `/private/tmp` directory is a standard OS X directory and should always exist. I don't know why it got lost on your Mac. I think you would have gotten the same error trying to install any other installer package. The issue is not related to the FUSE installer but to your environment.

**Comment by BLaurent** [comment]
Hi I do Have the same kind of issue here on el capitain.
 brew cask install osxfuse                       ──(Thu,Nov24)─┘
==> Caveats
You must reboot for the installation of osxfuse to take effect.

==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.5
Already downloaded: /Users/benoitlaurent/Library/Caches/Homebrew/Cask/osxfuse--3.5.3.dmg
==> Verifying checksum for Cask osxfuse
==> Running installer script /usr/sbin/installer
Password:
==> installer: Package name is FUSE for macOS
==> installer: choices changes file '/usr/local/Caskroom/osxfuse/3.5.3/Extras/Ch
==> installer: Installing at base path /
==> installer: The install failed (The Installer encountered an error that cause
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- #<Pathname:/usr/sbin/installer> -pkg /usr/local/Caskroom/osxfuse/3.5.3/Extras/FUSE for macOS 3.5.3.pkg -target / -applyChoiceChangesXML /usr/local/Caskroom/osxfuse/3.5.3/Extras/Choices.xml

==> Standard Output of failed command:
installer: Package name is FUSE for macOS
installer: choices changes file '/usr/local/Caskroom/osxfuse/3.5.3/Extras/Choices.xml' applied
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
