### ISSUE TITLE
large setxattr(2) calls cause mount to die

### ISSUE THREAD

**Issue by tv42** [osxfuse/osxfuse#293]
A FUSE userspace server receives requests from `/dev/fuse` by allocating some memory and calling `read(2)`. Obviously, the request must fit into that buffer. With OSXFUSE, the size of the buffer is communicated to the kernel via the `iosize` mount option, most likely in an effort to 1) "right-size" actions where OSXFUSE/OSX can control the size 2) early reject requests with unreasonably large payloads (coming from userspace applications) .

Side note: why `iosize` and not `fuse_init_out.max_write`?

it seems OSX/OSXFUSE enforces a 16MB max extended attribute value size. If `iosize < 16MB`, there's a range where requests cannot be sent to the userspace FUSE server, but are not hard-forbidden by the kernel logic. Those requests seem to be poison.

```
# terminal 1
./hellofs-16mb-buffer -fuse.debug mnt

# terminal 2
./set-large-xattr mnt/hello
umount mnt

# observed in terminal 1
2016/06/28 22:07:16 FUSE: <- Setxattr [ID=0x3 Node=0x2 Uid=501 Gid=20 Pid=1160] "greeting" 68656c6c6f2c20776f726c6468656c6c... fl=0 @0x0
2016/06/28 22:07:16 FUSE: -> [ID=0x3] Setxattr
```

Now build again with a version of bazil.org/fuse with decreased
request buffer size:

```
diff --git i/fuse_darwin.go w/fuse_darwin.go
index b58dca9..2c30d1a 100644
--- i/fuse_darwin.go
+++ w/fuse_darwin.go
@@ -6,4 +6,4 @@ package fuse
 // forcibly close the /dev/fuse file descriptor on a Setxattr with a
 // 16MB value. See TestSetxattr16MB and
 // https://github.com/bazil/fuse/issues/42
-const maxWrite = 16 * 1024 * 1024
+const maxWrite = 8 * 1024 * 1024
```

```
# terminal 1
./hellofs-8mb-buffer -fuse.debug mnt

# terminal 2
$ ./set-large-xattr mnt/hello
input/output error
$ 

# observed in terminal 1
2016/06/28 22:09:35 FUSE: <- Access [ID=0x4 Node=0x1 Uid=501 Gid=20 Pid=1169] mask=0x1
2016/06/28 22:09:35 FUSE: -> [ID=0x4] Access
2016/06/28 22:09:35 FUSE: <- Lookup [ID=0x3 Node=0x1 Uid=501 Gid=20 Pid=1169] "hello"
2016/06/28 22:09:35 FUSE: -> [ID=0x3] Lookup 0x2 gen=0 valid=1m0s attr={valid=1m0s ino=2 size=13 mode=-r--r--r--}
2016/06/28 22:09:35 FUSE: <- Access [ID=0x2 Node=0x2 Uid=501 Gid=20 Pid=1169] mask=0x2
2016/06/28 22:09:35 FUSE: -> [ID=0x2] Access
$ 
$ mount|grep hello
helloworld on /Users/qa/mnt (osxfuse, local, nodev, nosuid, synchronous, mounted by qa)
$ ls mnt
ls: mnt: Device not configured
```

(The fact that there was no error is perhaps a bug in bazil.org/fuse
or `hellofs.go`; that's not relevant here.)

Poking further, going well above the 16MB boundary results in the same behavior:

```
$ ./set-large-xattr -size=16777216 mnt/hello
$ ./set-large-xattr -size=16777217 mnt/hello
$ ./set-large-xattr -size=17777217 mnt/hello
input/output error
$ 
```

(and the mount died on the last one)

I'm attaching a zip with the binaries and the repro helper sources:
[large-setxattr-bug.zip](https://github.com/osxfuse/osxfuse/files/340497/large-setxattr-bug.zip)

**Comment by bfleischer** [comment]
osxfuse is closing the FUSE device because the file system did not read the whole buffer. Linux seems to treat this differently. I have not tried it but from what I can see in the sources Linux only returns an error to user space but leaves the device open. This might be dangerous in case of fully asynchronous I/O.

For extended attributes > 16MB the FUSE kernel extension should return an error in vnop_setxattr. I'll need to look into that some more.

**Comment by tv42** [comment]
Perhaps there is be a way to make `vnop_setxattr` handle the short read in a per-op fashion, and not just wreck the whole mount? In this case, it could behave exactly like the >16MB case.

**Comment by bfleischer** [comment]
> it seems OSX/OSXFUSE enforces a 16MB max extended attribute value size.

The osxfuse 3.x kernel extension currently expects the user space FUSE server to be able to handle 32MB extended attribute values. Calling setxattr with anything > 32MB returns `E2BIG`.

**Comment by bfleischer** [comment]
I've made some changes to way osxfuse handles short reads. Version 3.4.1 should behave more like Linux. If you try to set an extended attribute value greater than the buffer size of the user space FUSE server, osxfuse should return `E2BIG` instead of killing the file system.
