### ISSUE TITLE
duplicate mount point in /Volumes (appending numeric suffix)

### ISSUE THREAD

**Issue by danzalot** [osxfuse/osxfuse#294]
duplicate mount point in /Volumes (e.g. /Volumes/DRIVE, /Volumes/DRIVE 1, ../DRIVE 2 etc)
or doesn't delete mount point after every unmount of removable usb drive
or doesn't use existing mount point for the same volume

osxfuse 2.8
el capitan 10.11.5
rtfs-org 2016.2.22

**Comment by bfleischer** [comment]
Please unplug your USB drive and delete all those `/Volumes/DRIVE...` folders manually. Then upgrade to osxfuse 3.4.0. Version 3.4.0 is currently in beta but should fix your issue.
