### ISSUE TITLE
Mac OSX EI /Volumes/ have many disk letter AND it doesn't show on Desktop

### ISSUE THREAD

**Issue by CloudnuY** [osxfuse/osxfuse#296]
I installed the NTFS-3G by brew and replaced the `mount-ntfs` file in Recovery Mode.

1. Plug in the external harddrive but it doesn't appeared on my desktop.

2. In `/Volumes/` folder, there are many disk letter such as `XXXX`, `XXXX 1`, `XXXX 2`, `XXXX 3`, but only the newest letter can open.  I unmounted my external driver by `Disk Utility` or right click on disk icon or directly plug out, but `XXXX (number)` still exist.

**Comment by bfleischer** [comment]
Please unplug your external drive and remove all those numbered folders manually. Then follow the NTFS-3G installation guide on https://github.com/osxfuse/osxfuse/wiki/NTFS-3G and make sure to upgrade to the latest beta version of osxfuse. This should fix the issue.

**Comment by CloudnuY** [comment]
Thanks~  It solved!
