### ISSUE TITLE
macOS Sierra

### ISSUE THREAD

**Issue by F3000** [osxfuse/osxfuse#297]
Unable to install on Beta 2 . Maybe you can fix it so i can test it with further Betas of macOS.

![bildschirmfoto 2016-07-11 um 21 54 29](https://cloud.githubusercontent.com/assets/8161283/16744590/15727350-47b2-11e6-8308-7a653890434b.png)

**Comment by bfleischer** [comment]
Please see https://github.com/osxfuse/osxfuse/issues/290
