### ISSUE TITLE
sshfs broken in public beta 2 of Sierra

### ISSUE THREAD

**Issue by sdavey** [osxfuse/osxfuse#301]
sshfs was working great before I updated to public beta 2 of Sierra. now something like sshfs -o IdentityFile=~/.ssh/id_rsa,auto_cache,reconnect,defer_permissions,negative_vncache,volname=dev -o sshfs_debug user@my.domain:/ ~/dev
returns "remote host has disconnected"

**Comment by bfleischer** [comment]
Works fine for me when connecting to an OS X 10.11 host. sshfs relies on the OpenSSH client that is shipping with macOS. Maybe this is a configuration issue. Can you connect to the server via ssh?

**Comment by sdavey** [comment]
ok, thanks. must be something on my end. I am able to connect via ssh. go ahead and close this issue.

sean
