### ISSUE TITLE
osxfuse 3.4  command mount_osxfuse argument is changed?

### ISSUE THREAD

**Issue by shenwen2012** [osxfuse/osxfuse#303]
i use command  "Library/Filesystems/osxfuse.fs/Contents/Resources/mount_osxfuse  -o default_permissions,allow_other,fssubtype=testfs  8  /mnt"  failed Invalid argument  by osxfuse3.4.  but in osxfuse2.8 is ok.   osxfuse 3.4  mount_osxfuse  argument is changed?

**Comment by bfleischer** [comment]
`mount_osxfuse` should never be called directly. This is equally true for osxfuse 2.8 and 3.4. You need to call your file system binary to mount the file system.

Please use our Google group at https://groups.google.com/forum/#!forum/osxfuse-group for questions like this. Thanks.
