### ISSUE TITLE
osxfuse-2.8.3.dmg seems to have "2.7.3" in pkgconfig/osxfuse.pc and the libraries

### ISSUE THREAD

**Issue by cameron-simpson** [osxfuse/osxfuse#304]
Trying to install python-llfuse on top of OSXFUSE and it complains that the fuse version is too old:

+ exec venv pip install llfuse
Collecting llfuse
  Using cached llfuse-1.1.1.tar.bz2
    Complete output from command python setup.py egg_info:
    fuse version too old (found: b'2.7.3', required: 2.8.0)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/cameron/tmp/pip-build-4h_umdv8/llfuse/

It looks like OSXFUSE 2.8.3 was built with the version string "2.7.3"; it is in the pkgconfig/osxfuse.pc file and also the binaries:

cd /usr/local/lib
strings libosxfuse*|g 2.7/3
212:2.7.3
615:2.7.3
1047:2.7.3
1450:2.7.3
1882:2.7.3
2285:2.7.3

Could a new release be made with the right release version string please? Or could I be told what I'm doing wrong if I'm misreading things?

Thanks,
Cameron Simpson

**Comment by bfleischer** [comment]
All osxfuse 2.x releases ship with libfuse 2.7.3. The version numbering is correct. If you need a newer version of libfuse use the latest osxfuse 3.4.1 beta release. It comes with libfuse 2.9.6.

**Comment by cameron-simpson** [comment]
Ah, I presumed these we synonymous (osxfuse and libfuse); perhaps that should be more evident. Ok. Fetching 3.4.1 now. I'll chat to the python-llfuse maintainers if my problems persist.

Thank you,
Cameron SImpson
