### ISSUE TITLE
macOS Sierra mount failed on /Volumes and also on /Users

### ISSUE THREAD

**Issue by Rowanatkinson91** [osxfuse/osxfuse#306]
Hi,
I installed OSXFUSE 3.4.2.dmg in macOS Sierra beta 6 and tried the sample filesystem (HelloFS) using Xcode 8. It says mount failed due to Permission denied. 

> 2016-08-18 12:02:14.079096 HelloFS[577:46839] kGMUserFileSystem Error: Error Domain=GMUserFileSystemErrorDomain Code=1002 "Unable to create directory for mount point." UserInfo={NSLocalizedDescription=Unable to create directory for mount point., NSUnderlyingError=0x6080000470b0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}, userInfo={
    NSLocalizedDescription = "Unable to create directory for mount point.";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=13 \"Permission denied\"";
}

I tried changing the volume path to /Users/(username)/Documents/Hello, it says Internal fuse error.
Error logs:
> the OSXFUSE file system is not available (-1)
2016-08-18 11:42:02.359796 HelloFS[527:13993] kGMUserFileSystem Error: Error Domain=GMUserFileSystemErrorDomain Code=1003 "Internal fuse error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error messages using Console." UserInfo={NSLocalizedDescription=Internal fuse error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error messages using Console.}, userInfo={
    NSLocalizedDescription = "Internal fuse error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error messages using Console.";
}

Corresponding crash report from Diagnostics:
[HelloFS_crash_report.txt](https://github.com/osxfuse/osxfuse/files/424107/HelloFS_crash_report.txt)

Does the sample filesystems work with OSXFUSE 3.x? Any other change needed to run the samples?

**Comment by rucomcode** [comment]
Same problem to me
FUSE for macOS 3.4.2

**Comment by Rowanatkinson91** [comment]
For /Volumes:
According to the Bug report (https://openradar.appspot.com/radar?id=4948585099558912), /Volumes directory permissions have been changed and you can no longer create items in /Volumes unless root.

For /Users:
The application runs fine when its launched from output folder or archived as Mac application.
But if i run from Xcode, i get Internal Fuse error with the crash report attached.

Anyone facing similar problem?

**Comment by rucomcode** [comment]
I can mount to /Volumes with root access, but then I can't saw file in Finder and other apps

**Comment by bfleischer** [comment]
Please try again with the latest FUSE release. In order to allow non-admin users to mount FUSE volumes in `/Volumes`, starting with version 3.5.0, FUSE will create non-existent mount points automatically.

**Comment by rucomcode** [comment]
I still receive error: /Volumes/Learn Server: No such file or directory

**Comment by eladts** [comment]
I also get the same error with FUSE 3.5.0 and SSHFS 2.5.0.

sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.5.0
FUSE library version: 2.9.7

sshfs tsur7: /Volumes/tsur7
/Volumes/tsur7: No such file or directory

**Comment by bfleischer** [comment]
When mounting a SSH volume you need to create the mount point yourself. This has always been this way. You can create a mount point in /Volumes by running the following commands:

    sudo mkdir /Volumes/sshfs
    sudo chown ${USER} /Volumes/sshfs

To mount the file system run:

    sshfs user@host:/path /Volumes/sshfs

**Comment by eladts** [comment]
I think OSXFUSE SSHFS should be modified to take advantage of the automatic mount point creation feature that was introduced in OSXFUSE 3.5.0. This will allow SSHFS to mount in /Volumes without sudo privileges, as was possible before Sierra.

**Comment by matiasjrossi** [comment]
@bfleischer: I personally agree with @eladts, the fact that having to create the mount point beforehand is the status quo, does not necessarily imply it is the best behavior to expose.

From my perspective, the whole point of having a FS in user land is to allow non-privileged users perform privileged actions with the restrictions set in place by running trusted code (fuse), so forcing root privileges kind of defeats the purpose to my eyes.

What is the rationale to not consider using the new capability of OSXFUSE 3.5.0?

**Comment by bfleischer** [comment]
I agree with you, it would be preferable to not have to rely on sudo to mount a sshfs volume under /Volumes. Technically this is an sshfs enhancement not a FUSE bug and it is not related to the HelloFS issue reported by @Rowanatkinson91. That's why I closed this issue.

If you like you can open another issue in the sshfs tracker.
