### ISSUE TITLE
NTFS input/output error when removing files

### ISSUE THREAD

**Issue by sryze** [osxfuse/osxfuse#308]
Hello, I'm not sure this is the right place to post this bug, feel free to close if not.

I tried to clean up Xcode user data folder for a project I'm working on because Xcode didn't save the project state, and got a lot of error messages like this:

```
$ rm -rf ProjectName.xcworkspace/xcuserdata
rm: ProjectName.xcworkspace/xcuserdata/user.xcuserdatad/UserInterfaceState.xcuserstate.ntfs-3g-0000000046: Input/output error
...
```

I've already had this error before, though with different files, and usually running chkdsk from Windows helps. 

What are these `ntfs-3g-xxxxxxxxxx` files? Is this a bug in ntfs-3g? Or is Xcode doing something not supported on NTFS?

**Comment by bfleischer** [comment]
I think this might be a NTFS-3G issue. Please post the issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7.
