### ISSUE TITLE
fuse: dlopen(libfusemod_iconv.so, 2): image not found

### ISSUE THREAD

**Issue by emeidi** [osxfuse/osxfuse#309]
I've upgraded my Mac mini from Mac OS X Mavericks to OS X El Capitan on Saturday. Since then, one of my backup scripts relying on curlftpfs, rsync and osxfuse is **not** working anymore.

The sample command called by my script is:
`/opt/local/bin/curlftpfs  -s -r -o ftp_method=singlecwd -o defer_permissions -o modules=iconv,from_code=latin1 "domain.tld" "/Users/mario/Sites/ftpmounts/domain.tld"`

The error message is:
`fuse: dlopen(libfusemod_iconv.so, 2): image not found`

The FTP site cannot be mounted and the backup fails.

If I run the command without

`-o modules=iconv,from_code=latin1`

it executes fine.

I can't find libfusemod_iconv.so in my filesystem:

`sudo find /opt -name libfusemod_iconv.so`
`sudo find /usr -name libfusemod_iconv.so`
`sudo find /bin -name libfusemod_iconv.so`

Versions:
OS X El Capitan 10.11.6
curlftpfs @0.9.2_2 (active) (through MacPorts)

osxfuse 2.8.3, now upgraded to osxfuse 3.4.2 (Problem persists)
osxfuse @2.8.2_0 (active) (through MacPorts)

Not sure which osxfuse is actually used by curlftpfs?
OK, looks like the MacPorts one is loaded:

```
$ kextstat | grep -i osxfuse
  174    0 0xffffff7f830d4000 0x16000    0x16000    com.github.osxfuse.filesystems.osxfusefs (2.8.2) 65E3D8B7-6765-38EB-A567-87064E1B60CD <7 5 4 3 1>
```

**Comment by emeidi** [comment]
I think I've solved the issue:

Instead of
`-o modules=iconv,from_code=latin1`

I've used
`-o codepage=latin1 -o iocharset=utf8`

and the FTP site gets mounted. I'm using the latter command line arguments for years on my Linux server. So it looks like Mac is now compatible with those arguments ...

**Comment by bfleischer** [comment]
The iconv module is built into libosxfuse. There should be no need to look for libfusemod_iconv.so, which does ship with FUSE on macOS. Maybe this has something to do with CurlFtpFS or the way MacPorts builds libosxfuse, but "-o modules=iconv" works fine for me when using the loopback file system.
