### ISSUE TITLE
build.sh fails on my Xcode

### ISSUE THREAD

**Issue by emilymaier** [osxfuse/osxfuse#310]
I've been trying to build osxfuse using ./build.sh -t distribution as described in the readme, but I've been running into a few problems. First, I get the error message:

> No version of Xcode found

Poking around in the script indicates it's trying to find xcodebuild, and the glob doesn't find it where my system has it (/usr/bin/xcodebuild). Fixing that gives a new error:

> Failed to parse version of Xcode at path ''
> No version of Xcode found

Am I doing anything wrong here? Xcode is definitely installed, and I'm able to build components of osxfuse (like the kext) from within Xcode itself.

**Comment by bfleischer** [comment]
On which version of macOS are you trying to build FUSE? Where is Xcode installed and which version of it? Which branch of the osxfuse repository are you trying to build?

**Comment by emilymaier** [comment]
I'm using 10.11.6 with Xcode 7.3.1 and trying to build the current tip of support/osxfuse-3. Xcode was installed from the app store and lives in /Applications/Xcode.app/

**Comment by bfleischer** [comment]
The build script should work fine on 10.11 with Xcode 7.3.1. This is probably a configuration issue on your end.

The script tries to locate all installed versions of Xcode and will then use the newest available version, that includes, in your case, the OS X 10.11 SDK, to build FUSE.  

Xcode 3, if installed, is located by looking for `/*/usr/bin/xcodebuild`. Newer version of Xcode (including 7.3.1) are located using Spotlight. Please make sure that the following command returns `/Applications/Xcode.app`:

    mdfind -onlyin "/Applications" 'kMDItemCFBundleIdentifier == "com.apple.dt.Xcode"'

**Comment by emilymaier** [comment]
Indeed the problem was in Spotlight. Thanks!

**Comment by mcampos-quinn** [comment]
I'll comment further for anyone else who found this same question. I had the same problem and found that I had to reindex spotlight. `sudo mdutil -i on /` fixed the issue.

**Comment by yan12125** [comment]
```sudo mdutil -i on /``` also fixes the issue for me!

**Comment by swhobbit** [comment]
Why in Ceiling Cat's Name does it rely on Spotlight? I don't see why Spotlight is needed to look in a known location.

Spotlight is EXPLICITLY disabled on this machine, it consumes resources and does evil things when I'm trying to eject disks.  This sounds like a solution looking for a problem.

**Comment by soulne4ny** [comment]
It is a cumbersome requirement to have a spotlight on to build a project from its source code, isn't it?

**Comment by swhobbit** [comment]
I did a Mac Ports install. How the port chose to install it was beyond my control.
