### ISSUE TITLE
versioning semantics?

### ISSUE THREAD

**Issue by ThomasWaldmann** [osxfuse/osxfuse#313]
The version numbers you use for the (pre-) releases, what versioning semantics do they follow?

Nowadays semantic versioning is quite popular, but the gh releases page does not look like it:
- 3.5.0 is marked stable
- 3.5.1 is marked pre-release / developer preview (in semantic versioning it would be a stable bugfix release)

https://github.com/osxfuse/osxfuse/releases
https://osxfuse.github.io/

Besides that, in many other versioning schemes, it would be also usual that 3.5.1 is preferable to 3.5.0 (and not less "release", "stable", ...).

**Comment by ThomasWaldmann** [comment]
anybody?

**Comment by bfleischer** [comment]
Most new FUSE release usually start out as a developer preview before becoming the next stable release, after one or more weeks, depending on the changes. However, if the update contains an important bugfix the developer preview phase can be skipped. This has been the case for 3.5.2. 

The preview phase gives developers a chance to test new builds before they are released to the general public. This way bugs and compatibility issues can be caught early. If serious bugs are reported the preview will not become the next stable release, of course.

> Besides that, in many other versioning schemes, it would be also usual that 3.5.1 is preferable to 3.5.0 (and not less "release", "stable", ...).

3.5.1 contains only internal changes and is generally preferable to 3.5.0, after it passes the preview phase. You can think of it as a golden master that will eventually become as the next stable release.
