### ISSUE TITLE
Preference pane title

### ISSUE THREAD

**Issue by Eitot** [osxfuse/osxfuse#317]
The title of the pane is now so long that it actually overlaps with another one. It is possible to use a line break? Alternatively, could you shorten it to just ‘FUSE’ as shown on the icon?

![screen shot 2016-09-24 at 15 39 54](https://cloud.githubusercontent.com/assets/15073177/18808848/8ac4d6ca-826d-11e6-9667-c92de7c1dab0.png)

**Comment by bfleischer** [comment]
I've shortened the name of the preference pane to just "FUSE" in version 3.5.3. If you think about it "for macOS" is pretty much redundant.
