### ISSUE TITLE
naming inconsistency

### ISSUE THREAD

**Issue by tessus** [osxfuse/osxfuse#319]
This is not an important issue, but I don't like inconsistencies.

![fuse](https://cloud.githubusercontent.com/assets/223439/18884337/01f2445a-84b5-11e6-9336-6f6c2f1dd831.jpg)

You can close this ticket ritght away. I just wanted to mention it.

**Comment by bfleischer** [comment]
Thanks, I've fixed this yesterday. The fix will be in the 3.5.3 update.
