### ISSUE TITLE
macfuse -> osxfuse code migration guide?

### ISSUE THREAD

**Issue by tessus** [osxfuse/osxfuse#320]
I was wondering, if there's a guide on how to convert/migrate code that uses the macfuse API to use the osxfuse API.

I've noticed that the compat layer will be removed and thus a code migration will be paramount to several applications. MacFusion, VeraCrypt, ....

**Comment by bfleischer** [comment]
Usually recompiling the file system and linking it against libosxfuse instead of libfuse or OSXFUSE.framework instead of MacFUSE.framework should be sufficient.

**Comment by tessus** [comment]
This is interesting. Why would newly compiled apps still require the compat layer then?

If there are no code changes necessary, this shouldn't be the case. Very strange.

**Comment by bfleischer** [comment]
Please see https://github.com/veracrypt/VeraCrypt/issues/11 for details on VeraCypt. I don't use MacFusion but if they are still relying on the MacFUSE compatibility layer then you should definitely raise this issue with them.

FUSE for macOS is a successor to MacFUSE. The API of version 2.x is mostly identical to MacFUSE. In 3.x the API has changed slightly but should mostly be backward compatible. Depending on the features used by the file system the transition should be very smooth.

**Comment by bfleischer** [comment]
By the way, version 2.x did not even contain header files for the MacFUSE compatibility layer. Building a file system with the compatibility layer has never been supported and should be considered bad practice. The compatibility layer is intended to support old file system binaries that were built with MacFUSE.

**Comment by tessus** [comment]
Thank you very much for the info.

Actually I suggested to work on the transition of the API for VeraCrypt, but for that I need to know how to do it. According to your comments, VeraCrypt just has to link osxfuse instead. Done.
