### ISSUE TITLE
Symlink name breaks puppet pkgdmg install

### ISSUE THREAD

**Issue by diastelo** [osxfuse/osxfuse#322]
I use puppet to install certain packages automatically on the Macs on our network. The pkgdmg module in puppet that allows me to install pkg files with puppet is looking for files with the pkg extension in the root directory of the DMG. Changing the symlink to be "FUSE for macOS.pkg" instead of "FUSE for macOS" fixes my problem.

**Comment by bfleischer** [comment]
The issue should be fixed in commit https://github.com/osxfuse/osxfuse/commit/f5bdf1a03ae82039e7e4515763d9c9c754e5c602.
