### ISSUE TITLE
The OSXFUSE file system is not available after upgrade to OS X 10.12

### ISSUE THREAD

**Issue by phirestalker** [osxfuse/osxfuse#324]
osxfuse 3.5.2 installed from codeplex website
OS X 10.12

When I try to mount volumes I get the error in the title now. I am using Veracrypt to mount volumes, which worked fine until I upgraded to OS X 10.12
![screenshot 2016-10-08 17 13 11](https://cloud.githubusercontent.com/assets/7477095/19217412/1d306a02-8d8f-11e6-990f-c42f01458fe7.png)

**Comment by phirestalker** [comment]
also:

sudo kextutil /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.12/osxfuse.kext
Password:
(kernel) Kext com.github.osxfuse.filesystems.osxfuse start failed (result 0x5).
(kernel) Kext com.github.osxfuse.filesystems.osxfuse failed to load (0xdc008017).
(kernel) Failed to load kext com.github.osxfuse.filesystems.osxfuse (error 0xdc008017).
Failed to load /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.12/osxfuse.kext - (libkern/kext) kext (kmod) start/stop routine failed.

if it's helpful. It doesn't look helpful

**Comment by bfleischer** [comment]
Try rebooting your Mac. If loading the kernel extension still fails check if your system.log contains the following line

    osxfuse: Failed to register major device number 

If this is the case there are no free device slots. FUSE needs to register a virtual device for exchanging messages between the kernel and the actual file system implementations running in user space. The number of available device slots is limited by macOS. So if you are using other software, that eats up all these device slots FUSE will not be able to register its virtual device.

**Comment by phirestalker** [comment]
thanks for quick reply.

I did reboot after upgrading osxfuse. I looked in the logs and do not see
that line, what else might it be? where can I check?

On Sat, Oct 8, 2016 at 8:09 PM, Benjamin Fleischer <notifications@github.com

**Comment by bfleischer** [comment]
Can you post the output of `kextstat`?

**Comment by phirestalker** [comment]
`Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
    1  107 0xffffff7f80a46000 0x9d30     0x9d30     com.apple.kpi.bsd (16.0.0) 5634782E-4DC3-49BB-81CF-446F004202F8
    2    8 0xffffff7f80efb000 0x3940     0x3940     com.apple.kpi.dsep (16.0.0) 9DCE7B23-DA99-4A4B-98C5-1F415800C8E6
    3  125 0xffffff7f80a12000 0x21040    0x21040    com.apple.kpi.iokit (16.0.0) 6FAB3CF2-F930-4212-87F0-CD0B0C0D961D
    4  135 0xffffff7f80a00000 0xd200     0xd200     com.apple.kpi.libkern (16.0.0) 0875A31A-15AE-4D0C-BB2A-01B70880B606
    5  124 0xffffff7f80a0e000 0x3dd0     0x3dd0     com.apple.kpi.mach (16.0.0) 1BD0C00C-0885-4C02-B522-D1E9CBDE84E7
    6   62 0xffffff7f80a34000 0xb9c0     0xb9c0     com.apple.kpi.private (16.0.0) 6EA8E14B-52FC-4347-9042-A22A4F3900BB
    7   82 0xffffff7f80a40000 0x5890     0x5890     com.apple.kpi.unsupported (16.0.0) B69829B4-6889-4B29-93B4-FB7BD433E50E
    8    7 0xffffff7f810eb000 0xa9000    0xa9000    com.apple.kec.corecrypto (1.0) 87F8F7C6-C6E8-3CD2-A231-A5BD74B7987C <7 6 5 4 3 1>
    9    0 0xffffff7f81245000 0xf000     0xf000     com.apple.kec.pthread (1) 9B72ADED-A0E4-3B51-A117-01150075897A <7 6 5 4 1>
   10    1 0xffffff7f8208f000 0xb000     0xb000     com.apple.kec.Libm (1) 1441A2E9-3C13-3554-8028-F69175A80A5A <4>
   11   26 0xffffff7f80f02000 0x9000     0x9000     com.apple.iokit.IOACPIFamily (1.4) 4F7FB6AD-2498-3F71-827C-ED7AA4BF2511 <7 6 4 3>
   12   30 0xffffff7f80bbf000 0x34000    0x34000    com.apple.iokit.IOPCIFamily (2.9) 731443D8-78D5-30C8-939A-1ED3E857CA22 <7 6 5 4 3>
   13    2 0xffffff7f8297d000 0x60000    0x60000    com.apple.driver.AppleACPIPlatform (5.0) D748FA50-380C-3F0D-BAD9-EB7A15848EA8 <12 11 7 6 5 4 3 1>
   14    1 0xffffff7f81414000 0xb000     0xb000     com.apple.driver.AppleFDEKeyStore (28.30) B9C62BFE-2AF9-33FF-85AD-B2BCEEF35E57 <8 7 6 5 4 3 1>
   15    3 0xffffff7f817f4000 0x7000     0x7000     com.apple.iokit.IOReportFamily (31) 3CAF0CDE-3EB5-32C8-91EF-EC5C7CAFBA22 <5 4 3>
   16   14 0xffffff7f80a50000 0x27000    0x27000    com.apple.iokit.IOStorageFamily (2.1) 510A2AD8-C127-34AA-A984-95A82C6AC1DA <7 6 5 4 3 1>
   17    0 0xffffff7f8190e000 0x19000    0x19000    com.apple.driver.DiskImages (444) 80D7E3BB-4F87-342C-B79E-77D9FDC33F2C <16 7 6 5 4 3 1>
   18    1 0xffffff7f824e1000 0x21000    0x21000    com.apple.driver.AppleCredentialManager (1.0) 74348615-A50D-3A32-B837-034444FDCBF6 <8 7 6 5 4 3 1>
   19    3 0xffffff7f81201000 0x16000    0x16000    com.apple.driver.AppleMobileFileIntegrity (1.0.5) C521A417-63C5-3F01-AD3A-C2BBFA94763D <8 7 6 5 4 3 2 1>
   20    0 0xffffff7f82502000 0x3e000    0x3e000    com.apple.driver.AppleKeyStore (2) 77B67825-2A7E-3084-A292-1810E7851823 <19 18 8 7 6 5 4 3 1>
   21    0 0xffffff7f825a0000 0x2b000    0x2b000    com.apple.driver.AppleIntelCPUPowerManagement (219.0.0) 36216E26-C378-3067-B5B5-C27076D64955 <7 6 5 4 3 1>
   22    0 0xffffff7f80eff000 0x2000     0x2000     com.apple.security.TMSafetyNet (8) 1CB512A3-24BD-344A-BFB4-44A61F27AB03 <7 6 5 4 2 1>
   23    2 0xffffff7f81217000 0x5000     0x5000     com.apple.kext.AppleMatch (1.0.0d1) 3B280DAB-903F-33DC-8110-525A1154B11E <4 1>
   24    1 0xffffff7f8121c000 0x1f000    0x1f000    com.apple.security.sandbox (300.0) 0DB843E1-989D-35FB-8EED-722AAD25D8A4 <23 19 16 7 6 5 4 3 2 1>
   25    0 0xffffff7f8123b000 0x9000     0x9000     com.apple.security.quarantine (3) 37B046F5-3150-34B0-A5FB-8DC85FC09589 <24 23 7 6 5 4 2 1>
   26    0 0xffffff7f83a58000 0x8000     0x8000     com.apple.nke.applicationfirewall (171) 234047FB-816E-3A64-A96B-34BC08DCD3F5 <7 6 5 4 3 1>
   27    0 0xffffff7f8259b000 0x3000     0x3000     com.apple.driver.AppleIntelCPUPowerManagementClient (219.0.0) B802638B-251C-3602-BA8C-001F87228765 <7 6 5 4 3 1>
   28    0 0xffffff7f8294b000 0x3000     0x3000     com.apple.driver.AppleAPIC (1.7) BC2E6D01-BCBB-3525-BF38-BF99C3F1EC46 <4 3>
   29    2 0xffffff7f81791000 0x4000     0x4000     com.apple.iokit.IOSMBusFamily (1.1) 185F0EBF-0262-3370-BD47-8FE4C8AA726E <5 4 3>
   30    0 0xffffff7f829e3000 0x7000     0x7000     com.apple.driver.AppleACPIEC (5.0) A984BD16-D3DD-3E81-AC9A-69E0F546B973 <29 13 11 5 4 3>
   31    0 0xffffff7f82408000 0x4000     0x4000     com.apple.driver.AppleSMBIOS (2.1) 9BB02681-4B47-3592-AD62-71FB0BF56965 <7 4 3>
   32    7 0xffffff7f8141f000 0x78000    0x78000    com.apple.iokit.IOHIDFamily (2.0.0) EF97107C-5B48-3B48-A1CF-D9BAC7C2632D <14 7 6 5 4 3 2 1>
   33    0 0xffffff7f829ed000 0x4000     0x4000     com.apple.driver.AppleACPIButtons (5.0) B40BC4E6-0A6A-3D4A-B534-84CEE779302B <32 15 13 11 7 6 5 4 3 1>
   34    0 0xffffff7f82620000 0x3000     0x3000     com.apple.driver.AppleHPET (1.8) 2CFB49B8-4CC2-320B-9C6E-99646DFD8571 <11 7 5 4 3>
   35    1 0xffffff7f8184b000 0x5000     0x5000     com.apple.driver.AppleEFIRuntime (2.0) 6B7A5B9A-C313-3F7F-B6E2-60EE54593BC8 <7 6 5 4 3>
   36    1 0xffffff7f80f0b000 0xd000     0xd000     com.apple.driver.AppleBusPowerController (1.0) DB526B45-1A45-3A81-A0C1-57F826CADEDF <11 5 4 3>
   37    0 0xffffff7f82435000 0x8000     0x8000     com.apple.driver.AppleRTC (2.0) 3FD1BCF4-8AFC-3CE6-A36E-26410544AD14 <11 5 4 3 1>
   38    1 0xffffff7f81850000 0xb000     0xb000     com.apple.driver.AppleEFINVRAM (2.1) 6F4404D6-8625-35CA-AEB6-6ECD7B64FA52 <35 7 6 5 4 3 2 1>
   39    2 0xffffff7f815fa000 0x4000     0x4000     com.apple.driver.AppleUSBHostMergeProperties (1.1) 4B681300-2D50-30F8-90AA-A2F06578A3F4 <4 3 1>
   40   16 0xffffff7f80f18000 0x68000    0x68000    com.apple.iokit.IOUSBHostFamily (1.1) 6A671CD8-5527-3A10-8675-1421D158D7A7 <36 7 6 5 4 3 1>
   41    3 0xffffff7f80f88000 0x99000    0x99000    com.apple.iokit.IOUSBFamily (900.4.1) 8F6207EC-608D-373A-B35E-E6578202F58D <40 12 7 5 4 3 1>
   42    0 0xffffff7f815f5000 0x5000     0x5000     com.apple.driver.usb.AppleUSBHostPacketFilter (1.0) CA3B53E3-FA12-3659-B869-E267709C4007 <40 7 6 5 4 3 1>
   43    3 0xffffff7f8152b000 0x3d000    0x3d000    com.apple.driver.usb.AppleUSBEHCI (1.1) D9DF0161-D131-3A0C-81B3-6EFF864FED92 <40 11 7 5 4 3 1>
   44    1 0xffffff7f8156c000 0x1f000    0x1f000    com.apple.driver.usb.AppleUSBUHCI (1.1) 852B9116-5551-3E50-AA00-FCFDAEAEA831 <43 40 7 5 4 3 1>
   45    0 0xffffff7f8158e000 0x6000     0x6000     com.apple.driver.usb.AppleUSBUHCIPCI (1.1) E49064EB-E0C6-37E4-B916-ECF03AC74766 <44 43 40 12 11 7 5 4 3 1>
   46    0 0xffffff7f8160a000 0xe000     0xe000     com.apple.driver.usb.AppleUSBEHCIPCI (1.1) BBDDC1A9-7ADE-39F0-90A4-C349C319E87A <43 40 12 11 7 5 4 3 1>
   47    3 0xffffff7f81b60000 0x1a000    0x1a000    com.apple.iokit.IOAHCIFamily (288) 5C275B66-A173-3D92-853A-44FC35D45FFC <5 4 3 1>
   48    0 0xffffff7f82950000 0x1e000    0x1e000    com.apple.driver.AppleAHCIPort (326) F91BC44F-48CB-3348-AED0-9CAA6A9D7ECD <47 12 5 4 3 1>
   50    5 0xffffff7f8138c000 0x2d000    0x2d000    com.apple.iokit.IONetworkingFamily (3.2) 6326DB88-5330-3F0C-91F6-D478AB5E7503 <7 6 5 4 3 1>
   51    0 0xffffff7f81893000 0x11000    0x11000    com.apple.driver.Intel82574LEthernet (2.7.2) 2842CDCE-4F41-32B0-B77D-74D5C013476F <50 12 5 4 3 1>
   52    1 0xffffff7f81bb3000 0x29000    0x29000    com.apple.driver.corecapture (1.0.4) FEB510C7-BFC6-3721-8143-476E4EB62788 <7 6 5 4 3 1>
   53    1 0xffffff7f81be5000 0xe6000    0xe6000    com.apple.iokit.IO80211Family (1200.12.2) 11F0AC73-496B-349F-81BE-3D1BE4C45234 <52 50 19 8 7 6 5 4 3 1>
   54    0 0xffffff7f81cd5000 0x1ef000   0x1ef000   com.apple.driver.AirPort.Brcm4331 (800.20.24) 83F35371-C137-3453-BCDD-37C9825EECA4 <53 50 12 7 5 4 3 1>
   55    2 0xffffff7f812cc000 0x73000    0x73000    com.apple.iokit.IOFireWireFamily (4.6.4) D7C7A0A7-9B83-33AF-A12A-F8AE97FCED7A <5 4 3 1>
   56    0 0xffffff7f81971000 0x26000    0x26000    com.apple.driver.AppleFWOHCI (5.5.5) 6EF0BC66-3AF8-3272-AE3A-E588FFB07BF7 <55 12 7 6 5 4 3 1>
   57    7 0xffffff7f80b7c000 0x2b000    0x2b000    com.apple.iokit.IOSCSIArchitectureModelFamily (394) 0E35A335-5605-36FB-991C-D0D38F4FA4E7 <6 5 4 3 1>
   58    0 0xffffff7f81b7d000 0xd000     0xd000     com.apple.iokit.IOAHCISerialATAPI (266) 681FA1E2-E3DE-3FEB-ACA7-16FC2B9078A6 <57 47 5 4 3 1>
   59    0 0xffffff7f817a0000 0x7000     0x7000     com.apple.iokit.SCSITaskUserClient (394) 4A92621E-97C8-3AB4-8E25-C540967F573C <57 16 5 4 3 1>
   60    3 0xffffff7f817ab000 0xe000     0xe000     com.apple.iokit.IOCDStorageFamily (1.8) 9EEF7CF2-673C-3743-84DD-D3B3D5E61DDB <16 5 4 3 1>
   61    2 0xffffff7f817bc000 0xb000     0xb000     com.apple.iokit.IODVDStorageFamily (1.8) 9BC77405-09A3-3398-AE63-98894C42E288 <60 16 5 4 3 1>
   62    1 0xffffff7f817ca000 0x9000     0x9000     com.apple.iokit.IOBDStorageFamily (1.8) EE071733-F836-360B-958B-440E2CCF81E1 <61 60 16 5 4 3 1>
   63    0 0xffffff7f817d6000 0x1a000    0x1a000    com.apple.iokit.IOSCSIMultimediaCommandsDevice (394) 315023CC-5BBD-3C98-947C-56D52D1C50F6 <62 61 60 57 16 6 5 4 3 1>
   64    0 0xffffff7f80c0c000 0x4b000    0x4b000    at.obdev.nke.LittleSnitch (4718) 715E9654-C3FB-39A4-9514-C770F749EE8E <7 5 4 3 1>
   65    1 0xffffff7f81eff000 0x7000     0x7000     com.apple.filesystems.hfs.encodings.kext (1) 55720CF4-F816-39E6-8594-5E23BE4DE22C <7 6 5 4 3 1>
   66    0 0xffffff7f81f06000 0x69000    0x69000    com.apple.filesystems.hfs.kext (366.1.1) 2F506B53-03D9-3991-966F-C65ECFF463BE <65 7 6 5 4 3 1>
   67    0 0xffffff7f82078000 0xa000     0xa000     com.apple.BootCache (39) 7F9AAFD7-4871-36F1-80CA-107A763017F1 <7 6 5 4 3 1>
   68    0 0xffffff7f82924000 0x6000     0x6000     com.apple.AppleFSCompression.AppleFSCompressionTypeZlib (1.0.0) 9B32DDE9-151F-31A1-90E9-3CEB2C7BE27C <6 4 3 2 1>
   69    0 0xffffff7f8292c000 0x3000     0x3000     com.apple.AppleFSCompression.AppleFSCompressionTypeDataless (1.0.0d1) C6F882D7-C35C-3963-A2FA-10033FF40107 <7 6 4 3 2 1>
   71    0 0xffffff7f815bf000 0x2e000    0x2e000    com.apple.driver.usb.AppleUSBHub (1.1) DC24F9D4-9F5E-34AC-A61E-90C9292310D6 <40 11 5 4 3 1>
   72    0 0xffffff7f815fe000 0x8000     0x8000     com.apple.driver.usb.AppleUSBHostCompositeDevice (1.1) 39E80BC3-6CBA-3611-87F7-127CEBA9111B <40 5 4 3 1>
   73    0 0xffffff7f821b2000 0x8000     0x8000     com.apple.driver.usb.networking (5.0.0) BD6EEE30-3331-376B-A9F8-FA10A8F28731 <40 5 4 3 1>
   75    1 0xffffff7f813cc000 0x2d000    0x2d000    com.apple.iokit.IOUSBMassStorageDriver (131.1.1) 91153C74-5D56-340F-B268-C883F80E0EA8 <57 40 16 6 5 4 3 1>
   76    1 0xffffff7f81400000 0x11000    0x11000    com.apple.iokit.IOUSBMassStorageClass (4.0.4) E1B27EA5-B663-3F8E-A209-7769EAFB1160 <57 41 16 5 4 3 1>
   77    1 0xffffff7f812a9000 0x19000    0x19000    com.apple.iokit.IOSCSIBlockCommandsDevice (394) 7D111DA4-D66E-309D-BDB6-6C7465180C66 <57 16 6 5 4 3 1>
   78    0 0xffffff7f823c4000 0x4000     0x4000     com.apple.driver.AppleUSBStorageCoexistentDriver (404.1.1) 62003603-5846-3AA0-A098-B189311A2F30 <77 76 75 57 40 16 5 4 3 1>
   80    0 0xffffff7f81b8a000 0x1c000    0x1c000    com.apple.iokit.IOAHCIBlockStorage (295.1.1) 08375C5A-FF97-32B5-8146-98192272C923 <47 16 6 5 4 3 1>
   82    0 0xffffff7f814ac000 0xb000     0xb000     com.apple.driver.usb.IOUSBHostHIDDevice (1.1) A4BB4CAC-5885-3B48-B035-666B004CA240 <40 32 5 4 3 1>
   83    0 0xffffff7f822d7000 0xa000     0xa000     com.apple.driver.AppleHIDKeyboard (197) E03366C7-2F55-3D98-917A-39A349F4DAAA <32 5 4 3>
   84    2 0xffffff7f8209a000 0x95000    0x95000    com.apple.vecLib.kext (1.2.0) 6ADA5F0B-10EF-360A-BF1E-E142D2074E4E <10 6 5 4 3>
   85    5 0xffffff7f8212f000 0x30000    0x30000    com.apple.iokit.IOAudioFamily (205.11) BB1375FC-983D-3923-927F-88C0186414C8 <84 5 4 3 1>
   86    0 0xffffff7f82215000 0x58000    0x58000    com.apple.driver.AppleUSBAudio (305.62) BB99BC0A-33DA-3C64-B097-C5732DF017EA <85 40 39 12 5 4 3 1>
   87    0 0xffffff7f81f7c000 0xdc000    0xdc000    com.apple.driver.CoreStorage (540) DDEB6924-19AE-3E3B-86A9-4020D1AABF4C <16 7 6 5 4 3 1>
   90    5 0xffffff7f817fb000 0xa000     0xa000     com.apple.driver.IOPlatformPluginFamily (6.0.0d8) 09B480A4-4793-311C-B5CF-4C56A3C67D18 <11 7 6 5 4 3>
   91    0 0xffffff7f824dc000 0x3000     0x3000     com.apple.driver.AppleLPC (3.1) F51595F0-F9B1-3B85-A1C3-F984DAD4107E <90 12 5 4 3>
   92    5 0xffffff7f819cb000 0xdf000    0xdf000    com.apple.iokit.IOBluetoothFamily (5.0.0f18) 3AA9411B-1D19-318E-A777-19A4F0DC9D02 <15 7 5 4 3 1>
   93    2 0xffffff7f81af2000 0xb000     0xb000     com.apple.iokit.IOBluetoothHostControllerTransport (5.0.0f18) B4746AC0-E50F-3D3B-9AC5-CD8FC0F59860 <92 40 12 11 7 6 5 4 3 1>
   94    1 0xffffff7f81afd000 0x23000    0x23000    com.apple.iokit.IOBluetoothHostControllerUSBTransport (5.0.0f18) 39D72509-C571-340A-83BB-7B38183028CE <93 92 40 12 11 7 6 5 4 3 1>
   95    0 0xffffff7f81b20000 0x8000     0x8000     com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport (5.0.0f18) EDFF8873-9655-3AA3-87BF-0ABC85155A89 <94 93 92 40 12 11 7 6 5 4 3>
   96    1 0xffffff7f81805000 0x12000    0x12000    com.apple.driver.IOPlatformPluginLegacy (1.0.0) 4F0E3729-43A1-313A-8DF1-5C292531E536 <90 11 7 6 5 4 3>
   97    3 0xffffff7f81819000 0x19000    0x19000    com.apple.driver.AppleSMC (3.1.9) FA8E2E8A-FA5B-3949-AA1D-946DE5F5217B <11 7 5 4 3 1>
   98    0 0xffffff7f81834000 0x10000    0x10000    com.apple.driver.ACPI_SMC_PlatformPlugin (1.0.0) 56637575-8F71-3C20-BF82-7DC99E722444 <97 96 90 12 11 7 6 5 4 3>
   99    0 0xffffff7f823f4000 0x3000     0x3000     com.apple.driver.AppleSMBusPCI (1.0.14d1) F5516FB7-82C6-3E74-98E7-80EDCA074BC2 <12 5 4 3>
  100    0 0xffffff7f81961000 0xe000     0xe000     com.apple.iokit.IOFireWireIP (2.2.7) F30C2597-CAFD-386B-90E6-7A4007D8A6D5 <55 50 5 4 3 1>
  101    2 0xffffff7f82637000 0xc000     0xc000     com.apple.iokit.IOHDAFamily (276.26) 02E32F26-A9E6-3586-BE75-203B8F48EC8A <5 4 3 1>
  102   12 0xffffff7f818b7000 0x3b000    0x3b000    com.apple.iokit.IOGraphicsFamily (2.4.1) 377FAA09-C02F-3FF4-A5DE-C0F2E711C8B0 <12 7 5 4 3 1>
  103    1 0xffffff7f8266e000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (276.26) D0953002-6091-376F-8E0F-33B65F42CEF9 <102 101 85 12 7 6 5 4 3 1>
  104    1 0xffffff7f81795000 0x5000     0x5000     com.apple.iokit.IOSlowAdaptiveClockingFamily (1.0.0) F026208D-CC0C-3599-B303-9196904A584E <7 6 5 4 3 1>
  105    0 0xffffff7f82547000 0x2000     0x2000     com.apple.driver.AppleIntelSlowAdaptiveClocking (4.0.0) 6FE984DD-A1FE-309E-83CF-B346989A6F17 <104 4 3>
  106    2 0xffffff7f828f7000 0xa000     0xa000     com.apple.AppleGraphicsDeviceControl (3.13.60) FDEAB5E1-3BFF-34DF-92AB-6AE26C8405F7 <7 6 5 4 3 1>
  107    2 0xffffff7f82a71000 0x14c000   0x14c000   com.apple.kext.AMDSupport (1.4.4) DE6DDF10-212A-31AC-9866-AD498B159045 <106 102 12 11 7 5 4 3 1>
  108    0 0xffffff7f832df000 0x61d000   0x61d000   com.apple.kext.AMD5000Controller (1.4.4) 8E382918-AE78-3092-9DCB-E7D4C35895BB <107 102 12 11 5 4 3 1>
  109    0 0xffffff7f825dc000 0xa000     0xa000     com.apple.driver.AppleHV (1) 39AC9B9B-7B20-322F-82F0-044B3CC08D43 <7 6 5 4 3 1>
  110    0 0xffffff7f81f76000 0x5000     0x5000     com.apple.Dont_Steal_Mac_OS_X (7.0.0) B97F871A-44FD-3EA4-BC46-8FD682118C79 <97 8 7 4 3 1>
  111    1 0xffffff7f81778000 0x17000    0x17000    com.apple.iokit.IOSurface (152) CD2E7A07-1BD9-3298-A038-E6F8098F0C2A <7 6 5 4 3 1>
  112    1 0xffffff7f82bcc000 0x91000    0x91000    com.apple.iokit.IOAcceleratorFamily2 (288.13) 27E0AFCE-E36A-35F5-A008-BB1EB3A2C7B9 <102 12 7 6 5 4 3 1>
  113    0 0xffffff7f82c6c000 0x569000   0x569000   com.apple.AMDRadeonX3000 (1.4.4) 9BA87B01-1C6A-3F8C-98DA-A56416DD21C2 <112 111 102 12 7 5 4 3 1>
  114    1 0xffffff7f81033000 0xe000     0xe000     com.apple.iokit.IOSerialFamily (11) B36990F3-B873-31BB-8A1B-5615A3277382 <7 6 5 4 3 1>
  115    0 0xffffff7f81ade000 0xa000     0xa000     com.apple.iokit.IOBluetoothSerialManager (5.0.0f18) C30455D2-0A79-308A-B395-C166632DC106 <114 7 5 4 3 1>
  116    2 0xffffff7f823f7000 0xe000     0xe000     com.apple.driver.AppleSMBusController (1.0.14d1) 4DAA381E-3690-3E94-8025-DFB34F714094 <29 12 11 5 4 3>
  117    2 0xffffff7f818fe000 0x10000    0x10000    com.apple.iokit.IONDRVSupport (2.4.1) C1544DFB-9066-340F-AD0A-9302DC3E6841 <102 12 7 5 4 3>
  118    0 0xffffff7f813c0000 0x6000     0x6000     com.apple.iokit.IOUserEthernet (1.0.1) 5EE448BD-95EC-35AD-B7FC-A1237E4BB346 <50 6 5 4 3 1>
  119    0 0xffffff7f832a7000 0x24000    0x24000    com.apple.kext.AMDFramebuffer (1.4.4) BBAE6B39-3BC0-3A47-AF75-EF98BC177EB1 <107 102 12 11 7 5 4 3 1>
  120    0 0xffffff7f824a2000 0xe000     0xe000     com.apple.driver.AppleMCCSControl (1.2.13) 102DD5D9-2DD5-3BCB-B5C0-BE08E1049CD6 <116 102 97 12 11 7 5 4 3 1>
  121    0 0xffffff7f82274000 0x5000     0x5000     com.apple.driver.AppleUpstreamUserClient (3.6.4) 761DD71A-0746-3515-A557-B702BBDD664A <102 12 11 7 5 4 3 1>
  122    1 0xffffff7f8268b000 0x13000    0x13000    com.apple.kext.OSvKernDSPLib (525) D0421B4D-7B97-3102-BC42-3684344DB5E6 <5 4>
  123    1 0xffffff7f8269e000 0x147000   0x147000   com.apple.driver.DspFuncLib (276.26) A58B8C19-2454-3C68-9F14-767A95D941B6 <122 85 84 38 6 5 4 3 1>
  124    0 0xffffff7f827f0000 0xb4000    0xb4000    com.apple.driver.AppleHDA (276.26) 7611D43E-12FE-3228-A6D3-9C99A5D030CC <123 117 103 102 101 85 6 5 4 3 1>
  125    0 0xffffff7f82167000 0x5000     0x5000     com.apple.driver.AudioAUUC (1.70) D58388C6-8260-390F-BE31-37C02572DA9F <102 85 12 11 7 5 4 3 1>
  127    0 0xffffff7f82646000 0x16000    0x16000    com.apple.driver.AppleMikeyDriver (276.26) 9D7B8FE2-CD5A-3FE1-8FC4-8127EECCA77B <116 11 5 4 3 1>
  128    0 0xffffff7f82494000 0x4000     0x4000     com.apple.driver.AppleMikeyHIDDriver (127) 30A94E7A-4BA2-3EC5-9815-C299A790A2B9 <32 7 4 3 1>
  129    0 0xffffff7f8248d000 0x4000     0x4000     com.apple.driver.AppleOSXWatchdog (1) 757A8B72-2A1A-32BA-99EC-6D802DE6E91F <12 7 6 5 4 3 1>
  130    0 0xffffff7f80a7f000 0x62000    0x62000    com.paragon-software.kext.VDMounter (4.2) 3F301F93-CB8D-3149-8C74-D68B3D1C6D52 <16 5 4 3 1>
  131    0 0xffffff7f80af9000 0x7000     0x7000     net.sf.tuntaposx.tun (1.0) 95DD963D-E23D-3B0F-8DE8-A4D2F6BFA5CC <7 5 4 1>
  132    0 0xffffff7f80b03000 0x7000     0x7000     net.sf.tuntaposx.tap (1.0) 23FDB715-3D0D-3A26-ACBA-E3794C231CB7 <7 5 4 1>
  133    2 0xffffff7f81194000 0x5000     0x5000     com.apple.kext.triggers (1.0) 4E564246-8804-3673-B440-606AD360A3BB <7 6 5 4 3 1>
  134    0 0xffffff7f82084000 0x9000     0x9000     com.apple.filesystems.autofs (3.0) AA36D92F-D92B-3102-BAE3-F86A0A298143 <133 7 6 5 4 3 1>
  135    0 0xffffff7f83a62000 0x14000    0x14000    com.intel.kext.intelhaxm (1.1.9) A7C54B24-47F7-364A-9A2C-929D5C0A4F0A <7 5 4 3 1>
  136    3 0xffffff7f83a76000 0x63000    0x63000    org.virtualbox.kext.VBoxDrv (5.0.26) C47FFBAD-20EC-3203-AF08-9E6FA4C5C0BE <7 5 4 3 1>
  137    0 0xffffff7f81254000 0xd000     0xd000     com.apple.driver.pmtelemetry (1) E6E68296-809B-3884-ADEF-E85831F4B106 <7 6 5 4 3>
  138    0 0xffffff7f82903000 0x18000    0x18000    com.apple.driver.AGPM (110.23.7) E6276A25-70A0-366A-A935-2328CFA9226D <117 106 102 90 12 6 5 4 3>
  139    0 0xffffff7f8227d000 0x9000     0x9000     com.apple.driver.AppleTyMCEDriver (1.0.2d2) 200A9785-8ABC-3FF4-9F36-237030D34DB3 <90 12 11 7 6 5 4 3 1>
  140    0 0xffffff7f83ad9000 0x7000     0x7000     com.zerotier.tap (1.0) EFD27D47-368B-3F9E-830F-434D2CF62ACE <7 5 4 1>
  141    1 0xffffff7f8161b000 0x3000     0x3000     com.apple.iokit.IOUSBUserClient (900.4.1) 78304A44-D868-3A4F-8F4F-1687661CF79A <41 39 7 5 4 3 1>
  142    0 0xffffff7f83ae0000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (5.0.26) BA00D956-8C19-360E-9F31-5957AE3E2D88 <141 136 41 7 5 4 3 1>
  143    0 0xffffff7f83ae8000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (5.0.26) B09BEE18-08A1-3B8E-AA70-591C702AC702 <136 7 5 4 3 1>
  144    0 0xffffff7f83aed000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (5.0.26) 9D101030-90D0-3447-8340-CCDD6B58165A <136 5 4 1>
  145    0 0xffffff7f825d3000 0x5000     0x5000     com.apple.driver.AppleHWSensor (1.9.5d0) 92511291-6B64-35B1-A824-53034DEBDD39 <5 4 3>
  146    1 0xffffff7f82289000 0x12000    0x12000    com.apple.driver.AppleInputDeviceSupport (76.1) 8C2F9A69-1627-3364-A8F3-8020075D26B1 <5 4 3 1>
  147    1 0xffffff7f8229e000 0x31000    0x31000    com.apple.driver.AppleMultitouchDriver (367.6) 00DD40D1-31DC-39CB-A40D-572047979A61 <146 32 15 7 5 4 3 1>
  148    1 0xffffff7f81abe000 0x1a000    0x1a000    com.apple.driver.IOBluetoothHIDDriver (5.0.0f18) 48D44CE6-F9F9-3201-B189-3A028084A343 <92 32 5 4 3>
  149    0 0xffffff7f82939000 0xb000     0xb000     com.apple.driver.AppleBluetoothMultitouch (92) DC50E9B7-9C4D-3E6D-A36E-D154940FD6AB <148 147 92 32 5 4 3>
  150    0 0xffffff7f83af3000 0x61000    0x61000    com.apple.filesystems.smbfs (3.1) 2D18A430-2FEB-31EB-9462-9CD093806F8B <133 8 7 6 5 4 3 1>
`

**Comment by bfleischer** [comment]
VirtualBox eats up multiple device slots. TunTap requires at least one device slot. ZeroTier and Intel HAXM most likely do, too. On El Capitan there were 8 free device slots. On Sierra there seem to be less. FUSE should work fine after uninstalling VirtualBox or TunTap. Unloading or uninstalling ZeroTier or Intel HAXM might work, too

**Comment by phirestalker** [comment]
yep uninstalling HAXM worked. Now to complain to Apple for once again making an arbitrary, clueless "decision" to cripple their own software.

**Comment by bfleischer** [comment]
Duplicate of #315
