### ISSUE TITLE
Sierra problems

### ISSUE THREAD

**Issue by karolyi** [osxfuse/osxfuse#326]
Hi,

OSX Sierra, MacFuse 3.5.2, VeraCrypt 1.19-Beta, and I have the following error when trying to mount a volume:

![image](https://cloud.githubusercontent.com/assets/987055/19397518/7fc78b88-9248-11e6-9bed-2f8830379b59.png)

I could not get more detailed information, unfortunately.

**Comment by bfleischer** [comment]
Please report the issue to the VeraCrypt team. IT might be related to https://github.com/veracrypt/VeraCrypt/issues/11.
