### ISSUE TITLE
Error: Darwin API version 25 or greater must be used

### ISSUE THREAD

**Issue by anismo** [osxfuse/osxfuse#327]
Hi 

I am trying to use osxfuse version 3.5.2 on Mac OSX 10.11.6 (El Capitan) and including fuse.h in my C++ project fails with error "Darwin API Version 25 or greater must be used". 

I would be grateful if someone can point to a working example filesystem on mac.

Best
Anis

**Comment by bfleischer** [comment]
It looks like you forgot to define `FUSE_USE_VERSION` before including fuse.h. Have a look at the loopback reference file system on https://github.com/osxfuse/filesystems/tree/master/filesystems-c/loopback.

You can find more demo file systems in the filesystems repository on https://github.com/osxfuse/filesystems. However, some of the file systems are a little outdated and might not work out of the box on recent versions of macOS.
