### ISSUE TITLE
fuse_umount does not remove mount point

### ISSUE THREAD

**Issue by tessus** [osxfuse/osxfuse#332]
I've been having issues with sshfs: using a wrong password results in a stale mount point
Please see https://github.com/libfuse/sshfs/issues/34 for a detailed error description.

But it's not a bug in sshfs. To make a long story short, the code `fuse_unmount(mountpoint, ch);` does not actually remove the mount point. Thus the problem must be somewhere in the fuse code. That's all I could ascertain so far.

I didn't know where to open the issue with `fuse_unmount`. I hope this is the right place.

My env:
OSX 10.9.5 and 10.11.6, OSX FUSE 3.5.3

**Comment by tessus** [comment]
any update on this?

**Comment by bfleischer** [comment]
Thanks for the bug report. The issue will be fixed in the next release, 3.6.1.

**Comment by tessus** [comment]
awesome, thx.
