### ISSUE TITLE
The folder “web” can’t be opened because you don’t have permission to see its contents.

### ISSUE THREAD

**Issue by alexiTakov** [osxfuse/osxfuse#336]
Hello!, in advice sorry for my english.
So.
I am install osSiera. First i do foolish thing, i try install FUSE older version (2.4)  with errors. 
But, after google help me. And I install a latest version.

And eventually  I can mount my server, but I can't read folders content. Mounted so Users/user/Documents/ssh and so /Volumes/ssh.

---
I am code also on Ubuntu(14.04) and  Mac-Mini(El Capitan). 
all the same, but it works on other my machines.

Thanks for attention!
![admin finder today at 14 47 47](https://cloud.githubusercontent.com/assets/15850419/20455271/08a7718e-ae69-11e6-8000-cd7e0189b77b.png)

**Comment by bfleischer** [comment]
Have you tried using the mount-time option `defer_permissions`?

Without `defer_permissions` the kernel will attempt to do the "right thing" based on what it can "see" (the permission bits as reported by the file system). If the file system retrieves file information from another computer and reports user/group IDs as is, the kernel will not see any alien IDs as belonging to the user that mounted the volume. This can happen if user ID translation is not enabled or sometimes doesn't work with sshfs. The `defer_permissions` option is useful in such cases. It causes FUSE to assume that all accesses are allowed - it will forward all operations to the file system, and it is up to somebody else to eventually allow or deny the operations. In the case of sshfs, it would be the SFTP server eventually making the decision about what to allow or disallow.

**Comment by alexiTakov** [comment]
thanks, ok. 
I would like to understand what it really means ;). But?, what can i do? 
any "magic  commmand" ??

----
after 1 minute
oooouuuWAH)) Great!)

In google I find similary issue, where you also help( https://github.com/osxfuse/filesystems/issues/1 )

Magic parametr :  
`sshfs root@188.225.37.30:/home/admin/   /Users/alex/Documents/ssh -o defer_permissions` 
)
Cool.Thanks man!
