### ISSUE TITLE
Install failed on el capitain

### ISSUE THREAD

**Issue by BLaurent** [osxfuse/osxfuse#337]
Hi,
I have some issue installing osxfuse...
Thanks in advance
Regards

 brew cask install osxfuse                  
==> Caveats
You must reboot for the installation of osxfuse to take effect.

==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.5
Already downloaded: /Users/benoitlaurent/Library/Caches/Homebrew/Cask/osxfuse--3.5.3.dmg
==> Verifying checksum for Cask osxfuse
==> Running installer script /usr/sbin/installer
Password:
==> installer: Package name is FUSE for macOS
==> installer: choices changes file '/usr/local/Caskroom/osxfuse/3.5.3/Extras/Ch
==> installer: Installing at base path /
==> installer: The install failed (The Installer encountered an error that cause
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- #<Pathname:/usr/sbin/installer> -pkg /usr/local/Caskroom/osxfuse/3.5.3/Extras/FUSE for macOS 3.5.3.pkg -target / -applyChoiceChangesXML /usr/local/Caskroom/osxfuse/3.5.3/Extras/Choices.xml

==> Standard Output of failed command:
installer: Package name is FUSE for macOS
installer: choices changes file '/usr/local/Caskroom/osxfuse/3.5.3/Extras/Choices.xml' applied
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

**Comment by bfleischer** [comment]
Please download the latest release from https://osxfuse.github.io and run the installer manually. Using Homebrew to install FUSE is not officially supported. You might want to report the issue to the Homebrew team, though.

**Comment by BLaurent** [comment]
Actually I have the same error with the installer, that's why I tried with brew...

**Comment by umireon** [comment]
@BLaurent You can try `brew cask uninstall osxfuse --force --debug` to remove potentially conflicting files.

**Comment by BLaurent** [comment]
I did the uninstall.
Relaunch the install manually using the dmg file
Failed again.

**Comment by umireon** [comment]
@BLaurent The error message of the installation process may be in `/var/log/install.log`.
The contents can be obtained by `cat /var/log/install.log`.

**Comment by BLaurent** [comment]
Nov 26 14:34:34 C02P652UG3QD installd[716]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.XOeoeR/Scripts/com.github.osxfuse.pkg.Core.8ja01m
Nov 26 14:34:34 C02P652UG3QD install_monitor[48426]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Nov 26 14:34:34 C02P652UG3QD installd[716]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.XOeoeR/Scripts/com.github.osxfuse.pkg.MacFUSE.TUMzTB
Nov 26 14:34:35 C02P652UG3QD installd[716]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/C7742F49-C099-4B9F-A353-A7A3EE081C15.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/C7742F49-C099-4B9F-A353-A7A3EE081C15.activeSandbox
Nov 26 14:34:35 C02P652UG3QD installd[716]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/C7742F49-C099-4B9F-A353-A7A3EE081C15.activeSandbox/Root (2 items) to /
Nov 26 14:34:35 C02P652UG3QD shove[48458]: [source=dir, dst=notExist] failed _RelinkFile(/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/C7742F49-C099-4B9F-A353-A7A3EE081C15.activeSandbox/Root/Library/PreferencePanes/OSXFUSE.prefPane, /Library/PreferencePanes/OSXFUSE.prefPane): No such file or directory
Nov 26 14:34:35 C02P652UG3QD shove[48458]: srcPath = /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/C7742F49-C099-4B9F-A353-A7A3EE081C15.activeSandbox/Root/Library/PreferencePanes/OSXFUSE.prefPane NSFileOwnerAccountID=0 NSFileSystemFileNumber=162601383 NSFileExtensionHidden=0 NSFileSystemNumber=16777220 NSFileSize=102 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2016-10-19 05:57:16 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=3 NSFileModificationDate=2016-10-19 05:57:16 +0000
Nov 26 14:34:35 C02P652UG3QD shove[48458]: dstParentPath = /Library/PreferencePanes NSFileOwnerAccountID=0 NSFileSystemFileNumber=866474 NSFileExtensionHidden=0 NSFileSystemNumber=16777220 NSFileSize=170 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2015-08-02 02:46:10 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=5 NSFileModificationDate=2016-10-27 05:40:36 +0000
Nov 26 14:34:35 C02P652UG3QD install_monitor[48426]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: releasing backupd
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: allow user idle system sleep
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={NSUnderlyingError=0x7f86a9d32530 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}, NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., arguments=(
	    "-f",
	    "-s",
	    "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/C7742F49-C099-4B9F-A353-A7A3EE081C15.activeSandbox/Root",
	    "/"
	)} {
	    NSLocalizedDescription = "An unexpected error occurred while moving files to the final destination.";
	    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"";
	    arguments =     (
	        "-f",
	        "-s",
	        "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/C7742F49-C099-4B9F-A353-A7A3EE081C15.activeSandbox/Root",
	        "/"
	    );
	}
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: Running idle tasks
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: Removing client PKInstallDaemonClient pid=48411, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Nov 26 14:34:36 C02P652UG3QD Installer[48411]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={arguments=(
	    "-f",
	    "-s",
	    "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/C7742F49-C099-4B9F-A353-A7A3EE081C15.activeSandbox/Root",
	    "/"
	), NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., NSUnderlyingError=0x7f9d62a017b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: Done with sandbox removals
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: Purging invalid sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/401C75C2-D700-426E-A65C-03418B88749B.trashedSandbox
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: Purging invalid sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/93695761-D866-498F-86B8-7B2F81A7E4B7.trashedSandbox
Nov 26 14:34:36 C02P652UG3QD installd[716]: PackageKit: Purging invalid sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/E8FE5E74-770A-48C7-A22B-065E9E8506DB.trashedSandbox
Nov 26 14:34:37 C02P652UG3QD Installer[48411]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Nov 26 14:34:37 C02P652UG3QD Installer[48411]: IFDInstallController 6061DE60 state = 8
Nov 26 14:34:37 C02P652UG3QD Installer[48411]: Displaying 'Install Failed' UI.
Nov 26 14:34:37 C02P652UG3QD Installer[48411]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by umireon** [comment]
It seems that something wrong with the permission: try [First Aid](http://www.macworld.co.uk/feature/mac-software/el-capitan-disk-utility-3634604/)
Or if you have Anti-Virus, disabling it during installation may allow FUSE to be installed.

**Comment by chim1005** [comment]
@BLaurent, were you able to resolve your installation issue?  If so, would you please share how you did it?
Thanks.

**Comment by BLaurent** [comment]
Still failing, I am upgrading to sierra will see.

**Comment by BLaurent** [comment]
Same issue on sierra

**Comment by chim1005** [comment]
Thanks for the update.  We are also seeing similar failures with different package on Sierra.

**Comment by BLaurent** [comment]
Well if I uncheck the install of the pane I got a success ...

**Comment by bfleischer** [comment]
Is this issue still reproducible with the latest version FUSE for macOS?

**Comment by iamphoccer** [comment]
I am seeing the same error trying to install 3.8.0 on Sierra:

May 16 12:16:15 hostname installd[497]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={NSUnderlyingError=0x7ff4b6c49030 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}, NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., arguments=(
            "-f",
            "-s",
            "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/CA56B4F3-07F1-49D9-8FBF-1F36F9CB86A1.activeSandbox/Root",
            "/"
        )} {
            NSLocalizedDescription = "An unexpected error occurred while moving files to the final destination.";
            NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=13 \"Permission denied\"";
            arguments =     (
                "-f",
                "-s",
                "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/CA56B4F3-07F1-49D9-8FBF-1F36F9CB86A1.activeSandbox/Root",
                "/"
            );
        }
