### ISSUE TITLE
help please with OSXfuse

### ISSUE THREAD

**Issue by jame0210** [osxfuse/osxfuse#338]
hello
I need help Please

I dont understand to much about computers

I created a volume in external hard drive with the Lacie 
Private-Public software where I put thousands of importante files.
I created it on my MAC with last version MacOS 10.11 and I accessed the files a lot of times
Then I spend many months without access to those files
and now When I try to access the files on external drive double clicking the icon Private-Public 
the window to put my password and have access to my files DOES NOT APPEAR.
and the message 
"OSXFUSE with MacFUSE Compatibility Layer is requires for Lacie Private-Public"

I already tried to update Fuse to last version but still not working.
Can you help me to solve this problem?
Its very importante to me

Thank you very much

Jose

**Comment by bfleischer** [comment]
Please contact LaCie's support. I've never used Private-Public and I'm not sure if it is even compatible with macOS 10.2. According to LaCies website Private Public supports Mac OS X 10.5 to 10.9.
