### ISSUE TITLE
Unable to mount ext4 disk

### ISSUE THREAD

**Issue by marty-b1** [osxfuse/osxfuse#340]
I am getting this message when I try to mount an external USB 3.0 drive:

"The disk you inserted was not readable by this computer."

I found someone with a [similar issue here](http://forums.macrumors.com/threads/usb-mounting-problem.1867273/) (but it looks like they are using ext2 while I have ext4).

I tried manually mounting the drive but that doesn't work either.  I get the following error in that case:

"diskutil mount readOnly /dev/disk2s1
Volume on disk2s1 failed to mount
If the volume is damaged, try the "readOnly" option"

Curiously, it still says "try the "readOnly" option" even though I _am_ trying the readOnly option.

Does anyone have any suggestions?

**Comment by ckrmml** [comment]
I currently copy from an ext4 partition, so it works. 
Steps i took:

1. install osxfuse
-> reboot
2. install [homebrew](http://brew.sh/index_de.html)
`$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
-> reboot
3. install [ext4fuse](https://github.com/gerard/ext4fuse) (via homebrew)
`$ brew install ext4fuse`
reboot
4. mount partition
`$ mkdir tmp`
`$ ext4fuse /dev/disk(disknumber)s(number_of_partition) /tmp`
so in your case
`$ ext4fuse /dev/disk2s1 /mount/path/you_choose`

I'm on El Capitan 10.11.6 (15G31), might be different on macOS Sierra, don't know about that

**Comment by marty-b1** [comment]
Can anyone confirm that for macOS 10.12.1? Is Homebrew normally required just to get this to work?  I thought OSXFuse was supposed to do this straight out of the box?

Thanks.

**Comment by ckrmml** [comment]
As far as i understand it, osxfuse does nothing out of the box except giving you the opportunity to install "plugins" to use different unsupported filesystems

check [README](https://github.com/osxfuse/osxfuse/blob/master/README.md)
> The FUSE for macOS software package **provides multiple APIs for developing file systems** for OS X 10.9 to macOS 10.12. It is a successor to MacFUSE, which has been the basis of many products, but is no longer being maintained.
> 
> **You can use the provided APIs to develop numerous types of file systems**, whose content can come from a local disk, from across the network, from memory, or any other source. One of these APIs is a superset of the FUSE API, that originated on Linux.

and [wiki](https://github.com/osxfuse/osxfuse/wiki)
> "FUSE for OS X" **allows you to extend** OS X's native file handling capabilities **via third-party file systems**. It is a successor to MacFUSE, which has been used as a software building block by dozens of products, but is no longer being maintained.

**Comment by marty-b1** [comment]
I did as you recommended and rebooted but I still get the exact same error.

**Comment by ckrmml** [comment]
Probably because you have only installed osxfuse and not ext4fuse after that. you need ext4fuse to mount the ext4 device/partition as far as i know

**Comment by marty-b1** [comment]
What I am saying I followed _your_ instructions with home brew too.

**Comment by xzxzzxzxzca** [comment]
Check out this thread https://github.com/gerard/ext4fuse/issues/27

**Comment by bfleischer** [comment]
I assume the issue has been resolved, so I'm closing the ticket.

**Comment by rhen49** [comment]
Having the exact same problem.  I was trying to follow the instructions [here](http://osxdaily.com/2014/03/20/mount-ext-linux-file-system-mac/) which I guess are wrong.  After following through what was said above and installing ext4fuse I can run this without errors:

```
mount partition
$ mkdir tmp
$ ext4fuse /dev/disk(disknumber)s(number_of_partition) /tmp
so in your case
$ ext4fuse /dev/disk2s1 /mount/path/you_choose
```


However, when I try to CD to the mount point I get this:

`-bash: cd: LTemp: No such file or directory`

In this case I had created the directory /LTemp to use as the mount point and I mounted the drive to it with the following command and I got no error.

`sudo ext4fuse /dev/disk2s1 /LTemp/`

**Comment by marty-b1** [comment]
I learned from another site that you need to use the "-o allow_other" flag if you want to be able to see the files if you are not root.

The command should look like this:

`sudo ext4fuse /dev/disk2s1 /LTemp -o allow_other`

**Comment by trireme** [comment]
"-o allow_other" flag works only if the ID of your user matches the ID of the user (or group) of the directories and files on the mounted hard drive, otherwise you want see them. You can create a user or group with the ID which has permission to see the directories and files with System Settings->User & Groups
