### ISSUE TITLE
allow_other with suid helper broken in 3.5.0

### ISSUE THREAD

**Issue by emilymaier** [osxfuse/osxfuse#343]
Starting in 3.5.0, the behavior of mount_osxfuse changed so that suid programs can't use allow_other when mounting a filesystem. Here's the test program I wrote and made suid root:

```
#include <unistd.h>

int main() {
	execl("/usr/local/bin/sshfs", "/usr/local/bin/sshfs", "-o", "allow_other",  "account", "/Volumes/Workstation", (char*) NULL);
	return 0;
}
```

In 3.4.2 running this program as an unprivileged user works fine. In 3.5.0 and 3.5.4 I get the following error:

> mount_osxfuse: failed to mount /Volumes/Workstation@/dev/osxfuse0: Operation not permitted

Is this a regression or intended behavior?

**Comment by bfleischer** [comment]
The mount_osxfuse helper needs root privileges to create mount points under /Volumes on macOS 10.12. mount_osxfuse is root owned and, starting with 3.5.0, its suid bit is set. The helper falls back to the real user ID for mounting the volume. This means that allow_other and allow_root can only be set if the real user ID is a member of the admin group.

The real user of your test program is the unprivileged user. As a workaround you can add the following two lines before calling `execl`.

    setuid(0);
    setgid(0);

**Comment by WhiteyDude** [comment]
I have a similar bash script to mount my various sshfs locations.

My mount point is under my user, not under Volumes, so suid permissions have never been required.

Is there a workaround for this behaviour? I could add sshfs to the NOPASSWD in sudoers, but I don't think this is a safe behaviour. I can't see another way to automate this though, as this fails no matter what I do.
