### ISSUE TITLE
Volume rename supported?

### ISSUE THREAD

**Issue by swt2c** [osxfuse/osxfuse#344]
Is volume renaming supported by the kext now?

I noticed that this change was committed in August:
https://github.com/osxfuse/osxfuse/commit/decd1b237b82d47ef7b30ed5f17ed8e2918975a7

**Comment by bfleischer** [comment]
No, but its on my todo list. When a volume is renamed, macOS also renames the mount point in /Volumes. Currently the FUSE user space library does not support this behavior. I'll need to rewrite some parts of libosxfuse to address the issue.

If you are using osxfuse commercially and are interested in sponsoring my work on this, feel free to contact me. You can find my email address on my GitHub profile.

**Comment by swt2c** [comment]
How much work needs to be done on the kext side?

I'm not using the FUSE user space library, but the bazil golang one, so I assume I would need similar support there.

**Comment by bfleischer** [comment]
The kext part should be mostly done. However, I will not release a version of osxfuse with volume rename support enabled in the kernel extension without libosxfuse supporting the feature. Kernel support and user space support are a package deal.
