### ISSUE TITLE
Building up connection failed

### ISSUE THREAD

**Issue by manuSrep** [osxfuse/osxfuse#345]
Since some days (maybe since the update on OS X 10.11.6) I am not longer able to use sshfs. No connection is established while the Finder freezes. No error message is shown. Is there anyone else with the problem and knows a solution?

Best Regards
Manuel

**Comment by bfleischer** [comment]
Which versions of FUSE and sshfs are you using?

**Comment by manuSrep** [comment]
MacBook-Pro-4:~ manuel$ sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.5.4
FUSE library version: 2.9.7
