### ISSUE TITLE
For Sierra, I am not able to move mount_ntfs even in recovery mode, hence the auto mount fails.

### ISSUE THREAD

**Issue by dhawalbanker** [osxfuse/osxfuse#348]
Any alternative methods? Currently I am using /etc/fstab to manually list all the external drive I have, but that's not the long term solution. 

Any help will be highly appreciated.

**Comment by bfleischer** [comment]
Did you follow the instructions on https://github.com/osxfuse/osxfuse/wiki/NTFS-3G? Which step did not work for you? Please post the exact error message.

**Comment by dhawalbanker** [comment]
I was not able to move mount_ntfs to .orig in recovery mode. 

sudo mv "/Volumes/Macintosh HD/sbin/mount_ntfs" "/Volumes/Macintosh HD/sbin/mount_ntfs.orig"

**Comment by bfleischer** [comment]
Are you sure you are in recovery mode? It sounds like you are in single user mode. In recovery mode the file system should be writeable. See https://support.apple.com/en-us/HT201314 for details on how to start the recovery system.

**Comment by dhawalbanker** [comment]
Thanks @bfleischer for your reply. I was pretty sure that I was in recovery mode. But its being to long to remember exactly. I will try again and will get back. 

This was mainly for auto NTFS mounting.
