### ISSUE TITLE
How to uninstall OSXFUSE?

### ISSUE THREAD

**Issue by AitchB** [osxfuse/osxfuse#350]
Hello everyone and a happy new year to you all. 

I purchased a Lima personal cloud dongle. The application uses OSXFUSE. For those who have never heard of it, Lima's dongle is attached to my router and to an external hard drive. I am supposed to then have access to all files on the EXHD from anywhere with any device. Lima's install app installs OSXFUSE on the EXHD and four folders (Desktop, Documents, Music, Movies, Pictures).  However, for reasons known only to them, Lima has in error installed OSXFUSE on the iMac's internal HD (I attach an image to better explain) and this now seems to be preventing subsequent installations of Lima finding the empty HD, which it needs. 

![lima 4 13 07 09](https://cloud.githubusercontent.com/assets/24973075/21741069/d81e30c8-d4cb-11e6-9faf-d2c7763171f9.png)

I am having trouble getting Lima to run to the point that I need to get OSXFUSE off my computer. It should then either allow me to carry on with my life or allow me to reinstall correctly the Lima. Lima support is a bit wanting.

I did not install OSXFUSE. I have no OXFUSE icon in the System Preferences pane. I have no OSXFUSE install or uninstall app.

My question is: How do I safely remove the Lima virtual disk (shown in the Info on the image). 

Any help will be highly appreciated.

Henry

**Comment by catwell** [comment]
Henry, I answered your question [on the Google Group](https://groups.google.com/forum/#!topic/osxfuse-group/CIvfx-hhzoM).

**Comment by AitchB** [comment]
Bonjour Pierre,

Thank you so much for responding to my cry of help and your explanation!
That is clearer than Support's last reply. I understand now that the "Lima"
disk image should be where it is! But you say if I uninstall the Lima app
it will also uninstall that disk image. It didn't!

I have the disk reformatted with the volume "Lima 6jan" - 6jan is the date.
Mac OS Extended (Journaled) /GUID. It still shows 1.31 GB of data on it
despite having tried to erase / delete / with both Mac's Disk Utility and
reformatting and deleting the HD on a PC then back to the Mac and changing
it back to Mac OS (J). The data is still there.

I'll let you ponder the problem and I'll be patient!

Thanks again for the reply,

Henry

**Comment by catwell** [comment]
@AitchB I will email you privately about this to avoid bothering the OSXFUSE Open Source project with this issue, which they are not responsible for.

**Comment by AitchB** [comment]
You have my email.

**Comment by mixtly87** [comment]
How to uninstalling osxfuse as if it never existed on macOS?

The first time you install osxfuse on your machine, you get the 'System Extension Blocked' dialog.

If you uninstall osxfuse and reinstall it, you will never again get the 'System Extension Blocked' dialog.

I would like to bring the system into such state that it shows that dialog so that I need to manually Allow the extension in Security & Privacy options.

Is there a way to do that?
