### ISSUE TITLE
Cannot install on MacBook

### ISSUE THREAD

**Issue by xros** [osxfuse/osxfuse#351]
I downloaded the latest osxfuse 3.5.4 for OS X

After opening it, i can't find the install button? Is that missing?

I thought the correct installation screen should be 
![image2](https://raw.githubusercontent.com/wiki/osxfuse/osxfuse/OSXFUSE_MacFUSE_Compatibility_Layer.png)

But I didn't find it...
I'm new to osxfuse.

![image](http://i.imgur.com/ZvKIEpO.png)

This mac
Macbook Pro 13
macOS Sierra 10.12.2

**Comment by bfleischer** [comment]
you need to double-click the "FUSE for macOS" icon in the center.
