### ISSUE TITLE
load_osxfuse and kextload fail, but resolved after reboot

### ISSUE THREAD

**Issue by gabriel** [osxfuse/osxfuse#358]
Fuse for macos: 3.5.5 (also experienced with 3.5.2)
MacOS: 10.12.3 

I wasn't able to load the osxfuse kext. It exited with code 255 with no output:

```sh
/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse; echo $?
255
```

I tried to load it via kextload:

```sh
sudo kextload /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.12/osxfuse.kext
/Library/Filesystems/osxfuse.fs/Contents/Extensions/10.12/osxfuse.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
```

I didn't see anything written to /var/log/system.log.

I rebooted and unfortunately the problem went away.

**Comment by gabriel** [comment]
It seems to happen if VMWare is running. I am running VMWare Version 8.5.3 (4696910).

**Comment by gabriel** [comment]
To repro:

```
sudo kextunload -b com.github.osxfuse.filesystems.osxfuse
# Load VMWare
/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse; echo $?
255
# Quit VMWare
/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse; echo $?
0
```

**Comment by bfleischer** [comment]
FUSE needs to register a virtual device for exchanging messages between the kernel and the actual file system implementation running in user space. The number of available device slots is limited by macOS. So if you are using other software like VMware, VirtualBox, TunTap, Intel HAXM, ..., that eat up all free device slots, FUSE will not be able to register its virtual device.

On a brand new install of macOS 10.12 there are six free device slots. VMware, VirtualBox both require multiple slots. TunTap (VPN) requires two slots, as far as I know. Intel HAXM requires at least one slot.

**Comment by gabriel** [comment]
Is the 255 exit code from loading signify not enough device slots or is that a generic error code?

Is there a way for us to detect this scenario ahead of time (so we can show a nice error message with potential workarounds)?

**Comment by bfleischer** [comment]
As far as I know it is not possible to return a meaningful error code from the kernel extension's start function. This means all the FUSE mount helper knows is that the kernel extension failed to load. The 255 exit code you are seeing does not signify that there are not enough device slots. 

Using `dmesg` you can see the error code returned by the kernel extension's start function but this is not very helpful in passing the error to the user.

    Kext com.github.osxfuse.filesystems.osxfuse start failed (result 0x5).

FUSE logs the following error message when it is unable to register a virtual device.

    osxfuse: Failed to register major device number

**Comment by gabriel** [comment]
Could there be any alternative way, you can think of, to get this error message without root privilege (since dmesg requires root)? 

I assume writing an error to a (special) log in /var/log/ readable from the kernel is a bad idea?

**Comment by gabriel** [comment]
Or maybe we could write a small utility which reports the number of available device slots?

**Comment by bfleischer** [comment]
> I assume writing an error to a (special) log in /var/log/osxfuse.log from the kernel is a bad idea?

Yes, probably.

> Or maybe we could write a small utility which reports the number of available device slots?

I'm not sure if it is possible to find out if there are free device slots left from a user space tool. What you can do is write a toll that calls `dmesg` and checks for `osxfuse: Failed to register major device number`.

Do you whether bazil-fuse uses the osxfuse helpers (load_osxfuse and mount_osxfuse) or a custom implementation? As a temporary workaround it might be possible to check for the error message in load_osxfuse. But this would certainly not be reliable since the `dmesg` buffer is limited.

I think it would be find a replacement for the character device based communication channel.

**Comment by gabriel** [comment]
Yeah it would appear any non-zero return from kext start, gets turned into  `kOSKextReturnStartStopError` (https://opensource.apple.com/source/xnu/xnu-2422.1.72/libkern/c++/OSKext.cpp, search for `result = kOSKextReturnStartStopError`).

The only reliable way I can think of to share info from kernel (not through dmesg) would be to use sysctl but you'd need a seperate kext thats sole purpose is to do this? There is no way to use sysctl without a loaded kext right?

**Comment by bfleischer** [comment]
> The only reliable way I can think of to share info from kernel (not through dmesg) would be to use sysctl but you'd need a seperate kext thats sole purpose is to do this? There is no way to use sysctl without a loaded kext right?

Yes, you need a loaded kernel extension for sending information like this to a user space process. Implementing a custom sysctl should work. Another option would be using a control socket.

**Comment by bfleischer** [comment]
Apple seems to have increased the number of available device slots in macOS 10.13. There seem to be 10 free device slots.

**Comment by judy** [comment]
That will be nice! Until then, is there no way to increase this number? As a developer, I need to use Virtual Box and a VPN that uses the tun/tap kexts, and can't figure out how to get this working. There still isn't an easy way to determine the number of free device slots, much less what things are taking up device slots.

**Comment by gabriel** [comment]
To free up slots:
- Unload smb kext (if not connecting to Windows machines): sudo kextunload -b com.apple.filesystems.smbfs
- Unload Intel HAXM: sudo kextunload -b com.intel.kext.intelhaxm

Unfortunately VirtualBox takes slots even when not running. VMWare is nicer, and frees up slots when it's not running.

**Comment by fridaynext** [comment]
Is there another way to free up slots, like uninstalling and reinstalling Fuse?  I've uninstalled Virtualbox completely, deleted the one profile I had in Tunnelblick, and uninstalled Tunnelblick, and I'm still getting the KBFS error.  Any other options besides a whole new reinstall of macOS?  Is there a command I can run to delete interfaces?

**Comment by gabriel** [comment]
Did you restart after uninstalling?

**Comment by shiggins8** [comment]
> Apple seems to have increased the number of available device slots in macOS 10.13. There seem to be 10 free device slots.

@bfleischer where did you find the documentation for that number? And are you aware of any way that I can check for that number dynamically from an app I'm coding on MacOS?

**Comment by mvmn** [comment]
> On a brand new install of macOS 10.12 there are six free device slots

How can one check the amount of free slots? What are those slots to begin with - are they mentioned in any Apple documentation? Can we ask Apple to increase number of those to something reasonable? What does it take to increase this number?

**Comment by bfleischer** [comment]
> How can one check the amount of free slots?

I don't think you can. The system will return an error when you try to register a new device and all slots are taken. 

> What are those slots to begin with - are they mentioned in any Apple documentation?

I don't know of any good Apple documentation regarding the device slots. All character device families visible in `/dev` need to be registered and the total number of is limited.  

https://developer.apple.com/documentation/kernel/cdevsw?language=objc

> Can we ask Apple to increase number of those to something reasonable? What does it take to increase this number?

Apple would need to alter the kernel. However, the situation seems to have gotten much better since macOS 10.12.

**Comment by mvmn** [comment]
Thank you very much for the response.

I've googled through documentation on macOS, Darwin and BSD and found information on character devices, but have found no mention of "slots" and no information on limits on number of those devices.

Is there really no documentation that mentions this? How did people even come up with terms like "slot" then? And how did it became known that 10.12 had 6 of those while 10.13 had 10 - determined empirically (e.g. via trial and error)?

Or perhaps I just didn't find the right documentaton yet.

**Comment by bfleischer** [comment]
I came up with the term "slot" for lack of any other word, that explains the situation well, and I found the number of of free "slots" by reading though the kernel code and registering more and more devices until the system returned an error.

**Comment by mvmn** [comment]
Oh, I see.

Which APIs did you use to register character device BTW? Did you use something like cdevsw_add?

**Comment by bfleischer** [comment]
See https://github.com/osxfuse/kext/blob/support/osxfuse-3/osxfuse/fuse_device.c#L547

**Comment by mvmn** [comment]
So you did use cdevsw_add. Good.
Thank you very much for all the details!

**Comment by mvmn** [comment]
P.S. It seems the term "slot" is actually used in kernel code
https://github.com/apple/darwin-xnu/blob/master/bsd/kern/bsd_stubs.c

**Comment by mvmn** [comment]
P.P.S. Looking at bsd_stubs.c and https://github.com/apple/darwin-xnu/blob/master/bsd/dev/i386/conf.c seems like the limit is the size of `cdevsw` structure (defined as `const int nchrdev = sizeof(cdevsw) / sizeof(cdevsw[0]);`)

The structure and thus the limit is platform dependent, but looks like for i386 it has size of 42, where free slots initially are 1, 9 to 11 and 13 to 41 (inclusive). Thus looking for free slots from slot 24 onwards should produce 18 of them. But then I'm not sure if there isn't anything else at play that takes away 8 more slots...

**Comment by prantlf** [comment]
I [forked](https://gist.github.com/prantlf/23bafe218e8a2def8085772ebe9bda62) Erik Gomez's [script](https://gist.github.com/erikng/d85b17e6e13fd8dcad7cf51d1c6b3a1c) (found in an [article](https://blog.quirke.org/macos/catalina/panic/fail/2019/10/28/post.html)) to list the loaded kernel extensions, unload some [as suggested](https://github.com/osxfuse/osxfuse/issues/358#issuecomment-316164723) by @gabriel and finally got macFUSE loaded:

```
$ kextsthatwillmakeanadmincry.py --loaded | jq '.IdentifiedKexts[]["Identifier"]'
"com.sentinelone.sentinel-kext"
"com.nomachine.driver.nxau"
"com.paragon-software.lvm-for-mac"
"com.GSI.kext.gsidrv"
"io.macfuse.filesystems.macfuse"
"com.cisco.kext.acsock"
"com.paragon-software.filesystems.extfs"
"net.sf.tuntaposx.tap"
"net.sf.tuntaposx.tun"
```

Thank you!

**Comment by prantlf** [comment]
By the way, @bfleischer, I am thankful that you publish installable packages at https://osxfuse.github.io/. When I tried `brew cask install osxfuse`, it failed. It tried to change the owner of `/usr/local/lib/sentinel.dylib`. It was not possible, because Sentinel protects its files. (All files in `/usr/local/lib` are owned by me, `sentinel.dylib` by `root`.) I have no idea why Homebrew (apparently?) tries to `chown` all files in `/usr/local/lib`. Unfortunately, my employer imposed the "malware" Sentinel on my Mac. Installing macFUSE aned SSHFS from `dmg` and `pkg` worked like a charm. Thank you!

**Comment by mvmn** [comment]
What happens if you install Homebrew into a dir in user home directory instead of the default location? It should keep all dependencies inside that directory AFAIK.

I use this to ensure it doesn't mess with SIP and other things in macOS - I've got homebrew in ~, and as far as I can tell it installs all libs into ~/homebrew/var/lib now
