### ISSUE TITLE
Trying to install Fuse on Mac OS X 10.12.2

### ISSUE THREAD

**Issue by guy-thornton** [osxfuse/osxfuse#359]
Getting an Package failed to install when running Fuse 3.5.5.dmg installer.
here is the log file output:
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: @(#)PROGRAM:Install  PROJECT:Install-1000
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: @(#)PROGRAM:Installer  PROJECT:Installer-909
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Hardware: MacBookAir7,2 @ 2.20 GHz (x 4), 8192 MB RAM
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Running OS Build: Mac OS X 10.12.2 (16C68)
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: TMPDIR=/var/folders/r2/s8vmbkz95q98mfrjhnsxpx5c0000gn/T/
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: HOME=/Users/williamthornton
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: SHELL=/bin/bash
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.zZJ73N2yjX/Listeners
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.OuM4c7MBaN/Render
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: LOGNAME=williamthornton
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000004.Installer
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: COMMAND_MODE=unix2003
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: USER=williamthornton
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Env: XPC_FLAGS=0x0
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: FUSE for macOS  Installation Log
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Opened from: /Volumes/FUSE for macOS/Extras/FUSE for macOS 3.5.5.pkg
Feb 14 16:26:35 C1MS81KHH3QK Installer[1318]: Product archive /Volumes/FUSE for macOS/Extras/FUSE for macOS 3.5.5.pkg trustLevel=202
Feb 14 16:26:40 C1MS81KHH3QK Installer[1318]: InstallerStatusNotifications plugin loaded
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: ================================================================================
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: User picked Custom Install
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: Choices selected for installation:
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: 	Upgrade: "FUSE for macOS"
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: 	Upgrade: "FUSE for macOS Core Components"
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: 		FUSE for macOS 3.5.5.pkg#Core.pkg : com.github.osxfuse.pkg.Core : 3.5.5
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: 	Upgrade: "FUSE for macOS Preference Pane"
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: 		FUSE for macOS 3.5.5.pkg#PrefPane.pkg : com.github.osxfuse.pkg.PrefPane : 3.5.5
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: 	Install: "MacFUSE Compatibility Layer"
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: 		FUSE for macOS 3.5.5.pkg#MacFUSE.pkg : com.github.osxfuse.pkg.MacFUSE : 3.5.5
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: ================================================================================
Feb 14 16:26:54 C1MS81KHH3QK Installer[1318]: It took 0.00 seconds to summarize the package selections.
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Administrator authorization granted.
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: ================================================================================
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: User picked Standard Install
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Choices selected for installation:
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: 	Upgrade: "FUSE for macOS"
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: 	Upgrade: "FUSE for macOS Core Components"
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: 		FUSE for macOS 3.5.5.pkg#Core.pkg : com.github.osxfuse.pkg.Core : 3.5.5
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: 	Upgrade: "FUSE for macOS Preference Pane"
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: 		FUSE for macOS 3.5.5.pkg#PrefPane.pkg : com.github.osxfuse.pkg.PrefPane : 3.5.5
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: 	Install: "MacFUSE Compatibility Layer"
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: 		FUSE for macOS 3.5.5.pkg#MacFUSE.pkg : com.github.osxfuse.pkg.MacFUSE : 3.5.5
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: ================================================================================
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: It took 0.00 seconds to summarize the package selections.
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#Core.pkg
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#PrefPane.pkg
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#MacFUSE.pkg
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Set authorization level to root for session
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Will use PK session
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Using authorization level of root for IFPKInstallElement
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Starting installation:
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Configuring volume "Macintosh HD"
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Preparing disk for local booted install.
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Free space on "Macintosh HD": 135.96 GB (135960100864 bytes).
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: Create temporary directory "/var/folders/r2/s8vmbkz95q98mfrjhnsxpx5c0000gn/T//Install.1318XYU0ai"
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: IFPKInstallElement (3 packages)
Feb 14 16:27:05 C1MS81KHH3QK installd[784]: PackageKit: Adding client PKInstallDaemonClient pid=1318, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Feb 14 16:27:05 C1MS81KHH3QK Installer[1318]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Feb 14 16:27:05 C1MS81KHH3QK installd[784]: PackageKit: ----- Begin install -----
Feb 14 16:27:05 C1MS81KHH3QK installd[784]: PackageKit: request=PKInstallRequest <3 packages, destination=/>
Feb 14 16:27:05 C1MS81KHH3QK installd[784]: PackageKit: packages=(
	    "PKLeopardPackage <file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#Core.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#PrefPane.pkg>",
	    "PKLeopardPackage <file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#MacFUSE.pkg>"
	)
Feb 14 16:27:05 C1MS81KHH3QK installd[784]: PackageKit: Session UUID file exists - will not overwrite /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox
Feb 14 16:27:06 C1MS81KHH3QK installd[784]: PackageKit: Extracting file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#Core.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root, uid=0)
Feb 14 16:27:07 C1MS81KHH3QK installd[784]: PackageKit: Extracting file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#PrefPane.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root, uid=0)
Feb 14 16:27:07 C1MS81KHH3QK installd[784]: PackageKit: Extracting file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.5.5.pkg#MacFUSE.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root, uid=0)
Feb 14 16:27:07 C1MS81KHH3QK installd[784]: PackageKit: prevent user idle system sleep
Feb 14 16:27:07 C1MS81KHH3QK installd[784]: PackageKit: suspending backupd
Feb 14 16:27:07 C1MS81KHH3QK installd[784]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.8XFMBS/Scripts/com.github.osxfuse.pkg.Core.C59za7
Feb 14 16:27:08 C1MS81KHH3QK install_monitor[1589]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Feb 14 16:27:09 C1MS81KHH3QK installd[784]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.8XFMBS/Scripts/com.github.osxfuse.pkg.MacFUSE.9Lsjm5
Feb 14 16:27:10 C1MS81KHH3QK installd[784]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox
Feb 14 16:27:10 C1MS81KHH3QK installd[784]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root (2 items) to /
Feb 14 16:27:11 C1MS81KHH3QK shove[1625]: [source=dir, dst=notExist] failed _RelinkFile(/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root/Library/PreferencePanes/OSXFUSE.prefPane, /Library/PreferencePanes/OSXFUSE.prefPane): No such file or directory
Feb 14 16:27:11 C1MS81KHH3QK shove[1625]: srcPath = /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root/Library/PreferencePanes/OSXFUSE.prefPane NSFileOwnerAccountID=0 NSFileSystemFileNumber=9523337 NSFileExtensionHidden=0 NSFileSystemNumber=16777220 NSFileSize=102 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2017-01-29 23:09:49 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=3 NSFileModificationDate=2017-01-29 23:09:49 +0000
Feb 14 16:27:11 C1MS81KHH3QK shove[1625]: dstParentPath = /Library/PreferencePanes NSFileOwnerAccountID=0 NSFileSystemFileNumber=627450 NSFileExtensionHidden=0 NSFileSystemNumber=16777220 NSFileSize=170 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2016-07-30 22:51:52 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=5 NSFileModificationDate=2017-02-14 15:58:34 +0000
Feb 14 16:27:11 C1MS81KHH3QK install_monitor[1589]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Feb 14 16:27:11 C1MS81KHH3QK installd[784]: PackageKit: releasing backupd
Feb 14 16:27:11 C1MS81KHH3QK installd[784]: PackageKit: allow user idle system sleep
Feb 14 16:27:11 C1MS81KHH3QK installd[784]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={NSUnderlyingError=0x7fd448f8f490 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}, NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., arguments=(
	    "-f",
	    "-s",
	    "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root",
	    "/"
	)} {
	    NSLocalizedDescription = "An unexpected error occurred while moving files to the final destination.";
	    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"";
	    arguments =     (
	        "-f",
	        "-s",
	        "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root",
	        "/"
	    );
	}
Feb 14 16:27:11 C1MS81KHH3QK installd[784]: PackageKit: Running idle tasks
Feb 14 16:27:11 C1MS81KHH3QK Installer[1318]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={arguments=(
	    "-f",
	    "-s",
	    "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/4BEB8C83-0180-4F9A-A666-D2ACC23A8E7B.activeSandbox/Root",
	    "/"
	), NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., NSUnderlyingError=0x60000024d860 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Feb 14 16:27:11 C1MS81KHH3QK installd[784]: PackageKit: Removing client PKInstallDaemonClient pid=1318, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Feb 14 16:27:11 C1MS81KHH3QK installd[784]: PackageKit: Done with sandbox removals
Feb 14 16:27:12 C1MS81KHH3QK installd[784]: PackageKit: Sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/15078E70-1B22-4C71-8930-30DAD4F087B9.sandbox: relevance 1593
Feb 14 16:27:12 C1MS81KHH3QK Installer[1318]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Feb 14 16:27:12 C1MS81KHH3QK Installer[1318]: IFDInstallController C600 state = 8
Feb 14 16:27:12 C1MS81KHH3QK Installer[1318]: Displaying 'Install Failed' UI.
Feb 14 16:27:12 C1MS81KHH3QK Installer[1318]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
Feb 14 16:27:41 C1MS81KHH3QK Installer[1318]: IFJS: *** exception: TypeError: null is not an object (evaluating 'my.target.receiptForIdentifier')
Feb 14 16:27:41 C1MS81KHH3QK Installer[1318]: IFJS: *** exception: TypeError: null is not an object (evaluating 'my.target.receiptForIdentifier')
Feb 14 16:27:41 C1MS81KHH3QK Installer[1318]: IFJS: *** exception: TypeError: null is not an object (evaluating 'my.target.receiptForIdentifier')
Feb 14 16:27:41 C1MS81KHH3QK Installer[1318]: IFJS: *** exception: TypeError: null is not an object (evaluating 'my.target.receiptForIdentifier')

**Comment by bfleischer** [comment]
Is this issue still reproducible with the latest version of FUSE for macOS?

**Comment by ipatch** [comment]
@bfleischer 

I'd go ahead and close some of these issues that you labeled **feedback required** it makes others browsing through open issues to find on going issues.
