### ISSUE TITLE
Mountpoint directory name replaced by "OSXFUSE Volume 0 (encfs)" in Finder

### ISSUE THREAD

**Issue by jmascart** [osxfuse/osxfuse#361]
I use osxfuse for 3 different FUSE FS:
- encfs
- acdcli
- an hello world fuse

With all of these, when i mount the fuse FS in a directory, the directory disappear from Finder. And a new item shows up:
![image](https://cloud.githubusercontent.com/assets/12075001/23653948/c22c7ffe-032e-11e7-8ee4-b1ed7e946109.png)

I'd like that Finder keep showing the original directory. Is it related to osxfuse ?

**Comment by bfleischer** [comment]
The mount option `volname` can be used to set the name of the mounted volume. Running `encfs` with the following option `-o volname=Secret` will display the name "Secret" in Finder instead of "OSXFUSE Volume 0 (encfs)".
