### ISSUE TITLE
Fuse, VeraCrypt, NTFS -> Read only

### ISSUE THREAD

**Issue by xxvxxv** [osxfuse/osxfuse#362]
Hi, im not sure if the VeraCrypt is the problem or the Fuse. Encrypted container (NTFS) is read only in Mac, but because FAT-containers work fine, I guess I'm doing something wrong with Fuse? 

A veracrypt container: 
file: ABC
size: 50 gb
format. ntfs
created under windows laptop with veracrypt
placed on the nas

When I mount the file ABC using MacBook, it is on read-only state although VeraCrypt says "read only: no" and I checked also that the option is not selected when mounting the container. "Get info" in MacOs says "Sharing & Permission: you can read only"

So, I cannot add files to the container in Mac OS (Sierra 10.12.3), VeraCrypt 1.19 and Fuse 3.5.5 installed. 

(FAT containers (only 2 gb) are working ok, but this ntfs file doesn't.)

**Comment by xxvxxv** [comment]
Apparently it wasn't enough just to install Fuse to be able to write NTFS volumes... Because I cannot write to any NTFS drives either.

**Comment by bfleischer** [comment]
You need to install NTFS-3G to be able to write to NTFS volumes. FUSE is a library that can be used by third party developers as a building block to write file system drivers. NTFS-3G is such a file system. See https://github.com/osxfuse/osxfuse/wiki/NTFS-3G for instructions on how to install NTFS-3G.
