### ISSUE TITLE
Error: could not copy extended attributes (but it is working)

### ISSUE THREAD

**Issue by xros** [osxfuse/osxfuse#363]
I installed the osxfuse.dmg(3.5.5) downloaded directly from the site, then I installed ntfs from `brew install ntfs-3g`.
The first time it didn't work but after that I re-installed that and rebooted the Macbook, it worked. 

OS X 10.12.3
I tried to copy a file to a NTFS hard drive. After it finished , an error came out as the following one.

Using command `cp ./install60.iso /Volumn/NTFS/`

```could not copy extended attributes to ./install60.iso: Operation not supported on socket```

Then I tried to do the file fingerprint check using `shasum -a 256 install60.iso` It turned out the new file was 100% good. What wrong is that? 

P.S. Using the Finder App on Mac to copy files would fail at last.

**Comment by xros** [comment]
Okay. I read from some articles about this. This turned out to be caused by the difference of file system.  So here I can use `rsync` to replace `cp` which is a bit of less-relaxed. Hope we could make this better.

**Comment by raubreywhite** [comment]
This seems to be a problem on High Sierra, copying to a rclone mounted drive.

**Comment by jee1mr** [comment]
Any update on this?

**Comment by lassiter** [comment]
I can confirm it's a issue on Mojave too.

**Comment by csuka** [comment]
any fix?

**Comment by murilo8812** [comment]
use rsync instead of cp worked for me

**Comment by retokromer** [comment]
Or `gcp --preserve=mode,timestamps` works on my end.

**Comment by aprilspace** [comment]
sudo rsync -aP source destination

**Comment by Dhakshith** [comment]
Navigating with ../../ worked for me. No idea why.

**Comment by kupietools** [comment]
None of these solutions worked for me on mojave. rsync just gave me `rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.2/rsync/main.c(996) [sender=2.6.9]`, all other suggestions above result in "device not configured" error.

**Comment by moshix** [comment]
this works for me: 

- mount the file system on a Linux box
- scp the files from your Mac over to the Linux box and let Linux write the files to the file system

Yes, it's a bit more cumbersome, and slower, but it gets it done. 

As an alternative, you can scp the files to your own Mac. This also works for me. Must faster.

**Comment by SN-F-QR** [comment]
> None of these solutions worked for me on mojave. rsync just gave me `rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.2/rsync/main.c(996) [sender=2.6.9]`, all other suggestions above result in "device not configured" error.

Can be solved by using sudo before rsync

**Comment by stopsopa** [comment]
Use rsync

```

rsync -azP --no-o --no-g "${SOURCE}/" "{TARGET}/"

```

be careful though to make sure if SOURCE and TARGET points to directories to add / to the end of both of them. as above
