### ISSUE TITLE
Context with data file source for file/folder copy

### ISSUE THREAD

**Issue by radj** [osxfuse/osxfuse#365]
At the FUSE level delegates, we can get FUSE context for the process that's doing the operation. I am suggesting to also include file source if it is a copy.

For example, a user is copying an html file only from outside the file system into the file system. We would want to parse the html file and also copy the other resources that was surrounding this file from the source directory. This is a trivial example as this is a user error for not copying everything but it's the idea of having a reference to the source.

Is this possible to implement in a FUSE delegate or in FUSE itself?

**Comment by bfleischer** [comment]
FUSE doesn't to actually know if a file is being copied. All FUSE sees is a series of read and write calls. I agree with you, this would be useful feature but I don't think it is possible to implement this on the VFS level.

**Comment by radj** [comment]
I understand.

Out of topic though: say, if we were to implement this outside and complimenting FUSE, would you have any suggestion how to accomplish this?
