### ISSUE TITLE
Accessing to shared folder

### ISSUE THREAD

**Issue by gkirlik** [osxfuse/osxfuse#366]
Dear All,

I have a problem with accessing a shared folder using sshfs. I can read, write and execute in my local folders via mounted folder. However, I could not access to shared folder. I mounted a directory using following command and "source" folder is shared.

$ sshfs -o allow_other,default_permissions user@adress:/home/local /home/source

$ cd /home/source
$ ls
documentation projects software
$ cd software/
-bash: cd: software/: Permission denied

Apparently, there is a problem with the file permission after mounting with sshfs.

$ ll -a
drwxrwxr-x 1 1000 authedusers 4096 Mar 13 12:33 .
drwxr-xr-x 4 user staff 136 Mar 20 15:35 ..
drwxr-x--- 1 1000 authedusers 4096 Mar 13 12:33 documentation
drwxrwx--- 1 1000 authedusers 4096 Feb 22 12:12 projects
drwxr-x--- 1 1000 authedusers 4096 Feb 22 12:11 software

How can I solve this problem?

Best,
Gokhan

**Comment by bfleischer** [comment]
Have you tried mounting the volume with the `defer_permissions` option instead of `default_permissions`? For details see https://github.com/osxfuse/osxfuse/wiki/Mount-options#default_permissions-and-defer_permissions.
