### ISSUE TITLE
Problems with MAC OS 10.12.4

### ISSUE THREAD

**Issue by doceno** [osxfuse/osxfuse#368]
Hello dear developers, am having problems installing on this OS version.
This is the message:

Error - This release of OSXFUSE is not compatible with the version of OS X you are running.
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/usr/local/Caskroom/osxfuse/2.8.3/Install OSXFUSE 2.8.pkg>", "-target", "/"]

==> Output of failed command:

==> Exit status of failed command:
#<Process::Status: pid 1174 exit 1>

Thanks for the hard work!

**Comment by bfleischer** [comment]
Hi @doceno,

the version of FUSE you are trying to install is outdated and is not compatible with macOS Sierra. You need to update your HomeBrew formulas first, or download the the latest version of FUSE from https://osxfuse.github.io.

**Comment by doceno** [comment]
Thanks you very much for the quick answer, am testing now updating brew and also will check downloading it from github.

Thanks again.
