### ISSUE TITLE
ntfs-3g in 10.12.4 macOS

### ISSUE THREAD

**Issue by raviabi11** [osxfuse/osxfuse#370]
Mounted the NTFS volume manually.
All the files in the drive are listing with size as zero bytes. [something to do with the changes in metadata reading]
Write operation fails with error "Error code -36"

**Comment by bfleischer** [comment]
NTFS-3G and FUSE for macOS are independent projects. Please post any NTFS-3G related issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7.
