### ISSUE TITLE
Possible mistake in Apple Developer Certificate for maintainer?

### ISSUE THREAD

**Issue by stysedo** [osxfuse/osxfuse#374]
I noticed that there was a change in the Apple Developer Certificate that was used to sign the osxfuse-3.5.7prerelease.
Is the change of country from Germany to US intended or did Apple make a mistake with the parameters of this Certificate renewal?. Or is something else going on...

**Comment by stysedo** [comment]
Further details:
This pertains to the Installer Certificate as displayed in Installer.app for FUSE for macOS.pkg//FUSE for macOS 3.5.7.pkg and not the Application Certificate used to sign the installed components.

![fuse for macos pkg installercert](https://cloud.githubusercontent.com/assets/22488914/25071143/fa020340-227d-11e7-8d4d-e2ba1b62c5ce.png)

**Comment by bfleischer** [comment]
> Is the change of country from Germany to US intended or did Apple make a mistake with the parameters of this Certificate renewal?

The change from DE to US was not intended. As far as I know Apple is responsible for the certificate's subject information. I don't know why they chose US for the new certificate. But I don't think this is a big deal. The old certificate expired last month so I had to request a new one. Nothing else has changed.

**Comment by stysedo** [comment]
Sloppiness by Apple in filling in the 'Subject' information during certificate renewal is certainly a plausible explanation.
I may report this example to Apple's certificate policy administrator to make them aware of their propensity for errors.  
Please do not take it personally.
