### ISSUE TITLE
pid in fuse_context

### ISSUE THREAD

**Issue by mlhartme** [osxfuse/osxfuse#378]
I'd like to write a file system that checks the process id of the caller.

fuse_context provides uid, gid und pid, where pid seem to be a thread it.
Can you tell me how to map this thread id to the process id of the caller?
Or, if that's not possible - can you provide a process id in fuse_context?

Best Regards

Michael

**Comment by bfleischer** [comment]
The pid returned by `fuse_get_context()` should be the actual pid of the process responsible for the file system operation. Can you provide some sample code that shows the issue?

**Comment by mlhartme** [comment]
After some retesting, I cannot reproduce the problem. fuse_get_context() returns the proper pid.

Sorry for the inconvenience!
