### ISSUE TITLE
MacOS 10.13

### ISSUE THREAD

**Issue by DiegoGiovany** [osxfuse/osxfuse#380]
Almost all software from 10.12 works well on 10.13...

But sshfs shows a error of unsuported osx, maybe  only a version bump is needed...

Thanks

**Comment by Ajaybh** [comment]
I tried fuse installation yesterday and got the same results. Hopefully, Apple File System and encryption do not bring any surprise.

**Comment by bfleischer** [comment]
The current version of FUSE does not work on macOS 10.13. This is intentional. FUSE is based on a kernel extension and works on a lower level than most apps you might be using. Incompatibilities between kernel extensions and new versions of macOS can result in kernel panics and data loss. To make sure this does not happen, the current version of FUSE will only work on Mac OS X 10.5 to macOS 10.12.   

I will publish a new release that supports macOS 10.13 once I've had a chance run some tests and address compatibility issues, should there be any.

**Comment by Ajaybh** [comment]
Thanks for the update!

**Comment by DiegoGiovany** [comment]
Thanks for the update !!! 
Since I really need to use sshfs as soon as possible, I've trying to build a new version myself, but even if I change all 10.12 on the code to 10.13,   I aways get this error:

Falling back to macOS 10.12 SDK as default SDK
T:distribution       | macOS 10.12 SDK not supported
Terminated: 15

Can you point-me the direction to get it to compile?

**Comment by jq1106** [comment]
After latest commit compile gets a little further, but still errors.

Log for anyone that cares:
`Running libtoolize...
./makeconf.sh: line 13: libtoolize: command not found
Running autoreconf...
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:77: warning: macro 'AM_ICONV' not found in library
configure.ac:10: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:77: error: possibly undefined macro: AM_ICONV
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
T:library            | Failed to make configuration
Terminated: 15
Received signal: SIGTERM
`

**Comment by bfleischer** [comment]
@jq1106 Please make sure your build environment is set up correctly. See README for details. The latest commit https://github.com/osxfuse/osxfuse/commit/42ff4d6584c6a42a37e92a5d7338dec1f17020bb can be built on macOS 10.12 with Xcode 9 and should work on 10.13. However, I'm not done running compatibility tests.

I've not tried building FUSE on macOS 10.13, yet. To "cross-compile" the distribution target on macOS 10.12 for running on 10.13 use the following build command:

    ./build.sh -v 5 -t distribution -- -s 10.13 -d 10.13

The FUSE kernel extension built by the above command will not be codesigned. You will need to disable System Integrity Protection (or sign the extension with your kernel extensions signing certificate), otherwise macOS will refuse to load it.

**Comment by DiegoGiovany** [comment]
I'm on 10.13, and, aways getting this error: Falling back to macOS 10.12 SDK as default SDK 

Can you make your "alpha/beta" build avaliable? we can help with the tests

Thanks

**Comment by dany20mh** [comment]
@DiegoGiovany For SDK you need to install Xcode 9 and restart your computer, I was getting that error too.

@bfleischer 
I'm getting this error now:

```
./build.sh -v 5 -t distribution -- -s 10.13 -d 10.13
DEFAULT_BUILD_CONFIGURATION=Release
DEFAULT_BUILD_DIRECTORY=/tmp/osxfuse
DEFAULT_LOG_VERBOSE=2
DEFAULT_PREFIX=''
DEFAULT_SDK=10.13
DEFAULT_SDK_10_10_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_10_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_11_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_11_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_12_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_12_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_13_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_13_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_5_ARCHITECURES=([0]=ppc [1]=ppc64 [2]=i386 [3]=x86_64)
DEFAULT_SDK_10_5_COMPILER=4.2
DEFAULT_SDK_10_6_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_6_COMPILER=com.apple.compilers.llvmgcc42
DEFAULT_SDK_10_7_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_7_COMPILER=com.apple.compilers.llvmgcc42
DEFAULT_SDK_10_8_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_8_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_9_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_9_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_SUPPORTED=([0]=10.5 [1]=10.6 [2]=10.7 [3]=10.8 [4]=10.9 [5]=10.10 [6]=10.11 [7]=10.12 [8]=10.13)
DEFAULT_SOURCE_DIRECTORY=/Users/danial/Downloads/osxfuse-support-osxfuse-3
BUILD_SOURCE_DIRECTORY=/Users/danial/Downloads/osxfuse-support-osxfuse-3
BUILD_BUILD_DIRECTORY=/tmp/osxfuse
Search for Xcode
Xcode 9.0 found at path '/Applications/Xcode.app/Contents/Developer'
XCODE_9_0_PATH=/Applications/Xcode.app/Contents/Developer
XCODE_INSTALLED=([0]=9.0)
XCODE_SDK_10_13_XCODE=([0]=9.0)
XCODE_SDK_INSTALLED=([0]=10.13)
Done searching for Xcode
Source extension osxfuse
T:distribution       | Source target distribution
T:distribution       | Invoke action build
T:distribution       | BUILD_TARGET_OPTION_ARCHITECTURES=([0]=i386 [1]=x86_64)
T:distribution       | BUILD_TARGET_OPTION_BUILD_CONFIGURATION=Release
T:distribution       | BUILD_TARGET_OPTION_BUILD_SETTINGS=()
T:distribution       | BUILD_TARGET_OPTION_CODE_SIGN_IDENTITY=''
T:distribution       | BUILD_TARGET_OPTION_DEBUG_DIRECTORY=''
T:distribution       | BUILD_TARGET_OPTION_DEPLOYMENT_TARGET=10.13
T:distribution       | BUILD_TARGET_OPTION_GROUP=''
T:distribution       | BUILD_TARGET_OPTION_MACROS=()
T:distribution       | BUILD_TARGET_OPTION_OWNER=''
T:distribution       | BUILD_TARGET_OPTION_PREFIX=''
T:distribution       | BUILD_TARGET_OPTION_PRODUCT_SIGN_IDENTITY=''
T:distribution       | BUILD_TARGET_OPTION_PROVISIONING_PROFILE_SPECIFIER=''
T:distribution       | BUILD_TARGET_OPTION_ROOT=0
T:distribution       | BUILD_TARGET_OPTION_SDK=10.13
T:distribution       | BUILD_TARGET_OPTION_XCODE=9.0
T:distribution       | DISTRIBUTION_KEXT_TASKS=([0]=10.13)
T:distribution       | DISTRIBUTION_MACFUSE=0
T:distribution       | Clean target
T:distribution       | Source target distribution
T:distribution       | Invoke action clean
T:distribution       | BUILD_TARGET_OPTION_ARCHITECTURES=([0]=i386 [1]=x86_64)
T:distribution       | BUILD_TARGET_OPTION_BUILD_CONFIGURATION=Release
T:distribution       | BUILD_TARGET_OPTION_BUILD_SETTINGS=()
T:distribution       | BUILD_TARGET_OPTION_CODE_SIGN_IDENTITY=''
T:distribution       | BUILD_TARGET_OPTION_DEBUG_DIRECTORY=''
T:distribution       | BUILD_TARGET_OPTION_DEPLOYMENT_TARGET=10.13
T:distribution       | BUILD_TARGET_OPTION_GROUP=''
T:distribution       | BUILD_TARGET_OPTION_MACROS=()
T:distribution       | BUILD_TARGET_OPTION_OWNER=''
T:distribution       | BUILD_TARGET_OPTION_PREFIX=''
T:distribution       | BUILD_TARGET_OPTION_PRODUCT_SIGN_IDENTITY=''
T:distribution       | BUILD_TARGET_OPTION_PROVISIONING_PROFILE_SPECIFIER=''
T:distribution       | BUILD_TARGET_OPTION_ROOT=0
T:distribution       | BUILD_TARGET_OPTION_SDK=10.13
T:distribution       | BUILD_TARGET_OPTION_XCODE=9.0
T:distribution       | Removing target build directory '/tmp/osxfuse/distribution'
T:distribution       | Completed action clean
T:distribution       | Build target for macOS 10.13
T:fsbundle           | Source target fsbundle
T:fsbundle           | Invoke action build
T:fsbundle           | BUILD_TARGET_OPTION_ARCHITECTURES=([0]=i386 [1]=x86_64)
T:fsbundle           | BUILD_TARGET_OPTION_BUILD_CONFIGURATION=Release
T:fsbundle           | BUILD_TARGET_OPTION_BUILD_SETTINGS=([0]=ENABLE_MACFUSE_MODE=0)
T:fsbundle           | BUILD_TARGET_OPTION_CODE_SIGN_IDENTITY=''
T:fsbundle           | BUILD_TARGET_OPTION_DEBUG_DIRECTORY=''
T:fsbundle           | BUILD_TARGET_OPTION_DEPLOYMENT_TARGET=10.13
T:fsbundle           | BUILD_TARGET_OPTION_GROUP=''
T:fsbundle           | BUILD_TARGET_OPTION_MACROS=()
T:fsbundle           | BUILD_TARGET_OPTION_OWNER=''
T:fsbundle           | BUILD_TARGET_OPTION_PREFIX=''
T:fsbundle           | BUILD_TARGET_OPTION_PRODUCT_SIGN_IDENTITY=''
T:fsbundle           | BUILD_TARGET_OPTION_PROVISIONING_PROFILE_SPECIFIER=''
T:fsbundle           | BUILD_TARGET_OPTION_ROOT=0
T:fsbundle           | BUILD_TARGET_OPTION_SDK=10.13
T:fsbundle           | BUILD_TARGET_OPTION_XCODE=9.0
T:fsbundle           | FSBUNDLE_KEXT_TASKS=([0]=10.13)
T:fsbundle           | Clean target
T:fsbundle           | Source target fsbundle
T:fsbundle           | Invoke action clean
T:fsbundle           | BUILD_TARGET_OPTION_ARCHITECTURES=([0]=i386 [1]=x86_64)
T:fsbundle           | BUILD_TARGET_OPTION_BUILD_CONFIGURATION=Release
T:fsbundle           | BUILD_TARGET_OPTION_BUILD_SETTINGS=()
T:fsbundle           | BUILD_TARGET_OPTION_CODE_SIGN_IDENTITY=''
T:fsbundle           | BUILD_TARGET_OPTION_DEBUG_DIRECTORY=''
T:fsbundle           | BUILD_TARGET_OPTION_DEPLOYMENT_TARGET=10.13
T:fsbundle           | BUILD_TARGET_OPTION_GROUP=''
T:fsbundle           | BUILD_TARGET_OPTION_MACROS=()
T:fsbundle           | BUILD_TARGET_OPTION_OWNER=''
T:fsbundle           | BUILD_TARGET_OPTION_PREFIX=''
T:fsbundle           | BUILD_TARGET_OPTION_PRODUCT_SIGN_IDENTITY=''
T:fsbundle           | BUILD_TARGET_OPTION_PROVISIONING_PROFILE_SPECIFIER=''
T:fsbundle           | BUILD_TARGET_OPTION_ROOT=0
T:fsbundle           | BUILD_TARGET_OPTION_SDK=10.13
T:fsbundle           | BUILD_TARGET_OPTION_XCODE=9.0
T:fsbundle           | Removing target build directory '/tmp/osxfuse/fsbundle'
T:fsbundle           | Completed action clean
T:fsbundle           | Build target for macOS 10.13
Build settings from command line:
    ARCHS = i386 x86_64
    CODE_SIGN_IDENTITY = 
    CONFIGURATION_BUILD_DIR = /tmp/osxfuse/fsbundle
    ENABLE_MACFUSE_MODE = 0
    GCC_VERSION = com.apple.compilers.llvm.clang.1_0
    MACOSX_DEPLOYMENT_TARGET = 10.13
    PROVISIONING_PROFILE_SPECIFIER = 
    SDKROOT = macosx10.13

xcodebuild: error: 'osxfusefs.xcodeproj' does not exist.
T:fsbundle           | Failed to build target
Terminated: 15
Received signal: SIGTERM
```

**Comment by DiegoGiovany** [comment]
I had to delete xcode 8.3.3, and compilation comes to this (long after last error):

PhaseScriptExecution BridgeSupport\ Metadata build/OSXFUSE.build/Release/OSXFUSE.build/Script-28D525C40EA8076400B7CF7B.sh
    cd /Users/Diego/dev/osxfuse/framework
    /bin/sh -c /Users/Diego/dev/osxfuse/framework/build/OSXFUSE.build/Release/OSXFUSE.build/Script-28D525C40EA8076400B7CF7B.sh
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/System/Library/BridgeSupport/ruby-2.3/bridgesupportparser.bundle, 9): Library not loaded: @rpath/libclang.dylib (LoadError)
  Referenced from: /System/Library/BridgeSupport/ruby-2.3/bridgesupportparser.bundle
  Reason: image not found - /System/Library/BridgeSupport/ruby-2.3/bridgesupportparser.bundle
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/BridgeSupport/ruby-2.3/bridgesupportparser.rb:6:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/bin/gen_bridge_metadata:65:in `<main>'
Command /bin/sh failed with exit code 1

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution BridgeSupport\ Metadata build/OSXFUSE.build/Release/OSXFUSE.build/Script-28D525C40EA8076400B7CF7B.sh
(1 failure)
T:framework          | Failed to build target
Terminated: 15
Received signal: SIGTERM

**Comment by akio-ito** [comment]
@bfleischer Thank you!
Worked for me with following steps:

Compile with **MacOS 10.12** (iMac 2016 16GB RAM Fusion Drive) 
1. Download XCode 9
2. Execute XCode Beta to automatically Install Components
3. Confirm if OK
    xcode-select -print-path (must be /Applications/Xcode-beta.app/Contents/Developer)
 
4. Clone and Compile osxfuse
    git clone --recursive -b support/osxfuse-3 git://github.com/osxfuse/osxfuse.git osxfuse
    cd osxfuse
    ./build.sh -v 5 -t distribution -- -s 10.13 -d 10.13
    …
** BUILD SUCCEEDED **
 
T:prefpane           | Completed action build
T:prefpane           | Source target prefpane
T:prefpane           | Invoke action install
T:prefpane           | BUILD_TARGET_OPTION_ARCHITECTURES=([0]=i386 [1]=x86_64)
T:prefpane           | BUILD_TARGET_OPTION_BUILD_CONFIGURATION=Release
T:prefpane           | BUILD_TARGET_OPTION_BUILD_SETTINGS=()
T:prefpane           | BUILD_TARGET_OPTION_CODE_SIGN_IDENTITY=''
T:prefpane           | BUILD_TARGET_OPTION_DEBUG_DIRECTORY=''
T:prefpane           | BUILD_TARGET_OPTION_DEPLOYMENT_TARGET=10.13
T:prefpane           | BUILD_TARGET_OPTION_GROUP=''
T:prefpane           | BUILD_TARGET_OPTION_MACROS=()
T:prefpane           | BUILD_TARGET_OPTION_OWNER=''
T:prefpane           | BUILD_TARGET_OPTION_PREFIX=''
T:prefpane           | BUILD_TARGET_OPTION_PRODUCT_SIGN_IDENTITY=''
T:prefpane           | BUILD_TARGET_OPTION_PROVISIONING_PROFILE_SPECIFIER=''
T:prefpane           | BUILD_TARGET_OPTION_ROOT=0
T:prefpane           | BUILD_TARGET_OPTION_SDK=10.13
T:prefpane           | BUILD_TARGET_OPTION_XCODE=9.0
T:prefpane           | Install target
T:prefpane           | Completed action install
T:distribution       | Build preference pane component package
pkgbuild: Inferring bundle components from contents of /tmp/osxfuse/distribution/PrefPane
pkgbuild: Writing new component property list to /tmp/osxfuse/distribution/Packages/PrefPane.plist
pkgbuild: Reading components from /tmp/osxfuse/distribution/Packages/PrefPane.plist
pkgbuild: Adding component at Library/PreferencePanes/OSXFUSE.prefPane
pkgbuild: Wrote package to /tmp/osxfuse/distribution/Packages/PrefPane.pkg
T:distribution       | Build distribution package
productbuild: Wrote product to **/tmp/osxfuse/distribution/Distribution.pkg**
T:distribution       | Completed action build
 
 
5. Move resulting Distribution.pkg to MacOS 10.13
   cd /tmp/osxfuse/distribution/
   open .
   Drag and Drop Distribution.pkg to Google Driver
  
----------------------
Test with **MacOS 10.13** (MacBook Pro 13 Inch Retina Mid 2014) 
1. Disable System Integrity Protection
2. Install Distribution.pkg
    Copy Distribution.pkg from Google Driver
    Click Distribution.pkg

**Comment by DiegoGiovany** [comment]
@akio-ito or @bfleischer, can you send-me the compiled version? I don't have a 10.12 to try now....

diego.giovany@gmail.com

Thanks

**Comment by DiegoGiovany** [comment]
@akio-ito, Thank-you very much for the file, I wish to report it's full working !!!!

Thanks everyone

**Comment by dany20mh** [comment]
@akio-ito @DiegoGiovany 
Do you mind share the file too ?

**Comment by jq1106** [comment]
Just compiled and tested. Works for me. Here’s a link: https://arxius.io/f/04f1e7a3

**Comment by dany20mh** [comment]
@jq1106 
With that, did you disable System Integrity Protection or you just use it as it is ?

**Comment by jq1106** [comment]
Yeah I have SIP disabled.

**Comment by bfleischer** [comment]
The official 3.6.0 developer preview with experimental support for macOS 10.13 can be downloaded from https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.6.0

**Comment by peteeaston** [comment]
3.6.0 still doesn't seem to work rigth: 
error:  mount_strongfuse: the STRONGFUSE file system is not available

**Comment by bfleischer** [comment]
@peteeaston STRONGFUSE is an unofficial fork of FUSE for macOS. Unless you can reproduce the issue with the official FUSE for macOS 3.6.0 release you need to file a bug with the ExpanDrive team.

I'd like to add that ExpanDrive does not sponsor or contribute to the FUSE for macOS project, even though FUSE is a core component of the ExpanDrive software.

**Comment by yan12125** [comment]
Got a similar issue (@rpath/libclang.dylib missing). My workaround is:

```
cd /Applications/Xcode.app/Contents/Developer/Toolchains/
sudo ln -s XcodeDefault.xctoolchain OSX10.13.xctoolchain
```

Technical details:
```otool -l /System/Library/BridgeSupport/ruby-2.3/bridgesupportparser.bundle``` says RPATH is /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.13.xctoolchain/usr/lib, while there's only /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain. Sounds like an Xcode bug.

Environment:
Xcode 9.2 (9C40b)
macOS 10.13.2

**Comment by mcmara** [comment]
Got a similar issue as well (.dylib missing). The previous workaround of user yan12125 worked perfectly for me (I have the same environment), and I was able to build osxfuse via macports. Thank you.

**Comment by ruclsq** [comment]
and now I have the same problem to set up sshfs on macOS 10.13.2,
Error: Failed to build osxfuse: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port sshfs failed

so how can I solve the problem?

**Comment by daslicht** [comment]
is there meanwhile a solution ?

**Comment by yan12125** [comment]
I submitted a bug report to Apple. A copy of that bug can be found at https://openradar.appspot.com/40649128. By the way, rumors have that the priority of a bug gets increased if more people report the same bug.

@daslicht, @ruclsq : You may want to create a symlink as described in https://github.com/osxfuse/osxfuse/issues/380#issuecomment-354148424

**Comment by kszys** [comment]
The workaround from yan12125 works like a charm!
