### ISSUE TITLE
Lacie Private Public stopped working

### ISSUE THREAD

**Issue by WayneSch** [osxfuse/osxfuse#382]
I have been using the Lacie Private-Public app for encrypting certain files. It has worked fine until this morning, when it tells me OSXFUSE with MacFuse Compatibility layer is required for Lacie Privage-Public. It asks me to install, but when I click on install, it says "Error while installing OSXFuse. Please try again later." I found the OxFuse website and downloaded the Mac installer, but I get the same problem. I tried restarting the computer, but still it doesn't work. I tried uninstalling it from my Preferences panel, then reinstalling from the download, but I get the same messages. An additional note: I tried the HD on my laptop and it still works on it. Something changed on my PowerMac.

**Comment by bfleischer** [comment]
Please report this issue to LaCie. This is most likely something LaCie needs to look into.

**Comment by WayneSch** [comment]
I shall, but since you are provider of the Fuse I thought you could explain why it stopped working on my PowerMac but continues to work on my Macbook.

Wayne Schotten
felixnwill@me.com <mailto:felixnwill@me.com>
(415)846-8632




- Brazilian carving, courtesy of Doug Zamora

**Comment by bfleischer** [comment]
All I can tell you is that FUSE works fine on my G4 Mac mini. However, I don't have access to a G5 PowerMac to test with. 

I don't know why Private-Public stopped working on your PowerMac. It might not be compatible with the latest version of FUSE. It could have something to do with the CPU architecture. Your MacBook uses an Intel CPU, your PowerMac an PowerPC CPU. I can only speculate.

Have you tired using any other FUSE file systems than Private-Public on your PowerMac?

**Comment by WayneSch** [comment]
I contacted Lacie (Seagate) and they could only refer me back to you. 

Nnothing happened between the last time I accessed it successfully and the next morning when I could not, except the computer normally going to sleep and reawakening.

I have tried downloading and reinstalling Fuse but got the same message while trying to open Private-Public.
I completely removed it from the Preference Pane, and downloaded and reinstalled same message.
I have tried restarting the Power Mac after re-installing. 
I have tried uninstalling Fuse, restarted the PowerMac, reinstalled Fuse and restarted but I keep getting the same series of messages
The message says I need to install Fuse with layer compatibility, so I’ve been careful to check that on the installation package.
If I try to install from within the Private-Pubic software I keep getting an error message that suggests I try later.
Why would trying later make a difference, anyway? I have very high speed internet connection, fiber optics into my building. 

Both the d2 and Rugged work with my laptop but neither works with the Powermac.
The Powermac uses a 3.5Ghz 6 core Intel Xeon E5 processor and is running OXS El Capitan v 10.11.8
The MacBook Pro Retina uses a 2.5GHz Intel Core i5

I asked this of Lacie(Seagate) but no answer so far. "My question then becomes who understands the relationship between your harddrive operating system and the software you provide with it? Why would you require a plug in on your  Public Private without knowing the connection to Fuse?” To that I would ask how do I connect the software that needs to use Fuse with the installed Fuse and why does installing it tell me it failed and try later?

Someone has to know the answers. 

Wayne Schotten
felixnwill@me.com <mailto:felixnwill@me.com>
(415)846-8632




- Brazilian carving, courtesy of Doug Zamora

**Comment by WayneSch** [comment]
In trying to figure out what is going on, I looked at the Fuse on the laptop which works and see it is version 2.6.2, while on the non functioning Powermac it is 3.5.8. I wonder if the Fuse version got automatically updated thus creating the problem for me.   I downloaded an installer for 2.6.2 and it said it not compatible with this version of my operating system which is 10.11.6. My laptop which has 2.6.2 is OS X 10.12.4.
I am betting that if I can get version 2.6. 2 installed on the Powermac the problem will clear up. Is there a 2.6. 2 compatible with 10.11.6?

Wayne Schotten
felixnwill@me.com <mailto:felixnwill@me.com>
(415)846-8632




- Brazilian carving, courtesy of Doug Zamora

**Comment by bfleischer** [comment]
> Both the d2 and Rugged work with my laptop but neither works with the Powermac.
The Powermac uses a 3.5Ghz 6 core Intel Xeon E5 processor and is running OXS El Capitan v 10.11.8
The MacBook Pro Retina uses a 2.5GHz Intel Core i5

What you are describing is not a Power Mac. Power Macs don't come with Intel CPUs. I believe you have a Mac Pro. This makes a big difference in diagnosing the issue. It means we can rule out the CPU architecture.

With that out of the way let's get back to the real issue.

Version 2.6.2 of the FUSE software you are using on your MacBook Pro is over three years old and very much outdated. In fact the latest version of macOS supported by it is 10.9. Using version 2.6.2 on macOS 10.10 and later can cause serious issues. It is best to keep your FUSE installation up to date.

The latest version of LaCie's Private-Public software ships with FUSE for macOS 3.5.3 and should be compatible with FUSE for macOS 3.5.8. It looks like your version of Private-Public is very much outdated, too.

I recommend you update Private-Public and FUSE to the latest versions. This should resolve the compatibility issue. LaCie should have been able to figure this out.

I'd like to add that LaCie does not sponsor or contribute to the FUSE for macOS project, even though FUSE is a core component of the Private-Public software. I'm not getting payed by them. Referring support cases here is neither fair to LaCie's customers nor me. I'm sorry you got caught in the middle of this and I hope you can understand my situation.

**Comment by WayneSch** [comment]
You are right, my bad. 
I had a Power Mac before the Mac Pro and by habit still call it a Power Mac.

Jumping to the end of your memo, please accept my gratitude for helping me solve this. I’ve been in business myself, and the issue of divided responsibly can often lead to frustration on the part of a customer caught between two entities. Like you, I usually sucked it up, and helped the customer anyway. Thank you.

Once i saw the difference in version numbers, I became alarmed that updating my laptop to 3.5.8 would cause the same problem as on my Mac Pro. That is why I was seeking to replace the Fuse on my Mac Pro with the older version since it was still working properly on the laptop.  To help you understand my nervousness, I have been avoiding updating the Mac Pro to the newer operating system since I got snared in an update to Final Cut Pro, that made my 700 gigabyte video project incompatible with the the new software and I could not convert it properly. I reinstalled the older version of FCP and hoping soon to put the final touches on the project, so I can freely update everything. 

I will update as you say, but I will move cautiously as I am concerned that updating the Private-Public may not be compatible with the encrypted files. I’ll have to test a copy on  separate harddrive. 

If you’re interested, I’ll send you a report once I try it. 

Best regards.


Wayne Schotten
felixnwill@me.com <mailto:felixnwill@me.com>
(415)846-8632




- Brazilian carving, courtesy of Doug Zamora

**Comment by bfleischer** [comment]
> If you’re interested, I’ll send you a report once I try it.

This would be great, especially if someone else in running into the same issue and finds this ticket.

**Comment by WayneSch** [comment]
Good news, I downloaded the new version of Lacie Public-Private, installed the new Fuse and it worked. I wasn’t sure how that might affect the access to the files, so I copied the unencrypted files from my laptop into new encrypted folders as a safe procedure. Crisis over. :-)


Wayne Schotten
felixnwill@me.com <mailto:felixnwill@me.com>
(415)846-8632




- Brazilian carving, courtesy of Doug Zamora
