### ISSUE TITLE
Mounted SSHFS volume empty in Finder on macOS 10.13

### ISSUE THREAD

**Issue by raymondljones** [osxfuse/osxfuse#384]
I have downloaded the Beta version, and it does appear to mount the volume.  However, when I try to browse the volume, it is just completely empty.

**Comment by raymondljones** [comment]
On second glance ... I can use terminal to cd there.  In which case, the volume is not empty.  But only if I do a 'ls -la' on the directory.  Is it maybe something with the defer-permissions option?

**Comment by bfleischer** [comment]
Let's start with the following questions.

* Which version of FUSE are you using?
* Which version of macOS are you using?
* Which FUSE file system are you using?

**Comment by raymondljones** [comment]
Using the new MacOS Beta 10.13
Using Fuse Beta 3.6
SSHFS
The same commands I used before to mount the SSHFS Volumes still seem to mount them, but everything is hidden in the Finder.

**Comment by bfleischer** [comment]
Which version of SSHFS are you using and how did you install it (Homebrew, MacPorts, FUSE website, ...)?

**Comment by raymondljones** [comment]
homebrew sshfs 2.9

**Comment by bfleischer** [comment]
Do you still have access to Mac running an earlier version macOS, e.g. 10.12? It would be interesting to see if FUSE for macOS 3.6.0 with SSHFS 2.9 behaves differently when connecting to the same server on macOS 10.12.

**Comment by raymondljones** [comment]
I have another machine at home I could do that with.  Is there a different version of sshfs I should try on my current mac?

**Comment by bfleischer** [comment]
> Is there a different version of sshfs I should try on my current mac?

No, Homebrew's 2.9 should be fine. I just wanted to make sure you are not using an outdated version.

I tried to reproduce the issue on macOS 10.13 with SSHFS 2.9 and FUSE for macOS 3.6.0 but it worked fine for me. Finder shows all files on the server. Have you tried to reproduce the issue on 10.12?

**Comment by raymondljones** [comment]
Nope, not yet.  What -o flags are you throwing when you connect?  Can you show me an example of the command you use to mount the volume?

**Comment by bfleischer** [comment]
I'm not using any mount options. The server is a Mac running 10.12.

    sshfs user@172.16.115.1:/path/to/data /Volumes/sshfs

**Comment by bfleischer** [comment]
I just checked with `-o defer_permissions`, it works for me, too. Can you post the exact mount-time options you are using?

**Comment by raymondljones** [comment]
Sure, give me a few minutes.  I am just getting to work.  I appreciate the help.

**Comment by raymondljones** [comment]
sshfs  -o kill_on_unmount -o reconnect -o defer_permissions -o direct_io user@server.com:/var/www ~/Desktop/raylj

Obviously I changed the user and name of the server
These flags used to work, but now result in all the files and folders being hidden.

**Comment by raymondljones** [comment]
I just don't understand why everything is hidden in the Finder, but if I cd to the volume in terminal, everything is there.

**Comment by raymondljones** [comment]
Hmmmm... very odd.  Only adding the 'local' option seems to work just fine.  Other than the fact that they appear on my desktop as a local drive, it does the trick.  Also, combining my options like this:
-o local,kill_on_unmount,reconnect,defer_permissions,direct_io

The thing is ... ever since macfusion stopped being worked on (and also stopped working on the recent OS's), I wrote my own MacOS application that allows me to store ssh configuration for all the many servers I manage.  I open the app, choose which server to mount, and then I can browse the file system right on my mac.  I suppose it doesn't matter if the volume shows up with a "local" drive icon.

**Comment by bfleischer** [comment]
> I just don't understand why everything is hidden in the Finder, but if I cd to the volume in terminal, everything is there.

For some tasks Finder uses helper processes running as root. By default FUSE blocks access to mounted volumes by anyone but the user who mounted the volume. FUSE contains exception for all know cases where Finder uses such helper processes but it might be possible 10.13 requires a new exception.

Could you please mount the volume with `-o allow_other` (and without the `-o local`) and check if Finder still shows an empty directory.

**Comment by raymondljones** [comment]
allow_other results in the same thing.  the volume mounts but everything inside is hidden.
I have tried every combination of options, and in every combination ... only adding -o local works.

**Comment by bfleischer** [comment]
For some users mount points outside of `/Volumes` have caused issues in the past. `~/Desktop/test`  works for me, though.

It's possible that the issue is caused by macOS 10.13 itself, after all its still an early beta. Without being able to reproduce the issue locally there is not much I can do.

**Comment by raymondljones** [comment]
All good, I will wait and see once 10.13 is out of beta

**Comment by ashcass** [comment]
I'm having the same issue with mac OS 10.13.1:
sshfs me@ip:/path /Users/me/test -o local
works, but without -o local I can only see the mounted disk in terminal (not Finder)

**Comment by profrink** [comment]
I had the same problem but for me helped only following option:
sshs user@ip:/path mountpoint -oauto_cache,reconnect,defer_permissions,noappledouble,negative_vncache,volname=

The remote folder is shown as volume with my login name. If I use a volname=test I got a empty finder folder.

**Comment by wolfposd** [comment]
This seems to be unresolved,

Whenever Im mounting a network drive with sshfs some of the files/folders are not visible from finder, but they do show up in terminal

OSX: 10.14.4
SSHFS version 2.10
OSXFUSE 3.8.3
FUSE library version: 2.9.7

Im mounting with no special options:
`sshfs username@networkdrive:/path/ ~/mnt/path`

in Finder some folders appear empty, but when I `cd` there and do `ls -l` the files do show up

**Comment by dmitryd** [comment]
`-o defer_permissions` always helps me.
