### ISSUE TITLE
Unmount does not close device properly

### ISSUE THREAD

**Issue by pollylm** [osxfuse/osxfuse#385]
Unmounting does not appear to close the osxfuse device properly. If you use a threaded application to mount volumes, you can only mount 64 volumes - even unmounting some does not allow you to mount more. All following attempts fail with error '_mount_osxfuse: failed to open device_'
Closing the process that did the mounts does appear to finish the cleanup, as the next try will be able to mount again.

It appears to be linked to the 'OSXFUSE_NDEVICES' as osxfuse 3.0.3 will fail at 24 mounts instead (osxfuse 2.7.5 does not fail).
I have been running my tests with osxfuse 3.5.8

I have edited the loopback example filesystem from support to use threads. If you manually unmount some volumes as it is mounting more, you can see that it will still be unable to mount more than 64 volumes.
Apologies if it is not particularly well written, C is not my normal language.
[loopback.txt](https://github.com/osxfuse/osxfuse/files/1088689/loopback.txt)

**Comment by bfleischer** [comment]
Thanks for the bug report. The issue will be fixed in version 3.6.1.
