### ISSUE TITLE
Photos.app Compatibility Issues

### ISSUE THREAD

**Issue by songgao** [osxfuse/osxfuse#387]
Hi Ben!

We noticed Photos.app doesn't like libraries in osxfuse mounts. If you put a Photos.app library in an osxfuse mount and try to open it, Photos.app shows a (useless) error message:

> The library could not be opened.
> Photos has attempted to repair the library "Photos Library", but is unable to open it.

It's easy to reproduce with `osxfuse/filesystems/filesystems-c/loopback`, by moving an empty Photos.app library into the loopback mount and open it.

Any ideas what could cause this?

If it helps, we have experimented with some other filesystems, and found that Photos.app will happily open libraries in FAT filesystems, but not NTFS. It's also fine if the library is in a sparse bundle image which itself is in a osxfuse mount.

My current theory is Photos.app has a whitelist of filesystems that it wants to support, but have no way to know for sure since there doesn't seem to be a way to fake an existing filesystem through osxfuse (the `fstypename` mount option doesn't remove the `fusefs_` prefix). I figured you might have a way to test it with some kernel space tricks.

cc @strib @jzila

**Comment by bfleischer** [comment]
Hi Song,

I've created a FUSE test build that does not prefix `fstypename`. You are right, Photos.app seems to have a whitelist of supported file system types. I've mounted a loopback volume with `fstypename=hfs` and Photos.app opens the library without complaining or any obvious issues. `fstypename=apfs` works, too.

I don't think there is much we can do about this from the FUSE end, except pretending to be an HFS or APFS volume, of course. But this might cause issues down the road.

Photos.app only supporting Apple file systems seems to be a know issue. I've stumbled upon several reports of people trying to store their library on a NAS volume (and failing to do so). The only workaround seems to be wrapping the library in a HFS formatted sparse bundle.

**Comment by songgao** [comment]
Hi Ben,

Thanks so much for looking into it with a test build and confirming the issue! I was about to draw the same conclusion, but couldn't completely convince myself without asking you :-)

FWIW, regarding to NAS volume, it seems to be happy with a Samba mount. So NAS might not be a good argument to convince Apple to do something about this.

I'm gonna close this for now.

**Comment by songgao** [comment]
(just realized I mis-typed NFS into NTFS in the original issue description, and fixed it. We tried NFS and found it didn't work; we did not try NTFS)
