### ISSUE TITLE
PreferencePane icon is fuzzy

### ISSUE THREAD

**Issue by clavichord93** [osxfuse/osxfuse#388]
In OS X Fuse PreferencePane, Fuse icon is fuzzy. It is not a big problem but a clearer makes better. Would you fix this?

![](https://ws3.sinaimg.cn/large/006tNbRwly1fh9a6kl05cj317c0i2whf.jpg)

**Comment by bfleischer** [comment]
Thanks for the bug report. The issue will be fixed in the next release, 3.6.1

**Comment by clavichord93** [comment]
The icon is still fuzzy in 3.6.3.

**Comment by bfleischer** [comment]
Did you try quitting and restarting System Preferences?

**Comment by clavichord93** [comment]
After restarting Syetem Preferences, the icon is wonderful now. Thanks for fixing it!
