### ISSUE TITLE
Slow transferspeed with sshfs + osxfuse version > 2.8.3

### ISSUE THREAD

**Issue by ibaun** [osxfuse/osxfuse#389]
Mounting a network disk with sshfs on macosx seems to give me very slow transfer speeds. 

Test setup:
- Ubuntu server 16.04 on remote end
- mac osx 10.11.6 on local end
- sshfs remote@ip:. ~/dir
- rsync --progress ~/dir/somefile ~/

With a direct scp remote@ip:dir/somefile ~/ I get about 110 MB/s transfer speed. 
Using sshfs over osxfuse, the results are:
rsync from sshfs 2.9.0 + osxfuse 2.8.1: ± 55 MB/s
rsync from sshfs 2.9.0 + osxfuse 2.8.2 & 2.8.3: ± 50 MB/s
rsync from sshfs 2.9.0 + osxfuse >= 3.0.4: ± 10 MB/s

This has been discussed also at https://github.com/libfuse/sshfs/issues/11, with the latest results pointing more towards a problem with osxfuse than sshfs.

**Comment by bfleischer** [comment]
The slow transfer speeds are a result of an incompatibility between sshfs and FUSE for macOS 3.x. sshfs returns "wrong" values in `sshfs_getattr()` and `sshfs_fgetattr()`. 

The `st_blksize` value of `struct stat` represents the optimal block size for file I/O operations. FUSE for macOS will use this value when performing read or write operations on the file. The smaller `st_blksize` is the more context switches are required to complete the operation.

Setting `st_blksize` to 0 results in FUSE for macOS falling back to the global I/O size, that can be specified through the `-o iosize=...` mount-time option.
