### ISSUE TITLE
Incompatibility with macOS High Sierra of FUSE 3.6.1 via Transmit

### ISSUE THREAD

**Issue by IsaiahvH** [osxfuse/osxfuse#391]
Hi,

I'm using the application Transmit for FTP control, which in turn uses FUSE.
I recently upgraded to macOS High Sierra (10.13) beta (17A291m).

When I attempt to mount a disk via Transmit, I receive this error;
![screen shot 2017-07-09 at 19 51 52](https://user-images.githubusercontent.com/1858814/27996353-7c33d07e-64e0-11e7-8367-694b06689281.png)
followed by
![screen shot 2017-07-09 at 19 56 42](https://user-images.githubusercontent.com/1858814/27996364-c294dde2-64e0-11e7-9ca8-652f4e507722.png)

I updated my version of FUSE to 3.6.1 which I had hoped to be compatible with macOS High Sierra.
However, this same error remains.

Is this something due to FUSE or should I rather contact the developers from Transmit about this?
I hope this can be fixed;

Kind regards,

Isaiah van Hunen

**Comment by bfleischer** [comment]
Hi Isaiah,

Transmit Disk is based on a custom version of FUSE that has been modified by Panic (the developers of Transmit) to fit their needs. As far as I know Panic has not yet released a version of Transmit Disk that is compatible with High Sierra. You will need to contact Panic about that.
