### ISSUE TITLE
drive content doesn't refresh

### ISSUE THREAD

**Issue by leochou0729** [osxfuse/osxfuse#392]
Hello, 
I'm using encfs on macOS 10.12 with Dropbox. If I upload a file into the encrypted folder from another computer, the dropbox folder syncs immediately, but the encfs drive doesn't refresh its content automatically  in Finder. I try to pass "-o attr_timeout=0 -o entry_timeout=0" to OSXFUSE, but it doesn't work. passfs also has the same problem.  If I mount it normally as network drive, I can close the Finder window and open it again to show its content. If I mount it as local drive with "-o local" option, I have to remount to show its content. Using ls command in terminal can always show the correct content in the drive. Thanks!

**Comment by bfleischer** [comment]
The `local` option implies that the file system will not change remotely. But that's exactly what happens here, meaning `local` is the wrong option for what you are trying to do.

Finder can only update its windows if it is properly notified that the file system changed remotely. If Finder is not notified it assumes nothing has changed and does not trigger an update. Letting Finder know that the file system content was altered is the job of the file system, i.e. EncFS and passfs. 

Please report the issue to EncFS and passfs.

**Comment by benrubson** [comment]
@bfleischer, and how should EncFS (or others) notify Finder ?
Anything special to do ?
Thx 👍

**Comment by rfjakob** [comment]
Seems to be answered in https://github.com/osxfuse/osxfuse/issues/264, quoting:

> For osxfuse 2.x the (non portable) libosxfuse function fuse_purge_np() can be used to purge the cached file contents for a specific file. This is useful if the file has been changed remotely.
> 
> For osxfuse 3.x there are the standard functions fuse_lowlevel_notify_inval_inode() and fuse_lowlevel_notify_inval_entry().
> 
> fuse_lowlevel_notify_inval_inode () is the new fuse_purge_np()
> fuse_lowlevel_notify_inval_entry() should be what you are looking for.
> You might still need to call -[NSWorkspace noteFileSystemChanged:] to get Finder to refresh the currently open window.

**Comment by leochou0729** [comment]
Has EncFS already used these new functions to notify Finder to refresh? Thanks!

**Comment by bfleischer** [comment]
> Has EncFS already used these new functions to notify Finder to refresh? Thanks!

The question has been answered here: https://github.com/vgough/encfs/issues/250
