### ISSUE TITLE
Cannot clone the whole project - modules are not checkout.

### ISSUE THREAD

**Issue by iradization** [osxfuse/osxfuse#393]
Hi, 

I wanted to checkout the project as a whole (including all related modules). 

It appears that the command which appear on the readme file is wrong. 

The prefix should be `https://` rather then `git://` in the following command : 
git clone --recursive -b support/osxfuse-3 git://github.com/osxfuse/osxfuse.git osxfuse

Am I missing anything ? 
Irad

**Comment by bfleischer** [comment]
`git clone --recursive -b support/osxfuse-3 git://github.com/osxfuse/osxfuse.git osxfuse`and
`git clone --recursive -b support/osxfuse-3  https://github.com/osxfuse/osxfuse.git osxfuse` work just fine for me.

Which version of git are you using? Can you post the exact output of the first git command (with the `git://...` url)?

**Comment by iradization** [comment]
I'm using git version 2.13.1, and this is what I get :

`
 clone --recursive -b support/osxfuse-3 git://github.com/osxfuse/osxfuse.git 
Cloning into 'osxfuse'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out
github.com[1: 192.30.253.112]: errno=Operation timed out
`

**Comment by bfleischer** [comment]
This looks more like a network or firewall issue. Could it be that SSH connections (port 22) are blocked in your network? We can rule out Git 2.13.1 because I'm using the same version.

**Comment by iradization** [comment]
Yes, you're right. it was indeed a firewall issue. 
the port for git over ssh was closed in my firewall.

thanks a lot !
