### ISSUE TITLE
Does this work with High Sierra?

### ISSUE THREAD

**Issue by djkcel** [osxfuse/osxfuse#395]
Running 10.13 High Sierra.  When trying to mount, I get:

**Installed version of macOS unsupported**
The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS.

But when trying to upgrade the package it says:
Error: sshfs 2.9 already installed

**Comment by djkcel** [comment]
Running 10.13 High Sierra.  When trying to mount, I get:

**Installed version of macOS unsupported**
The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS.

**Comment by bfleischer** [comment]
Which version of FUSE are you using?

**Comment by djkcel** [comment]
D'oh, my bad.  I didn't realize that it was a cask, not a brew, so `brew upgrade osxfuse` wasn't working.  I ran
`brew cask reinstall osxfuse  `
and it worked after that.

Thanks
