### ISSUE TITLE
Shell `>>` operator not appending in an osxfuse mount

### ISSUE THREAD

**Issue by damonearp** [osxfuse/osxfuse#398]
Running osxfuse 3.6.3.

Ran my program in a debugger and our [struct fuse_operations::write](https://libfuse.github.io/doxygen/structfuse__operations.html#a1fdc611027324dd68a550f9662db1fac) function is being called with offset 0. Seems like fuse is ignoring the O_APPEND flag. 

Found this https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220185 while investigating the issue.

Behavior witnessed
```
$ echo hello > osxfusemount/file00
$ cat osxfusemount/file00
hello
$ echo hello hello >> osxfusemount/file00
$ cat osxfusemount/file00
hello hello
$
```

Expected Output
```
$ echo hello > osxfusemount/file00
$ cat osxfusemount/file00
hello
$ echo hello hello >> osxfusemount/file00
$ cat osxfusemount/file00
hello
hello hello
$
```

**Comment by bfleischer** [comment]
Which file system are you using? Appending files works fine with the loopback reference file system.

**Comment by damonearp** [comment]
This is a custom filesystem that isn't open sourced yet. I went back and tried running it through the debugger again and found that our stat wasn't updating st_size correctly, this seems to be part of the reason the offset parameter is incorrect. Oddly this doesn't happen on linux with libfuse. Feel free to close this, OS X support is low priority for us and I've been tied down with other issues. Sorry for the delayed response.
