### ISSUE TITLE
Compiling procfs today?

### ISSUE THREAD

**Issue by ylluminate** [osxfuse/osxfuse#399]
What are the steps to compile and install `procfs` today for macOS Sierra?

**Comment by bfleischer** [comment]
To build procfs you need to run `make` in Terminal. But I doubt it will work on Sierra. The procfs source code has not been touched in years. If I remember correctly the last supported version of macOS is 10.6.

**Comment by ylluminate** [comment]
See: https://github.com/alexchandel/procfs/issues/6
