### ISSUE TITLE
Developing a FS with Ruby: No FUSE install available

### ISSUE THREAD

**Issue by ylluminate** [osxfuse/osxfuse#400]
I'm attempting to use [`rfusefs`](https://github.com/lwoggardner/rfusefs) to develop a filesystem. First, I'm just starting off testing it via a tutorial I found [here](https://www.learnwithdaniel.com/2017/04/file-systems-ruby-fuse/), but when I simply `gem install rfusefs` I get this:

```
Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/username/.rvm/rubies/ruby-2.4.1/bin/$(RUBY_BASE_NAME)
	--with-fuselib
	--without-fuselib
No FUSE install available

ld: library not found for -lfuse
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Obviously I don't have the libraries in a location where I can find them when compiling things.  How's this handled on `osxfuse` since we're not installing this via Homebrew and letting it handle dep locations?

**Comment by bfleischer** [comment]
> ld: library not found for -lfuse

For historic reasons the FUSE library on macOS is named libosxfuse.dylib, not libfuse.dylib. I haven't used rfusefs before so I don't know if it is compatible with macOS. You should check with the rfusefs developers.

In general when building console applications linking against FUSE it is a good idea to install pkg-config first. pkg-config is used by many build systems to look up external libraries.
