### ISSUE TITLE
Packaging for file system handlers?

### ISSUE THREAD

**Issue by ajmas** [osxfuse/osxfuse#402]
[osxfuse.py.txt](https://github.com/osxfuse/osxfuse/files/1195297/osxfuse.py.txt)

Would the be any value creating a packaging for filesystems designed to be used with OS Fuse and then creating a UI that can leverage any of them. The draft idea would be as follows:
```
   /Library/
      Fuse Plug-Ins/
          sshfs.fusefs
```

A fusefs package would contain:
   
-  plist describing the file system
   - Name
   - Description
   - FS identifier, so it can be used when saving mount paths. Example: ssh, ext4, hfs
   - Fields to fill in. If non are specified then it would be assumed a default behaviour for mount point and path
- The library/command that will be called, or optionally a symlink, to allow use with tools preferring other install locations or legacy reason
- Man page

An interim solution could follow something closer to what git does, whereby it will see if there is a script that starts with 'git-' in the PATH environment. In the case of osfuse you would have fuse-sshfs,  fuse-ext4, etc. Ideally the commands would also provide a way of finding the fs identifier, such as via '--id'?

So the following command would look for fuse-ext4
```
osfuse mount ext4 <source path/url> <mount point> <options>
```
and the following list the supported file systems:
```
osfuse list
```
Just curious as to whether this, or something like it, could be of interest. The main motivation is to get things standardised enough that they could be used by a general GUI or something like the Finder's 'connect to server' option. Also, by having the 'osxfuse' command be the main entry point, the logic for the creating and deleting the mount point could be reused across file systems.

I have attached a Python command that illustrates the concept.

[osxfuse.py.txt](https://github.com/osxfuse/osxfuse/files/1195299/osxfuse.py.txt)

**Comment by bfleischer** [comment]
This ticket has been inactive for years, so I'm closing it. I definitely see value in maintaining a list of compatible file systems and a simple way to build or install them, similar to a package manager. However, I don't have time to develop or maintain something like this.
