### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pari-pacc** [osxfuse/osxfuse#405]
NWHM0091:~ root# git clone https://github.com/osxfuse/osxfuse.git
Cloning into 'osxfuse'...
remote: Counting objects: 2335, done.
remote: Total 2335 (delta 0), reused 0 (delta 0), pack-reused 2335
Receiving objects: 100% (2335/2335), 1.54 MiB | 828.00 KiB/s, done.
Resolving deltas: 100% (1338/1338), done.
NWHM0091:~ root# cd osxfuse/
NWHM0091:osxfuse root# ls -la
total 120
drwxr-xr-x  15 root  wheel    510 Aug 13 14:42 .
drwxr-x---  22 root  wheel    748 Aug 13 14:42 ..
drwxr-xr-x  13 root  wheel    442 Aug 13 14:42 .git
-rw-r--r--   1 root  wheel    393 Aug 13 14:42 .gitignore
-rw-r--r--   1 root  wheel    319 Aug 13 14:42 .gitmodules
-rw-r--r--   1 root  wheel  12561 Aug 13 14:42 LICENSE.txt
-rw-r--r--   1 root  wheel   2440 Aug 13 14:42 README.md
drwxr-xr-x   6 root  wheel    204 Aug 13 14:42 build.d
-rwxr-xr-x   1 root  wheel  30087 Aug 13 14:42 build.sh
drwxr-xr-x   7 root  wheel    238 Aug 13 14:42 common
drwxr-xr-x   2 root  wheel     68 Aug 13 14:42 framework
drwxr-xr-x   2 root  wheel     68 Aug 13 14:42 fuse
drwxr-xr-x   2 root  wheel     68 Aug 13 14:42 kext
drwxr-xr-x   2 root  wheel     68 Aug 13 14:42 prefpane
drwxr-xr-x   2 root  wheel     68 Aug 13 14:42 support
NWHM0091:osxfuse root# sh build.sh 
./build.d/lib/xcode.sh: line 122: syntax error near unexpected token `<'
./build.d/lib/xcode.sh: line 122: `    done < <(mdfind -onlyin "/Applications" 'kMDItemCFBundleIdentifier == "com.apple.dt.Xcode"')'
NWHM0091:osxfuse root#

**Comment by bfleischer** [comment]
Please read the README.md first before opening issues. The readme contains build instructions you don't seem to have followed. First of all you need to recursively clone the repository, install external dependencies and then run the build script with the correct parameters.
