### ISSUE TITLE
fuse_unmount hangs indefinitely

### ISSUE THREAD

**Issue by martijnotto** [osxfuse/osxfuse#406]
I am developing a filesystem for Linux and osx (and eventually Windows too). I have initially written it on Linux (as that is what I use myself and know quite well) and am now in the process of porting it to osx.

The filesystem is written using the lowlevel API, using a libuv event loop. I have a signal handler to trap SIGINT and SIGTERM. When received, I call the following functions:

```
fuse_session_remove_chan()
fuse_session_destroy()
fuse_unmount()
```

On osx this hangs in fuse_unmount, it works fine on Linux. The filesystem is not busy as far I know (though Finder keeps periodically sending some weird requests for non-existing entries like ._. and similar things). I have tried debugging what exactly happens using gdb, but all I see is a call stack with three entries, where none of them are visible (showing ?? for all three).

Any idea what the problem here is? If you need any more information please let me know (and please be specific in how to get that information - I am very unfamiliar with osx and find it a very difficult OS).

osxfuse 3.6.3
osx sierra
LLVM version 8.1.0

**Comment by martijnotto** [comment]
Interestingly, if the mount _is_ busy (e.g. there is terminal open somewhere within the mount point) the application does close down properly, but the mount point is left. If the mount point is _not_ busy, the application hangs while shutting down.

**Comment by bfleischer** [comment]
On macOS (and BSD, as far as I know) you need to call unmount before shutting down the FUSE session. Calling unmount before closing the session ensures that FUSE is able to empty all kernel-side caches.

**Comment by martijnotto** [comment]
I had the same idea and have already tried this. Unfortunately it makes no difference. fuse_unmount hangs whether or not it is executed before or after closing the session. The only time it does not hang is when it fails (because the mount is still active).

**Comment by bfleischer** [comment]
Are you sure you are still processing FUSE requests after calling `fuse_unmount ()`? You need to make sure that the channel is not closed before receiving `FUSE_DESTROY`.

I'm not sure if it helps, but if you are looking for an minimal example file system have a look at hello_ll (https://github.com/osxfuse/filesystems/blob/master/filesystems-c/hello/hello_ll.c).

**Comment by martijnotto** [comment]
I cannot process anything _after_ fuse_unmount(), because the call never completes. Because the program blocks in fuse_unmount(), none of the handlers are ever called.

**Comment by benrubson** [comment]
@bfleischer, @martijnotto, we are facing the same issue in EncFS.
We mount the Fuse FS using `fuse_main()`, and unmount using `fuse_unmount(mountpoint, nullptr)`.
It works perfectly on Linux, FreeBSD, Windows (Dokan).
But fails on Mac OS, `fuse_unmount` returns but does not unmount.
Any solution ?
Thank you very much 👍

**Comment by ghost** [comment]
I don't think you're facing the same issue that I do. For me fuse_unmount just hangs indefinitely. The only way to stop and unmount was to use hdiutil eject -force, so I wrote a quick bash script that traps signals, then sends the signal to the application in the background and then runs hdiutil. When hdiutil is run the fuse_unmount function returns.

It's a gory solution, but it works.
