### ISSUE TITLE
Fuse is not working on mac os x  10.13 Beta (17A352a)

### ISSUE THREAD

**Issue by ondrejF** [osxfuse/osxfuse#407]
Trying to use FUSE version 3.6.3 with ExpanDrive on Mac OS 10.13 Beta (17A352a), getting message FUSE  version is unsupported on this version of Mac OS..

**Comment by bfleischer** [comment]
Please report the issue to the ExpanDrive support team. ExpanDrive is based on an unofficial, modified version of FUSE that does not seem to be compatible with 10.13, yet. However, official FUSE for macOS releases starting with 3.6.0 work on macOS 10.13.

**Comment by ondrejF** [comment]
Thanks for prompt and clear answer. I will contact ExpanDrive

Regards & Thanks

Ondrej Felix
