### ISSUE TITLE
Index FUSE drive?

### ISSUE THREAD

**Issue by mickaphd** [osxfuse/osxfuse#408]
I would like to know if it's possible to index a fuse network drive with spotlight in macOS? I use pCloud (which use fuse) for example and I didn't find any way to index it and then use it with Spotlight. 
Thank you!

**Comment by bfleischer** [comment]
Sadly it is not possible to index network drives. This is a limitation of Spotlight, not FUSE. However if you mount the volume using the `local` option Spotlight can be enabled.
