### ISSUE TITLE
doesn't compile with Xcode 8.2.1 on 10.11.6

### ISSUE THREAD

**Issue by mklein-de** [osxfuse/osxfuse#411]
see https://trac.macports.org/ticket/54781

This is not specific to macports, `./build.sh -t distribution -v 5` fails the same way with commit a770e21acc1e518a18ec246be6195b58b07a92a5

**Comment by bfleischer** [comment]
Xcode 8 does not contain the OS X 10.11 SDK, so you cannot build kernel extensions for 10.11 with it. Unlike regular macOS oder iOS applications kernel extensions do not support setting a deployment target. This is not a bug.
