### ISSUE TITLE
Should the write callback function be called every 4096 bytes?

### ISSUE THREAD

**Issue by yiskwang** [osxfuse/osxfuse#412]
I just installed the latest version of OSX FUSE with max_write=33554432 
and mounted my own file system.

When I run an application using fwrite() with a large size buffer, 
.write callback function is called with 4096-byte chunks. 

I have also tried to mount with -o direct_io, but I failed to see a single callback.

Could you tell me how to solve this problem?

**Comment by bfleischer** [comment]
On macOS you need to use the mount-time option iosize instead. See https://github.com/osxfuse/osxfuse/wiki/Mount-options#iosize for details.

Please note the the global I/O size can be overridden on a file by file basis. If you return a `st_blksize` != 0, FUSE will use `st_blksize` as I/O chunk size for this particular file.
