### ISSUE TITLE
Macfuse compatibity layer for oxsfuse and mac high sierra

### ISSUE THREAD

**Issue by maclarry** [osxfuse/osxfuse#415]
Installed Fuse for macOS 3.7 on mac high sierra beta(GM).  Pop up screen shows no macfuse compatibilty layer when I try to open file.  I checked compatibility layer on install.

**Comment by bfleischer** [comment]
What exactly are you trying to do? The MacFUSE compatibility layer supports old MacFUSE file systems. You cannot open a file with the compatibility layer.

**Comment by maclarry** [comment]
Sorry for the incomplete explanation.  I  was trying to open an Veracrypt encrypted volume that I had created earlier with veracrypt.   It kept showing I needed a compatibility layer installed.  I did find a solution.  I removed fuse and reinstalled fuse again.  Then I uninstalled Veracrypt and reinstalled it.  I can now open the veracrypt volume.  All seems fine.  Thanks for the reply.
