### ISSUE TITLE
Mounted SSHFS showing zero space 

### ISSUE THREAD

**Issue by divamgupta** [osxfuse/osxfuse#417]
I use the latest osxfuse on macOS sierria. I had mounted the a SSHFS drive using:

` sshfs -o allow_other,defer_permissions  divam14038@k40: ~/k40_mount`

But df -h command shows zero space.  

`divam14038@k40:    0Bi    0Bi    0Bi   100%       0          0  100%   /Users/divamgupta/k40_mount`

The server is a centOS server with quota enabled. But I am only using 50% of the quota.

**Comment by bfleischer** [comment]
Please update to FUSE for macOS 3.7.1. This is a known bug in version 3.7.0.

**Comment by divamgupta** [comment]
Yes, it is working now.
