### ISSUE TITLE
Spotlight on 10.13

### ISSUE THREAD

**Issue by Alex-C-Eltima** [osxfuse/osxfuse#420]
Hi! Our app mounts disks with "local" and "allow_other" keys. On 10.12 the Spotlight search by name works perfectly. But on 10.13 Spotlight locates the files, but returns the attached error upon opening in Finder. 

![screen shot 2017-09-22 at 16 43 57](https://user-images.githubusercontent.com/17063982/30852122-6bcb60a6-a2b3-11e7-9b32-00f0f80c216f.png)

Is this a bug, or some misconfiguration on our side, any suggestions how to resolve?

**Comment by Alex-C-Eltima** [comment]
This behavior seems to be fixed in 3.8.0 build released on 07 May 2018

**Comment by bfleischer** [comment]
Thanks for the feedback.
