### ISSUE TITLE
sshfs on macOS High Sierra (10.13)

### ISSUE THREAD

**Issue by lonetis** [osxfuse/osxfuse#421]
Mounting a directory with sshfs in macOS High Sierra (10.13) on an APFS File System and opening that directory in Finder results in the following error: **LSOpenURLsWithRole() failed with error 5 for the file PATH TO DIR**.

However, navigating via terminal in that mounted directory still works. Just cannot open the mounted directory in Finder.

**Comment by devavret** [comment]
Can you check that the path where you're mounting has no illegal character. I had the exact same issue. In my case, I was mounting in a folder that was inside a hidden folder (/Users/deva/.sshfs/folder1) and renaming .sshfs to sshfs fixed it.

**Comment by lonetis** [comment]
Mounting a directory via sshfs on macOS High Sierra (17A405) now works without any problems. Don't really know what happened but issue seems to be fixed now. Thanks for your advise. But it now works even with illegal characters, so mounting in a .sshfs directory should work now.

**Comment by svalgaard** [comment]
I had the exact same issue and no illegal characters involved. Reboot did not help.
Reinstalling sshfs from macports made it work again.

**Comment by oprog** [comment]
I had a similar issue and fixed with running:
 _xcode-select --install_  
in terminal.
Have no idea why it fixed the issue but now fuse/sshfs works just like before the High Sierra update.

**Comment by hasibahmed** [comment]
For me, reinstalling osxfuse and sshfs didn't do it, required a reboot too.

**Comment by hasibahmed** [comment]
Hi, this is back again, reinstalling osxfuse / rebooting didn't help. Any ideas ?

**Comment by aristako** [comment]
Throwback, but one of the options specified [here](https://blog.bmonkeys.net/2013/slowdowns-using-vpn-and-mac-os-x) made the problem go away for me. Good luck!

**Comment by cameron-simpson** [comment]
I have just spent some time with this error "LSOpenURLsWithRole() failed with error 5", and have devised a workaround for my particular case. I'm working on a Python implemented filesystem via llfuse and osxfuse behind that.

I've been opening the mounted filesystem with "open /path/to/mountpoint" and getting the cited error message.

The Finder does a getxattr of "com.apple.FinderInfo"; returning an empty attribute value or raising OS error ENOATTR causes the error message. My horrible workaround for now is that _if_ the requested attribute is not present _and_ the attribute name is "com.apple.FinderInfo", return the errno ENOTSUP, indicating that extended attributes are not supported (a lie!).

That has been sufficient to get MacOS file dialogues working again for me.

**Comment by cameron-simpson** [comment]
... and now I'm back to the same error message. So this is not a fix or workaround :-(
