### ISSUE TITLE
I upgraded to macOS High Sierra now can't access VeraCrypt drives

### ISSUE THREAD

**Issue by ghost** [osxfuse/osxfuse#425]
Hi,

After upgrading to High Sierra I came to know osxfuse incomplateblitiy issue with the new apple file system with, thus can't access my drives in Vercrypt. Is there a way to go back to the old file system or a workaroundd to get access to my veracrypt drives... Highly appreciated your help.

**Comment by bfleischer** [comment]
How did you determine that FUSE is incompatible with High Sierra? FUSE supports High Sierra since version 3.6.0, which was released in June. Which version are you using?

Have you reported the issue to the VeraCrypt team?

**Comment by ghost** [comment]
Hi,

I'm on the latest version of fuse...And veracrypt says the same they support new file system of Mac... So APFS is supported by FUSE

**Comment by pmalhaire** [comment]
I have an apfs drive with macOS 10.13 and loopbackfs works.

**Comment by ghost** [comment]
![screen shot 2017-09-29 at 12 04 38](https://user-images.githubusercontent.com/32378430/31006606-67e06c4a-a50e-11e7-9a14-b112e344e999.jpg)
I get this screen can't access the drives and still... Thank you for your swift replies

**Comment by bfleischer** [comment]
@Muscati143 I ran a quick test with VeraCrypt on macOS 10.13. I was able to create and mount an exFAT formatted container file without any issues.

VeraCrypt uses FUSE to mount the decrypted volume. FUSE is not involved in the device or partition selection process. I'm pretty sure FUSE is not to blame for the empty list. The VeraCrypt team might be able to help you.

**Comment by nast90210** [comment]
I have the same problem - veracrypt don't see any partitions. It's seems to be problem with fuse. Because I can create and mount container. But when I try to mount partition with APFS veracrypt say that it's read-only. So I think fuse just can't see APFS disk.

**Comment by typcn** [comment]
![image](https://user-images.githubusercontent.com/8022103/31075141-b912ba28-a739-11e7-8e7e-778a99ef617c.png)

Same here, I can only see the DMGs.
I think this is a issue with VeraCrypt.

**Comment by stollge** [comment]
Also problems with High Sierra, upgraded latest issues of VeraCrypt and osxfuse but files missing after April 2016! Help.

**Comment by kodsama** [comment]
I confirm the bug. Just installed high sierra and the latest osxfuse (3.7.1) and veracrypt (1.21) can't see any drives anymore...

**Comment by qvantor** [comment]
After update to High Sierra I got this error, when i try to mount my disc:
![screen shot 2017-11-14 at 18 57 13](https://user-images.githubusercontent.com/9914154/32793108-b039959c-c96d-11e7-974c-31455647425d.png)
Is anyway to decrypt data from my veracrypt file?

**Comment by MilesRomney** [comment]
I had a similar problem, and upgraded to Fuse 3.7.1. which resolved it:

https://osxfuse.github.io/

**Comment by njm2112** [comment]
@qvantor: I am getting the "mount_osxfuse" error on Sierra 10.12.6 with OSXFUSE 3.7.1 installed. I don't think that particular error is directly a result of the High Sierra upgrade.

**Comment by Ahmet-Ozkaya** [comment]
I face exactly the same problem ghost faced. I updated FUSE and Veracrypt. But mounted volume shows empty directory.

**Comment by bakku** [comment]
I got the same error as @qvantor. On Sierra I did not get it, but after updating it occurs.

**Comment by bakku** [comment]
Updating osxfuse AND rebooting fixed it for me 👍

**Comment by kotov01** [comment]
Tell me please where to click that would update FUSE)))

**Comment by bakku** [comment]
You can find some instructions here: https://github.com/osxfuse/osxfuse/wiki/FAQ#22-how-can-i-keep-fuse-for-os-x-up-to-date

**Comment by kotov01** [comment]
Thank you very much))) everything works)))

**Comment by ILC2018** [comment]
Hello everyone! I had the same problem as Ghost; I actually did not have FUSE. I downloaded it, but nothing changed. I contacted veracrypt; however in the meantime I discovered that if you select "mount all devices" instead of just "mount", and entering the password for that specific volume, I am able to access it. 

Cheers!
