### ISSUE TITLE
Sierra Secure Kext Loading pop up System Preference button doesn't work

### ISSUE THREAD

**Issue by hjmallon** [osxfuse/osxfuse#426]
The OSFUSE popup with the button that is meant to open the security preferences panel doesn't work for me. I am getting a log messages as follows. The button makes the System Preferences App in the dock bounce indefinitely.

    Oct  3 12:48:38 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.system): Could not import service from caller: caller = mount_osxfuse.546, service = com.apple.systempreferences.844, error = 134: Service cannot load in requested session

Any ideas? It is being launched from a root daemon if that matters.

**Comment by gtimmy** [comment]
But System Preferences App is still accessible if you open if by yourself? Because it looks like an issue with a System Preferences not with button.

**Comment by hjmallon** [comment]
System Preferences can be opened manually. I assumed that the problem was something to do with "Because they have no knowledge of users, daemons also have no access to the window server, and thus no ability to post a visual interface or launch a GUI application." from Apple docs. (https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/DesigningDaemons.html#//apple_ref/doc/uid/10000172i-SW4-SW5)

But I am not sure.
