### ISSUE TITLE
FUSE do not show Volume Icon

### ISSUE THREAD

**Issue by kevinlieser** [osxfuse/osxfuse#427]
Fuse 3.7.1 on macOS High Sierra do not show the volume icon on path "/.VolumeIcon.icns" of the disk. On macOS Sierra and a previous version of FUSE this works very well.

Just seeing the default "FUSE" finde Icon.

**Comment by bfleischer** [comment]
Are you using the volicon mount-time option?

**Comment by kevinlieser** [comment]
I am using sshfs to mount my SSH drive. I tried the volicon option but it seems it have no impact with SSHFS. But the description of volicon says something like "this option do the nessecary things to show up the icon -> simulating the icon to the root of the drive unter "/.VolumeIcon.icns" where the icons should be". And if the option only simulates the icon at this path where it in my case really is... why should my icon not work anymore?!

**Comment by bfleischer** [comment]
> And if the option only simulates the icon at this path where it in my case really is... why should my icon not work anymore?!

There are a number of reasons. Apple might have made some icon-related changes to Finder in High Sierra. The permissions, owner, or group of your icon file might be causing the issue. Or the icon file itself could be the problem.

Starting with version 3.6.1 high-level FUSE file systems (like SSHFS) fall back to the default FUSE volume icon if no other volume has been specified at mount-time. This means you will need to use the volicon option to make FUSE display your custom icon.

> I tried the volicon option but it seems it have no impact with SSHFS.

Finder caches volume icons. Could you try mounting the volume with the volicon option under a different mount point?

**Comment by kevinlieser** [comment]
Ok, got it working. Deleted my "real" .VolumeIcon.icns files, added the volicon option and restarted the computer. Thanks!

**Comment by tofutim** [comment]
Kevin, can you give more information on how you did your workaround. I am using qcowmount and seeing
```
Tims-Air:qemu_vms tim$ sudo qcowmount raspbian-stretch.qcow /mnt/rpi
Password:
qcowmount 20170222

volicon: missing 'iconpath' option
Unable to create fuse handle.
```
On OSX 10.13. I used `brew cask install caskroom/cask/osxfuse`

**Comment by kevinlieser** [comment]
I am using `sshfs` and providing the volicon option with `... -o volicon=/Path/to/MyIcon.icns ... `. So nothing special...
