### ISSUE TITLE
Mac 10.13 Finder hangs leading to system freeze when mounted and any file in the file system is accessed

### ISSUE THREAD

**Issue by lakshmi-subramanya** [osxfuse/osxfuse#430]
Finder hangs resulting in system freeze at times while mounting Filr application on Mac 10.13 using OSX Fuse versions 3.6.2, 3.6.3 and 3.7.1.

Hang related samples/stack traces are attached. 

This is ship stopper for us and blocking our release to support Mac OS 10.13.
Any workaround or fixes at the earliest is more appreciable.

**Comment by lakshmi-subramanya** [comment]
[Sample of FilrFS_FinderHang.txt](https://github.com/osxfuse/osxfuse/files/1371621/Sample.of.FilrFS_FinderHang.txt)
[Sample of Finder.txt](https://github.com/osxfuse/osxfuse/files/1371622/Sample.of.Finder.txt)

**Comment by bfleischer** [comment]
Please do not double post issues. Original issue: #423
