### ISSUE TITLE
osxfuse uninstalled behind my back

### ISSUE THREAD

**Issue by pollymow** [osxfuse/osxfuse#432]
Sorry for having to bother you with this – kind of – side issue:
Something is installing osxfuse behind my back on user login on my 10.9 system.
Easy – so I thought – to find out:
• check login items
• check launch control entries, deamons etc.
• do a full text search of my complete user account (+ system) to find any suspicious entries relating to osxfuse (found DiskDrill option to keep osxfuse updated, unchecked it but problem persists)
• try to find the calling process which launches uninstall_osxfuse, which leads to nothing except the root process
Mostly, the uninstall process fails and hangs, leaving osxfuse partially installed. When trying to reinstall it using the prefpane the version info says 3.5.6 but I can manage to reinstall the current version without issues.
Any ideas, how to track down the culprit? This is bothering me for some time now.

**Comment by bfleischer** [comment]
What exactly is bothering you, that FUSE is installed when you login or that FUSE is uninstalled when you login?

**Comment by pollymow** [comment]
> What exactly is bothering you, that FUSE is installed when you login or that FUSE is 
> uninstalled when you login?

It is bothering me that
(a) Some process tries to uninstall FUSE, though it is needed by at least VeraCrypt and DiskDrill, maybe others.
(b) That this uninstall – seemingly – leads to a major downgrade.
(c) That this uninstall seems to fail every time (leaving VeraCrypt complaining).
(d) That all of this is done behind my back, without my consent,
(e) by a process I am unable to identify
(f) and which I am unable to stop doing this.

**Comment by bfleischer** [comment]
Ah I see. It was not clear to me that a process is trying to uninstall FUSE in order to install an older version of the software. Some developers don't seem to understand that downgrading FUSE is a really bad idea and doing so behind the back of users is even worse. 

Have you checked your ~/Library/LaunchAgents and ~/Library/LaunchDaemons directories?

**Comment by bfleischer** [comment]
No feedback in over a month, so I'm closing the ticket.
