### ISSUE TITLE
volicon mod time updated on getattr, causing Finder readdir loop

### ISSUE THREAD

**Issue by jeremyspiegel** [osxfuse/osxfuse#434]
Since updating to osxfuse 3.7.1 from 3.6.3, I noticed that sometimes Finder gets into a state where it will issue readdirs every second. It normally performs lots of getaddrs, but this readdir behavior is new and led to some performance issues.

I found that the new vnode_notify code was being called in fuse_vnop_getattr via fuse_internal_attr_loadvap, in response to an updated mod time for `/.VolumeIcon.icns`. I'm using the volicon module, which returns the current time for the mod time of the file. From [volicon.c](https://github.com/osxfuse/fuse/blob/master/lib/modules/volicon.c#L109):
```
buf->st_atime = buf->st_ctime = buf->st_mtime = time(NULL);
```

If I remove this line, the problem goes away. Is there any need for this time to be based on the current time? If not then I would suggest removing it (I'm happy to create a pull request if you agree).

Thanks @bfleischer for all your work on this project!

**Comment by bfleischer** [comment]
Nice find. Thanks for the bug report. I'll look into it.

**Comment by bfleischer** [comment]
The above commits fix the issue. Instead of returning the current time the volicon module now returns the mount time. I think this is semantically more correct than returning Jan 1 1970.

**Comment by jeremyspiegel** [comment]
Thanks for the fix, it makes sense.

However, I think the new `vnode_notify` code is causing another similar issue. For example, suppose a new file is remotely added to an already large folder, and as part of this I am updating the modification time of the folder and performing a `stat` on the folder. This is causing the `fuse_vnop_getattr` for the folder to notice the updated modification time, go though the new `vnode_notify` code, and cause Finder and other apps like Chrome to all perform `readdir`s on the folder. Since the folder is so large, I see this causing high CPU usage in my filesystem, and in Finder/Chrome, even though there are no Finder windows open to the large folder.

This may be related to https://github.com/osxfuse/osxfuse/issues/436.
