### ISSUE TITLE
update documentation for tunables value

### ISSUE THREAD

**Issue by solj** [osxfuse/osxfuse#435]
It seems as though the name for the tunables value on OS X has changed since this was written. Here is a patch for the page with the new tunables value:

    diff --git a/Mount-options.md b/Mount-options.md
    index 3d3e744..74094a6 100644
    --- a/Mount-options.md
    +++ b/Mount-options.md
    @@ -5,10 +5,10 @@ By default, osxfuse limits volume access to the user that mounted the volume. No
     With `allow_other`, the volume will be accessible normally to all users, but usual permission checks will of course apply. Note that `allow_other` is a privileged option in that it can only be used by either the superuser or by a user belonging to the "osxfuse Admin" group. When osxfuse loads in the kernel, it sets this group's ID to be that of the admin group on Mac OS X. The superuser can view or change this ID through the `sysctl` interface (note that osxfuse allows you to set any group ID you specify, even those that do not exist):

     ```
    -$ sudo sysctl macfuse.tunables.admin_group # get
    -macfuse.tunables.admin_group: 80
    -$ sudo sysctl -w macfuse.tunables.admin_group=81 # set
    -macfuse.tunables.admin_group: 80 -> 81
    +$ sudo sysctl vfs.generic.osxfuse.tunables.admin_group # get
    +vfs.generic.osxfuse.tunables.admin_group: 80
    +$ sudo sysctl -w vfs.generic.osxfuse.tunables.admin_group=81 # set
    +vfs.generic.osxfuse.tunables.admin_group: 80 -> 81
     ```

     ### allow_recursion
    @@ -170,4 +170,4 @@ You can use the `volicon` option to specify an icon file that would be used as t

     `volname=NAME`, where `NAME` is a string.

    -You can use the `volname` option to specify a name for the osxfuse volume being mounted. This is the name that would show up on the Desktop. In the absence of this option, osxfuse will automatically generate a name that would incorporate the osxfuse device index and the user-space file system being used. For example, an SSHFS mount might have an automatically assigned name "osxfuse Volume 0 (sshfs)".
    \ No newline at end of file
    +You can use the `volname` option to specify a name for the osxfuse volume being mounted. This is the name that would show up on the Desktop. In the absence of this option, osxfuse will automatically generate a name that would incorporate the osxfuse device index and the user-space file system being used. For example, an SSHFS mount might have an automatically assigned name "osxfuse Volume 0 (sshfs)".

**Comment by bfleischer** [comment]
Thanks
