### ISSUE TITLE
Can NOT make FUSE work with High Sierra 10.13.1 Beta

### ISSUE THREAD

**Issue by jarjartee** [osxfuse/osxfuse#439]
been trying latest version of FUSE - NOT playing ball with HS Beta, did try a Trial Version of Paragon ExtFs - this works fine - NO glitches. Bear in mind I'm NOT a programmer so will NOT be able to give very detailed reports unless  guided into directories / files etc. So just to summarise - .ext3/4 NOT showing in Finder - it DOES show in DiskUtility BUT not able to mount

**Comment by lfpippa** [comment]
Same here. I tried both on 10.13.1 (17B48), the stable release, and 10.13.2 (17C60c), the beta release.

**Comment by iapYang** [comment]
Just upload to HS 10.13.1, not working.

**Comment by bfleischer** [comment]
FUSE is a building block that is used by third-party developers to build actual file systems like ext4fuse. FUSE on its own cannot read ext3 or ext4 volumes.
