### ISSUE TITLE
Xcode9 edit file  use LoopbackFS

### ISSUE THREAD

**Issue by KobeLuo** [osxfuse/osxfuse#443]
When i mount one disk use LoopbackFS, I recorded the log as follow:

- create Dir:/(A Document Being Saved By Xcode)
- create File:/(A Document Being Saved By Xcode)/A.txt,flags:2562,mode:420
- release:/(A Document Being Saved By Xcode)/A.txt,flags:2562
- move:/(A Document Being Saved By Xcode)/A.txt to dest:/A.txt
- remove Dir:/(A Document Being Saved By Xcode)
- remove File:/A~.txt

I founded i received one event about remove the path `/A~.txt`, but i didn't received any create fun about the path:`/A~.txt`

**Comment by gtimmy** [comment]
You won't get an event about create A.txt because it's how Xcode works. Create a temp file and tries to move a temp file to A.txt it's done in order to save your work and don't lose it during the saving. A.txt may be busy by another program or locked or anything else. Anyway, it's not a Xcode-unique technic, MS Office does the same thing and TextEdit and etc. So, it's not a OSXFUSE issue.

**Comment by KobeLuo** [comment]
@gtimmy  I'm sorry,I don't know how do i to receive the create event about path `/A~.txt` ?
There is does't work for my workspace if i trash one file on server before the file create, or i need do some thing to adpt it in this case.

**Comment by radj** [comment]
@KobeLuo I cannot reproduce the sequence above. I do not have a remove for a file ending with tilde. Maybe it was created by Xcode before you started monitoring logs?

Or you might want to add a log at `openFileAtPath:` because depending on the `mode` parameter, this can also create a file.

**Comment by KobeLuo** [comment]
@radj Thank you for reply and find the question exactly,  
I founded the function `openFileAtPath:`maybe will create one file.

- open file, path:/Personal Folder/FILES/A.sb-86d9b9e7-oartUn, model:0
- read file:/Personal Folder/FILES/A.sb-86d9b9e7-oartUn, range:[0-16]
- the resource key of path:/Personal Folder/FILES/A.sb-86d9b9e7-oartUn is not found!!!
- remove file,/Personal Folder/FILES/A.sb-86d9b9e7-oartUn

And share the result to you @gtimmy 

Thanks again
