### ISSUE TITLE
High Sierra - Fuse crashing

### ISSUE THREAD

**Issue by teckdan** [osxfuse/osxfuse#444]
I see this message in the logs generated by my app 

Abnormal termination of fuse thread

Version installed : 3.7.1

**Comment by radj** [comment]
@teckdan Can you attach a crash log or at least the crash stack? And what were you doing on the mounted volume that led to the crash? Can you reproduce this crash using LoopbackFS?

**Comment by twoelevenjay** [comment]
@radj I am having this issue as well and not finding any relevant crash logs. Maybe I am looking in the wrong place. Where should I look?

**Comment by teckdan** [comment]
I can see in the log of the application I use, which is FileCloud. If you can tell me where to look for Fuse's logs, I can pull the info.

17:11:24:535 [1] [default[#1]]:I: Entering Fuse thread
17:11:24:535 [1] [default[#1]]:I: umount -f /Users/Dany/FileCloud/
17:11:24:539 [1] [default[#1]]:I:  Mount options =  -odefault_permissions,-f,daemon_timeout=30,kill_on_unmount
17:11:25:202 [1] [default[#1]]:E: Abnormal termination of fuse thread
17:11:25:536 [0] []:I: Ignoring SIGINT

**Comment by twoelevenjay** [comment]
For me after upgrading to High Sierra i attempted to sshfs like I have a 100 times and it told me my version of fuse was not supported by High Sierra so i upgraded fuse, sshfs and attempted it again. Now it freezes my entire macbook pro late 2016 + touchbar, every time.

**Comment by bfleischer** [comment]
Is this still an issue with the latest version of FUSE?
