### ISSUE TITLE
Installation (3.7.1) hangs

### ISSUE THREAD

**Issue by diobosco** [osxfuse/osxfuse#445]
Hi

I couldn't finish the installation of Fuse for macOS (3.7.1). It stops shortly before the end in the step "Validating packages..". I check marked also "MacFUSE Compatibility Layer".
[Installationlog FUSEformacOS.txt](https://github.com/osxfuse/osxfuse/files/1454461/Installationlog.FUSEformacOS.txt)

Can you help me, please?

Further testing showed that FUSE for macOS could be installed when I uncheck the compatibility layer installation. Unfortunately, I need this feature.

**Comment by ColinInBelgium** [comment]
Three years later ... I have the same problem with the latest version of OSXFuse : Hangs at end of validation when I check the needed "MacFUSE Compatibility Layer".

Does anyone have a solution? Thanks.
