### ISSUE TITLE
Error 255 when attempting to mount ssh drive

### ISSUE THREAD

**Issue by AlexWang-16** [osxfuse/osxfuse#446]
Hey everyone, I'm a first time macfuse and sshfs user. I've installed Macfuse v3.7.1 as well as ssh fs.

I then performed the following steps:
1. Opened terminal and navigated to my desktop
2.  `mkdir server`
3. `sshfs admin@192.168.1.5:/ server:/`

I got the following message
`mount_osxfuse: the file system is not available (255)`

Can someone please help me out? How can I get sshfs to work? I'm on MacOS 10.13.1 right now. Thanks in advance.

**Comment by swt2c** [comment]
Try `sshfs admin@192.168.1.5:/ server` instead.

**Comment by AlexWang-16** [comment]
Just tried it and it didn't work either.

I tried the following

`sshfs root@192.168.1.5:/ server`

`sshfs root@192.168.1.5:/ /Users/Alex/Desktop/server`

I got the same error on both attempts.

**Comment by DanielFarber** [comment]
Are you simultaneously running VMWare Fusion?

**Comment by guyzmo** [comment]
Hi, I'm having the same error, when doing a command I've been running regularly for a while. I'm pretty sure it was working during december, and it's not anymore. I'm ssh-ing from a mac client to a linux server.

on the mac:

```
SSHFS version 2.10
OSXFUSE 3.7.1
FUSE library version: 2.9.7
fuse: no mount point
```

on the linux:

```
OpenSSH_7.5p1, OpenSSL 1.1.0e  16 Feb 2017
```

there's nothing visible in the logs, and nothing with `-d` option. `ssh` to the server works.

```
% sshfs user@server:/mountpoint ./mountpoint
mount_osxfuse: the file system is not available (255)
```

**Comment by guyzmo** [comment]
ok, I finally found out what it was. It was related to the number of virtual devices allowed: cf https://github.com/osxfuse/osxfuse/issues/358 

I shut the smbfs kernel extension, and voila !
