### ISSUE TITLE
unreliable behavior (no mount, dismount)

### ISSUE THREAD

**Issue by Popkultur** [osxfuse/osxfuse#451]
Hi,

I experience an unreliable behavior. Sometime my ntfs-disk is dismounted after 1 hour, sometime it is even not mounted after all. Also I can not delete files from the drive.

I'm with openBSD 6.2 and Windows 10, Dualbooting by BIOS and using an exchange disk for my data. The disk is a generic 6TB drive (wd green, probably).

it says now:

The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Failed to mount '/dev/sd1j': Operation not permitted
The NTFS partition is in an unsafe state. Please resume and shutdown
Windows fully (no hibernation or fast restarting), or mount the volume
read-only with the 'ro' mount option.

so, probably it is a difference whether I tell windows to reboot or to shut down.

**Comment by swt2c** [comment]
It doesn't sound like you are using FUSE for macOS.  Are you?

**Comment by Popkultur** [comment]
no, actually not. I don't even really know what FUSE is. okay. Wrong thread, wrong repository.
