### ISSUE TITLE
is it possible to refresh Finder manually via OSX FUSE?

### ISSUE THREAD

**Issue by KobeLuo** [osxfuse/osxfuse#453]
- we are making virtual drive via OSX FUSE, and connect to server
- Now, server did change, I want to refresh finder manually

### is it possible to do it via fuse?

**Comment by Ajaybh** [comment]
Try NSWorkspace.shared().noteFileSystemChanged(path)

**Comment by KobeLuo** [comment]
Yes, ` NSWorkspace.shared().noteFileSystemChanged(path)` it's work.

#### Note: 
- the code must execute in main thread,else the finder will not responding.

Thanks. @Ajaybh

**Comment by amoffat** [comment]
I wasn't able to get NSWorkspace noteFileSystemChanged working (even called it on the main thread), but I did have luck with `fuse_invalidate_path` called with a mount-relative path.
