### ISSUE TITLE
Unmounting sshfs drive causes system crash

### ISSUE THREAD

**Issue by mbsabath** [osxfuse/osxfuse#456]
On Mac OS 10.12.6, on a 2017 MacBook Pro. 

Unmounting a drive on both the command line (`umount <relative and absolute path>`) and in finder causes a forced restart. My theory is that somehow the local file system is being unmounted. Has anyone else ran into this error?

**Comment by vzakuta** [comment]
For me as well - same behavior on Mac OS 10.12.6. Started happening as soon as I upgraded from El Capitan to Sierra. Unmounting either on command line or via the Finder or via MacFusion causes forced system restart.

Here is the kernel panic log

[MacSierraKernelPanicOSXFuse.txt](https://github.com/osxfuse/osxfuse/files/1555920/MacSierraKernelPanicOSXFuse.txt)

**Comment by bfleischer** [comment]
Could you please post the kernel panic log? Without the logs it is virtually impossible to diagnose the issue. You should be able to find the relevant logs in `/Library/Logs/DiagnosticReports`. Alternatively you can try to reproduce the panic and then copy the complete report from the panic alert (after your Mac has restarted) and post that.

**Comment by vzakuta** [comment]
I just posted the kernel panic log.
[MacSierraKernelPanicOSXFuse.txt](https://github.com/osxfuse/osxfuse/files/1555922/MacSierraKernelPanicOSXFuse.txt)

**Comment by bfleischer** [comment]
@vzakuta The panic is caused by the CrowdStrike Software you are using. As you can see in the following extract from the panic log the FUSE kernel extension does not play a part in the backtrace that lead to the panic.

```
      Kernel Extensions in backtrace:
         com.crowdstrike.sensor(58.3)[87F86A9D-75DF-30A4-BB32-6F56A392FE48]@0xffffff7f93e7f000->0xffffff7f93f48fff
            dependency: com.crowdstrike.platform(1.1)[5082D4E1-4EF4-365E-BA08-E0AF10787460]@0xffffff7f93e7a000
            dependency: com.apple.iokit.IONetworkingFamily(3.2)[6326DB88-5330-3F0C-91F6-D478AB5E7503]@0xffffff7f91b51000
```

Please contact the CrowdStrike team for support. This is something they need to have a look at.

@mbsabath Are you using the CrowdStrike software, too? It would be great if you could post a panic log.

**Comment by vzakuta** [comment]
Thanks!
Will do. It’s the antivirus that runs on my machine.
Vitaly
