### ISSUE TITLE
Build Error macOS 10.13

### ISSUE THREAD

**Issue by siosys** [osxfuse/osxfuse#457]
Trying to build osxfuse 3.7.1 I'm encountering the following error:

:info:build ** BUILD FAILED **
:info:build The following build commands failed:
:info:build 	PhaseScriptExecution BridgeSupport\ Metadata build/OSXFUSE.build/Release/OSXFUSE.build/Script-28D525C40EA8076400B7CF7B.sh
:info:build (1 failure)

I saw this was an issue back in June, but my understanding is that this should be fixed for 10.13? Building osxfuse 3.7.1 work fine for me on 10.12 and 10.11.

**Comment by swt2c** [comment]
See #416
