### ISSUE TITLE
The many "osxfuseXX" files under /dev

### ISSUE THREAD

**Issue by nythepegasus** [osxfuse/osxfuse#458]
I'm sorry if this is a stupid question, but what are the "/dev/osxfuseXX" used for? I currently have 64 of these files.. Are they something I should worry about consuming a lot of storage?

**Comment by steveatinfincia** [comment]
The OSXFUSE kext uses tiny device files in `/dev/` to let apps communicate with it. They don't take up any space and shouldn't cause problems.
