### ISSUE TITLE
ntfs-3g Error code -36

### ISSUE THREAD

**Issue by 6pm** [osxfuse/osxfuse#459]
I checked [linux.die.net/man/8/ntfs-3g.probe](https://linux.die.net/man/8/ntfs-3g.probe) and didn't found error with code 36.  
What is means this error? And how I fix it?

**Comment by bfleischer** [comment]
Please note that NTFS-3G and FUSE for macOS are independent projects. Should you run into NTFS-3G related issues please post the issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7.

As far as I know the error originates from Finder and it seems to to be triggered by NTFS-3G. So far I have not been able to reproduce the issue with other file systems. This is something the NTFS-3G team needs to investigate.
