### ISSUE TITLE
Problem with umlauts ('ä','ö','ü')

### ISSUE THREAD

**Issue by tothrobert** [osxfuse/osxfuse#460]
I have a Macbook Pro with High Sierra and the latest version of Fuse (3.7.1) installed. I use Fuse together with SeaFile. Everything works fine, unless I put files (& folders) with umlaut ('ä', 'ö' or 'ü') characters in their names into my mounted Fuse-Volume. When I open the volume, the files (& folders) with umlauts appear twice in the list. When I remove one of them, both files/folders will be deleted. If I rename one of the files/folders with a filename without umlauts, the file/folder will be listed correctly, that means only once. Not a big issue, but something worth to be mentioned. Anyone an idea for correction?

Robert

**Comment by edouardmercier** [comment]
From my experience, via the command line, this can be solved by using the `-o modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC` option.

**Comment by tothrobert** [comment]
Thanks a lot! 👍

Von meinem iPhone gesendet
