### ISSUE TITLE
Erase a flash disk with Disk Util in ntfs-3g

### ISSUE THREAD

**Issue by ILAgent** [osxfuse/osxfuse#467]
Hello !
I've installed Fuse and ntfs-3g, restarted my Mac (OS X Sierra), but Disk Util isn't offering ntfs-3g as  available FS.  How can I format my drive in ntfs-3g ?

**Comment by bfleischer** [comment]
Please note that NTFS-3G and FUSE for macOS are independent projects. Should you run into NTFS-3G related issues please post the issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7.

As far as I know it is no longer possible to for third-party file system developers to integrate their file systems with Disk Util. But if you know your way around Terminal, you can always use the NTFS command line tools to reformat your disk.
