### ISSUE TITLE
Objective-C LoopbackFS fails with Office 2016 Save

### ISSUE THREAD

**Issue by southrivertech** [osxfuse/osxfuse#471]
Hi,

I'm using the Objective-C LoopbackFS sample to mount a local folder as a volume. Works great. I then run any Office 2016 app (on Mac High Sierra) and when I save it I get a Save error.

Has anyone else seen this issue?

Thanks!

**Comment by bfleischer** [comment]
I'm closing this issue because it has bee inactive for years. Feel free to open a new ticket in case this is still an issue with up-to-date versions of macFUSE and Office. Please provide detailed repro steps, in case you do.
