### ISSUE TITLE
error:  osxfuse: fuse_vnop_readdir failed (err=13)

### ISSUE THREAD

**Issue by mayankchat** [osxfuse/osxfuse#472]
I am getting message in console

osxfuse: fuse_vnop_readdir failed (err=13)

I am using OSX el captain.  How do I correct it?

Thanks.

**Comment by swt2c** [comment]
What FUSE filesystem are you using?

**Comment by mayankchat** [comment]
None.  I have Fuse 3.7.1 installed.

**Comment by swt2c** [comment]
FUSE doesn't do anything by itself.  You have to be using a FUSE filesystem to see that error.  What does `mount` show?

**Comment by mayankchat** [comment]
/dev/disk0s2 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk2s2 on /Volumes/1 TB HD 2016 - 1 (hfs, local, journaled)
/dev/disk0s4 on /Volumes/50 GB HD 2017 - 2 (hfs, local, journaled)
/dev/disk2s4 on /Volumes/1 TB HD 2016 - 2 (hfs, local, journaled)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
Disk Drill@osxfuse0 on /Volumes/.DDPreviewDisk (osxfuse, nodev, nosuid, read-only, synchronous, mounted by mchaturvedi)

**Comment by mayankchat** [comment]
Disk Drill is a Data Recovery software.

**Comment by swt2c** [comment]
You are using 'Disk Drill' FUSE filesystem.  You will have to ask the authors of Disk Drill about that error you are seeing.

**Comment by mayankchat** [comment]
ok Thanks
