### ISSUE TITLE
mac high sierra system crash 

### ISSUE THREAD

**Issue by OptimusPrimeCao** [osxfuse/osxfuse#476]
After install sshfs, my os system frequently crash these days, below is my crash log, anyone could help me on this?

Anonymous UUID:       55509958-BAAC-E247-56D7-0873FBD1ED32

Sun Feb 11 10:22:01 2018

*** Panic Report ***
panic(cpu 2 caller 0xffffff80160b954c): "a freed zone element has been modified in zone kalloc.64: expected 0xfacade2eacec48f9 but found 0xfacafe2eacec48f9, bits changed 0x200000000000, at offset 56 of 64 in element 0xffffff805fc46300, cookies 0x3f0011700a8a4536 0x53521aef3282479"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4570.20.62/osfmk/kern/zalloc.c:1120
Backtrace (CPU 2), Frame : Return Address
0xffffff921747b470 : 0xffffff801606b6f6 
0xffffff921747b4c0 : 0xffffff8016196f54 
0xffffff921747b500 : 0xffffff8016188c39 
0xffffff921747b580 : 0xffffff801601d190 
0xffffff921747b5a0 : 0xffffff801606b1cc 
0xffffff921747b6d0 : 0xffffff801606af4c 
0xffffff921747b730 : 0xffffff80160b954c 
0xffffff921747b790 : 0xffffff80160b9381 
0xffffff921747b7e0 : 0xffffff80160b7903 
0xffffff921747b910 : 0xffffff80160771a4 
0xffffff921747b950 : 0xffffff801661e1c7 
0xffffff921747b980 : 0xffffff801661f694 
0xffffff921747b9a0 : 0xffffff8016677723 
0xffffff921747b9e0 : 0xffffff80166784b2 
0xffffff921747ba50 : 0xffffff801667bcf9 
0xffffff921747bad0 : 0xffffff7f989cecd9 
0xffffff921747bae0 : 0xffffff80166ce9f8 
0xffffff921747bb10 : 0xffffff801613e3fb 
0xffffff921747bb50 : 0xffffff8016070e05 
0xffffff921747bba0 : 0xffffff801604dc2d 
0xffffff921747bbf0 : 0xffffff80160714d0 
0xffffff921747bc30 : 0xffffff80160582ce 
0xffffff921747bcb0 : 0xffffff801605b21c 
0xffffff921747bcf0 : 0xffffff80160952f8 
0xffffff921747bd30 : 0xffffff8016526dec 
0xffffff921747bda0 : 0xffffff801654093d 
0xffffff921747be20 : 0xffffff8016540d97 
0xffffff921747be70 : 0xffffff8016063bff 
0xffffff921747bec0 : 0xffffff801601d15c 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOSurface(209.0)[9D4ADF2A-E6F7-3BFE-B5FF-8C7317DF164B]@0xffffff7f989c5000->0xffffff7f989defff

BSD process name corresponding to current thread: Google Chrome He

Mac OS version:
17B1003

Kernel version:
Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
Kernel UUID: 4B214D53-883B-3E5F-A115-9FDA17E68BA8
Kernel slide:     0x0000000015e00000
Kernel text base: 0xffffff8016000000
__HIB  text base: 0xffffff8015f00000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)

System uptime in nanoseconds: 798380618491
last loaded kext at 373567259048: com.apple.driver.usb.cdc.acm	5.0.0 (addr 0xffffff7f9ba0e000, size 57344)
loaded kexts:
com.github.osxfuse.filesystems.osxfuse	3.7.1
com.apple.filesystems.msdosfs	1.10
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AGPM	110.23.24
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDAHardwareConfigDriver	280.12
com.apple.driver.AppleGraphicsDevicePolicy	3.16.19
com.apple.driver.AppleHDA	280.12
com.apple.AGDCPluginDisplayMetrics	3.16.19
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.1f1
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.AVEBridge	1.0.0
com.apple.driver.AppleThunderboltIP	3.1.0
com.apple.driver.AppleIntelKBLGraphics	10.2.8
com.apple.driver.AGDCBacklightControl	3.16.19
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleBacklight	170.10.1
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.AppleCameraInterface	6.01.2
com.apple.driver.eficheck	1
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleSMCLMU	211
com.apple.driver.AppleIntelKBLGraphicsFramebuffer	10.2.8
com.apple.driver.usb.AppleUSBHostBillboardDevice	1.0
com.apple.filesystems.apfs	748.21.6
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.filesystems.hfs.kext	407.1.3
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.driver.AppleTopCaseHIDEventDriver	127
com.apple.driver.AirPort.BrcmNIC	1200.26.1a3
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	183
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.IOBufferCopyEngineTest	1
com.apple.driver.usb.cdc.acm	5.0.0
com.apple.driver.usb.cdc.ecm	5.0.0
com.apple.driver.usb.cdc.ncm	5.0.0
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.kext.triggers	1.0
com.apple.driver.AppleGraphicsControl	3.16.19
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.iokit.IOTimeSyncFamily	600.15
com.apple.driver.AppleSSE	1.0
com.apple.AppleGPUWrangler	3.16.19
com.apple.iokit.IOBluetoothHostControllerUARTTransport	6.0.1f1
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.1f1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleThunderboltEDMSink	4.1.2
com.apple.driver.AppleThunderboltDPOutAdapter	5.0.2
com.apple.driver.AppleIntelLpssUARTv1	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.iokit.IOSerialFamily	11
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IONDRVSupport	517.17
com.apple.AppleGraphicsDeviceControl	3.16.19
com.apple.iokit.IOAcceleratorFamily2	374.1
com.apple.iokit.IOGraphicsFamily	517.17
com.apple.iokit.IOSurface	209
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleActuatorDriver	1004.1
com.apple.driver.AppleHIDKeyboard	203
com.apple.driver.AppleHSBluetoothDriver	127
com.apple.driver.IOBluetoothHIDDriver	6.0.1f1
com.apple.iokit.IOBluetoothFamily	6.0.1f1
com.apple.driver.AppleMultitouchDriver	1004.1
com.apple.driver.AppleInputDeviceSupport	1000
com.apple.driver.AppleHSSPIHIDDriver	52
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.driver.AppleHPM	3.1.3
com.apple.driver.AppleIntelLpssI2CController	3.0.60
com.apple.driver.AppleHSSPISupport	52
com.apple.driver.AppleThunderboltNHI	4.5.6
com.apple.iokit.IOThunderboltFamily	6.5.8
com.apple.driver.AppleXsanScheme	3
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.1.2
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.20.7
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140
com.apple.iokit.IOSCSIBlockCommandsDevice	404.20.1
com.apple.iokit.IOSCSIArchitectureModelFamily	404.20.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro14,1, BootROM MBP141.0169.B00, 2 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.43f6
Graphics: Intel Iris Plus Graphics 640, Intel Iris Plus Graphics 640, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x170), Broadcom BCM43xx 1.0 (7.77.37.2.1a3)
Bluetooth: Version 6.0.0f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.1

**Comment by bfleischer** [comment]
The crash is triggered by something Google Chrome does.

The backtrace leading to the kernel panic does not contain anything related to FUSE or SSHFS. The panic log lists all kernel extensions that play a part in the crash:

```
Kernel Extensions in backtrace:
com.apple.iokit.IOSurface(209.0)[9D4ADF2A-E6F7-3BFE-B5FF-8C7317DF164B]@0xffffff7f989c5000->0xffffff7f989defff
```

As you can see, FUSE (`com.github.osxfuse.filesystems.osxfuse`) is not in the list. It seems to be a mere coincidence that the panic occurred shortly after you installed SSHFS. Maybe Chrome updated itself at the same time. Even though it looks like this might be a bug in the macOS kernel, it would be best to report it to the Chrome team. 

Anyway, you might want to update to macOS 10.13.3 as it seems you are still running 10.13.1. The issue might have already been fixed in the latest version.
