### ISSUE TITLE
Why fuse always call getAttr with outdated file when open microsoft word/excel

### ISSUE THREAD

**Issue by KobeLuo** [osxfuse/osxfuse#477]
### Description:
- When i double click one office(MS word/excel) file, i found that osxfuse always call getAttributes function for some files which has been deleted. 
- and every time always call these files. 
![error report](https://user-images.githubusercontent.com/26185543/36135430-0032f0bc-10c6-11e8-8276-590e7e91a111.png)

### Questions:
- how to fix it?

***
### Envir:
OSX FUSE for Mac OS: 3.7.1 
Mac system version: 10.13.2 macos high sierra

**Comment by bfleischer** [comment]
FUSE forwards file system operations initiated by other processes to the FUSE daemon running in user space. FUSE does not generate file system operations out of the blue. Office in particular generates a lot of getattr requests. I don't think this is a bug. If you receive a getattr request for a file that has been deleted, simply return ENOENT.

**Comment by KobeLuo** [comment]
@bfleischer  
Thanks great for your reply.

The question is why system will call getattr request for a file that has been deleted ,and these files aways same .
Has some cache in the some place of system ?  

It's not a  issue for functionally, but a lots of getattr request will reduce efficiency, we save one large office file on mount disk very slowly.  we want to improve it.
but there has one application [PCloud](https://www.pcloud.com/zh/) which using osxfuse framework, i found this app save file very fast. even fastly than the `LookbackFS` demo.
