### ISSUE TITLE
LSOpenURLsWithRole() failed with error 5 sshfs macOS High Sierra

### ISSUE THREAD

**Issue by hasibahmed** [osxfuse/osxfuse#478]
Hello, I would like to open issue [#421](https://github.com/osxfuse/osxfuse/issues/421) again. I am facing this issue after updating to High Sierra. Initially this issue was solved by reinstalling sshfs and rebooting. However, the issue came back again. Since then I have tried several approach. Sometimes it would work and other times problem shows up. It seems completely random and unfortuantely I have been able to pinpoint the exact cause of the problem. Any help is much appreciated. 
Thank you!

**Comment by doublsky** [comment]
I am having the same issue. It happens to one of the server I use, but not others. Could it be an issue on the remote side?

**Comment by bddavison** [comment]
Problem for me too.  FUSE for macOS 3.7.1 on High Sierra 10.13.3.

**Comment by ghost** [comment]
I have the same problem

**Comment by DoaneAS** [comment]
also having this issue.  I'm able to cd to the mounted directory in a shell and cp files for example onto my desktop, but all Finder integration is broken.  Fuse 3.7.1, MacOS 10.13.3.

**Comment by uniqueum** [comment]
Running High Sierra (10.13.4) here too, Fuse for macOS 3.7.1, SSHFS 2.5.0

It helped to play around with the options (-o) a little. Had the same problem upon just mounting via
sshfs user@server:/ ~/server ,
but the remote drive/path is perfectly accessible via Finder, if I mount it this way:
sshfs -o auto_cache,allow_other,defer_permissions,volname=server user@server:/path/to/home/ ~/server .

Hope that helps.

**Comment by biomystery** [comment]
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.8.0  (upgraded from 3.7.xx)
FUSE library version: 2.9.7

sshfs -o follow_symlinks,auto_cache,allow_other

The error is  disappeared  after reboot/

**Comment by neoadventist** [comment]
@uniqueum solution worked for me. After I upgraded, I could see the remote file system via the terminal but not via finder. After setting the additional options I was able to see it again! Thanks!

**Comment by kelek** [comment]
All I needed was `-o follow_symlinks`.  The options above didn't work for me when combined with `,IdentityFile=<file>` and produced a `failed to mount ... mnt@/dev/osxfuse0: Operation not permitted`, most likely because it was a `sshfs` without running as root.

**Comment by codechikbhoka** [comment]
I had the similar problem, killed sshfs forcefully and restarted it again. It worked :)

**Comment by bfleischer** [comment]
A new SSHFS build is available on https://macfuse.io/. Therefore, I'm closing this issue.
