### ISSUE TITLE
volicon: missing 'iconpath' option

### ISSUE THREAD

**Issue by tofutim** [osxfuse/osxfuse#480]
I am attempting to mount a qcow2 image using libqcow and osxfuse. However, when I do so, I see
```
Tims-Air:qemu_vms tim$ sudo qcowmount raspbian-stretch.qcow /mnt/rpi
Password:
qcowmount 20170222

volicon: missing 'iconpath' option
Unable to create fuse handle.
```
I had installed osxfuse using `brew install caskroom/cask/osxfuse`. Is the iconpath a compile time option? How do I fix this? I am on OSX 10.13. I'm guessing I have to somehow hook up the icns file.

**Comment by bfleischer** [comment]
Which version of FUSE are you using? The iconpath option is required when loading the volicon module at mount-time. It's not a compile-time option. I've never used qcowmount, but judging from your description I think it would be best to raise the issue with the qcowmount team.

**Comment by bfleischer** [comment]
No feedback, closed.
