### ISSUE TITLE
remote host has disconnected on macOS 10.12.6

### ISSUE THREAD

**Issue by tharwan** [osxfuse/osxfuse#481]
Hi, I am running into a strange issue. I am trying to mount a share on my synology NAS via sshfs. 

When I try to do it with Transmit (the Panic transfer app) everything works fine, and from what I understand they use fuse and sshfs for mounting under the hood.

When I try to mount from the terminal via sshfs everything seems to work fine until I try to open a file. Browsing the directories is still fine. The debug output can be found below.
[fuse.log](https://github.com/osxfuse/osxfuse/files/1748093/fuse.log)

Any idea where the problem could be? Since it works via Transmit I assume it is an issue with either the mounting point (in my case in my home directory) or some option?

**Comment by xguse** [comment]
krickets... ?

**Comment by bobetocalo** [comment]
?????
