### ISSUE TITLE
"Unable to contact update server" on Mac OS X 10.5

### ISSUE THREAD

**Issue by sideeffect42** [osxfuse/osxfuse#483]
When launching the FUSE preference pane on Mac OS X 10.5.8 it displays the message "Unable to contact update server" instead of checking for updates (and prompting for an update if one is available).

**Comment by bfleischer** [comment]
Thanks for the bug report. OS X 10.8 and earlier versions do not seem to support the TLS standard required for downloading the release file, that is hosted on GitHub. Opening the FUSE for macOS website https://osxfuse.github.io/ in Safari does not work either on OS X 10.8 and earlier versions. This could be related to https://githubengineering.com/crypto-deprecation-notice/.

However, I don't think there is anything we can do to fix this besides moving the release file to a less secure host. This is certainly not ideal.

**Comment by sideeffect42** [comment]
The reason for the failure is GitHub having dropped TLS 1.0 support for sure.
There's a few options I can think of, neither is ideal:

1. Move to a "less-secure" host
As you said this not ideal, but in terms of security it would not be worse than before.
The supported ciphers could be customized to get the best out of what's available. The result should not be too bad, especially since it's just transport encryption. The validity of the installer should be verified with dedicated checksums and signatures.
2. Ship own SSL library (CommonCrypto, OpenSSL, ...)
This is the most inconvenient option, but the most secure one.
Since CommonCrypto is open-source there is a chance that a newer version (that supports TLS 1.2) would run on older versions of OS X and could be shipped with OSXFUSE.
3. Disable updater
If the above two options don't work, the updater could be disabled and replaced with a link to an updates page. The link could be opened in a browser which supports TLS 1.2.
(http://tenfourfox.blogspot.com/2018/02/the-tls-apocalypse-reaches-power-macs.html)
