### ISSUE TITLE
OS X 10.13.2 kernel panic using rsync and FUSE for macOS 3.7.1 (upspinfs)

### ISSUE THREAD

**Issue by unobe** [osxfuse/osxfuse#484]
I'm not sure where precisely the cause of this bug is happening, so am reporting to Apple, this project, and [upspin.io](https://github.com/upspin/upspin/issues/576).

1. What version of osxfuse are you using? The latest download for OS X (FUSE for macOS 3.7.1)
2. What operating system and processor architecture are you using? OS X 10.13.2 iMac (21.5-inch, Late 2013) 2.7 GHz Intel Core i5
3. What did you do?
Created two upspin servers, mounting each using upspinfs. Since there were a lot of files, I decided to see how rsync handles such a task, so did:
`$ rsync -av ~/ufs-a/user@example.com/my_data ~/ufs-b/user@example.com/my_data`
The rsync got so far as building the list of files to copy, and when it was taking unusually long, I figured it might be better to stop the process and copy over small groups of files. I pressed ^C a few times to abort the process.
4. What did you expect to see?
I expected for the process to stop and return to the terminal prompt so that I could use another method of file transfer.
5. What did you see instead?
A kernel panic occurred, which I obviously didn't expect:
`Anonymous UUID:       2445484F-08E2-751C-9AA7-E69BCD85497B

Sun Mar 11 01:06:43 2018

*** Panic Report ***
panic(cpu 1 caller 0xffffff800b600fb8): Mutex unlock attempted from non-owner thread
Backtrace (CPU 1), Frame : Return Address
0xffffff91157031b0 : 0xffffff800b6505f6 
0xffffff9115703200 : 0xffffff800b77d604 
0xffffff9115703240 : 0xffffff800b76f0f9 
0xffffff91157032c0 : 0xffffff800b602120 
0xffffff91157032e0 : 0xffffff800b65002c 
0xffffff9115703410 : 0xffffff800b64fdac 
0xffffff9115703470 : 0xffffff800b600fb8 
0xffffff9115703480 : 0xffffff800b65f6f3 
0xffffff91157034c0 : 0xffffff800bb2b7f6 
0xffffff9115703540 : 0xffffff800bb2bcc2 
0xffffff9115703580 : 0xffffff7f8e5061ce 
0xffffff91157035b0 : 0xffffff7f8e50c44e 
0xffffff91157035e0 : 0xffffff800b8baf03 
0xffffff9115703650 : 0xffffff7f8c50446f 
0xffffff91157038e0 : 0xffffff7f8c502826 
0xffffff91157039d0 : 0xffffff7f8c4f8b5b 
0xffffff9115703a20 : 0xffffff7f8c4fcb85 
0xffffff9115703b60 : 0xffffff800bd042ed 
0xffffff9115703ba0 : 0xffffff800b8b133d 
0xffffff9115703bf0 : 0xffffff800b89f41b 
0xffffff9115703f10 : 0xffffff800b89fd1f 
0xffffff9115703f40 : 0xffffff800bbfb3e8 
0xffffff9115703fa0 : 0xffffff800b602906 
      Kernel Extensions in backtrace:
         com.apple.security.sandbox(300.0)[0E42B540-D3DB-3904-BD91-F604DB2F5712]@0xffffff7f8c4f5000->0xffffff7f8c514fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[58669FC2-CC90-3594-AD69-DB89B923FD20]@0xffffff7f8c4db000
            dependency: com.apple.kext.AppleMatch(1.0.0d1)[2D2996CA-A15E-39E6-9D6B-2BE6DF131972]@0xffffff7f8c4f0000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[B0FCE898-1542-34C0-B845-46FAE81DD9E6]@0xffffff7f8be51000
         com.github.osxfuse.filesystems.osxfuse(3.7.1)[8C89BD7B-DA6D-347D-AC76-759C45AE6099]@0xffffff7f8e505000->0xffffff7f8e51dfff

BSD process name corresponding to current thread: rsync

Mac OS version:
17C205

Kernel version:
Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
Kernel UUID: 87641697-A3DD-30C4-B010-E65ECE57550B
Kernel slide:     0x000000000b200000
Kernel text base: 0xffffff800b400000
__HIB  text base: 0xffffff800b300000
System model name: iMac14,1 (Mac-031B6874CF7F642A)

System uptime in nanoseconds: 1064463808316848
last loaded kext at 1022362836184894: com.github.osxfuse.filesystems.osxfuse	3.7.1 (addr 0xffffff7f8e505000, size 106496)
last unloaded kext at 1035095180780508: com.apple.driver.CoreStorage	546 (addr 0xffffff7f8e36f000, size 884736)
loaded kexts:
com.github.osxfuse.filesystems.osxfuse	3.7.1
com.apple.filesystems.ntfs	3.13
com.apple.filesystems.smbfs	3.2
com.apple.driver.AppleBluetoothMultitouch	92
com.apple.driver.AudioAUUC	1.70
com.apple.AGDCPluginDisplayMetrics	3.16.2
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.2f2
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AGPM	110.23.24
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelHD5000Graphics	10.3.0
com.apple.driver.AppleHDA	280.12
com.apple.driver.AppleThunderboltIP	3.1.1
com.apple.driver.AppleMikeyDriver	280.12
com.apple.driver.eficheck	1
com.apple.iokit.AppleBCM5701Ethernet	10.3.1
com.apple.driver.AppleSMCLMU	211
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleLPC	3.1
com.apple.driver.AirPort.BrcmNIC	1220.28.1a3
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.AppleIntelFramebufferAzul	10.3.0
com.apple.filesystems.autofs	3.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	407.30.1
com.apple.driver.AppleAHCIPort	329
com.apple.driver.AppleSDXC	1.7.6
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	183
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.IOBufferCopyEngineTest	1
com.apple.driver.AppleBluetoothHIDKeyboard	203
com.apple.driver.AppleHIDKeyboard	203
com.apple.driver.IOBluetoothHIDDriver	6.0.2f2
com.apple.driver.AppleMultitouchDriver	1204.13
com.apple.driver.AppleInputDeviceSupport	1201.8
com.apple.iokit.IOTimeSyncFamily	650.5
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSSE	1.0
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.AppleGPUWrangler	3.16.2
com.apple.iokit.IONDRVSupport	517.22
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleThunderboltEDMSink	4.1.2
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.AppleGraphicsDeviceControl	3.16.21
com.apple.iokit.IOAcceleratorFamily2	376.6
com.apple.iokit.IOGraphicsFamily	517.22
com.apple.iokit.IOSurface	209.2.2
com.apple.kext.triggers	1.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.2f2
com.apple.iokit.IOBluetoothFamily	6.0.2f2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPOutAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.iokit.IOAHCIBlockStorage	301.20.1
com.apple.driver.AppleThunderboltNHI	4.5.6
com.apple.iokit.IOThunderboltFamily	6.6.3
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.30.4
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.30.1
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.30.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

EOF
Model: iMac14,1, BootROM IM141.0123.B00, 4 processors, Intel Core i5, 2.7 GHz, 8 GB, SMC 2.14f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.77.37.5.1a3)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS541010A9E662, 1 TB
USB Device: USB 3.0 Bus
USB Device: BUP Slim SL
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
Thunderbolt Bus: iMac, Apple Inc., 23.10
`

**Comment by LishengZhou** [comment]
My iMac (macOS High Sierra) got kernel panic after rsync too...

**Comment by bfleischer** [comment]
Is this still an issue with the new 3.8.0 release?

**Comment by LishengZhou** [comment]
Thanks for asking! The issue has gone after I re-installed High Sierra. Sorry for not updating earlier!

-Lisheng

**Comment by bfleischer** [comment]
@unobe Can you reproduce the kernel panic somewhat reliably? It would be great if you could post a panic log with the most recent version of macOS (17E202). Apple has not release a kernel debug kit for the specific version of macOS you were using at the time of the panic. This means that I'm only able to symbolicate the FUSE part of backtrace, which is not very helpful in this particular case.

**Comment by bfleischer** [comment]
Since there is no kernel debug kit for version 17C205 there is nothing I can do. Feel free to reopen the issue if you can reproduce the panic with an up to date version of macOS.
