### ISSUE TITLE
Word creates temp folders when saving existing .doc file

### ISSUE THREAD

**Issue by jeremyspiegel** [osxfuse/osxfuse#485]
When running loopback, open an existing .doc file, make an edit, and save. Word 2016 creates a temp folder with a name of the form `test.doc.sb-6d6ce842-tI5oYC`, and this folder isn't removed until the document is closed in Word. It seems that this is a known issue when opening such files over an SMB share (https://community.spiceworks.com/topic/1946623-office-mac-2016-word-when-saving-creates-a-folder-file-docx-sb-xxxxxxxx-xxxxxx). This doesn't happen when opening a .doc file on the local HFS+ filesystem.

Is there a way to prevent this behavior (to appear to Word more like HFS+ and not like an SMB mount)? I've tried using the "-o local" option but that doesn't help.

Thanks!

**Comment by ghost** [comment]
I am not using osxfuse, and I have the same issue.
Here are some further threads on this topic. They have not solved the problem for me, but might help you debug.

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_mac/how-to-stop-mac-creating-a-separate-backup-folder/e3021801-2f82-4a64-b3f6-95675fef337d

https://community.spiceworks.com/topic/1946621-tmp-file-issue-office-2016-for-mac?from_forum=42

https://social.technet.microsoft.com/Forums/office/en-US/50d3d7fb-f9c1-49b3-86e3-f9ede62b33d0/mac-2016-word-when-saving-creates-a-folder-example-nameoffolderdocxsb98c2cb88xxxxxx?forum=Office2016forMac

**Comment by crosscontrol** [comment]
I also am not using osxfuse but I was having a very similar issue and I want to post what fixed this for me. What I was seeing: multiple of those temporary folders were created and Word couldn't save files at all. The temp folders would persist after closing Word. After this fix, a single folder still shows up but is removed after a few moments (without having to close Word).

For my issue, the solution was a dataset settings issue that caused this behavior. Hopefully others can translate this solution to their particular SMB implementation. I'm using FreeNAS-11.3-U5 (uses ZFS) at the time of this writing for my SMB share. When creating a dataset if you don't select a share type of SMB (other option being Generic), it won't work properly with Word and other applications (Apple Pages too). Namely, the [documentation denotes](https://www.ixsystems.com/documentation/freenas/11.3-U5/storage.html?highlight=data%20set#id41) these changes when creating the dataset:

"Select the type of share that will be used on the dataset. Choose between Generic for most sharing options or SMB for a SMB share. Choosing SMB sets the **ACL Mode to Restricted** and **Case Sensitivity to Insensitive**. This field is only available when creating a new dataset."

I think the key here is that the case sensitivity of the data is set to **insensitive** (like the Mac OS). The ACL mode might affect it too so something to look at.

Hopefully this helps someone or this project.

**Comment by bfleischer** [comment]
When implementing the FUSE renamex callback, mounting with the local flag and setting up a .TemporaryItems folder structure on the FUSE volume, FUSE should behave like HFS when saving Word documents.
