### ISSUE TITLE
Error opening '/dev/disk2s1': Resource busy

### ISSUE THREAD

**Issue by chaevnicher** [osxfuse/osxfuse#486]
> $sudo /usr/local/bin/ntfs-3g /dev/disk2s1 /Volumes/NTFS -olocal -oallow_other

return
Error opening '/dev/disk2s1': Resource busy
Failed to mount '/dev/disk2s1': Resource busy
Mount is denied because the NTFS volume is already exclusively opened.
The volume may be already mounted, or another software may use it which
could be identified for example by the help of the 'fuser' command.

**Comment by bfleischer** [comment]
This is an NTFS-3G issue. Please note that NTFS-3G and FUSE for macOS are independent projects. Should you run into NTFS-3G related issues please post the issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7.
