### ISSUE TITLE
Cannot find the description on how to use Fuse

### ISSUE THREAD

**Issue by Marty56** [osxfuse/osxfuse#487]
A getting started is missing.

A lot of talks about APIs and stuff but a simple "getting started" is missing or at least I could not find it after having search for 20 minutes. It would be great to put a link on the home page.

The FAQ talks about "4.2. I mounted a "FUSE for OS X" volume ..." but no doc on "how to mount a FUSE for OS X volume". I guess this is a just too trivial question for Fuse developers to be answered in the FAQ.

**Comment by jamie-arcc** [comment]
+1 on this.  I am also having issues with configuration.  sysctl does not show the paths listed on the "mount options" page in the wiki. vfs.general does not contain anything related to osxfuse.
