### ISSUE TITLE
Help wanted: Is there a way to tell if a file is being opened directly by the user with a double click. 

### ISSUE THREAD

**Issue by 0Dmitry** [osxfuse/osxfuse#489]
We are trying to build a virtual disk that shows files from a remote file storage. And we want that the user could be able to see the whole folder structure and files that exists in the remote storage through this virtual disk, but the files should be downloaded from the remote storage only when the user has double-clicked on a file. The problem is that when I open a folder in the mounted fuse drive, method `- (BOOL)openFileAtPath:(NSString *)path  mode:(int)mode userData:(id *)userData error:(NSError **)error`  is called on each file of that directory.  

Is there a way to find out whether the user actually tries to open a file or just opens the directory containing it ?

**Comment by bududomasidet** [comment]
the same problem there, please help
