### ISSUE TITLE
sysctl on High Sierra 10.13.3 does not show 'vfs.generic.osxfuse' path

### ISSUE THREAD

**Issue by jamie-arcc** [osxfuse/osxfuse#490]
Just installed 3.7.1 using the dmg installer from the website onto 10.13.3, running on a Late 2012 21.5" Core-i7 iMac. I am trying to follow the directions in the mount options wiki page, but the referenced path 'vfs.generic.osxfuse' is not being shown by sysctl, even after a reboot.  the FUSE menu appears in system preferences.

**Comment by bfleischer** [comment]
Are you sure the FUSE kernel extension was loaded at the time you checked for vfs.generic.osxfuse?

**Comment by jamie-arcc** [comment]
I am not sure how I would check that, but I will try to figure that out. I installed it per the directions and even rebooted numerous times.  I am still somewhat new to Mac, coming mostly from Linux.

update:

No, It doesn't appear to be loaded.

**Comment by jamie-arcc** [comment]
I just installed 3.8.0 and the issue is resolved by that.
