### ISSUE TITLE
Frequent System Freezes and Crashes

### ISSUE THREAD

**Issue by Serubin** [osxfuse/osxfuse#492]
Hello!

I've been having some odd problems on a Macbook Pro 2017 TB running 10.13.3. When doing io intensive work such as npm i or rsyncing data off the EncFS/FUSE drive my computer tends to freeze up and crash or EncFS/FUSE becomes unreachable (though the EncFS/FUSE drive is still mounted).

I've been collecting logs to see what might be the cause, but both FUSE and EncFS logs seem normal. Happy to provide if necessary. 

To clarify, these crashes cause the entire machine to freeze up and require a power cycle to remedy.

Thanks!

**Comment by jasonkhadka** [comment]
I have similar problem right now. MacBook Pro 2017 (10.13.4).   
If I try to mount a drive ` sshfs user@x.x.x.x:/home/user/drive /Users/name/Documents/mount -ovolname=my-mount`
and this freezes the terminal and the computer. I updated Fuse to `3.8` and this problem still persists. 
This problem started this week, for some reason.

**Comment by Serubin** [comment]
It's been very difficult to pin point where this is coming from as the logs all look normal and it seems to be an issue specifically with the newer MBPs.
