### ISSUE TITLE
Problems with install due to something in the security tab

### ISSUE THREAD

**Issue by HSoeren** [osxfuse/osxfuse#496]
![image](https://user-images.githubusercontent.com/25493517/38824358-42bd473e-41a9-11e8-8c73-32487927f47b.png)
(UI in german) - It asks me for the permission to trust the software by Benjamin Fleischer, if i click on "Erlauben" (Allowing to run it) nothing happens. I just reinstalled software, looked for updates for my macbook and rebooted it two or three times. Is there something to consider ?
Thanks

**Comment by akhaisin** [comment]
This https://github.com/osxfuse/osxfuse/issues/437#issuecomment-358425747 helped me.

**Comment by bfleischer** [comment]
This is a duplicate of issue #437. #437 already contains a pretty extensive list of applications that are messing with allowing third party kernel extensions in system preferences.
