### ISSUE TITLE
Appending does not work when direct_io is set

### ISSUE THREAD

**Issue by petersohn** [osxfuse/osxfuse#497]
I used [this example](https://www.cs.nmsu.edu/~pfeiffer/fuse-tutorial/)  to reproduce the problem. All it does is replicate a directory and log all operations. Without any special mount options, it works well. However, with the `direct_io` mount option, appending to a file does not work. Instead of writing to the end of the file, the contents are written to the beginning. The same happens if I modify the source code and add `fi->direct_io = 1;` into `open()`.

It can be simply reproduced from the shell. After the following commands:

```bash
echo 'first line' >test_fuse/a
echo 'second' >>test_fuse/a
```

The contents of the file should be this:

```
first line
second
```

But instead, when using `direct_io`, the contents are:

```
second
ine
```

**Comment by benrubson** [comment]
I faced the same issue with FreeBSD :
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220185

**Comment by petersohn** [comment]
It looks like the issue has a fix already committed: https://github.com/osxfuse/kext/commit/10412fb23bda9693ae8e7f7859e5d80df2406c63

When are you planning the next release?

**Comment by bfleischer** [comment]
Thanks for the bug report. The new 3.8.0 release fixes the issue.
