### ISSUE TITLE
path length limit (if the path language is chinese, Japanese, Korean)

### ISSUE THREAD

**Issue by mawenbo** [osxfuse/osxfuse#498]
when path language is chinese , japanese, korean, if the file path name is to long , it will not show this file ,and not show the other file or folder.

can you tell me the rule of judge the path length (language is not english),so I can delete the path if the  path name is too long

**Comment by bfleischer** [comment]
What file system are you using? Have you tried contacting the developer of the particular file system?

**Comment by jief666** [comment]
I think I have the same problem. And it's not about asian version.
In the kext, you are using MAXNAMLEN as the max length of a name. It seems logical, alright, but it's doesn't work with UTF8. One char can be 3 chars (which is common for asian version).

Try a file named : abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþāăąćĉċčďđēĕėęěĝğġģĥħĩīĭįĳĵķĺļľŀłńņňŋōŏőœŕŗřśŝşšţťŧũūŭůűųŵŷÿźżžɓƃƅɔƈɖɗƌǝəɛƒɠɣɩɨƙɯɲɵơƣƥƨʃƭʈưʊʋƴƶʒƹƽǆǆǉǉǌǌǎǐǒǔǖǘ
also it shows up fine in Finder, it won't with osxfuse.
It's 255 character, but strlen() is 396.

this : ǚǜǟǡǣǥǧǩǫǭǯǳǳǵǹǻǽǿȁȃȅȇȉȋȍȏȑȓȕȗșțȟȧȩȫȭȯȱȳ̀́̓ʹ;ά·έήίόύώαβγδεζηθικλμνξοπρστυφχψωϊϋϣϥϧϩϫϭϯѐёђѓєѕіїјљњћќѝўџабвгдежзийклмнопрстуфхцчшщъыьэюяѡѣѥѧѩѫѭѯѱѳѵѷѹѻѽѿҁґғҕҗҙқҝҟҡңҥҧҩҫҭүұҳҵҷҹһҽҿӂӄӈӌӑӓӗӝӟ
has 254 characters, but a strlen() of 424

So DIRCOOKEDSIZE has to be maxed out to 255 utf8 chars, which is 4*MAXNAMLEN.

**Comment by vincentdchan** [comment]
@bfleischer Will this issue be fixed?

**Comment by bfleischer** [comment]
This is not a macFUSE issue. File names on macFUSE may be 255 bytes long, not 255 UTF-8 characters. You need to make sure to use the NFC representation instead of the NFD representation to fit more characters in the 255 bytes.

**Comment by jief666** [comment]
Anyway MacFUSE can be updated to accept more than 255 bytes ?

**Comment by bfleischer** [comment]
255 bytes is the standard. Most file system do not support longer file names. See https://en.wikipedia.org/wiki/Comparison_of_file_systems. 

It might be possible to increase the limit, but this would raise a lot of issues, e.g. copying a file with a longer name than 255 bytes to an APFS, HFS+ or exFAT volume would no longer work.

**Comment by bfleischer** [comment]
The hard limit for file names on macOS 11 seems to be 1024 bytes (including the terminating \0 character).
