### ISSUE TITLE
[Swift] Asynchronous task and synchronous return

### ISSUE THREAD

**Issue by Mathieu-Gosbee-ConnectedLab** [osxfuse/osxfuse#499]
I'm unable to run an asynchronous task to fetch data using the following signature as it expects a synchronous return value:
`readFile(atPath path: String!,
                                  userData: Any!,
                                  buffer: UnsafeMutablePointer<Int8>!,
                                  size: Int,
                                  offset: off_t,
                                  error: NSErrorPointer)  -> Int32`

Is there a known solution for this?

**Comment by Mathieu-Gosbee-ConnectedLab** [comment]
The "answer" is `DispatchSemaphore`.
```

let dispatch = DispatchSemaphore(value: 0)
func syncReturn () -> Int32 {
        var val: Int32 = -1
        
        DispatchQueue.global().asyncAfter(deadline: .now() + .milliseconds(500)) {
            print("500 msec seconds later")
            val = 11
            dispatch.signal()
        }
        dispatch.wait()
        return val
}

```

There doesn't seem to be a way to do it natively async.

**Comment by bfleischer** [comment]
If you are looking for a asynchronous API you might want to consider using the low level FUSE C API. Other than that some form of semaphore or locking mechanism should work, as @Mathieu-Gosbee-ConnectedLab explained.
