### ISSUE TITLE
How to set creation time

### ISSUE THREAD

**Issue by alexanderharm** [osxfuse/osxfuse#501]
FUSE itself does not seem to have support for file creation time (birth time, `Btime`). Is there an attribute in osxfuse I can use to set the creation time of a file? Currently all files show as created on `1970-01-01` in Finder.

rfjakob/gocryptfs#229

**Comment by bfleischer** [comment]
FUSE for macOS sends `FUSE_GETXTIMES` messages to your user space file system daemon. You need to reply with the creation time. I don't know how this is handled by the Go library you are using. But this is definitely no t a limitation of FUSE.
