### ISSUE TITLE
Version 3.8.0: Upgrade prompting for older version (3.7.1)

### ISSUE THREAD

**Issue by deinfluence** [osxfuse/osxfuse#502]
Just upgraded to 3.8.0 and its prompting to upgrade (downgrade) to an older version. Assume its an issue on the website rather than code

![fuse issue](https://user-images.githubusercontent.com/27931868/39840259-c3eba8d6-53ac-11e8-9805-5db69609ec1b.jpg)

**Comment by dany20mh** [comment]
It's because the 3.8.0 is beta version and you don't have **Show Beta Versions** checked so the latest available version would be 3.7.1

**Comment by deinfluence** [comment]
Its not beta any more: https://osxfuse.github.io/2018/05/07/OSXFUSE-3.8.0..html

**Comment by bfleischer** [comment]
Thanks @dany20mh
