### ISSUE TITLE
Unable to install in High Sierra, hangs on Validating Packages 3.8.0 & 3.7.0

### ISSUE THREAD

**Issue by hutber** [osxfuse/osxfuse#504]
I am trying to install via PKG.

I will install with all options or without, the outcome is the same. I follow the steps, then the install starts.
Once it reaches the Validating packages... the bullets on the left change from Installation to the `Complete Installation` being darker grey, but still not changing 
![image](https://user-images.githubusercontent.com/1344898/40369870-dba48bd0-5dd6-11e8-9c1b-7587219bc6c3.png)

I then click the Red cross as there is nothing left to do:
![image](https://user-images.githubusercontent.com/1344898/40369905-f3ae76dc-5dd6-11e8-8f0c-a3414a8b540f.png)

When I click `Show Error` the dialog just disappears, so i am unable to show you the error log either.

Sorry.

**Comment by dkotama** [comment]
have you tried using brew installer ?

`brew cask install osxfuse`

**Comment by saibv** [comment]
I am seeing the same issue with the package installer on High Sierra. The brew installer doesn't work either.. 

brew cask install osxfuse
Updating Homebrew...
==> Caveats
To install and/or use osxfuse you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

You must reboot for the installation of osxfuse to take effect.

==> Satisfying dependencies
==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.8.0/osxfuse-3.8.0.dmg
Already downloaded: /Users/sabhagav/Library/Caches/Homebrew/Cask/osxfuse--3.8.0.dmg
==> Verifying checksum for Cask osxfuse
==> Installing Cask osxfuse
==> Running installer for osxfuse; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is FUSE for macOS
installer: choices changes file '/var/folders/9z/p7mnc52x7k51nvs9wjp8tvv80000gn/T/choices20180626-14639-11vlu7s.xml' applied
installer: Upgrading at base path /
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 3.8.0 of Cask osxfuse
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/osxfuse/3.8.0/Extras/FUSE for macOS 3.8.0.pkg -target / -applyChoiceChangesXML /var/folders/9z/p7mnc52x7k51nvs9wjp8tvv80000gn/T/choices20180626-14639-11vlu7s.xml

==> Standard Output of failed command:
installer: Package name is FUSE for macOS
installer: choices changes file '/var/folders/9z/p7mnc52x7k51nvs9wjp8tvv80000gn/T/choices20180626-14639-11vlu7s.xml' applied
installer: Upgrading at base path /
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 15488 exit 1>

**Comment by zhanglp99** [comment]
I got the same issue. Installation hang on "Validating packages...", any idea to solve it ?

**Comment by mpechner** [comment]
Yup.  "System software from developer "Benjamin Fleischer" was blocked from loading"  I unlock the panel and click allow aaannnddd click allow annddd....

Paid for SyncMate and this is a require component.  Open a ticket with them as well.

**Comment by AdanCortes** [comment]
After many unsuccessful attempts to install osxfuse via the PKG file, I was able to install it on 10.13.6 High Sierra by:
1. Installing all system updates
2. Issuing the following commands on a terminal
<code><pre>
sudo spctl --master-disable
sudo reboot
brew cask install osxfuse
sudo reboot
</pre></code>

**Comment by mpechner** [comment]
That is it.  It is a recentish update.  Because I tit not have this issue before.  This is begin  called a feature to improve security.  But, no, a bug to require these steps.

**Comment by ahmedelz** [comment]
Thanks @AdanCortes. These commands worked for me on 10.14.3.

```
sudo spctl --master-disable
sudo reboot
brew cask install osxfuse
sudo reboot
```

**Comment by AdanCortes** [comment]
I'm glad it helped.

**Comment by foxdelta99** [comment]
Hello,

I've got the same kind of problem, on High Sierra. Neither dmg install nor brew install work. The brew install error is slightly different as the one stated above:
```
==> Installing Cask osxfuse

==> Running installer for osxfuse; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is FUSE for macOS
installer: Installing at base path /
installer: The install failed (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide.)
==> Purging files for version 3.9.2 of Cask osxfuse
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=florianduret USER=florianduret USERNAME=florianduret /usr/sbin/installer -pkg /usr/local/Caskroom/osxfuse/3.9.2/Extras/FUSE\ for\ macOS\ 3.9.2.pkg -target /` exited with 1. Here's the output:
installer: Package name is FUSE for macOS
installer: Installing at base path /
installer: The install failed (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:109:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>
```

The proposed solution consisting in running the 
``` sudo spctl --master-disable```
command does not work for me either.

Any ideas ?

**Comment by zhanglp99** [comment]
I come cross the same issue as "foxdelta99",  the below  recipe :
"sudo spctl --master-disable
sudo reboot
brew cask install osxfuse
sudo reboot "  does not work for me,
 any update ?

**Comment by VaZ420** [comment]
Anyone stomp this bug out yet after a year ?!??!
Same thing is happening to me in Mojave 10.4.6. 
Manually added the osxfuse prefpane and it says FUSE DOES NOT APPEAR TO BE INSTALLED.
Clicking install FUSE asks for my password and then Nothing. FUSE DOES NOT APPEAR TO BE INSTALLED.
What is this bug ??

**Comment by bfleischer** [comment]
@VaZ420

I have never been able to reproduce the issue. Without being able to reproduce it, there is nothing I can do. The issue is most likely caused by something on your Mac. It could be number of things. 

If possible, try installing FUSE on a clean install of macOS and I'm sure it will work just fine.

**Comment by VaZ420** [comment]
Yes it generally works on all systems except for mine recently. Ok in vmware mojave too.
I had it installed for years and the 2nd last update failed so i removed it. Then i installed the latest .pkg and it gets stuck on Validating…

**Comment by VaZ420** [comment]
![Screen Shot 2024-04-05 at 7 33 31 PM](https://github.com/osxfuse/osxfuse/assets/66917489/f1ebd44d-75ed-4f07-9084-ad742be00c1f)

Problem still persists in Mojave with latest 4.6.2. 
"Unable to install update"

Any solid fix yet ?

**Comment by bfleischer** [comment]
@VaZ420 Try downloading the installer from https://macfuse.io and run it. As I said 4 years ago, installing macFUSE works fine on a clean install of Mojave and you confirmed that it works fine on your Mojave VM. That makes it an isolated issue that is most likely caused by something on your Mac.

**Comment by hutber** [comment]
Why does anybody use Macs, its beyond me. When almost all flavours of linux actually work!!

**Comment by VaZ420** [comment]
> @VaZ420 Try downloading the installer from https://macfuse.io and run it. As I said 4 years ago, installing macFUSE works fine on a clean install of Mojave and you confirmed that it works fine on your Mojave VM. That makes it an isolated issue that is most likely caused by something on your Mac.

Ya sure isolated..so whats casuing my issue and the others who are stuck on 'Validating' ? 
![Screen Shot 2024-04-08 at 6 27 36 AM](https://github.com/osxfuse/osxfuse/assets/66917489/2b3f0e4e-42bc-4650-a69c-4a0f11230c3a)
I'm not going to wipe my OS just for Macfuse ! Come on use some logic here. OS is running fine for years, obviously you don't want to dig deep enough to Solve this bug. I have log files just ask which ones you want.

AND as for Linux ?!! LOL Which one ? The answer is very simple OSX has everything i use and need where all these linux flavors offer me nothing and lack support for everything i need. 
You must be just browsing websites and check your email which is perfectly fine for any linux flavor. Oh ya and they have DOOM i hear 😂

**Comment by bfleischer** [comment]
@VaZ420 The installer app is a macOS component and the validation step is an automated process handled by the installer app. As a developer, when building an installer package you use a macOS tool and point it to a set of files that you want to package. This tool then builds the installer package which contains an archive of the files that should be installed and some meta information. As a developer I have no way to intervene in the validation step of the installation process. That's why I pointed out that the issue is most likely caused by something on your Mac. If there is a bug, it's most likely a macOS bug, not a macFUSE bug. There have not been any reports like yours for recent versions of macOS and I have not been able to reproduce the issue.

> Come on use some logic here. OS is running fine for years, obviously you don't want to dig deep enough to Solve this bug. I have log files just ask which ones you want.

Let's use some logic then ... Trying to solve an isolated issue on an outdated version of macOS that is most likely a macOS or installer app bug is not good use of my time. macOS Mojave has a market share of less than 1% and, judging from the bug reports I received, the issue you are running into only affected an extremely low number of Mojave users. Logic dictates to devote my time to issues that affect more users. I have no interest in "digging deep" four years after the issue was raised on a now outdated version of macOS when there is a known workaround (reinstalling macOS).
