### ISSUE TITLE
Help - using a larger iosize

### ISSUE THREAD

**Issue by ivancitin** [osxfuse/osxfuse#507]
Hello,

I was wondering if anyone could help me in figuring out how to get better write performance, basically being able to use a larger `iosize`. I have tried setting it to the maximum `32 MB` but the maximum i can see being used is `131072`. I'm setting `st_blksize = 0` in the `stat` in both the `getattr` and the `fgetattr`.

I'm mounting using `fuse_main(...)` with this arguments:
```
argv[0]='<path to the app>'
argv[1]='<mounting point>'
argv[2]='-ovolname=<name>'
argv[3]='-odaemon_timeout=1800'
argv[4]='-onoappledouble'
argv[5]='-olocal'
argv[6]='-onoubc'
argv[7]='-oiosize=33554432'
argv[8]='-odefault_permissions'
```

Anyone has an idea of what mount [options](https://github.com/osxfuse/osxfuse/wiki/Mount-options) are preventing me from getting a higher write size, or what option i'm missing?

I'm using [osxfuse-3.7.1](https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.7.1)

To be precise, there is an initial write with a higher size, but all the followed ones comes with `131072`, something like:
```
sample_callback_write: path='<path>', size='8388608', offset='0'
sample_callback_write: path='<path>', size='131072', offset='8388608'
sample_callback_write: path='<path>', size='131072', offset='8519680'
...
sample_callback_write: path='<path>', size='131072', offset='17170432'
sample_callback_write: path='<path>', size='106496', offset='17301504'
sample_callback_write: path='<path>', size='2366', offset='17408000'
```

**Comment by DigitalGuardianDev** [comment]
Hi Ivan,

I'm also facing the same issue and wondering if you found any workaround.

**Comment by misku** [comment]
Hi guys, did you try setting a larger `blocksize`, e.g. `blocksize=32768`?

**Comment by DigitalGuardianDev** [comment]
Thanks Misku, the blocksize helped to increase the write speed upto 1MB per block.
