### ISSUE TITLE
I'm not able to compile under macOS10.14 with Xcode10 - Beta

### ISSUE THREAD

**Issue by puhtaytow** [osxfuse/osxfuse#509]
I'm not able to compile due to:

`Assertion 'common_is_variable DEFAULT_SDK_10_14_ARCHITECURES' failed
at common_variable_clone (./build.d/lib/common.sh, line 501)
at common_variable_clone (./build.d/lib/common.sh, line 514)
at build_target_invoke (./build.sh, line 656)
at build_main (./build.sh, line 942)
at main (./build.sh, line 950)`

**Comment by DJBenson** [comment]
Same here - exactly the same error message.

EDIT: Did you check out the support/osxfuse-3 branch as master doesn't have the 10.14 changes. I cloned support/osxfuse-3 and got an error about SDK 10.5 not being available so I edited build.d/targets/release.sh and replaced 10.5 with 10.14 and also added 10.14 into the case statement further down and got a bit further - I still get a build failure on fsbundle though.

./build.sh -t fsbundle
T:fsbundle           | Clean target
T:fsbundle           | Build target for macOS 10.14
T:fsbundle           | Failed to build target
Terminated: 15

(p.s. I am not a developer, I am someone who likes to (try to) problem solve so the changes I made could be completely wrong!)

**Comment by puhtaytow** [comment]
Hi DJBenson,

I think it won't work as since 10.5 there was a lot of heavy changes under macOS (previously OS X) hood, and to what I know Fuse needs custom kernel modules (KEXT) which probably won't work at all.

PS. I'm trying to trick it as well :) so far without luck.

**Comment by lungj** [comment]
If you compile with verbosity at level 9, you'll get a lot of useful error messages:
`./build.sh -t distribution -v 9`
You should then remove `i386` from from the list of architectures to build for in `build.d/defaults.sh` for `DEFAULT_SDK_10_14_ARCHITECURES`.

A bunch of headers also use system header angle brackets instead of double quotes. When you compile, the compiler will tell you what to fix.

Next, you'll run into a problem with `libclang.dylib`. It's not in the expected place.
`sudo ln -s /Applications/Xcode-beta.app/Contents/Frameworks/libclang.dylib /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.14.xctoolchain/usr/lib`
See: https://trac.macports.org/ticket/54939 for details.

That'll let you compile. Unfortunately, I'm not sure if everything works after that.

**Comment by warrentheranga** [comment]
Did you create the symlink like this:
cd /Applications/Xcode.app/Contents/Developer/Toolchains
sudo ln -s XcodeDefault.xctoolchain OSX10.14.xctoolchain

Otherwise where are you getting the OSX10.14.xctoolchain from?

Thank you

**Comment by dannote** [comment]
@warrentheranga In this case I get the following errors:
```
2018-06-08 14:13:24.579 XCBBuildService[34124:317622] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain: error: failed to load toolchain: toolchain 'com.apple.dt.toolchain.XcodeDefault' already registered from /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.14.xctoolchain
2018-06-08 14:13:24.836 XCBBuildService[34124:317622] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain: error: failed to load toolchain: toolchain 'com.apple.dt.toolchain.XcodeDefault' already registered from /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.14.xctoolchain
2018-06-08 14:13:25.063 XCBBuildService[34124:317622] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain: error: failed to load toolchain: toolchain 'com.apple.dt.toolchain.XcodeDefault' already registered from /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.14.xctoolchain
2018-06-08 14:13:25.307 XCBBuildService[34124:317622] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain: error: failed to load toolchain: toolchain 'com.apple.dt.toolchain.XcodeDefault' already registered from /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.14.xctoolchain
```

**Comment by dannote** [comment]
So I managed to build it successfully by linking `libclang.dylib` as @lungj suggested.

That's what I get now:

```
$ sshfs --version
SSHFS version 2.10
OSXFUSE 3.8.0
FUSE library version: 2.9.7
fuse: no mount point
```

and

```
/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse; echo $?
255
```

**Comment by warrentheranga** [comment]
Actually, are you running Xcode 9.4 as well as the beta?

**Comment by lungj** [comment]
@warrentheranga, I am running only Xcode 10 beta (with command-line tools); I put it in `/Applications/Xcode-beta.app`. My `/Applications/Xcode.app` has no real Xcode. I created the directory to house the symlink using `mkdir -p /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.14.xctoolchain/usr/lib`.

**Comment by warrentheranga** [comment]
That was the missing step, brilliant thank you

**Comment by eskimo** [comment]
If anyone has an error like "error: possibly undefined macro: AM_ICONV" it's related to gettext. I solved it with "brew link gettext --force"

**Comment by lungj** [comment]
@dannote , if you're getting error 255, you may need to disable SIP (System Integrity Protection) by rebooting into recovery mode and running the command from the terminal:

    csrutil disable

SIP prevents unsigned kexts from being loaded, amongst other things, and thus may be preventing your self-compiled osxfuse kext from loading.

**Comment by eskimo** [comment]
Anyone have any luck mounting sshfs? Can't seem to get it going on my end.

**Comment by ghost** [comment]
I was able to build it successfully however when trying to mount a Veracrypt container (which was the whole point) in 10.14, I get "/var/folders/vr/bxpntfsn5c14zd97tkz56mx40000gp/T//.veracrypt_aux_mnt3/control

VeraCrypt::FilesystemPath::GetType:45"

**Comment by bfleischer** [comment]
A few hours ago I have released version 3.8.1, which adds, among other things, experimental support for macOS 10.14. It would be great if you could give it a test drive and let me know if you ran into any issues.

**Comment by warrentheranga** [comment]
Success! mounted the drive on my raspberry pi over ssh. reading and writing fine too

**Comment by DJBenson** [comment]
`The following build commands failed:
	PhaseScriptExecution BridgeSupport\ Metadata /Users/jonathan.thomson/osxfuse/framework/build/OSXFUSE.build/Release/OSXFUSE.build/Script-28D525C40EA8076400B7CF7B.sh`

**Comment by ghost** [comment]
Back with a Veracrypt update, Tried creating a new hidden container and it failed with the same message as above after getting to the end of container creation. I'm not too sure whether to discuss it here or Veracrypt repo

**Comment by lungj** [comment]
I was able to use Veracrypt with branch support/osxfuse-3 commit de73426.

**Comment by Prostak** [comment]
In **MacOS 10.11.6** (which is the latest OS I can install on my box):
while using **veracrypt 1.22**

when using **osxfuse 3.8.1** I get the same "VeraCrypt::FilesystemPath::GetType:45" error as above (similar filename: /var/folders/.../.veracrypt_aux+mnt3/control) - in the end of a container creation.

osxfuse **3.7.1 is OK** with the same OS and veracrypt.

**Comment by GrandM1961** [comment]
I got only one problem with using this osxfuse
xcodebuild: error: 'osxfusefs.xcodeproj' does not exist.

any idea to resolve this?

**Comment by bfleischer** [comment]
For all of you having issues related to VeryCrypt, please contact the VeraCrypt team.

@GrandM1961 Please follow the build instructions to the letter. You probably did not clone the osxfuse repository recursively.
