### ISSUE TITLE
Issues on 10.12.6

### ISSUE THREAD

**Issue by HelmoHass** [osxfuse/osxfuse#511]
had to revert back to 3.8 since with this release disks are not recognized/mounted.

**Comment by bfleischer** [comment]
Which release are you referring to? Version 3.8.2 should be working fine on macOS 10.12.

**Comment by HelmoHass** [comment]
HelmoHass commented on 26 Jun
and 
bfleischer commented 2 days ago
🥇

**Comment by bfleischer** [comment]
No helpful feedback, closed.
