### ISSUE TITLE
Include osxfuse inside my App bundle.

### ISSUE THREAD

**Issue by jedeloya** [osxfuse/osxfuse#512]
Hi.

My question is more about support services for enterprises, can you please send me information about that?

We are working on a solution that will use osxfuse to make a filesystem. And we have some doubts about the distribution of our app.

What is the best way to distribute our solution? Inside of our app include kext and run an instance of it?, or require to the final user to install osxfuse before installing our solution.

Best Regards

**Comment by gtimmy** [comment]
We've created our own installer which contains osxfuse installer inside and install it by script `sudo installer -pkg {OSXFUSE_INSTALLER} -target / -applyChoiceChangesXML {OSXFUSE_INSTALLER_SETTINGS}`

**Comment by jedeloya** [comment]
Hi.

Thanks a lot, you mean that using something like Whitebox Packages in the before installation scripts, i can run this?

Can you explain the OSXFUSE_INSTALLER_SETTINGS part?

Thanks in advance

**Comment by gtimmy** [comment]
You can modify (enable or disable) installing options (see screenshot) by applying settings file.
<img width="732" alt="screen shot 2018-07-02 at 20 32 25" src="https://user-images.githubusercontent.com/4819559/42177945-41fbd14c-7e37-11e8-9845-dd5bb9f6d6a8.png">

To get options file - run command `installer -pkg {FUSE_INSTALLER_PATH}.pkg -showChoicesXML > {OSXFUSE_INSTALLER_SETTINGS}.plist`. You can modify this file and use in your installing script.

**Comment by jedeloya** [comment]
Hi.

Thanks a lot for your reply, I'm going to test this and post if work for me.

Best Regards.

**Comment by bfleischer** [comment]
Please make sure in your installer that you don't downgrade the current FUSE installation if a newer version of FUSE (than the one you are shipping with your app) is already installed.

**Comment by jedeloya** [comment]
Hi.

How can I check if there is an installed version and wich version is it?
