### ISSUE TITLE
FinderInfo for root directory

### ISSUE THREAD

**Issue by jief666** [osxfuse/osxfuse#513]
Why the extended attribute "com.apple.FinderInfo" is forced for root.
I mean, if there isn't, Fuse will generate one ?

It's annoying for me because it always report syncs as modified. I patched volicon_listxattr to not report "com.apple.FinderInfo" if there isn't. Ans it seems to work. So I wonder if it's shouldn't be removed ?

**Comment by bfleischer** [comment]
com.apple.FinderInfo is required to set the volume icon. Removing it will remove the volume icon.
