### ISSUE TITLE
git clone broken

### ISSUE THREAD

**Issue by jief666** [osxfuse/osxfuse#514]
git clone --recursive -b support/osxfuse-3 git://github.com/osxfuse/osxfuse.git doesn't work :

> Submodule path 'framework': checked out '8b7990632502368c6d93a47f823b4a3b112ce3d3'
Submodule path 'fuse': checked out '5de674354557075bec27e80eaeeac8d4e171f83b'
error: Server does not allow request for unadvertised object 60c55dd9d4f717033943a0127d83b0a10741a404
Fetched in submodule path 'kext', but it did not contain 60c55dd9d4f717033943a0127d83b0a10741a404. Direct fetching of that commit failed.

by the way, which branch should I clone to recompile library to work with packaged version 3.8.0 ?

**Comment by misku** [comment]
I confirm. This `osxfuse` commit: https://github.com/osxfuse/osxfuse/commit/1dc4b528c9fcbbcf1150574bd0ea2d2daf079e00 refers to non-existing commit (`60c55d`) in `kext` submodule: https://github.com/osxfuse/kext/commits/support/osxfuse-3
@bfleischer could you please update `kext` repo? Thanks!

**Comment by bfleischer** [comment]
Thanks, I've pushed the missing commit.

@jief666 Do not recompile libosxfuse. Link against the one in `/usr/local/lib`. If you ship your own version of libosxfuse your file system will break with every new release of FUSE for macOS! If your goal is to prevent your app from crashing on launch (in case FUSE is not installed), then weakly link against libosxfuse. This way your app will launch even if libosxfuse is not installed.

**Comment by jief666** [comment]
I'm recompiling osxfuse because of #513. I wanted to understand and try to remove these fake FinderInfo attribute, to see what happen before reporting.
Thanks.

**Comment by jief666** [comment]
which branch should I clone to recompile the library to work with packaged version 3.8.0 (the one currently installed on my Mac. I can upgrade if needed) ?
