### ISSUE TITLE
No formatting in macOS Mojave

### ISSUE THREAD

**Issue by GrandM1961** [osxfuse/osxfuse#515]
I have installed the latest version of osxfuse and I can read and write to ntfs formatted harddrives, but I cannot reformat it into NTFS. it shows greyed out
![schermafbeelding 2018-07-04 om 18 31 31](https://user-images.githubusercontent.com/19931368/42287869-7cce8e7c-7fb8-11e8-855e-511257a9d903.png)

**Comment by bfleischer** [comment]
Please note that NTFS-3G and FUSE for macOS are independent projects. Should you run into NTFS-3G related issues please post the issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7.

As far as I know you need to use a command line tool that ships with NTFS-3G to re-format volumes.
