### ISSUE TITLE
fuse-ext2: command not found

### ISSUE THREAD

**Issue by habibutsu** [osxfuse/osxfuse#516]
After trying install osxfuse from `osxfuse-3.8.2.dmg` on High Sierra 10.13.4 `fuse-ext2` is not available, besides in the folder `/System/Library/Filesystems` no any new items.

**Comment by ldartez** [comment]
bump...same issue here

**Comment by bfleischer** [comment]
fuse-ext2 is a separate project. As such you need to install fuse-ext2 independently of FUSE.
