### ISSUE TITLE
FUSE invoke [NSNull Length] And [NSNull enumerateByteRangesUsingBlock] on MacOS

### ISSUE THREAD

**Issue by KobeLuo** [osxfuse/osxfuse#517]
FUSE invoke the NSData methods `length` and `enumerateByteRangesUsingBlock`   use NSNull instance, the screenshot as below:
![screen shot 2018-07-11 at 11 08 48 am](https://user-images.githubusercontent.com/26185543/42548841-be930e8a-84fb-11e8-9abf-98c3b05a39f4.png)

And I did check my code carefully, all of the funcs parameters in  fuseloopInvoke did check, could you help me.

Environment:
Mac OS X 10.13.3 (17D47)
OSX FUSE 3.8.0
Xcode 9.0

**Comment by KobeLuo** [comment]
Has anyone encountered this problem?

**Comment by bfleischer** [comment]
Have you figured out the issue in the meantime? I don't think FUSE is to blame for this. The framework never calls `enumerateByteRangesUsingBlock`.

**Comment by KobeLuo** [comment]
@bfleischer  I added one NSNull extension to avoid this kind of logs as following code: 
```
@implementation NSNull (Ext)

- (NSInteger)length { return 0; }
- (void)enumerateByteRangesUsingBlock:(NSNullExceptionInvoke)invoke {
    
//    NSLog(@"dddd");
}
@end
```
I didn't understand why this function invoke will only happens on xcode9?

## The another important question is:  
Could i have any measure to debug the osxfuse code on xcode instead use FUSE library?  Our team made one virtual disk and data sync from our server base on OSXFUSE library, but when the microsoft office software edit some  files, fuse always invoke open/release so many times and it looks like meanless,we need improve the edit speed, i want to know the true reason.
