### ISSUE TITLE
Problem with installer

### ISSUE THREAD

**Issue by jedeloya** [osxfuse/osxfuse#521]
Hi, I have tried to run installer from a script as you told me on another issue, I used this  command to get the options file: 

installer -pkg {FUSE_INSTALLER_PATH}.pkg -showChoicesXML > {OSXFUSE_INSTALLER_SETTINGS}.plist

After I ran the next script using generated options file:

sudo installer -pkg {OSXFUSE_INSTALLER} -target / -applyChoiceChangesXML {OSXFUSE_INSTALLER_SETTINGS}

But I get this error message:

installer: Package name is FUSE for macOS
installer: choices file 'settings.plist' either could not be found or was malformed

could you please help me?

Thanks in advance

**Comment by jedeloya** [comment]
Other question, how can I check for installed Fuse version? This is for not to downgrade an installed fuse distribution.

Best Regards.

**Comment by bfleischer** [comment]
Sorry for not replying earlier. I'm assuming by now you've found a solution.
