### ISSUE TITLE
"installer -package" command not working on OSX on 10.14 beta 4 

### ISSUE THREAD

**Issue by hrishi3390** [osxfuse/osxfuse#522]
sudo installer -package ~/Downloads/osxfuse-3.8.2.pkg  -target /

Above command giving below error on mac 10.14 beta 4
installer: Error - the package path specified was invalid: '~/Downloads/osxfuse-3.8.2.pkg'

**Comment by kainjow** [comment]
Apparently you're giving it a path that doesn't exist. It's not a fuse issue.

Does `osxfuse-3.8.2.pkg` exist inside your Downloads folder?

**Comment by hrishi3390** [comment]
I run same command with 3.7.1 osxfuse..it works file. But does not run with osxfuse-3.8.2.pkg
Yes. osxfuse-3.8.2.pkg exists inside Downloads folder

**Comment by hrishi3390** [comment]
It is having problem when run silently on terminal. Do we have way to install osxfuse-3.8.2.dmg silently. again attaching command to reproduce the issue
$installer -package ~/Downloads/osxfuse-3.8.2.dmg -target /
$installer: Error - the package path specified was invalid: '/Users/dguser/Downloads/osxfuse-3.8.2.dmg'.

**Comment by bfleischer** [comment]
No wonder that it does not work. osxfuse-3.8.2.dmg is a disk image! You need to run the installer command with the actual installer package as argument.

**Comment by hrishi3390** [comment]
So dont we have any option to install osxfuse silently ??

**Comment by bfleischer** [comment]
You can install FUSE silently, but you need to call the installer command on the actual installer package from the dmg file, not the dmg file itself. The dmg file is not a valid installer package. That's what the installer command is trying to tell you.

> $installer: Error - the package path specified was invalid: '/Users/dguser/Downloads/osxfuse-3.8.2.dmg'.

A dmg file is a disk image, a virtual disk so to speak, and not an installer package, that can be installed.
