### ISSUE TITLE
Prompts for password more than 20 times

### ISSUE THREAD

**Issue by sbruzzone** [osxfuse/osxfuse#527]
Hi, I'm trying to uninstall osxfuse with the following:
brew cask uninstall osxfuse
then this happens:
Uninstalling Cask osxfuse
==> Running uninstall process for osxfuse; your password may be necessary
==> Unloading kernel extension com.github.osxfuse.filesystems.osxfusefs
Password:
Password:
==> Uninstalling packages:
com.github.osxfuse.pkg.Core
Password:
Password:
Password:
Password:
Password:
Password:
Password:
Password:
Password:
Password:
Password: 
..
..
I stopped counting at 30
Is this something reasonable?
Thanks
Sebastian

**Comment by bfleischer** [comment]
Please contact the Homebrew team. Installing (and uninstalling) FUSE via Homebrew is not officially supported by the FUSE for macOS project. However, the Homebrew maintainer who is responsible for the osxfuse cask, might be able to help you.
