### ISSUE TITLE
milestones

### ISSUE THREAD

**Issue by ThomasWaldmann** [osxfuse/osxfuse#528]
https://github.com/osxfuse/osxfuse/milestones these look a bit strange:
- most of these (100%) milestones should be closed (as they are done and released)
- the ones that are not yet 100% done, but a release has been made already point to some problem (either an issue was not closed although it has been fixed or an issue planned to get fixed for that milestone wasn't fixed for that milestone and should be moved to another milestone now)
- a 3.8.3 milestone is missing

The reason why I was looking there was to determine whether 3.8.3 release might be in the very near future.

**Comment by bfleischer** [comment]
I've cleaned up the milestones.
