### ISSUE TITLE
Sparse files no longer work

### ISSUE THREAD

**Issue by vasi-stripe** [osxfuse/osxfuse#530]
I've tried returning an `st_blocks` field different from `st_size / 512`, and it doesn't seem to affect anything. This is true even with `-o sparse` passed as an option.

I've verified that this is also the case when using the `ufs` example filesystem, even though it seems to support sparse mode: https://github.com/osxfuse/filesystems/blob/master/filesystems-c/unixfs/ufs/ufs_mainx.c#L98 . There's also an historical commit that implies this once worked: https://github.com/osxfuse/kext/commit/a92433ba3902e3f8990b08c524219da6dfa0deb3

I'm using osxfuse 3.8.0 on macOS 10.13.3

**Comment by bfleischer** [comment]
Is this still an issue with the latest version of macFUSE?
