### ISSUE TITLE
statfs_x: what values to use for statfs::f_flags, statfs::f_type and statfs::f_fsubtype?

### ISSUE THREAD

**Issue by kiril-kirov** [osxfuse/osxfuse#531]
I'm currently implementing a callback for `statfs_x`. I can fill almost all fields (I think) appropriately, but I have no idea what values to use for the the fields above.

`man statfs` gives *some* possible flags, but says nothing about type/subtype.

I took a look at `::statfs("/"...)`, nothing really interesting came out.

I guess all three fields can be set to 0?
I wonder if this can break something that's not obvious.

Also `diskutil info` on my mountpoint says `Could not find disk: <path>`. I see that this invokes my callback, so I believe I've set something wrong. Any help?

Thanks a lot, 
Kiril

**Comment by bfleischer** [comment]
`f_flags`, `f_type` and `f_fsubtype` are ignored. `f_fsubtype` is set at mount time.

See https://github.com/macfuse/library/blob/master/lib/fuse_lowlevel.c#L355 for a list of relevant fields. Everything else from `struct statfs` is ignored.
