### ISSUE TITLE
Root-changed mount tool, NTFS still cannot be written.

### ISSUE THREAD

**Issue by TiansuYu** [osxfuse/osxfuse#534]
I have followed the instructions on this website (downloaded rtfs-3g from brew, and changed the OS mount-tool with ntfs-3g-tool in recovery mode), however the NTFS disk could not be written. 

In recovery mode, the two
`sudo mv "/Volumes/Macintosh HD/sbin/mount_ntfs" "/Volumes/Macintosh HD/sbin/mount_ntfs.orig"
sudo ln -s /usr/local/sbin/mount_ntfs "/Volumes/Macintosh HD/sbin/mount_ntfs"`
lines has been delivered, but no info returned. 

Restart entering the NTFS drive, it cannot be written. 

So I tried manually mount the volumes, using `sudo /usr/local/bin/ntfs-3g /dev/disk3s1 /Volumes/NTFS -olocal -oallow_other`, the terminal says the "command not found". 

I am guessing this is because the rtfs-3g is not properly installed, but I am not sure. 

The second guess is that the disk is a little dirty due to inappropriate use on wins, so I tried to run `rtfsfix`, but the command is also not found. 

Anyone cares to share some opinion on this issue?

**Comment by yurikoles** [comment]
>"command not found"
@Miraclei you had moved the binary, just run `brew reinstall ntfs-3g`.

**Comment by TiansuYu** [comment]
I tried, but this is still not working. 

Reinstall:
`Tiansus-MacBook-Pro:~ tiansuyu$ brew reinstall ntfs-3g`
`==> Reinstalling ntfs-3g `
`==> Downloading https://homebrew.bintray.com/bottles/ntfs-3g-2017.3.23.high_sier
Already downloaded: /Users/tiansuyu/Library/Caches/Homebrew/ntfs-3g -2017.3.23.high_sierra.bottle.tar.gz`
`==> Pouring ntfs-3g--2017.3.23.high_sierra.bottle.tar.gz`
`🍺  /usr/local/Cellar/ntfs-3g/2017.3.23: 89 files, 1.7MB`

Try the manually mount:
`Tiansus-MacBook-Pro:~ tiansuyu$ sudo /usr/local/Celler/ntfs-3g /dev/disk2s1 /Volumes/NTFS -olocal -oallow_other `
`Password:`
`sudo: /usr/local/Celler/ntfs-3g: command not found`

change `celler` back to `bin`:
`Tiansus-MacBook-Pro:~ tiansuyu$ sudo /usr/local/bin/ntfs_3g /dev/disk2s1 /Volumes/NTFS -olocal -oallow_other `
`sudo: /usr/local/bin/ntfs_3g: command not found`

**Comment by yurikoles** [comment]
Please try to use just `ntfs-3g` command without path.

**Comment by TiansuYu** [comment]
Thanks, @yurikoles a lot. It worked, but the system says I'm a unprivileged user, thus cannot mount. 
`tiansuyu$ ntfs-3g /dev/disk2s1 /Volumes/NTFS -olocal -ooallow_other`
`Unprivileged user can not mount NTFS block devices using the external FUSE
library. Either mount the volume as root, or rebuild NTFS-3G with integrated
FUSE support and make it setuid root. Please see more information at
http://tuxera.com/community/ntfs-3g-faq/#unprivileged`

Does this means I have to go back to recovery mode, move the binary like before? Or set the `setuid root`? But how?

**Comment by bfleischer** [comment]
@Miraclei Mounting a NTFS-3G file system requires root permissions. This means you need to call the ntfs-3g command with sudo:

`sudo ntfs-3g /dev/disk2s1 /Volumes/NTFS -olocal -ooallow_other`

**Comment by TiansuYu** [comment]
@bfleischer Thanks, that's exactly what I had done, but clearly not working. I actually gave up on editing my NTFS drives. And I am attributing this to my own physiological electro-magenetic field that I am a living computer Reissner-Nordström black hole. (which, in a large part explains everything going on with every generation of my laptop) :) You can close this up. 👍
