### ISSUE TITLE
Help - Building from source

### ISSUE THREAD

**Issue by ivancitin** [osxfuse/osxfuse#535]
Hello, i'm trying to build from source, in a Mac 10.12, the build succeed, but when i try to install the created Distribution, i get the error that the package is not compatible, if i install only the generated Core package, it does install, but when it's used i get the error that the installed version of fuse is too old.

Can someone please help me with the build options, i basically want an installation able to work from Mac 10.11 -> Mac 10.14.

Just using `./build.sh -v 5 -t distribution` doesn't create a distribution i can install in the Mac 10.12 i'm building the source code on.

I'm building in a Mac 10.12 with Xcode 9.2, i checked the source from the `3.8.2` release tag.

Any help appreciated, thanks

**Comment by bfleischer** [comment]
Please use the official installer package instead of distribution your own FUSE builds. Shipping custom builds will most likely cause issues and makes debugging crashes virtually impossible for me. Can you elaborate why you need custom builds?

**Comment by ivancitin** [comment]
Hello Benjamin,

Appreciate taking the time yourself to directly respond, I was mostly interested for my personal testing (kind of a hobby) to avoid conflicts with other newer or older versions, but i desisted. Sorry for inconveniences. Your work with this project is really appreciated.
