### ISSUE TITLE
Reboot Causes FUSE Devices to Disappear

### ISSUE THREAD

**Issue by jdgiotta** [osxfuse/osxfuse#540]
There maybe a way to resolve this that I can't find in the docs/wiki, but whenever I reboot my machine the /dev/osxfuse* devices disappear.

The only way I can get them back is to re-install.

**Comment by sebsto** [comment]
I observed the same on Mojave.  10.14.0

**Comment by bfleischer** [comment]
The FUSE kernel extension is loaded when the first FUSE file system is mounted. As such it is not loaded automatically after reboots. This means the /dev/osxfuse* devices are not available until you mount the first file system.

To load the FUSE kernel extension manually call `/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse`.
