### ISSUE TITLE
Unsupported macOS Version

### ISSUE THREAD

**Issue by liujianqiao** [osxfuse/osxfuse#541]
After I upgrade to the latest macOS (Mojave Version 10.14), the osxfuse refuses to work properly.
There is a pop-up window saying "Unsupported macOS Version: The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS."

**Comment by bfleischer** [comment]
Please follow the instructions and install the latest version of FUSE and you should be fine.
