### ISSUE TITLE
Building Macports version of osxfuse/sshfs fails for 10.13.2

### ISSUE THREAD

**Issue by dkbarto** [osxfuse/osxfuse#543]
The tail of the log file shows the fault.

Using MacOS
	10.13.6

Xcode
	10.0 (10A255)

Clang
	Apple LLVM version 10.0.0 (clang-1000.11.45.2)
	Target: x86_64-apple-darwin17.7.0
	Thread model: posix
	InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-19b3fb7" && ./build.sh -t packagemanager -a build -v 5 --build-directory="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/work" -- -a x86_64 --framework-prefix="/opt/local" --fsbundle-prefix="/opt/local" --library-prefix="/opt/local" 
DEFAULT_BUILD_CONFIGURATION=Release
DEFAULT_BUILD_DIRECTORY=/tmp/osxfuse
DEFAULT_LOG_VERBOSE=2
DEFAULT_PREFIX=''
DEFAULT_SDK=10.13
DEFAULT_SDK_10_10_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_10_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_11_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_11_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_12_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_12_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_13_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_13_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_5_ARCHITECURES=([0]=ppc [1]=ppc64 [2]=i386 [3]=x86_64)
DEFAULT_SDK_10_5_COMPILER=4.2
DEFAULT_SDK_10_6_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_6_COMPILER=com.apple.compilers.llvmgcc42
DEFAULT_SDK_10_7_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_7_COMPILER=com.apple.compilers.llvmgcc42
DEFAULT_SDK_10_8_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_8_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_10_9_ARCHITECURES=([0]=i386 [1]=x86_64)
DEFAULT_SDK_10_9_COMPILER=com.apple.compilers.llvm.clang.1_0
DEFAULT_SDK_SUPPORTED=([0]=10.5 [1]=10.6 [2]=10.7 [3]=10.8 [4]=10.9 [5]=10.10 [6]=10.11 [7]=10.12 [8]=10.13)
DEFAULT_SOURCE_DIRECTORY=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-19b3fb7
BUILD_SOURCE_DIRECTORY=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/work/osxfuse-osxfuse-19b3fb7
BUILD_BUILD_DIRECTORY=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/work
Search for Xcode
Xcode 10.0 found at path '/Applications/Xcode.app/Contents/Developer'
XCODE_10_0_PATH=/Applications/Xcode.app/Contents/Developer
XCODE_INSTALLED=([0]=10.0)
XCODE_SDK_10_14_XCODE=([0]=10.0)
XCODE_SDK_INSTALLED=([0]=10.14)
Done searching for Xcode
Falling back to macOS 10.14 SDK as default SDK
Source extension osxfuse
Assertion 'common_is_variable DEFAULT_SDK_10_14_ARCHITECURES' failed
at common_variable_clone (./build.d/lib/common.sh, line 501)
at common_variable_clone (./build.d/lib/common.sh, line 514)
at build_target_invoke (./build.sh, line 656)
at build_main (./build.sh, line 942)
at main (./build.sh, line 950)
Terminated: 15
Received signal: SIGTERM

**Comment by yurikoles** [comment]
I think this should be reported downstream to macports.

**Comment by dkbarto** [comment]
MacPorts says that since no updates have appeared there for over a year, that the port is no longer ‘maintained’ and should be reported upstream.

Apparently no one wants this information.

	David

**Comment by bfleischer** [comment]
I don‘t know who maintains the osxfuse MacPorts port, but FUSE for macOS 3.8.2 is compatible with Mojave. Updating the port should be all that is needed. I‘m sorry, but there is nothing I can do. This is clearly a MacPorts issue.

I recommend using the official FUSE installer instead of MacPorts.
