### ISSUE TITLE
Heads up/warning: BridgeSupport doesn't seem to compile on Mojave

### ISSUE THREAD

**Issue by amirrajan** [osxfuse/osxfuse#544]
Just a heads up (I know at least indirectly y'all rely on BridgeSupport). It looks like `gen_bridge_metadata` segfaults using system Ruby. There was a workaround where using ruby `2.3.7` wouldn't cause the segfault, but that doesn't seem to work either now. Compiling BridgeSupport from source also fails.

This is a reference to BridgeSupport targeting clang 7.0: https://github.com/hipbyte/bridgesupport

**Comment by amirrajan** [comment]
Using this older fork does work: https://github.com/amirrajan/BridgeSupport

**Comment by amirrajan** [comment]
Currently, you'll get the following error if you try to execute `gen_bridge_metadata`:

```
dependent dylib '@rpath/libclang.dylib' not found for '/System/Library/BridgeSupport/ruby-2.3/bridgesupportparser.bundle'
```

I haven't tried it yet, but I'm assuming the symlink fix detailed here will work for Mojave too: 

https://trac.macports.org/ticket/54939

Specifically:

```
cd /Applications/Xcode.app/Contents/Developer/Toolchains
sudo ln -s XcodeDefault.xctoolchain OSX10.13.xctoolchain
```

Except maybe changing it to `OSX10.14.xctoolchain`. Will update once I verify this workaround works.

Edit:

The `OSX10.14.xctoolchain` workaround didn't work, but it seems this does (along with a full compile of BridgeSupport on Mojave):

```
sudo mkdir -p /usr/local/lib/
sudo ln -s "$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib" /usr/local/lib/
```

**Comment by amirrajan** [comment]
Related: https://github.com/amirrajan/rubymotion-applied/issues/106

**Comment by amirrajan** [comment]
One of my colleagues built the following on his Mojave machine:

https://www.dropbox.com/s/ixryj9ne9o7c83h/bridge_support_2.tgz?dl=0

The binaries above plus the following line fixed BridgeSupport on Mojave:

```
sudo mkdir -p /usr/local/lib/
sudo ln -s "$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib" /usr/local/lib/
```

The binaries were compiled off of this repo: https://github.com/amirrajan/BridgeSupport

To clarify, I'm not sure how much this will help y'all. But in the past, we've both (RubyMotion and osxfuse) have similar problems/needs with regards to BridgeSupport. So at a minimum, this legwork may help y'all!

**Comment by amirrajan** [comment]
More updates. **Mojave's system Ruby is _definitely_ broken.** Here are the steps to recreate along with information: https://github.com/amirrajan/RubyMotionBridgeSupport/issues/1

**Comment by amirrajan** [comment]
This is the fix: https://github.com/amirrajan/RubyMotionBridgeSupport/commit/4b821d3756d2b40c739f1d40a785e3165566e573

**Comment by rh314** [comment]
> This is the fix: [amirrajan/RubyMotionBridgeSupport@4b821d3](https://github.com/amirrajan/RubyMotionBridgeSupport/commit/4b821d3756d2b40c739f1d40a785e3165566e573)

404 at the moment 😢

**Comment by amirrajan** [comment]
@rh314 It's been moved to http://github.com/amirrajan/rubymotion-bridgesupport.

I'm almost done with Catalina fixes ^_^

**Comment by rh314** [comment]
> @rh314 It's been moved to [http://github.com/amirrajan/rubymotion-bridgesupport](https://github.com/amirrajan/rubymotion-bridgesupport).
> 
> I'm almost done with Catalina fixes ^_^

Thank you so much! 😄

**Comment by amirrajan** [comment]
@rh314 : https://github.com/osxfuse/osxfuse/issues/646
