### ISSUE TITLE
Using Fuse with pCloud Client prevents OS X simple restart or shutdown

### ISSUE THREAD

**Issue by ppharrington** [osxfuse/osxfuse#545]
I'm not convince that it comes from pCloud client, bit I've reported to them anyway. On every computer with these active on it, the usual shutting down or restarting of the computer mostly often fails and I have to use Terminal to shut down or restart the computer.
This issue has always been there since pCloud client v3.5.9 (and fuse 3.6) and from OS X Sierra to Mojave, no matter which computer.
I was wondering if some similar issue was known and if there might be hints about what to do then.
Thanks for your attention.

**Comment by OfficerPlod** [comment]
I've also been using pCloud since v3.5.9 and gone through various versions, including Fuse upgrades and never had this problem. I'm still running High Sierra.
My issue has always been pCloud not mounting after a restart. I have to log in and out a few times before it mounts or, at worse, reinstall pCloud!
Sounds like we both have problems - just totally different problems. 
I run a 'blessed' User Folder on a separate HDD, so dunno if that makes any difference.

**Comment by TheGauge** [comment]
I'm also experiencing this issue on two separate MacBooks, one with a vanilla Mojave install, the other upgraded from High Sierra.  They have very little common software installed on them but they do have FUSE for macOS (v3.8.2) and pCloud Drive (now v3.7.7) installed.

Often when I shut down the computers the menu bar disappears but the desktop and dock remain and nothing happens.  I can still launch applications (which causes the menu bar to reappear) but further attempts to shut down do nothing.  The only successful way to turn off or restart is to open a terminal and sudo shutdown -h now.

Are there any logs or diagnostics that can be run for FUSE that might shed some light on this?

**Comment by Dauphin38** [comment]
Finder crash with 3.8.3 and Mojave bêta 10.14.4 (18E205e) and Cloud 3.7.9

**Comment by exiledpoacher** [comment]
Upgraded FUSE to v3.8.3 (including MacFUSE compatibility layer) with pCloud 3.8 and macos 10.11.6 (El Capitan) on my MacBook 5.2 (White 2009 model) seems to have solved the shutdown/restart problem discussed above.

**Comment by bfleischer** [comment]
This ticket has been inactive for years, so I'm closing it. Should you run into similar issues using the latest version of macFUSE, feel free to open a new ticket.
