### ISSUE TITLE
FUSE 3.8.2 not working with LaCie Private-Public on OSX Mojave

### ISSUE THREAD

**Issue by jotlord5** [osxfuse/osxfuse#547]
Hi,

I can't access my Private-Public partition anymore on my LaCie Porsche's design disks. I keep getting the error message that Fuse needs to be installed and that it could not be installed correctly. However, I am running version 3.8.2.

I tried to uninstall and reinstall but it won't work. Could anyone help please?

**Comment by mcolburn** [comment]
I also have the same problem.

**Comment by bfleischer** [comment]
Please report the issue to LaCie. FUSE 3.8.2 works fine on Mojave. This is something the LaCie team needs to look into.
