### ISSUE TITLE
Microsoft Word not working in a FUSE drive

### ISSUE THREAD

**Issue by ivancitin** [osxfuse/osxfuse#548]
Hi,

I found a weird behavior with Microsoft Word and a FUSE drive. Steps to reproduce it:
-  Open Word, version 16.16.2 (180910)
- Start from a blank document and type something
- Hit the close x
- Select to save the document into the FUSE drive

The document should be saved and Word closed, but instead, something happen in the save, it fails and Word comes back, only and empty file is created. I looked into the callback received and the only write operation i saw was the single create file.

This is odd, i'm not able to find what exactly is failing, i tested this with the Loopback FS, with both Fuse 3.7.1 and 3.8.2, in both Mac Sierra and Hight Sierra.

Is anyone else able to reproduce this, any hint on what the issue could be?

Interestingly, if instead of hitting the close button, the save button is hit, everything works as expected. Something is preventing Word save behavior from working when instead of hitting save, you hit close and then choose to save.

Any help appreciated, thank you.

**Comment by yingbo** [comment]
Reproduced the error. macOS Mojave 10.14.2, word 181208, fuse 3.8.2.

**Comment by karanambhanu** [comment]
It happens with Mac OS High Sierra and Mojave. At certain times I am able to open a word/excel document in fuse mounted folder. But some times, the word /excel document does not open and shows a pop up saying  " Word experienced an error trying to open the file.Try these suggestions
* check the file permissions for the document or drive
* Make sure there is sufficient free memory and disk space.
* Open the file in Text Recovery Coverter".

This happens randomly and happens to only few files not for all Microsoft Word files.

It's a big help if some one can share some inputs on resolving this issue.

**Comment by AdithyaURRao** [comment]
Even i am facing same issue. Even if you try to modify a word/excel file same issue occurs all the time in FUSE mounted folder. 
Any resolution for this ?

**Comment by karanambhanu** [comment]
I haven't make it to work so far. Not sure if this is something related to Microsoft office package not supporting the files in a mounted folder.??

**Comment by legsak1mbo** [comment]
We've seen the same here. But we also see this behaviour with Word on an SMB share mounted via Cmd+K in the Finder so I would suggest that it's actually a Word bug.

**Comment by bfleischer** [comment]
This ticket has been inactive for a long time, so I'm closing it. Feel free to open a new ticket in case you still run into this issue with the latest versions of macFUSE and Word.
