### ISSUE TITLE
File system unmounts, gives error "no path for address"

### ISSUE THREAD

**Issue by radupopescu** [osxfuse/osxfuse#549]
Hello,

I'm one of the developers of CernVM-FS, a read-only file system based on FUSE, used for software distribution (https://github.com/cvmfs/cvmfs).

A user is experiencing a strange problem on a couple of older Mac mini machines with magnetic (non-fusion storage). He is running OSXFUSE 3.8.2 and CernVM-FS.
At a certain point, under load, CernVM-FS becomes unmounted on these machines. The mountpoint is unusable, although it still shows up in the output of the `mount` command.
The message "no path for address" shows up in error logs.

I should mention that CernVM-FS is used in production at the CERN since many years, both on Linux and Mac. I know it's basically impossible to diagnose the problem with the limited information provided here, but we haven't been able to reproduce the user's problem on our own machines.

I'm writing hoping that the specific error message "no path for address" rings a bell. Any ideas?

Many thanks!

**Comment by bfleischer** [comment]
I'm sorry for the late reply and that I cannot be of more help, but I have no idea where the "no path for address" could be coming from. All I can say is that FUSE volumes will be unmounted automatically on macOS in case the file system daemon becomes unresponsive for 60 seconds (default value). This time limit can be increased to up to 600 seconds. I don't know your specific file system but if it involves requests on a slow network this might be the reason for the unmounts.
