### ISSUE TITLE
remote folder accessible in finder but not through terminal

### ISSUE THREAD

**Issue by shubham-prasad** [osxfuse/osxfuse#554]
<img width="1280" alt="screenshot 2018-11-10 at 8 56 21 pm" src="https://user-images.githubusercontent.com/6239536/48303025-244a3e80-e52b-11e8-8622-cb6ee8f02f69.png">

command used
sshfs Dan@192.168.11.108:/ ~/danny -ovolname=Dan -o defer_permissions

shubhams-MacBook-Pro:~ shubham$ uname -a
Darwin shubhams-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

shubhams-MacBook-Pro:~ shubham$ sshfs --version
SSHFS version 2.10
OSXFUSE 3.8.2
FUSE library version: 2.9.7
fuse: no mount point

**Comment by bfleischer** [comment]
This ticket has been inactive for a long time, so I'm closing it. Feel free to re-open it in case this is still an issue.
