### ISSUE TITLE
MacFUSE compatibility layer

### ISSUE THREAD

**Issue by siftuser** [osxfuse/osxfuse#555]
I enabled  "MacFUSE compatibility layer". Also restarted the system. 

When I run `ls -lh /usr/local/include/macfuse*`, it shows `No such file or directory`

Is there any other way to confirm this feature is installed ? Thanks!

**Comment by bfleischer** [comment]
Check /usr/local/lib. If you find libfuse.dylib then the compatibility layer is installed.
