### ISSUE TITLE
 osxfuse-3.8.2.dmg installation fails on latest macOS.

### ISSUE THREAD

**Issue by wang3t** [osxfuse/osxfuse#559]
1. Download "osxfuse-3.8.2.dmg" and 
2. tried to install to latest macOS,
3. It fails with "The FUSE for macOS installation package is not compatible with this version of macOS."

**Comment by daynaskully** [comment]
+1

**Comment by bfleischer** [comment]
Version 3.8.2 works fine on macOS 10.14. Which version of macOS are you using?

**Comment by bfleischer** [comment]
I just checked on macOS 10.14.2. FUSE 3.8.2 can be installed without any issues. Are you using the official installer package?

**Comment by bfleischer** [comment]
No feedback, closed
