### ISSUE TITLE
Mount remote drive that requires VPN to connect

### ISSUE THREAD

**Issue by jaredpz** [osxfuse/osxfuse#560]
Hi all,

I want to mount a drive using sshfs on a server that I use a VPN to connect to.  I have no problem mounting the drive when I'm connected to the VPN, but once I'm off the network the server is no longer available and the drive becomes inaccessible.  After I've disconnected if I try to `ls` the directory where I put the mount it just says "ls .: device not configured" and the mounted drive disappears from Finder (I still see the folder I mounted it to in Terminal, but not Finder).  To get it to work again I have to reconnect to VPN, unmount the location I mounted the drive previously and remount.  Is there a way to get it so that the drive automatically reconnects and remounts when I log back into my VPN?  If I have to remount every time I might as well just us sftp to connect to the drive when I need to, but haveing a mounting solution would be much preferable.

I'm on OSX 10.11.6 and the command I used to mount the drive was:
`sshfs user@server.address:/source/dir/here ~/local_mount -o auto_cache,reconnect,defer_permissions,noappledouble,volname=Local_Name`

Thanks!

**Comment by bfleischer** [comment]
I think this is something that would need to be handled by sshfs, not FUSE. Could you please open an issue in the sshfs issue tracker: https://github.com/libfuse/sshfs/issues
