### ISSUE TITLE
BAD signature from "Benjamin Fleischer <fleiben@gmail.com>" [expired]

### ISSUE THREAD

**Issue by PeterWq** [osxfuse/osxfuse#561]
Hi, getting an error for a signature verification;
Downloaded the next files from the https://github.com/osxfuse/osxfuse/releases:
osxfuse-3.8.2.dmg
osxfuse-3.8.2.sha256
osxfuse-3.8.2.sha256.sig
When trying to verify the signature in terminal:

Downloads >gpg --verify osxfuse-3.8.2.sha256.sig osxfuse-3.8.2.sha256
gpg: Signature made Sun Jul  1 10:03:29 2018 PDT
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: **BAD signature from "Benjamin Fleischer <fleiben@gmail.com>" [expired]**

If I verify the file: osxfuse-3.8.2.sha256 using the OpenPGP: Verify signature of file
getting next error:
Verification FAILED: Signature and data do not match. This could mean the data has been tampered with. (Benjamin Fleischer <fleiben@gmail.com>) (Code: 8)

Any help to get the right signature would be appreciated
Thank you

**Comment by bfleischer** [comment]
The signature is valid, I just checked. The key has been renewed months ago. Please refresh your keys by calling `gpg --refresh-keys`.
