### ISSUE TITLE
Operation not supported on socket Error

### ISSUE THREAD

**Issue by 266918** [osxfuse/osxfuse#563]
MacOS: 10.14.2 (18C54)
ntfs-3g 2017.3.23
mount: sudo /usr/local/bin/ntfs-3g /dev/disk2s1 /Volumes/NTFS -olocal -oallow_other
copy error: could not copy extended attributes to /Volumes/NTFS/test/Transactions.csv: Operation not supported on socket

**Comment by bfleischer** [comment]
Please note that NTFS-3G and FUSE for macOS are independent projects. Should you run into NTFS-3G related issues please post the issues on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7.
