### ISSUE TITLE
readdir is broken in multithread environment

### ISSUE THREAD

**Issue by aleksandr-skobelev-epam** [osxfuse/osxfuse#564]
If we have several concurrent requests for listing of the same directory with a lot of entries in it, and are using readdir in the new mode (i.e are keeping offsets while filling the directory entries) there is a chance that the one of that requests will finish first and the rest ones get incomplete listing.

The reason for this issue seems to be in `fuse_dh.filled` flag that is set to 1 in the begining of the `readdir_fill()` function and set to 0 in the `fill_dir()` callback function for the new mode.

The problem that in the new mode when we finish to fiil the all entries, we usually get at least one more request for `readdir()` in which we don't call the callback function and so we don't reset `filled` flag to zero, so it remains 1. So the other unfinished requests will not call to `readdir_fill()` in `fuse_lib_readdir()` and return an empty buffer instead.

Here the modified version of loopback fs from the filesystems-c folder: 
[loopback.zip](https://github.com/osxfuse/osxfuse/files/2686109/loopback.zip)

It is modified to aget arbitrary root folder and the readdir callbacks also changed to cache previously listed entries (I've failed to get properly working seekdir/telldir/readdir in the multithreading environment).

To run it use something like 
    
     /loopback -f  -oallow_other,native_xattr,volname=LoopbackFS,rootdir=/Users/Shared  /Volumes/loop

Supposing that /Users/Shared contains a folder named "30000" with 30000 items in it, 
run the following script in the Terminal: 

    for i in  {1..2} ; do (ls -l /Volumes/loop/30000/ | wc -l ) & sleep 2 ; done

You may need to tune the sleep delay to encounter the issue: the very short one will let the both requests finish at the same moment, and the very long will run the second request after the first one has finished. On my machine I can reproduce it more or less reliable with delay 1-2 secs.
    
The fix for this issue is to revert setting `filled` flag. I.e we need to set it to `0` in `readdir_fill()` function and set to `1` in `fill_dir` for the old mode:

    diff --git a/lib/fuse.c b/lib/fuse.c
    index d0c0f2e..53645ef 100644
    --- a/lib/fuse.c
    +++ b/lib/fuse.c
    @@ -4018,7 +4018,6 @@ static int fill_dir(void *dh_, const char *name, const struct stat *statp,
     		if (extend_contents(dh, dh->needlen) == -1)
     			return 1;
     
    -		dh->filled = 0;
     		newlen = dh->len +
     			fuse_add_direntry(dh->req, dh->contents + dh->len,
     					  dh->needlen - dh->len, name,
    @@ -4026,6 +4025,7 @@ static int fill_dir(void *dh_, const char *name, const struct stat *statp,
     		if (newlen > dh->needlen)
     			return 1;
     	} else {
    +		dh->filled = 1;
     		newlen = dh->len +
     			fuse_add_direntry(dh->req, NULL, 0, name, NULL, 0);
     		if (extend_contents(dh, newlen) == -1)
    @@ -4055,7 +4055,7 @@ static int readdir_fill(struct fuse *f, fuse_req_t req, fuse_ino_t ino,
     		dh->len = 0;
     		dh->error = 0;
     		dh->needlen = size;
    -		dh->filled = 1;
    +		dh->filled = 0;
     		dh->req = req;
     		fuse_prepare_interrupt(f, req, &d);
     		err = fuse_fs_readdir(f->fs, path, dh, fill_dir, off, fi);

The patch is attached:  [readdir.patch.zip](https://github.com/osxfuse/osxfuse/files/2686157/readdir.patch.zip)

**Comment by bfleischer** [comment]
Thanks. The fix will land in version 4.2.0 as part of the upstream commit https://github.com/osxfuse/fuse/commit/06fc40705f23cb7e9af4df2febae8e6889b1a95d.

The fix exposed a bug in the loopback file system. As a result readdir returns EIO. It took me some time to figure out what's causing readdir to fail.
