### ISSUE TITLE
How to uninstall osxfuse as if it never existed on macOS?

### ISSUE THREAD

**Issue by mixtly87** [osxfuse/osxfuse#565]
The first time you install osxfuse on your machine, you get the 'System Extension Blocked' dialog.

If you uninstall osxfuse and reinstall it, you will never again get the 'System Extension Blocked' dialog.

I would like to bring the system into such state that it shows that dialog so that I need to manually Allow the extension in Security & Privacy options.

Is there a way to do that?

**Comment by ghost** [comment]
"Test User Approval Kernel Extension Loading on mac (TN2459)"
https://stackoverflow.com/a/52888465/1032277
