### ISSUE TITLE
OpenDrive on Mojave: only read operations work.

### ISSUE THREAD

**Issue by keeninter** [osxfuse/osxfuse#566]
After createFileAtPath(),  setAttributes() and writeFileAtPath() do not get called, removeItemAtPath() is called instead. Tested on Mojave (including 10.14.2) with OSXFUSE 3.8.2 and 3.8.3. Surprisingly, on at least one machine everything works fine.

**Comment by bfleischer** [comment]
Please raise this issue with the OpenDrive team.
