### ISSUE TITLE
.fuse_hidden files linger after upgrade to macOS Mojave

### ISSUE THREAD

**Issue by aiasi** [osxfuse/osxfuse#569]
After I upgraded from High Sierra to Mojave, I began noticing the .fuse_hidden files appearing, especially if I open/edit/save a Word file.
I was able to reproduce the problem with the LoopbackFS example program and w/both OSXFUSE 3.8.2 and 3.8.3.

Steps to reproduce:
0) Environment: macOS Mojave 10.14.2 / FUSE 3.8.3
1) Download fresh copy of LoopbackFS
2) Launch in Xcode ver 10.1 
3) Drag an existing MSWord file into a new folder you created inside of the LoopbackFS mount
4) Open the MSWord file within the FS mount, edit, then save in place
5) Note that a fuse_hiddenxxx is created and does not go away
6) Attempt to delete the enclosing folder and OSX complains that the "folder is in use"

This is a significant problem as the fuse_hidden files are preventing enclosing folders from being deleted.

**Comment by bfleischer** [comment]
Is this still an issue with recent versions of macOS, macFUSE and Word?
