### ISSUE TITLE
sshfs freezes on mac osx mojave 10.14.1 with vagrant

### ISSUE THREAD

**Issue by cnesty** [osxfuse/osxfuse#570]
craignesty$ vagrant --version
Vagrant 2.2.3
SHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.8.3
FUSE library version: 2.9.7

Guest Additions Version: 5.2.22
default: VirtualBox Version: 6.0
default: Mounting shared folders...
    default: /vagrant => /Users/craignesty/Documents/GATECH/CS6200

Vagrant creates a shared folder. 

If I do this
 sshfs vagrant@default:/vagrant/myproject ./myproject

My whole machine freezes. I'm run Mac OS Mojave 10.14.1. I need to restart my machine to gain regain functionality by holding down the touchid button.

**Comment by bfleischer** [comment]
I this still an issue?

**Comment by mk-conn** [comment]
+1 - But not especially with vagrant and not the whole machine (macOS 10.14.4), only the Finder freezes when trying to mount a remote (remote is not mounted... so I have to ctrl+c the sshfs command)

**Comment by themiyan** [comment]
+1 i use sshfs to load a remote disk and i have a similar problem:

`sshfs account@server.nl: ~/mnt/disk_name -o follow_symlinks,volname=disk_name,defer_permissions,auto_cache
` 
 
when i cd and list file the terminal hangs and so does the finder. After a while an error is given as 
`Device not configured`


running: macOS 10.14.6 
SSHFS version 2.10
OSXFUSE 3.10.3
FUSE library version: 2.9.7

**Comment by diegovillanueva** [comment]
same problem with macos 10.14.5 and
SSHFS version 2.10
OSXFUSE 3.8.3
FUSE library version: 2.9.7

**Comment by maxcaibm** [comment]
Sorry for bumping this issue, but just wondering if anyone has found a resolution? I am experiencing similar issues and have not found one.

**Comment by stefangeneralao** [comment]
My apologies as well for bumping this issue. Has anyone found a fix?

@maxcaibm did you find a fix?

**Comment by FranzKnut** [comment]
Bump

**Comment by bfleischer** [comment]
macFUSE 4.6.2 addresses hangs when mounting file systems. This ticket has been inactive for a long time, so I'm closing it. Feel free to open a new ticket in case this is still an issue with macFUSE 4.6.2.
