### ISSUE TITLE
Conflicting info for stable vs. pre-release versions

### ISSUE THREAD

**Issue by stysedo** [osxfuse/osxfuse#571]
Not to be too pedantic but...
The main FUSE page indicates that version 3.8.3 is the current stable release, while the Downloads[1] page indicates that 3.8.2 is the "Latest Release" and 3.8.3 is "Pre-release."

[1] https://github.com/osxfuse/osxfuse/releases

**Comment by bfleischer** [comment]
Thanks, fixed!
