### ISSUE TITLE
Question: hardened runtime / kext-dylib compatibility

### ISSUE THREAD

**Issue by koczkatamas** [osxfuse/osxfuse#572]
First of all, I'd like to thank you for this great project! :)

So we are turning on [Hardened Runtime](https://developer.apple.com/documentation/security/hardened_runtime_entitlements) in our application and we have to [disable library validation](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation) to be able to load osxfuse's dylib.

As an alternative we were thinking about including the latest dylib in our application and sign it again with our own code signature certificate, so we won't have to disable library validation (we would like to still install the kext module via the official installer).

Our question is whether we can expect various versions of the dylib and kext to be compatible or is it a wrong approach to the problem?

By any chance do you have any better idea how to solve the issue?

**Comment by bfleischer** [comment]
Including the dylib in your application will cause issues. Currently the library checks the version of the kernel extension. If it does not match the library's version you won't be able to mount your volume. Right now there is no guarantee that an older dylib will work with a newer kernel extension.

However, I'm planning to remove the version check when the interface is stable. But this might take a while.
