### ISSUE TITLE
SSHFS returns "missing host" when attempting to connect to host.

### ISSUE THREAD

**Issue by Lite5h4dow** [osxfuse/osxfuse#576]
Command:
`sshfs uname@xxx.xxx.xxx.xxx ~/Net\ Drive/ .`

Expected result:
successful connection

Actual Result:
```
missing host
see 'sshfs -h' for usage
```

steps to replicate: 
unknown (jus ttry connecting to a host i guess)

Further Details:
SSH works fine. using ftp clients works fine, just not sshfs 🤷‍♂️

**Comment by SombiriX** [comment]
Try changing the command to `sshfs uname@xxx.xxx.xxx.xxx:/absolut/path/to/Net\ Drive/ .` the `:` is required to specify a remote path.
