### ISSUE TITLE
Lacie Public Private 

### ISSUE THREAD

**Issue by AAR15** [osxfuse/osxfuse#578]
1.  I have a Lacie 1 TB external hard drive with a Google developed " Public / Private " section.
It worked fine on a 2012 iMac3.4GHz intel i 7 running Sierra , then High Sierra. Then when I installed Mojave the " Public/ Private " section opened but became " read only ". 

2.  Then ( February 2019 ) the iMac hard drive started to fail.

3.  I replaced the iMac with a new 2017 model with Mojave. I expected Public / Private " read only ". The Lacie drive worked except for Public Private . However this time it accepted the password then threw up - 

                            " std:: exception at std :: exception "

4.  The Public / Private section depends on MacFUSE ( 32 bit ). Mac FUSE has been replaced by OSXFUSE ( 64 bit ). MacFUSE is not supported any more. I installed OSXFUSE with the MacFUSE compatibility layer ticked. The installation is supposed to be successful.

5.  This time the message came up 

  [ lock image ]   " OSXFUSE with MacFUSE Compatibility Layer is required for LaCie Private Public.
 Click install to continue and start using LaCie Private Public. ( Administrative  privileges are required to perform this installation )                        Quit              Install  "

6.   Note that the " layer " is already installed . I hit " install ", it asks for the administrator password. This time it throws up

  [ lock image ]   " Error while installing OSXFuse. Please try again later ".

It never works.

7.   I thought the problem was Mojave ( its not ) , the new machine ( its not ). If I try to connect to an older Mac running Sierra ( which should work ). I get EXACTLY the same problem.

8.  I also tried to instal MACFUSE 2.0 to get around the problem. However my Mac's " Security & Privacy " blocks me. It looks like its almost there when that happens. 

Has anyone beaten this problem ? LaCie have no idea.

**Comment by noobmaster29** [comment]
I'm having the same issue.

**Comment by AAR15** [comment]
I may be able to help. After a ridiculous path I got there.

1. 	Forget OSXFUSE 3.8.3 / Compatibility layer - doesn’t work.

2.     Forget Windows unless the external drive has been set up for Windows / Mac

3.     Forget Mojave 

4.     Forget Lacie - they would not have a clue. The advice I got from them was 1. erase the disk ( exactly what I did NOT want ) or 2. plug into a windows machine - they thought the drive had converted itself to NTFS. Wrong. I tried it. Window will recognise a USB C / Thunderbolt 3 but not the Mac OS of the drive

5.    I also feared that the drive had been hopelessly corrupted and that nothing would work. Thankfully - no , it is OK

The course I took was to try to recreate the system that worked . That meant -

a.     getting hold of another machine ( older ) - a Mac Air -  that would support OS 10.11 ( El Capitain ). I got nowhere with High Sierra. Then I cleared Macfuse / OSXFUSE versions already there , found OSXFUSE 2.8 dmg by internet search and tried to instal that.

b.     before doing that I had to get around Mac Gatekeeper. As the old versions of MacFuse etc are not supported Macs will reject them. So you have to enable the software source “ Anywhere “ which is easily done on El Capitain but requires Terminal on Mojave ( too hard and useless for this problem ).

c.     Then I sought to instal OSXFUSE 2.8 , ticked the Compatibility Layer  ( useless on 3.8.2 ) and it worked. 

Then I copied all the files locked behind the Public / Private barrier onto another external drive.

If you try to instal OSXFUSE 2.8 on Mojave it just rejects it outright. The key is the recreation of a 32 bit system circa 2015 ( I think ). There may be other combinations ( apart from El Capitain / OSXFUSE 2.8 ) that work . I have no idea. This worked.

AAR15

**Comment by bfleischer** [comment]
Please refer for all Lacie Public Private issues to Lacie. Lacie is not using FUSE the right way and bundled a very outdated version of FUSE, the last time I checked. I tried to contact them but was ignored.

**Comment by warlordjc** [comment]
Solved:
I had the same issue, this was working fine till I moved to OSX Catalina then all hell broke lose. My data was locked. To resolve:
1. I created a bootable USB with OSC High Sierra https://www.macworld.com/article/3204672/how-to-create-a-bootable-macos-high-sierra-installer-drive.html
2. Follow the steps to reboot the computer into OSX High Sierra on the USB
3. In my case I was using the Lacie d2 USB 3.0 Thunderbolt Series. If you try to launch Private-Public on the drive it will launch and prompt you to install OSXFuse which came with the drive . You need to quit that install it launches for OSXFUSE as it will end up with errors and you cannot proceed.
-in my case I downloaded and installed Fuse for MacOS 3.9.0 from the github source. You need to install that with MacFuse Compatibility layer checked.
- Then download Private/Public version 1.9 compatible with MacOS High Sierra 10.13 from the Lacie website http://www.lacie.com/support/software/private/
and install when prompted keep both copies and the new install would be named Private-Public 2.app. 
Do not launch it (If you launch it, it will prompt you to partition the remaining capacity on the Lacie drive - which you do not want to do)
Copy Private-Public 2.app from the Applications folder and paste it on the same Lacie partition on the external Lacie drive containing the LaPrivate Folder (which contains your LaPrivate.lc file which is your encrypted drive).
Now launch Private-Public 2.app launch it from the Lacie drive. 
you will be prompted for your password to access the encryped LaPrivate.lc file which would then be mounted as the drive LaPrivate.

You can copy your files off the encrypted section to another drive or the non-encrypted partition of the Lacie drive. Once you are sure you have the files safe on another drive or partition, you can delete them off the LaPrivate partition and reboot into OSX Catalina by restarting your mac and removing the bootable High Sierra USB.
You will now be able to access your files.

**Comment by Sculptort** [comment]
I tried to do this but I am not very knowable about programs or tech stuff. When I have followed you instructions I get these messages 
![Untitled 2](https://user-images.githubusercontent.com/69959451/90732458-09415c80-e2c3-11ea-9d95-779d09f21b0a.jpeg)
![Untitled 3](https://user-images.githubusercontent.com/69959451/90732488-152d1e80-e2c3-11ea-8531-61e99f6aa2bd.jpeg)
I have over 20 years of images on my Lacie Private-Public folders. I have bought a Apple laptop running OS High Sierra 
Why no one was warned about not upgrading to the latest OS and how this would effect them is beyond belief. I would never have upgraded my desktop computer.
If there is anyway you can help please just let me know, I am in the depths of despair.

**Comment by locknauth** [comment]
Please download the files below

https://www.lacie.com/ca/en/support/usb-keys/moskeyto/

Solution provided by warlordjc is bang on! Worked perfectly for me

![image](https://user-images.githubusercontent.com/5922682/125861912-e5eae730-9cd5-4530-8a61-9303b5a079d1.png)

**Comment by caroline-englert** [comment]
@locknauth @warlordjc The links you provided to Private/Public version 1.9 are no longer active and instead just take me to the Lacie products page. Do you know of anywhere else the software might be held? 

Lacie is being of no help and referring me to data recovery 3rd parties rather than helping to solve.
