### ISSUE TITLE
Why are directory dates all set to Dec 31  1969 on s3fs mounted dirs?

### ISSUE THREAD

**Issue by mfeblowitz** [osxfuse/osxfuse#579]
After mounting an s3 bucket, the mount point and all subdirectories show the date `Dec 31  1969` and a size of `0`. This also is the case for (sub)directories newly created on the cloud side.

The dates look ok when looking on S3 directly, and also when using fuse on Linux. 
This is v 1.85 on Mojave 10.14.3

**Comment by bfleischer** [comment]
Please raise this issue with the maintainers of s3fs. Unless s3fs provides the correct dates there is not much FUSE can do.
