### ISSUE TITLE
Device not configured, not unmountable

### ISSUE THREAD

**Issue by mfeblowitz** [osxfuse/osxfuse#582]
Scenario:

- Mac loses contact with s3
- any access results in a "Device not configured" message
- umount complains of device busy; same for the recommended `diskutil unmount`
- lsof does not find the mounted dir - not when specified as device id or mount path

So far, the only way I've found to have it let go is to reboot.

Any recommendations?

**Comment by mfeblowitz** [comment]
according to [this](https://stackoverflow.com/questions/14057830/unmount-the-directory-which-is-mounted-by-sshfs-in-mac), the following command does work: 

`umount -f <path>`

**Comment by lopugit** [comment]
Yo thank you @mfeblowitz 💯🙏🧎😘
