### ISSUE TITLE
Enable hardened runtime

### ISSUE THREAD

**Issue by Longhanks** [osxfuse/osxfuse#584]
Hi, sorry to bother you again.

I'm currently trying to get an application notarized as is required beginning in macOS 10.14.5 (see https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution), but I'm getting into trouble, because osxfuse is not notarized and cannot be because it doesn't use the hardened runtime.

The hardened runtime can be enabled by providing the following argument to `codesign`: `--options=runtime`.

Would it be possible to ship the osxfuse binaries with the flag enabled? If I understood that flag correctly, it is simply ignored on older macOS versions, so it shouldn't be a problem to stay backwards compatible.

Thanks for any help!

**Comment by bfleischer** [comment]
Are you bundling libosxfuse with your app?

**Comment by Longhanks** [comment]
Not directly inside of the application bundle, but I'm thinking of shipping a *.pkg installer that contains Bundle.pkg and PrefPane.pkg from osxfuse (as well as the application bundle), so that potential users don't have to run two installers. This *.pkg currently fails notarization with for example the following issues:

```json
    {
      "severity": "error",
      "code": null,
      "path": "chili-gui.pkg/PrefPane.pkg Contents/Payload/Library/PreferencePanes/OSXFUSE.prefPane/Contents/MacOS/autoinstall-osxfuse-core",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "chili-gui.pkg/Core.pkg Contents/Payload/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "chili-gui.pkg/Core.pkg Contents/Payload/Library/Filesystems/osxfuse.fs/Contents/Resources/mount_osxfuse",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    },
```

**Comment by Longhanks** [comment]
Not directly inside of the application bundle, but I'm thinking of shipping a *.pkg installer that contains Bundle.pkg and PrefPane.pkg from osxfuse (as well as the application bundle), so that potential users don't have to run two installers. This *.pkg currently fails notarization with for example the following issues:

```json
    {
      "severity": "error",
      "code": null,
      "path": "my_installer.pkg/PrefPane.pkg Contents/Payload/Library/PreferencePanes/OSXFUSE.prefPane/Contents/MacOS/autoinstall-osxfuse-core",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "my_installer.pkg/Core.pkg Contents/Payload/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "my_installer.pkg/Core.pkg Contents/Payload/Library/Filesystems/osxfuse.fs/Contents/Resources/mount_osxfuse",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    },
```

**Comment by bfleischer** [comment]
Ok, this is bad. Enabling the hardened runtime requires that binaries are built with at least macOS SDK 10.9. Most parts of FUSE are built with an older SDK. The fastest way to address this is most likely dropping support for anything below macOS 10.9.

**Comment by bfleischer** [comment]
FUSE for macOS 3.9.0 is fully notarized. I enabled the hardened runtime for all executables. However, you will still need to allow third party libraries when enabling the hardened runtime.

**Comment by jarrocha** [comment]
@bfleischer I would like to see the code changes to this latest commit you did when there are no sources when checking out the latest tag 3.9.0. I'll appreciate your help.

**Comment by compuguy** [comment]
@jarrocha He's no longer posting source code for recent releases see #590 for more information.
