### ISSUE TITLE
Unicode normalization for Finder

### ISSUE THREAD

**Issue by netheril96** [osxfuse/osxfuse#585]
The original issue is [here](https://github.com/netheril96/securefs/issues/74). The gist: even though securefs, a FUSE filesystem I've written, passes filenames as is, Finder insists that the filenames must be in NFD format, as if securefs were the same as HFS+. So why? Does Finder treats any osxfuse volume in the same way as HFS+ volume, or do I have pass some flags to osxfuse to signal that it does not do Unicode normalization?

**Comment by netheril96** [comment]
Is anybody monitoring this issue tracker at all?

**Comment by gxfxyz** [comment]
I've encountered the same issue with [rclone mount](https://rclone.org/commands/rclone_mount/). In the rclone osxfuse volume, folders with NFC form unicode names (e.g. `'ô' == '\xf4'`) would become empty in Finder. Finder only can show the folder contents if its name is in NFD form (e.g. `'ô' == 'o\u0302'`). 

----

Update:

Passing this option `-o modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC` to osxfuse fixes this issue.

For rclone users:

To pass this option to osxfuse, rclone needs to be compiled from source with `go build -tags cmount`.

Steps to reinstall rclone with `cmount` via Homebrew:

1. Uninstall:

```
brew uninstall rclone
```

2. Edit homebrew rclone formula:

```
brew edit rclone
```

```diff
diff --git a/Formula/rclone.rb b/Formula/rclone.rb
index cc2d18dc68..a18d072756 100644
--- a/Formula/rclone.rb
+++ b/Formula/rclone.rb
@@ -18,7 +18,7 @@ class Rclone < Formula
     ENV["GOPATH"] = HOMEBREW_CACHE/"go_cache"
     mkdir_p buildpath/"src/github.com/ncw/"
     ln_s buildpath, buildpath/"src/github.com/ncw/rclone"
-    system "go", "build", "-o", bin/"rclone"
+    system "go", "build", "-o", bin/"rclone", "-tags", "cmount"
     man1.install "rclone.1"
     system bin/"rclone", "genautocomplete", "bash", "rclone.bash"
     system bin/"rclone", "genautocomplete", "zsh", "_rclone"
```

3. Build and install rclone:

```
brew install --build-from-source rclone
```

Then use following command to mount:

```
rclone cmount remote:path/to/files /path/to/local/mount -o modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC
```

**Comment by FurloSK** [comment]
I am encountering the very same issue using pCloud (which, in turn, requires and uses FUSE under its hood). Is there any workaround for me, a "common" user?

**Comment by bfleischer** [comment]
For future reference: https://github.com/macfuse/macfuse/wiki/File-Names-(Unicode-Normalization-Forms)
