### ISSUE TITLE
Notarizing osxfuse or apps using it

### ISSUE THREAD

**Issue by mixtly87** [osxfuse/osxfuse#586]
Signing your apps for Gatekeeper: https://developer.apple.com/developer-id/

Apple: _Starting with the public release of macOS 10.14.5, all new kernel extensions and updates to kernel extensions need to be submitted for notarization._

Is there going to be a support for this for osxfuse? Will osxfuse get notarization? If not, will we still be able to notarize apps using osxfuse under the hood?

**Comment by hjmallon** [comment]
Related to https://github.com/osxfuse/osxfuse/issues/584

You should be able to notarize apps with OSXFUSE in their installation bundles when the above issue is addressed.

**Comment by bfleischer** [comment]
The latest release of FUSE for macOS is fully notarized.
