### ISSUE TITLE
offset 0 in the write method several times during writing a file

### ISSUE THREAD

**Issue by arvgord** [osxfuse/osxfuse#587]
@bfleischer Thank you for implementation fuse for macOS!
I develop a network file system on JAVA for macOS with the help of OSXFuse and java library [jnr-fuse](https://github.com/SerCeMan/jnr-fuse).
It works mostly well, I can read data from the server and can write data to the server. But sometimes errors occur. I tested it on macOS High Sierra 10.13.6 and macOS Mojave 10.14.3 on both systems was installed OSXFuse 3.8.3.
I mount OSXFuse with the following parameters:
- -onegative_timeout=4
- -onolocalcaches // because network file system
- -onoappledouble // .DS_Store and ._ files are not used
- -odefer_permissions
- -ouid={user_uid}
- -ogid={user_gid}    

Also, I implemented setxattr, getxattr, listxattr, removexattr methods. Instead auto_xattr option, these methods were implemented but do nothing (always return 0).
Usually, when I write data to the file(with the help of **write** method) the **size** parameter is 65536. I found that in the **write** method, the **offset** parameter may take the 0 value several times during write of one file. When the **offset** parameter takes 0 value, the **write** method again starts writing data at the beginning of the file and filling it with zeros instead of real data. Thus the real data have recorded earlier is replaced with zeros. This behavior may be caused several times while writing one file. But after reaching the offset of the previous stop (where offset 0 occurred), the normal file recording continues. As a result, I get a corrupted file that was filled with zeros at the beginning of the file.

Additional information:
- OS versions - Mojave 10.14.3 and High Sierra 10.13.6
- OSXFuse - 3.8.3
- jnr-fuse - 0.5.3
- JRE 1.8.0_202-b08

**Comment by aiasi** [comment]
I believe I am seeing something similar to your problem. In my case, I'm writing a file and sometime before its done with all the writes, a read() is called on that same file (using a different FD). That read causes the writes to reset to almost the beginning of the file and fills it with junk data.

Appears to occur at random times but perhaps in conjunction with previously written files. The key is that weird read() that seems to directly reset the offset. Are you seeing a read() occur each time before your offset is reset to 0?
I'm wondering if FUSE is persisting information from a prior write() of a completely different file and spontaneously corrupting a subsequent series of writes.  

***** writeFile test.txt  Size= 131072   offset= 125440000   fileDescriptor= 0
***** writeFile test.txt  Size= 131072   offset= 125571072   fileDescriptor= 0
***** writeFile test.txt  Size= 126976   offset= 125702144   fileDescriptor= 0

***** readFile test.txt   Size= 4096  offset= 4096  fileDescriptor= 790    (why???)

***** writeFile test.txt  Size= 131072   offset= 4096     fileDescriptor= 0   (oh oh!!!)
***** writeFile test.txt  Size= 131072   offset= 135168   fileDescriptor= 0
***** writeFile test.txt  Size= 131072   offset= 266240   fileDescriptor= 0

**Comment by arvgord** [comment]
>Are you seeing a read() occur each time before your offset is reset to 0?   

Yes, read is called every time when offset reset to 0.

**Comment by bfleischer** [comment]
@arvgord, @aiasi Can you reproduce the issue with the loopback file system? I need to be able to reproduce the issue in order to fix any bugs. Are you both developing file systems in Java with jnr-fuse? 

I'm assuming you are developing commercial software? If so, please contact me via email. You can find my email address on my GitHub page. I'm done working for free and am looking for sponsors.

**Comment by aiasi** [comment]
@bfleischer, thanks! No, in my case I am not using Java/JNR-fuse but C++/Swift. However, I believe I was able to resolve my problem by updating the file size attribute in attributesOfItem(). In my application, file content is dynamically manipulated and it was a matter of telling FUSE about that. I have not seen another zero-ed offset in my testing over the last few days but I have some additional test cycles on large files to complete and will post here if I see a recurrence. I am working towards commercialization and will definitely contact you regarding some upcoming challenges regarding performance and caching ;)
