### ISSUE TITLE
Less convoluted volume names

### ISSUE THREAD

**Issue by cpcallen** [osxfuse/osxfuse#591]
When I mount my Android phone using [Android File Transfer for Linux](https://github.com/whoozle/android-file-transfer-linux) the resulting volume gets named `OSXFUSE Volume 0 (aft-mtp-mount)`, which I do not find very meaningful or descriptive.

It would be nice if mounted volumes would get named for the device/volume being mounted or the mountpoint ("Pixel" and "pixel" respectively, in my particular use-case).

(Originally reported [here](https://github.com/whoozle/android-file-transfer-linux/issues/219)).

**Comment by bfleischer** [comment]
This is not an FUSE bug. The file system is simply not providing a name for the mounted volume.
