### ISSUE TITLE
Extension installer still not authorised on 10.14 Mojave

### ISSUE THREAD

**Issue by jon-blum** [osxfuse/osxfuse#593]
Just did an install of OSXFuse-3.9.0.dmg on a clean Mojave VM... this is the version with the notarised disk image and binaries, which I thought would resolve the Gatekeeper-related install problems on Mojave.

The installer proceeded just fine until the last screen -- at which point it brought up the usual "System extension blocked" / "allow loading system software from developer 'Benjamin Fleischer'" message in the installer.

As an extra complication -- under Mojave, by default the System Preferences / Security & Privacy / General pane doesn't even *show* the "Allow apps downloaded from  Anywhere" option any more.  The only way to complete installation was to disable Gatekeeper from the command prompt:

sudo spctl --master-disable

...and then open the Security & Privacy pane, select "Anywhere", and *then* you could approve "Benjamin Fleischer".

This is not the easiest of install paths...  is there any chance of this being fixed soon?

**Comment by bfleischer** [comment]
Please read up on how kernel extension notarization works. Kernel extensions that are not notarized will not load on 10.14.5. This has nothing to do with the "Allow loading system software from developer 'Benjamin Fleischer'" dialog. Notarization is simply an additional requirement and does not replace the need to allow the software.

The fact the the "Allow" button does not appear on your system is most likely an issue on your end. It works just fine for other users. It might be related to you using a VM. There are know issues with System Preferences not accepting input by virtual input devices.

**Comment by bfleischer** [comment]
I'm using VMware Fusion and the "Allow" buttons appears as expected after installing FUSE for the first time.
