### ISSUE TITLE
Unable to change case of file name in Finder

### ISSUE THREAD

**Issue by kainjow** [osxfuse/osxfuse#594]
If a file is renamed to be a different case in Finder, for example hi.txt -> HI.txt, Finder generates an error:

> The name “HI” with extension “.txt” is already taken. Please choose a different name.

I have reproduced this with loopback FS.

**Comment by bfleischer** [comment]
Is the underlying file system case sensitive?

**Comment by kainjow** [comment]
Underlying FS for loopback is normal APFS, so case insensitive.

Wonder if it's related to the use of VOL_CAP_FMT_CASE_PRESERVING? https://github.com/osxfuse/kext/blob/support/osxfuse-3/osxfuse/fuse_vfsops.c#L799
