### ISSUE TITLE
If path Deep to many , cause path length to long , docx file will can not open 

### ISSUE THREAD

**Issue by wenboma** [osxfuse/osxfuse#597]
for example:
path is : /反映确认用/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ
/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/名称未設定フォルダ/12.docx
open 12.docx , fail

**Comment by kainjow** [comment]
What app are you opening the file with? I’ve seen similar behavior and I think it’s a limitation with Office.

**Comment by wenboma** [comment]
I try in osfuse Demo
this file can open normal in local but fuse demo can not open

**Comment by rccharles** [comment]
What macOS application are you using to open the file ( we are not talking about the version of Fuse )? 

I have run into the length of the file path limitation in Microsoft Office in Word 2011. It's around 253 to 260 characters.  

You should try making a short in length alias of the file.  Open the alias.

**Comment by bfleischer** [comment]
This ticket has bee inactive for a long time. I'm unable to reproduce the issue with the lastest version of macFUSE.
