### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by stysedo** [osxfuse/osxfuse#600]
As of June 17, 2019 it looks as though the GPG key used to create the detached signatures for FUSE for macOS/osxfuse assets has expired.

**Comment by bfleischer** [comment]
I’ve extended the key several hours ago. You’ll need to update it from a key server.

**Comment by stysedo** [comment]
Key ID A2818875 has expired again on August 8, 2023.

**Comment by bfleischer** [comment]
I renewed the key.
