### ISSUE TITLE
after installing Mojave 10.14.5 became super slow, spinning wheel, PKD and Routined constantly crashing

### ISSUE THREAD

**Issue by chriz74x** [osxfuse/osxfuse#601]
I think these tools destroyed something in my computer. Uninstalling didn't make any difference. I am constantly getting pkd crashes due to some com.apple.pluginkit not found when trying to write to some strangely named folder. I think this software is trying to register something to be made persistent in Finder or something and is failing miserably. I am not at my PC now so I can't paste the errors. 

p.s. removing fuse (and ntfs-3g) didn't solve the situation.

**Comment by bfleischer** [comment]
FUSE for macOS does not rely on plugins or use com.apple.pluginkit in any way. I don't think FUSE is to to blame for the issues you are seeing.

> p.s. removing fuse (and ntfs-3g) didn't solve the situation.

This reinforces my doubts about FUSE being to blame for the issues. FUSE is a completely passive software component. It does not register any components.

**Comment by chriz74x** [comment]
Interesting. The only thing I did apart installing FUSE was updating brew
