### ISSUE TITLE
Verify correct PGP key?

### ISSUE THREAD

**Issue by jonathancross** [osxfuse/osxfuse#602]
Hi, I am trying to verify the **correct** GPG key used to sign releases here.
```
gpg: Signature made Fri Jun 14 02:52:28 2019 CEST
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: Good signature from "Benjamin Fleischer <fleiben@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0093 B21E F45D 6352 84F6  A147 53C9 18C1 A281 8875
     Subkey fingerprint: 135F 164B 411B AA1F 4A4B  CD37 617A 3461 8026 08A1
```

Unfortunately this key is not in the OpenPGP Web Of Trust.

I also don't see it clearly posted anywhere in forums, Keybase, or here on GitHub, so it really could be a key created by anyone hypothetically.

@bfleischer Can you please post your key fingerprint in the project [README](https://github.com/osxfuse/osxfuse/blob/master/README.md), and perhaps somewhere else like a personal website, [LinkedIn](https://www.linkedin.com/in/benjamin-fleischer-68300383/) or better yet [Keybase.io](https://keybase.io/)?  Exchanging key sigs with someone whose key is in the web of trust would be even better.

**Comment by bfleischer** [comment]
You can find my key in the release notes for version 3.6.0. It is the first release I signed using GnuPG. 

https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.6.0

But I agree, I could post it somewhere more prominent. I don't know anybody with a "trusted" key, who could sign mine.

**Comment by jonathancross** [comment]
That was fast, thanks!
I just sent you an email as you were responding.
I'd be happy to exchange signatures if there is an opportunity (my [key is in the WOT Strong Set](https://pgp.cs.uu.nl/stats/c0c076132ffa7695.html)).

**Comment by jonathancross** [comment]
Great to see you've been signing releases and commits!
