### ISSUE TITLE
Release tags for 3.10.0 and 3.9.X point to empty repos

### ISSUE THREAD

**Issue by strib** [osxfuse/osxfuse#603]
I might be doing something wrong, but starting with the 3.9.0 release tag, I'm unable to see any source code in the github repo.  e.g.: https://github.com/osxfuse/osxfuse/tree/osxfuse-3.10.0.  The `git clone` command from the main readme also checks out a blank repo.

The source code downloads from the github releases page are also empty.

The tags for 3.8.3 and earlier (e.g. https://github.com/osxfuse/osxfuse/tree/osxfuse-3.8.3) still work fine as far as I can tell.

Is there something new I need to do to check out the source for these tags?  Or are the tags wrong?  Thanks!

**Comment by yan12125** [comment]
osxfuse is no longer open source since version 3.9.0. Some more details can be found in https://github.com/osxfuse/osxfuse/issues/590.

**Comment by compuguy** [comment]
As @yan12125 said, @bfleischer is no longer releasing the source code for osxfuse. I wish he would mention this either on the osxfuse website and/or the readme for the repo.

**Comment by strib** [comment]
Understood thanks, somehow I missed that earlier issue.
