### ISSUE TITLE
Failure to install on OS X 10.13.6

### ISSUE THREAD

**Issue by bonner** [osxfuse/osxfuse#606]
I am getting the following failure when trying to install fuse 3.6.0-3.10.0 on my macbook pro with OS X 10.13.6

> Jul 19 10:21:51 GC02WT3VBHTD6E Installer[1962]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Jul 19 10:21:51 GC02WT3VBHTD6E Installer[1962]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.6.0.pkg#Core.pkg
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: Set authorization level to root for session
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: Will use PK session
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: Using authorization level of root for IFPKInstallElement
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: Starting installation:
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: Configuring volume "Macintosh HD"
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: Preparing disk for local booted install.
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: Free space on "Macintosh HD": 341.03 GB (341027491840 bytes).
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: Create temporary directory "/var/folders/47/whb_bx255sl4_st5z6xbmlhh0000gn/T//Install.1962j6y7s3"
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: IFPKInstallElement (1 packages)
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: Adding client PKInstallDaemonClient pid=1962, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Jul 19 10:21:52 GC02WT3VBHTD6E Installer[1962]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: ----- Begin install -----
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: packages=(
	    "PKLeopardPackage <id=com.github.osxfuse.pkg.Core, version=3.6.0, url=file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.6.0.pkg#Core.pkg>"
	)
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: Skipping stale sandbox at path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/858835A5-F6AD-433A-8A99-5C596610F108.activeSandbox
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: Skipping stale sandbox at path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/6F0BA7E9-0B9E-45C0-AD84-F36E193C8B3E.activeSandbox
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: Skipping stale sandbox at path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/A5C1E3EA-A5E1-4BB6-A701-2A8E0993FBFF.activeSandbox
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: Skipping stale sandbox at path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/FB21FAF9-F9E9-4A8A-9F8E-C388D880541B.activeSandbox
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: Extracting file://localhost/Volumes/FUSE%20for%20macOS/Extras/FUSE%20for%20macOS%203.6.0.pkg#Core.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.activeSandbox/Root, uid=0)
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: prevent user idle system sleep
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: suspending backupd
Jul 19 10:21:52 GC02WT3VBHTD6E installd[1493]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.4fmgmJ/Scripts/com.github.osxfuse.pkg.Core.xIBaaG
Jul 19 10:21:52 GC02WT3VBHTD6E install_monitor[1968]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Jul 19 10:21:53 GC02WT3VBHTD6E installd[1493]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.activeSandbox
Jul 19 10:21:53 GC02WT3VBHTD6E installd[1493]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.activeSandbox/Root (2 items) to /
Jul 19 10:21:54 GC02WT3VBHTD6E shove[1975]: [source=file] **failed _RelinkFile(/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.activeSandbox/Root/Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/_CodeSignature/CodeResources, /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/_CodeSignature/CodeResources): Permission denied**
Jul 19 10:21:54 GC02WT3VBHTD6E shove[1975]: srcPath = /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.activeSandbox/Root/Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/_CodeSignature/CodeResources NSFileOwnerAccountID=0 NSFileHFSTypeCode=0 NSFileSystemFileNumber=12471205 NSFileExtensionHidden=0 NSFileSystemNumber=16777220 NSFileSize=5402 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2017-06-12 22:51:24 +0000 NSFilePosixPermissions=420 NSFileHFSCreatorCode=0 NSFileType=NSFileTypeRegular NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=1 NSFileModificationDate=2017-06-12 22:51:24 +0000
Jul 19 10:21:54 GC02WT3VBHTD6E shove[1975]: dstPath = /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/_CodeSignature/CodeResources NSFileOwnerAccountID=0 NSFileHFSTypeCode=0 NSFileSystemFileNumber=1014315 NSFileExtensionHidden=0 NSFileSystemNumber=16777220 NSFileSize=5402 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2017-09-21 06:11:50 +0000 NSFilePosixPermissions=420 NSFileHFSCreatorCode=0 NSFileType=NSFileTypeRegular NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=1 NSFileModificationDate=2017-09-21 06:11:50 +0000
Jul 19 10:21:54 GC02WT3VBHTD6E shove[1975]: dstParentPath = /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/_CodeSignature NSFileOwnerAccountID=0 NSFileSystemFileNumber=1014314 NSFileExtensionHidden=0 NSFileSystemNumber=16777220 NSFileSize=96 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2017-09-21 06:11:50 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=3 NSFileModificationDate=2017-09-21 06:11:50 +0000
Jul 19 10:21:54 GC02WT3VBHTD6E install_monitor[1968]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Jul 19 10:21:54 GC02WT3VBHTD6E installd[1493]: PackageKit: releasing backupd
Jul 19 10:21:54 GC02WT3VBHTD6E installd[1493]: PackageKit: allow user idle system sleep
Jul 19 10:21:54 GC02WT3VBHTD6E installd[1493]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., arguments=(
	    "-f",
	    "-s",
	    "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.activeSandbox/Root",
	    "/"
	), NSUnderlyingError=0x7faa10f1a190 {**Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"**}} {
	    NSLocalizedDescription = "An unexpected error occurred while moving files to the final destination.";
	    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=13 \"Permission denied\"";
	    arguments =     (
	        "-f",
	        "-s",
	        "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.activeSandbox/Root",
	        "/"
	    );
	}
Jul 19 10:21:54 GC02WT3VBHTD6E installd[1493]: PackageKit: Running idle tasks
Jul 19 10:21:54 GC02WT3VBHTD6E Installer[1962]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={NSUnderlyingError=0x60000005bc90 {Error **Domain=NSPOSIXErrorDomain Code=13 "Permission denied"**}, NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., arguments=(
	    "-f",
	    "-s",
	    "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/8211711E-3F0D-41E5-B0AB-BD46DE548F6E.activeSandbox/Root",
	    "/"
	)}
Jul 19 10:21:54 GC02WT3VBHTD6E installd[1493]: PackageKit: Removing client PKInstallDaemonClient pid=1962, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Jul 19 10:21:54 GC02WT3VBHTD6E installd[1493]: PackageKit: Done with sandbox removals
Jul 19 10:21:55 GC02WT3VBHTD6E Installer[1962]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jul 19 10:21:55 GC02WT3VBHTD6E Installer[1962]: IFDInstallController 1E6A0 state = 8
Jul 19 10:21:55 GC02WT3VBHTD6E Installer[1962]: Displaying 'Install Failed' UI.
Jul 19 10:21:55 GC02WT3VBHTD6E Installer[1962]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

I tried a clean install without nuking the file system, did not help, I have done
`sudo spctl --master-disable`
and 
`csrutil disable ` from recovery mode

any help appreciated, its a permission issue, but where, everything "seems" all right

**Comment by bonner** [comment]
Did a clean install and I am still getting the same thing...

**Comment by bonner** [comment]
update:
Still unable to do a proper installation

The last thing I tried was to copy the .pkg file from a mounted dmg to another location (this was not necessary) /Volumes/Data/InstallFuse/fuse.pkg, from there I ran

`/usr/bin/sudo -E -- env LOGNAME=username USER=username USERNAME=username /usr/sbin/installer -pkg ./fuse.pkg -target /Volumes/Data -verbose`

This wrote the contents (as far as I know) for fuse to /Volumes/Data/Library.
I then copied these files using sudo to /Library.

The first time I did it I just did a recursive chmod on /Data/Volumes/Library to 777.

When copying 2 of the 4 directories within /Data/Volumes/Library to /Library I encountered permission denied errors very similar to those I posted in this ticket when I ran the installer through the UI.

`GC02WT3VBHTD6E:Library mbonner$ sudo cp -r ./Filesystems/osxfuse.fs /Library/Filesystems
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/_CodeSignature/CodeResources: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/MacOS/applet: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/applet.rsrc: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/main.scpt: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/lib/common.sh: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/lib/installer.sh: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/lib/osxfuse.sh: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/lib/array.sh: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/lib/math.sh: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/lib/string.sh: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/lib/macos.sh: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Resources/Scripts/uninstall_osxfuse.sh: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/Info.plist: Permission denied
cp: /Library/Filesystems/osxfuse.fs/Contents/Resources/uninstall_osxfuse.app/Contents/PkgInfo: Permission denied`

I got similar output from the PreferencePanes directory as well, the other two are fine.

**NOTE: I have previously disabled SIP**
_csrutil status
System Integrity Protection status: disabled._

The files were copied to /Library.
So, as root, I can do 
`$ ls -lrt /Library/PreferencePanes/OSXFUSE.prefPane/Contents/_CodeSignature/CodeResources 
-rw-r--r--  1 root  wheel  5696  6 Jul 10:38 /Library/PreferencePanes/OSXFUSE.prefPane/Contents/_CodeSignature/CodeResources`
BUT, I cannot do 
`cat  /Library/PreferencePanes/OSXFUSE.prefPane/Contents/_CodeSignature/CodeResources 
Password:
cat: /Library/PreferencePanes/OSXFUSE.prefPane/Contents/_CodeSignature/CodeResources: Permission denied`

This kind of blows my mind, I am root, I have read permission on a file, I cannot cat it!

Anyways, the files are all in place, the preference pane is not present in system preferences, I am now trying to install virtual machine now, it probably will not work because not even root can read some of the files in _/Library/Filesystems/osxfuse.fs_

**Comment by bfleischer** [comment]
I have never been able to reproduce this issue but I don't think FUSE is to blame for this.

**Comment by bonner** [comment]
Yes, I agree, unsure why fuse is exposing the issue, but it certainly seems to be something very unusual with my file system and/or os.
I have posted to the mac forums: https://discussions.apple.com/thread/250513560

**Comment by bfleischer** [comment]
I'm closing the issue. Feel free to update it in case there are any new information or workarounds.
