### ISSUE TITLE
Disable osx alerts

### ISSUE THREAD

**Issue by andreipro1002** [osxfuse/osxfuse#607]
Hello,
We have a project where we use the fuse operations from https://github.com/libfuse/libfuse/blob/master/include/fuse.h, and we were wondering if it's possible to replace the mac os default alert with a custom one. For example, if a folder is read-only and we try to compress a file, it will trigger the function _int (*create) (const char *, mode_t, struct fuse_file_info *);_ and the system will display the error **An unrecoverable error occurred while compressing a file**, is it possible to disable this alert and show the one we create? 
Thanks in advance.

With respect,
Andrei

**Comment by bfleischer** [comment]
The alerts or error messages, that are displayed by Finder, cannot be altered.
