### ISSUE TITLE
Not detecting FUSE_USE_VERSION on macOS Mojave

### ISSUE THREAD

**Issue by lukethompsxn** [osxfuse/osxfuse#609]
I have `#define FUSE_USE_VERSION 31` prior to including the `fuse.h` header, however, osxfuse is not detecting this definition and is overwriting it on line 28 of osxfuse/fuse/fuse.h. 

It has defined it to use an old version which causes the compatibility checks to fail. 

A workaround is to simply modify line 28 on `fuse.h` to use the version you wish to use but this is a hassle.

Seems similar to this [issue](https://github.com/astrada/ocamlfuse/issues/2).

**Comment by bfleischer** [comment]
FUSE for macOS does not support version 31, yet. We are still using libfuse 2.

**Comment by lukethompsxn** [comment]
I do not think this is the issue, I have tried specifying version 26 and still run into the same problem
