### ISSUE TITLE
Auto Mount NTFS with volname

### ISSUE THREAD

**Issue by AdsonCicilioti** [osxfuse/osxfuse#610]
I am in High Sierra and correctly installed osxfuse and ntfs-3g.

My goal is to auto mount an NTFS Partition from my Second HD.

I replaced native mount_ntfs with ntfs-3g, so this NTFS Partition is booting itself on boot with this horrible name - `OSXFUSE Volume 0 (ntfs-3g)`.
The partition has the label=Storage.
I tried to create an entry in `/etc/fstab`:
```
/dev/disk1s1 / Volumes / Storage ntfs volname = Storage, local, allow_other 0 0
```
It works when I run `sudo mount -a`, but the system self-assembly that makes it ugly seems to occur first. 

I would like suggestions.

**Comment by bfleischer** [comment]
If the file system does not specify a volume name at mount time osxfuse will need to use a fallback. That's what seems to be happening here. Please raise this issue with the rtfs-3g team. I don't think this is a FUSE issue.
