### ISSUE TITLE
Fuse not compatible with macOS Catalina Beta 5

### ISSUE THREAD

**Issue by sadegs123** [osxfuse/osxfuse#612]
Can you please update Fuse for Catalina beta 5? I am trying to use share file and it gives me an error saying fuse is not compatible with my drive.

**Comment by bfleischer** [comment]
The latest release of FUSE for macOS, 3.10.2 as of writing this, is compatible with Catalina. All you need to do is update.

**Comment by Puntoboy** [comment]
This is causing an issue with the latest Catalina beta. I have installed it but I am still getting the error pop up from Citrix Files (aka ShareFile).

**Comment by bfleischer** [comment]
@Puntoboy Please raise this issue with Citrix. Citrix is not using official FUSE for maCOS releases. They need to update their custom version of FUSE to work with Catalina.

**Comment by Puntoboy** [comment]
> @Puntoboy Please raise this issue with Citrix. Citrix is not using official FUSE for maCOS releases. They need to update their custom version of FUSE to work with Catalina.

Thanks. I didn't realise that. The OP mentioned Share File so I assumed this was fixed.
