### ISSUE TITLE
Mounting silently fails when permission has been granted but the OS hasn't been restarted yet

### ISSUE THREAD

**Issue by Cyberbeni** [osxfuse/osxfuse#618]
On Catalina, you need to restart the OS after enabling the kernel extension in system preferences. There is no notification posted and there is no alert presented in non quiet mode.

Also making a separate notification for every mount error is not that great. There should be 1 notification that includes the errorcode and a suggested error message, so people who want to show error messages on their side can more easily prepare for future/unexpected errors.

https://github.com/osxfuse/support/blob/a7d20f1d36dc6805f00b289791118f730ac9c07e/mount_osxfuse/mount_osxfuse.c#L900

**Comment by bfleischer** [comment]
We need to wait for one of the next beta releases or the GM release of Catalina. I believe the reboot requirement will not be present in the final Catalina  release.

**Comment by bfleischer** [comment]
Beta 8 does lo longer require a reboot after installing a new kernel extension. So I'm closing the issue.

**Comment by Cyberbeni** [comment]
@bfleischer Are you sure? It is still part of the release notes. It only asked for restart the first time (when the user has to press allow in system preferences) and I don't have a clean install to easily try it out.

**Comment by bfleischer** [comment]
Yes, I‘m sure.
