### ISSUE TITLE
Can't get rid of error

### ISSUE THREAD

**Issue by 123me** [osxfuse/osxfuse#620]
Can't uninstall osx fuse and keep getting this message every time I boot up:

"The OSXFUSE library version this program is using is incompatible with the loaded OSXFUSE kernel extension."

Mac version 10.14.6

**Comment by bfleischer** [comment]
It looks like you are using an app that is constantly reinstalling FUSE. This is not the standard FUSE behavior. FUSE does not reinstall itself.

Furthermore the error suggest the developer of the app that displays the error is not using FUSE in the right way. Could you check which app is responsible for the error. It most likely starts automatically when you log in.

**Comment by 123me** [comment]
Thanks - think it was Sdrive.
