### ISSUE TITLE
Unsupported macOS Version

### ISSUE THREAD

**Issue by chelrich** [osxfuse/osxfuse#621]
I updated to Catalina V10.15 Beta and now am getting multiple pop-ups stating: "This version of FUSE is too old for the operating system.  Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS."

I have attempted uninstalling FUSE in every way I can.  I have also installed the new version, uninstalled it again, and repeated multiple times.  I've rebooted several times.  Currently, my machine shows that no instance of it is installed, yet the incessant pop-ups persist.  I can't think of what else to do.

<img width="436" alt="Screen Shot 2019-08-29 at 7 46 35 PM" src="https://user-images.githubusercontent.com/54695764/63989598-b6f5a300-ca95-11e9-88bb-31c036a223d4.png">

**Comment by bfleischer** [comment]
Do you recognize the app symbol one the left in the dialog? This is not an official FUSE version. The official FUSE version would display the FUSE icon, which is different.

You need to get in touch with the developers of the custom version of FUSE. Obviously they did a poor job and did not fully rebrand their custom version.

**Comment by chelrich** [comment]
Oh my goodness!  That makes so much sense.  Thank you so much for pointing that out--figured it out.
