### ISSUE TITLE
Error 100057

### ISSUE THREAD

**Issue by andreipro1002** [osxfuse/osxfuse#622]
Hey,
I happened to receive the error 100057 quite often when debugging my app, and happened also to the clients when trying to copy multiple files on the mounted fuse volume. Do you know any reason why this error occurs and is there any fix for it? Thanks in advance.
<img width="399" alt="Screenshot 2019-09-04 at 15 52 11" src="https://user-images.githubusercontent.com/4287792/64256491-44207800-cf2c-11e9-8fa9-50665831e118.png">

**Comment by bfleischer** [comment]
Which file system are you using?

**Comment by andreipro1002** [comment]
@bfleischer Hey, I'm not sure I understand what do you mean, I'm using the fuse file system.

**Comment by bfleischer** [comment]
FUSE is a building block to develop actual file systems. FUSE itself is not a file system. Most likely you installed FUSE as a dependency of an app. Do you remember the name of the app? What are you using the FUSE volume for?

Nevertheless, you need to report this issue to the developer of the actual file system.

**Comment by andreipro1002** [comment]
@bfleischer We are using FUSE for a file sharing app, and I'm currently working on the project fixing some issues. As far as I see, the error occurs when the file system is disconnected. Have you ever encountered this problem before? 

Edit: the FUSE library used is osxfuse-3.10.2

**Comment by bfleischer** [comment]
Ok, so you are the developer of the file system. I don't know what the specific error code means but your file system is most likely not behaving the way it should. Maybe you could try stripping down the file system to find out which part is causing the error. Or you could run FUSE in debug mode and look for any file system operation that returns an error.
