### ISSUE TITLE
Creation date always as epoch with sshfs [MacOS >= 10.14.5]

### ISSUE THREAD

**Issue by nedex** [osxfuse/osxfuse#623]
**UPDATE for future viewers**: I've mistaken `ctime` for creation time, while on macOS it is `birthtime`. I don't know how it used to work in the past.

Every server I try to mount with sshfs has files and directories with creation date of 01.01.1970 (via stat or finder informations).
I've tried multiple versions and combinations of osxfuse and sshfs and it doesn't seem to work.
Maybe the problem is the OSX version since in the past I didn't have this issue (although with another Mac).

I also looked into the sshfs source code and the `st_ctime` (`sshfs.c` file, `stbuf->st_ctime = stbuf->st_mtime = mtime`) variable seems to be correctly set, tried to mount in debug mode, and also the `workaround=fstat` flag didn't help.
So that's why i think it's a osxfuse / os problem rather than sshfs.

My environment and tested versions:
macOS Mojave 10.14.6 / Catalina 10.15 to 10.5.3
OSXFuse 3.9.2 / 3.10.2 to 3.10.4
SSHFS: 2.5.0 / 2.10

I mostly tried Debian servers and with my android phone (with `adb-channel` trick) which was the main target, and i can confirm that on these servers the `stat` command correctly returns the creation date in ssh.
I have tried both official pkgs and brew installs without any changes.

EDIT: Can confirm that even on the older mac I was using, it stopped working with latest version of Mojave, so the problem should be somewhere in the latest versions.

EDIT 2: Update with Catalina informations and OSXFuse 3.10.3

EDIT 3: Updated versions (Catalina 10.15.3 + OSXFuse 3.10.4)

Thanks.

**Comment by nedex** [comment]
The bug is still there.
Does anybody has a clue?
Otherwise I would need some help to build and debug personally...

**Comment by nedex** [comment]
Still the same up to Big Sur 11.0.1 ...

**Comment by ysmolski** [comment]
Confirming this issue is still present. I use MacFuse 4.2.4 and gocrypts 2.2.1. Any clue where to start looking to fix it? I'm new to OSXFUSE.

**Comment by bfleischer** [comment]
This not a bug in macFUSE. macFUSE supports the concept of creation time. It works fine with the Loopback reference file systems.

SSHFS uses the SFTP protocol. Many Unix file systems don't have the concept of creation time. The POSIX standard does not mandate it. Support for supplying the creation time of a file is an optional extension to the SFTP protocol. In case the server does not pass a creation time to SSHFS there is nothing SSHFS or macFUSE can do.

@ysmolsky Please raise this issue with the gocrypts team. macFUSE supports the concept of creations time, gocrypts might not.

**Comment by nedex** [comment]
> This not a bug in macFUSE

I'm using SSHFS on other clients and it works (for example sshfs on Debian or other SFTP clients), while using the same servers on macOS using macFUSE don't work.

This feature stopped working at some point, since I used this feature to copy some files while keeping the creation date.

If you need more proof please let me know.

**Comment by bfleischer** [comment]
It's not about proof. macFUSE supports creation times. You can check with with the loopback reference file systems (https://github.com/macfuse/demo). This means it's not a macFUSE issue.

Excerpt from man 2 stat:
```
     st_mtime         Time when file data last modified.  Changed by the
                      mknod(2), utimes(2) and write(2) system calls.

     st_ctime         Time when file status was last changed (inode data
                      modification).  Changed by the chmod(2), chown(2),
                      link(2), mknod(2), rename(2), unlink(2), utimes(2) and
                      write(2) system calls.

     st_birthtime     Time of file creation.  Only set once when the file is
                      created.  This field is only available in the 64 bit inode
                      variants.  On filesystems where birthtime is not
                      available, this field is set to 0 (i.e. epoch).
```

`st_ctime` is not the creation time of the file, `st_birthtime` is. `st_birthtime` might not be set by the sshfs version you use.

**Comment by nedex** [comment]
> `st_birthtime` might not be set by the sshfs version you use.

I'm using the latest version of sshfs available, the 2.5.0 (as also stated in the issue).

**Comment by bfleischer** [comment]
Version 2.5.0 from the macFUSE website does not set `st_birthtime`. 

> This feature stopped working at some point, since I used this feature to copy some files while keeping the creation date.

> EDIT: Can confirm that even on the older mac I was using, it stopped working with latest version of Mojave, so the problem should be somewhere in the latest versions.

With the 2.5.0 version the creation date should always have been 01.01.1970. That's why I was asking which version of SSHFS you were using.

Anyway, this is not a macFUSE bug. Implementing this feature in SSHFS should be possible for servers that pass the creation time of files. SSHFS is not well maintained currently.

**Comment by nedex** [comment]
Now I'm getting it, thank you.

I also opened the issue on the sshfs repo, maybe it should be re-opened at this point.

EDIT: I'll try add native birthtime support and add a flag to "infer" it from other dates (it's useful for me, it might for others too).
