### ISSUE TITLE
osxfuse 3.10.2 causes panics on macOS catalina (10.15 Beta 7)

### ISSUE THREAD

**Issue by DigitalGuardianDev** [osxfuse/osxfuse#624]
Installed osxfuse 3.10.2 on macOS catalina (10.15 Beta 7). The install was successful. On attaching a USB thumb drive to the system, it panics with following panic report.

panic(cpu 2 caller 0xffffff7f9dca7707): "osxfuse: What kind of a flag is this (4)?"@/Users/benjamin/Arbeit/FUSE/Repositories/osxfuse/kext/osxfuse/fuse_file.h:80
Backtrace (CPU 2), Frame : Return Address
0xffffff81f8ef3690 : 0xffffff8018942afb 
0xffffff81f8ef36e0 : 0xffffff8018a79ca5 
0xffffff81f8ef3720 : 0xffffff8018a6b70e 
0xffffff81f8ef3770 : 0xffffff80188e9bb0 
0xffffff81f8ef3790 : 0xffffff80189421e7 
0xffffff81f8ef3890 : 0xffffff80189425cb 
0xffffff81f8ef38e0 : 0xffffff80190d3419 
0xffffff81f8ef3950 : 0xffffff7f9dca7707 
0xffffff81f8ef39f0 : 0xffffff7f9dca46a8 
0xffffff81f8ef3a20 : 0xffffff8018bd0f20 
0xffffff81f8ef3aa0 : 0xffffff8018bbb669 
0xffffff81f8ef3d60 : 0xffffff8018bbae60 
0xffffff81f8ef3f40 : 0xffffff8018f9e4f9 
0xffffff81f8ef3fa0 : 0xffffff80188ea376 
      Kernel Extensions in backtrace:
         com.github.osxfuse.filesystems.osxfuse(3.10.2)[4CAD8CC9-131B-34B2-80F2-CB438623C3E5]@0xffffff7f9dc9d000->0xffffff7f9dcb6fff

BSD process name corresponding to current thread: mds_stores
Boot args: debug=0xd44 _panicd_ip=x.x.x.x kdp_match_name=en5

Mac OS version:
19A546d

Kernel version:
Darwin Kernel Version 19.0.0: Sun Aug 18 23:37:31 PDT 2019; root:xnu-6153.0.166~17/RELEASE_X86_64
Kernel UUID: 3DF78B9A-F155-3176-889D-DB780ED589D6
Kernel slide:     0x0000000018600000
Kernel text base: 0xffffff8018800000
__HIB  text base: 0xffffff8018700000
System model name: MacBookPro11,5 (Mac-06F11F11946D27C5)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 227873418783
last loaded kext at 227702104965: com.github.osxfuse.filesystems.osxfuse	3.10.2 (addr 0xffffff7f9dc9d000, size 106496)
loaded kexts:
com.github.osxfuse.filesystems.osxfuse	3.10.2
com.verdasys.dgagent	0035.52.7
@filesystems.msdosfs	1.10
@filesystems.smbfs	3.4
@kext.AMDFramebuffer	3.0.0
@kext.AMDRadeonX4000	3.0.0
@kext.AMDRadeonServiceManager	3.0.0
>AudioAUUC	1.70
>!AGraphicsDevicePolicy	4.1.46
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	4.1.46
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.0d105
>!AUpstreamUserClient	3.6.8
>pmtelemetry	1
>!APlatformEnabler	2.7.0d0
>AGPM	111.1.18
>X86PlatformShim	1.0.0
>!AHDAHardwareConfigDriver	283.13
>!A!IHD5000Graphics	14.0.0
@Dont_Steal_Mac_OS_X	7.0.0
>AGDCBacklightControl	4.1.46
>!AHDA	283.13
>eficheck	1
>ACPI_SMC_PlatformPlugin	1.0.0
>!ABacklight	170.18
>!AThunderboltIP	3.1.2
|Broadcom!B20703USBTransport	7.0.0d105
>!AMuxControl	4.1.46
>!ASMCLMU	212
>!ALPC	3.1
>!ACameraInterface	7.6.0
@kext.AMD7000!C	3.0.0
>!A!IFramebufferAzul	14.0.0
>!AFIVRDriver	4.1.0
>!A!ISlowAdaptiveClocking	4.0.0
>!AMCCSControl	1.12
@filesystems.autofs	3.0
|SCSITaskUserClient	422.0.2
>!ATopCaseHIDEventDriver	153
>!UTopCaseDriver	153
>!U!SCoexistentDriver	489.0.2
>!UCardReader	489.0.2
|IO!BUSBDFU	7.0.0d105
@filesystems.apfs	1412.0.28
>AirPort.BrcmNIC	1400.1.1
>!AAHCIPort	341.0.2
>!AFileSystemDriver	3.0.1
@filesystems.hfs.kext	522.0.8
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!AVirtIO	1.0
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ARTC	2.0
>!AHPET	1.8
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7

**Comment by bfleischer** [comment]
This is a known issue. Apple made some modifications to the kernel in Catalina. The kernel uses an undocumented flag that FUSE does not know how to handle. All known cases of this happening seem to be triggered by Spotlight (mds_stores).

Fixing this would be much easier if Apple had released the source code of the kernel.

**Comment by bfleischer** [comment]
The issue should be fixed in the new 3.10.3 release.

**Comment by DigitalGuardianDev** [comment]
The issue is not observed in 3.10.3 pre-release. Any plan for it's official release?

**Comment by bfleischer** [comment]
Usually I wait one or two weeks before promoting a developer preview to stable. 3.10.3 will become the new stable release next week, unless critical bugs are reported.
