### ISSUE TITLE
the file system is not available (255), Mojave 10.14.6

### ISSUE THREAD

**Issue by neutrinos93** [osxfuse/osxfuse#625]
Hello, 

it is the first time I try to install oxsfuse on my laptop with MacOSX 10.14.6. I'm installing the FUSE version 3.10.2.

I ran the following commands:
`mkdir ~/app`
`sshfs remotelocation ~/app -o volname=app`

and I got the error
`mount_osxfuse: the file system is not available (255)`.

I also tried to reboot the system before and after installing fuse and still had the same problem... any suggestions?

**Comment by bfleischer** [comment]
Please post questions like this on our Google group at https://groups.google.com/forum/#!forum/osxfuse-group.
