### ISSUE TITLE
Duplicate a file in Catalina beta 7 in the finder and it disappears

### ISSUE THREAD

**Issue by joconnorak** [osxfuse/osxfuse#627]
Has anyone else seen this?
Beta 7, duplicate a file on the file system, duplicate it. It appears briefly then disappears until the media is unmounted and re-mounted.

**Comment by bfleischer** [comment]
Duplicating files on a LoopbackFS volume on beta 8 works fine for me. Which file system did you use?

**Comment by joconnorak** [comment]
Thanks. I must have an error in my file system which previous OS’s didn’t hit.

Jim

**Comment by joconnorak** [comment]
I don't see any errors in calls to my file system, but I'm mounting in an odd place. Will let you know what I find.

**Comment by joconnorak** [comment]
Using the loop back file system I can repeat the problem by mounting the file system into a special mount point -- ~/.folder/disk3s2_random
So this is odd.

**Comment by joconnorak** [comment]
The problem has to do with the allow root user option. If I don't allow root then things appear to work properly. The fuse group is set to a group that the file system user is in, it appears. I'm chasing this down, but posting here my intermediate discovery in case anyone else is interested.

**Comment by joconnorak** [comment]
Benjamin,
Allow Root option on the loopback file system doesn't work in the beta 10 Catalina Finder. The file appears on the Finder until the copy completes. New files written to the media have similar problems.

I forgot what I lose if I turn off allow root. Seems like I turned this on back in the mists of time and I don't remember why.

**Comment by fredriklindellckp** [comment]
Benjamin,

Any updates on this issue, we see the same behaviour on released 10.15 Catalina with OSXFUSE 3.10.3 and the loopback example (loopback.c). Items created in the "looped" directory is only seen briefly and then vanish from the finder view. Item is created and seen in the backing folder. Once remounting the loopback the items are seen. Elaborating with the different OSXFUSE options doesn't give any work around for the issue.

**Comment by joconnorak** [comment]
I had to turn off “allow root” to get things working.
I don’t know if this is fundamentally an Apple bug or not.

**Comment by fredriklindellckp** [comment]
We don't use the allow root option at all but are seeing the items created in the fused root folder briefly appear and then disappear. Issue is reproduced with:

diskutil umount /Volumes/UNTITLED
sudo diskutil mount -mountpoint /tmp/cp/me_mounts/\_disk2s1\_/\_UNTITLED\_ disk2s1
sudo ./loopback /Volumes/UNTITLED -omodules=threadid:subdir,subdir=/tmp/cp/me_mounts/\_disk2s1\_/\_UNTITLED\_ -oallow_other,local,native_xattr,volname=LoopbackFS

**Comment by jarrocha** [comment]
Hello Fredrik,
If you open a file and then try to save it in your mounted volume, do you get an error regarding a file lock? Try removing the allow_other option and see if it helps.

**Comment by bfleischer** [comment]
I can reproduce the issue with the C loopback file system. However, with LoopbackFS it works just fine in my case (with or without `allow_root` and `allow_other`).

**Comment by bfleischer** [comment]
It looks like the issue is caused by a change in macOS 10.15. loopback uses `opendir(3)`, `readdir(3)` and `closedir(3)` to list the contents of a directory on the backing volume.

When calling `opendir(3)` macOS 10.15 seems to create a view of the current directory contents. This view is not updated when files are added or removed from the directory. That's why duplicated files disappear immediately after they are created, they are not in the (now outdated) view. On macOS 10.14 the view is updated automatically to reflect the new directory contents.

From what I can tell, the macOS 10.14 behavior seems to be the standard on other operation systems as well.

**Comment by bfleischer** [comment]
The above commit fixes the loopback issue on macOS 10.15. No FUSE update is required.

**Comment by joconnorak** [comment]
Thanks!
Will try out your changes to the C loopback myself.

**Comment by fredriklindellckp** [comment]
Excellent, will try the changes

**Comment by fredriklindellckp** [comment]
Tried it and works. Thanks

**Comment by mishz** [comment]
https://github.com/osxfuse/osxfuse/issues/627#issuecomment-537345757
