### ISSUE TITLE
MacOS 10.14.6 kernel panic

### ISSUE THREAD

**Issue by ipleten** [osxfuse/osxfuse#629]
I'm not sure that osxfuse is culprit. I'm trying to run 'telepresence' to connect to k8s cluster via VPN
`
telepresence --swap-deployment pipe-test-977 --namespace ps --docker-run --rm -it pipe-test --method container --expose --port 8080 `

> Anonymous UUID:       572C7423-D827-9959-B211-EC5D6599E6C8
> 
> Mon Sep 30 09:50:02 2019
> 
> *** Panic Report ***
> panic(cpu 2 caller 0xffffff8006f1e8e0): assertion failed: m->m_flags & M_PKTHDR, file: /BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4903.271.2/bsd/kern/uipc_mbuf2.c, line: 630
> Backtrace (CPU 2), Frame : Return Address
> 0xffffff9219ba34a0 : 0xffffff80069ae6ed 
> 0xffffff9219ba34f0 : 0xffffff8006aea185 
> 0xffffff9219ba3530 : 0xffffff8006adb8ba 
> 0xffffff9219ba35a0 : 0xffffff800695bb40 
> 0xffffff9219ba35c0 : 0xffffff80069ae107 
> 0xffffff9219ba36e0 : 0xffffff80069adf53 
> 0xffffff9219ba3750 : 0xffffff8006f1e8e0 
> 0xffffff9219ba3790 : 0xffffff8006d917b3 
> 0xffffff9219ba3b00 : 0xffffff8006dbb695 
> 0xffffff9219ba3c50 : 0xffffff8006f24f9b 
> 0xffffff9219ba3d70 : 0xffffff8006f362a8 
> 0xffffff9219ba3e70 : 0xffffff8006f367c4 
> 0xffffff9219ba3f40 : 0xffffff8006fba5ed 
> 0xffffff9219ba3fa0 : 0xffffff800695c306 
> 
> BSD process name corresponding to current thread: com.docker.vpnki
> 
> Mac OS version:
> 18G103
> 
> Kernel version:
> Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
> Kernel UUID: C41337A1-0EC3-3896-A954-A1F85E849D53
> Kernel slide:     0x0000000006600000
> Kernel text base: 0xffffff8006800000
> __HIB  text base: 0xffffff8006700000
> System model name: MacBookPro11,4 (Mac-06F11FD93F0323C5)
> 
> System uptime in nanoseconds: 1937619566828
> last loaded kext at 1824223018154: com.github.osxfuse.filesystems.osxfuse	3.10.2 (addr 0xffffff7f899e8000, size 106496)
> last unloaded kext at 1927032097327: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f88daa000, size 32768)
> loaded kexts:
> com.github.osxfuse.filesystems.osxfuse	3.10.2
> com.netskope.client.nsIPFilterNKE	1
> org.virtualbox.kext.VBoxNetAdp	6.0.10
> org.virtualbox.kext.VBoxNetFlt	6.0.10
> com.carbonblack.CbOsxSensorNetmon	1906.04.62fc5
> org.virtualbox.kext.VBoxUSB	6.0.10
> org.virtualbox.kext.VBoxDrv	6.0.10
> com.carbonblack.CbOsxSensorProcmon	1906.04.62fc5
> com.carbonblack.cbsystemproxy.62fc5	1906.04.62fc5
> com.symantec.ips.kext	14.2.1f52
> com.symantec.nfm.kext	14.2.1f52
> com.symantec.internetSecurity.kext	14.2.1f52
> com.symantec.SymXIPS	8.2.2
> com.apple.fileutil	20.036.15
> com.apple.driver.AudioAUUC	1.70
> com.apple.driver.AppleGraphicsDevicePolicy	3.50.12
> com.apple.filesystems.autofs	3.0
> com.apple.AGDCPluginDisplayMetrics	3.50.12
> com.apple.driver.AppleHV	1
> com.apple.iokit.IOUserEthernet	1.0.1
> com.apple.iokit.IOBluetoothSerialManager	6.0.14d3
> com.apple.driver.AppleUpstreamUserClient	3.6.5
> com.apple.driver.AGPM	110.25.11
> com.apple.driver.ApplePlatformEnabler	2.7.0d0
> com.apple.driver.X86PlatformShim	1.0.0
> com.apple.driver.pmtelemetry	1
> com.apple.driver.AppleIntelHD5000Graphics	12.1.0
> com.apple.Dont_Steal_Mac_OS_X	7.0.0
> com.apple.driver.AppleHDA	282.54
> com.apple.driver.eficheck	1
> com.apple.driver.AppleBacklight	170.12.12
> com.apple.driver.AppleThunderboltIP	3.1.2
> com.apple.iokit.BroadcomBluetooth20703USBTransport	6.0.14d3
> com.apple.driver.AppleLPC	3.1
> com.apple.driver.AppleOSXWatchdog	1
> com.apple.driver.AppleSMCLMU	212
> com.apple.driver.AirPort.BrcmNIC	1400.1.1
> com.apple.driver.AppleCameraInterface	6.8.0
> com.apple.driver.AppleIntelFramebufferAzul	12.1.0
> com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
> com.apple.driver.AppleMCCSControl	1.5.9
> com.apple.driver.AppleUSBCardReader	456.260.3
> com.apple.driver.AppleTopCaseHIDEventDriver	138.4
> com.apple.driver.AppleUSBTopCaseDriver	138.4
> com.apple.filesystems.apfs	945.275.7
> com.apple.driver.AppleAHCIPort	329.260.5
> com.apple.driver.AppleVirtIO	2.1.3
> com.apple.filesystems.hfs.kext	407.200.4
> com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
> com.apple.BootCache	40
> com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
> com.apple.AppleSystemPolicy	1.0
> com.apple.private.KextAudit	1.0
> com.apple.driver.AppleSmartBatteryManager	161.0.0
> com.apple.driver.AppleHPET	1.8
> com.apple.driver.AppleACPIButtons	6.1
> com.apple.driver.AppleRTC	2.0
> com.apple.driver.AppleSMBIOS	2.1
> com.apple.driver.AppleACPIEC	6.1
> com.apple.driver.AppleAPIC	1.7
> com.apple.nke.applicationfirewall	201
> com.apple.security.TMSafetyNet	8
> com.apple.iokit.IOUSBUserClient	900.4.2
> com.apple.kext.triggers	1.0
> com.apple.iokit.IOAVBFamily	760.6
> com.apple.plugin.IOgPTPPlugin	740.2
> com.apple.iokit.IOEthernetAVBController	1.1.0
> com.apple.iokit.IOSkywalkFamily	1
> com.apple.driver.AppleSSE	1.0
> com.apple.driver.DspFuncLib	282.54
> com.apple.kext.OSvKernDSPLib	528
> com.apple.AppleGPUWrangler	3.50.12
> com.apple.driver.AppleBacklightExpert	1.1.0
> com.apple.iokit.IONDRVSupport	530.51
> com.apple.driver.AppleGraphicsControl	3.50.12
> com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.14d3
> com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.14d3
> com.apple.iokit.IOBluetoothHostControllerTransport	6.0.14d3
> com.apple.driver.AppleHDAController	282.54
> com.apple.iokit.IOHDAFamily	282.54
> com.apple.iokit.IOAudioFamily	206.5
> com.apple.vecLib.kext	1.2.0
> com.apple.iokit.IO80211Family	1200.12.2
> com.apple.driver.mDNSOffloadUserClient	1.0.1b8
> com.apple.driver.corecapture	1.0.4
> com.apple.AppleGraphicsDeviceControl	3.50.12
> com.apple.iokit.IOAcceleratorFamily2	404.14
> com.apple.iokit.IOSurface	255.6.1
> com.apple.driver.X86PlatformPlugin	1.0.0
> com.apple.driver.IOPlatformPluginFamily	6.0.0d8
> com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
> com.apple.driver.AppleSMBusController	1.0.18d1
> com.apple.iokit.IOGraphicsFamily	530.66
> com.apple.driver.AppleActuatorDriver	2450.1
> com.apple.driver.AppleHSBluetoothDriver	138.4
> com.apple.driver.IOBluetoothHIDDriver	6.0.14d3
> com.apple.iokit.IOBluetoothFamily	6.0.14d3
> com.apple.driver.AppleHIDKeyboard	208
> com.apple.driver.AppleMultitouchDriver	2450.1
> com.apple.driver.AppleInputDeviceSupport	2440.2
> com.apple.driver.usb.IOUSBHostHIDDevice	1.2
> com.apple.driver.usb.networking	5.0.0
> com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
> com.apple.driver.AppleThunderboltDPInAdapter	5.6.9
> com.apple.driver.AppleThunderboltDPAdapterFamily	5.6.9
> com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.5
> com.apple.iokit.IOAHCIBlockStorage	301.270.1
> com.apple.driver.AppleThunderboltNHI	4.7.9
> com.apple.iokit.IOThunderboltFamily	6.8.6
> com.apple.driver.usb.AppleUSBXHCIPCI	1.2
> com.apple.driver.usb.AppleUSBXHCI	1.2
> com.apple.iokit.IOAHCIFamily	288
> com.apple.iokit.IOSerialFamily	11
> com.apple.filesystems.hfs.encodings.kext	1
> com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
> com.apple.iokit.IOUSBFamily	900.4.2
> com.apple.driver.AppleUSBHostMergeProperties	1.2
> com.apple.driver.AppleEFINVRAM	2.1
> com.apple.driver.AppleEFIRuntime	2.1
> com.apple.iokit.IOSMBusFamily	1.1
> com.apple.iokit.IOHIDFamily	2.0.0
> com.apple.security.quarantine	3
> com.apple.security.sandbox	300.0
> com.apple.kext.AppleMatch	1.0.0d1
> com.apple.driver.DiskImages	493.0.0
> com.apple.driver.AppleFDEKeyStore	28.30
> com.apple.driver.AppleEffaceableStorage	1.0
> com.apple.driver.AppleKeyStore	2
> com.apple.driver.AppleUSBTDM	456.260.3
> com.apple.driver.AppleMobileFileIntegrity	1.0.5
> com.apple.iokit.IOUSBMassStorageDriver	145.200.2
> com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
> com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
> com.apple.iokit.IOStorageFamily	2.1
> com.apple.kext.CoreTrust	1
> com.apple.driver.AppleCredentialManager	1.0
> com.apple.driver.KernelRelayHost	1
> com.apple.iokit.IOUSBHostFamily	1.2
> com.apple.driver.usb.AppleUSBCommon	1.0
> com.apple.driver.AppleBusPowerController	1.0
> com.apple.driver.AppleSEPManager	1.0.1
> com.apple.driver.IOSlaveProcessor	1
> com.apple.iokit.IOTimeSyncFamily	740.2
> com.apple.iokit.IONetworkingFamily	3.4
> com.apple.iokit.IOReportFamily	47
> com.apple.driver.AppleACPIPlatform	6.1
> com.apple.driver.AppleSMC	3.1.9
> com.apple.iokit.IOPCIFamily	2.9
> com.apple.iokit.IOACPIFamily	1.4
> com.apple.kec.pthread	1
> com.apple.kec.Libm	1
> com.apple.kec.corecrypto	1.0
> 
> EOF
> Model: MacBookPro11,4, BootROM 194.0.0.0.0, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.29f24
> Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
> Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
> Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
> AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
> Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
> Network Service: Wi-Fi, AirPort, en0
> Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
> USB Device: USB 3.0 Bus
> USB Device: Apple Internal Keyboard / Trackpad
> USB Device: Bluetooth USB Host Controller
> Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
>

**Comment by bfleischer** [comment]
FUSE is not to blame for this crash. It does not appear in the back trace that lead to the crash. You could try to report the crash to the docker team. The current process that triggered the panic is `com.docker.vpnki`.
