### ISSUE TITLE
Cant open extensions or download 3rd party applications

### ISSUE THREAD

**Issue by chavo163** [osxfuse/osxfuse#634]

**Comment by bfleischer** [comment]
Could you provide some information as to what is not working and how this is related to FUSE?

**Comment by chavo163** [comment]
<img width="481" alt="Screen Shot 2019-10-11 at 1 15 22 AM" src="https://user-images.githubusercontent.com/56419619/66626158-37dfa880-ebc5-11e9-9ead-d189ffe219d9.png">
<img width="686" alt="Screen Shot 2019-10-11 at 1 15 30 AM" src="https://user-images.githubusercontent.com/56419619/66626160-37dfa880-ebc5-11e9-9c21-890f21144e8a.png">
<img width="572" alt="Screen Shot 2019-10-11 at 1 15 40 AM" src="https://user-images.githubusercontent.com/56419619/66626161-37dfa880-ebc5-11e9-92f4-5348c82a437b.png">

**Comment by chavo163** [comment]
<img width="668" alt="Screen Shot 2019-10-11 at 1 20 48 AM" src="https://user-images.githubusercontent.com/56419619/66626220-66f61a00-ebc5-11e9-9d3d-86c258ebdea2.png">

**Comment by bfleischer** [comment]
Please report the issue to the pCloud team. It looks like they are shipping an old version of FUSE.
