### ISSUE TITLE
Failed installation of osxfuse on 10.15 Catalina

### ISSUE THREAD

**Issue by gioalex** [osxfuse/osxfuse#636]
Hi all,
here the commands used to install osxfuse.

In the main log I saw a 404 error while fetching osxfuse-3.8.3_0.**darwin_19**.x86_64.tbz2 package.
Hope this help..

tnks
Alessandro

alex@iMac-di-Alessandro bindfs-1.14.1 % sudo port install osxfuse
Password:
--->  Computing dependencies for osxfuse
--->  Fetching archive for osxfuse
Warning: Your DNS servers incorrectly claim to know the address of nonexistent hosts. This may cause checksum mismatches for some ports. See this page for more information: <https://trac.macports.org/wiki/MisbehavingServers>
--->  Attempting to fetch osxfuse-3.8.3_0.darwin_19.x86_64.tbz2 from https://packages.macports.org/osxfuse
--->  Attempting to fetch osxfuse-3.8.3_0.darwin_19.x86_64.tbz2 from http://lil.fr.packages.macports.org/osxfuse
--->  Attempting to fetch osxfuse-3.8.3_0.darwin_19.x86_64.tbz2 from http://fco.it.packages.macports.org/mirrors/macports-packages/osxfuse
--->  Building osxfuse
Error: Failed to build osxfuse: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port osxfuse failed

alex@iMac-di-Alessandro bindfs-1.14.1 % sudo port install osxfuse
Password:
--->  Computing dependencies for osxfuse
--->  Fetching archive for osxfuse
Warning: Your DNS servers incorrectly claim to know the address of nonexistent hosts. This may cause checksum mismatches for some ports. See this page for more information: <https://trac.macports.org/wiki/MisbehavingServers>
--->  Attempting to fetch osxfuse-3.8.3_0.darwin_19.x86_64.tbz2 from https://packages.macports.org/osxfuse
--->  Attempting to fetch osxfuse-3.8.3_0.darwin_19.x86_64.tbz2 from http://lil.fr.packages.macports.org/osxfuse
--->  Attempting to fetch osxfuse-3.8.3_0.darwin_19.x86_64.tbz2 from http://fco.it.packages.macports.org/mirrors/macports-packages/osxfuse
--->  Building osxfuse
Error: Failed to build osxfuse: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_fuse_osxfuse/osxfuse/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port osxfuse failed

Main log here:

[main.log](https://github.com/osxfuse/osxfuse/files/3731073/main.log)

**Comment by bfleischer** [comment]
Please raise the issue with the MacPorts team. MacPorts ships an outdated version of FUSE that is not compatible with macOS Catalina. The easiest way to resolve this issue might be downloading the installer from https://osxfuse.github.io and installing it manually.

If you are interested in the full story, see https://github.com/osxfuse/osxfuse/issues/590 and the linked issues.

**Comment by gioalex** [comment]
Thank you bfleischer for your response!

**Comment by leszek-s** [comment]
After installing osxfuse manually from dmg downloaded from https://osxfuse.github.io/ you might want to execute this:
sudo ln -s /usr/local/lib/pkgconfig/fuse.pc /opt/local/lib/pkgconfig/fuse.pc
After that mac ports will be able to detect that you already have osxfuse and will not throw errors when you install other packages that depend on osxfuse.
