### ISSUE TITLE
Version 3.10.3 -- The FUSE for macOS installation package is not compatible with this version of macOS Catalina.

### ISSUE THREAD

**Issue by antoniosamuels** [osxfuse/osxfuse#638]

**Comment by fulldecent** [comment]
It is possible that FUSE died with Catalina and won't come back. If so, the issue is that it should be stated correctly here https://github.com/osxfuse/osxfuse.github.com/blob/master/index.html#L8

**Comment by bfleischer** [comment]
@antoniosamuels You are not providing any information at all. There is nothing anyone could do to help you without knowing what you are trying to accomplish. I'm assuming you are trying to install FUSE, right? 

@fulldecent What makes you think FUSE died? Version 3.10 is compatible with Catalina.

**Comment by fulldecent** [comment]
Sorry. I have been misreading https://library.panic.com/transmit/transmit5/transmit-disk/#transmit-disk-has-been-discontinued-as-of-transmit-5-6-0 to understand that Catalina does not support FUSE (which is part of Transmit Disk). Please ignore my note above.

**Comment by antoniosamuels** [comment]
Problem resolved
