### ISSUE TITLE
fs_setattr in a fuse_lowlevel implementation sends invalid mode

### ISSUE THREAD

**Issue by tommetge** [osxfuse/osxfuse#64]
After extensive testing, it appears that setattr is called with impossible modes. Example values being passed (these are each octals) on create/truncate/chmod and other system calls:

- 60144
- 70652
- 130357
- 60063

etc.

The last 3 octets are perfectly fine - it's the random value in the 5th slot that doesn't make sense. For example, 60144, according to the stat man page (10.8.2) says that 6 == S_IFBLK (block special). Huh?

Is there an alternative definition for the mode bits being provided?

Thanks!

**Comment by bfleischer** [comment]
No reply in three years, closed.
