### ISSUE TITLE
volname not being respected

### ISSUE THREAD

**Issue by kevin52408** [osxfuse/osxfuse#640]
A co-worker who first upgraded to Catalina noticed, and then when I upgrade my machine it started doing it as well. We both are running 3.10.3. If I run:

```
sudo mkdir /Volumes/localDir
sudo chown me:staff /Volumes/localDir
sshfs me@remote.server:/remoteDir /Volumes/localDir -o volname=specialName
```

then the mount will be labeled as 'remoteDir' in Finder. But if I have the remote server mount at root:

```
sudo mkdir /Volumes/localDir
sudo chown me:staff /Volumes/localDir
sshfs me@remote.server:/ /Volumes/localDir -o volname=specialName
```

then the mount will be labeled 'localDir', but in neither instance will it use 'specialName'. I tried adding -d to the sshfs command, but I wasn't able to make much sense of it. If it would help to have some sort of debug info just let me know what you need.

**Comment by bfleischer** [comment]
The `volname` option works fine for me on Catalina when using the SSHFS 2.5.0 build from https://osxfuse.github.io.

```
sudo mkdir /Volumes/test    
sudo chown benjamin:staff /Volumes/test 
sudo chmod 700 /Volumes/test
sshfs benjamin@172.16.1.1:/ /Volumes/test -ovolname=HelloWorld -oallow_other -odefer_permissions 
```

**Comment by kevin52408** [comment]
I was using the same version of sshfs. There was an update for Catalina that came out this week (10.15.3) and that fixed the issue.
