### ISSUE TITLE
Unsupported macOS Version

### ISSUE THREAD

**Issue by jonallen356** [osxfuse/osxfuse#641]
I just updated my Mac to Catalina (10.15) and am now receiving an error message that pops up in about six successive dialogue boxes. When I clear them out by clicking OK, they just come back over top of whatever window I am working on. I cannot function with this happening. Here is the error message:

> The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS.

I have updated to the latest version of FUSE from the website and restarted with no change.

Can anyone help me solve this issue?

**Comment by bfleischer** [comment]
You are probably using an unofficial version of FUSE and need to update that version as well. Some developers took the FUSE source code, recompiled it and distributed it as part of their apps, without properly rebranding it. Which FUSE-based apps are you using?

**Comment by jonallen356** [comment]
Thank you, I just figured it out. I am using Citrix ShareFile and after updating that app I have no more error messages.
