### ISSUE TITLE
Debug output problem

### ISSUE THREAD

**Issue by hasse69** [osxfuse/osxfuse#643]
I am currently debugging a problem a user is having and debug output looks a bit strange
```
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40
   unique: 2, error: 0 (Undefined error: 0), outsize: 96
```
I would have expected error 0 to be presented as "success"?
This is supposed to be version 3.10.3 of OSXFUSE.
I snooped around a bit in source code and could only find this in fuse/lib/fuse_lowlevel.c
```
static int fuse_send_msg(struct fuse_ll *f, struct fuse_chan *ch,
                         struct iovec *iov, int count)
{
        struct fuse_out_header *out = iov[0].iov_base;

        out->len = iov_length(iov, count);
        if (f->debug) {
                if (out->unique == 0) {
                        fprintf(stderr, "NOTIFY: code=%d length=%u\n",
                                out->error, out->len);
                } else if (out->error) {
                        fprintf(stderr,
                                "   unique: %llu, error: %i (%s), outsize: %i\n",
                                (unsigned long long) out->unique, out->error,
                                strerror(-out->error), out->len);
                } else {
                        fprintf(stderr,
                                "   unique: %llu, success, outsize: %i\n",
                                (unsigned long long) out->unique, out->len);
                }
        }

        return fuse_chan_send(ch, iov, count);
}
```
which looks perfectly fine, error 0 should resolve to the success branch?
The file system is however using the high level API so I am probably looking at the wrong place.
But this was the only piece of code I could find dealing with the debug output. What did I miss?

**Comment by hasse69** [comment]
Ok, I think I have found the cause of this anomaly.

The output is _not_ coming from OSXFUSE, it comes from the MacFUSE compatibility layer.
My file system configuration picked up the MacFUSE library before the OSXFUSE one. 
That seems to be the reason for the problems some users are having. But before closing this issue, one question would be nice to get an answer too. Is MacFUSE really expected to work on e.g. systems like:
```
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G103
```
The reason I ask is simply because I am starting to wonder if we should still try to look for that implementation of FUSE?

**Comment by bfleischer** [comment]
The last version of macOS fully supported by the original MacFUSE was Mac OS X 10.5.

You should never link against the compatibility layer. FUSE for macOS does not even contain headers for the linking against the compatibility layer. It exists only to support legacy MacFUSE file systems binaries that might still be floating around. It is an optional install that the user has to check manually to install.

In version 4 of FUSE for macOS the compatibility layer will be gone.

**Comment by hasse69** [comment]
Thanks, clear as milk :)
Closing.
