### ISSUE TITLE
Problem with deleting .docx files

### ISSUE THREAD

**Issue by andreipro1002** [osxfuse/osxfuse#645]
Hello,
It seems to be a problem with deleting the .docx files using the LoopbackFS sample project (https://github.com/osxfuse/filesystems) on OSX Catalina. When deleting the .docx file, the callback removeItemAtPath is not called, and after the file is gone, a temp file .fuse_hidden0000 appears in the same directory. Do you know any solutions for this? Thanks in advance.

**Comment by bfleischer** [comment]
`.fuse_hidden...` files appear in case a running process is still referencing a deleted file (open file handle). The file should disappear when the file handle is closed.
