### ISSUE TITLE
Heads up/warning: BridgeSupport issues on Catalina

### ISSUE THREAD

**Issue by amirrajan** [osxfuse/osxfuse#646]
It's that time of the year again. I'll post updates with regards to Catalina as they come. Keep an eye on the following repo: http://github.com/amirrajan/rubymotion-bridgesupport

**Comment by amirrajan** [comment]
Here's the fixes that worked for me: https://github.com/amirrajan/rubymotion-bridgesupport/commit/e5864430a3b9535fe69a4e91be3acf0f2c769bbe

**Comment by bfleischer** [comment]
FUSE dropped BridgeSupport in version 3.9.0. The feature does not seem to be widely used and was causing many issues.

**Comment by amirrajan** [comment]
No prob! Thanks for letting me know. Our commercial product relies of BridgeSupport, so we always have a working version (in the off chance y'all decide to reintegrate BridgeSupport).
