### ISSUE TITLE
GCC not listed as dependency

### ISSUE THREAD

**Issue by lukelane124** [osxfuse/osxfuse#647]
When install sshfs on Catalina I get an error about [no installed system compiler capable of compiling python available, please install gcc] which in my opinion should already be there...

I'm 100% not familiar with the brew backend system, so it may be a python issue and not an sshfs issue.
[Command output.txt](https://github.com/osxfuse/osxfuse/files/3832866/file2.txt)

**Comment by bfleischer** [comment]
This is not a FUSE issue. Please raise this issue with the Homebrew team.
