### ISSUE TITLE
Can't mount EFS drives in software, unsure of next step

### ISSUE THREAD

**Issue by jch708** [osxfuse/osxfuse#648]
A forewarning: I'm new to GitHub, coding, and third-party programming in general so bear with me!

I believe an issue like this has been discussed before on here, but unsure it relates specifically to this issue: I currently work at a media company that utilizes EditShare for file storage, where a few of us have updated to Catalina. ES mounts drives either through EFS (Amazon's Elastic File Storage, I believe) and Native SMB. 

Connecting via SMB is fine...
![Screen Shot 2019-11-12 at 12 04 25 PM](https://user-images.githubusercontent.com/57685318/68706782-55e25500-0545-11ea-9fdd-9ae41b710678.png)

...but upon the new update, we received this error: 
![Screen Shot 2019-11-12 at 12 04 38 PM](https://user-images.githubusercontent.com/57685318/68706698-26cbe380-0545-11ea-9b0f-506ee8e45602.png)

I've tried the age-old "uninstall FUSE -> download/reinstall -> restart", and a few other "turn it off/turn it on again", but can't seem to find a solution. 

Any thoughts on troubleshooting? Again, thanks in advance if this comes off like a caveman issue.

**Comment by bfleischer** [comment]
You need to update your EditShare client software. EditShare is using a custom version of FUSE.
