### ISSUE TITLE
Not working on Catalina 10.15.1

### ISSUE THREAD

**Issue by arsayu** [osxfuse/osxfuse#650]
Im unable to paste on NTFS drive.
Already updated FUSE on 3.10.3

**Comment by umlmaster** [comment]
Same problem here: read works fine, write not available

**Comment by bfleischer** [comment]
You probably need to (re-)install NTFS-3G. FUSE on its own does not support writing to NTFS volumes. FUSE is a building block used by NTFS-3G to add NTFS write support to macOS.

Please see https://github.com/osxfuse/osxfuse/wiki/NTFS-3G
