### ISSUE TITLE
Rejecting Finder eject

### ISSUE THREAD

**Issue by kainjow** [osxfuse/osxfuse#651]
We use `fuse_setup()` and then `fuse_loop_mt()`. In Finder if you eject the volume, `fuse_loop_mt` exits with 0. Is there a way to hook into this functionality to provide better user experience, such as prompting the user to quit the client program?

**Comment by bfleischer** [comment]
Have you tired looking into the DIskArbitration API? As far as I remember it allows you to interrupt unmounts. `DARegisterDiskUnmountApprovalCallback` might be what you are looking for.
