### ISSUE TITLE
ABI incompatibility with kexts compiled with SDK < 10.10.

### ISSUE THREAD

**Issue by dverevkin** [osxfuse/osxfuse#652]
Hello!
I've encountered compatibility problem of my kext that was built with SDK 10.9 with the latest versions of osxfuse (VeraCrypt, Boxcryptor). When I call vnode_getattr in my kext with vnode located on fuse filesystem, kernel crashes with panic report. According to this report there was an attempt to access memory page missed in RAM (CR2 register stores this address). Over time investigating the problem, I've noticed the following:
1. Size of vnode_attr struct differs on 10.9 and 10.10+. But its ABI achieved by va_active and va_supported bitfields;
2. Thus my code compiled with 10.9 allocates less memory on stack to keep instance of vnode_attr struct, than code, compiled with 10.10+;
3. When I call vnode_getattr like this:
```
...
vnode_attr attr;
VATTR_INIT(&attr);
VATTR_WANTED(&attr, va_fsid);
if ((error = vnode_getattr(vnode, &attr, vfs_context)) != 0)
 return error;
if (!VATTR_IS_SUPPORTED(&attr, va_fsid))
return ENOTSUP;
... // here we can use attr.va_fsid
```
I expect only va_fsid field will be filled. But osxfuse implementation also fills va_fsid64 (at least);
4. There is no va_fsid64 field in vnode_attr structure in SDK 10.9, so osxfuse implementation writes its value behind the end of the stack memory, allocated for vnode attributes, corrupting the stack.
5. When my code tries to read memory pointed by corrupted stack, it crashes the system.

Please, investigate.

**Comment by bfleischer** [comment]
The issue should be fixed in the upcoming 3.10.4 release.
