### ISSUE TITLE
Finder Doesn't Respond while SSHFS is waiting for Password

### ISSUE THREAD

**Issue by pale2hall** [osxfuse/osxfuse#653]
Dumb weird edge case.

I have my password for an ssh server saved in an image document on my Mac.  I used sshfs to mount a remote server, and when it asked for the password, I went to go open the Image.  Finder couldn't open the Image "Preview" Viewer while SSHFS was waiting for my password.  When I tried to relaunch Finder, thinking it had crashed, it relaunched, but wouldn't let me open a finder window. 

I assume that OSXFuse/SSHFS causes a type of system-wide hang while it is in the process of mounting a drive.  This isn't really a big issue, but one I thought I would bring to your attention, and now that I know it happens I will be more aware of it in the future.

Great software, and a godsend.  Hope someone with the same edge/corner case finds this note useful.

```

OSX Catalina 10.15 (19A602)
MacBook Pro (15-inch, 2018)
2.2 GHz 6-Core Intel Core i7
16 GB 2400 MHz DDR4
Radeon Pro 555X 4 GB
Intel UHD Graphics 630 1536 MB


  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	1037.0.78.0.0 (iBridge: 17.16.10572.0.0,0)
```

**Comment by zehongs** [comment]
Same problem with Catalina 10.15.4. But mine is worse, since it couldn't establish a mount point correctly. I had to shutdown mac to bring everything back.

**Comment by zehongs** [comment]
I just found that I need manually give the `full disk access permission` to my terminal (in my case, iTerm). And everything works fine now!

**Comment by bfleischer** [comment]
The new 4.6.2 release addresses the hanging issue.
