### ISSUE TITLE
OS X wont boot after installing (stop sign). How to completely uninstall from terminal?

### ISSUE THREAD

**Issue by lgander** [osxfuse/osxfuse#656]
I need to uninstall from terminal. Which files should i remove?
Thanks

**Comment by lgander** [comment]
I searched *osxfuse* and deleted everything including that name. Still unable to boot. 
Hopefully there are some files I´m missing and someone can point me to them.

**Comment by vincbeaulieu** [comment]
After restarting my computer, my finder stop booting, it get stuck at loading. So I've uninstalled FuseOSX using safe mode and I had the same issues. But now, after uninstall, even in safe mode the finder does boot.

**Comment by bfleischer** [comment]
It is very unlikely FUSE for macOS is to blame for this. FUSE is a completely passive component. The FUSE kernel extension is not even loaded automatically on system starts. This means that, unless you are using an application, that mounts a FUSE volume on system starts, FUSE can in no way interfere with macOS starts.

The most important file to remove would be the FUSE file system bundle which is located at /Library/Filesystems/osxfuse.fs. The FUSE kernel extension (which is part of the file system bundle) in the only FUSE component that hooks into the system. The rest is just a bunch libraries and the preference pane which cannot interfere with system starts.

To uninstall the rest run the FUSE uninstaller in the FUSE disk image after your system starts again. But like I said I highly doubt FUSE is to blame for this.

**Comment by lgander** [comment]
Ok, so i think it was a problem with paragon ntfs. Here is what happened to me, and how I fixed it:

First I Installed paragon. Asked me to restart. After restarting I couldn´t boot (stop sign). Solution to that:
1- Boot in recovery mode (cmd+r), open disk utility, mount disk, open terminal
2- `find / -name *paragon*`
3- `rm “path/file”` (copied every path/file that showed after the "find" command). if the file is a directory, then you should: `rm -rf "path/file"`
4- `find / -name *ufsd*`
5- also removed (rm) everything with ufsd on its name.
6- to clear cache: `rm -rf /system/library/caches/com.apple.kext.caches/startup/`

Then it booted fine, and I installed OSX Fuse. After that, same stop sign. solution:
1- `find / -name *osxfuse*`
2- `rm` (or `rm -rf` if its a folder) everything listed there
3- `find / -name *ntfs*`
4- you are going to see 2 files (actually folders) on the recovery partition named **ntfs.kext** and **ntfs.fs**. You are also going to see them both on your **/volume/harddrive/...**. You have to delete the ones on your volume, and then copy both from your recovery partition to your volume. 
5- boot and reinstall OSX Fuse

I guess that those files got corrupted with paragon, and then installing osxfuse crashed everything again. So MAYBE, just replacing both files would work and there is no need to manually remove OSX Fuse. 

It took me quite some time to figure this out. Hope someone finds this info helpful.

**Comment by bfleischer** [comment]
@legandro Thanks for posting your findings.
