### ISSUE TITLE
$MFTMirr does not match $MFT (record 3)

### ISSUE THREAD

**Issue by avatar-lavventura** [osxfuse/osxfuse#658]
I have upgraded my macOS from High Sierra to Catalina, which, I think, causes for me to have following error. Is there any way to fix this error? 

    $ mkdir /Volumes/FOLDER
    $ sudo /usr/local/bin/ntfs-3g /dev/disk2s1 /Volumes/FOLDER -olocal -oallow_other -o auto_xattr    
    $MFTMirr does not match $MFT (record 3).
    Failed to mount '/dev/disk2s1': Input/output error
    NTFS is either inconsistent, or there is a hardware fault, or it's a
    SoftRAID/FakeRAID hardware. In the first case run chkdsk /f on Windows
    then reboot into Windows twice. The usage of the /f parameter is very
    important! If the device is a SoftRAID/FakeRAID then first activate
    it and mount a different device under the /dev/mapper/ directory, (e.g.
    /dev/mapper/nvidia_eahaabcc1). Please see the 'dmraid' documentation
    for more details.

**Comment by bfleischer** [comment]
I'm sorry, but I cannot help you with this. Please note that NTFS-3G and FUSE for macOS are independent projects. Should you run into NTFS-3G related issues, please raise the issue with the NTFS-3G maintainers.

**Comment by avatar-lavventura** [comment]
Thanks. Where would be correct place the raise the issue to reach NTFS-3G maintainers?

**Comment by bfleischer** [comment]
You could try the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7. Tuxera is the company behind NTFS-3G.

**Comment by avatar-lavventura** [comment]
They don't have any sign-up option to their forum, and I am unable to open a topic for that reason.
