### ISSUE TITLE
sshfs doesn't work on Catalina

### ISSUE THREAD

**Issue by emmemme** [osxfuse/osxfuse#659]
I migrate to a new mac book pro with Catalina version 10.15.2 (19C57)
I installed with brew osxfuse and sshfs

From terminal
`sshfs -V` 
returns
`SSHFS version 2.10
OSXFUSE 3.10.4
FUSE library version: 2.9.7
fuse: no mount point`

The ssh command with id_rsa works

but when I try to use my old command (it works on High Sierra) 

`sshfs -o defer_permissions -o IdentityFile=/Users/xxx/.ssh/id_rsa,reconnect root@x.x.x.x:/var/www/html /Users/xxx/Remotes/yyy`

listing the folder with `ls -al yyy` results `ls: yyy: Device not configured`

What can I do to solve this problem?

**Comment by bfleischer** [comment]
I'm sorry but your bug report does not provide much information to go on. Which version of FUSE and SSHFS are you using? What exactly is not working? Do you see an error message?

FUSE for macOS 3.10 supports macOS Catalina. SSHFS should run fine, too. Can you check if you are using up-to-date versions of FUSE and SSHFS.

**Comment by emmemme** [comment]
Sorry. The problem was a lack of permissions on local folder. I changed them and everything works!
