### ISSUE TITLE
Finder stop responding when connection drop

### ISSUE THREAD

**Issue by vincbeaulieu** [osxfuse/osxfuse#660]
When my connection drop, the finder stop responding for a good 4 to 5 min.
No kernel panic, no crash report, just Finder is not Responding, then it come back to normal.
I am on Mojave, 10.14.6, using the osxfuse Beta.

**Comment by MarkDana** [comment]
the same issue

**Comment by aboersch** [comment]
the same issue

**Comment by bfleischer** [comment]
Is this still an issue using the latest version of macFUSE?
