### ISSUE TITLE
Notarized program linked to libosxfuse crashes on Catalina

### ISSUE THREAD

**Issue by lins05** [osxfuse/osxfuse#663]
Hi,

We have a program that makes use of osxfuse and libosxfuse, and it seems not working anymore on osx 10.15 after it's notarized.

This happens for both osxfuse 3.8.2 and osxfuse 3.10.4.

What has been done so far:
1. Exclude the libosxfuse.dylib from our application bundle. This doesn't make any difference.
2. Add an entitlement like this:
```xml
...
<key>com.apple.security.cs.allow-jit</key>
<true/>
<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
<true/>
...
```
But that doesn't help either.

Any suggestions what else could we do?

**Comment by bfleischer** [comment]
`com.apple.security.cs.allow-jit` and `com.apple.security.cs.allow-unsigned-executable-memory` should not be required for using FUSE. However, you need to make sure to allow loading third party libraries in your entitlements, otherwise libosxfuse cannot be loaded.

**Comment by lins05** [comment]
@bfleischer  Thanks for the reply! However that doesn't seem to make a difference. Actually I noticed similar things in osxfuse 3.9.0 release announcement:

![Screen Shot 2019-12-18 at 11 36 39 AM](https://user-images.githubusercontent.com/717363/71053841-c7d43c80-218a-11ea-8107-3653cd7183e3.png)

So  yesterday I tried with this updated the entitlement file, but the problem still remains: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-executable-page-protection</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
</dict>
</plist>
```

May I ask do you know any other people have already successfully integrated libosxfuse into a notarized app on catalina?

**Comment by lins05** [comment]
The problem is resolved ... I got some inspiration from https://forums.developer.apple.com/thread/120647 and realized in our program the binary that links to libsoxfuse is launched as a child process of the main program. And it looks like the entitlements attached to the application has no effect on the child process.  After adding the entitlement to the child process binary, it no longer crashes on Catalina.
