### ISSUE TITLE
Can't approve extension with Catalina 10.15.2

### ISSUE THREAD

**Issue by jdeibele** [osxfuse/osxfuse#667]
I'm using Homebrew to install, following the instructions here: https://www.maketecheasier.com/mount-access-ext4-partition-mac/

I rebooted.   When I try to mount the external drive, I get a prompt to approve an extension but the security panel turns blank.   I can't access any of the sub panels, like Firewall.

> sudo ext4fuse /dev/disk4s2 /tmp/Maxtor -o allow_ot
mount_osxfuse: the file system is not available (1)

Which is reasonable, since the extension was not approved.

I've reported this to Apple as well.

I've tried re-installing.   Attached is from logs
![Screen Shot 2020-01-09 at 12 46 40 PM](https://user-images.githubusercontent.com/264802/72104437-492d7380-32e0-11ea-9024-c612353f12e5.png)

[grep for fuse.txt](https://github.com/osxfuse/osxfuse/files/4042469/grep.for.fuse.txt)

**Comment by jarrocha** [comment]
I'll suggest to try and install osxfuse from the website yourself, at the end of the installation you should get a prompt to approve the extension: https://osxfuse.github.io/2019/12/05/OSXFUSE-3.10.4.html

**Comment by jdeibele** [comment]
Thanks very much for the suggestion.   After rebooting, that did work.

It turns out there's nothing on this disk that I want but it's nice to be able and look and be sure before formatting it.

Thoughts on closing this issue?    It might affect other Homebrew users or it might just be something odd on my system.

**Comment by bfleischer** [comment]
I‘m going to close the issue. Homebrew runs the same installer from the website. There should not be a difference. I think this was just a hiccup on your system.

**Comment by alnr** [comment]
I have this same problem (Catalina 10.15.2).

The installer shows this dialog
![Screenshot 2020-01-15 at 12 41 50](https://user-images.githubusercontent.com/3969502/72431162-6a84d880-3794-11ea-8a14-c4715d6b80b1.png)

When clicking on "Open Security & Privacy System Preferences", I get this dialog (no mention of Benjamin Fleischer).
![Screenshot 2020-01-15 at 12 43 03](https://user-images.githubusercontent.com/3969502/72431231-9acc7700-3794-11ea-93f5-eb3df8a1c092.png)

**Comment by bfleischer** [comment]
@alnr You are probably using an app that can create keyboard or mouse events. See https://github.com/osxfuse/osxfuse/issues/437 for reference.

**Comment by alnr** [comment]
Even after booting to safe mode, I still cannot get the message to show up... I think I tried everything.
