### ISSUE TITLE
USB timeouts

### ISSUE THREAD

**Issue by waddles** [osxfuse/osxfuse#670]
I am not certain if this problem is due to `osxfuse` or `fuse2fs` (part of `e2fsprogs`) but when I attempt to write a file on the USB device it seems to time out, causing `fuse2fs` to crash.

I have used Dtrace to trace the calls to osxfuse and results are stored in https://gist.github.com/waddles/a70bbf4098eeda6ab2e5401a0973a63d

Basically, the `release` system call seems to take forever and `fuse2fs` tries to give up by interrupting it, which `osxfuse` appears to ignore.

* macOS Catalina 10.15.2
* osxfuse 3.10.4
* e2fsprogs 1.44.5_1

The [`e2fsprogs`](https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/about/) project has a FUSE driver for ext2 but it does not get built by default. All I had to do was patch the formula by telling it where to search for the `fuse.h` headers.

```
$ cp $(brew formula e2fsprogs) e2fsprogs.rb
$ cat <<EOF | patch
diff --git a/e2fsprogs.rb b/e2fsprogs.rb
index c1b09cd976..b38756042d 100644
--- a/e2fsprogs.rb
+++ b/e2fsprogs.rb
@@ -23,7 +23,7 @@ class E2fsprogs < Formula
     # see https://github.com/Homebrew/homebrew-core/pull/35339
     # and https://sourceforge.net/p/e2fsprogs/discussion/7053/thread/edec6de279/
     system "./configure", "--prefix=#{prefix}", "--disable-e2initrd-helper",
-                          "MKDIR_P=mkdir -p"
+                          "MKDIR_P=mkdir -p", "--enable-fuse2fs", "CPPFLAGS=-I/usr/local/include/osxfuse"

     system "make"
     system "make", "install"
EOF
patching file e2fsprogs.rb

$ brew install --head ./e2fsprogs.rb
```

**Comment by bfleischer** [comment]
From the perspective of FUSE it should not make any difference if the backing storage is connected over USB or is a file on an internal volume. Since it works for the file I don't think this is a general issue with FUSE. I've used fuse-ext2 successfully with an USB memory stick before. That's why I think it would be best to forward your findings to the fuse2fs team. Maybe they can debug the issue.

> Basically, the release system call seems to take forever and fuse2fs tries to give up by interrupting it, which osxfuse appears to ignore.

The only way a file system server can interrupt an ongoing file system operation is by returning an error. Could your elaborate? 

By default the FUSE kernel extension will interrupt file system callbacks after a timeout of 60 seconds. If the file system server does not respond the file system is marked as dead.

**Comment by waddles** [comment]
Well, I tried this again today but with the USB drive connected directly to the mac and it does the same as in the gist.

When doing `echo baz > baz.txt`,  the relevant part is:
```
getattr /foo/baz.txt
   unique: 2, success, outsize: 136
unique: 2, opcode: WRITE (16), nodeid: 3, insize: 84, pid: 3083
write[140198739444144] 4 bytes to 0 flags: 0x1
   write[140198739444144] 4 bytes to 0
   unique: 2, success, outsize: 24
unique: 2, opcode: GETATTR (3), nodeid: 3, insize: 56, pid: 3083
getattr /foo/baz.txt
   unique: 2, success, outsize: 136
unique: 2, opcode: FLUSH (25), nodeid: 3, insize: 64, pid: 3083
flush[140198739444144]
lock[140198739444144] F_SETLK F_UNLCK start: 0 len: 0 pid: 0
   unique: 2, error: -78 (Function not implemented), outsize: 16
unique: 2, opcode: RELEASE (18), nodeid: 3, insize: 64, pid: 3083
release[140198739444144] flags: 0x2
unique: 3, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 148
access / 01
+21605896       0.022 0       access          /foo
+21605994       0.011 -2      getattr         /foo/baz.txt (st_size=0)
+21606151       0.011 0       getattr         /foo (st_size=0)
+21606274       0.005 0       access          /foo
+21606358       0.012 0       getattr         /foo (st_size=0)
+21606549       0.090 0       create          /foo/baz.txt
+21606573       0.002 0       fgetattr        /foo/baz.txt
+21606664       0.006 -2      getattr         /foo/._baz.txt (st_size=0)
+21606751       0.023 0       getattr         /foo/baz.txt (st_size=0)
+21606839       0.008 0       getattr         /foo/baz.txt (st_size=0)
+21606966       0.018 0       getattr         /foo/baz.txt (st_size=0)
+21607724       0.451 4       write_buf       /foo/baz.txt
+21607830       0.009 0       getattr         /foo/baz.txt (st_size=0)
+21607934       0.002 -78     flush           /foo/baz.txt
+21607965       0.014 -78     lock            /foo/baz.txt
unique: 4, opcode: INTERRUPT (36), nodeid: 0, insize: 48, pid: 3083
INTERRUPT: 2
unique: 5, opcode: INTERRUPT (36), nodeid: 0, insize: 48, pid: 148
INTERRUPT: 3

   unique: 2, success, outsize: 16
   unique: 3, success, outsize: 16
+305874479    284266.433 0       release         /foo/baz.txt
+305874492    284049.736 0       access          /
+305894486     15.708 1035    destroy
```

So basically, we see it do `getattr`, `write`, `getattr`, `flush`, `lock`, `release`, `access`. Something is causing it to take about 284 seconds to return from `release`, in which time fuse2fs has timed out and died.

I will try again with fuse-ext2 but it doesn't even want to mount in rw mode for me at the moment.

**Comment by bfleischer** [comment]
There has not been any new information in two months, so I'm going to close the issue.
