### ISSUE TITLE
Build from source fails with Xcode 11

### ISSUE THREAD

**Issue by jandrewb** [osxfuse/osxfuse#672]
I may be doing something wrong, but the project is not building with Xcode 11.3 (on macOS 10.15). Am I missing something obvious, or is Xcode 11 not yet supported?

When I run: 
./build.sh -t distribution

I get the following output:
Assertion 'common_is_variable DEFAULT_SDK_10_15_ARCHITECURES' failed
at common_variable_clone (./build.d/lib/common.sh, line 501)
at common_variable_clone (./build.d/lib/common.sh, line 514)
at build_target_invoke (./build.sh, line 656)
at build_main (./build.sh, line 942)
at main (./build.sh, line 950)
Terminated: 15

**Comment by Stakaitis** [comment]
I'm having the same issue Xcode (Version 11.3.1), macOS Catalina (version 10.15.3)

**Comment by bfleischer** [comment]
The latest version available in source form in the repository is 3.8.3, which does not support running on macOS 10.15. The latest version of FUSE, that supports running on macOS 10.15, is only available in binary form and can be downloaded from https://osxfuse.github.io.
