### ISSUE TITLE
wrong include path?

### ISSUE THREAD

**Issue by robmaz** [osxfuse/osxfuse#673]
Installing the MacOS .dmg via brew cask osxfuse (which appears to just download and run the installer) creates an osxfuse.pc package configuration file in /usr/local/lib/pkgconfig. The include path specified in this file is

  /usr/local/include/osxfuse/fuse

This appears to be incorrect. A fuse.h is already found in /usr/local/include/osxfuse and it appears that fuse apps want to include other headers xxx as <fuse/fuse_xxx.h> – at least I managed to build hadoop's fuse_dfs against osxfuse successfully by changing the include path to /usr/local/include/osxfuse

Not sure where the path is coming from. osxfuse.pc is referenced in scripts in build.d/targets

If the current behavior is intended, why is there a fuse.h in the unreachable osxfuse folder?

**Comment by bfleischer** [comment]
The fuse.h file in /usr/local/include/osxfuse exists only for legacy reasons. This is the intended behavior.
