### ISSUE TITLE
.kext appears to reuse UNIQUE values in successive upcalls

### ISSUE THREAD

**Issue by edmc-ss** [osxfuse/osxfuse#674]
As per FUSE in e.g. Linux, the .Unique field in the InHeader is supposed to be, uh, unique. This is used in order that FUSE might be able to issue multiple such upcalls to the user mode agent and receive responses to them perhaps out of order and be able to sort out which responses go with which requests.

I've logged the unmarshalled InHeader's coming up from OSXFuse .kext and see that they are reused (indeed, I'm seeing 2 and 3 used over and over again).

**Comment by edmc-ss** [comment]
This is perhaps related to my other issue where the .kext would appear to be closing the /dev/osxfuse* file out from under my user mode code (https://github.com/osxfuse/osxfuse/issues/671).

**Comment by edmc-ss** [comment]
I should add that I have not seen a Unique value reused while a prior use of the Unique value was still in use... so perhaps this is "ok". Perhaps the author has an array or something where each slot is simply indexed by Unique and, hence, doesn't need a map-like mechanism to look up the context of the upcall being responded to. Hard to say without confirmation (or seeing the source code :-)).

**Comment by bfleischer** [comment]
Yes, the FUSE kernel extension on macOS reuses tickets, as the requests are called in the kernel extension. But it is ensured that the user space library will not receive calls with the same "unique" value at the same time. The kext only reuses uniques after the user space file system server signals that it is done with the request.

This design decision dates back to the old MacFUSE days and does not cause any issues with libfuse.
