### ISSUE TITLE
Question - KEXs deprecation

### ISSUE THREAD

**Issue by ivancitin** [osxfuse/osxfuse#675]
Hi,

I just went through this page [apple-deprecating-macos-kernel-extensions](https://www.zdnet.com/article/apple-deprecating-macos-kernel-extensions-kexts-is-a-great-win-for-security/) and was wondering how will this affect osxfuse?

Thanks

**Comment by bfleischer** [comment]
It won't affect FUSE since FUSE is not using any of the deprecated APIs. VFS plugins, like the FUSE kernel extension, have not been deprecated by Apple. Furthermore there is no alternative system extension API to develop file systems.

**Comment by ivancitin** [comment]
Good to know, thanks for the clarification.

**Comment by jarrocha** [comment]
Hey Benjamin,
Do you think this FileProvider API is more of an alternative right now? 
[FileProvider API info](https://developer.apple.com/documentation/fileprovider?language=objc)

Do you see this API causing the deprecation of VFS plugins in the future? I know it's hard to tell right now but just wanted to see your thoughts.

**Comment by bfleischer** [comment]
As far as I know, Apple silently removed the FileProvider feature from macOS 10.15 during the beta phase. I don't know if the feature has returned in a recent 10.15.x update, but I don't think it has.

However, the FileProvider API does not allow you to implement fully functional file systems. It is intended for cloud services but not general purpose file systems. FUSE offers much more flexibility and a level of system integration you cannot achieve with the FileProvider API.

**Comment by jarrocha** [comment]
Thanks for your comments.

**Comment by juliangruber** [comment]
We just requested a signing certificate with kext capabilities from apple and this was their response:

> Engineering has reviewed this request and states that the functionality described can be accomplished using the File Provider APIs, and that a kext (and kext signing certificate) is not required.
>
> The File Provider API documentation can be found here:
>
> https://developer.apple.com/documentation/fileprovider

**Comment by bfleischer** [comment]
@juliangruber File Provider support is still not available in macOS 10.15.5. Xcode clearly states: File Provider extensions are not available when building for Mac Catalyst. The documentation is not up to date.

**Comment by rsegretin** [comment]
@juliangruber did they actually point you to use a feature that is just not there? I've been researching ways to create placeholders for files that are only available in a cloud server, and thought I would be able to use File Provider, but it seems it won't be available in Catalina. Only way around might be VFS Kext, but that answer you received kinda worries me.

**Comment by juliangruber** [comment]
I've posted the whole response, unfortunately that's all we got

**Comment by rsegretin** [comment]
Your certificate was intended for Catalina, right?

**Comment by juliangruber** [comment]
That is correct

**Comment by rsegretin** [comment]
I think I'm more worried now. Thanks a lot.
