### ISSUE TITLE
Stall in fuse_unmount after session exit in signal handler

### ISSUE THREAD

**Issue by vasi** [osxfuse/osxfuse#677]
My filesystem [attempts to kill itself in a signal-handler](https://github.com/vasi/squashfuse/blob/master/ll.c#L433-L436) using `fuse_session_exit`, if it's been idle too long. This works fine on Linux. But with osxfuse, the main function stalls when it calls `fuse_unmount`, for around a minute.

Any idea what's going on here?

I tried to look at libfuse for inspiration, and [this commit](https://github.com/osxfuse/fuse/commit/9ff468a18a3ec75fddbabbf5c3a2304c446e4920#diff-72158d2bb895ddc51c4d439bd3d27838) looks interesting. But some bits seem out of date, for example there's no `fuse_chan_cleardisk` in the most recent osxfuse.

**Comment by bfleischer** [comment]
FUSE on macOS might need to flush some dirty pages from kernel memory when you unmount the file system. What you are doing effectively prevents FUSE from doing this. This will lead to data loss in some situations. You are seeing a 60 seconds delay because you are running into a timeout. The FUSE kernel extension is trying communicate with the file system server running in user space, but gives up after waiting for 60 seconds without receiving a reply. To unmount a FUSE file system on macOS, call unmount and let FUSE exist gracefully.

**Comment by vasi** [comment]
So there's no way for a filesystem to cause itself to unmount? It has to be via `unmount` at the command-line?

**Comment by bfleischer** [comment]
Sure there is, call fuse_unmount(). But you will need to wait before until the event loop exits or, in case you implemented your own event loop, wait until you receive a FUSE_DESTROY message from the kernel. The same approach works on Linux as well.

**Comment by bfleischer** [comment]
> I tried to look at libfuse for inspiration, and this commit looks interesting. But some bits seem out of date, for example there's no fuse_chan_cleardisk in the most recent osxfuse.

This commit has not made it way into official releases. I've been trying to use DiskArbitration to unmount FUSE file systems. When support for renaming FUSE volumes is enabled, the mount point of a FUSE volume will change while the file system is mounted. This is where DiskArbitration comes into play.

If you are evaluating FUSE for macOS for commercial use, feel free to contact me. You can find my email address on my GitHub profile.

**Comment by vasi** [comment]
> Sure there is, call fuse_unmount(). But you will need to wait before until the event loop exits or, in case you implemented your own event loop, wait until you receive a FUSE_DESTROY message from the kernel. The same approach works on Linux as well.

Isn't that what I was originally doing?
- Call `fuse_exit_session` to trigger the event loop ending
- Wait for the event loop to end, and control to return to main
- Call fuse_unmount. But it stalls.

Is there a different sequence of events you would expect to work?

The only thing I've been able to make work is actually calling `umount()` in my signal handler. Is that how signal handling for eg: SIGINT is currently working in libfuse?

**Comment by lwoggardner** [comment]
For anyone coming to this later I encountered and solved this dilemma while writing ruby bindings (ffi-libfuse).

The trick for me was that the event loop needs to continue to run **DURING** the execution of `fuse_unmount()`, ie you cannot unmount from the event thread.

Also, if you are using `fuse_exited()` (or the session equivalents) to control the event loop, `fuse_exit()` should not be called until **AFTER** fuse_unmount completes.
