### ISSUE TITLE
iOS FUSE plugin?

### ISSUE THREAD

**Issue by jmonroe91** [osxfuse/osxfuse#678]
Is there a free, standalone open-source FUSE plugin to mount an iOS device as a filesystem? I have looked but can only find such a thing as part of a another application (I think it was iExplorer?)
I want to sync files using rsync to a file manager application on the iOS device.

**Comment by bfleischer** [comment]
I don't know of any stand-alone FUSE file system for mounting iOS devices. 

Please ask questions like this on the [FUSE for macOS Google Group](https://groups.google.com/forum/#!forum/osxfuse-group). The issue tracker should only be used for actual issues.

**Comment by jarrocha** [comment]
A good alternative is to look into the FileProvider API for iOS.
