### ISSUE TITLE
Can't verify GPG signature: sks.keyservers.net reponding with 502 or 504.

### ISSUE THREAD

**Issue by WillSkates** [osxfuse/osxfuse#679]
Hello!

I can't currently verify the gpg signature for any release because sks.keyservers.net is responding with a 502 or 504 error when I access https://sks-keyservers.net/pks/lookup?op=vindex&search=0x135F164B411BAA1F4A4BCD37617A3461802608A1.

Is the key available anywhere else?

Cheers,
Will

**Comment by bfleischer** [comment]
Hi Will, you can download the key from https://osxfuse.github.io/static/53C918C1A2818875.asc.

**Comment by ajay-gh** [comment]
Any chance you could explain, why you wouldn't upload your public (up-to-date) key to a key server, and publish the key's fingerprint on the Macfuse page. This way you don't have to answer repeated questions from users who can't figure it out, and users don't have to wonder why this unusual approach. Thank you for bearing with me.

**Comment by bfleischer** [comment]
@ajay-gh I used to upload the key until the sks key servers went down. Can you suggest a different server?

**Comment by bfleischer** [comment]
I tried uploading the key again. This time it worked. It seems only the web lookup is down.

This one seems to work: http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0x53C918C1A2818875

**Comment by ajay-gh** [comment]
I am using the GPG keychain for Mac. About 1 year ago, the standard key server used by this application got replaced by different / new one ( hkps://keys.openpgp.org ). Since then no problems at all. Interestingly enough, before there was a choice of 3 or 4 keyservers, since the change this is no longer the case.

**Comment by ajay-gh** [comment]
Nothing has changed. After update of the fleiben@... key from 2 keyservers (using GPG keychain), I cannot verify / confirm your actual, valid key ID or fingerprint against a different (trusted) source - e.g. your fingerprint published here on github. My suggestion : publish the fingerprint right here in this thread after verifying it has not expired, and it has the key ID A2818875 (or another one if it has changed).

**Comment by bfleischer** [comment]
Fingerprint: 0093B21EF45D635284F6A14753C918C1A2818875
Long key ID: 53C918C1A2818875
Short Key ID: A2818875

Key on Key Server: http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0x53C918C1A2818875
Key on GitHub: https://osxfuse.github.io/static/53C918C1A2818875.asc

**Comment by ajay-gh** [comment]
Perfect, this should help anybody searching for your public key in the macfuse/osxfuse thread, and trying to match these data. I have just publicly signed your key on hkps://keys.openpgp.org
