### ISSUE TITLE
OSXFuse framework fails to load after Runtime Hardened enabled

### ISSUE THREAD

**Issue by stonespirit** [osxfuse/osxfuse#680]
Hi

OSXFuse framework fails to load after Runtime Hardened enabled,
Step:
1 Run code sign script:  codesign --force --options=runtime --deep -s "xxxxxx" -v  LoopbackFS.app
2 Run LoopbackFS.app, and Crash, Crash log:

Process:               LoopbackFS [65779]
Path:                  /Users/USER/Library/Developer/Xcode/DerivedData/LoopbackFS-hffmrmxbhukvbmegaiowlsgnngiw/Build/Products/Release/LoopbackFS.app/Contents/MacOS/LoopbackFS
Identifier:            com.google.LoopbackFS
Version:               1.0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           LoopbackFS [65779]
User ID:               501

Date/Time:             2020-02-26 14:03:16.184 +0800
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Anonymous UUID:        F33E8719-217B-7DAB-4EA2-F5B0E44342D0

Sleep/Wake UUID:       26DF7237-4C31-43AE-9ED2-44FC97C70A38

Time Awake Since Boot: 84000 seconds
Time Since Wake:       19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Library/Frameworks/OSXFUSE.framework/Versions/A/OSXFUSE
  Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/LoopbackFS-hffmrmxbhukvbmegaiowlsgnngiw/Build/Products/Release/LoopbackFS.app/Contents/MacOS/LoopbackFS
  Reason: no suitable image found.  Did find:
	/Library/Frameworks/OSXFUSE.framework/Versions/A/OSXFUSE: code signing blocked mmap() of '/Library/Frameworks/OSXFUSE.framework/Versions/A/OSXFUSE'
	/Library/Frameworks/OSXFUSE.framework/Versions/A/OSXFUSE: stat() failed with errno=1

Binary Images:
       0x108131000 -        0x108134fff +com.google.LoopbackFS (1.0) <0A70C1D9-7646-3499-86D0-86041F3E53B9> /Users/USER/Library/Developer/Xcode/DerivedData/LoopbackFS-hffmrmxbhukvbmegaiowlsgnngiw/Build/Products/Release/LoopbackFS.app/Contents/MacOS/LoopbackFS
       0x115b6c000 -        0x115bfccb7  dyld (733.8) <EBC07CB6-870A-3A8E-B48A-67F62EA161F3> /usr/lib/dyld
    0x7fff3dc94000 -     0x7fff3dca0ffe  com.apple.NetFS (6.0 - 4.0) <0B2088AE-C16D-3FC3-9445-4EDAD2D51686> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS

Model: MacBookPro12,1, BootROM 189.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.7 GHz, 8 GB, SMC 2.28f7
Graphics: kHW_IntelIris6100Item, Intel Iris Graphics 6100, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54414C41522D4E5544
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54414C41522D4E5544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.106.3 AirPortDriverBrcmNIC-1440.1)
Bluetooth: Version 7.0.3f5, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
USB Device: Lenovo Optical Mouse
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by stonespirit** [comment]
I found same issue, like this:
https://forums.developer.apple.com/thread/118067
https://forums.developer.apple.com/message/390019#390019

Is there any solution about this issue?
Thanks

**Comment by stonespirit** [comment]
MacOS:10.15
XCode:11

**Comment by bfleischer** [comment]
As part of my regression tests I'm building a version of LoopbackFS with the hardened runtime feature enabled. I never ran into any issues with Xcode 10.

Did you make sure to disable library validation when enabling the hardened runtime? Running the codesign command does not suffice.

**Comment by stonespirit** [comment]
Yes, I  have made sure to disable library validation.
I am trying to notarize my app, and "LoopbackFS" is demo, but the steps are same.

**Comment by bfleischer** [comment]
Why are you running codesign manually? When you do this you need to make sure to include the correct entitlements. Please check the entitlements after re-signing LoopbackFS.

**Comment by stonespirit** [comment]
I am trying to notarize my app, and code sign by script

**Comment by stonespirit** [comment]
Thanks, this issue has been resolved by adding codesign --entitlements
