### ISSUE TITLE
Could not load FUSE preference pane in system preferences

### ISSUE THREAD

**Issue by stonespirit** [osxfuse/osxfuse#681]
Could not load FUSE preference pane in system preferences

Step:
1 Click "Fuse"  in system preferences
2 Popup alert "Could not load FUSE preference pane"
3 Reinstall OSXFuse，but still reproduce

MacOS:10.15.3

**Comment by stonespirit** [comment]
Uninstall and reinstall, and resolved

**Comment by Aholicknight** [comment]
I am having this same issue on Big Sur...does anyone know how to fix?
