### ISSUE TITLE
External HDD with FUSE file system won't mount in OS X Catalina

### ISSUE THREAD

**Issue by Vovo232** [osxfuse/osxfuse#682]
Hi guys,

Since I update my MacBook Pro to Catalina FUSE stopped working.

We have 360 VR Camera Nokia OZO and its HDD is formatted with FUSE-PC file system.
It won't mount... 

I can see it in Disk Utility, I can also mount it manualy, but I can't access the files...

Anyone has encountered this kind of issue?

Thank you very much!

**Comment by bfleischer** [comment]
Do you mean NTFS-3G? I don't know what you mean by FUSE-PC file system.

Make sure you update FUSE to the latest version. It might be necessary to re-install NTFS-3G. In any case, please report the issue to the developer of the file system you are using.

**Comment by Vovo232** [comment]
Hi Benjamin,

thank you for reply.

File system Fuse-PC I don’t know either… its dedicated format for Nokia OZO professional VR Cam, unfortunately. 
Nokia support recommended us to upgrade FUSE (we did it as a very first thing)
It is possible that is some kind of NTFS-3G, but anyway…

On MAC with El Capitan (OS 10.11.6) with FUSE 3.7.1. - it works perfectly, but on all our new Macs with Catalina and FUSE 3.10.4 doesn’t…

Without FUSE we can’t see the disk at all, after re-install to 3.10.4 we are able to manually mount the USB disk but we can’t access the files on it… the disk is invisible.
On all Windows computer it works… but its not solution for us (due tons of other software and licenses etc.)

You are my last chance, because nobody helped us, so far. 
In new version of FUSE something has changed… and our solution stopped working.

Thank you very much in advance

Peter
