### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by MichaelVoelkel** [osxfuse/osxfuse#683]
I find nothing about how to use fuse. Is there some page with examples?

**Comment by bfleischer** [comment]
FUSE is a building block used by (third party) file systems. If you are looking for a specific FUSE-based file system, you should find information on how to use the particular file system on the developer's website. If you are a developer looking for example file systems, check the [filesystems](https://github.com/osxfuse/filesystems) repo. 

Please post question like this on the [FUSE Google Group](https://groups.google.com/forum/#!forum/osxfuse-group). The issue tracker should only be used for actual issues.
