### ISSUE TITLE
Files fail to save after enabling "Ignore ownership on this volume"

### ISSUE THREAD

**Issue by kainjow** [osxfuse/osxfuse#684]
Here's a weird one. I reproduced with LoopbackFS.

1. Run a fuse mount
2. Open a file in TextEdit and verify you can save. Keep the file open.
3. On an external volume (you can also use a mounted disk image), Finder > Get Info the volume and uncheck "Ignore ownership on this volume"
4. Go back to the file in TextEdit and try to save. You'll get an error like "The document x could not be saved":

<img width="438" alt="76579838-eb0d4000-648a-11ea-973e-093284e3aa27" src="https://user-images.githubusercontent.com/271035/76580060-be0d5d00-648b-11ea-99aa-9de336fe15a9.png">

**Comment by bfleischer** [comment]
I tried to reproduce the issue on macOS 14 using macFUSE 4.6.2, but saving the file after unchecking "Ignore ownership on this volume" worked fine. Seems the issue has been fixed in the meantime.
