### ISSUE TITLE
[Q] Meaning of "mount_osxfuse: cannot stat the mount point..."?

### ISSUE THREAD

**Issue by GJRobert** [osxfuse/osxfuse#685]
I have used [bindfs](https://bindfs.org/) and osxfuse for a while. But in the recent week, I have encountered twice the situation as described below:

1.  All of sudden, my mounted folders are all unmounted for unknown reason.
2. I try to execute bindfs commands again, with the following error:
```
mount_osxfuse: cannot stat the mount point <path to my mount point>
```

Restarting the system usually makes bindfs work again, but this does re-occur.
How should prevent this?
(Please kindly direct me if there is a more suitable place to ask my question)

**Comment by mikescar** [comment]
Hi @GJRobert Perhaps the google group would be better place to find answer: https://groups.google.com/forum/#!forum/osxfuse-group
