### ISSUE TITLE
OSX Catalina - Cannot move files to trash or delete / Can create, save, rename

### ISSUE THREAD

**Issue by spreaderman** [osxfuse/osxfuse#688]
I am using OSX Catalina with FUSE & sshfs.  Everything works except moving to trash.  I get error 8062 from OSX.  Of course if I use 'rm' at the command line, it works.  Is this a known issue?  I would have thought one could map the 'move to trash' to at least, 'rm'. Not possible?  Any help appreciated.

    sshfs -o allow_other,defer_permissions root@example.com:/ /Users/myuser/Desktop/remoteWebServer

**Comment by tg-z** [comment]
> I am using OSX Catalina with FUSE & sshfs. Everything works except moving to trash. I get error 8062 from OSX. Of course if I use 'rm' at the command line, it works. Is this a known issue? I would have thought one could map the 'move to trash' to at least, 'rm'. Not possible? Any help appreciated.
> 
> ```
> sshfs -o allow_other,defer_permissions [root@example.com](mailto:root@example.com):/ /Users/myuser/Desktop/remoteWebServer
> ```

hi, i'm not sure if its a known issue, but there are a few possible workarounds that might simplify moving something to trash. here's a short shell script/bash function: 
```bash
del () {
echo -e "\x1b[38;5;9m--deleted files/directories--\x1b[0m"
for i
do echo $i 
done

 mv $* ~/.Trash/
 }
```

**Comment by bfleischer** [comment]
This ticket has been inactive for a long time, so I'm closing it. Feel free to open a new ticket in case this is still an issue on macOS 14 and the latest version of macFUSE.
