### ISSUE TITLE
MacOS 10.15.4: mount ok, but ls gives 'operation not permitted'

### ISSUE THREAD

**Issue by PenelopeFudd** [osxfuse/osxfuse#690]
Hi;

I'm trying to mount an AWS S3 bucket on /tmp/my-test-bucket, and getting a frustrating problem:
```
$ cd /tmp

$ aws s3 mb s3://my-test-bucket
$ date | aws s3 cp - s3://my-test-bucket/testfile.txt
$ aws s3 cp s3://my-test-bucket/testfile.txt -
Sat 18 Apr 2020 21:29:03 PDT
$ mkdir my-test-bucket
$ yas3fs --debug -l logfile.txt  s3://my-test-bucket my-test-bucket

$ ls my-test-bucket
ls: my-test-bucket: Operation not permitted

$ ls my-test-bucket/testfile.txt
my-test-bucket/testfile.txt

$ ls -l my-test-bucket/testfile.txt
-rwxr-xr-x  1 PenelopeFudd  staff  29 19 Apr  2020 my-test-bucket/testfile.txt

$ cat my-test-bucket/testfile.txt
cat: my-test-bucket/testfile.txt: Operation not permitted
```
The problem is not with '[yas3fs](https://github.com/danilop/yas3fs)', as it happens with '[sshfs](https://github.com/osxfuse/sshfs)' too:
```
$ cd /tmp

$ mkdir www
$ ssh www 'date > /tmp/my-date.txt'
$ sshfs www:/tmp www
$ ls www
ls: www: Operation not permitted
$ ls -l www/my-date.txt
-rw-------  1 PenelopeFudd  staff  29 18 Apr 21:37 www/my-date.txt
$ cat www/my-date.txt
cat: www/my-date.txt: Operation not permitted
```
I'm really bemused by all this: when I run sshfs with the -d option, there are no error messages shown, apart from 'No such file or directory' for .localized, .hidden, and .DS_Store.

Is there something new from Apple that is explicitly designed to frustrate users of OSXFuse?

========

Just as I was getting ready to submit this issue, I tried it (both yas3fs and sshfs) in my home directory, and it WORKED!  Well, sort of:
```
$ cd $HOME

$ yas3fs --debug -l logfile.txt s3://my-test-bucket my-test-bucket
$ ls -l my-test-bucket
total 4096
drwxr-xr-x@   1 root          wheel  4096 Apr 19  2020 ./
drwxr-xr-x+ 122 PenelopeFudd  staff  3904 Apr 18 21:58 ../
-rwxr-xr-x    1 PenelopeFudd  staff    29 Apr 19  2020 testfile.txt*

$ cd my-test-bucket
$ cat testfile.txt
Sat 18 Apr 2020 21:29:03 PDT
$ date > nextfile.txt
-bash: nextfile.txt: Permission denied
$ rm testfile.txt
rm: testfile.txt: Permission denied
```
This must be a subtle problem with yas3fs, because sshfs works perfectly now:
```
$ cd $HOME
$ sshfs www:/tmp www
$ cd www
$ cat my-date.txt
Sat Apr 18 21:37:51 PDT 2020
$ date > my-date.txt
$ cat my-date.txt
Sat 18 Apr 2020 22:07:39 PDT
$ rm my-date.txt
```

If you could modify OSXFuse to warn users that the mount point they've picked isn't going to work properly, that'd be cool.

Thanks!

**Comment by PenelopeFudd** [comment]
Addendum: I just tried '[s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse)', and it worked perfectly (read/write/delete) in my home directory, but not in the /tmp directory.

Cheers!

**Comment by baptistecs** [comment]
I just had the same issue on macOS Big Sur 11.7.5 with macFUSE 4.4.2 and 4.4.3
This was fixed by allowing the Terminal app to access network volumes by checking the checkbox in:
System preferences > Security & Privacy > Privacy > Files and Folders > Network Volumes

<img width="673" alt="image" src="https://user-images.githubusercontent.com/50966051/235135354-a5529625-2767-4c43-a748-c69c1afee77e.png">

**Comment by bfleischer** [comment]
@baptistecs Thanks for sharing.

**Comment by Mistralys** [comment]
This was a life saver, thanks. I did not realize that MacFuse mounts were considered network mounts.

**Comment by francium** [comment]
Ran into it unexpectedly, not sure what caused it. But this thread helped.

In MacOS 26.4.1, I had to do Settings -> Privacy & Security -> Full Disk Access -> [x] Terminal

In "Files & Folder", the Terminal app was already given Full Disk Access, but in "Full Disk Access" section, Terminal wasn't given the permission.
