### ISSUE TITLE
how to mount a Finder dir ? LoopbackFS

### ISSUE THREAD

**Issue by gMan1990** [osxfuse/osxfuse#691]
`mount -t osxfuse` ?

**Comment by bfleischer** [comment]
FUSE file system are not mounted using the `mount` command. You need to call the file system binary with a set of parameters that depend on the file system.  At least you need to specify the mount point.

**Comment by gMan1990** [comment]
@bfleischer

```plain
> sudo mount -t osxfuse . /Volumes/mountTest
OSXFUSE mount version 3.10.4

This program is not meant to be called directly. The OSXFUSE library calls it.

Available mount options:
    ...

Available negative mount options:
    ...
```

**Comment by bfleischer** [comment]
As I explained earlier you need to call the file system binary, not the mount command. You can mount a loopback volume by calling loopback with the following parameters.

```
mkdir /tmp/dir
./loopback /Volumes/loop -omodules=threadid:subdir,subdir=/tmp/dir -oallow_other,native_xattr,volname=LoopbackFS
```

**Comment by gMan1990** [comment]
@bfleischer where is the `loopback` application? I can't find it / How to install it

**Comment by misku** [comment]
@gMan1990 https://github.com/osxfuse/filesystems/tree/master/filesystems-c/loopback
