### ISSUE TITLE
Assertion 'common_variable_is_legal_name XCODE_SDK_10_15.4_XCODE' failed

### ISSUE THREAD

**Issue by jrgleason** [osxfuse/osxfuse#692]
Per the instructions I run 

    ./build.sh -t distribution

But I get...

>Assertion 'common_variable_is_legal_name XCODE_SDK_10_15.4_XCODE' failed

**Comment by bfleischer** [comment]
The FUSE source code, that is available in the repository, is version 3.8.3, which is not compatible with macOS 10.15 or Xcode 11. The source code for the latest version of FUSE, that is compatible with Catalina, is not publicly available.

**Comment by jfb007** [comment]
Does this mean, the project "osxfuse" is dead for Catalina and future versions of macOS?

**Comment by bfleischer** [comment]
> Does this mean, the project "osxfuse" is dead for Catalina and future versions of macOS?

No, it does not. Version 3.10 supports Catalina. But starting with version 3.9.0 I stopped releasing parts of the source code. The last version, with the complete source code available, is 3.8.3.

**Comment by netscylla** [comment]
Catalina & Macports - We installed the binary 3.10.4 from the main website, then symlinked the files in /usr/local/include/fuse to /opt/local/include/fuse - complied fine, and should remain fine when we apply future updates.  I think brew doesn't have this issue at it uses /usr/local.

**Comment by karolisr** [comment]
Hmmm. Is there a way to make the MacPorts port work with Catalina?

**Comment by bfleischer** [comment]
The MacPorts version of FUSE for macOS is outdated and does not support macOS 10.15. Using it on 10.15 will cause issues and could lead to data loss. I've bee in contact with someone from the MacPorts team, but they don't want to update the FUSE port due to FUSE no longer being open source in its entirety.
