### ISSUE TITLE
How to distribute mac application?

### ISSUE THREAD

**Issue by kondak3** [osxfuse/osxfuse#693]
We done one application using your osxfuse. How to submit application in app store include with framework. we can't to tell the end users to install osxfuse manually.

we are getting below error.

Dyld Error Message:
  Library not loaded: /Library/Frameworks/OSXFUSE.framework/Versions/A/OSXFUSE
  Referenced from: /Users/USER/Desktop/*/LoopbackFS.app/Contents/MacOS/LoopbackFS
  Reason: image not found

**Comment by bfleischer** [comment]
You cannot distribute FUSE for macOS in the App Store. This means the core feature of your app must work without FUSE for macOS being installed. Then when a user want to use an additional feature (file system integration) you can redirect the users to a support article on your website containing instruction on how to install FUSE for macOS and other required components.

Please note that FUSE for macOS may not be bundled or distributed with commercial software without obtaining a license.

**Comment by didactic-drunk** [comment]
Could using [A kernelless filesystem](https://github.com/iterate-ch/kfs) or nfs as a backend solve this issue?

Pros:
* Can provide file system mounting directly from app store without additional installation.
* Kernel driver not needed.
* Less specialized knowledge.
* Possibly faster development.
* Special signing key not required.
* Each app can have it's own fuse version without relying on a single kernel driver version.

Cons:
* ?

There is at least one commercial product (if not several) using this technique.
