### ISSUE TITLE
FUSE write failure when using tup on macOS 10.15.5

### ISSUE THREAD

**Issue by jwmerrill** [osxfuse/osxfuse#695]
Cross-posted from tup issue: https://github.com/gittup/tup/issues/395

**Version info:**
macOS: 10.15.5 (19F101)
tup: 0.7.8 (installed with homebrew)
osxfuse: 3.10.4, 3.10.5

[Tup](http://gittup.org/tup/) uses FUSE to monitor file system access during builds.

When I run `tup` on the example project from [A First Tupfile](http://gittup.org/tup/ex_a_first_tupfile.html), I see the following output:

```
> tup
[ tup ] [0.001s] Scanning filesystem...
[ tup ] [0.003s] Reading in new environment variables...
[ tup ] [0.005s] Parsing Tupfiles...
fuse: writing device: Socket is not connected
tup error: FUSE file-system does not appear to be mounted properly.
```

It takes a few minutes after "Parsing Tupfiles..." to get to the error output. The error output appears to come from 

https://github.com/gittup/tup/blob/4aee2f7e1eda1fa2732d1d52f4f585e9ec54c648/src/tup/server/fuse_server.c#L293-L321

where `tup` is polling for access to a special file.

## Notes

I had initially installed osxfuse 3.10.4 through homebrew cask, but I tried uninstalling that and installing [osxfuse 3.10.5](https://osxfuse.github.io/2020/05/27/OSXFUSE-3.10.5.html) (currently a developer preview). That version also exhibits this problem.

I also tried installing `sshfs` to test whether my `osxfuse` installation was working at all, and I was able to successfully mount and read/write a directory on a separate machine. I think that's evidence that `osxfuse` is at least basically functional in this configuration.

Two of my coworkers also recently upgraded to macOS 10.15.5 and are also experiencing this problem.

**Comment by gittup** [comment]
I believe I've fixed this issue in tup itself. There seems to be something new in 10.15 that was causing a problem with the way tup used fuse. I can reproduce the issue in an example fuse filesystem by doing the following:

1) Running fuse_main in a thread
2) Accessing a file in the fuse fs from another thread
3) Calling fchdir() in the fuse hook (I think it has to try to fchdir() to the parent of the mount directory. So if the fuse fs is mounted in /Users/myuser/tmp, then opening /Users/myuser and fchdir() there will hang).

The fchdir() call hangs for a while, and eventually a timeout somewhere causes the fuse filesystem to get interrupted and unmount.

STR:
1) wget https://raw.githubusercontent.com/libfuse/libfuse/fuse_2_9_5/example/fusexmp_fh.c
2) patch with:
```
--- tmp.c	2020-06-04 19:12:28.000000000 -0700
+++ fusexmp_fh_test.c	2020-06-04 13:19:05.000000000 -0700
@@ -18,7 +18,6 @@
 #define _GNU_SOURCE
 
 #include <fuse.h>
-#include <ulockmgr.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
@@ -32,6 +31,9 @@
 #include <sys/xattr.h>
 #endif
 #include <sys/file.h> /* flock(2) */
+#include <pthread.h>
+
+static char cwd[4096];
 
 static int xmp_getattr(const char *path, struct stat *stbuf)
 {
@@ -62,6 +64,16 @@
 {
 	int res;
 
+	int dfd;
+ 	int rc;
+ 	printf("Access(%s)\n", path);
+	printf("Cwd: %s\n", cwd);
+ 	dfd = open(cwd, O_RDONLY);
+ 	printf(" - dfd: %i\n", dfd);
+ 	rc = fchdir(dfd);
+ 	printf(" - rc: %i\n", rc);
+ 	close(dfd);
+
 	res = access(path, mask);
 	if (res == -1)
 		return -errno;
@@ -489,15 +501,6 @@
 }
 #endif /* HAVE_SETXATTR */
 
-static int xmp_lock(const char *path, struct fuse_file_info *fi, int cmd,
-		    struct flock *lock)
-{
-	(void) path;
-
-	return ulockmgr_op(fi->fh, cmd, lock, &fi->lock_owner,
-			   sizeof(fi->lock_owner));
-}
-
 static int xmp_flock(const char *path, struct fuse_file_info *fi, int op)
 {
 	int res;
@@ -551,7 +554,6 @@
 	.listxattr	= xmp_listxattr,
 	.removexattr	= xmp_removexattr,
 #endif
-	.lock		= xmp_lock,
 	.flock		= xmp_flock,
 
 	.flag_nullpath_ok = 1,
@@ -560,8 +562,32 @@
 #endif
 };
 
+struct dat {
+	int argc;
+	char **argv;
+};
+
+void *tfunc(void *arg)
+{
+	struct dat *mdat = arg;
+	printf("Entering fuse_main\n");
+	fuse_main(mdat->argc, mdat->argv, &xmp_oper, NULL);
+	printf("Leaving fuse main\n");
+	return NULL;
+}
+
 int main(int argc, char *argv[])
 {
+	struct dat mdat = {argc, argv};
+	struct stat buf;
+	pthread_t pid;
 	umask(0);
-	return fuse_main(argc, argv, &xmp_oper, NULL);
+
+	getcwd(cwd, sizeof(cwd));
+
+	pthread_create(&pid, NULL, tfunc, &mdat);
+	sleep(1);
+	stat("tmp/test", &buf); // Assuming we mounted fuse to "tmp"
+	pthread_join(pid, NULL);
+	return 0;
 }
```
(The ulockmgr changes are just to making compiling it easier)
3) mkdir tmp
4) gcc fusexmp_fh_test.c `pkg-config fuse --cflags --libs` && ./a.out -d tmp

You should see it process a few calls successfully, then one of the access() calls will block after the open() and before the fchdir(). The fuse fs is then unresponsive and after a while will quit.

The same code works on OSX 10.14 and lower, as well as on Linux.
