### ISSUE TITLE
Error Code 100006 when coping files from my LTO

### ISSUE THREAD

**Issue by maglite85** [osxfuse/osxfuse#696]
Hello,

I've been using fuse in combination with my LTFS formatted LTO Drive for years without any problems. 

Since a couple of weeks I always get the Error Code 100006 whenever I try to copy files from the LTO Drive to my Hard Drive.

Do you have any suggestions how I can fix this problem?

Thank you so much

**Comment by bfleischer** [comment]
I'm sorry, but I cannot help you with this. I don't have access to a LTO drive. Please report the issue to the LTFS maintainer.
