### ISSUE TITLE
Is the Unix FS UFS file system able to mount Sun OS disk images?

### ISSUE THREAD

**Issue by earlthesquirrel** [osxfuse/osxfuse#697]
I've got the new Fuse install and also downloaded the filesystems git repo and was able to build that.

However, I have a "ufs" executable but no clear instructions how to use it.  Is it functional enough to be able to mount, read and write Sun OS disk images?  (I'm trying to do some restoration on some Sun boxes and getting the OS onto a disk has been a big challenge.)  I'm hoping Fuse could be of some real assistance here, if this works.

**Comment by bfleischer** [comment]
I'm sorry, but I don't know if it will work. Please post questions like this on our Google Group https://groups.google.com/forum/#!forum/osxfuse-group. The issue tracker should only be used for reporting bugs.
