### ISSUE TITLE
New OSXFuse User with Mac Error "The operation can’t be completed because an unexpected error occurred (error code 100102)."

### ISSUE THREAD

**Issue by HashaRock** [osxfuse/osxfuse#698]
I have just installed OSXFuse and it seems to be working fine. The external drive is mounted properly but when I try to transfer files to the External drive, I get this message:
"The operation can’t be completed because an unexpected error occurred (error code 100102)."

Does anyone know why this is not working? I have used Tuxera's free trial and it works fine, but I want an answer to why my computer has this problem. 

NTFS-3g 2017.3.23_2 is the update and I am on macOS Catalina.

macOS is running completely fine and not giving back any signs of hardware problems or problems within transferring files over the same drive.

Files that I write on the External Drive show up, but cannot be opened and are 0 bytes, when I unmount and eject the drive. In FUSE, I cannot see them at all. 
![Screen Shot 2020-06-11 at 8 28 52 AM](https://user-images.githubusercontent.com/63619145/84390823-ba3dc380-abbd-11ea-8f2f-8e0c9e62aafa.jpg)

**Comment by bfleischer** [comment]
Please note that FUSE for macOS and NTFS-3G are independent projects. If you run into any issues with NTFS-3G please raise the issues with the NTFS-3G maintainers.

**Comment by Artoria2e5** [comment]
This is a EOPNOTSUPP. How are you mounting it, like what exactly are your flags?

**Comment by ketsapiwiq** [comment]
I had the same problem, had to mount it with `-o local -o allow_other -o auto_xattr -o auto_cache` instead of only `-olocal -oallow_other`. Found this solution from #704.
