### ISSUE TITLE
Bad signature for 3.10.6?

### ISSUE THREAD

**Issue by hasselhoffd** [osxfuse/osxfuse#699]
Hello - I'm trying to verify the signature of the sha256 file and am receiving  a "BAD signature" message. When I execute the same procedure for 3.10.5, it appears to be 'ok'. Please see the results below.
thanks!

From 3.10.6:

gpg: Signature made Mon Jun  8 05:43:26 2020 PDT
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: BAD signature from "Benjamin Fleischer <fleiben@gmail.com>" [unknown]

From 3.10.5:

gpg: Signature made Wed May 27 10:07:12 2020 PDT
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: Good signature from "Benjamin Fleischer <fleiben@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0093 B21E F45D 6352 84F6  A147 53C9 18C1 A281 8875
     Subkey fingerprint: 135F 164B 411B AA1F 4A4B  CD37 617A 3461 8026 08A1

**Comment by bfleischer** [comment]
The signatures of 3.10.5 and 3.10.6 are both valid for me:

```
 % gpg --verify /Users/benjamin/Downloads/osxfuse-3.10.6.sha256.sig
gpg: assuming signed data in '/Users/benjamin/Downloads/osxfuse-3.10.6.sha256'
gpg: Signature made Mon Jun  8 14:43:26 2020 CEST
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: Good signature from "Benjamin Fleischer <fleiben@gmail.com>" [ultimate]
% gpg --verify /Users/benjamin/Downloads/osxfuse-3.10.5.sha256.sig 
gpg: assuming signed data in '/Users/benjamin/Downloads/osxfuse-3.10.5.sha256'
gpg: Signature made Wed May 27 19:07:12 2020 CEST
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: Good signature from "Benjamin Fleischer <fleiben@gmail.com>" [ultimate]
```

Maybe your .sh256 or .sig file was corrupted during the download?

**Comment by hasselhoffd** [comment]
Hi - You are correct. It appears there was something wrong with the 'sha256' file for some reason. After downloading and verifying again, it was fine. 

I appreciate you taking the time to respond.

Regards

xxxxxxx$ gpg --verify /Users/xxxxxxxxx/Downloads/osxfuse-3.10.6.sha256.sig 
gpg: assuming signed data in '/Users/xxxxxxxxx/Downloads/osxfuse-3.10.6.sha256'
gpg: Signature made Mon Jun  8 05:43:26 2020 PDT
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: Good signature from "Benjamin Fleischer <fleiben@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0093 B21E F45D 6352 84F6  A147 53C9 18C1 A281 8875
     Subkey fingerprint: 135F 164B 411B AA1F 4A4B  CD37 617A 3461 8026 08A1
