### ISSUE TITLE
Feature request: Linux-style xattr namespace translation

### ISSUE THREAD

**Issue by Artoria2e5** [osxfuse/osxfuse#702]
A lot of userspace FSes are written with Linux-style xattr in mind, which doesn't really work the same way as xattr on macOS. The main difference is that Linux xattrs use *namespaces* with different privillege levels represented by prefixes, while macOS use "open" xattrs without such a format requirement. As a result, when a request is made to write, say, `com.apple.quarantine`, the userspace FS is likely to reject it as it does not start with any of the four predefined namespaces.

NTFS-3G has a way of mapping between "user (Linux) xattrs" and "open xattrs" interfaces, but this feature is likely to be missing in many other userspace FSs. I propose a new option `linux_xattr` that performs the following:

* If the xattr to access starts with `osxfuse.`, this is a special request to access a namespaced xattr. Strip the prefix and pass it directly down to the FS.
* Otherwise, the xattr name is prefixed with `user.` before passing down.

Linux documents its xattr behavior in [xattr(7)](https://man7.org/linux/man-pages/man7/xattr.7.html). It might be a good idea to additionally map some of the more sensitive stuff (say, `com.apple.system`), to a non-user namspace (`system.*`). Automatic detection of Linux xattr is possible by attempting an "open namespace" access.

**Comment by bfleischer** [comment]
Namespace translation might be useful in certain cases, but it would be time consuming to maintain given that extended attributes are not well documented on macOS. Currently this is beyond the scope of the macFUSE project. I think the best way of implementing something like this, in a reusable way, would be implementing a high-level libfuse module that performs the mapping. This could be implemented and maintained by a third party.
