### ISSUE TITLE
extended_security conflicts with allow_others

### ISSUE THREAD

**Issue by Artoria2e5** [osxfuse/osxfuse#703]
I am trying to mount NTFS-3G with full Unix permissions and ACL. However, after running the following command as root, all access from other users fail with "No message available on STREAM":

```sh
/usr/local/opt/ntfs-3g/bin/ntfs-3g \
  -o volname="Windows" \
  -o local \
  -o negative_vncache \
  -o streams_interface=openxattr \
  -o auto_cache \
  -o noatime \
  -o windows_names \
  -o inherit \
  -o allow_other \
  -o big_writes \
  -o extended_security \
  /dev/disk1s4 /Volumes/Windows >> /var/log/mount-ntfs-3g.log 2>&1
```

Removing the `extended_security` makes it work again with functional Unix permissions. You will need to run `ntfsusermap` to get the UIDs mapped beforehand.

**Comment by bfleischer** [comment]
Please report the issue the the NTFS-3G maintainers.

**Comment by Artoria2e5** [comment]
I am still thinking this may be a fuse thing. Let me test this on a much more simplified `LoopBackFS` then.

**Comment by Artoria2e5** [comment]
Not reproduced with LoopBackFS. Will report to NTFS-3G.

**Comment by Artoria2e5** [comment]
Now that NTFS-3G got their ENOATTR thing together, this is still partially failing: `chmod +a` works but `chmod 644` doesn't. The worst part is that I can't even see a `setattr` or a `chmod` request in the debug log. Any idea what kind of macOS security magic this is?

Nevermind, `inherit` is on.
