### ISSUE TITLE
Problems using file with titles containing Korean

### ISSUE THREAD

**Issue by windroad77** [osxfuse/osxfuse#708]
Hi~!

Files with Korean titles cannot be played in the case of videos, and files in comic books cannot be opened.

1. When connecting only plexdrive or rclone for google drvie
    - If the Korean title is short, click the name change, hit enter and try again, but it will play, but it will be separated when checked in the Google driver.
   - If the Korean title is long, the above method cannot be used.

2. When connecting a folder connected by plexdrive or rclone to sshdfs -o modules=iconv,from_code=utf-8,to_code=utf-8-mac
    -  If the Korean title is short, you can play and use the file.
    -  If a file with a long Korean title is included, the list of files in the corresponding folder of Google Drive connected by plexdrive is not displayed.

For Google File Stream, it seems to solve it like this:

https://www.aurelp.com/tag/maximum-file-name-google-drive/

For other mount programs (ex: Mountain Duck), if the number of characters in the file title exceeds, the list of those files is hidden and the rest of the files are shown.

Do you have any plans to solve the above problem?

Please refer to the above issue in the next update.

Thank you for your efforts.

Have a nice day~!

**Comment by jarrocha** [comment]
Hello,
Could you give us an example of Korean titles that gives you an issue?

**Comment by windroad77** [comment]
1. Install osxfuse

2. Connect Google Drive with plexdrive and rclone
-All Korean title files are not executed 
(ex)Comic book korean title:
100명의 영웅을 키운 최강 예언자는, 모험자가 되어서도 세계의 제자로부터 사랑 받고 있습니다.
Drama korean tile: 굿 닥터.avi)

3. Relink the connected folder with the following command
     sshdfs -o defer_permissions -o modules=iconv,from_code=utf-8,to_code=utf-8-mac
-When files with long characters (28-31 in Korean) are included, the list in the folder is not visible.
(ex)Comic book korean title:
100명의 영웅을 키운 최강 예언자는, 모험자가 되어서도 세계의 제자로부터 사랑 받고 있습니다.
