### ISSUE TITLE
FUSE for macOS not compatible with macOS 10.14?

### ISSUE THREAD

**Issue by Planetxfuse** [osxfuse/osxfuse#709]
After an update to Mojave my Veracrypt container does not mount anymore and I get the error message:
mount_osxfuse: the file system is not available (255)

I tried to load the kext, but without success.
```
sudo kextload /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.14/osxfuse.kext
```

![veracrypt](https://user-images.githubusercontent.com/67795690/86481048-820a4a80-bd4f-11ea-96c2-4774ec14c652.png)
Under macOS 10.13 the container is still mountable.
Any help is very much appreciated...

**Comment by Planetxfuse** [comment]
FUSE for macOS: 10.13.6
VeraCrypt: 1.24 Update 4

**Comment by jarrocha** [comment]
The osxfuse version you install must have the kext for your OS. In your case, this directory has to exist:
**/Library/Filesystems/osxfuse.fs/Contents/Extensions/10.13** for High Sierra
**/Library/Filesystems/osxfuse.fs/Contents/Extensions/10.14** for Mojave
Make sure you have a version that is compatible with 10.14, maybe reinstalling the newest version could fix this.

**Comment by Planetxfuse** [comment]
Many thanks for your comment! 
I tried first to uninstall/reboot and then reinstall the latest version of osxfuse, 10.13.6.
The folder 10.14 is present as an alias to the folder 10.10.
I even tried to reinstall VeraCrypt. The strange thing, it is possible to create a new container, but impossible, to mount it accordingly.



![folders](https://user-images.githubusercontent.com/67795690/86488104-79197900-bd4f-11ea-96d4-1f83b37b812a.png)

**Comment by Planetxfuse** [comment]
Edit:
 is present as an alias to the folder 10.10. ->  is present as an alias to the folder 10.11

Sorry, my fault.

**Comment by bfleischer** [comment]
@Planetxfuse Please raise the issue with the VeraCrypt team.
