### ISSUE TITLE
International characters (e.g. Swedish åäö) in remote file system folder names makes Finder hang

### ISSUE THREAD

**Issue by bnilsson11** [osxfuse/osxfuse#71]
If I mount a linux volume which contains folders with names containing Swedish characters 'åäö', the parent Finder window freezes as soon as the folder comes into view. In the console I repeatedly see the message: 

Finder: -[__NSCFDictionary setObject:forKey:]: attempt to insert nil key

and I need to restart/kill the Finder by Cmd-Alt-esc to continue. 
If I rename the folders to remove the Swedish characters the problem goes away.

A similar problem concerns documents with "wrong" names. Double-clicking on it gives a dialog box "The application can't be found". An document without the "wrong" characters in the name opens properly.

I use MacOS 10.7.5, OSXFUSE 2.5.4 and MacFusion Version 2.0.4 (2.0.4)

**Comment by Doloresanto** [comment]
Hi, I'm seeing this with Russian characters ё and й.

On my mac I have:
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

On remote system:
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=

Finder sees the files with the mentioned characters in names, but cannot access them. The mount option doesn't seem to have an effect.
