### ISSUE TITLE
Fuse does not do anything

### ISSUE THREAD

**Issue by Cedrun** [osxfuse/osxfuse#714]
Hello,

I am new in Mac world. I installed the lastest version of Fuse for read and write in NTFS disks and I can't.

I have a Fuse icon on the control panel but I can't configure anything.

Can anybody help me?.

Thanks in advance

**Comment by bfleischer** [comment]
You will need to setup NTFS-3G, too. FUSE is the foundation for NTFS-3G but does not provide read-write access to NTFS volumes on its own. NTFS-3G is the actual file system implementation. See https://github.com/osxfuse/osxfuse/wiki/NTFS-3G for more details and installation instructions.

**Comment by Cedrun** [comment]
Thank you for your answer.
