### ISSUE TITLE
Lacie Private-Public locked folder

### ISSUE THREAD

**Issue by Sculptort** [osxfuse/osxfuse#715]
I was stupid enough to update my apple OS to Catalina and now I cannot open my private-public folder. Lacie are no help at all and neither is Apple. I was told I should get a computer that is old and operates on an older system, which I now have and it operates on High Sierra 10.13.6 It still won't open my folder. I have over 20 years of images on my Lacie Private-Public folders. 
Why no one was warned about not upgrading to the latest OS and how this would effect them is beyond belief. I would never have upgraded my desktop computer.
If there is anyway anyone can help? Please just let me know, I am in the depths of despair. Happy to pay and even remote access if needed.

**Comment by bfleischer** [comment]
First of all try to install the latest version of Private-Public then install the latest version of FUSE. This might help. Last time I checked LaCie was shipping a very outdated version of FUSE with their software. That‘s why you need to install FUSE after Private-Public.

Ultimately this is an issue that LaCie would need to look into as it is happening with their their software.

**Comment by Sculptort** [comment]
Thank you for your reply but Lacie have washed their hands about my problem. Apart from paying out to a lawyer I am lost as what I should do next? I will try and find and load the last version of Private-Public and see if that works

**Comment by Sculptort** [comment]
Thank you for your reply but Lacie have washed their hands about my
problem. Apart from paying out to a lawyer I am lost as what I should do
next? I will try and find a load the last version of Private-Public and see
if that works

**Comment by bfleischer** [comment]
If you know that Lacie Private-Public works on a specific version of macOS you could set up a virtual machine with that specific version of macOS, open your vaults and copy their contents to another place. This will be quite some work, but it might be a viable option to rescue your data. That's pretty much all the advice I can offer.

**Comment by Sculptort** [comment]
My problem is that I cannot find a Lacie Private-Public download for Mac
anywhere on the web including Lacie. I have tried about 15 sites that say
they can provide this but none can.

**Comment by Sculptort** [comment]
Ok I now have Lacie manager for High Sierra but still having problems with the OSFUSE

**Comment by caroline-englert** [comment]
@Sculptort did you find a solution / way to download Lacie Private-Public?
