### ISSUE TITLE
An unexpected error occured-cryptomator

### ISSUE THREAD

**Issue by Smiley006** [osxfuse/osxfuse#716]
[An unexpected error occured.docx](https://github.com/osxfuse/osxfuse/files/5112074/An.unexpected.error.occured.docx)

**Comment by Sculptort** [comment]
I am not sure that this helps. What can I do about it?

**Comment by bfleischer** [comment]
Please raise the issue with the Cryptomator team. They need to look into it, there is nothing I can do from the FUSE end.

**Comment by Sculptort** [comment]
How do I contact Cryptomator team. I am new to all this and the site. A
total newbie to any kind of programing or anything technical with computers.
Kind regards
Terry

**Comment by bfleischer** [comment]
@Sculptort If you google "Cryptomator", their [website](https://cryptomator.org) is the first hit. You can find the support options in the footer of the Cryptomator website.
