### ISSUE TITLE
Write permission

### ISSUE THREAD

**Issue by uwillenbacher** [osxfuse/osxfuse#717]
Hello,

First up, let me Thank you for this wonderful App. 

So I am using Banktivity on my MacBook Pro (Catalina) and I am used to store my data on Dropbox, I am using cryptomator to crypt my data and it in turn uses FUSE to virtual mount the de-crypted data on my Mac.

When I try to safe my data I get a dialog box claiming that I need to change permissions, i.e. can not write the data. I checked the files permission and it is 755 with me as the owner and staff being the group.

Any idea how to solve this?

**Comment by bfleischer** [comment]
Please raise the issue with Cryptomator support. They need to look into this.

**Comment by uwillenbacher** [comment]
I did... no response yet. thank you...
