### ISSUE TITLE
Error message AskPassTool is missing

### ISSUE THREAD

**Issue by Jinchuurikki** [osxfuse/osxfuse#719]
I use FUSE for MacOS v3.11.0 in combination with Forklift v3.4.1 on a macbook running Catalina MacOS.
I have been happily using this combo for the past couple of weeks, using the the feature "Mount as Disk”.
This morning I mounted a hard drive to upload a file (about 1.4 GB in size) to the server but I kept on receiving an error after about 300-500 MB.
So I thought to check for updates for Forklift and FUSE for MacOS. After updating however the problem got worse. Now I can’t even use the feature "Mount as Disk”, reason given is "AskPassTool is missing”.
I couldn’t find any resources regarding that error. Is there anything you can help me with in here please. I will probably start getting complaints from my colleagues regarding the same matter soon.

Appreciate your help.

![Screen Shot 2020-08-26 at 11 09 51 AM](https://user-images.githubusercontent.com/70243019/91239668-524a5280-e794-11ea-8601-cab024ab826b.png)
<img width="664" alt="Screen Shot 2020-08-26 at 11 17 46 AM" src="https://user-images.githubusercontent.com/70243019/91239674-55ddd980-e794-11ea-8ead-55d0fc9b801b.png">

**Comment by bfleischer** [comment]
Please get in touch with the ForkLift support team. They need to look into this. Furthermore I would like to add that ForkList is not contributing to the continued development of FUSE for macOS.

**Comment by Jinchuurikki** [comment]
I will do.
Thanks Benjamin for your reply.




Best regards
Pietro Lubich
 





Mob 027 463 5253  |  Skype live:pietro_556
