### ISSUE TITLE
auto mount not working well

### ISSUE THREAD

**Issue by kronosboy** [osxfuse/osxfuse#720]
mounting the HD using
`sudo /usr/local/bin/ntfs-3g /dev/disk1s1 /Volumes/NTFS -o local -o allow_other -o auto_xattr -o auto_cache`
using **-o auto_xattr** works fine
but if I replace the Mac Os mount tool with the one of ntfs-3g doing
`sudo ln -s /usr/local/sbin/mount_ntfs "/Volumes/Macintosh HD/sbin/mount_ntfs"`
The HD can be mount in read/write mode but can't see preview or open file directly for HD.
Is it possible to configure the mount_ntf of ntfs-3g to include **-o auto_xattr**
I am using Mac Os Sierra 10.12.6

**Comment by bfleischer** [comment]
Please raise this issue with the NTFS-3G team. The mount script is not part of FUSE for macOS.

**Comment by okla** [comment]
@kronosboy You can `sudo nano /usr/local/sbin/mount_ntfs` and add **-o auto_xattr** line here
