### ISSUE TITLE
osxfuse mounted drive may cause kernel panics and Finder issues on Big Sur

### ISSUE THREAD

**Issue by 0jg** [osxfuse/osxfuse#721]
Hi,

On every use of osxfuse on Big Sur (build 20A5354i, latest developer beta), osxfuse seems to be causing issues with Finder. If I am dealing with files on a mounted remote server, Finder always hangs and requires a restart. When restarting, it shows the error `LSOpenURLsWithRole() failed with error -1 for the file /System/Library/CoreServices/Finder.app.`. 

My Mac then frequently kernel panics, and reboots with the prohibited icon (https://support.apple.com/en-gb/HT210901)[https://support.apple.com/en-gb/HT210901]. After a reboot, it usually allows me to log-in fine.

This happens every time I use osxfuse on Big Sur (and at no other times when I'm using Finder).

Let me know if you'd like any logs or further information, or whether this is an issue with Finder itself rather than osxfuse.

Best wishes,
Jack

**Comment by bfleischer** [comment]
Could you please post the panic log?

**Comment by 0jg** [comment]
> Could you please post the panic log?

Sure—here is one of the logs. I'm not sure I can see anything related to sshfs/osxfuse, but the panics always seem to happen when using a mounted drive.

https://gist.github.com/j-griffiths/03f38663d6aae012d400c145610d1b86

**Comment by 0jg** [comment]
The kernel panics and Finder crashes seem to have been resolved with a PRAM reset and disk First Aid (although it seems the PRAM reset is the magic thing to do!) This seems to be a repeating issue with the latest beta and—I believe—not specific to osxfuse, e.g., https://developer.apple.com/forums/thread/657905.

**Comment by bfleischer** [comment]
Thanks for the update and the link to the developer forum. The panic log you posted does not contain any indication that FUSE might be to blame. The FUSE kernel extension was not loaded at the time of the crash.
