### ISSUE TITLE
Mac OS 11.0 SDK and Arm64 Support

### ISSUE THREAD

**Issue by izackp** [osxfuse/osxfuse#722]
- Build scripts need to be updated to accept sdk 11
- Projects need to change so valid architectures include arm64 and possibly arm64e
- PAGE_SIZE is no longer a constant which causes some build issues in mount_osxfuse and osxfuse projects
- The build script eventually ends with this error "T:prefpane           | Failed to locate autoinstaller" which I'm not sure what is trying to find it and where/when does it get created.

**Comment by bfleischer** [comment]
Version 4.0.0 adds support for Apple Silicon.
