### ISSUE TITLE
Unable to contact update server 

### ISSUE THREAD

**Issue by calishajj** [osxfuse/osxfuse#723]
Help! This software has saved me before from having to buy a new laptop. My macbook is old and apple system updates no longer work on it. When that happened everything stopped wanting to work. I found Fuse and downloaded the 3.8 version and it worked beautifully to update my system. Well it's time again and I got the new Fuse 3.11.0. but every time I click check for updates it says unable to contact update server. Unfortunately I can't seem to figure out why. Please help!

**Comment by bfleischer** [comment]
Legacy versions of macOS do not support the latest TLS standard (https) required for contacting the update server. You will have to download the latest version of FUSE and install it manually.
