### ISSUE TITLE
all files have hidden in the finder on external HD

### ISSUE THREAD

**Issue by rafaeltrojan** [osxfuse/osxfuse#725]
I've used an external HDD, with NTFS on Mojave.
The first time the mount worked, but now the finder does not show the HD files.
I think that the files is there, because the capacity used is the same...

**Comment by bfleischer** [comment]
Please report the issue with the NTFS-3G developers. There is nothing I could do to help you. FUSE for macOS and NTFS-3G are independent projects.

**Comment by amgdeveloper** [comment]
> I've used an external HDD, with NTFS on Mojave.
> The first time the mount worked, but now the finder does not show the HD files.
> I think that the files is there, because the capacity used is the same...

Did you manage to solve it?, I'm having the same problem
