### ISSUE TITLE
Mounting NTFS via VeraCrypt fails again on Big Sur Beta 6

### ISSUE THREAD

**Issue by tholu** [osxfuse/osxfuse#726]
After the release of 3.11.0 (see #705) everything worked fine (mounting NTFS via VeraCrypt).

However after updating to MacOS Big Sur Beta 6 - 11.0 Beta (20A5364e) - it fails with the following error message: `hdiutil attach failed - no mountable file systems`

When trying to mount manually with Tuxera Diskmanager, the error message is the following:
`Error while mounting disk2: Too many levels of remote in path`

**Comment by zambaras** [comment]
I'm also having this problem on the latest Big Sur developer build.  My VeraCrypt containers are located on a remote SMB volume and I initially thought this was related but after moving them locally I'm having the same problem.  Hope this gets sorted soon.

**Comment by watanaberyunosuke** [comment]
I am currently having the issue with cryptomator. The error message as follow:

: ru.serce.jnrfuse.FuseException: Unable to mount FS, return code = 1
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:283)
	... 14 more

**Comment by tholu** [comment]
Works again in Big Sur Beta 7 - 11.0 Beta (20A5374g).
