### ISSUE TITLE
Fuse will only load with SIP disabled

### ISSUE THREAD

**Issue by tormodwill** [osxfuse/osxfuse#728]
MacOS Mojave  10.14.6

Disabled SIP : 
`Tormods-MacBook-Pro:~ tormod$ kextstat|grep fuse
 164  0 0xffffff7f84831000 0x1a000  0x1a000  com.github.osxfuse.filesystems.osxfuse (3.11.0) E8885520-BA4F-3A9F-92C5-03F90FF86802 <8 6 5 3 1>
Tormods-MacBook-Pro:~ tormod$ `

all sshfs and commands work when 
`csrutil disable`

When
`csrutil enabled`

Then there is no output of the commad 
`kextstat|grep fuse
`

```
Tormods-MacBook-Pro:~ tormod$ sshfs  --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.11.0
FUSE library version: 2.9.7
fuse: no mount point
Tormods-MacBook-Pro:~ tormod$ 
```

**Comment by bfleischer** [comment]
All official releases of FUSE are properly signed and notarized to load fine with SIP enabled.

If it does not load for you, the issue is most likely caused by something on your Mac. The FUSE installation might be damaged or there could be a system policy preventing third party kernel extensions from loading.

**Comment by tormodwill** [comment]
Hello

Thanks for the reply.

Here is some of the things I have done to my mac :
https://discussions.apple.com/thread/251719580?page=2 <https://discussions.apple.com/thread/251719580?page=2>
Any idea what causes SIP to shut down Fuse ?

I also find that other user have the same problem :
https://groups.google.com/g/osxfuse-group/c/J-jpwgWaJK4 <https://groups.google.com/g/osxfuse-group/c/J-jpwgWaJK4>

Regardless, solution or not, I have to thank for the work put into Fuse. I realise that a lot of effort and manhours have been put into Fuse.


Best regards

Tormod Willassen
