### ISSUE TITLE
Git not working with macFUSE 4

### ISSUE THREAD

**Issue by iaxat** [osxfuse/osxfuse#729]
Hello I am trying to clone repositories inside my google drive which is mounted to my system using Rclone and have install OSX Fuse from the website. But the cloning is not happening.

Although I am able to write text files or just copy or paste or open and edit but the cloning is not working, and since the cloning itself is not working I can for sure say the other git commands will not work but there is no way to check that out. I am a beginner, if there is any advice please ler me know, I would prefer to keep everything in cloud and it is just not working.

After the osxFuse was installed on the system, I did the same steps and things that I did onto my ubuntu system and it used to work fine on ubuntu but it does not seem to work that way on mac. Of course I did not install any osFuse or any alternate on the ubuntu.

Please assist

**Comment by NorseGaud** [comment]
The best thing to do is to provide steps to replicate this. This also should include versions of macOS, FUSE, etc.

**Comment by iaxat** [comment]
System information:
Macos - Catalina - 10.57
OSxFUSE - Latest Version

The steps are as follows:
1. Install FUSE from website
2. Install rclone
3. Create gdrive in rclone
4. Mount using Rclone
5. Clone any github repo using git to the mounted drive

This cloning used to work in linux and still does, like ubuntu. But does not work and there is some issue with FUSE or may be some specific setting that it requires. I have a ubuntu, and git works pretty well on mounted drives on ubuntu.

**Comment by iaxat** [comment]
Label should be changed, feedback has already been provided.

**Comment by bfleischer** [comment]
The issue is caused by an upstream change in libfuse.

**Comment by iaxat** [comment]
What should be done about it? What are the ways that it can be solved.

**Comment by bfleischer** [comment]
I've reverted the change. It seems to be inherently flawed for file systems that call the filler function with non-zero offsets in the readdir file system callback. This will always trigger the EIO error you are seeing  with git.

**Comment by iaxat** [comment]
So does this require me to update to the new version, or will it get updated automatically?

**Comment by bfleischer** [comment]
You will need to update to version 4.0.3 when it is released.

**Comment by iaxat** [comment]
I updated it but the issue persists.

**Comment by bfleischer** [comment]
Cloning works again since version 4.0.3 with the loopback reference file system. This means, if you are still running into the issue with >= 4.0.3, the rclone team needs to look into this.
