### ISSUE TITLE
OSXFuse Installation Hangs when Compatibility Layer Option selected

### ISSUE THREAD

**Issue by ColinInBelgium** [osxfuse/osxfuse#731]
OSXFuse and Veracrypt were working until I reinstalled Mojave 10.14.6

When I try to reinstall OFXFuse (including compatibility layer for legacy MacFUSE file systems) it hangs at the end of the "validation of packages”:
![Screenshot 2020-10-04 at 09 37 01](https://user-images.githubusercontent.com/54828701/95009816-2a68cd00-0625-11eb-8426-909a1bd574c7.png)

It installs without that option, but on mounting a volume in Veracrypt, I then get the same error I had after reinstalling Mojave: 
![Screenshot 2020-10-04 at 09 19 58](https://user-images.githubusercontent.com/54828701/95009747-b29aa280-0624-11eb-9ca8-6e80bb1b542c.png)
Can someone please explain how to avoid OSXFuse installation hanging at "validation of packages”?

Thanks.

**Comment by bfleischer** [comment]
The "Validating packages" phase is managed by the macOS installer automatically. I cannot reproduce the issue and I don't think there is anything I can do about it.

However, the compatibility layer was only intended for Google MacFUSE 2.x based file systems. The Google MacFUSE project was abandoned more that 10 years ago, therefore the compatibility layer should no longer be needed. In fact, macFUSE 4 does no longer include the compatibility layer.
