### ISSUE TITLE
Cannot select installation disk

### ISSUE THREAD

**Issue by nvmnghia** [osxfuse/osxfuse#732]
I'm stuck at this:

![image](https://user-images.githubusercontent.com/22721156/95284623-d100d800-0888-11eb-9e7a-c448d74b0240.png)

Furthermore, when installing with homebrew, I get this error:

```bash
==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.11.2/osxfuse-3.11.2.dmg
Already downloaded: /Users/nvmnghia/Library/Caches/Homebrew/downloads/c3e68242cf1794b67a6b47745d4918712d81fef66294a99ebb93dc453e77421f--osxfuse-3.11.2.dmg
==> Verifying SHA-256 checksum for Cask 'osxfuse'.
==> Installing Cask osxfuse
==> Running installer for osxfuse; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Error trying to locate volume at /
==> Purging files for version 3.11.2 of Cask osxfuse
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=nvmnghia USER=nvmnghia USERNAME=nvmnghia /usr/sbin/installer -pkg /usr/local/Caskroom/osxfuse/3.11.2/Extras/FUSE\ for\ macOS\ 3.11.2.pkg -target /` exited with 1. Here's the output:
installer: Error trying to locate volume at /
```

How can I fix this?

**Comment by bfleischer** [comment]
I don't know what might be causing your root volume not showing up in the installer, but this looks more like a macOS issue than a FUSE issue. You will probably run into the same issue with other installers, too. The best might be to raise the issue with Apple support.

**Comment by sajjadintel** [comment]
Were you able to fix this?

**Comment by nvmnghia** [comment]
A clean Hackintosh install helped me.

**Comment by sajjadintel** [comment]
I face this problem in my Macbook pro, after sudden shutdown when battery was drained. this is the second time I face this issue, I can't install macos everytime my battery drains ://

**Comment by sajjadintel** [comment]
running CleanMyMac_X_4.0.3 has fixed the issue
