### ISSUE TITLE
Issues on Big Sur Beta 9: "Missing extension with identifier com.github.osxfuse.filesystems.osxfusefs"

### ISSUE THREAD

**Issue by pat-s** [osxfuse/osxfuse#733]
When upgrading via `brew` I see

```
==> Purging files for version 3.11.2 of Cask osxfuse
Error: osxfuse: Failure while executing; `/usr/bin/sudo -E -- /sbin/kextunload -b com.github.osxfuse.filesystems.osxfusefs` exited with 3. Here's the output:
Executing: /usr/bin/kmutil unload -b com.github.osxfuse.filesystems.osxfusefs
Error occurred unloading extensions: Missing extension with identifier com.github.osxfuse.filesystems.osxfusefs
```

I've run `/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse; echo $?` as suggested in #705 which returned 0 and also allowed the app in the system extension panel (including a reboot).

**Comment by bfleischer** [comment]
Please report this issue to the Homebrew team. The identifier `com.github.osxfuse.filesystems.osxfusefs` is not correct. It needs to be `com.github.osxfuse.filesystems.osxfuse`. And it should not be necessary for Homebrew to unload the FUSE kernel extension. The FUSE installer already does this.

**Comment by pat-s** [comment]
Could it be that the macOS internal identifier changed somehow between Catalina and BigSur? I see that the correct one exists in the homebrew formula and guessing that something happens behind scenes.
Hence I am not sure what if there is anything that can be done on brew's side.

It fails when purging the old install - maybe it works if I trigger a manual uninstall and a fresh install again?

**Comment by bfleischer** [comment]
The `kextunload` command (with the wrong bundle identifier) is called by Homebrew. This is not done by macOS or FUSE. 

The cask contains the wrong identifier: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/osxfuse.rb

**Comment by pat-s** [comment]
Ah!

I changed it locally and wondered because the install still failed. I got confused because the diff is only the `fs` at the end.

Somehow the old identifier is still used for purging even when the formula is updated.

The following worked

```
rm -rf /usr/local/Caskroom/osxfuse
brew install osxfuse
```
