### ISSUE TITLE
Open System Preferences dialog keeps on showing up.

### ISSUE THREAD

**Issue by vijaynr** [osxfuse/osxfuse#735]
Hi, first and foremost, Thanks for this wonderful framework. It solves most of our problems. 

I have a fresh installation of macOS 11 Beta. Then,  when I try to install MyApp which installs osxfuse along with it on that machine, it asks us to navigate to 'System Extensions -> General' and approve the System Extension that's getting loaded. But When I click OPEN, it goes away and comes back again and again. Same with CANCEL too.  Why does the pop-up go away? Is this how it is supposed to be?  I can see from the changelog, that some issue wrt this was solved in 3.11.2. But it looks like the problem is not solved with 3.11.2 either.

**Comment by bfleischer** [comment]
Until the kernel extension has been allowed to load by the user, the alert is displayed on every mount attempt. It looks like something on your Mac tries to mount a volume again and again and again ...

**Comment by vijaynr** [comment]
Yes, you are correct the application which uses osxfuse tries mounting again and again. Now the follow-up question, Does the alert only come when the mount happens?  Or does it come immediately after osxfuse is installed? I would prefer the alert immediately after install though.

**Comment by bfleischer** [comment]
The alert is displayed by the FUSE installer if is it not run silently in background.
