### ISSUE TITLE
4.0.0: Installer prefs pane needs title?

### ISSUE THREAD

**Issue by FGasper** [osxfuse/osxfuse#737]
I see this when trying to install in Mojave:

![image](https://user-images.githubusercontent.com/844867/97718776-b216ef80-1a9c-11eb-8803-b9449446385d.png)

**Comment by bfleischer** [comment]
Which version are you trying to install? 4.0.0?

**Comment by FGasper** [comment]
> Which version are you trying to install? 4.0.0?

Yes, sorry.

**Comment by bfleischer** [comment]
Fixed in the upcoming 4.0.1 release.
