### ISSUE TITLE
Update available: 3.11.2 is shown for macFuse 4.0.0

### ISSUE THREAD

**Issue by vijaynr** [osxfuse/osxfuse#738]
![image](https://user-images.githubusercontent.com/17999110/97737275-cdb4e100-1b02-11eb-907e-60188c58cf0e.png)
This is after installing the macFuse 4.0.0.

**Comment by bfleischer** [comment]
The latest non-beta version is 3.11.2. If you check the "Show Beta Versions" checkbox, it will say 4.0.0 is the newest release.

The behavior is not ideal, but I don't consider this a bug.
