### ISSUE TITLE
preferences pane says 3.11.2 installed even after running a manual install

### ISSUE THREAD

**Issue by patdiddy** [osxfuse/osxfuse#739]
When I tried using the "update FUSE" option in the preferences pane, nothing happened, so I downloaded the installer. After it was successfully installed, I manually allowed it to run in the security preferences pane. Upon returning to the FUSE pane, it's still saying that I don't have 4.0.0 installed. I'm running macOS 10.15.7 on MacBookPro16,1.

A screenshot is attached below
[Screen Shot 2020-10-30 at 3.03.16 PM.pdf](https://github.com/osxfuse/osxfuse/files/5467853/Screen.Shot.2020-10-30.at.3.03.16.PM.pdf)

**Comment by AlbertHusniaux** [comment]
Similar issue.  Preference pane shows version 4.0.1 as the installed version, but mentions there is an update available, 3.11.2 being mentioned.  Weird: it should mention that no update is available.  By the way: it does not display OSXFUSE in the prefence pane, but macFUSE.
How should I correct this?

**Comment by AlbertHusniaux** [comment]
Screenhot pertaining to the previous comment.

<img width="671" alt="macFuse Preference Pane error" src="https://user-images.githubusercontent.com/39201940/97848391-4da09e00-1cf1-11eb-8e3b-093dce328702.png">

**Comment by bfleischer** [comment]
There are two seeds:

* the stable release seed and 
* the developer release seed (beta versions)

The preference pane checks if you are on the latest version for the selected seed. If you are not it will provide the latest version on the seed as an update.

You installed version 4.0.1 (developer release), but you did not select "Show Beta Versions". So you specifically told the updater that you want only stable releases. However, the latest version on the stable release seed is 3.11.2, not 4.0.1.

**Comment by AlbertHusniaux** [comment]
Solved.  Thank you.

**Comment by AlbertHusniaux** [comment]
Dear Benjamin,


I appreciate your quick reaction.  

i had a tick in the “developer” box in the previous preference pane, the OSX Fuse one. 


For some reason, this tick disappeared when upgrading to the 4.0 version.

I had to manually delete the older preference pane as well and restart the Mac, when performing this update.  


All seems fine now. 


Congrats for the product and your speedy reaction.


Cordially Yours,


Albert


Albert Husniaux

albert.husniaux@skynet.be <mailto:albert.husniaux@skynet.be>

Vast		+32 (0)16 81 07 41
Mobiel	+32 (0)472 84 17 76
