### ISSUE TITLE
Getting kext load failed error when switched to macFUSE 4.0.1

### ISSUE THREAD

**Issue by mixtly87** [osxfuse/osxfuse#741]
So I updated OSXFUSE to macFUSE and replaced the OSXFUSE.framework with macFUSE.framework in my app and now I have an issue with macFUSE 4.0.1. When my app tries to mount the volume, the following error occurs:

```
kext load failed: -603946996
mount_macfuse: the file system is not available (255)
```

I'm mounting like this:
```
NSString* volName = [NSString stringWithFormat:@"volname=%@", mountPath.lastPathComponent];
NSString* mountIconPath = [[NSBundle mainBundle] pathForResource:@"mount-icon" ofType:@"icns"];
NSString* volIcon = [NSString stringWithFormat:@"volicon=%@", mountIconPath];
NSArray* options = @[ volName, @"modules=iconv", volIcon, @"auto_cache", @"daemon_timeout=30" ];
[self.fuse mountAtPath:mountPath withOptions:options];
```

macOS Big Sur 11.0.1 Beta (20B5012d)
MacBook Pro (Retina, 13-inch, Late 2013)

Did anyone encounter similar issue?

Also, I have some questions:
1. Is there a rough estimate when will 4.0.1 be released to general public?
2. My current app relies on OSXFUSE.framework. How is that going to work when macFUSE 4.0.1 is released? Is it going to replace the OSXFUSE.framework and thus break my app? Are app users going to need to update the app which uses new macFUSE in order to be able to continue using VFS via my app?
3. Are filesystems example projects going to be updated with new macFUSE 4.0.1 usage so that we can test if those projects would work for us and to see an example on how to use the updated macFUSE 4.0.1?

**Comment by mixtly87** [comment]
I deleted macFUSE and then installed the OSXFUSE latest version, restarted the MBP, but I'm still getting the error:
```
kext load failed: -603946996
mount_osxfuse: the file system is not available (255)
```

in my app console. Should I completely reinstall the macOS? I'm using macOS Big Sur 11.0.1

**Comment by mixtly87** [comment]
When I try manually:
```
cd /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11
sudo kextload osxfuse.kext
Password:
Executing: /usr/bin/kmutil load -p /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11/osxfuse.kext
Validating extension failed: KernelExtension com.github.osxfuse.filesystems.osxfuse v3.11.2 in executable kext bundle com.github.osxfuse.filesystems.osxfuse at /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11/osxfuse.kext:

Filesystem error: Invalid directory for executable kext bundle com.github.osxfuse.filesystems.osxfuse at /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11/osxfuse.kext. Should appear in one of:
	/System/Library/Extensions
	/Library/Apple/System/Library/Extensions
	/Library/Extensions
	/AppleInternal/Library/Extensions
	/System/AppleInternal/Library/AuxiliaryExtensions
	/System/AppleInternal/Diagnostics/AuxiliaryExtensions
	/System/Library/AuxiliaryExtensions
	/Library/StagedExtensions
	/private/var/db/KernelExtensionManagement/Staging
centerdevice@centerdevice 10.11 % pwd
/Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11
```

Does anyone have a hint on how to fix the state?

**Comment by MyopicPaideia** [comment]
Getting the same error all of the sudden as well trying to mount my GDrives via rclone. It started while I was still on OSXFuse so I tried to update to macFUSE to fix it - no dice.

But it is still working on my 2016 13,1 MBP using the same macOS 11.0.1 and the latest OSXFUSE? Weird.

Have tried updating, have had multiple reboots, etc.

     dlg@MBP1422017 ~ % rclone mount TTCAB: /Users/Shared/rclone/TTCAB
     kext load failed: -603946996
     2020/11/13 09:35:00 Fatal error: failed to mount FUSE fs: exit status 255

**Comment by dziny** [comment]
I'm seeing the same issue after upgrading two separate computers. Kext does not load with the error as above (3rd post).

**Comment by bfleischer** [comment]
> 1. Is there a rough estimate when will 4.0.1 be released to general public?

I'm currently working on 4.0.3. It will address some compatibility issues.

> 2. My current app relies on OSXFUSE.framework. How is that going to work when macFUSE 4.0.1 is released? Is it going to replace the OSXFUSE.framework and thus break my app? Are app users going to need to update the app which uses new macFUSE in order to be able to continue using VFS via my app?

macFUSE includes a OSXFUSE.framework symlink. Your App will continue to work just fine if you built it using OSXFUSE 3.

> 3. Are filesystems example projects going to be updated with new macFUSE 4.0.1 usage so that we can test if those projects would work for us and to see an example on how to use the updated macFUSE 4.0.1?

It is just a matter of linking against the new framework. The API is mostly the same. I removed some deprecated non-portal functions from libfuse and added new callbacks to the Objective-C framework. Have a look at the release notes and the headers for more information.  

All file systems compiled with OSXFUSE 3, that do not use deprecated functions and link against libosxfuse or OSXFUSE.framework, should work on macFUSE 4 out of the box. 

I will update the demo projects when I can find some time. Addressing compatibility issues has a higher priority right now.

**Comment by bfleischer** [comment]
Regarding the loading issues of the "kext load failed" issues:
-603946996 means kOSKextReturnValidation (Validation failures encountered; check diagnostics for details)

Can you please check if the following paths exist?

`/Library/StagedExtensions/Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11/osxfuse.kext`

For macFUSE 4 ist should be 

`/Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext`

macOS copies staged kernel extensions to the `/Library/StagedExtensions` folder and loads them from there. If one of the above paths exists, move it to the trash, reboot your Mac and try again.

**Comment by MyopicPaideia** [comment]
The path exists for me (macFUSE 4) - Do I delete only the kext file itself, or the entire macfuse.fs package?

I see no macFUSE kext file in the StagedExtenstions folder

**Comment by bfleischer** [comment]
> The path exists for me (macFUSE 4) - Do I delete only the kext file itself, or the entire macfuse.fs package?

Try deleting `/Library/StagedExtensions/Library/Filesystems/macfuse.fs`.
If `/Library/StagedExtensions/Library/Filesystems` is empty, delete the folder as well.
If `/Library/StagedExtensions/Library` is empty, delete the folder as well. 

> I see no macFUSE kext file in the StagedExtenstions folder

That is weird. But it would explain the kextload error log. macOS failed to stage the extension. 

FUSE simply ties to load the kernel extension (similar to the kextload command above). macOS' KextManager then takes care of the staging. This process is completely transparent for FUSE. I don't think there is anything I can do from the FUSE end. I don't know if there is a way to reset it.

The new KextManager has been buggy in earlier beta versions of Big Sur. Did you upgrade from 10.15 to Big Sur or did you upgrade from one of the Big Sur beta releases?

**Comment by dziny** [comment]
I can confirm: there is no macfuse.kext in /Library/StagedExtensions but the directory /Library/StagedExtensions/Library/Filesystems/macfuse.fs existed, I've deleted since.
My upgrade was directly from Catalina to the just released Big Sur (without going through any beta version).

**Comment by mixtly87** [comment]
> > 1. Is there a rough estimate when will 4.0.1 be released to general public?
> 
> I'm currently working on 4.0.3. It will address some compatibility issues.
> 
> > 1. My current app relies on OSXFUSE.framework. How is that going to work when macFUSE 4.0.1 is released? Is it going to replace the OSXFUSE.framework and thus break my app? Are app users going to need to update the app which uses new macFUSE in order to be able to continue using VFS via my app?
> 
> macFUSE includes a OSXFUSE.framework symlink. Your App will continue to work just fine if you built it using OSXFUSE 3.
> 
> > 1. Are filesystems example projects going to be updated with new macFUSE 4.0.1 usage so that we can test if those projects would work for us and to see an example on how to use the updated macFUSE 4.0.1?
> 
> It is just a matter of linking against the new framework. The API is mostly the same. I removed some deprecated non-portal functions from libfuse and added new callbacks to the Objective-C framework. Have a look at the release notes and the headers for more information.
> 
> All file systems compiled with OSXFUSE 3, that do not use deprecated functions and link against libosxfuse or OSXFUSE.framework, should work on macFUSE 4 out of the box.
> 
> I will update the demo projects when I can find some time. Addressing compatibility issues has a higher priority right now.

Good to know!

But what about projects built with and embedding macFUSE.framework?
Ie, currently I can't Archive my xcode (Xcode 12.2) project because it complains that OSXFUSE.framework doesn't support arm64 architecture. So I updated fuse on my MBP to 4.0.2 and included macFUSE.framework instead of OSXFUSE.framework in my project.
Will users still having 3.11.2 installed on theirs Macs be able to use my app or will they have to update to macFUSE4 before being able to use apps built with macFUSE?

**Comment by dziny** [comment]
I've found the following workaround. After installing maxfuse 4.0.2 I didn't have the folder
/Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/11/
I've manually created it and placed macfuse.kext into it.
Then I've executed 
sudo kextload /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext
and after approving it in Securing center it has loaded!
Have tried reboot but the kext does not load automatically. So as a workaround I've created a shell script at boot to load it. It an unclean fix but I think it indicate where is the issue.

**Comment by bfleischer** [comment]
Thanks for providing the workaround. 

The kernel extension is not supposed to load automatically at boot time. It is loaded when the first FUSE file system is mounted. This means your script should not be required.

**Comment by dziny** [comment]
> The kernel extension is not supposed to load automatically at boot time. It is loaded when the first FUSE file system is mounted. This means your script should not be required.

Well it does not. If I don't execute loading the kext, my mount fails :(

**Comment by bfleischer** [comment]
@dziny This could have many causes. Your workaround might not fix the issue. The file system you are using might not be compatible with the latest version of FUSE or it might use a third party library, that needs to be updated. Without more context it is impossible to make an educated guess.

**Comment by MyopicPaideia** [comment]
Just want to update this. I got it to work in macOS 11.0.1 using the latest releases of macFUSE. All I had to do was disable SIP by restarting in recovery mode and doing `csrutil disable`, then restarting normally.

Then you run your mounting command once, triggering a warning about the extensions trying to be used. Allow the system extensions to be used, and then restart again one more time.

Now the mount extensions are allowed to work as they should by the OS. It seems it is either taking it one step further in security to approve these extensions with macOS Big Sur.

Or else some Macs get the kext permissions screwed up a bit or reset when they are updated to 11.0.1. If anyone else can verify this fixes for them I think we can say we found the problem? Apple's aggressive system integrity protection service.

Don't forget to re-enable csrutil after either :)

**Comment by bfleischer** [comment]
@MyopicPaideia You should not have to disable SIP in order to use macFUSE. macFUSE is properly signed and notarized. Even though disabling SIP seems to solve the issue for you, it is not be required in general.

**Comment by MyopicPaideia** [comment]
@bfleischer understood, but I still had to allow it via System Preferences in the General section of the Security & Privacy pane. And Big Sur informed me that I would need to do a restart of the system in order for the allowed third party (yes properly signed, your name came up as the developer) extensions. Just saying...

I think my machine may have gotten its kernel extension cache locked, corrupted or otherwise permissions screwed up during one of the beta updates or from the final beta to the GM release. That could also explain the behavior.

**Comment by mixtly87** [comment]
What finally worked for me:
1. Uninstall macFUSE
2. Reboot into Recovery mode and in Terminal do `csrutil disable` - but as @bfleischer this step is probably not needed.
3. Reboot into macOS and install macFUSE or OSXFUSE.
4. Enable extension in Security & Privacy

(5. don't forget to `csrutil enable` if you did that step)

P.S.
I had no content in /Library/StagedExtensions folder

**Comment by mixtly87** [comment]
I can confirm that apps linked with OSXFUSE will work on systems having macFUSE installed.
However, vice versa does not apply of course: if you link your app with macFUSE, the target system must have macFUSE installed on it.

Conclusion would be that we should continue to link our apps with OSXFUSE for a while to give customers enough time to update their FUSE to macFUSE - once macFUSE is released.

**Comment by dziny** [comment]
> What finally worked for me:
> 
> 1. Uninstall macFUSE
> 2. Reboot into Recovery mode and in Terminal do `csrutil disable` - but as @bfleischer this step is probably not needed.
> 3. Reboot into macOS and install macFUSE or OSXFUSE.
> 4. Enable extension in Security & Privacy
> 
> (5. don't forget to `csrutil enable` if you did that step)
> 
This worked for me but not the last step. When I reenable `csrutil enable` the kext will not load. I had to do `csrutil enable --without kext`. If kext protection activated I never get the Security & Privacy popup.

**Comment by bfleischer** [comment]
> Conclusion would be that we should continue to link our apps with OSXFUSE for a while to give customers enough time to update their FUSE to macFUSE - once macFUSE is released.

You will need to link against macFUSE 4, if you want to ship a native Apple Silicon (or universal) binary. If you are fine with Rosetta, linking against the old 3.11 release should work.

**Comment by mixtly87** [comment]
> > Conclusion would be that we should continue to link our apps with OSXFUSE for a while to give customers enough time to update their FUSE to macFUSE - once macFUSE is released.
> 
> You will need to link against macFUSE 4, if you want to ship a native Apple Silicon (or universal) binary. If you are fine with Rosetta, linking against the old 3.11 release should work.

Oh yes! I dropped the Apple Silicon in my thoughts. Thanks for a reminder.

**Comment by florian-obradovic** [comment]
Anyway to get osxfuse (installed via brew, coming from catalina upgrade to big sur) working without the csrutil workaround?

**Comment by nevets963** [comment]
Atleast in my case, I solved this issue through an update of FUSE.

Inside System Preferences under the FUSE icon:
![Screenshot 2020-11-24 at 16 32 32](https://user-images.githubusercontent.com/1112574/100123640-a8519380-2e72-11eb-9cd9-fd790663da07.png)

Click 'Check for updates'
![Screenshot 2020-11-24 at 16 32 48](https://user-images.githubusercontent.com/1112574/100123752-c3bc9e80-2e72-11eb-8a5f-87f60af3526e.png)

After it installs, I then tried sshfs within Terminal where it will prompt to allow access, and this must be allowed within 'Security & Privacy'. When doing so, it says the computer must be restarted. After the restart, it's now working again

**Comment by dps-910** [comment]
> What finally worked for me:
> 
> 1. Uninstall macFUSE
> 2. Reboot into Recovery mode and in Terminal do `csrutil disable` - but as @bfleischer this step is probably not needed.
> 3. Reboot into macOS and install macFUSE or OSXFUSE.
> 4. Enable extension in Security & Privacy
> 
> (5. don't forget to `csrutil enable` if you did that step)
> 
> P.S.
> I had no content in /Library/StagedExtensions folder

I did this and it worked, thanks 👍

**Comment by GregDunn1953** [comment]
Mac OS 10.14.6 - uninstalled FUSE, did the reboot/crsutil disable and then installed FUSE 4.0.4/rebooted.  FUSE will load and work properly as long as I have SIP disabled or use '--without kext' but if I attempt to enable SIP again and load FUSE, I get this:

<img width="426" alt="FUSE error" src="https://user-images.githubusercontent.com/48167374/101273147-e8612200-3760-11eb-97c7-f89a6ddaba67.png">

However, there is **no** option to allow the kext in the 'Security&Privacy/General' pane so I can't complete the steps.

**Comment by bfleischer** [comment]
@GregDunn1953 You might be using an app or tool that is able to synthesize keyboard or mouse events. If you are using one of these apps or tools, macOS might not display the Allow button in system preferences. Please see #654.

**Comment by GregDunn1953** [comment]
Good thought!  Unfortunately, I'm not running any app which does that.  Just to be sure, I rebooted in Safe mode and tried to access MacFUSE again; still, the "Allow" button does not appear.  I checked the console log and only found the following references to MacFUSE:

error	01:04:30.072488 -0500	kextd	Unable to stage kext (/Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext) to secure location.

error	01:04:30.072542 -0500	kextd	io.macfuse.filesystems.macfuse was unable to stage properly; failing.

default	01:04:35.513600 -0500	mount_macfuse	MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported

error	01:04:35.597586 -0500	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for RESP:{ID: org.idrix.VeraCrypt, PID[9445], auid: 501, euid: 501, responsible path: '/Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt', binary path: '/Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt'}, ACC:{ID: mount_macfuse, PID[9582], auid: 501, euid: 501, binary path: '/Library/Filesystems/macfuse.fs/Contents/Resources/mount_macfuse'}, REQ:{ID: com.apple.appleeventsd, PID[60], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}


I don't know if that's sufficient info; if not, how to filter the console log to ferret out the needed details?

**Comment by bfleischer** [comment]
> error 01:04:30.072488 -0500 kextd Unable to stage kext (/Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext) to secure location.

This is the reason why the kernel extension cannot be loaded. macOS will not load any kernel extensions that have not been properly staged (`/Library/StagedExtensions`).

**Comment by GregDunn1953** [comment]
I get that - unfortunately I have no idea how to make the installer or OS stage the kext.  I did a full filesystem check to make sure permissions were set properly, removed the staging directories (even running kextcache --clear-staging), removed FUSE and then rebooted, finally doing a new install of FUSE.

Unfortunately, when I try to load FUSE, I still get the dialog but no option to "allow" in the Privacy/General pane.  The staging directories were not re-created by the install process.  I even tried creating and populating the Filesystems kext staging directory manually; this causes the OS to skip the "blocked" prompt but does not allow FUSE to load.  

Disabling SIP (I've been using --without kext) is the only way I can get FUSE to load.

I do have Default Folder X installed, and thought it might be interfering - but quitting it seems to make no difference.  Something about my machine (unmodified 2016 MBP) or installation of Mojave is not behaving properly with regards to kext staging.

**Comment by mike-kfed** [comment]
> Anyway to get osxfuse (installed via brew, coming from catalina upgrade to big sur) working without the csrutil workaround?

I opened a bug in homebrew to no longer install the old osxfuse, there I posted a workaround how to load the macfuse instead Homebrew/homebrew-core#66915 I hope this helps

**Comment by tigger4t** [comment]
I am trying to install Macfuse 4.0.4 on a 2019 Mac with Mojave 10.14.6 after Veracrypt stopped working as it was unable to load FUSE.  When trying to install FUSE I do not get an option in the Privacy pane to allow software from Benjamin Fleischer and have tried most if not all of the solutions in this discussion.  Can anyone help please?

*** UPDATE ****

A reinstall of MacOS Mojave fixed the problem - please ignore.

**Comment by williamhoney** [comment]
@GregDunn1953  I have exactly the same machine, Mojave, no Default Folder X and I get exactly what you get. 

> Unfortunately, when I try to load FUSE, I still get the dialog but no option to "allow" in the Privacy/General pane. 

Same error in Console about kext failed to stage.

> Disabling SIP (I've been using --without kext) is the only way I can get FUSE to load.

This I have not tried yet as I hope for the solution. 

@tigger4t suggested to reinstall Mojave. Really? 

@bfleischer would highly appreciate your thoughts. 

Is there a way to let the installation stage the kext? 

PS. Forgot to say that I actually disabled the gatekeeper with 

`sudo spctl --master-disable`

and I have "Anywhere" checked on the Security&Privacy>General pane.


PPS as I am investigating I stumbled upon this post https://developer.apple.com/forums/thread/657789 which discussed exactly the situation where the policy does not allow creation of a temp dir for kext management.

**Comment by williamhoney** [comment]
Here is what helped me:

https://github.com/pqrs-org/Karabiner-Elements/issues/2373#issuecomment-676121212

quote here for convenience:

> _Based on the temporary directory error, can you check the permissions and flags for the following:
> 
> /private/var/db/KernelExtensionManagement should be 0755 with the "restricted" flag set, and the com.apple.rootless attribute set to KernelExtensionManagement (you can check the value of the attribute with xattr -l)
> /private/var/db/KernelExtensionManagement/Staging should be 0755 with the "restricted" flag set.
> I recently had an issue where VMWare Fusion broke after upgrading to 10.14.6, and after some digging around through the console log, I found that it was trying to use these directories while staging the kexts.
> 
> When compared to another Mac running 10.14.6, I found that the "restricted" flag was not set against KernelExtensionManagement, which appears to have affected how SIP treats the directory.
> 
> If that's the case for you, you should be able to repair it using chflags (e.g chflags restricted /Volumes/Macintosh\ HD/private/var/db/KernelExtensionManagement) from the terminal in recovery mode._

The user StoneJT received great praise for this in the thread I quoted above, pls thank him if it worked for you.

**Comment by GregDunn1953** [comment]
First of all I looked at the private/var/db and KernelExtensionManagement is NOT set to restricted, nor is its subdir "Staging".  But com.apple.rootless was set on both directories.  So on to the next step.

Rebooted into Recovery mode.  Note that you may need to actually mount your Mac HD before continuing.  On my system it was NOT mounted, possibly because I'm using FileVault.

Found the KernelExtensionManagement directory, set 'restricted' on it and its subdir 'Staging'.   Rebooted into normal mode.

Launched VeraCrypt, and MacFUSE loaded and mounted my encrypted drive.  Success!  It didn't even ask for confirmation.

Hope this is useful info.

**Comment by tigger4t** [comment]
> @GregDunn1953 I have exactly the same machine, Mojave, no Default Folder X and I get exactly what you get.
> 
> > Unfortunately, when I try to load FUSE, I still get the dialog but no option to "allow" in the Privacy/General pane.
> 
> Same error in Console about kext failed to stage.
> 
> > Disabling SIP (I've been using --without kext) is the only way I can get FUSE to load.
> 
> This I have not tried yet as I hope for the solution.
> 
> @tigger4t suggested to reinstall Mojave. Really?
> 
> @bfleischer would highly appreciate your thoughts.
> 
> Is there a way to let the installation stage the kext?
> 
> PS. Forgot to say that I actually disabled the gatekeeper with
> 
> `sudo spctl --master-disable`
> 
> and I have "Anywhere" checked on the Security&Privacy>General pane.
> 
> PPS as I am investigating I stumbled upon this post https://developer.apple.com/forums/thread/657789 which discussed exactly the situation where the policy does not allow creation of a temp dir for kext management.

Hi - I have a similar issue with Parallels but a Ctrl+R at state and reinstalling Mojave fixes it every time.  My guess is that FUSE and Parallels installs are over-writing or corrupting something but I lack the expertise to find out what.

**Comment by tiiiecherle** [comment]
The following works for me.

macOS 11.1
macFUSE 4.0.5 (also works for Virtualbox extensions)
SIP settings in Recovery: `csrutil enable --without debug --without fs `

1   copy the extension to
`/Library/Apple/System/Library/Extensions/`

2  load the extension manually (only has to be done once)
`sudo kextload /Library/Apple/System/Library/Extensions/macfuse.kext`

3   confirm security popup

4   open System Preferences - Security - General and confirm extension

5   reboot

I don't know if this is the correct way of doing this but it survives a reboot and the extension works with my sip settings.

**Comment by bentitmus** [comment]
I had a similar issue and the solution proposed by @tiiiecherle works for me (copying the extension to the specified location before manually loading it). I am on macOS 11.1 on an Apple Silicon MacBook Air.

**Comment by ekaulberg** [comment]
The solution @GregDunn1953 and @williamhoney mentioned (from StoneJT's suggestion in a different product's issue) worked for me, on a fresh install of macOS Mojave 10.14.6 with no SIP changes trying to use macFUSE 4.1.2.

**Comment by xxandy** [comment]
From the posts above, assembled this workaround that got me unstuck:

### kill the zombie, non-working one
sudo kextunload /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext

### confirm it is gone
kextstat | grep -i fuse

### bring a fresh one back to life
sudo kextload /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext

### confirm it is back up
kextstat | grep -i fuse

**Comment by HUGHUSR** [comment]
**I have a fix.** The problem is that Mojave updates have whacked some flags on critical directories. You can find the fix here: https://discussions.apple.com/thread/253737669

The problem is that it is a pain to fix, as both directories are sandbox protected, AND you have to boot into safe mode after the flags are fixed, as the missing flags have busted a ton of other permissions as well.

I hope this helps!!

**Comment by GregDunn1953** [comment]
OK, so I ran the ls command.  According to the Apple forum message, I should see:

```
total 0
drwxr-xr-x@   3 root  wheel  restricted   96B Jun 24  2021 ./
	com.apple.rootless	  25B 
drwxr-xr-x  125 root  wheel  sunlnk      3.9K Mar 12 17:13 ../
drwxr-xr-x    2 root  wheel  restricted   64B Mar 12 17:22 Staging/
```
But here's what I see:
```

total 0
drwxr-xr-x@   4 root  wheel  restricted  128B Feb 27 23:50 ./
	com.apple.rootless	  25B 
drwxr-xr-x  109 root  wheel  sunlnk      3.4K Mar  5 05:38 ../
drwxr-xr-x    3 root  wheel  restricted   96B Feb 27 23:51 AuxKC/
drwxr-xr-x@   2 root  wheel  restricted   64B Feb  8 23:14 Staging/
	com.apple.rootless	  -1B
```

They're different, in that Staging has additional attributes.  Do I clear them in Safe mode?  If so, how?  The Apple forum message hints that you have to use chflags, but omits any details as to how this is achieved.

**Comment by GregDunn1953** [comment]
Well, folks, I finally just gave up.  Figuring I'd spend a few hours or days trying to fix this, as well as some other application installation problems I'd been having with this laptop, I just re-formatted the HD and restored all my stuff from a backup.

Everything works perfectly now.  It took just under 2 hours to format and restore everything, plus updating FUSE.  It's clear that installing a new OS on top of an older one is sometimes not the way to go, and this is one of them.  Thanks for all the suggestions, and may your path be easier!

**Comment by doncwilliam** [comment]
You may take a look at this article: https://docs.hedge.video/postlab/drive/fuse
