### ISSUE TITLE
document new mount protocol for 4.0.0

### ISSUE THREAD

**Issue by wez** [osxfuse/osxfuse#742]
Over in https://github.com/facebookexperimental/eden we talk directly to the kernel component of both linux and osxfuse so that we are able to migrate live mounts from one version of the software to another without unmounting (we call this mechanism "graceful restarts").  We don't (cannot!) use libfuse and we perform our own `mount` syscall with appropriate mount options.

With the new 4.x release the details have changed in an opaque way.
I can see that paths have changed in the new install image, which seems simple enough to deal with, but the release notes refer to dropping support for the "old style" mount protocol that we're using.

Please share details on how the new style protocol works so that we can evaluate what we need to do to prepare for 4.x.

**Comment by bfleischer** [comment]
Ten days ago, I contacted you via email regarding the issue and an opportunity for Facebook to sponsor the continued development of FUSE on macOS. Since I have not received a reply, I was wondering, if you received my email.
