### ISSUE TITLE
version mismatch?

### ISSUE THREAD

**Issue by hmijail** [osxfuse/osxfuse#743]
I'm trying to build libfuse/sshfs, which requires osxfuse. So I installed FUSE for macOS 3.11.2.

The sshfs build fails because it tries to find `fuse3` through `pkg-config`.
But `pkg-config`'s packages only list a `fuse` which says `Version: 2.9.7`.

So, what is the actual library version of osxfuse? Should the pkg-config file list another version number?

**Comment by bfleischer** [comment]
FUSE for macOS 3.11.2 ships with a modified version of libfuse 2.9.7. You will need to use sshfs 2.x.
