### ISSUE TITLE
Can't mount partition 

### ISSUE THREAD

**Issue by niceonegary** [osxfuse/osxfuse#745]
This is probably just user error but I'm getting the following when trying to mount a partition of an NTFS disk

NTFS signature is missing.
Failed to mount '/dev/disk4': Invalid argument
The device '/dev/disk4' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?

**Comment by bfleischer** [comment]
`/dev/disk4` is the whole disk, not a partition. Try mounting the actual NTFS partition.

Please note that NTFS-3G and FUSE are independent projects. Please contact the NTFS-3G support for NTFS related questions.
