### ISSUE TITLE
Kernel extension cannot be loaded on Big Sur due to legacy BlackBerry driver

### ISSUE THREAD

**Issue by MrMartinuk** [osxfuse/osxfuse#746]
I've read all the other posts, but I can't get OSX/Mac fuse working on Big Sur :(  I've tried disable SIP, tried all the other work arounds. To no avail. If I load the kernel extension manually, I get this horrible error moaning about some Blackberry stuff. I have tried deleting all mentions of Blackberry anywhere but it still errors.  Any  advice appreciated

sudo kextload macfuse.kext

Executing: /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/10.11/macfuse.kext
Unable to resolve dependencies for com.rim.driver.BlackBerryUSBDriverInt: 'com.rim.driver.BlackBerryUSBDriverInt, required by "com.highpoint-tech.kext.HighPointRR, io.macfuse.filesystems.macfuse, com.highpoint-tech.kext.HighPointIOP, com.rim.driver.BlackBerryUSBDriverVSP, com.huawei.driver.HuaweiDataCardHiPortDriver, com.epson.print.kext.USBPrintClass, com.FTDI.driver.D2XXHelper, com.softraid.driver.SoftRAID, com.silabs.driver.CP210xVCPDriver64" names a dependency on 'com.apple.iokit.IOUSBMassStorageClass', which was not found.

**Comment by bfleischer** [comment]
This is a know issue/bug of Apple's new Kext Manager implementation on macOS Big Sur. FUSE does not in any way depend on the BlackBerry kernel extension.

Have a look at the section "Removing BlackBerry drivers" on https://bombich.com/kb/ccc5/some-third-party-storage-drivers-may-cause-hardware-misbehavior. After removing the BlackBerry driver make sure to reboot your Mac.

**Comment by bfleischer** [comment]
> /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/10.11/macfuse.kext

Make sure to load the proper kernel extension for Big Sur after removing the BlackBerry driver. If you are using macFUSE 4 the correct path is `/Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext`

**Comment by MrMartinuk** [comment]
Thanks, that worked! thought I had removed all the blackberry bits and pieces but found a few more as per the guide. 

Thanks for that. I feel I have got my life back now ! :)

**Comment by bfleischer** [comment]
I'm glad it worked!
