### ISSUE TITLE
Enabling kernel extensions on M1 Mac fails with error 11

### ISSUE THREAD

**Issue by mbirth** [osxfuse/osxfuse#747]
I am trying to install osxfuse 4.0.3 on my new M1 Mac and macOS tells me to change the security policy in the Recovery Environment. However, when trying this, I get the error:

    The operation couldn't be completed.
    (com.apple.BootPolicy.updateTagError error 11.)

Any hints?

**Comment by mbirth** [comment]
Never mind. Booted back into the system, then back into the Recovery Environment and suddenly it worked without complaining.

**Comment by mcfearsome** [comment]
I am experiencing this as well and rebooting and retrying does not change anything.

Oddly when I go into the utility, the "Reduced Security" radio button is checked. What I cannot do is check "Allow user management of kernel extensions...", trying to do that results in an error.

I am not familiar with this utility and it's full purpose but that box seems like one I want checked.

Appreciate any help anyone can provide!

Edit: To be explicit, I am on a m1 MacBook Pro

**Comment by unbeatable-101** [comment]
> I am experiencing this as well and rebooting and retrying does not change anything.
> 
> Oddly when I go into the utility, the "Reduced Security" radio button is checked. What I cannot do is check "Allow user management of kernel extensions...", trying to do that results in an error.
> 
> I am not familiar with this utility and it's full purpose but that box seems like one I want checked.
> 
> Appreciate any help anyone can provide!
> 
> Edit: To be explicit, I am on a m1 MacBook Pro

Try again, it worked for me on an M1 MacBook Air

**Comment by mcfearsome** [comment]
> > I am experiencing this as well and rebooting and retrying does not change anything.
> 
> > 
> 
> > Oddly when I go into the utility, the "Reduced Security" radio button is checked. What I cannot do is check "Allow user management of kernel extensions...", trying to do that results in an error.
> 
> > 
> 
> > I am not familiar with this utility and it's full purpose but that box seems like one I want checked.
> 
> > 
> 
> > Appreciate any help anyone can provide!
> 
> > 
> 
> > Edit: To be explicit, I am on a m1 MacBook Pro
> 
> 
> 
> Try again, it worked for me on an M1 MacBook Air

And...same result.

**Comment by unbeatable-101** [comment]
Are you doing it by using the dialogue box in system preferences or by manually rebooting?
@mcfearsome

**Comment by mcfearsome** [comment]
> Are you doing it by using the dialogue box in system preferences or by manually rebooting?
> 
> @mcfearsome

I am rebooting and using the "Startup Security Utility"
