### ISSUE TITLE
System Extension Blocked

### ISSUE THREAD

**Issue by ikitayama** [osxfuse/osxfuse#749]
I'm on M1. Is this still expected behavior with the Beta 4.0.3?

**Comment by bfleischer** [comment]
4.x supports M1 Macs. You need to provide  more context. Did you enable loading third party kernel extensions in recovery mode?

**Comment by ikitayama** [comment]
Yes, I did.

**Comment by ikitayama** [comment]
The latest macOS Big Sur 11.0.1.

**Comment by ikitayama** [comment]
I just saw I have both FUSE and macFUSE, is this causing the trouble?

**Comment by ikitayama** [comment]
Now I have this:

```
  dyld: Library not loaded: /usr/local/lib/libosxfuse.2.dylib
  Referenced from: /usr/local/bin/sshfs
  Reason: image not found
```

**Comment by bfleischer** [comment]
See #347.

**Comment by ikitayama** [comment]
Thanks, but now I am seeing the Subject message again.

**Comment by ikitayama** [comment]
@bfleischer do you have access to M1?

**Comment by ikitayama** [comment]
I'd appreciate suggestions from the current M1 owners.

**Comment by ikitayama** [comment]
I don't think this is possible on Big Sur, no?
```
The system extension required for mounting macFUSE volumes could not be loaded.

Please open the Security & Privacy System Preferences pane, go to the General preferences and allow loading system software from developer "Benjamin Fleischer". A restart might be required before the system extension can be loaded.

Then try mounting the volume again.
```

**Comment by bfleischer** [comment]
> Thanks, but now I am seeing the Subject message again.

Please read the ticket to the end. You are missing a symlink for SSHFS to work.

**Comment by ikitayama** [comment]
I have this though:

```
✗ ls -lrt libosxfuse_i64.2.dylib
lrwxr-xr-x  1 itaru  staff  15 Nov 27 07:35 libosxfuse_i64.2.dylib -> libfuse.2.dylib
```

**Comment by ikitayama** [comment]
Switching to the release 4.0.2 worked for me. I.e., I was able to make the system recognize you as a trusted developer.
