### ISSUE TITLE
SSHFS: Apple Silicon Native Support

### ISSUE THREAD

**Issue by Harry1993** [osxfuse/osxfuse#751]
As of now, here is how to run sshfs natively on your Apple M1 devices.

I bought a MacBook Air M1 notebook and I want to run sshfs natively. However, macports fails to compile osxfuse (I believe it will be fixed soon, but I don't wanna wait), so I manually downloaded and installed macFUSE 4.0.3 as it is arm64-native. Then, I downloaded sshfs 2.10 (sshfs 3.* are not compatible with osxfuse) and tried to compile it locally. It failed, unfortunately, because `fuse_darwin.h` can't be found under `/usr/local/include/fuse/`.

Then, I went to `/usr/local/include/fuse/` and found `fuse.h`. So, I went back to `sshfs.c` and changed `# include <fuse_darwin.h>` to `#include <fuse.h>`. This time, sshfs was built successfully, and also runs smoothly.

For the future, as far as I can see, either macFUSE should rename it back, or SSHFS 2.10 should update its `sshfs.c`.

**Comment by owenschris** [comment]
Thanks for posting the workaround. I think the release as of today (4.0.4) is arm64-native ~~and now includes sshfs bundled with it~~. 

The only real steps were Big Sur related:

- I needed to do the permissions recovery boot to allow non-Apple extensions.
- I also needed to change some mount points in old scripts since there have been changes to what locations are read-only in the filesystem. 

Works without incident for my setup so far -- thanks @bfleischer and contributors.

**Comment by Harry1993** [comment]
> Thanks for posting the workaround. I think the release as of today (4.0.4) is arm64-native and now includes sshfs bundled with it.
> 
> The only real steps were Big Sur related:
> 
> * I needed to do the permissions recovery boot to allow non-Apple extensions.
> * I also needed to change some mount points in old scripts since there have been changes to what locations are read-only in the filesystem.
> 
> Works without incident for my setup so far -- thanks @bfleischer and contributors.

Thanks! I just installed Version 4.0.4 and rebooted. Could you tell me where to find the sshfs executable that is bundled?

**Comment by owenschris** [comment]
Oops, you're right. Your workaround works with the 4.0.4 release, but sshfs isn't included from what I see. It looks like I built sshfs following your suggestions but was actually stuck in a bad permissions state or had some issue with the files that was fixed by the update or the additional reboot. Sorry about that.

**Comment by bfleischer** [comment]
Currently I do not have time to create a pull request for SSHFS. The old 2.5.0 build should still work fine with macFUSE 4.0.4 on Big Sur.

@Harry1993 It seems you have already patched 2.10 to work with macFUSE 4.0.4. Please create a pull request on the upstream SSHFS repository at https://github.com/libfuse/sshfs/. Thanks.

**Comment by canversemike** [comment]
Also got this working today with 2.5 by removeing # include <fuse_darwin.h>
Cheers.

**Comment by notDavid** [comment]
In case anyone else stumbles upon this error after compiling sshfs 2.5:
`(process:77242): GLib-CRITICAL **: 21:40:21.772: g_slice_set_config: assertion 'sys_page_size == 0' failed`

Removing these lines fixes it: https://github.com/libfuse/sshfs/pull/27/files

**Comment by NSExceptional** [comment]
Hey all; what's the status of this? Trying to install `sshfs` from homebrew yields `no bottle for Apple Silicon`. Was the homebrew stuff never updated?

**Comment by galicae** [comment]
here in 2023 to say this workaround still works in an Apple M1 Max on Ventura 13.1.

**Comment by DolphDev** [comment]
Wanted to shoutout I've created - https://github.com/DolphDev/Mac-Build-Your-Own-SSHFS - It's requires you to build yourself, but made it easy. It's based on insights from https://github.com/tormodwill/macSSHFS and builds the last version of sshfs to support libfuse 2.x

For any developers that what this on arm, plus a more recent version, hope this helps. Not sure if the current workaround still works.
