### ISSUE TITLE
kGMUserFileSystemMountPathKey removed in macFUSE 4.0.x

### ISSUE THREAD

**Issue by znek** [osxfuse/osxfuse#752]
kGMUserFileSystemMountPathKey (@"mountPath")  has been removed in macFUSE 4.0.x, meaning that macFUSE isn't binary compatible with OSXFUSE, which is a pitty. Would it be possible to reintroduce the key with a future 4.0.x update?

**Comment by bfleischer** [comment]
Thanks for the bug report. macFUSE 4 is not supposed to break binary compatibility with existing file systems. The key is deprecated, so I removed it from the header, but I forgot to keep exporting the constant. The userInfo dictionary still contains the mount path for now. However, the @"mountPath" key will not longer be present in version 5.

**Comment by bfleischer** [comment]
The issue will be fixed in the upcoming 4.0.5 release.
