### ISSUE TITLE
Updated to macOS 11.1 beta, kext load failed

### ISSUE THREAD

**Issue by lxchtan** [osxfuse/osxfuse#756]
The macfuse installed version is 4.0.4.

When I run `sshfs`, it shows that

```shell
kext load failed: -603946986
mount_macfuse: the file system is not available (255)
```

Try to run 

```shell
sudo kextload /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext
```

It complained

```shell
Executing: /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext
Error Domain=KMErrorDomain Code=31 "Error occurred while building a collection: in '/Library/Extensions/spl.kext/Contents/PlugIns/KernelExports.kext/KernelExports' missing __TEXT segment" UserInfo={NSLocalizedDescription=Error occurred while building a collection: in '/Library/Extensions/spl.kext/Contents/PlugIns/KernelExports.kext/KernelExports' missing __TEXT segment}
```

Security & Privacy pane didn't have the warnings to allow, when I try the method in #741. 

What's wrong?

**Comment by bfleischer** [comment]
Delete `/Library/Extensions/spl.kext`. This kernel extension is not compatible with macOS 11 and prevents other kernel extensions from loading. That's why the FUSE kernel extension cannot be loaded in your case. As far as I know spl.kext is related to OpenZFS.

**Comment by lxchtan** [comment]
It worked, thanks a lot.
