### ISSUE TITLE
Unable to update to FUSE 4.0.4

### ISSUE THREAD

**Issue by odalage** [osxfuse/osxfuse#758]
I am tryin g to update FUSE version from 3.10.4 to 4.0.4 in the preference pane but after a few seconds of seemingly trying to update, it goes back to the previous state.
Do I have to remove it (uninstall) and reinstall FUSE?

**Comment by vordenken** [comment]
Had the same problem. I just manually downloaded the newest version from the GitHub releases and installed it without a problem.
