### ISSUE TITLE
/sbin/ read-only in Big Sur even after apfs unlockVolume

### ISSUE THREAD

**Issue by cionz0** [osxfuse/osxfuse#760]
I've installed all the required things by following https://github.com/osxfuse/osxfuse/wiki/NTFS-3G#auto-mount-ntfs-volumes-in-read-write-mode and I want to mount automatically in RW mode ntfs volumes.

Of course, I've disabled SIP.

When I run `diskutil apfs unlockVolume disk1s1` it says that the volume is already unlocked.

But then, when I try to backup `/sbin/mount_ntfs ` I get an error saying that the volume is read-only.

I've tried both from "normal" and recovery mode.

Any hints?

**Comment by maticrivo** [comment]
I'm facing the same issue.. any idea how to solve this?

**Comment by knightjp** [comment]
I would like to find a solution to this as well.

**Comment by mostafa0017** [comment]
`sudo mount -u -w "/Volumes/YourDriveName"`
ie:
`sudo mount -u -w "/Volumes/Macintosh HD"`
The use of `-u` changes the status of an already mounted file system and `-w` will mount it as `read-write`.
