### ISSUE TITLE
Can "prevent 3rd-party extension loading" be re-enabled after successful install?

### ISSUE THREAD

**Issue by Europa2010AD** [osxfuse/osxfuse#761]
My system is running MacOS 11.1 on a Mac Mini M1.

The extension loading prevention feature that's disabled in safe-mode during installation -- can it be re-enabled after verifying MacFuse works as intended? Or will it prevent the extension from loading at the next reboot?

**Comment by NewAlexandria** [comment]
Try it and report back.  I've read that some have issues and some don't.

**Comment by bfleischer** [comment]
@Europa2010AD You will need to leave your M1 Mac mini in "reduced security mode", otherwise macOS will refuse to load third-party kernel extensions.
