### ISSUE TITLE
Never seeing the FORGET op-code

### ISSUE THREAD

**Issue by Feuermurmel** [osxfuse/osxfuse#765]
To gain experience with macFUSE, I've implemented a toy filesystem using the [Python-LLFUSE](https://github.com/python-llfuse/python-llfuse) package and am running it agains macFUSE 4.0.4 on macOS 10.13.6. Python-LLFUSE is giving me access to the low-level interface of libfuse 2 (`struct fuse_lowlevel_ops`).

The problem that I'm running into is that I'm never seeing a call to `forget()`. My assumption is that these messages either never reach the user-land process or are somehow lost inside of libosxfuse. My reasoning for this is that I'm running both my filesystem and `sshfs` (the binary distribution from https://osxfuse.github.io) with `-o debug` passed to FUSE and the FORGET op-code never appears in the log output (I assume [this line in fuse.c](https://github.com/libfuse/libfuse/blob/fuse_2_9_bugfix/lib/fuse.c#L2749) would produce it).

In the case of `sshfs` I'm doing this:

```
$ mkdir mnt backing
$ sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
$sshfs -f -s -d -o debug localhost:backing mnt 2>&1 | tee log.txt
[...]
```

In another terminal:

```
$ for i in {000..999}; do touch mnt/$i; rm mnt/$i; done
```

When this finishes, I terminate the `sshfs` process and look at `log.txt`, e.g.:

```
$ grep -i forget log.txt
```

Which comes back empty. At the same time, I'm seeing a lot of log lines for CREATE and LOOKUP, which to my understand should eventually be matched by calls to FORGET:

```
$ grep -i create log.txt | tail
   create[4300229648] flags: 0xa02 /522
unique: 6, opcode: CREATE (35), nodeid: 1, insize: 60, pid: 16570
create flags: 0xa02 /523 0100644 umask=0000
   create[4298161088] flags: 0xa02 /523
unique: 4, opcode: CREATE (35), nodeid: 1, insize: 60, pid: 16572
create flags: 0xa02 /524 0100644 umask=0000
   create[4300232912] flags: 0xa02 /524
unique: 5, opcode: CREATE (35), nodeid: 1, insize: 60, pid: 16574
create flags: 0xa02 /525 0100644 umask=0000
   create[4298161280] flags: 0xa02 /525
```

Am I misunderstanding something? Gauging from the [documentation in `fuse_lowlevel.h`](https://github.com/libfuse/libfuse/blob/fuse_2_9_bugfix/include/fuse_lowlevel.h#L207), this op-code is necessary to correctly implement a FUSE filesystem.

**Comment by bfleischer** [comment]
`FORGET` is sent when the vnode (in kernel space) is reclaimed by macOS. This should be the case when unmounting the file system. Killing `sshfs` is not a clean way to unmount the file system. When using the `umount` command or `diskutil unmount` you should see the `FORGET` messages.
