### ISSUE TITLE
/sbin/mount_ntfs keeps getting back to original

### ISSUE THREAD

**Issue by maticrivo** [osxfuse/osxfuse#766]
Hi, following the guide https://github.com/osxfuse/osxfuse/wiki/NTFS-3G#auto-mount-ntfs-volumes-in-read-write-mode-on-macos-1015-catalina on mac os Big Sur I successfully renamed the original mount command to `mount_ntfs.orig` and created the new `mount_ntfs` file with the contents on the guide, but when restarting back to normal the file I added is deleted and the original file is back in it's place.

any idea?

**Comment by knightjp** [comment]
How did you manage to rename the file. I always get an error stating that the section is only read only. 
`mv: rename /sbin/mount_ntfs to /sbin/mount_ntfs.orig: Read-only file system`

**Comment by Laurazepam** [comment]
> How did you manage to rename the file. I always get an error stating that the section is only read only. 
> 
> `mv: rename /sbin/mount_ntfs to /sbin/mount_ntfs.orig: Read-only file system`

"sudo mount -uw /" will mount root as rw, sip needs to be disabled for this to work

**Comment by knightjp** [comment]
> > How did you manage to rename the file. I always get an error stating that the section is only read only.
> > `mv: rename /sbin/mount_ntfs to /sbin/mount_ntfs.orig: Read-only file system`
> 
> "sudo mount -uw /" will mount root as rw, sip needs to be disabled for this to work

I tried this... disabled SIP and then rebooted the system. 
I got this error... 
`mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66`

**Comment by Linus-XZX** [comment]
This seems to be a macOS feature... Whenever an update is installed many modified system files get reverted. As far as I'm concerned this reverting would cover practically everything with the `com.apple.rootless` xattr.

**Comment by knightjp** [comment]
> This seems to be a macOS feature... Whenever an update is installed many modified system files get reverted. As far as I'm concerned this reverting would cover practically everything with the `com.apple.rootless` xattr.

You do have a point. I would say that when it comes to security, it probably is a good policy. But not for those of us that want to have added functionality of writing to a NTFS formatted drive..

**Comment by bfleischer** [comment]
The proper way to add support for writing NTFS volumes would probably be to create a file system bundle in /Library/Filesystems instead of replacing a system tool in /sbin. But this would be beyond the scope of the macFUSE project.
