### ISSUE TITLE
can't mount a drive in rclone

### ISSUE THREAD

**Issue by eyeran** [osxfuse/osxfuse#767]
hey there,

when I'm trying to mount a drive (google drive in my case) using rclone, i get the following error:

`2020/12/30 13:13:05 Fatal error: failed to mount FUSE fs: cannot locate OSXFUSE`

Since my programming skills are not that advanced, I don't really know what to do from there on. 
I'm using a MBP from late 2013 with the latest version of Catalina running on it and have the latest version of OSXFUSE installed (4.0.4.)

I would appreciate any help, thank you! :)

**Comment by bfleischer** [comment]
Please raise the issue with the rclone team. rclone might need to be updated to be compatible with macFUSE 4.

**Comment by eyeran** [comment]
alright, thank you! :)
