### ISSUE TITLE
Is MacFUSE still open-source?

### ISSUE THREAD

**Issue by inklesspen** [osxfuse/osxfuse#768]
The "source" tarball for recent releases contains only the license file. However, this license file still has references to "source distributions".

Will the source for 4.x be available, or is this project becoming closed source?

**Comment by bfleischer** [comment]
The latest version of the source code, that is available on GitHub, is for 3.8.3. For the time being most components of macFUSE are closed source. libfuse, which is covered under the LGPL, can be found on https://github.com/osxfuse/fuse/tree/master/.
