### ISSUE TITLE
Does macFuse only work with reduced system security in Apple Silicon?

### ISSUE THREAD

**Issue by vijaynr** [osxfuse/osxfuse#769]
I had to Reduce the System Security and Allow loading of third party kernel extensions to load the macFuse kernel extension on Apple silicon Macs? Is there no work around for it?

**Comment by bfleischer** [comment]
That's the way Apple designed macOS 11 on Apple Silicon Macs. I'm afraid there is no way around it. The process is not user friendly, but at least you have to do this only once.

That being said, if there was a new non-kernel API for developing full-featured file system, I would update FUSE to use the new API, but there is no such non-kernel API.
