### ISSUE TITLE
v4 is called macfuse but the readme says osxfuse is the successor of macfuse

### ISSUE THREAD

**Issue by balupton** [osxfuse/osxfuse#770]
https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.5

yet

> The FUSE for macOS software package provides multiple APIs for developing file systems for OS X 10.9 to macOS 10.13. It is a successor to MacFUSE, which has been the basis of many products, but is no longer being maintained.
> https://github.com/osxfuse/osxfuse/blob/master/README.md#about-fuse-for-macos

> "FUSE for OS X" is a fully backwards compatible successor to MacFUSE. MacFUSE is used by many applications but has not seen an official update since 2008. The latest release does not fully support Mac OS X 10.6 and will not work at all on OS X 10.7 and later versions. The OSXFUSE project has sprung from the MacFUSE Google Group in order to continue the work on FUSE for OS X. See question 1.3 for information about the "MacFUSE Compatibility Layer".
> https://github.com/osxfuse/osxfuse/wiki/FAQ#11-what-is-fuse-for-os-x-is-it-the-same-as-macfuse-or-fuse-on-linux

So confused

**Comment by bfleischer** [comment]
Fixed
