### ISSUE TITLE
renameat stuck - process killed

### ISSUE THREAD

**Issue by olvrlrnz** [osxfuse/osxfuse#773]
I'm writing a new file system. As usually, I start with loopbackFS and modify as necessary. Since my goal is to mount a folder to the same file system path, I have to use the *at variants of various calls. In case of rename:
```c
static int loopback_rename(const char *from, const char *to)
{
    int res;

    res = renameat(rootFolderFd, make_relative_path(from), rootFolderFd, make_relative_path(to));
    if (res) {
        return -errno;
    }

    return res;
}
```

where `rootFolderFd` is a file descriptor to the now "invisible" source directory. `make_relative_path` translates e.g. `/foo.txt` to just `foo.txt`.

So far, `rename` has been the only call that causes problems:
```
sh-3.2$ mv foo.txt bar.txt
mv: rename foo.txt to bar.txt: Socket is not connected
```
It will take `$(daemon timeout)` seconds until the ```mv``` call returns with an error, the file on disk however has been renamed successfully. Which leads me to believe the syscall went through but does not return from the fuse vfs code in kernel. A sample of the mount process while the shell, or Finder for that matter, is stuck:
```
    2664 Thread_11350
    + 2664 thread_start  (in libsystem_pthread.dylib) + 15  [0x7fff2031a47b]
    +   2664 _pthread_start  (in libsystem_pthread.dylib) + 224  [0x7fff2031e950]
    +     2664 ???  (in libfuse.2.dylib)  load address 0x10d9f9000 + 0x12970  [0x10da0b970]
    +       2664 ???  (in libfuse.2.dylib)  load address 0x10d9f9000 + 0x1647c  [0x10da0f47c]
    +         2664 ???  (in libfuse.2.dylib)  load address 0x10d9f9000 + 0xab2c  [0x10da03b2c]
    +           2664 ???  (in fs)  load address 0x10d9db000 + 0x405e  [0x10d9df05e]
    +             2664 ???  (in fs)  load address 0x10d9db000 + 0x587a  [0x10d9e087a]
    +               2664 renameat  (in libsystem_kernel.dylib) + 11  [0x7fff202f49db]
    +                 2664 __renameat  (in libsystem_kernel.dylib) + 10  [0x7fff2030be6a]
```

On Linux, the same code works as expected.

Just out of curiosity I placed the `renameat` call in an async block:
```c
static int loopback_rename(const char *from, const char *to)
{
    char *f = strdup(from);
    char *t = strdup(to);

    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        int res;

        fprintf(stderr, "### calling rename\n");
        res = renameat(rootFolderFd, make_relative_path(f), rootFolderFd, make_relative_path(t));
        fprintf(stderr, "### called rename: %s\n", res ? strerror(errno) : "OK");

        free(t);
        free(f);
    });

    return 0;
}
```
which does _not_ get stuck.

Does anybody have an idea what's going on?

Fuse Version: 4.0.5
OS Version: 11.1 (20C69)
Xcode Version: 12.3 (12C33)

**Comment by bfleischer** [comment]
File system callbacks are not allowed to call back into the FUSE file system, i.e. trigger file system operations on the FUSE volume. This can result in a deadlock in the FUSE kernel extension.

I'm assuming your renameat() call triggers such a file system operation along the way. This fits your dispatch_async() observation.

> On Linux, the same code works as expected.

This might be due to some implementation differences between Linux and macOS.

**Comment by olvrlrnz** [comment]
I tried a different scenario:

- Have a folder, e.g. `$(HOME)/mnt` with a file `foo.txt` in it
- Compile and run the following program:
```c
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    int fd, res;
    const char *dir = "<HOME>/mnt";

    if ((fd = open(dir, O_DIRECTORY | O_RDONLY)) == -1) {
        fprintf(stderr, "open: %s\n", strerror(errno));
        exit(1);
    }

    fprintf(stderr, "Mount something on %s and press any key to continue ...\n", dir);
    getchar();

    res = renameat(fd, "foo.txt", fd, "bar.txt");
    fprintf(stderr, "renameat: %s\n", res ? strerror(errno) : "OK");

    close(fd);
    return res;
}
```
- For simplicity I attached an empty disk image there: `hdiutil attach ~/empty.dmg -mountpoint ~/mnt`
- Continue the test program
- `renameat` gets called and returns immediately without error

This is basically what loopback fs does except this works. And I don't really understand where the difference is

**Comment by bfleischer** [comment]
If you want to know where the file system hangs, have a look at the stackshot command line tool. It should allow you to capture kernel stack traces when your file system hangs. It should then be relatively easy to see what's going on. 

> This is basically what loopback fs does except this works. And I don't really understand where the difference is

This scenario might look similar but it is completely different. 

When your file system is stuck in the rename callback the files and folders on the FUSE volume, that are involved in the rename process, are locked until your rename callback returns. If your rename callback then triggers a file system operation on the FUSE volume involving one of the locked files or folders, it will be blocked until the locks have been released. This means your rename callback would be waiting on itself to return. This is a deadlock.

When mounting a DMG your test program only calls renameat(), but it is not responsible for handling file system operations on the DMG.
