### ISSUE TITLE
GPG signature problems

### ISSUE THREAD

**Issue by ajay-gh** [osxfuse/osxfuse#775]
Downloading of Macfuse 4.0.5 and trying to verify the file's signature, I see this

> Untrusted signature
> Benjamin Fleischer <fleiben@gmail.com>
> 135F 164B 411B AA1F 4A4B  CD37 617A 3461 8026 08A1
> The signature of this message is valid but untrusted. That means it has not been tampered with. It is untrusted though, because the key has not yet been verified. This KB-article explains how to verify and sign a public key.

Going back to my GPG keychain it appears that the associated key has a different fingerprint (0093 B21E F45D 6352 84F6   A147 53C9 18C1 A281 8875), with the same email in use. Updating from the key server, this is not rectified. I do not see a way to "add  trust" to the key with fingerprint 135F or to verify this key here on github or elsewhere.

**Comment by bfleischer** [comment]
Please see https://github.com/osxfuse/osxfuse/issues/679
