### ISSUE TITLE
Permission for distribution with brew cask 

### ISSUE THREAD

**Issue by NotANormalNerd** [osxfuse/osxfuse#777]
Hello Benjamin,

When I am already here: I saw you changed the License  `redistributions bundled with commercial software are not allowed without specific prior written permission` 
My question and hereby also asking for permission just to clarify: Do you consider homebrew commercial software (it's open source so I would not) or is homebrew still allowed to distribute the osxfuse cask version 4 going onward?

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/osxfuse.rb

Thanks a lot.

Best regards,
Dennis Schmalacker

**Comment by NotANormalNerd** [comment]
Nvm. Did not see the name change.

**Comment by bfleischer** [comment]
For the record, I do not consider Homebrew commercial software. The license change does not affect Homebrew.
