### ISSUE TITLE
Issues mounting in OS 11.1

### ISSUE THREAD

**Issue by Tagnal-git** [osxfuse/osxfuse#778]
I am testing on an OS 11.1 machine and running our 3rd party version of macFUSE 4.0.5 (SSMFS).  Sometimes when I run our app, it properly mounts the file system.  If I then close our app, it unmounts the file system and quits.  If I try to relaunch and remount the file system, I do get the kGMUserFileSystemDidMount notification, however, the file system doesn't appear to mount in the Finder.  And exactly 2 minutes later, I get the kGMUserFileSystemDidUnmount notification.  (something timed out?). At this point, I am unable to mount the file system any more for some random amount of time it seems.  I may wait a few minutes and try again and it might work, other times it doesn't work again for an extended amount of time.  

kmutil showloaded shows that the kext is loaded.  

Everything works as expected in Catalina.    

Is this related to:
_Please note, that in some cases, loading the SSMFS system extension on macOS 11 might not work on the first attempt. In total I reported more than 10 bugs to Apple since the first release of macOS 11. Seven of these issues are currently open. This SSMFS release contains workarounds for two of them. All open issues are related to loading system extensions, that Apple needs to address._

**Comment by bfleischer** [comment]
@Tagnal-git Please send me emails regarding SSMFS support. You can find my email address on my GitHub profile.
