### ISSUE TITLE
sshfs installation problem macFUSE

### ISSUE THREAD

**Issue by MIraola** [osxfuse/osxfuse#781]
Hi,

I am working with a M1 Macbook with Big Sur. After installing FUSE 3.11 and later updating it to macFUSE 4.0.5, I try to install sshfs running the following command: 

_brew install sshfs_

which gives me this error:

sshfs: FUSE for macOS is required for this software. OsxfuseRequirement unsatisfied!

Can you help me to find a solution, please? Thanks.

**Comment by bfleischer** [comment]
If you want to use brew to install sshfs, please raise this issue with the Homebrew team.

Alternatively you can download an older version of sshfs from https://osxfuse.github.io.

**Comment by MIraola** [comment]
Good. I have installed it from the repository you have written. Thank you.

**Comment by gromgit** [comment]
Homebrew has disabled all FUSE formulae on macOS for reasons, but I've revived most of them in [my own tap](https://github.com/gromgit/homebrew-fuse). Try:
```
brew install gromgit/fuse/sshfs-mac
```
