### ISSUE TITLE
macOS Mojave is reporting kext error when QUITTING Osiris

### ISSUE THREAD

**Issue by roblarose** [osxfuse/osxfuse#782]
I'm working this issue with Projective.io support, but effectively what we're seeing is on Mojave systems enrolled in Jamf MDM, with the team ID 3T5GSNBU6W approved, we can launch Osiris & mount filesystem, and the kext loads as expected.

On QUIT of the application, it's throwing an error "There was a problem with OSReturn. Unknown kext error: -603946981"

On a system that is not enrolled in MDM, the app quits normally with no error.

Any chance this is something known with osxfuse, as opposed to strictly an implementation problem w/ Osiris?

Thanks in advance for any insight.

**Comment by bfleischer** [comment]
I don't have any hand-on experience with MDM enrolled systems and I cannot test this setup. But I am not aware of any issues. 

Raising the issue with Projective.io is the right thing to do. If the error is displayed by Osiris, they should be able to find out what triggers it.

**Comment by misku** [comment]
The problem has already been fixed ~2 weeks ago. Thank you @bfleischer for answering.
