### ISSUE TITLE
Mount point is not "persistent" / Unable to keep "favorite" in Finder's sidebar

### ISSUE THREAD

**Issue by tobihagemann** [osxfuse/osxfuse#785]
### Description

When adding a mount point to Finder's sidebar (under "Favorites"), the location becomes unavailable after re-mounting it to the same mount point. This only happens if the mount point is inside `/Volumes`.

<img width="372" alt="finder-warning" src="https://user-images.githubusercontent.com/2924160/107960260-b2cc8680-6fa4-11eb-9971-9bec2f8f451b.png">

### System Setup

* Operating system and version: macOS Big Sur 11.2.1 (but seems to be reproducible in macOS Catalina as well)
* macFUSE version: 4.0.5

### Steps to Reproduce

1. Mount something via FUSE to `/Volumes/...`.
2. Add mount point to Finder's sidebar (under "Favorites") via drag & drop.
3. Unmount.
4. Mount again to the same location at `/Volumes/...`.
5. Try to access mount point via Finder's sidebar.

#### Expected Behavior

Mount point should be accessible via Finder's sidebar.

#### Actual Behavior

Mount point is not accessible via Finder's sidebar and Finder shows a warning (see screenshot at the top) when clicking on it.

#### Reproducibility

Always

### Additional Information

- I'm not sure how things are tested here but it's quite easy to reproduce this issue with [bindfs](https://bindfs.org/) (installed via Homebrew).
- As I've mentioned in the description, this only happens in `/Volumes` (or maybe also other directories, who knows). I wasn't able to reproduce this issue when the mount point was inside the home directory.
- I believe that this is a regression. I was unable to reproduce the issue with FUSE for macOS 3.11.2.

**Comment by jogan-r** [comment]
Did you ever find a solution or workaround for this? I'm having the same problem.

**Comment by tobihagemann** [comment]
- Workaround 1: Don't mount at `/Volumes`.
- Workaround 2: Create a symlink to `/Volumes/...` and add the symlink to the sidebar. Downside: You can't eject the drive from the sidebar.

**Comment by Quorum75** [comment]
People who are not familiar with Terminal, I will recommend to use:

https://github.com/nickzman/symboliclinker/releases
