### ISSUE TITLE
Need ssh KeyAlgorithms support

### ISSUE THREAD

**Issue by bfree-github** [osxfuse/osxfuse#786]
In order to connect to servers via KeyAlgorithms, we need to be able to pass through the following ssh arguments:

-o KexAlgorithms
-o HostKeyAlgorithms

Is there a way for sshfs to pass arguments to ssh, or otherwise support KeyAlgorithms?

**Comment by bfleischer** [comment]
This is the wrong place for SSHFS feature requests. Please raise the issue with the sshfs maintainers at https://github.com/libfuse/sshfs.
