### ISSUE TITLE
Allow button doesn't show up

### ISSUE THREAD

**Issue by RelaticsSys** [osxfuse/osxfuse#787]
I'm trying to use Veracrypt. After installing both Veracrypt and osxfuse, I get notified to allow/approve the system extension by Benjamin Fleischer. When going to the Security & Privacy screen, I do not see a allow button. Tried reinstalling.

I've been looking up older topics and trying fixes, but can't seem to find anything. (Like closing Chrome, VLC, wireless mouse etc)

**Comment by PrzemekCh** [comment]
same for me

**Comment by RelaticsSys** [comment]
> same for me

I found out. I needed to turn on Reduced Security in Startup tools (M1 Macbook)
