### ISSUE TITLE
[Big Sur] Seeing two icons in System Settings

### ISSUE THREAD

**Issue by dwt** [osxfuse/osxfuse#788]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/57199/110600916-bd81d200-8184-11eb-9e27-2c4851072ca7.png">

Both seem to be version 4.0.5 - should one of them be removed?

**Comment by bfleischer** [comment]
If you still see two FUSE icons after restarting System Preferences, please remove the "FUSE" preference pane by right-clicking on in and selecting "Remove ..." from the context menu. "macFUSE" is the new preferences pane from version 4.

**Comment by dwt** [comment]
thx
