### ISSUE TITLE
Mounted Disk Naming

### ISSUE THREAD

**Issue by andyanderson** [osxfuse/osxfuse#789]
I’m using macFUSE and mounting a remote file system via sshfs onto a directory on my desktop, e.g.

**$** _/usr/local/bin/sshfs aanderson@cluster: ~/Desktop/cluster_

Once it’s mounted I can reference the contents of this folder in the CLUI with _~/Desktop/cluster_. In the GUI, sshfs helpfully replaces the folder icon with a disk icon.

However, in the GUI it also changes the folder name to **macFUSE Volume 0 (sshfs)**, so when I look at it there I can’t immediately tell the purpose of this disk (unless I open it and recognize its contents).

This becomes more of a problem if I have several remote file systems mounted this way: **macFUSE Volume 1 (sshfs)**, etc.

Is there anyway that macFUSE could instead preserve the folder name? I suppose it could be appended with a macFUSE reference, but that really doesn’t seem necessary, and I don’t think it should be different than the name in the CLUI.

Thanks,

— Andy

**Comment by bfleischer** [comment]
Please see https://github.com/osxfuse/osxfuse/wiki/Mount-options. The volname option is what you are looking for.

**Comment by andyanderson** [comment]
Thanks! That works perfectly.

I had looked at the man page, but didn’t notice these extra options on the wiki.

— Andy
