### ISSUE TITLE
Unable to mount into macOS Catalina through SyncMate

### ISSUE THREAD

**Issue by krappdirk** [osxfuse/osxfuse#790]
I have the licensed version of SyncMate and use Macos Catalina. To mount my Android device, I have installed as needed https://osxfuse.github.io and "allowed" loading the OS extension in the Mac Preferences / Security & Privacy / General.

Nevertheless, the mount fails with the following error message: 
"""
Error
Mount unavailable. You need to install Fuse for OS X to activate this feature.
"""

Also a reboot did not help. I have over-installed Fuse a second time, also without luck.

SyncMate Expert -- Version 8.1.475
macFUSE  -- Installed Version: 4.1.0 -- No updates available at this time

**Comment by bfleischer** [comment]
Please raise this issue with the SyncMate team. SyncMate is not supporting the continued development of macFUSE. This means not even one cent of what you paid them reached this project. I hope you can understand, that I cannot provide support for their product.

**Comment by krappdirk** [comment]
Hi Benjamin,

Thanks for your instant feedback, as well as the hint that there is nothing more you can help with from your end.

I have reached out to [SyncMate team](https://www.sync-mac.com/de/contacts.html) already before I brought this to attention here. If it's okay 4U, I will let them know what you have just told me, once they come back to me with a ticket ID.

Again thanks & have a great Sunday !

// Dirk

**Comment by krappdirk** [comment]
Last update, just for the sake of completeness:

SyncMate team told me to go with FUSE v3.11.2, and I can confirm that it works with SyncMate Expert v8.1.475. ✅

Of course I told them that 

- it is already seven versions behind, with only 2 older versions offered in the release list, and they may have to consider vanishing that versions one day
- they should consider improving SyncMate and its installer to point to the (mac)FUSE version with which SyncMate is actually interoparable

😄
