### ISSUE TITLE
Rclone mount not working with FUSE on M1 Macs.

### ISSUE THREAD

**Issue by AyaanZaveri** [osxfuse/osxfuse#795]
Everytime I use the `rclone mount...` command, **FUSE** says:

<img width="286" alt="Screen Shot 2021-03-31 at 2 37 50 PM" src="https://user-images.githubusercontent.com/63752541/113194041-adfb2380-922e-11eb-85c7-b03d440fe902.png">

I tried going to security and privacy, enabled my system extensions and restarted my computer 3 times. Am I doing something wrong? I'm currently running [4.1.0](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.1.0) which is the latest version.

**Comment by bfleischer** [comment]
If possible, please upgrade to macOS 11.3 beta 4 or later. Apple addressed this bug in macOS 11.3 beta 4.

**Comment by AyaanZaveri** [comment]
Thanks!

**Comment by AyaanZaveri** [comment]
@bfleischer Is there any way to do this without installing a beta version?

**Comment by bfleischer** [comment]
You can retry the process multiple times, uninstall macFUSE, restart, reinstall it. Triggering the panic medic in the recovery recovery mode helps sometimes. After enough retries it will work, but the easiest way to solve this is upgrading to macOS 11.3.

**Comment by AyaanZaveri** [comment]
Thanks, but 11.3 isn’t out yet, right?
