### ISSUE TITLE
sshfs has been disabled because it requires fuse

### ISSUE THREAD

**Issue by darkclyan** [osxfuse/osxfuse#801]
Hello, someone could help me ?

I'm using telepresence to connect to a remote proxy. But, yesterday when I started telepresence appears the messages bellow:
`sshfs has been disabled because it requires fuse`

I tried all the steps in another issues, here in github.

1. Reinstall Big Sur and enables SIP -> No effect.
2. Reinstall Big Sur and enables SIP and reinstall osxfuse -> Got the same error and now I can't install sshfs because now the error is showing when I did:
`brew install sshfs`
3. Did the same steps bellow but now reinstalling osxfuse and sshfs with de .dmg in Download section -> no effect, the error persist.
4. Tried a hard reset in my Big Sur, and remake all the other steps -> The error persist and I can't install sshfs or telepresence, still sending the same error:
`sshfs has been disabled because it requires fuse`

@bfleischer - pls help me, ty.

**Comment by bfleischer** [comment]
Please raise this issue with the telepresence team. The error message "sshfs has been disabled because it requires fuse" seems to originate from Homebrew. There is nothing I can do about that. 

You can download (a slightly outdated version of) sshfs from https://osxfuse.github.io. This sshfs build works fine Big Sur. But judging from your description, telepresence tries to install its own version of sshfs using Homebrew. THat's why you need to raise the issue with the telepresence team.

**Comment by gromgit** [comment]
@darkclyan Homebrew has disabled all FUSE formulae on macOS for reasons, but I've revived most of them in [my own tap](https://github.com/gromgit/homebrew-fuse). Try:
```
brew install gromgit/fuse/sshfs-mac
```
then try telepresence again to see if it works now.

**Comment by youzeliang** [comment]
I also got  it , and  I found the source code

#on_macos do
#disable! date: "2021-04-08", because: "requires FUSE"
#end

a simple way to fix it   is  that  edit the formula file and remove the fuse restriction temporarily,

**Comment by Phenek** [comment]
This issue should be open.

````
Error: sshfs has been disabled because it requires closed-source macFUSE!
````
What should we do to install it from brew?

Workaround: I had to install sshfs from Release Page => [https://github.com/osxfuse/sshfs/releases](https://github.com/osxfuse/sshfs/releases)

**Comment by bfleischer** [comment]
@Phenek As I explained before, the error message "sshfs has been disabled because it requires closed-source macFUSE" originates from Homebrew. The Homebrew team decided to stop shipping sshfs. Please raise this issue with them. There is nothing I can do about it. That's why I closed the issue.

**Comment by zenghua-git** [comment]
> @darkclyan Homebrew has disabled all FUSE formulae on macOS for reasons, but I've revived most of them in [my own tap](https://github.com/gromgit/homebrew-fuse). Try:
> 
> ```
> brew install gromgit/fuse/sshfs-mac
> ```
> 
> then try telepresence again to see if it works now.

This one works perfectly for me (Mac OS 12 with M1). Thank you! All other solutions, like installing MacFUSE or sshfs from source code didn't work for me.

**Comment by rgaufman** [comment]
I'm not able to get this to work, I ran this:

```
bindfs /Volumes/Drive1_2TB/iCloud ~/Library/Mobile\ Documents/com~apple~CloudDocs
bindfs /Volumes/Drive1_2TB/Messages ~/Library/Messages
```

It seems to be mounted, but then the Messages app doesn't work and iCloud will not sync. Any ideas?
