### ISSUE TITLE
Unable to install nfts-3g after install macFuse on Catalina 10.15.7

### ISSUE THREAD

**Issue by henrychea** [osxfuse/osxfuse#802]
I have tried installing the older version 3.1.x as well but it displays the same error.
<img width="697" alt="Screen Shot 2021-04-20 at 4 56 17 PM" src="https://user-images.githubusercontent.com/40254517/115377227-9d204b00-a1f9-11eb-929a-946e49f2bd1e.png">

**Comment by bfleischer** [comment]
Please raise this issue with the Homebrew team. There is nothing I can do from my end.
