### ISSUE TITLE
When did moveItemAtPath become deprecated?

### ISSUE THREAD

**Issue by mixtly87** [osxfuse/osxfuse#803]
I noticed a line in my app's log:

```
*** WARNING: GMUserFileSystem delegate implements deprecated selector: moveItemAtPath:toPath:error:
```

When did `moveItemAtPath` became deprecated and what is the alternative?

**Comment by bfleischer** [comment]
Please check the releases notes for version 4.0.0 and the framework headers. The new callback is:

```
- (BOOL)moveItemAtPath:(NSString *)source toPath:(NSString *)destination options:(GMUserFileSystemMoveOption)options error:(NSError **)error;
```

The new moveItemAtPath:... callback adds support for renamex_np(2) calls.
