### ISSUE TITLE
Do you guys have a database of icons for the mount?

### ISSUE THREAD

**Issue by AyaanZaveri** [osxfuse/osxfuse#806]
Is there a way I could change the default icon for the mount?
<img width="94" alt="Screen Shot 2021-04-28 at 3 51 05 PM" src="https://user-images.githubusercontent.com/63752541/116464093-8b622780-a839-11eb-9945-583c744c3d59.png">
 If so, do you guys have a database of icons?

**Comment by Artoria2e5** [comment]
The current icon should be somewhere like `/Library/Filesystems/fusefs.fs/Contents/Volume.icns`. Replacing that would replace the default icon for all FUSE mounts. I am not aware of a mechanism to have per-filesystem "personality" icons, but macFUSE allows you to inject a [volicon](https://github.com/osxfuse/osxfuse/wiki/Mount-options#volicon) option.

The `.VolumeIcon.icns` file, when put in the root directory of a Volume, should change its icon on a per-volume basis.

**Comment by bfleischer** [comment]
The volicon option is the way to go.
