### ISSUE TITLE
Fuse 3.5 does not run on Mac OS 11.3 and v4.1.0 does not install

### ISSUE THREAD

**Issue by Isaac2k1** [osxfuse/osxfuse#807]
The installer runs, but Fuse is not installed and not visible in the preferences as it was before. As a result VeraCrypt does not run too.

**Comment by bfleischer** [comment]
Version 3.5 is years old and very much outdated. It does not support Big Sur.

Version 4.1.0 works fine on macOS 11.3. This is probably an issue on your end. Did you try restarting your Mac after completing the installation?

**Comment by Isaac2k1** [comment]
Dear Benni, 
Many thanks for your reply and for your work on osxfuse. 
I‘ve assumed that V3.5 is way to old for Big Sur and have tried first the update button in the Fuse Control Panel, which did not work at all. Then I‘ve downloaded the most recent V4.1.0 which did not install at all and then I made the entry on GitHub. Finally I found someone in a forum to recommend V4.0.2 and I gave it a try and it worked and it also was able to update to V4.1.0 from within the control panel, thus finally is everything okay. 
In the end I had to select also the TrueCrypt checkbox in VeryCrypt to enable mounting of my container with my old PW. 
This is all my personal incentives to go away from OS‘s like Windows or also MacOS and try more and more Linux, in order to be free from mainstream and paid solutions. Sometime I try also to compile sources and test if I would be able to reproduce the software on my own machines. So please bear with me, if my try to use the proper GitHub channel to ask for a bug fix was finally unnecessary and a bit to fast.
—

Viele Grüße
Best regards

Marco Mailand

**Comment by felix-ht** [comment]
~~I have the same issue with 4.1. The installer start and finishes but the app does not get installed.~~
Was user error - everything worked fine.
