### ISSUE TITLE
File/dir names longer than 255 bytes

### ISSUE THREAD

**Issue by woncheol-kim** [osxfuse/osxfuse#808]
Hi, I've recently started to use rclone on my Mac and found that I can not access some of directories from network drives mounted with it. 

According to Nick Craig-Wood at the link below, unlike fuse for linux, macfuse seems to limit file/dir names to maximum 255 bytes:

https://forum.rclone.org/t/rclone-mount-and-utf-8-problem-on-macos/23929/8

Some of my files/dirs (actually many) are much longer than 255 bytes, so I wish the limit to be extended to 511 bytes.

Thank you.

**Comment by bfleischer** [comment]
Extending the file name limit beyond 255 bytes won't be possible. Certain macOS kernel data structures only provide room for  up to 255 bytes. The Unicode normalization form plays an important role here for non-latin characters. All Apple file systems are limited to 255 byte file names (in NFC form).

**Comment by bfleischer** [comment]
See https://github.com/macfuse/macfuse/wiki/Unicode-Normalization-Forms for details.
