### ISSUE TITLE
After installing macfuse, bindfs command is not available.

### ISSUE THREAD

**Issue by queglay** [osxfuse/osxfuse#810]
I had a a go at using this today, but bindfs was not available from the terminal after installation in macOS 11.3.1.
Is bindfs supposed to be added to the PATH variable by the installer?  If it is missing how should I fix it?

Thanks for any help.

**Comment by bfleischer** [comment]
bindfs is a completely different project and not a part of the macFUSE package. Please raise bindfs related issues with the bindfs team.
