### ISSUE TITLE
How to unmount sshfs mounted on FUSE filesystem

### ISSUE THREAD

**Issue by artgoldberg** [osxfuse/osxfuse#813]
Hello osxfuse

Following the directions in [SSHFS](https://github.com/osxfuse/osxfuse/wiki/SSHFS), I've mounted a remote directory on a local directory.

The line in the mount table is

    uid@xxx:/var/opt/leafapi/ on /Users/arthur_at_sinai/gitOnMyLaptopLocal/sc_repos/leafapi_on_vm (macfuse, nodev, nosuid, synchronous, mounted by arthur_at_sinai)

The connection has gone stale and I'd like to remount it. Reissuing this command

    sshfs uid@xxx:/var/opt/leafapi/ ~/gitOnMyLaptopLocal/sc_repos/leafapi_on_vm

generates

    mount_macfuse: mount point /Users/arthur_at_sinai/gitOnMyLaptopLocal/sc_repos/leafapi_on_vm is itself on a macFUSE volume

But various attempts to use `umount` fail. E.g.,

    umount /Users/arthur_at_sinai/gitOnMyLaptopLocal/sc_repos/leafapi_on_vm

generates

    umount(/Users/arthur_at_sinai/gitOnMyLaptopLocal/sc_repos/leafapi_on_vm): Resource busy -- try 'diskutil unmount'

And `diskutil unmount` says:

    Unmount failed for uid@xxx:/var/opt/leafapi/

And `sudo umount -f /Users/arthur_at_sinai/gitOnMyLaptopLocal/sc_repos/leafapi_on_vm` makes my system unstable. Various programs hang.

The only solution I know of logout and login.

Running macOS Big Sur.

Assistance would be greatly appreciated.

Arthur

**Comment by tormodwill** [comment]
Hi.
I use 
$ sudo umount /Volumes/xxxxxx
This works ok, but I use sshfs 2.10,  I could only mount as /Volumes from sshfs version 2.9, i belive.
This did not work for me at sshfs version 2.5.

**Comment by tormodwill** [comment]
It is also possible to right click on the "network volume icon" on the desktop. Then you get a menu with unmount...

**Comment by prullens** [comment]
Right mouse click on mounted folder and click "Eject "folder_name""

**Comment by jainraje** [comment]
Hi,
I'm running big sur and have exact same issue. 
cmd_prompt>sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point

The remote system has rebooted so the local mount point is lost. I'm not finding a way to add it back or unmount without a *painful* reboot. 

cmd_prompt>sshfs Smith@ipaddr:/home/Smith ~/mounts/XYZ
mount_macfuse: mount point /Users/Smith/mounts/XYZ is itself on a macFUSE volume

Th emount point is not visible so Finder App does not appear to be helpful here (to manually unmount). Any suggestions to bypass the reboot will be greatly appreciated. 

TIA

**Comment by tormodwill** [comment]
Hi

You can try the following command :

sudo umount /Users/Smith/mounts/XYZ


Best regards

Tormod Willassen


> 15. nov. 2022 kl. 04:42 skrev Rajeev Jain ***@***.***>:
> 
> /Users/Smith/mounts/XYZ

**Comment by jainraje** [comment]
Hi Tormod,
Your suggestion worked. I am now able to remount (ie sshfs) it back to my local system. Very, very good. Thank-you!
--Rajeev

**Comment by bfleischer** [comment]
macFUSE 4.6.2 addresses file system hangs and lingering mounts, so I'm closing this ticket. Feel free to open a new ticket, in case this is still an issue.
