### ISSUE TITLE
Error: ntfs-3g has been disabled because it requires FUSE!

### ISSUE THREAD

**Issue by jackeyxiang** [osxfuse/osxfuse#818]
#: brew install ntfs-3g
Error: ntfs-3g has been disabled because it requires FUSE!

**Comment by bfleischer** [comment]
Please raise this issue with the Homebrew team. There is nothing I can do from this end. 

You can download macFUSE from https://osxfuse.github.io.

**Comment by jackeyxiang** [comment]
thank you very much，I already raise this issue with the Homebrew team；




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "osxfuse/osxfuse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [osxfuse/osxfuse] Error: ntfs-3g has been disabled because it requires FUSE! (#818)





 
Please raise this issue with the Homebrew team. There is nothing I can do from this end.
 
You can download macFUSE from https://osxfuse.github.io.

**Comment by TwanLuttik** [comment]
i have experienced the same issue

**Comment by jaspervanbrian** [comment]
Hello, experiencing the same issue as well. Any workaround for this?

**Comment by sashabeep** [comment]
The same issue here, @jackeyxiang can you provide the link to brew issue?

**Comment by ghost** [comment]
https://github.com/Homebrew/homebrew-core/issues/77932

**Comment by bakwc** [comment]
Is there some alternative way to install ntfs3g? Currently all tutorials refers to: `brew install ntfs-3g` and it's not working :(

**Comment by sashabeep** [comment]
> Is there some alternative way to install ntfs3g? Currently all tutorials refers to: `brew install ntfs-3g` and it's not working :(

Looks like ntfs and mtp could not been installed because of some "political" reasons in brew. So i dunno what is the purpose of this project

**Comment by ghost** [comment]
If you check the linked homebrew-core issue someone [offers a workaround](https://github.com/Homebrew/homebrew-core/issues/77932#issuecomment-847105678).

**Comment by alydevs** [comment]
@bfleischer Could I suggest creating a homebrew tap repository containing at least a formula for ntfs-3g, and then updating the wiki documentation to indicate that said tap should be added first? Or just updating the documentation so it works in the meantime using this tap that has ntfs-3g as `ntfs-3g-mac` https://github.com/gromgit/homebrew-fuse

Something like this in the wiki:

> Install NTFS-3G from Homebrew by opening a Terminal and entering the following commands:
> `brew tap gromgit/homebrew-fuse`
> `brew install ntfs-3g-mac`

with the tap repo being replaced by e.g osxfuse/homebrew-tap if you don't want to rely on the third party workaround.

**Comment by bfleischer** [comment]
@alyssadev I'm fine with third-party workarounds. I don't have the time to maintain a tap. The Wiki page is editable. Feel free to add the required information.

**Comment by vesper8** [comment]
> @bfleischer Could I suggest creating a homebrew tap repository containing at least a formula for ntfs-3g, and then updating the wiki documentation to indicate that said tap should be added first? Or just updating the documentation so it works in the meantime using this tap that has ntfs-3g as `ntfs-3g-mac` https://github.com/gromgit/homebrew-fuse
> 
> Something like this in the wiki:
> 
> > Install NTFS-3G from Homebrew by opening a Terminal and entering the following commands:
> > `brew tap gromgit/homebrew-fuse`
> > `brew install ntfs-3g-mac`
> 
> with the tap repo being replaced by e.g osxfuse/homebrew-tap if you don't want to rely on the third party workaround.

This worked for me, but first I had to run `brew install --cask macfuse`

So all in all

```
brew tap gromgit/homebrew-fuse
brew install --cask macfuse
brew install ntfs-3g-mac
```
