### ISSUE TITLE
kernel extension problem: missing __TEXT segment

### ISSUE THREAD

**Issue by ghost** [osxfuse/osxfuse#820]
Hi,
The macfuse 4.1.2  fails to load the kernel extension. The common internet wisdom that in "Security & Privacy" there should be an option to authorize the extension, but it does not appear. Another common wisdom is that one should try to install this with "reduced security", but my Mac has no T2 chip, and as a Intel machine there are no options like that.

> sudo kmutil load --bundle-path /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext
Password:
Error Domain=KMErrorDomain Code=31 "Error occurred while building a collection: in '/Library/Extensions/spl.kext/Contents/PlugIns/KernelExports.kext/KernelExports' missing __TEXT segment" UserInfo={NSLocalizedDescription=Error occurred while building a collection: in '/Library/Extensions/spl.kext/Contents/PlugIns/KernelExports.kext/KernelExports' missing __TEXT segment}

I believe this is an unreported bug. Is there a way to proceed?

**Comment by bfleischer** [comment]
Let me start by saying that this is not a bug in macFUSE. 

According to the error message above `/Library/Extensions/spl.kext` is responsible for the error. spl.kext belongs to OpenZFS, but the version of spl.kext installed on your Mac is not compatible with the running version of macOS. The incompatible version of spl.kext will prevent other third-party kernel extensions like macFUSE from loading on your Mac. The easiest fix would be uninstalling OpenZFS or upgrading it to a compatible version.
