### ISSUE TITLE
sshfs is not available on macOS12

### ISSUE THREAD

**Issue by hijiri-yoshida** [osxfuse/osxfuse#822]
sshfs is not available on 12.0 Beta (21A5248p).
<img width="372" alt="スクリーンショット 2021-06-10 17 37 41" src="https://user-images.githubusercontent.com/11865376/121494114-6acde580-ca13-11eb-8c54-758ae74b9e3a.png">

**Comment by bfleischer** [comment]
Duplicate of #821. Closed.
