### ISSUE TITLE
How do I install oxfuse

### ISSUE THREAD

**Issue by Wolf49803** [osxfuse/osxfuse#823]
Downloading the zip file and opening it with the desktop app does nothing. Please make installation instructions clearer.

**Comment by yadomi** [comment]
There is literally Installation instruction on the wiki, it can't be more clear https://github.com/osxfuse/osxfuse/wiki/SSHFS#installation

**Comment by bfleischer** [comment]
@Wolf49803 

Download the macFUSE installer from https://osxfuse.github.io and run it. This installs macFUSE.

Then you will probably want to install a third party macFUSE-based file systems. Please see the installation instructions for the particular third-party file system or ask the team maintaining the file system for support. They should be able to help you.
