### ISSUE TITLE
Trouble with installing gcsfuse

### ISSUE THREAD

**Issue by ovcluster** [osxfuse/osxfuse#825]
I am facing the following error "gcsfuse has been disabled because it requires FUSE!", while trying to install gcsfuse. Kindly advise what would be the ideal solution for the problem.

**Comment by bfleischer** [comment]
macFUSE, gcsfuse and Homebrew are three separate projects. You are running into an issue installing gcsfuse using Homebrew. Please raise the issue with the Homebrew team or gcsfuse team.

You can download the macFUSE installer package from https://osxfuse.github.io.
