### ISSUE TITLE
 cant write NTFS for macOS 12.

### ISSUE THREAD

**Issue by hwx-code** [osxfuse/osxfuse#827]
in Macfuse 4.2.0  Add experimental support for macOS 12. But I found that I can't read and write NTFS file after installation

**Comment by bfleischer** [comment]
macFUSE 4.2.0 does not support writing NTFS volumes on its own. It is a framework for building actual file systems. NTFS-3G is such a file system and probably what you are looking for. NTFS-3G is based on macFUSE and allows you to write NTFS volumes. So, you need both macFUSE and NTFS-3G.

Installing NTFS-3G can be tricky on newer versions of macOS, but this is beyond the scope of the macFUSE project. You should however be able to find some howtos online.
