### ISSUE TITLE
MacFUSE won’t load in 10.14.6

### ISSUE THREAD

**Issue by FGasper** [osxfuse/osxfuse#829]
![image](https://user-images.githubusercontent.com/844867/126801899-865d9d53-9706-4041-a513-f15501ee3c33.png)
^^ I see the following with both 4.1.2 and 4.2.0.

All I see in the referent part of System Preferences is:
![image](https://user-images.githubusercontent.com/844867/126802003-f8bd7b7d-15b2-4930-a237-1d2b4f39601a.png)

There’s nowhere (that I can see … ?) to add “Benjamin Fleischer”.

**Comment by NYC-Jim** [comment]
I have the same iussue after updating to Big Sur 11.5.  I also noted that in the Security & Privacy settings, under the Privacy tab, and the Files and Folders settings, the VeraCrypt.app is grayed-out, and no way to enable it (even with the settings are unlocked) - Blocked from working... thanks Apple!
<img width="626" alt="Screen Shot 2021-07-24 at 11 19 33 AM" src="https://user-images.githubusercontent.com/37019835/126872983-407910da-a6f2-4357-a92a-2af9f3c8813f.png">

**Comment by FGasper** [comment]
Looks like this was a result of restrictions imposed from outside my system. (This is a work laptop.) Once Benjamin’s team ID was added to the allow-list I was able to use the extension again.

Closing. Thank you for maintaining macFUSE!

**Comment by johndonor3** [comment]
@FGasper I'm having the same issue on a work laptop, I assume I'll need to bug IT (though in theory I'm supposed to have full admin privileges). Can you please share the details of what had to be changed?

I see a very similar screen to @NYC-Jim, with the +/- buttons greyed out and unclickable, even with the screen "unlocked". But even if I could add something I'm not sure it would I should add.

Thanks!

**Comment by EricNepean** [comment]
I'm trying to Install MacFuse 4.2.1 on a MacBook Air running MacOS 10.14.6, and getting the same error message as F Gasper. On the Security&Privacy Window>General window, I also do not see the option to enable Software Install by Benjamin Fleischer as per FGasper.

I tried restarting, the problem is unchanged.

I'm unable to install MacFuse, and therefore unable to run applications that depend on it.

(Strangely enough my iMac, also 10.14.6 has has MacFuse installed for years, has upgraded to Macfuse 4.21 with no issues)

Any hope of resolution?

**Comment by johndonor3** [comment]
I had to appeal to my IT department (that manage my mac) and they ended up having to create a policy for me. We got the info we needed from this post (it looks like they discuss "policies" a little bit but I'll be honest I don't know much about that): https://support.lucidlink.com/support/solutions/articles/31000144507-filespace-fails-to-mount-macos

Note: I was able to install MacFuse, I just couldn't run it. I think that was the same problem others in this thread were having. If you can't get it to install at all you might be having a slightly different problem? But still maybe worth adding a policy for Benjamin Fleischer's software.

**Comment by EricNepean** [comment]
After restarting the Mac, and a failed install with no button to "enable Software Install by Benjamin Fleischer", I let the machine skit for a while, and tried once again (to verify the previous fail). Instead it worked.
MacFuse 4.2.1 is installed and apparently runs (because Veracrypt now runs)

**Comment by RokerHRO** [comment]
I got the same problem and it is still not working, even after "waiting for a while".

**Comment by johndonor3** [comment]
I see the link above is broken and I have colleagues who need this issue resolved, so for posterity here is the key info from that linked post:

The osxfuse kext is signed by Benjamin Fleischer - Team ID: 3T5GSNBU6W.
