### ISSUE TITLE
Unsupported MacOS Version

### ISSUE THREAD

**Issue by Alanreid11** [osxfuse/osxfuse#830]
Running MacFUSE 4.2.0
Catalina 10.15.7 Mac Pro 2019
Using Editshare Connect for EFS 

Error showing The installed version of EFSFUSE is too old for the operating system. Please upgrade your EFSFUSE installation to one that is compatible with the currently running version of macOS.
![Screenshot 2021-07-30 at 08 30 09](https://user-images.githubusercontent.com/88183423/127618262-b3c34139-d78d-41fd-bcd0-696ec1ee8358.png)

What am I missing? Thank you.

**Comment by bfleischer** [comment]
Editshare is using a custom version of macFUSE. Please update your Editshare software to the latest version. If this does not fix the issue, please raise the issue with the Editshare support team.
