### ISSUE TITLE
Write method not called

### ISSUE THREAD

**Issue by nickcone** [osxfuse/osxfuse#831]
So I currently have my file system fully working on Windows, I can add/delete files/directories and everything works as it should. The write method that I am using is not actually writing to the file system, It takes the image buffer and writes it to a temporary file. Then the temporary file is posted to a website, after it is posted to the website, the image appears in my file system. When I run it on Mac and copy a file to the file system, the file does not appear on the file system because the write method is never called and I get the error: The operation can't be completed because one or more require items can't be found(Error code -43). If I try to bring in a folder with images in it I get the error: The Finder can't complete the operation because some data in "._DS_Store" can't be read or written. (Error code -36). When I use the terminal to copy or move files to the file system(cp/mv), I get input/output error response, but the write method is called and all of my files appear in the file system. However, when I drag and drop them into the file system using finder, the write method is not called. Has anyone ran into this before or does anyone have a solution to this issue?
The order of operations on windows is: Open, create, open, getattr, write, getattr, release.
The order of operations on mac is: Open, create, open, getattr, release.
I can provide more detail on this if needed.

**Comment by bfleischer** [comment]
Please post questions like these in our [Google Group](https://groups.google.com/forum/#!forum/osxfuse-group). This tracker is intended for tracking bugs.
