### ISSUE TITLE
v_name race in mkdir

### ISSUE THREAD

**Issue by kikht** [osxfuse/osxfuse#832]
I've found a race in kext. When we run two syscalls `mkdir(parent)` and `mkdir(parent/child)` concurrently, it is possible for `mkdir(parent/child)` to fail with `EINVAL`. This result is not documented for this syscall and confuses userspace tools, e.g. nodejs when it tries to create directories recursively like `mkdir -p` does. 

`EINVAL` appears to come from `build_path_with_parent` kernel function that gets called during some security check in `hook_vnode_check_create` in sandbox.kext. Error is caused by `vp->v_name` being null in freshly created vnode for parent dir [here](https://github.com/apple/darwin-xnu/blob/a1babec6b135d1f35b2590a1990af3c5c5393479/bsd/vfs/vfs_cache.c#L557-L561). `v_name` for this vnode will later be filled in [mkdirat1 syscall handler](https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/vfs/vfs_syscalls.c#L9125-L9135) for parent dir. However if `mkdir(parent/child)` runs its hook exactly in this window after `fuse_vnop_mkdir` but before `vnode_update_identity` it will fail with EINVAL. 

The problem can be reproduced on loopbackfs by the following program:
```
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>

void* child_thread(void* arg) {
    mkdir("test_dir/parent", 0777);
    return NULL;
}

int main() {
    for (int i = 0; i < 1000000; i++) {
        system("rm -rf test_dir");
        mkdir("test_dir", 0777);

        pthread_t child;
        pthread_create(&child, NULL, child_thread, NULL);

        while (1) {
            if (mkdir("test_dir/parent/child", 0777) != 0) {
                intptr_t err = errno;
                if (err == ENOENT) {
                    continue;
                }

                perror("child err: ");
                printf("%d iterations\n", i);
                return err;
            }
            break;
        };

        pthread_join(child, NULL);
    }

    return 0;
}
```

To fix this we should fill `v_name` before we return from `fuse_vnop_mkdir`. I can see two ways of doing this. We can either pass `cnp` from `fuse_vget_i` to `FSNodeGetOrCreateFileVNodeByID` and fill [`vnfs_cnp` field](https://github.com/osxfuse/kext/blob/534773bd3135f04b7f6fb801faa2f8991daf4a6b/osxfuse/fuse_node.c#L171) before `vnode_create`. This is the way nfs [does this](https://github.com/apple/darwin-xnu/blob/a1babec6b135d1f35b2590a1990af3c5c5393479/bsd/nfs/nfs_node.c#L526). Or we can run `vnode_update_identity` with `VNODE_UPDATE_NAME` flag somewhere later like `mkdirat1` syscall handler does. 

I've only encountered this bug with `mkdir` syscalls, but it seems that it also can occur with other operations that create vnodes. Filling `vnfs_cnp` in `FSNodeGetOrCreateFileVNodeByID` should fix them all at once.

**Comment by bfleischer** [comment]
Thank you very much for your work. This is a really great bug report.

Filling `vnfs_cnp` in `FSNodeGetOrCreateFileVNodeByID()` seems to be the best solution in my opinion. We need to make sure that the file name is not cached automatically. But since we are already setting `vnfs_flags` to `VNFS_NOCACHE` (apparently for no reason) we don't need to worry about that.

With this change in place, your test program has been running for hours without triggering `EINVAL`. Your fix will be in the upcoming 4.2.1 release.
