### ISSUE TITLE
Mounting a server with portforwarding works, but not socket forwarding

### ISSUE THREAD

**Issue by keithy** [osxfuse/osxfuse#833]
When a server has portforwarding configured in .ssh/config mounting the filesystem, also sets up the port forwarding, but it doesnt forward sockets. (sshfs)

**Comment by bfleischer** [comment]
I think this is something that might need to be addressed from the sshfs end. It might be worth raising this issue on the sshfs issue tracker (https://github.com/libfuse/sshfs). Socket forwarding is a ssh feature, so I don't think this is a macFUSE issue.
