### ISSUE TITLE
MacOS 11.5.2: On 4.20 Kext won't load, on 4.1.2 it does. 

### ISSUE THREAD

**Issue by ropg** [osxfuse/osxfuse#835]
Seems the opposite of #828: there the upgrade from MacOS 11.4 to MacOS 11.5 broke MacFuse 4.1.2 but 4.20 worked, now on upgrade to MacOS 11.5.2 MacFuse 4.2.0 breaks and 4.1.2 works again.

**Comment by bfleischer** [comment]
You need to do a reboot after installing the macOS update. 4.1.2 and 4.2.0 both work just fine.

**Comment by ropg** [comment]
Ah. That makes sense, I indeed did not try a(n additional) reboot, figured the MacOS upgrade process had done that. Sorry for spurious report.
