### ISSUE TITLE
macFUSE suggest update from 4.2.0 to 4.1.2

### ISSUE THREAD

**Issue by YorikSar** [osxfuse/osxfuse#837]
I've just installed 4.2.0 version and in System Preferences it suggests to update to 4.1.2:
<img width="780" alt="Screen Shot 2021-09-15 at 16 59 04" src="https://user-images.githubusercontent.com/428074/133437705-2cbf129d-78b0-4d60-b2e1-93e7d6e06ca9.png">

I guess smth broken in upgrade detection.

**Comment by j-martin** [comment]
My understanding is that it's because 4.2.0 is considered to be a beta version (rightfully or not) and you got that box unchecked.

Checking `Show Beta Versions` will show that there is no updates available.

**Comment by bfleischer** [comment]
Martin is right. 4.2.0 is a beta release. Since the beta checkbox is not checked, the updater suggests the latest stable version, which is 4.1.2 right now.

**Comment by YorikSar** [comment]
@bfleischer Maybe it should show updates only if there's a non-beta update with newer version in this case? Recommending downgrade from beta to stable doesn't seem intuitive.
Also - maybe beta releases should have "beta" checkbox set by default?
