### ISSUE TITLE
The downloads link takes you to the release page and not the download page!

### ISSUE THREAD

**Issue by davidnewcomb** [osxfuse/osxfuse#838]
On page: https://osxfuse.github.io/
Click "Downloads" from the nav bar.
I am taken to the release notes page. There are no links to download anything here.

The Downloads link should point to https://osxfuse.github.io/archive.html because this page contains links to actual downloads.

While there is a link to the stable release on the front page, I didn't see it . There was a download button which I clicked straight away ...because that's how sites work! Or not in this case.

**Comment by bfleischer** [comment]
> I am taken to the release notes page. There are no links to download anything here.

There are download links. You just need to click on the little arrow next to "Assets" under each release. This is the standard GitHub releases view.
