### ISSUE TITLE
MacFuse 4.2.1 works on Big Sur 11.6 perfectly! None work on Monterey beta5 or Later

### ISSUE THREAD

**Issue by castiellian** [osxfuse/osxfuse#840]
macfuse 4.2.1 works on Big Sur and Monterey!

**Comment by maraqa-chu92** [comment]
I get:
zsh: parse error near `end'

and
zsh: parse error near `then'

when I try to do steps 3 and 4
Please advise!

**Comment by castiellian** [comment]
macfuse 4.2.1 works on Big Sur and Monterey!
https://bbs.pcbeta.com/viewthread-1906630-1-1.html

**Comment by castiellian** [comment]
@maraqa-chu92 
Please run this command on step 3 and find the correct phase.You probably find wrong line code.

`vi brew formula ntfs-3g`
`search ：/on_mac do`
`find out this：`
`on_macos do`
`disable! date: "2021-04-08", because: "requires closed-source macFUSE"`
`end`
`disable limitation：`
`# on_macos do`
`# disable! date: "2021-04-08", because: "requires closed-source macFUSE"`
`# end`
