### ISSUE TITLE
Unsupported macOS Version

### ISSUE THREAD

**Issue by user5201973** [osxfuse/osxfuse#843]
Get the following error after upgrade to macOS 12.0.1 when launching Amazon Workdocs Drive

The installed version of macFUSE is too old for the operating system. Please upgrade your macFUSE installation to one that is compatible with the currently running version of macOS
![Screen Shot 2021-10-26 at 6 41 38 AM](https://user-images.githubusercontent.com/93193947/138862216-86d24da7-b231-4855-89f5-a1f98deeaa17.png)

**Comment by bfleischer** [comment]
Amazon uses a custom version of macFUSE. Please update Amazon Workdocs Drive to the latest version. If this does not resolve the issue, please report it to Amazon.
