### ISSUE TITLE
Issue with kernel extension on mac Monterey

### ISSUE THREAD

**Issue by alexios-y** [osxfuse/osxfuse#844]
It would block installing kernel extensions in this new mac os by default. Users need to reduce security level to install extensions. Just wondering if there is any plan to use alternative extensions rather than kernel extensions in the future? Also Apple seems to ditch support for legacy system extensions some time later too.

**Comment by bfleischer** [comment]
Unfortunately, Apple has not announced an alternative API for developing full-featured file systems. I would love migrating macFUSE to a new non-kernel API, but currently there is none. That's the reason Apple has not deprecated file system kernel extensions, yet. Feel free to raise this issue with Apple. 

> Also Apple seems to ditch support for legacy system extensions some time later too.

Apple will not drop support for file system kernel extensions before they announce a new non-kernel API and giving developers enough time to migrate.
