### ISSUE TITLE
12.0.1 montery

### ISSUE THREAD

**Issue by ruanhailiang** [osxfuse/osxfuse#846]
It is not work. on version 12.0.1 montery

**Comment by bfleischer** [comment]
macFUSE 4.2.0 and later support macOS Monterey. Could you please provide more information?

**Comment by delfer** [comment]
use macFUSE instead of osxfuse
```brew install --cask macfuse```

**Comment by bFanek** [comment]
Some tools do not work on macFUSE 4.x, but work under 3.x
3.11.2 used to work on Big Sur (macOS 11), but refuses to load or install on Monetary (macOS 12)

Is there a way to get 3.x working on Monetary?

Thanks

**Comment by bfleischer** [comment]
> Some tools do not work on macFUSE 4.x, but work under 3.x

Which tools are you referring to? All "native" file systems that were built with version 3 should work on version 4 as well.

 > Is there a way to get 3.x working on Monetary?

No, macFUSE 4 is the future.

**Comment by bFanek** [comment]
Plexdrive does not work with 4.x
More details: https://github.com/plexdrive/plexdrive/issues/390

**Comment by bfleischer** [comment]
I commented on the Plexdrive issue. Plexdrive uses a third-party FUSE library which was never updated to add support for the Linux-style mount process that was introduced in version 3.3.0 of FUSE for macOS, more than 5 years ago. The relevant code is open source. Updating the third-party library does not require any "reverse engineering" and should be easy.

**Comment by windtear** [comment]
> It is not work. on version 12.0.1 montery

+1
VeraCrypt info：
kext load failed: -603947007
mount_osxfuse: the file system is not available (255)

**Comment by windtear** [comment]
> > It is not work. on version 12.0.1 montery
> 
> +1 VeraCrypt info： kext load failed: -603947007 mount_osxfuse: the file system is not available (255)

Update:
after I reinstall macfuse 4.2.1
It works for me!

It seems that macfuse must be reinstalled for every boot.

**Comment by RayOei** [comment]
I have issues with Keybase (see similar reports here: https://github.com/keybase/client/issues/24668) not sure if it is a MacFuse or Keybase issue.
Reinstalling MacFuse, which normally worked after a MacOS upgrade, did not this time.

**Comment by bFanek** [comment]
> I commented on the Plexdrive issue. Plexdrive uses a third-party FUSE library which was never updated to add support for the Linux-style mount process that was introduced in version 3.3.0 of FUSE for macOS, more than 5 years ago. The relevant code is open source. Updating the third-party library does not require any "reverse engineering" and should be easy.

Thank you @bfleischer  I ended up switching to rclone instead of Plexdrive. rclone works fine under macFUSE 4.x and macOS Monetary, I’ll use that for now until plexdrive is updated. Cheers.

**Comment by veepers037** [comment]
I just upgraded to the Monterey system and my Vera Crypt no longer opens any files.  It keeps sending me in a loop of messages stating when I try to install OSXFUSE 2.5.0: "This release of OSXFUSE is not compatible with the version of OS X you are running" or stating "Vera Crypt requires OSXFUSE 2.5 or above."  The MacFuse currently installed (and just re-installed) is 4.2.1 which worked great until Monterey.  Is there a solution?  Cordially, veepers037

**Comment by veepers037** [comment]
Tried reinstalling VeraCrypt and it is now functioning normally.  Hope this helps others who found the same problem after upgrading to Monterey.

**Comment by mixman68** [comment]
I have issues with MacBook Air M1 and macFuse 4.2.3

My system has a load average around 400 with macFuse activated, when I click on Remove FUSE button, the system cool down instant.

I have FileVault on

**Comment by Sierkinhane** [comment]
> > > It is not work. on version 12.0.1 montery
> > 
> > 
> > +1 VeraCrypt info： kext load failed: -603947007 mount_osxfuse: the file system is not available (255)
> 
> Update: after I reinstall macfuse 4.2.1 It works for me!
> 
> It seems that macfuse must be reinstalled for every boot.

I have tried it, but it didn't work.
