### ISSUE TITLE
Sidebar Icon 

### ISSUE THREAD

**Issue by true-Grand** [osxfuse/osxfuse#849]
I Don't Know where to put this so hopefully someone sees this and fix it
<img width="135" alt="Screen Shot 2021-11-08 at 8 38 56 PM" src="https://user-images.githubusercontent.com/78011648/140743698-edad866c-eaae-4666-94d4-06a4df3133ed.png">
. A mounted drive using Fuse isn't displaying a proper sidebar icon. Hopefully someone can fix it..

**Comment by ericv-hs** [comment]
Hello. Same issue on MacOS 12.0.1 (with pCloud).
In fact, network drive icon comes and goes away, replaced by a file icon. I didn't figure yet when and why.

**Comment by paulfreeman** [comment]
Seeing the same issue (in my case with pCloud).  Creates a sense of mistrust in a filesystem out of proportion to the symptom. Is this a sign of a larger underlying issue?

**Comment by HealsCodes** [comment]
Same issue here - latest MacFuse 4.2.4 on an M1 MacBook Air with macOS 12.1

It somehow feels like an issue with how macFuse handles drive icons.
I'm also running Cloud Mounter (as is visible in the screenshot) and it has no such issue adding it's two cloud volumes with proper icons.

I also noted that MacFuse Volumes generally ignore the normal sort order set for finder and appear at the top of the list after reboots / remount.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/304352/151675818-715bc5f5-9d71-4658-ab50-ff5136afa39c.png">

**Comment by bfleischer** [comment]
This issue has been inactive for a long time, so I'm closing it. As far as I can tell, macOS 14 displays a generic image in the Finder's sidebar when dragging macFUSE volumes to the "Favorites" section.
