### ISSUE TITLE
macFUSE kernel extension stops working until reload

### ISSUE THREAD

**Issue by ericswpark** [osxfuse/osxfuse#850]
The macFUSE kernel extension sometimes ~~gets unloaded~~ stops working after running the system for some time. When this happens, applications that rely on macFUSE stop working. Cryptomator shows a generic FUSE error indicating that it is unable to use macFUSE, while VeraCrypt shows a `mount_macfuse: the macFUSE kernel extension is not loaded` error when attempting to mount a volume.

~~When this happens, the only solution is to either reboot the machine, OR uninstall and reinstall macFUSE from the System Preferences pane.~~ (Easier solution found, just unload the kext. [See comment below](https://github.com/osxfuse/osxfuse/issues/850#issuecomment-967795637).)  Then it starts to work again for some time until the kernel extension ~~gets unloaded~~ breaks again.

I'm not sure exactly when the kernel extension ~~gets unloaded~~ stops working. Maybe upon resuming from sleep but not too sure.

I'm running macFUSE 4.2.1 on macOS Monterey 12.0.1.

**Comment by ericswpark** [comment]
Just found out that the kernel extension _is_ loaded when the error occurs, as the output of `kextstat` shows:

```
  207    0 0xffffff7f997cb000 0x14000    0x14000    io.macfuse.filesystems.macfuse (2081.20) 7AF3B76F-9FED-3061-B34E-4765286F3749 <9 7 6 3 1>
```

**Unloading the kernel extension fixes the error.** You can unload the kext by running: `sudo kextunload -b io.macfuse.filesystems.macfuse`.

You do not need to re-load the kernel extension; it gets reloaded automatically when running any application that relies on macFUSE.

So it seems like the applications that depend on macFUSE are not happy because something is going wrong with the macFUSE kernel extension and therefore the applications think the kernel extension is not loaded at all. Unloading the kernel extension resets the bugged state and lets macFUSE work again.

**Comment by j-rahman** [comment]
> **Unloading the kernel extension fixes the error.** You can unload the kext by running: `sudo kextunload -b io.macfuse.filesystems.macfuse`.
> 
> You do not need to re-load the kernel extension; it gets reloaded automatically when running any application that relies on macFUSE.

This does not work in my case. I get the following error.
`Executing: /usr/bin/kmutil unload -b io.macfuse.filesystems.macfuse
Error Domain=KMErrorDomain Code=71 "Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)" UserInfo={NSLocalizedDescription=Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)}`

**Comment by bfleischer** [comment]
@j-rahman The kernel extension cannot be unloaded in case a macFUSE volume is still mounted.

**Comment by bfleischer** [comment]
@ericswpark The error message you are seeing is returned in case the macOS system function getvfsbyname() reports that the macFUSE VFS plugin ist not available. There is no code in the macFUSE kernel extension to unload the VFS plugin (without the kernel extension being unloaded). This means there is probably more to the story. Can you describe in as much detail as possible what you did leading up to seeing this error message?

**Comment by j-rahman** [comment]
@bfleischer There are currently no mounted volumes. I have encountered this problem a couple of times before on macOS 12.0.1. Reinstalling and restarting or simply restarting the system often solves the issue. However, it is very inconvenient to have to restart in the middle of work.

Right now, I tried to mount a remote directory and got a `mount_macfuse: the macFUSE kernel extension is not loaded` error. So, I came here and looked for similar issues and whether there were any solutions. I tried to unload the kernel extension as suggested here but it failed.

`kextstat` shows the following entry:
```
  203    0 0xffffff7f998b1000 0x14000    0x14000    io.macfuse.filesystems.macfuse (2081.20) 7AF3B76F-9FED-3061-B34E-4765286F3749 <9 7 6 3 1>
```

**Comment by bfleischer** [comment]
@j-rahman Just to be sure, can you run `mount` in Terminal?

**Comment by j-rahman** [comment]
@bfleischer Yes, I can.

I even tried running `sudo kextload /Library/Filesystems/macfuse.fs/Contents/Extensions/12/macfuse.kext`, but it won't help. I get the same error `mount_macfuse: the macFUSE kernel extension is not loaded` whenever I try to use `sshfs` again. Perhaps I will have to restart. ☹️

**Comment by ericswpark** [comment]
> @ericswpark The error message you are seeing is returned in case the macOS system function getvfsbyname() reports that the macFUSE VFS plugin ist not available. There is no code in the macFUSE kernel extension to unload the VFS plugin (without the kernel extension being unloaded). This means there is probably more to the story. Can you describe in as much detail as possible what you did leading up to seeing this error message?

@bfleischer It usually happens after some time has elapsed since the last mount that utilizes macFUSE.

For example, when I reboot my Mac and start using VeraCrypt and Cryptomator, everything will work for a while. I'll unmount everything, eject the external drive, and then put my Mac to sleep, although I'm not sure if this is the exact trigger for the problem. On wake, I re-connect the external drive, and try and re-mount the encrypted files using the encryption tools, and I usually encounter the error during this time.

Again, I'm not sure exactly when macFUSE will stop working. I've tried unmounting and remounting several times to get it to trigger on-demand but it doesn't happen at once. Usually it takes a bit of inactivity before the kernel extension acts up. Every time I've encountered this bug the unload command always worked and I could mount volumes properly after executing it.

**Comment by ericswpark** [comment]
@j-rahman I think your issue is slightly different from mine but possibly related. The kext unload command _always_ works for me whenever I encounter this error.

I'm running macOS build 21A559, in case we're running different macOS builds and that's causing the discrepency. But I think this might be a separate issue altogether. In any case there are definite incompatibilities with Monterey and macFUSE as I haven't encountered this bug on Big Sur.

**Comment by AlexC127** [comment]
I have uninstalled macFUSE 4.2.1 and installed the latest 4.2.3.  However, still encounter the same problem.
Using below command to force proper unload.   When macFUSE is called next time, it is loaded.

$sudo kextunload -b io.macfuse.filesystems.macfuse

This happen after the Monterey upgrade,

**Comment by DaveFlowberries** [comment]
I have the same issue when trying to mount an existing volume or create a new volume:

"mount_macfuse: the macFUSE kernel extension is not loaded"

Tried with Veracrypt 1.25.7 and 1.24 versions, same issue. 
System is:
M1 Max MacBook Pro
OSX 12.1 (21C52) 

Only workaround I found is to run this every time I need to mount or create a volume:

sudo kextunload -b io.macfuse.filesystems.macfuse

That will work for one session, after which I need to run the command again.

**Comment by DaveFlowberries** [comment]
Updating OSX to 12.2 (21D49) solved the issue for me.

EDIT: Never mind, still have the issue after a day of using it without issues....

**Comment by sycam0r-e** [comment]
Just to chime in, I just encountered the same issue as ericswpark when using VeraCrypt. Executing `sudo kextunload -b io.macfuse.filesystems.macfuse` as they suggested solved the problem (for now). Before the error occurred, I had my Macbook running for 14 days (with intervals in sleep mode). VeraCrypt was not running (I have no other application that uses macFUSE).

OS: macOS 12.1 (21C52)
Kernel version: Darwin 21.2.0
mac FUSE version: 4.2.4
VeraCrypt version: 1.25.9

**Comment by bnetz** [comment]
Same problem (and solution: executing `sudo kextunload -b io.macfuse.filesystems.macfuse` for me ). Error appears sporadically independent of how long OS has been running, but always directly after waking up the OS from sleep mode.

macOS 12.1 (21C52), Darwin Kernel Version 21.2.0
mac FUSE 4.2.4
VeraCrypt 1.25.9

**Comment by tcpekin** [comment]
I have the same problem as @bfleischer above - I cannot unload the kernel extension, it has the same exact error, nothing is mounted, and when running sshfs, I get the same `mount_macfuse: the macFUSE kernel extension is not loaded`.

macOS 12.3 (21E230)
mac FUSE 4.2.4

```
sshfs -V
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
```

**Comment by porg** [comment]
I browsed and searched through the issues here as I also have issues with long term stability of macFUSE when a sshfs filesystem is mounted.

Maybe the root cause for this is #45?
- So not necessarily the sleep/standby of your Mac, which happens after a certain longer time,
- But rather the termination of your ssh connection, which may also happen after a certain longer time.

**Comment by ericswpark** [comment]
@porg I don’t think that is related as I only use VeraCrypt and Cryptomator, both of which do not use sshfs. I can also confirm that none of the volumes/vaults reside on a remote connection, so it is unlikely to be the issue.

**Comment by porg** [comment]
Thanks for the additional information.

**Comment by pguzowski** [comment]
I am getting the same error as @j-rahman when trying to fix this
```
$> sshfs remote:/ /mountpoint
mount_macfuse: the macFUSE kernel extension is not loaded

$> sudo kextunload -b io.macfuse.filesystems.macfuse    
Executing: /usr/bin/kmutil unload -b io.macfuse.filesystems.macfuse
Error Domain=KMErrorDomain Code=71 "Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)" UserInfo={NSLocalizedDescription=Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)}

$> mount | grep macfuse

$> sshfs -V
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
```

Was any solution found? Or is rebooting the only way? This is the first time this error has happened to me, and I regularly sleep the macbook (M1, macOS 12.3.1 21E258) between work and home for more than a year, and mount macfuse volumes each time

**Comment by hbeale** [comment]
I too am getting the same error as @j-rahman 
```
09:07 $ sshfs remote:/ ~/servers/58
mount_macfuse: the macFUSE kernel extension is not loaded
09:08 $ sudo kextunload -b io.macfuse.filesystems.macfuse
Executing: /usr/bin/kmutil unload -b io.macfuse.filesystems.macfuse
Error Domain=KMErrorDomain Code=71 "Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)" UserInfo={NSLocalizedDescription=Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)}
09:08 $ mount | grep macfuse
09:08 $ sshfs -V
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
09:08 $ sw_vers -productVersion
12.2
09:10 $ 
```

**Comment by willapp** [comment]
Same issue here. I'm using:

macFUSE 4.4.2
Veracrypt 1.24-Update8
macOS Ventura 13.2.1
Apple MacBook Air M1

Like others, I can't precisely reproduce the error but the typical scenario is as follows:

1. Run Veracrypt and use it to mount a file from the local filesystem.
2. Unmount the volume and close Veracrypt.
3. Leave the mac running for some time, including putting it to sleep but not shutting it down.
4. Run Veracrypt again and try to mount the same file.
5. Mostly it will work fine, but occasionally I'll receive the "mount_macfuse: the macFUSE kernel extension is not loaded" error.

Until I found this post, the only way I'd been fixing this is by rebooting the mac, but I can confirm that running "sudo kextunload -b io.macfuse.filesystems.macfuse" fixes it without a reboot.

**Comment by bfleischer** [comment]
The latest macFUSE release (4.4.3) contains a workaround for having to manually unload/reload the macFUSE kernel extension. 

That being said, I have not been able to reproduce the issue on any of my test machines. There must be more to it than the Mac going to sleep. There is no code path in macFUSE that unloads the VFS plugin while keeping the kernel extension loaded. This means, this could be a relatively new, undocumented behavior of macOS (without an obvious explanation) or (more likely) a bug in macOS.

macFUSE 4.4.3 checks whether the VFS plugin is loaded or not when trying to mount a volume. If the VFS plugin is not available, but the kernel extension is loaded, the kernel extension is reloaded.

**Comment by bfleischer** [comment]
No feedback for version 4.4.3, closed.
