### ISSUE TITLE
Running latest prerelease

### ISSUE THREAD

**Issue by johnnyatlaval** [osxfuse/osxfuse#852]
<img width="318" alt="Skärmavbild 2021-11-13 kl  07 43 10" src="https://user-images.githubusercontent.com/11561240/141609098-cdbf10df-4c6e-4019-9888-3b07ced0ba3a.png">

Hdutils attached fail - filesystem cannot be mounted. I get this error updating to your lastest release with the newest install from Apple Monterey 12.0.1 but if I try another time it works as magic.

**Comment by bfleischer** [comment]
Please raise issues involving VeraCrypt with the VeraCrypt team. I have no way of debugging this and it might be a VeraCrypt issue after all.

**Comment by johnnyatlaval** [comment]
Ok, I will try to raise the issue there. It is difficult to know for me as a user but, thank you for your answer!
