### ISSUE TITLE
pkg installation failed issue

### ISSUE THREAD

**Issue by anonymousguy96** [osxfuse/osxfuse#854]
Hi, I'm trying to install an audio plugin with no success cause its pkg file presents an error of failed installation.

Do you know how to fix it?
I'ma drop os info and the installer log here

Have a good day :)

macOS Mojave 10.14.6

Installer log:

Nov 16 01:15:44 IPNs-MBP Installer[916]: @(#)PROGRAM:Install  PROJECT:Install-1000
Nov 16 01:15:44 IPNs-MBP Installer[916]: @(#)PROGRAM:Installer  PROJECT:Installer-934.2
Nov 16 01:15:44 IPNs-MBP Installer[916]: Hardware: MacBookPro11,1 @ 2.59 GHz (x 8), 16384 MB RAM
Nov 16 01:15:44 IPNs-MBP Installer[916]: Running OS Build: Mac OS X 10.14.6 (18G8022)
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: TMPDIR=/var/folders/w2/m46wcc312tjd4gnkl53wcgjh0000gn/T/
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: SHELL=/bin/zsh
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: HOME=/Users/ipn
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.lmDQ5nut9X/Render
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.qv5sXCxtIl/Listeners
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: LOGNAME=ipn
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: XPC_SERVICE_NAME=com.apple.installer.3524
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: USER=ipn
Nov 16 01:15:44 IPNs-MBP Installer[916]: Env: XPC_FLAGS=0x0
Nov 16 01:15:44 IPNs-MBP Installer[916]: Devil-Loc  Installation Log
Nov 16 01:15:44 IPNs-MBP Installer[916]: Opened from: /Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install Devil-Loc.pkg
Nov 16 01:15:44 IPNs-MBP Installer[916]: Package Authoring Error: <background_scaling> has an unsupported MIME type: X-NSObject/NSNumber
Nov 16 01:15:44 IPNs-MBP Installer[916]: Package Authoring Error: <background_alignment> has an unsupported MIME type: X-NSObject/NSNumber
Nov 16 01:15:45 IPNs-MBP Installer[916]: Referenced component packages (1) trustLevel=100
Nov 16 01:15:50 IPNs-MBP Installer[916]: InstallerStatusNotifications plugin loaded
Nov 16 01:15:54 IPNs-MBP Installer[916]: Administrator authorization granted.
Nov 16 01:15:54 IPNs-MBP Installer[916]: ================================================================================
Nov 16 01:15:54 IPNs-MBP Installer[916]: User picked Standard Install
Nov 16 01:15:54 IPNs-MBP Installer[916]: Choices selected for installation:
Nov 16 01:15:54 IPNs-MBP Installer[916]: 	Install: "Devil-Loc"
Nov 16 01:15:54 IPNs-MBP Installer[916]: 		Install Devil-Loc.pkg : com.soundtoys.devilloc : 1.0.0.1.0
Nov 16 01:15:54 IPNs-MBP Installer[916]: ================================================================================
Nov 16 01:15:54 IPNs-MBP Installer[916]: It took 0.00 seconds to summarize the package selections.
Nov 16 01:15:54 IPNs-MBP Installer[916]: -[IFPKGDerivedDocument sortedPackageLocations]: result = (
	    "file://localhost"
	)
Nov 16 01:15:54 IPNs-MBP Installer[916]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Nov 16 01:15:54 IPNs-MBP Installer[916]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install%20Devil-Loc.pkg
Nov 16 01:15:54 IPNs-MBP Installer[916]: Set authorization level to root for session
Nov 16 01:15:54 IPNs-MBP Installer[916]: Will use PK session
Nov 16 01:15:54 IPNs-MBP Installer[916]: Using authorization level of root for IFPKInstallElement
Nov 16 01:15:54 IPNs-MBP Installer[916]: Starting installation:
Nov 16 01:15:54 IPNs-MBP Installer[916]: Configuring volume "Mac OS"
Nov 16 01:15:54 IPNs-MBP Installer[916]: Preparing disk for local booted install.
Nov 16 01:15:54 IPNs-MBP Installer[916]: Free space on "Mac OS": 81,38 GB (81383288832 bytes).
Nov 16 01:15:54 IPNs-MBP Installer[916]: Create temporary directory "/var/folders/w2/m46wcc312tjd4gnkl53wcgjh0000gn/T//Install.916Alx3wu"
Nov 16 01:15:54 IPNs-MBP Installer[916]: IFPKInstallElement (1 packages)
Nov 16 01:15:54 IPNs-MBP Installer[916]: Current Path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: Adding client PKInstallDaemonClient pid=916, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Nov 16 01:15:54 IPNs-MBP Installer[916]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: ----- Begin install -----
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: packages=(
	    "PKJaguarPackage <id=com.soundtoys.devilloc, version=1.0.0, url=file://localhost/Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install%20Devil-Loc.pkg>"
	)
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: Set reponsibility for install to 916
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: Extracting file://localhost/Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install%20Devil-Loc.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/BE804821-EF07-4D6E-A547-4FD82CFDD8C2.activeSandbox/Root, uid=0)
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: prevent user idle system sleep
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: suspending backupd
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit: Applications/SoundToys/Devil-Loc Authorizer.app relocated to Applications/Soundtoys/SoundToys Native Effects V4 Authorizer.app
Nov 16 01:15:54 IPNs-MBP installd[406]: PackageKit (package_script_service): Preparing to execute script "./preflight" in /Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install Devil-Loc.pkg/Contents/Resources
Nov 16 01:15:54 IPNs-MBP package_script_service[444]: PackageKit: Executing script "preflight" in /Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install Devil-Loc.pkg/Contents/Resources
Nov 16 01:15:54 IPNs-MBP package_script_service[444]: PackageKit: Set reponsibility for install to 916
Nov 16 01:15:54 IPNs-MBP package_script_service[444]: PackageKit: *** launch path not accessible
Nov 16 01:15:54 IPNs-MBP package_script_service[444]: PackageKit: Failed task attributes: {
	    NSFileCreationDate = "2013-08-29 05:52:42 +0000";
	    NSFileExtendedAttributes =     {
	        "com.apple.quarantine" = <30303833 3b363139 32636238 613b4b65 6b613b42 43394145 3541332d 35323446 2d343739 302d3835 38462d36 35454235 31453841 333646>;
	    };
	    NSFileExtensionHidden = 0;
	    NSFileGroupOwnerAccountID = 20;
	    NSFileGroupOwnerAccountName = staff;
	    NSFileHFSCreatorCode = 0;
	    NSFileHFSTypeCode = 0;
	    NSFileModificationDate = "2013-08-29 05:52:42 +0000";
	    NSFileOwnerAccountID = 501;
	    NSFileOwnerAccountName = ipn;
	    NSFilePosixPermissions = 438;
	    NSFileReferenceCount = 1;
	    NSFileSize = 1486;
	    NSFileSystemFileNumber = 12905081704;
	    NSFileSystemNumber = 16777220;
	    NSFileType = NSFileTypeRegular;
	}
Nov 16 01:15:54 IPNs-MBP install_monitor[920]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Nov 16 01:15:54 IPNs-MBP package_script_service[444]: Responsibility set back to self.
Nov 16 01:15:54 IPNs-MBP install_monitor[920]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Nov 16 01:15:55 IPNs-MBP installd[406]: PackageKit: releasing backupd
Nov 16 01:15:55 IPNs-MBP installd[406]: PackageKit: allow user idle system sleep
Nov 16 01:15:55 IPNs-MBP installd[406]: PackageKit: Cleared permissions on Installer.app
Nov 16 01:15:55 IPNs-MBP installd[406]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Install Devil-Loc.pkg”." UserInfo={NSFilePath=./preflight, NSURL=file://localhost/Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install%20Devil-Loc.pkg, PKInstallPackageIdentifier=com.soundtoys.devilloc, NSLocalizedDescription=An error occurred while running scripts from the package “Install Devil-Loc.pkg”.} {
	    NSFilePath = "./preflight";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cInstall Devil-Loc.pkg\U201d.";
	    NSURL = "file://localhost/Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install%20Devil-Loc.pkg";
	    PKInstallPackageIdentifier = "com.soundtoys.devilloc";
	}
Nov 16 01:15:55 IPNs-MBP installd[406]: PackageKit: Running idle tasks
Nov 16 01:15:55 IPNs-MBP Installer[916]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Install Devil-Loc.pkg”." UserInfo={NSFilePath=./preflight, NSURL=file://localhost/Users/ipn/Desktop/DEVLOC/SoundToys.Devil-Loc.v1.0.0.RTAS.VST.AU.fixed/Install%20Devil-Loc.pkg, PKInstallPackageIdentifier=com.soundtoys.devilloc, NSLocalizedDescription=An error occurred while running scripts from the package “Install Devil-Loc.pkg”.}
Nov 16 01:15:55 IPNs-MBP installd[406]: PackageKit: Removing client PKInstallDaemonClient pid=916, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Nov 16 01:15:55 IPNs-MBP installd[406]: PackageKit: Done with sandbox removals
Nov 16 01:15:56 IPNs-MBP Installer[916]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Nov 16 01:15:56 IPNs-MBP Installer[916]: IFDInstallController 1F84FB0 state = 8
Nov 16 01:15:56 IPNs-MBP Installer[916]: Displaying 'Install Failed' UI.
Nov 16 01:15:56 IPNs-MBP Installer[916]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by bfleischer** [comment]
Please raise this issue with the developers of the audio plugin. This is the wrong issue tracker.
