### ISSUE TITLE
Broken after reboot on macOS 12.0.1

### ISSUE THREAD

**Issue by WGroleau** [osxfuse/osxfuse#855]
Ian macOS 12.0.1,  ran the macFUSE 4.2.3 installer, and rebooted to activate it.  I then ran the sshfs 2.5.0 installer.

It worked (without sudo) when I was the owner of the mount point and gave me full access to everything in the shell.  owner and group were mine locally and were still correct on the server.  I edited and saved a text file, and it did not change owner or group on the server.  Great.

The mount point in the Finder has a name change to “macFUSE volume 0 (sshfs)” but that is harmless, and it changed back when dismounted.   It still appeared unchanged to “ls” in the shell.

Unfortunately, I rebooted after that.  Now,

- In Finder, the mount point are hidden, and Go→Go to file tries to 'cd' to a non-directory with a name that starts with the same letters as the mount-point.
- In the shell, if I try to `cd` or `ls` the mount point, I get "device not configured.
- `df` shows them mounted with size, available, and used all zero
- but umount says they are not mounted.
- and the same mount command says "already on a macFUSE volume'

**Comment by WGroleau** [comment]
?!? An hour or so after posting this as an issue, it is again working as expected.  ?!?

**Comment by davidnic1** [comment]
Lucky dog. Fresh install in a fresh m1 Mac just hangs for me.

**Comment by maxiller** [comment]
> ?!? An hour or so after posting this as an issue, it is again working as expected. ?!?

Did you do anything to make it work? Including reboot?
I can't even remove the mount point dir...


UPD (after a minute): I figured it out myself — managed to reset the mount point by unmounting it with diskutil.
`diskutil unmount /path/to/mount/point`

**Comment by WGroleau** [comment]
Been a long time, so I've done  lot of things since.  What I have now is a script that cron calls every four minutes.  This script looks in one of the remote directories.  An error would indicates it is not mounted.  In that case, an unmount command is issued to get past the weird state it gets in after a timeout.  If it's already fully unmounted, the error message doesn't hurt.  Either way, it is fully unmounted afterward, so the command to mount it won't fail.

At the end, another command to access the remote should work even if the starting one failed.  Having an access every four minutes would theoretically keep it active.  But if and when it doesn't, this script should bring it back.

I still think there may be some kid of bug, but this is my way around it

The attached script calls another script that is IN the mount point when not mounted.  That one contains only one command:
`nice  sshfs  account@host.TLD:remote-path  local-mount-point
`
[MTT.zip](https://github.com/osxfuse/osxfuse/files/7921335/MTT.zip)
.

**Comment by maxiller** [comment]
Thanks for that. Let's take the use case when mounts are made with some tool such as rclone.
I still wouldn't call that a bug, it is rather the way it happens when rclone (either fg or daemonized) crashes.
I think the workaround with unmounting works pretty well if the one knows what to check against _device is not configured_ error. Though, the error being thrown is not actual rclone's error — it comes from the OS, as native commands such as `du`, `ls` and even `rm` give exactly the same error.

Cron is good, but for occasional use of `rclone mount` it seems an overhead to me.

**Comment by bfleischer** [comment]
This issue has been inactive for al long time, so I'm going to close it. Feel free to open a new issue in case the problem persists and you think macFUSE is to blame for it.

**Comment by WGroleau** [comment]
Still doing the same, but I don't know where the real culprit is.
My workaround keeps me functioning, so this is not really worth pursuing in my mind.
