### ISSUE TITLE
sshfs hangs terminal on brand new Mac M1

### ISSUE THREAD

**Issue by davidnic1** [osxfuse/osxfuse#856]
Brand new Mac (OS 12.0.1, M1 chipset) sshfs and Fuse installed from https://osxfuse.github.io. I do:

> sudo sshfs -d mayacc@myhost.com:/home/myacc ~/mnt

The terminal hangs, can't ^C the process.

It works fine on my Intel Mac.

Any ideas what I've done wrong?

**Comment by StephanieSunshine** [comment]
I can confirm this. I installed for the first time today on a new Apple M1 MacOS 12.1 Macfuse 4.2.4 and SSHFS 2.5.0.  When I try to connect to a machine it just hangs, I can't control+c the process, manually killing the process with kill doesn't fully kill it, and when I went to reboot the machine hung at the end and forced me to hard reset it.  I have yet to have a problem with this machine even remotely close to this.

I do not have an Intel Mac to prove with, but other Linux boxes have no problem connecting to the machine I'm trying to connect to on my local network.

**Comment by jnchaba** [comment]
Same issue on my machine. Hard reset it the _only_ way to resolve this.

**Comment by samit4me** [comment]
Same issue here with m1 and MacOS 12.01 (hangs until a timeout).
It seems fine on intel mac.

**Comment by samit4me** [comment]
Not sure if this will help anyone, but `sshfs` was hanging on my m1 mac, but is now working 🎉

Unsure what fixed the issue but I did the following:

- Removed macFUSE (installed from https://osxfuse.github.io/)
- Restart
- Updated macOS from `12.0.1` to `12.1`
- Install macFUSE via brew (e.g. `brew install --cask macfuse`)
- Restart
- Then `sshfs` working 

Sorry if that doesn't resolve your issue, I'll update if I have any further issues.

**Comment by chasegiunta** [comment]
Wow, uninstalling and reinstalling via `brew install --cask macfuse` surprisingly works for me too!

**Comment by akodocumaster** [comment]
I tried removing macFuse, restarting and installing macFuse via brew (brew install --cask macfuse) and then restarting. sshfs crashes when I try to mount a volume.

Were you actually able to mount volumes @chasegiunta and @samit4me ?

System: MacBook Pro 13-inch, M1, 2020, macOs 12.2

**Comment by bfleischer** [comment]
brew installs the same macFUSE releases you can download from GitHub or the macFUSE website. There should not be any difference.

**Comment by samit4me** [comment]
> I tried removing macFuse, restarting and installing macFuse via brew (brew install --cask macfuse) and then restarting. sshfs crashes when I try to mount a volume.
> 
> Were you actually able to mount volumes @chasegiunta and @samit4me ?
> 
> System: MacBook Pro 13-inch, M1, 2020, macOs 12.2

So for me and my work colleagues, the issue seemed to disappear after updating to macOS 12.1.

After updating macOS, I actually uninstalled macFuse/SSHFS, rebooted and then installed them both again from https://osxfuse.github.io/ and everything seems to be working.

Sometimes I have issues if the remote host goes offline. To fix it, I have to reboot, then umount the drives, then reboot and re mount drives. There is probably a nicer way of killing processes etc without a reboot but I'm not sure.

Hope that helps, sorry if it doesn't, good luck.

**Comment by akodocumaster** [comment]
Sorry about deleting the original message, didn't expect to get answers this quick :) I got it working but everything hangs and the only solution seems to be a reboot if it can't reach the host for some reason.

**Comment by samit4me** [comment]
Yep same here, people with Intel Mac's don't seem to have the same issue.

**Comment by yashkant** [comment]
I got this to work on macOS Monterey (12.3.1) and M1 chip by using sshfs (version 2.5.0) and macfuse (version 4.2.0) both installed from .dmg, and not brew.

**Comment by serlou** [comment]
The same happened to me.
**Solution:** Go to Settings -> MacFUSE, and update the software to the latest stable version.

**Comment by dlangille** [comment]
> Wow, uninstalling and reinstalling via `brew install --cask macfuse` surprisingly works for me too!

This is what worked for me. I'm not on M1, I'm on intel.

**Comment by AllenEllis** [comment]
> The same happened to me. **Solution:** Go to Settings -> MacFUSE, and update the software to the latest stable version.

This didn't help me. I'm on an M1 Max MacBook Pro. Settings > MacFUSE shows installed version: 4.5.0, and no updates available at this time.

Starting any new connection just freezes everything and I have to do a hard reboot.

**Comment by vPeteWalker** [comment]
Same issue using Macfuse 4.5, whether using .dmg or installing via Brew. What info can I provide on this to assist?

**Comment by ngocbh** [comment]
I have the same issue.

**Comment by MattiasMartens** [comment]
Same issue on Sonoma 14.1.2, latest version of MacFUSE.

**Comment by bfleischer** [comment]
The new 4.6.2 release addresses the hang.

**Comment by sbaker25** [comment]
> The new 4.6.2 release addresses the hang.

I just experienced the same symptoms using 4.8.3.  Session accessing remote mount hangs.  Attempting to umount hangs.  Could not perform a graceful system restart, had to hard reset.

**Comment by bfleischer** [comment]
Please provide more information. Did the hang occur directly after mounting the volume?

**Comment by sbaker25** [comment]
That was a remarkably quick response :).  The hang was very shortly after mounting the volume, but not immediate.  I mounted the volume, was able to run "ls" and list contents of mount point.  I changed my working directory to one that was mounted and was not able to issue any other commands.  I waited a few minutes and then went to another tmux window to umount.   The umount command hung.  I tried to induce a break by disconnecting my network, but this had no effect. 

When I tried to restart, the OS beachball came up.  After a minute or two, I performed a hard reset.

**Comment by bfleischer** [comment]
It's hard to tell what might be causing the issue you are seeing. Your issue could be caused by a network issue or a server issue. SSHFS issues many server requests. Some servers rate-limit client requests. The hang you are seeing is most likely a result of SSHFS not receiving a response to a file system request.

The bug that was fixed in 4.6.2 is related to the mount process not succeeding and the volume then being in an unmountable state. That's not what's happening in your case.

**Comment by sbaker25** [comment]
It is certainly true that my failure is not happening on mount.  I tried a second time and had exactly the same result.  I was able to 'ls' the contents of my mount.  As soon as I used 'cd' to change to a directory on the mount, it hung.  I did not try umount this time and was able to perform a graceful OS system restart.
