### ISSUE TITLE
macfuse-4.2.3.sha256 signed with expired key

### ISSUE THREAD

**Issue by vespasian99** [osxfuse/osxfuse#859]
% gpg --verify macfuse-4.2.3.sha256.sig
gpg: assuming signed data in 'macfuse-4.2.3.sha256'
gpg: Signature made Tue 16 Nov 12:50:54 2021 GMT
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: Good signature from "Benjamin Fleischer <fleiben@gmail.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 0093 B21E F45D 6352 84F6  A147 53C9 18C1 A281 8875
     Subkey fingerprint: 135F 164B 411B AA1F 4A4B  CD37 617A 3461 8026 08A1

**Comment by bfleischer** [comment]
You need to update the key from a key server (e.g. https://keys.openpgp.org/search?q=fleiben%40gmail.com) or download it from https://osxfuse.github.io/static/53C918C1A2818875.asc.
