### ISSUE TITLE
Installing MacFuse on Apple silicon Monterey (macOS 12.0.1) breaks Apple Pay (security issue)

### ISSUE THREAD

**Issue by minimondo** [osxfuse/osxfuse#860]
I'm raising this more as a question: can anyone please confirm this on their M1 w/ Monterey?

MacFuse causes no issues on my Intel Monterey; Apple Pay works fine.

On my M1 Monterey, MacFuse also works perfectly, but trying to open the "Apple Pay" pane in sys prefs gives a security error. The op sys doesn't appear to trust the installed filesystem/KEXT. Please see screen dump.

FYI, the same issue occurs when a commercial 3rd-party NTFS filesystem is installed (in kernel space). It also works on Intel Monterey with no issues (other than a KEXT deprecation warning at boot).

I have raised this issue with Apple L3 support.

![symptom](https://user-images.githubusercontent.com/139458/143525042-c3494295-5252-49ee-bf69-756c276f685c.jpg)

**Comment by minimondo** [comment]
I was sent the following link regarding the tightened security on the M1 platform, and how some KEXTs can break Apple Pay:

https://support.apple.com/en-au/guide/security/sec8e454101b/web
![M1-Mac-Extensions-ApplePay](https://user-images.githubusercontent.com/139458/143526979-1944c0c6-828a-4ff8-8951-9b0dee495bcc.jpg)

**Comment by bfleischer** [comment]
I can confirm that Apple Pay works fine on macOS Monterey 12.0.1 on my Apple Silicon powered MacBook Pro with macFUSE being installed. It's definitely not macFUSE that is causing the issues for you.

Regarding the link you were sent by Apple:

All macFUSE releases since May 2019 have been reviewed and approved by Apple (Apple's notarization service). Installing macFUSE does not require you to disable System integrity Protection. This means macFUSE does not interfere with the trustworthiness of macOS and should therefore not be the reason for Apple Pay not being available on your Mac.

That being said, have you checked whether System Integrity Protection is disabled on your Mac or not? This would in fact be a security issue.

**Comment by minimondo** [comment]
Thanks for your rapid and helpful response.

Yes, I can’t understand my issue, as I know that MacFuse is notarised. I know it’s not a MacFuse problem, but FYI this is what happens to me:

1) clean fresh 12.0.1 (re)install on 16” MBP (Apple silicon); Apple Pay works fine.
2) install MacFuse; permit the installation of the kext/driver; reboot.
3) FUSE fs works fine; Apple Pay gives a “security changed” warning and doesn’t work.
4) I then have to enter RecoveryOS and run “kmutil …” to remove all 3rd-party extensions; on reboot Apple Pay is OK.

I did check that SIP was enabled; I also re-enabled it in RecoveryOS. No change.

Thanks again for taking the time to help.

Regards, M.

**Comment by minimondo** [comment]
Out of courtesy, I'm writing to detail my fix. The issue had nothing to do with MacFuse. I simply removed my 3 credit cards from the old Intel macbook (from which I migrated my account to the new M1 mac). Fixed. Thanks for your time; I hope this may help someone else.

**Comment by stefancars** [comment]
Hi. I'm not sure if Mac OS 12.2 is starting to cause issues, after upgrade to 12.2 my Apple Pay is now disabled.  I tried reinstalling the mac and ONLY thing i did was "lower" security settings and installed MacFUSE and Apple Pay is now disabled..

**Comment by stefancars** [comment]
> Hi. I'm not sure if Mac OS 12.2 is starting to cause issues, after upgrade to 12.2 my Apple Pay is now disabled. I tried reinstalling the mac and ONLY thing i did was "lower" security settings and installed MacFUSE and Apple Pay is now disabled..

And now, after just idling 1 hour and re-login to Apple ID, it works.... weird.

**Comment by minimondo** [comment]
Hi Stefan,

Monterey 12.2 hasn’t fixed the original issue. This issue has nothing to do with OSXFuse; any time the boot security on M1 Monterey is lowered, the code involved has some kind of leak/corruption which may cause somewhat random errors (usually only on M1 Pro/Max silicon). Usually Apple Pay and/or Time Machine stop working. I’m glad that your system is working again, but in my experience a simple shutdown and restart may break it again. The only solution for now (if you are affected) is to remove all 3rd-party extensions and enable full boot security. I can tell you that Apple engineering is aware of the issue. May I ask what hardware you are using?

**Comment by FuturePilot** [comment]
This is a strange situation. I have an M1 MBA and MacFuse and Apple Pay play just fine together. After installing and lowering the security settings on my Mac Studio, it disabled Apple Pay. Nothing I tried could get Apple Pay to re-enable except changing the security settings back to full.

**Comment by minimondo** [comment]
Yes, there was an issue with macOS and the bigger M1 chips (probably to do with a memory leak). All 3rd-party kernel extensions were impacted (along with Time Machine). The problem should have gone with Monterey 12.2.1 and later.

**Comment by FuturePilot** [comment]
I'm on 12.3.1. I'm more than happy to provide and troubleshooting information, logs, etc.

**Comment by minimondo** [comment]
Please try the following. NOTE to any readers - The problem is within macOS, not MacFuse or other extensions…

1) Uninstall MacFuse via the pref pane. Also, uninstall ALL other 3rd-party extensions, including the Rogue Amoeba ACE ( this is a hardware- abstraction-layer audio extension), if you have it.

2) Shutdown, boot into RecoveryOS. Run the Terminal from the Utilities menu. Enter and run this command:

kmutil trigger-panic-medic --volume-root /

3) Reboot and install just MacFuse. If Apple Pay works then install any other extensions, one by one.

4) if the problem persists, repeat steps 1 & 2. Then reinstall Monterey 12.3.1 from the network or a local installer copy.

**Comment by FuturePilot** [comment]
I followed those instructions but the problem persisted so I continued with the re-installation of 12.3.1 part, but it is still disabling Apple Pay when the MacFuse extension is loaded. That is the only extension I have installed on my system.

**Comment by minimondo** [comment]
Does your Mac Studio have an M1 Ultra CPU? If so, does it have 64 or 128GB of RAM? Asking because my MBP with M1 Max & 64GB is OK. Back in Oct 2021 it seemed to be RAM size that broke Apple Pay, etc.

**Comment by FuturePilot** [comment]
I have the M1 Ultra with 64GB of RAM.

**Comment by minimondo** [comment]
I need to give you further advice in private. I have just written to what I think is your email address via your blog. Can you please check and respond if I got it right?

Michael Sanders

**Comment by FuturePilot** [comment]
I did not receive any email. You can send me an email at futurepilot at gmx[dot]us
