### ISSUE TITLE
kext load failed: -603946986 ... using VeraCrypt with OS12.0.1

### ISSUE THREAD

**Issue by Eifelziege** [osxfuse/osxfuse#861]
OS 12.0.1
Macfuse 4.2.3
VeraCrypt 1.25.4
Any idea, what needs to be done to Mount a VeraCrypt Volume which was generated by VeraCrypt ?
I do get this error message even after installing different versions of both tools. 
I also tried to install with csrutil disable  ... 
<img width="258" alt="Bildschirmfoto 2021-12-09 um 16 25 20" src="https://user-images.githubusercontent.com/95870408/145426646-c475e7f6-bbad-4c0b-83c6-0897f0577c8a.png">
e

**Comment by bfleischer** [comment]
This means the macFUSE kernel extension could not be loaded. Directly after you see this error message go to System Preferences > Security & Privacy (General tab) and check if there is an "Allow" button to allow loading system software from Benjamin Fleischer. Make sure to press the button.

If you are on an M1 Mac you might need to enable support for third-party kernel extension from the recovery environment first. In this case the Security & Privacy preference pane will display instructions on how to do this.

**Comment by Eifelziege** [comment]
Unfortunately, this does not work – this is what I already tried (I am not on M1).
I was expecting this message during installation – but even there, it did not appear.
Any other idea ?

Von: Benjamin Fleischer ***@***.***>
Datum: Sonntag, 19. Dezember 2021 um 23:21
An: osxfuse/osxfuse ***@***.***>
Cc: Eifelziege ***@***.***>, Author ***@***.***>
Betreff: Re: [osxfuse/osxfuse] kext load failed: -603946986 ... using VeraCrypt with OS12.0.1 (Issue #861)

This means the macFUSE kernel extension could not be loaded. Directly after you see this error message go to System Preferences > Security & Privacy (General tab) and check if there is an "Allow" button to allow loading system software from Benjamin Fleischer. Make sure to press the button.

If you are on an M1 Mac you might need to enable support for third-party kernel extension from the recovery environment first. In this case the Security & Privacy preference pane will display instructions on how to do this.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fosxfuse%2Fosxfuse%2Fissues%2F861%23issuecomment-997472050&data=04%7C01%7C%7Cde9e7e625fd44cd195db08d9c33dd6ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755492632357965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=homiLsZmNLoBWSouys%2F%2BDCIAls7AnRQ6CvuPvIVsiVg%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW3N3SEB7XKLQ6LNHMAYBVLURZLEZANCNFSM5JWY727Q&data=04%7C01%7C%7Cde9e7e625fd44cd195db08d9c33dd6ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755492632357965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SpUHH%2BRd0NgFWo0ZN3QPx1%2BU3ScsZloR9LcQT%2F2crv0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cde9e7e625fd44cd195db08d9c33dd6ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755492632357965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MkmhFNuhuLWurW7J8RxZTIRwOO33qmB6mhaNxDDwAG4%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cde9e7e625fd44cd195db08d9c33dd6ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755492632357965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xdQu1dsAeqJeQz%2B1a%2FjiQ81pIDL7G56qzPmL1DLh74U%3D&reserved=0>.

**Comment by bfleischer** [comment]
For future reference, see https://github.com/macfuse/macfuse/wiki/Getting-Started. The document contains detailed instructions on how to enable the macFUSE kernel extension and it lists troubleshooting tips.
