### ISSUE TITLE
MacFuse pane in preferences on mac m1

### ISSUE THREAD

**Issue by xerxes24mg** [osxfuse/osxfuse#862]
In the System Preferences on my macbookpro m1 there is no macFUSE pane? On my Intel macbook I can see it. Is that normal?
Thanks for help.

**Comment by adityagi02** [comment]
I was having the same question, and I can say it's normal in m1s. many other preference panes are also not present in mine System Preferences that were there in intel's.

**Comment by bfleischer** [comment]
> I was having the same question, and I can say it's normal in m1s.

After installing an up-to-date version of macFUSE (that supports M1 Macs) you will see the macFUSE preference pane. It's exactly the same on Intel machines.

Which version of macFUSE did you install?

**Comment by xerxes24mg** [comment]
I‘ve installed version 4.2.3 and I can‘t see the preference pane.

**Comment by bfleischer** [comment]
@xerxes24mg Did you try restarting your mac after installing macFUSE?

**Comment by xerxes24mg** [comment]
@bfleischer Yes, I did, but couldn't never see the pane.

**Comment by erdengk** [comment]
@xerxes24mg   I have a similar problem. I installed macfuse 4.2.4 .  The pane can only be seen in the dock, but it cannot be displayed on the screen normally.

**Comment by niklasmato** [comment]
Did you load the kernel extension?

**Comment by xerxes24mg** [comment]
@niklasmato I did load the kernel extension, otherwise I would not be able to use the app that is dependent on the extension. But fortunately the app works. It's just the pref pane that has disappeared.

**Comment by bfleischer** [comment]
This ticket has been inactive for a long time, so I'm closing it. Feel free to open a new ticket in case this is still an issue.
