### ISSUE TITLE
Link to the macFUSE website broken in the system pane on Monterey 12.1

### ISSUE THREAD

**Issue by slackero** [osxfuse/osxfuse#866]
No real problem, but the link to the **macFUSE website** isn't working  
<img width="875" alt="Bildschirmfoto 2021-12-20 um 11 09 32" src="https://user-images.githubusercontent.com/15139/146734943-5323cb20-f96a-42ac-b47f-d608306e06e9.png">  
<img width="409" alt="Bildschirmfoto 2021-12-20 um 11 09 26" src="https://user-images.githubusercontent.com/15139/146734948-1ca3321f-feaa-4e97-8863-8881647a8698.png">

**Comment by bfleischer** [comment]
Works fine for me. Are you by any chance using a different browser than Safari?

**Comment by slackero** [comment]
Sure, Safari is completely unused here – it's not the default browser. And as I wrote, it works now – opening my default browser.
