### ISSUE TITLE
User mapping for triple boot?

### ISSUE THREAD

**Issue by nvmnghia** [osxfuse/osxfuse#867]
After running `ntfsusermap` on macOS, I can't write to my NTFS drive in Linux anymore. For example

- `touch new_file` does create `new_file`, but it complains `setting times of 'new_file': Permission denied`.
- `rm new_file` complains `remove write-protected regular empty file 'new_file'`. `rm -f` works.

I think this `ntfsusermap` is the problem, I've never touched the permission on Windows.

**Comment by bfleischer** [comment]
Please raise this issue with the NTFS-3G project. macFUSE and NTFS-3G are two different projects and judging from your description this sounds more like an NTFS issue than a macFUSE issue.
