### ISSUE TITLE
Confirmed macFUSE Bug -- Causes Consistent Crashes in Time Machine (Apple macOS) 

### ISSUE THREAD

**Issue by EvanHKatz** [osxfuse/osxfuse#868]
I have confirmed, reproduced and reported to Apple one or two (see below) bugs in macFUSE.

Specifically, after installing on December 20, 2021 the then newly released and updated version of macFuse, Time Machine would cause the Mac to crash and reboot on any and all Macs on which the new version of macFUSE had been installed.

After my extensive testing, and my multiple conversations with an Apple Level 2 senior Technical Support technician (e.g., submitting logs, reviewing recent software app and kext updates, and eventually then removing macFUSE) it was confirmed that it indeed was macFUSE that was causing the Macs to crash every single time that they ran Time Machine.  This was reported to Apple, which confirmed the bug, and I will e-mail to Ben directly the Apple Tech Support case #.

Also, please know that there either are one or two bugs in macFUSE.  Because upon inspection of the kext that macFUSE installed (the file is located and run by macFUSE from Macintosh HD / Library / Filesystems / macfuse.fs <you then need to right-click and select "Show Package Contents"> / Contents / Extensions / <Your macOS Version Number> / macfuse.kext), I observed and confirmed that macFUSE was/is loading the wrong version of macfuse.kext.

That is, even though we are running macOS Monterey (i.e., macOS v. 12.x), and have been since its release, macFUSE installed 10 versions of macfuse.kext, corresponding to the 10 most recently released macOS versions 11 and 10.x (specifically macFUSE for macOS 10.9 through 12.x), but was running macfuse.kext for macOS v. 11 (Big Sur), even though we have macOS v. 12 (Monterey), and even though we were running Monterey at the time that we installed macFUSE.

So, in sum, the macFUSE bug(s) is(are) that macFUSE, or its most recent update, (A) is incompatible with recent versions of macOS, or more likely (because that bug would easily have been caught in testing, and I also did not find/see a massive number of bug reports), (B) for some reason, decided to run all on of our Macs, all running Monterey, the version of macFUSE for Big Sur (i.e., macFUSE mistakenly ran the wrong version of the kext).  Again, I will e-mail a copy of this bug report to Ben.

If anyone has any questions, or would like any more information, please feel free to e-mail me.

Kind regards to all,
Evan Katz (NYC)
EKatz(at)CrawfordVentures(dot)com

<img width="304" alt="Screen Shot 2021-12-25 at 9 03 09 AM" src="https://user-images.githubusercontent.com/33664716/147386728-f286ecfb-d08d-411b-8003-082d665b7a4a.png">
<img width="935" alt="Screen Shot 2021-12-23 at 6 08 18 PM" src="https://user-images.githubusercontent.com/33664716/147386729-73ad7340-e5d6-4ba5-82b4-bf6fcec423de.png">
<img width="1468" alt="Screen Shot 2021-12-23 at 5 41 13 PM" src="https://user-images.githubusercontent.com/33664716/147386730-98e16ba4-447d-450c-991e-35c433a6f81c.png">

**Comment by bfleischer** [comment]
Hi Evan,

macFUSE loads the correct version of the kernel extension on macOS 12. There is just one kernel extension for macOS 11 and macOS 12. The "folder" named 12 in your last screenshot is just a symlink to the folder 11. In the lower left corner of the folder icon you can see a little arrow that indicates that this is a symlink and not a real folder. This means `/Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext` being loaded on macOS 12 is correct and not a bug.

> Specifically, after installing on December 20, 2021 the then newly released and updated version of macFuse, Time Machine would cause the Mac to crash and reboot on any and all Macs on which the new version of macFUSE had been installed.

I cannot confirm this. I'm using Time Machine myself and I'm not running into any issues whatsoever. There needs to be more to the crashes you are seeing. Please attach the kernel panic logs to this ticket. Without those logs there is nothing I can do.

Are you using Time Machine to back up a macFUSE volume or are you using a macFUSE volume as target location for Time Machine? If this is not the case, I don't see how Time Machine would even interact with macFUSE.

Which macFUSE-based file system are you using? macFUSE is just a building block that allows third-party developers to develop actual file systems. Please provide as much information about your setup and the exact repro steps that lead to the panic.

**Comment by bfleischer** [comment]
Are there any news regarding the panic logs?

**Comment by bfleischer** [comment]
I'm closing the ticket for lack of feedback.
