### ISSUE TITLE
VeraCrypt does not run on MacOS 12.0.1.de

### ISSUE THREAD

**Issue by dieideealisten** [osxfuse/osxfuse#869]
We use Veracrypt and MacFuse to encrypt USB-Volumes. After updating to 12.0 Veracypt/MacFuse doesn't work.

**Comment by bfleischer** [comment]
macFUSE 4.2.4 supports macOS 12. Please make sure to install the latest updates for macOS 12 and VeryCrypt. If the issue persists, please raise it with the VeryCrypt team.

**Comment by dieideealisten** [comment]
yep ... but Monterey seems to block MacFuse ... Veracrypt runs fine

**Comment by bfleischer** [comment]
You need to follow the instructions displayed by macFUSE and macOS to allow loading third-party kernel extensions (if you are on an Apple Silicon Mac) and more specifically the macFUSE kernel extension (Intel and Apple Silicon). Where exactly are you stuck?

**Comment by dieideealisten** [comment]
Unfortunately the alerts after the installing routine were quit. We can not get into the security settings again ... :( 
(Intel-Macbook//MacOS12.0.1). Unfortunately, reinstalling MacFuse did not bring up any kernel security setting windows.

**Comment by bfleischer** [comment]
You should see an alert every time you try to load the macFUSE kernel extension (i.e. every time you try to mount a VeraCrypt volume) until you allow loading the kernel extension. Try to mount your VeraCrypt volume. When it fails, open the Security and Privacy preference pane and switch to the General tab. There should be an "Allow" button.

**Comment by dieideealisten** [comment]
nope ... there's no allow-button

**Comment by bfleischer** [comment]
Then it's most likely not a macFUSE issue. You should see an "Allow" button in case the macFUSE kernel extension cannot be loaded.

**Comment by bfleischer** [comment]
For future reference see https://github.com/macfuse/macfuse/wiki/Getting-Started.
