### ISSUE TITLE
Use UNIX-style symlinks, not MacOS aliases

### ISSUE THREAD

**Issue by DUOLabs333** [osxfuse/osxfuse#870]
When running on MacOS, fuse-ext2 uses aliases, not symlinks. Many programs (like rsync), can't handle this, and it breaks compatibility on other systems. So, you should replace the use of aliases with symlinks. I'm not sure this is because of how `osxfuse` presents symlinks, or with how `fuse-ext2` works.

**Comment by bfleischer** [comment]
macFUSE support creating symlinks. If you are using Finder (or other high level macOS tools) to create links you will end up with a macOS alias, just like on any other macOS file system. If you are using `ln -s` you end up with a standard unix symlink.

**Comment by DUOLabs333** [comment]
So, is the default symlinks?

**Comment by bfleischer** [comment]
It depends on how you create the link. Finder creates aliases, not symlinks. You can create symlinks using low-level tools like `ln -s`.

**Comment by DUOLabs333** [comment]
I use `fuse-ext2`, so I'm assuming that it should be symlinks.

**Comment by bfleischer** [comment]
Finder creates aliases not symlinks. If you want that to change, you need to raise the issue with Apple.

**Comment by DUOLabs333** [comment]
But Finder has nothing to do with this -- it doesn't mount, unless it has deeper hooks into the kernel than I thought?

**Comment by bfleischer** [comment]
It does not matter who (or which process) mounts the volume. All that matters is how the link is created on the volume. If the application creating the link (e.g. Finder) creates an alias then there will be an alias on your ext2 volume. If the application creates a symlink, then there will be symlink on your volume. It all depends on the application that creates the link. There is nothing macFUSE can do to change the type of link.

**Comment by DUOLabs333** [comment]
I see. But why is Finder creating an alias?

**Comment by cdevers-es** [comment]
If I may — the application decides whether to create a file, an alias, or a symlink.

Finder on Mac OS X / OSX / macOS has _never_ supported creating Unix symlinks. Apple has had over twenty years to implement symlink support in Finder, but are still using aliases. They must have their reasons. 

As @bfleischer says, if you can create a symlink with `ln -s …`, then things are working as expected. 

***

Maybe it would help to describe the actual steps you’re using to reproduce the behavior you’re seeing?

**Comment by DUOLabs333** [comment]
Wait -- I'm mounting a disk image, how does Finder play in this?

**Comment by cdevers-es** [comment]
Please state the steps you’re using the reproduce the problem you’re asking about. That should clarify things.

**Comment by DUOLabs333** [comment]
I attach my disk image with `hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount $DISKIMAGE`
I then mount it with `sudo fuse-ext2 -o ro`
I then rsync the directory with `rsync -avh --no-compress --no-whole-file --inplace --progress`

**Comment by DUOLabs333** [comment]
It seems that I was mistaken -- it does use symlinks, it just that Finder doesn't show them properly (using `zsh` shows the symbolic links). Sorry for wasting your time.
