### ISSUE TITLE
MacFuse NTFS-3g doesn't work on Mac OS 12.1

### ISSUE THREAD

**Issue by emmarrem** [osxfuse/osxfuse#872]
After successful installation of the version 4.2.3 and upon using the command : 
sudo mkdir /Volumes/NTFS
sudo /usr/local/bin/ntfs-3g /dev/disk1s1 /Volumes/NTFS -o local -o allow_other -o auto_xattr -o auto_cache

I get the following error: sudo: /usr/local/bin/ntfs-3g: command not found

This issue was not prevalent on any previous versions of Mac OS

**Comment by bfleischer** [comment]
Did you install NTFS-3G? Looks like the `ntfs-3g` binary does not exist in `/usr/local/bin/`.

**Comment by emmarrem** [comment]
Yes I have installed the latest version of Macfuse 4.2.4.

Usually in the last iterations of the MacOs and Macfuse, after succesful install and then a restart, would be able to use the mount command.

however now it shows that ntfs-3g command is not found. 

Do i have to do something different? 

Thank you

**Comment by bfleischer** [comment]
macFUSE and NTFS-3G are two separate projects. NTFS-3G is based on macFUSE and needs to be installed separately. Check out https://github.com/osxfuse/osxfuse/wiki/NTFS-3G.
