### ISSUE TITLE
4.2.4, Monterey 12.2 bugs

### ISSUE THREAD

**Issue by ceavestone** [osxfuse/osxfuse#876]
Using Forklift 3.5.4 to mount a FTP disk, the operation has work brilliant until after the latest OS update.

The disk is mounted but saving operations is not commited through externat apps like VS CODE. Need to restart VS CODE and hopefully it works.

I can see that Forklift is not detecting the disk as mounted but it is still mounted on desktop.

**Comment by kehoe** [comment]
Same here on Monterey 12.1

Volume is mounted as sftp but saving operations not possible. Bug in VS Code or macFUSE?

**Comment by ceavestone** [comment]
When using Plain FTP , not TLS , it works better

**Comment by jzombie** [comment]
@ceavestone This Microsoft-provided VSCode extension may be useful for you: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

**Comment by bfleischer** [comment]
This issue has been inactive for a long time, so I'm going to close it. Feel free to open a new issue in case you are still running into the issue and think macFUSE is to blame for it.
