### ISSUE TITLE
Installing Macfuse on 10.14.6

### ISSUE THREAD

**Issue by troubleatmill** [osxfuse/osxfuse#877]
Trying to install Macfuse via the LucidLink app but the the message to allow Benjamin Fleischer never appears - I've re-installed a few times, rebooted after attempted to launch, installing MacFuse separately but getting no further…

BUT

When I look in System Report/Software/Extensions an older OSXFuse is listed but the Developer ID is Box.com (I have a Box account on this Mac:

<string>/Library/Filesystems/box.fs/Contents/Extensions/10.11/osxfuse.kext</string>
				<key>spext_runtime_environment</key>
				<string>spext_universal</string>
				<key>spext_signed_by</key>
				<string>Developer ID Application: Box, Inc. (M683GB7CPW), Developer ID Certification Authority, Apple Root CA</string>
				
Are they tripping over each other? As Box/OSXFuse would have been allowed before the upgrade to 10.14.6

Also grep osxfuse returns:

 192168018-JT-iMAC:~ jamestipping$ kextstat -l |grep  osxfuse
  174    0 0xffffff7f84cfc000 0x17000    0x17000    com.box.filesystems.osxfuse (403.11.2) 0F663263-16BA-340B-843A-9DE80C698E81 <8 6 5 3 1>

**Comment by 94gwz** [comment]
hello i have the same issue, how had you solved it ?

**Comment by troubleatmill** [comment]
Hi
I booted into recovery mode as per here:

https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection

Rebooted and approved OSXFuse and then re-enabled SIP.
