### ISSUE TITLE
Kernel panic when reading many files sequentially in Go

### ISSUE THREAD

**Issue by alltom** [osxfuse/osxfuse#878]
I have 735 text files in an [Upspin](https://upspin.io) directory, 408kB total. I can `grep foo *` and `cat *` without issue, but a simple Go loop like this kernel panics before it can finish, nearly every time, even if I sleep between reads:

```go
for _, path := range paths {
	os.ReadFile(path)
}
```

[The kernel panic trace is here](https://drive.google.com/file/d/1xls-Lo_YKq5XoMBAn2srZrI-nstEBRWn/view). The headline is "panic(cpu 4 caller 0xfffffe002120d808): lck_mtx_unlock(): Attempt to release lock not owned by thread (0xfffffe2999d8c060) @locks_arm.c:1687" and later the line, "Kernel Extensions in backtrace: io.macfuse.filesystems.macfuse(2084.20)[66ADEEBF-34FC-3531-B0CB-3DC4811653DC]@0xfffffe0020694f20→0xfffffe00206a772b".

I'm using macFUSE 4.2.4 on macOS 12.2 on an Apple M1 and compiling the Go program with Go 1.17.6, but I've had this problem with every version since before the macFUSE rename, and used to use an Intel MacBook Pro.

In case it helps, [I posted about this on the Upspin mailing list](https://groups.google.com/g/upspin/c/bLYMpwQ1HN4/m/vtym2OUkAgAJ) first and Russ Cox replied, "the Go loop differs from grep * and cat * in that it probably does end up issuing the system calls from a variety of different (user process) threads rather than a single one, and perhaps macfuse assumes the reads or the open and close come from the same thread."

**Comment by bfleischer** [comment]
Thanks for the bug report. Can you post an Intel panic log and the exact repro steps including the source code and an example directory of text files?

**Comment by alltom** [comment]
I don't have an Intel Mac any more, but I've created a public Upspin directory that reproduces the error for me:

* cd into tom@alltom.com/macfuseissue878
* `go run main.go`

There are 735 small text files with identical contents numbered 1 through 735. There's an Access file that makes the directory public. Then there's main.go with the contents:

```go
package main

import (
	"os"
	"log"
)

func main() {
	files, err := os.ReadDir(".")
	if err != nil {
		log.Fatalf("could not list files: %v", err)
	}

	for _, file := range files {
		os.ReadFile(file.Name())
	}
}
```

**Comment by bfleischer** [comment]
I've tried taking another shot at this. It took several attempts until I was able to create an upspin account. But now upspin claims macFUSE is not installed, which is not true. Which version of upspin are you using?

As far as I can tell, there is no documentation from Apple on how to symbolicate M1 kernel panic logs. It does not work the same way as symbolicating Intel panic logs. Unfortunately, this makes the M1 panic log undecipherable. 

To fix the panic, I need an Intel panic log or I need to be able to reproduce the issue myself.

**Comment by bfleischer** [comment]
I managed to mount upspin, with an old version of macFUSE. The upspin build from the official website does not seem to support macFUSE version 4. Now I'm getting a permission denied error when trying to access your directory. I'm stuck.

```
% cd up/tom@alltom.com/macfuseissue878
% ls -la
ls: .: Permission denied
````

**Comment by bfleischer** [comment]
I'm pretty sure I found the race condition that is responsible for the crashes. The new 4.2.5 release contains  a fix. However, I'm not able to verify this since I'm unable to make Upspin work. For lack of feedback, I'm going to close the ticket.

**Comment by alltom** [comment]
I can't wait to try it. Thanks so much for perservering on this. I wish I could help more. [I asked on the Upspin list if anyone could contribute Intel logs](https://groups.google.com/g/upspin/c/bLYMpwQ1HN4/m/Tb5HrGRdAAAJ), but it seems like the active users are probably also on Apple silicon already.

Just FYI, Upspin requires some patches to account for the rename to macFUSE, and the deprecation of the "old style" mount process, and it's complicated since the supporting FUSE library deleted its macOS code paths a while back. (Yay engineering…) My patches are in [this thread](https://groups.google.com/g/upspin/c/8C2yLzWguqE/m/tEx2EzrDBAAJ), but it looks like [it's starting to be integrated](https://groups.google.com/g/upspin/c/Md1YavXXDqY/m/16RD_dKGBQAJ).

**Comment by alltom** [comment]
My directory really is just files named "1" through "735" each containing "All work and no play makes Jack a dull boy", so even though it appears I set up my shared directory incorrectly, you can probably reproduce easily now that Upspin runs. :)
