### ISSUE TITLE
mv from gnuutils doesnt work on a mounted file system.

### ISSUE THREAD

**Issue by tomdvies** [osxfuse/osxfuse#881]
I get the error
`mv: cannot move 'filename1' to 'filename2': Function not implemented`
when using mv from gnuutils on a mounted filesystem, but if i use the stock mv it works fine. I'm unsure if this issue belongs here or on the gnutils issue tracker.

**Comment by bfleischer** [comment]
Please raise this issue with the coreutils/gnulib team. It seems they are calling a file system operation that is not supported by the macFUSE file system you are using. I took a brief look at the relevant coreutils and gnulib code and I think the operation might be renameatx_np(). Looks like there have been some changes to the relevant gnulib code recently. It might be worth making sure you are already using the latest version before raising the issue.
