### ISSUE TITLE
I'm a noob I guess 🤦‍♀️

### ISSUE THREAD

**Issue by murriiot** [osxfuse/osxfuse#885]
==> Installing Cask macfuse
==> Running installer for macfuse; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is macFUSE
installer: Upgrading at base path /
installer: The upgrade was successful.
==> Changing ownership of paths required by macfuse; your password may be necessary.
🍺  macfuse was successfully installed!
joel@iMac manomano-sf % brew upgrade
==> Upgrading 1 outdated package:
ntfs-3g 2017.3.23_3 -> 2021.8.22
Error: ntfs-3g has been disabled because it requires closed-source macFUSE!

**Comment by bfleischer** [comment]
For a workaround see https://github.com/osxfuse/osxfuse/issues/818. Feel free to raise this issue with the Homebrew team.
