### ISSUE TITLE
NO effect on Mac OS monterey 12.1

### ISSUE THREAD

**Issue by flodetan** [osxfuse/osxfuse#886]
i tried to install V 4.2.5 and v 4.3.1,  i still can not Write files to NTFS disk,  read from NTFS disk no problem.

OS: mac os monterey 12.1
software:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/3078244/167640170-10d922b7-b479-4184-92f3-aee5028d5eaf.png">

when i create a file in NTFS disk, it shows error:  create file failed becuase  MacintosHD is read-only file system.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/3078244/167640310-f1244d26-5e44-4eb2-8d5b-1e8bc3caeeaf.png">

**Comment by bfleischer** [comment]
macFUSE is a framework for building file systems. NTFS-3G is such a file system for reading and writing NTFS volumes. On macOS, NTFS-3G relies on macFUSE. So you would need to install NTFS-3G and macFUSE to mount NTFS volumes with support for writing files. This is a complicated set up and beyond the scope of the macFUSE project and this issue tracker.
 
Please note that NTFS-3G and macFUSE are independent projects. Should you run into NTFS-3G related issues, please raise the issue with the NTFS-3G team.
