### ISSUE TITLE
Remain stable after sleep/standby/wake or ssh connection termination. Or aid situation with auto unmount/remount for remote filesystems

### ISSUE THREAD

**Issue by porg** [osxfuse/osxfuse#889]
## Reproduction 1
1) Mount remote filesystem via macFUSE — In my case sshfs.
2) Put Mac to sleep — In my case via System Menu (Apple Symbol) > Sleep
3) Wake it shortly later (8min) — I can confirm it indeed slept with `pmset -g log`
```
2022-05-12 18:26:00 +0200 Sleep                 Entering Sleep state due to 'Software Sleep pid=163': Using AC (Charge:100%) 504 secs  
2022-05-12 18:34:24 +0200 Wake                  Wake from Normal Sleep [CDNVA] : due to XHC1/HID Activity Using AC (Charge:100%)
```
- **Expected**: You can continue browsing the remote webspace in Finder or in Terminal.
- **Actual**: It works that way.

## Reproduction 2
- Ad 3) Sleep longer (hours) And then wake.
- **Actual:** My Mac is only half responsive. Most apps still react. But apps with access to mounted volume like Finder or text editors hang. After 2-3min or so (a timeout?) the sshfs network volume disappears in the Finder and the apps are fully responsive again.

## Observations / Suspicions
- #850 neutrally observes "stops working after running the system for some time"
- #842 , #883 suspect specifically sleep/standby of your Mac, which happens after a certain longer time, but maybe this is just a correlation but not a causation?
- Looking at my reproduction #1 and #2 the most plausible root cause is rather the termination of the ssh connection #45, which happens to also kick in only after a certain longer time.

## Another fact: macFUSE does not publish any "stay awake assertions"
as other similar background processes do

```
$ pmset -g assertions

Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    0
   PreventSystemSleep             0
   ExternalMedia                  1
   PreventUserIdleSystemSleep     0
   NetworkClientActive            0
Listed by owning process:
   pid 101(powerd): [0x0000002100088002] 01:09:03 ExternalMedia named: "com.apple.powermanagement.externalmediamounted"  
   pid 161(WindowServer): [0x0000006800098161] 00:00:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle serviceID:10000035c name:AppleEmbeddedKeyboa product:Apple Internal Keyb eventType:3"  
	Timeout will fire in 240 secs Action=TimeoutActionRelease
No kernel assertions.
Idle sleep preventers: IODisplayWrangler
```

- No entry by macFUSE of SSHFS.

# Desired Fixes or Remedies

Sorted by most desired first:
1. macFUSE seamlessly supports to recover from wake after sleep or standby or ssh connection terminations.
2. If recovery from sleep/wake is technically not feasible (in the foreseeable future) it behaves macOS standard compliant: As long as a remote network volume is mounted it publishes an assertion to the OS to stay awake in the correct assertion category.
3. If offers a mechanism to automatically unmount on sleep and remount on wake. Even if sleep/standby/wake is not the root cause but rather the SSH connection termination (See #45) it could indirectly still remedy the situation, if standby happens before the ssh-connection-termination. Or macFUSE / sshfs could introduce its own option `unmount-remount-connection-after=numberInSeconds` independent from the Mac's sleep/standby timers.

**Comment by bfleischer** [comment]
A new SSHFS build is available on https://macfuse.io. Therefore, I'm closing this issue.
