### ISSUE TITLE
Why did the volume label name become like this?

### ISSUE THREAD

**Issue by nufeng1999** [osxfuse/osxfuse#890]
Why did the volume label name become like this?  

![https://github.com/nufeng1999/imgs/blob/main/img/DC0F0B07BD1739AAC17B6B323D1016D0.png?raw=true](https://github.com/nufeng1999/imgs/blob/main/img/DC0F0B07BD1739AAC17B6B323D1016D0.png?raw=true)

**Comment by arcenik** [comment]
The answer is: `-o volname=TheName` (see https://github.com/macfuse/macfuse/wiki/Mount-Options#volname)
