### ISSUE TITLE
XFS

### ISSUE THREAD

**Issue by juanpc2018** [osxfuse/osxfuse#891]
Having R&W support for XFS is very important...
Large 18TB drives dont like Ext4, complain making weird noises, Non-stop.
Havent tested Btrfs.
NTFS needs constant defrag, Not used in Windows Server.
ExFAT has very bad support in Linux, also feels weird/slow.
Free NTFS driver for Linux does Not like large 18TB drives.
HFS+ was nice for OSX, but... Wiki claims does Not have Checksums?
HFS+ free driver for Linux is incomplete.
APFS feels faster than HFS+ in OSX.

Havent tested Paragon paid drivers 
APFS/HFS+/NTFS for Windows, OSX and Linux.

Ext2Fsb 0.69 software for Windows, has a severe incompatibility problem with Newer Ext4 64-Bit headers.
0.70 fork has slow development.

All my test indicate:
XFS is the Future.
Ext4 Game Over.
HFS+ Game Over.
APFS also the Future.
NTFS Game Over.
Btrfs Unknown.

**Comment by bfleischer** [comment]
What exactly is this ticket about? Are you arguing for someone to implement XFS as a FUSE file system? This would be beyond the scope of the macFUSE project. 

However, as far as I can tell there is a project named fuse-xfs which uses macFUSE and supports reading XFS volumes.
