### ISSUE TITLE
macFUSE won't install on unsupported Mac (MBP 2011, Monterey)

### ISSUE THREAD

**Issue by makramakramakra** [osxfuse/osxfuse#892]
Hi Benjamin,

thanks for the great work you do! Cryptomator in combination with macFUSE works great - on almost all of our Macs. More precisely:
MB10,1 (2017), m3, Mon; MBA6,1 (2014), i5, Big Sur; MBP10,2 (2012), i5, Mon OCLP; MBP9,1 (Mid 2012), i7, Mon OCLP; iMac13,1 (Late 2012), i5, Big Sur OCLP; MBP6,2 (Early 2010), i5, Big Sur OCLP; MB6,1 (Late 2009), Big Sur OCLP; MB5,1 (Late 2008), Big Sur OCLP (OCLP= OpenCore Legacy Patcher)

On all of these machines, I have no issues with macFUSE. Neither MBP8,1 (Late 2011), i5, Mon OCLP did act up - until macOS 12.4. Now Cryptomator can't open the vaults anymore. And the macFUSE preference pane shows: "FUSE does not appear to be installed. Version available to install: 4.2.5." (which I had installed again using the installer. There I get the message, that everything went well. But obviously it didn't.)

The MBP8,1 is somewhat special in this line, because it is the only Mac that doesn't support metal and has Monterey installed. That could be the reason. Then I'll dump it (at least for the purpose I've been using it for). But maybe there's something else to it?

Martin

![Bildschirmfoto 2022-05-23 um 23 06 14](https://user-images.githubusercontent.com/96476329/170870368-4024d49b-953a-409e-80ea-34d3ea579b44.png)

**Comment by bfleischer** [comment]
macFUSE does not rely on Metal. Not sure why it does not work for you. The preference pane calls `/Library/PreferencePanes/macFUSE.prefPane/Contents/MacOS/autoinstall-macfuse-core -v --print` to determine wether macFUSE is installed or not. What does the command return in your case?

Did you try running the uninstaller from the macFUSE disk image in the Extras folder and then reinstalling macFUSE?

**Comment by makramakramakra** [comment]
Thanks for your answer. Right now, the MBP isn't here. And: I reverted it to Big Sur. ASAP I'll install a Monterey volume with macFUSE on it and report what I get.

And yes: I had used the uninstaller.

**Comment by makramakramakra** [comment]
I finally got hold of the MBP 8,1 again, installed Monterey and macFUSE from scratch. Result: Works flawlessly. I have no clue, what had gone wrong.

Thanks again for your efforts!

**Comment by bfleischer** [comment]
I'm grad everything works for you now.
