### ISSUE TITLE
Updated needed to work on macOS 13

### ISSUE THREAD

**Issue by aaronp613** [osxfuse/osxfuse#895]
Unsupported macOS Version: "The installed version of macFUSE is too old for the operating system. Please upgrade your macFUSE installation to one that is compatible with the currently running version of macOS."

**Comment by NewAlexandria** [comment]
Thanks, came here for this.  Eager to trial OSX 13/ventura features, but relying on `kbfs` still.  

@bfleischer if the repo sponsors are not active, and thus you're not active on this, can you let us know here please?

**Comment by bfleischer** [comment]
Working on it. Initial tests are promising. Give me a few days

**Comment by iMonZ** [comment]
> Working on it. Initial tests are promising. Give me a few days

Sounds nice!

**Comment by dev-coco** [comment]
Is there any progress?

**Comment by bfleischer** [comment]
The newly released 4.4.0 build comes with experimental support for macOS 13.

**Comment by nirmit** [comment]
So far, worked without issues.  Thank you, @bfleischer!
