### ISSUE TITLE
Feature request/bug? Case in MacOS directories

### ISSUE THREAD

**Issue by DarrenPIngram** [osxfuse/osxfuse#896]
Hi. 

Macfuse mounted to Dropbox via rclone. Latest version of both apps.

If (bold shows the change)

National-Press-Club-Address Volodymyr Shalkivskyi - Ukrainian Embassy'**S** Charge D'Affaires

exists in a directory you cannot rename it to 

National-Press-Club-Address Volodymyr Shalkivskyi - Ukrainian Embassy's Charge D'Affaires

As it claims a file exists. So you have to add a space, let it rename, and then take away the space and add the correction.

I am not sure where the issue lies, but if it is within OSX fuse it would be good to be fixed if possible.

**Comment by Scvairy** [comment]
Is you file system case-sensitive?
Mine is not and I have no problem with mounted via macfuse volumes.

**Comment by bfleischer** [comment]
@DarrenPIngram macFUSE supports case-sensitive and case-insisentiie file systems. The issue you are running into is most likely caused by the actual file system implementation you are using. The file system is probably declaring to be case-sensitive, although it is not. This would result in the issue you are describing.

**Comment by DarrenPIngram** [comment]
Ah, understand. I hate Apple's AFPS from a trial on my desktop. I think I need to do a full reinstall to rid my laptop of their innovation.  


—- 
Via iPad. Hopefully with not too many typos.

**Comment by DarrenPIngram** [comment]
Must say I can't be sure. APFS Encrypted according to Disk Utility.

However I've just done a test on a local directory (desktop) and I could
rename say Test.txt to test.txt without any error.

I can't say I recall the issue on my office computer, but I've been using
it on my laptop for several weeks (where the issue was noticed) due to my
long-term illness making me sleep more (so easier to be in the house).
