### ISSUE TITLE
Feature request? Cache

### ISSUE THREAD

**Issue by DarrenPIngram** [osxfuse/osxfuse#897]
Would it be possible for osxfuse to create a cache locally of directory information?

Situation. If the connection is lost or the mount stops when restarting osxfuse remembers "nothing" and it takes time to rebuild, when accessed, large directory trees etc. Even if it could remember from the cache and update from that, this would be a nice little time saver.

Thanks!

**Comment by bfleischer** [comment]
The sort of caching you are describing would need to be implemented in the actual file system, not macFUSE. macFUSE does not have enough information about the context of your data to make smart caching decisions. Have you tried raising the issue with the file system developer?

**Comment by DarrenPIngram** [comment]
Thanks. It was worth asking. I doubt Apple would bother and then they'd cripple it somehow & only give to the latest version.




—- 
Via iPad. Hopefully with not too many typos.
