### ISSUE TITLE
macfuse 4.3.1 hangs on python mmap call on Monterey

### ISSUE THREAD

**Issue by BrianLovelace128** [osxfuse/osxfuse#903]
We use macfuse and interact with the filesystem from python and have found that on Monterey with macfuse 4.3.1 we run into a hard hang when writing to a memory mapped file using the python mmap module. I've pasted the minimal python test case below. The I/O appears to be in an uninterruptable state as `kill -9` does not terminate the process. Additionally, any other interaction with the broken mount causes the same hang (ex, `ls /path/to/mount`, or just `mount` - running `mount` will list the macfuse mount then hang).

We've reproduced the issue on 4.3.1 and 4.4.0. We've tested 4.2.5 and 4.3.0 and confirmed that this issue does not occur on those versions. For now we are using 4.3.0 as a workaround.

The python test:

```
import os
import mmap

def test_mmap():
        fname = "simple_mmap_file.txt"
        mount_path = os.path.join("path/to/mount", fname)

        orig_val = b"Hello, Earthlings!\n" * 100
        repl_val = b"Hiya, humans!!!\n"

        with open(mount_path, "wb") as f:
            f.write(orig_val)

        with open(mount_path, "rb+") as f:
            with mmap.mmap(f.fileno(), 0) as mm:
                mm.write(repl_val)  # <-- This is where it hangs
```

**Comment by bfleischer** [comment]
This issue is fixed in macFUSE 4.4.1.
