### ISSUE TITLE
macOS Monterey how to install osxfuse

### ISSUE THREAD

**Issue by nioshield** [osxfuse/osxfuse#906]
# max os  version
macOS Monterey
12.4 

# installation error
installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.

**Comment by bfleischer** [comment]
The version of macFUSE you are trying to install is not compatible with macOS 12. Download the latest version and try again.

**Comment by nioshield** [comment]
@bfleischer  I use brew install osxfuse report  this error,what is the difference between macfuse and osxfuse ?

**Comment by bfleischer** [comment]
osxfuse is the old name for FUSE on macOS, macFUSE is the new name. For details see https://github.com/macfuse/macfuse/wiki/History. 

Homebrew is not shipping the latest version of macFUSE. You can download the latest version from https://macfuse.io.
