### ISSUE TITLE
SOLVED : Impossible to validate in pref pane "Benjamin Fleischer", it never appears in security pref pane

### ISSUE THREAD

**Issue by 94gwz** [osxfuse/osxfuse#908]
installing Macfuse on 10.14.6

When i install the app, i have the followinf message :
"Systems Extension blocked
The system extension required for mounting macFUSE volumes could not be loaded.
Please open the Security & Privacy System Preferences pane, go to the General preferences and allow loading system software from developer "Benjamin Fleischer". A restart might be required before the system extension can be loaded."

But "Benjamin Fleischer" never appears in General / Security & Privacy System Preferences pane

I try few times with restarted the mac and i used the uninstaller each time to remove properly the app, not works

Previously it works perfectly with the release 3.10.14, it's when i want to update in the last version, I have the issue

**Comment by festus77** [comment]
#94gwz - did you get this figured out? Having same issue.

MacOS 12.5 (Macbook Pro - m1)
macFUSE 4.4.0
VeraCrypt 1.25.9

Thanks,
festus

**Comment by 94gwz** [comment]
Hello, i solved the issue with the time machine back-up, I revert to Fuse 3.10.4 already, previously, installed & signed. 
And now it works as before.

**Comment by itefect** [comment]
I have the same problem.
Someone is able to give some hint how to fix it or debug the issue locally?

ps. I'm this-kind-of who doesn't have backups...

**Comment by NewAlexandria** [comment]
@itefect you can pull data the long way: even without the FS integration, you can use `keybase fs cp ....` to manage access to files/data

**Comment by 94gwz** [comment]
Hello, i solved the issue with the time machine back-up, I revert to Fuse 3.10.4 already, previously, installed & signed.
And now it works as before.

**Comment by charman2** [comment]
@itefect I have the same problem. @NewAlexandria could you expand on your suggestion?

**Comment by 94gwz** [comment]
Hello
The topic may be due to the SIP
Try this :
1. Uninstall macFUSE
2. Reboot into Recovery mode and in Terminal do the command csrutil disable
3. Reboot into macOS and install macFUSE or OSXFUSE.
4. Enable extension in Security & Privacy
(5. don't forget to csrutil enable if you did that step)

But be carreful, the SIP protect the system, disable it supposed to be very prudent when you Install a soft and be sure about the source of download.

Envoyé par myMail pour iOS

mercredi 19 octobre 2022 à 20:19 +0200 de ***@***.*** ***@***.***>:

**Comment by charman2** [comment]
This worked! Thanks. macFUSE had been installed as part of something else, so I wasn't even aware it was the problem until I saw this thread. Much appreciated.
