### ISSUE TITLE
Cannot Install Mac OS On SSD Disk After Trying Installation

### ISSUE THREAD

**Issue by joyoustr** [osxfuse/osxfuse#909]
Apart from High Sierra or Windows as I try, Big Sur and Monterey can not be installed on a brand-new SSD disk. It repeats trying to install MacOs while telling "29 minutes remaining". It starts over and over.

These are the commands that I use while trying to install:

_/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew cask install osxfuse
brew install ntfs-3g
csrutil disable
csrutil authenticated-root status
sudo mount -uw /
        sudo mv /sbin/mount_ntfs /sbin/mount_ntfs.original
        sudo ln -s /usr/local/sbin/mount_ntfs /sbin/mount_ntfs
sudo bless --folder MOUNT_PATH/System/Library/CoreServices --bootefi --create-snapshot

Diskpart(windows) and dd(macos) commands didn't help. Samsung magician secure erase didn't help too. MY SSD is samsung 970 evo plus. Thanks for help.

**Comment by bfleischer** [comment]
I'm not sure that I understand what you are trying to do. You can't install macOS on a NTFS volume. And you shouldn't need macFUSE to install macOS on an external SSD. Can you explain what you are trying to accomplish?

**Comment by bfleischer** [comment]
Closed for no feedback.
