### ISSUE TITLE
kernel panic in 12.4 with osxfuse 2.6.0 and ntfs-3g

### ISSUE THREAD

**Issue by njnevin** [osxfuse/osxfuse#91]
Hi. I am seeing a reproducible kernel panic when mounting and unmounting a NTFS file-system using ntfs-3g. I have seen a similar (probably the same) panic with osxfuse 2.5.4. Here is the crash log. Please let me know if there is any more information I can provide.

Fri Jul 12 14:36:16 2013
panic(cpu 0 caller 0xffffff8024ead456): trying to interlock destroyed mutex (0xffffff80305566a0)
Backtrace (CPU 0), Frame : Return Address
0xffffff80d7303cb0 : 0xffffff8024e1d626 
0xffffff80d7303d20 : 0xffffff8024ead456 
0xffffff80d7303d30 : 0xffffff802514df7f 
0xffffff80d7303d80 : 0xffffff8025150832 
0xffffff80d7303da0 : 0xffffff802514c60c 
0xffffff80d7303e10 : 0xffffff802514cb86 
0xffffff80d7303e50 : 0xffffff8025156a39 
0xffffff80d7303ec0 : 0xffffff8024e3a0d9 
0xffffff80d7303ef0 : 0xffffff8024e3cc38 
0xffffff80d7303f20 : 0xffffff8024e3caae 
0xffffff80d7303f50 : 0xffffff8024e1b70d 
0xffffff80d7303f90 : 0xffffff8024eb8c63 
0xffffff80d7303fb0 : 0xffffff8024ece14c 

BSD process name corresponding to current thread: ntfs-3g

Mac OS version:
12E55

Kernel version:
Darwin Kernel Version 12.4.0: Wed May  1 17:57:12 PDT 2013; root:xnu-2050.24.15~1/RELEASE_X86_64
Kernel UUID: 896CB1E3-AB79-3DF1-B595-549DFFDF3D36
Kernel slide:     0x0000000024c00000
Kernel text base: 0xffffff8024e00000
System model name: MacBookAir5,2 (Mac-2E6FAB96566FE58C)

System uptime in nanoseconds: 533939119478
last loaded kext at 245978074217: com.apple.filesystems.msdosfs 1.8.1 (addr 0xffffff7fa6aa1000, size 65536)
last unloaded kext at 306135817229: com.apple.filesystems.msdosfs       1.8.1 (addr 0xffffff7fa6aa1000, size 57344)
loaded kexts:
com.github.osxfuse.filesystems.osxfusefs        2.6.0
org.virtualbox.kext.VBoxNetAdp  4.2.14
org.virtualbox.kext.VBoxNetFlt  4.2.14
org.virtualbox.kext.VBoxUSB     4.2.14
org.virtualbox.kext.VBoxDrv     4.2.14
com.apple.filesystems.smbfs     1.8.4
com.apple.driver.AudioAUUC      1.60
com.apple.iokit.IOBluetoothSerialManager        4.1.4f2
com.apple.filesystems.autofs    3.0
com.apple.driver.X86PlatformShim        1.0.0
com.apple.driver.AGPM   100.12.87
com.apple.driver.ApplePlatformEnabler   2.0.6d1
com.apple.driver.AppleMikeyHIDDriver    122
com.apple.iokit.IOUserEthernet  1.0.0d1
com.apple.driver.AppleUpstreamUserClient        3.5.10
com.apple.driver.AppleSMCLMU    2.0.3d0
com.apple.iokit.BroadcomBluetoothHCIControllerUSBTransport      4.1.4f2
com.apple.Dont_Steal_Mac_OS_X   7.0.0
com.apple.driver.ApplePolicyControl     3.4.5
com.apple.driver.AppleHDA       2.3.7fc4
com.apple.driver.AppleSMCPDRC   1.0.0
com.apple.driver.AppleMikeyDriver       2.3.7fc4
com.apple.driver.AppleLPC       1.6.0
com.apple.driver.AppleBacklight 170.2.5
com.apple.driver.AppleMCCSControl       1.1.11
com.apple.driver.AppleIntelHD4000Graphics       8.1.2
com.apple.driver.AppleIntelFramebufferCapri     8.1.2
com.apple.driver.AppleUSBTCButtons      237.1
com.apple.driver.AppleUSBTCKeyboard     237.1
com.apple.driver.AppleUSBCardReader     3.1.7
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless     1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0d1
com.apple.BootCache     34
com.apple.driver.XsanFilter     404
com.apple.iokit.IOAHCIBlockStorage      2.3.1
com.apple.driver.AppleUSBHub    5.5.5
com.apple.driver.AirPort.Brcm4331       615.20.17
com.apple.driver.AppleAHCIPort  2.5.2
com.apple.driver.AppleUSBEHCI   5.5.0
com.apple.driver.AppleUSBXHCI   5.6.0
com.apple.driver.AppleEFINVRAM  1.7
com.apple.driver.AppleSmartBatteryManager       161.0.0
com.apple.driver.AppleRTC       1.5
com.apple.driver.AppleACPIButtons       1.7
com.apple.driver.AppleHPET      1.8
com.apple.driver.AppleSMBIOS    1.9
com.apple.driver.AppleACPIEC    1.7
com.apple.driver.AppleAPIC      1.6
com.apple.driver.AppleIntelCPUPowerManagementClient     196.0.0
com.apple.nke.applicationfirewall       4.0.39
com.apple.security.quarantine   2.1
com.apple.driver.AppleIntelCPUPowerManagement   196.0.0
com.apple.iokit.IOSerialFamily  10.0.6
com.apple.kext.triggers 1.0
com.apple.iokit.IOSurface       86.0.4
com.apple.iokit.AppleBluetoothHCIControllerUSBTransport 4.1.4f2
com.apple.iokit.IOBluetoothFamily       4.1.4f2
com.apple.driver.DspFuncLib     2.3.7fc4
com.apple.iokit.IOAudioFamily   1.8.9fc11
com.apple.kext.OSvKernDSPLib    1.6
com.apple.driver.AppleHDAController     2.3.7fc4
com.apple.iokit.IOHDAFamily     2.3.7fc4
com.apple.driver.AppleSMBusPCI  1.0.11d0
com.apple.driver.X86PlatformPlugin      1.0.0
com.apple.driver.AppleSMC       3.1.4d2
com.apple.driver.IOPlatformPluginFamily 5.3.0d51
com.apple.driver.AppleGraphicsControl   3.4.5
com.apple.driver.AppleBacklightExpert   1.0.4
com.apple.driver.AppleSMBusController   1.0.11d0
com.apple.iokit.IOAcceleratorFamily     74.5.1
com.apple.iokit.IONDRVSupport   2.3.7
com.apple.iokit.IOGraphicsFamily        2.3.7
com.apple.driver.AppleUSBMultitouch     237.3
com.apple.iokit.IOUSBHIDDriver  5.2.5
com.apple.iokit.IOSCSIBlockCommandsDevice       3.5.5
com.apple.iokit.IOUSBMassStorageClass   3.5.1
com.apple.iokit.IOSCSIArchitectureModelFamily   3.5.5
com.apple.driver.AppleThunderboltDPInAdapter    1.8.9
com.apple.driver.AppleThunderboltDPAdapterFamily        1.8.9
com.apple.driver.AppleThunderboltPCIDownAdapter 1.2.6
com.apple.driver.AppleUSBMergeNub       5.5.5
com.apple.driver.AppleUSBComposite      5.2.5
com.apple.driver.AppleThunderboltNHI    1.7.8
com.apple.iokit.IOThunderboltFamily     2.4.0
com.apple.iokit.IOUSBUserClient 5.5.5
com.apple.iokit.IO80211Family   530.4
com.apple.iokit.IONetworkingFamily      3.0
com.apple.iokit.IOAHCIFamily    2.3.1
com.apple.iokit.IOUSBFamily     5.6.0
com.apple.driver.AppleEFIRuntime        1.7
com.apple.iokit.IOHIDFamily     1.8.1
com.apple.iokit.IOSMBusFamily   1.1
com.apple.security.sandbox      220.3
com.apple.kext.AppleMatch       1.0.0d1
com.apple.security.TMSafetyNet  7
com.apple.driver.DiskImages     345
com.apple.iokit.IOStorageFamily 1.8
com.apple.driver.AppleKeyStore  28.21
com.apple.driver.AppleACPIPlatform      1.7
com.apple.iokit.IOPCIFamily     2.7.3
com.apple.iokit.IOACPIFamily    1.4
com.apple.kec.corecrypto        1.0

**Comment by bfleischer** [comment]
This ticket is really old, therefore I'm closing it. Feel free to re-open it if the issue happens again with the latest version of osxfuse.
