### ISSUE TITLE
Issue with modification time changes?

### ISSUE THREAD

**Issue by DarrenPIngram** [osxfuse/osxfuse#911]
Does MacFuse (latest version on MacOS 12.5) "take over" elements of the local drive insofar as its interaction with the underlying data? 

Trying to track down a strange problem with network drive storage (rclone, mounted via MacFuse) but have not reached a "pointing fingers" element.

Going back to first principles. Looked at a file downloaded (Locally) today. The modified time does not change in Finder (get info) but it does show in the terminal with stat

`16777220 8648623055 -rw-r--r-- 1 di staff 0 273507 "Aug 14 15:47:55 2022" "Aug 14 11:52:34 2022" "Aug 14 15:47:36 2022" "Aug 14 11:52:34 2022" 4096 536 0 test.name
`
From get-info in Finder etc : Modified: 14. August 2022 at 11.52

I also replicate it, e.g. download a file, rename the file (so it entirely changes the file metadata) and it still shows in the Finder the date of yesterday, rather than today.

Such a problem is creating issues with other scripts, but I do not know where the apparent logjam is. Now I know Apple's Finder is legendary (sic) but it would be good to rule out other elements before I try and get them to understand the issue, not that a fix may rush I guess...

**Comment by bfleischer** [comment]
macFUSE does not interfere with files outside of macFUSE volumes. Renaming a file (on the macOS system volume) does not update its last modification date. This is the expected behavior since the file's content has not been modified.

**Comment by DarrenPIngram** [comment]
Presumably the same is with a mount within Macfuse?
E.g. you mount volume "dog" (rclone dropbox volume), copy a file to "dog"
from system drive (non Macfuse)? Same if you copy a file and then edit the
file name ?

I've since understood that on a system volume just editing the filename
does not change the file in itself (thus not changing modification time).
Is this the same within Macfuse?

**Comment by bfleischer** [comment]
> Is this the same within Macfuse?

Yes, at least it should be. I depends on the specific implementation of the file system (rclone in your case). macFUSE aims to behave exactly as the built-in Apple file systems.
