### ISSUE TITLE
Macfuse system extension fail issue

### ISSUE THREAD

**Issue by allenoper** [osxfuse/osxfuse#912]
Hi

Macfuse system extension(Benjamin Fleischer) fails in one of our MacBooks
If I reboot after allow system extension, tell them to reboot again
(system preference -> Benjamin Fleischer extension allow -> reboot -> system preference -> Benjamin Fleischer extension allow -> reboot...... repeat~~)
Help me

Environment
 - OS : MacOS Monterey 12.5 (Apple Intel T2 security chip) 
 - Macfuse : 4.4.0

How can I solve this?

![24375E76-85E8-4A78-9B40-717533AE4FDF](https://user-images.githubusercontent.com/111332253/184794595-a6d142ea-da8f-4711-ac93-e9dcbd35df7b.jpeg)
![CCA4C9B3-920F-4AAB-ACCB-A43EBA574B9B](https://user-images.githubusercontent.com/111332253/184794604-1215861d-8680-4608-968f-2cbe0909f942.jpeg)

![4155F0F6-56E6-4E7C-A7DA-D0270262F1DE](https://user-images.githubusercontent.com/111332253/184793961-a34cdd9b-84af-4d85-add1-b21c2eebfbf7.jpeg)

**Comment by bfleischer** [comment]
Did you check the logs with `kmutil log` right after trying to load the macFUSE kernel extension?

Did you try running `kmutil trigger-panic-medic --volume-root /Volumes/<YourVolumeName>` in recovery mode?

**Comment by xkenokabe** [comment]
It seems that you are using the wrong method to allow the system extension. See below for how to do it.
https://iboysoft.com/mac-data-recovery/enable-thirdparty-extension.html
