### ISSUE TITLE
GRUB won't compile while using macFuse on macOS 12.5.1

### ISSUE THREAD

**Issue by memegauste** [osxfuse/osxfuse#913]
Hey, I am not sure if this belong here, but I'm trying to compile GRUB from `GNU` project and I get this error:
```
ld: library not found for -losxfuse
collect2: error: ld returned 1 exit status
make[2]: *** [grub-mount] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I'm quite not sure where it's trying to find `osxfuse`, but when I call ` ls /usr/local/lib | grep fuse` I get this result:
```
libconfuse.2.dylib
libconfuse.a
libconfuse.dylib
libfuse.2.dylib
libfuse.dylib
libfuse.la
libosxfuse.2.dylib
libosxfuse_i64.2.dylib
```

So, I think the library is here but the linker can't find it.
I suppose this is easily fixable by doing symlinks - but I don't know which. Can you help?
Also I call `make` with these flags:

```
make CC=/usr/local/Cellar/gcc/12.1.0/bin/gcc-12 CFLAGS="-I/usr/local/Cellar/gettext/0.21/include -I/usr/local/Cellar/xz/5.2.6/include -I/usr/local/include/fuse" LDFLAGS="-L/usr/local/lib" -j13 -lmacfuse
```

Thanks in advance!

**Comment by bfleischer** [comment]
Looks like `LDFLAGS` are not passed to grub-mount build target. `libosxfuse.2.dylib` is a symlink pointing to `libfuse.2.dylib`. If ld were looking for libosxfuse in `/usr/local/lib`, it should work. It might be best to raise the issue with the GRUB team. I don't know anything about how their build process works.
