### ISSUE TITLE
macOS monterey 12.5.1 apple M1 chip with macFuse 4.4.1 mount and unmount happening immediately 

### ISSUE THREAD

**Issue by kondak3** [osxfuse/osxfuse#914]
We implemented macOS application using file system (https://github.com/osxfuse/filesystems). 
This one working fine without any issue in "Intel machines". 

> "Apple M1 chip machine" enabled kernel settings. After folder mount, immediately unmount happening.
> We used 4.4.0 and 4.4.1. But issue not resolved.

**Comment by bfleischer** [comment]
You need to provide more information. In case your file system is open source, provide a link to the repository. The [filesystems](https://github.com/osxfuse/filesystems) repository contains many different demo file systems. Which one did you base your file system on?

**Comment by kondak3** [comment]
We are using "LoopbackFS" in swift. Same code, based on swift version changed syntax and folder choosing dynamical.
This code working Intel machines. But Apple M1 chip machines observed mount and unmount happening immediately. 
Machine not responding few mins/seconds.

**Comment by bfleischer** [comment]
The latest version of the Loopback file systems can be found here: https://github.com/macfuse/demo

For me, the Swift version works perfectly fine on M1 Macs. There is no automatic unmounting. You might want to look into your modifications or build settings.

**Comment by kondak3** [comment]
`We changed all the mentioned build settings and framework. Single mount creation working.`

Added mount creation code in separate class.

Creating more than one mount. MountPath and rootPath passing dynamically. 

We are trying 1 to 10 mounts, after creating 3 or 4, 

> few mounts "automatically unmounting" and getting an error "fuse: writing device: socket is not connected".

machine is freezing few mins. system not responding.

mount folder, unmount time getting below error message.

> fuse: fuse_remove_signal_handlers: unknown session"

**Comment by bfleischer** [comment]
It's not recommended serving multiple file systems from the same process. Technically it's possible, but not recommended.

The issue you are running into is moste definitely caused by your modifications of the LoopbackFS demo app. Is this a commercial project?

**Comment by kondak3** [comment]
We are not using any commercial purpose. Let us if any feasibility to create more than one mount without any issues.

**Comment by bfleischer** [comment]
You might want to look into your memory management. Not retaining the GMUserFileSystem instances could lead to immediate unmount.

**Comment by kondak3** [comment]
We didn't retaining instance of GMUserFileSystem. Still we are facing auto unmount in Apple M1 and macOS 12.5.1

**Comment by kondak3** [comment]
The latest version of the Loopback (https://github.com/macfuse/demo) modified with multiple mounts.
https://github.com/kondak3/LoopbackFS-Swift

This Loopback working without fail in "macOS Monterey(v12.3) with Intel Core i5" and macFuse 4.4.1.

But same Loopback in "macOS Monterey(v12.5.1) with Apple M1 chip" and macFuse 4.4.1. Getting auto-unmount with error of `fuse: writing device: Socket is not connected`

**Comment by bfleischer** [comment]
Your demo code work fine for me on an M1 Mac mini with macFUSE 4.4.1. No errors whatsoever.

**Comment by kondak3** [comment]
Please run more than one time. Mine MacBook Pro, Apple M1 Pro.

**Comment by bfleischer** [comment]
Works fine for me. I ran the app and it mounted the volumes. Then I unmount the volumes terminated the app and ran it again.

**Comment by kondak3** [comment]
MacBook Pro, Apple M1 Pro, still we are facing the auto unmount issue.

**Comment by bfleischer** [comment]
Like I said, it works for me. I cannot reproduce the issue. I highly doubt this is a general issue or a bug in macFUSE. I'm sorry, but you'll need to investigate this on your end.

**Comment by bfleischer** [comment]
I'm closing this issue for lack of feedback.
