### ISSUE TITLE
Unable to use MacFuse Apple M1 macbook

### ISSUE THREAD

**Issue by fa8sanger** [osxfuse/osxfuse#916]
Thank you for MacFuse, I've been using it over years!
Unfortunately, after getting a new laptop running on Apple M1 chip, I am not able to use it anymore.
Whenever I try to mount a disk a window opens saying "System Extension Blocked" recommending to open Sys Prefs... 
However, in Sys Prefs there is no option to "allow loading system software from developer "Benjamin Fleischer"" or anything like that. It may be the strict security run in my institute, but even my institute's IT team haven't been able to make it work.
I am writing in hope this is a known issue and there's some trick to have MacFuse working again.

Many thanks

**Comment by bfleischer** [comment]
Please see https://github.com/macfuse/macfuse/wiki/Getting-Started. Did you enable support for third party kernel extensions in recovery mode?

**Comment by fa8sanger** [comment]
Many thanks for getting back to me. I didn't know about that possibility. I'll talk to our IT team and see if that helps. I hope so!
