### ISSUE TITLE
Why is this closed source?

### ISSUE THREAD

**Issue by robd003** [osxfuse/osxfuse#917]
Wouldn't it be more beneficial to have this as an open source project so that the community could submit bug fixes?

**Comment by bfleischer** [comment]
In an ideal world macFUSE would be open source and companies making a profit from it would be willing to support its continued development. But we are not living in an ideal world. Please see https://www.theregister.com/2019/12/16/fuse_macos_closed_source/ for a more detailed answer.

**Comment by fulldecent** [comment]
Duplicate of https://github.com/osxfuse/osxfuse/issues/590
