### ISSUE TITLE
OSXFuse not loading when booting from external drive

### ISSUE THREAD

**Issue by soleroitsolutionsltd** [osxfuse/osxfuse#918]
It would seem that it is not really a MacFuse issue as it is apparently not possible to load a KEXT when booting a Silicon system underOS 12.5.x from an external external disk (even with all integrity checks tuned off).
Is it so or is this specific to OSXFuse ?

**Comment by bfleischer** [comment]
I don't have an external Thunderbolt disk at hand, so I cannot try to reproduce the issue. It would be great if someone else with an external thunderbolt disk could give it a try.

But, there is nothing I could do from the macFUSE end to either allow or disallow loading the macFUSE kernel extension when booting macOS from an external volume. Since loading macFUSE works fine when booting from an internal volume, I think this is either a macOS issue/bug or a problem with your specific configuration.

**Comment by cloverenergy** [comment]
Apparently a macOS bug (or limitation, although not sure what it would help with).

**Comment by cloverenergy** [comment]
I can confirm that it is not possible to load a KEXT on an externaly booted system - no idea why Apple disallows it (assuming it is a concious decision, not "just" an oversight).

FWIW trying with TUXERA NTFS driver (commercial product, but they never had anyone report the issue so far):

/usr/bin/kmutil load --bundle-path /Library/Filesystems/tuxera_ntfs.fs/Contents/Resources/Support/10.9/tuxera_ntfs.kext

Error Domain=KMErrorDomain Code=71 "Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/6906A3FA-FFD7-47A6-B67D-0B01BFF18144/boot/FBED4A2C033E83C26B25A2143E7E192BEB36501D39D06B93DC6C2AA073ACE7FCDF870B3DC2D9CFD0598F03C24D9FAA1E/System/Library/Caches/com.apple.kernelcaches/kernelcache" UserInfo={NSLocalizedDescription=Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/6906A3FA-FFD7-47A6-B67D-0B01BFF18144/boot/FBED4A2C033E83C26B25A2143E7E192BEB36501D39D06B93DC6C2AA073ACE7FCDF870B3DC2D9CFD0598F03C24D9FAA1E/System/Library/Caches/com.apple.kernelcaches/kernelcache}

**Comment by bfleischer** [comment]
@cloverenergy Thanks for the update.

**Comment by fabrizziosoares** [comment]
> I can confirm that it is not possible to load a KEXT on an externaly booted system - no idea why Apple disallows it (assuming it is a concious decision, not "just" an oversight).
> 
> FWIW trying with TUXERA NTFS driver (commercial product, but they never had anyone report the issue so far):
> 
> /usr/bin/kmutil load --bundle-path /Library/Filesystems/tuxera_ntfs.fs/Contents/Resources/Support/10.9/tuxera_ntfs.kext
> 
> Error Domain=KMErrorDomain Code=71 "Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/6906A3FA-FFD7-47A6-B67D-0B01BFF18144/boot/FBED4A2C033E83C26B25A2143E7E192BEB36501D39D06B93DC6C2AA073ACE7FCDF870B3DC2D9CFD0598F03C24D9FAA1E/System/Library/Caches/com.apple.kernelcaches/kernelcache" UserInfo={NSLocalizedDescription=Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/6906A3FA-FFD7-47A6-B67D-0B01BFF18144/boot/FBED4A2C033E83C26B25A2143E7E192BEB36501D39D06B93DC6C2AA073ACE7FCDF870B3DC2D9CFD0598F03C24D9FAA1E/System/Library/Caches/com.apple.kernelcaches/kernelcache}

Does anyone have any update on this issue on Ventura?

**Comment by soleroitsolutionsltd** [comment]
My understanding this is an Apple "issue" but I have to date to get a definitive answer as of if this is deliberate (and if so what is the rationale, I personally don’t see it).

In any case KEXT are more or less on the way out so OSXFUSE will need to adapt

**Comment by tristan-k** [comment]
I'm facing the same issue on a m1 mac mini with Sonoma 14.5.

**Comment by gitLinan** [comment]
I'm facing the same issue on a m4 mac mini with Sequoia 15.6.
