### ISSUE TITLE
Possible to create a version that doesn't require disable SIP?

### ISSUE THREAD

**Issue by christhomas** [osxfuse/osxfuse#919]
I'm curious whether it's possible to create a version of this extension in the future that doesn't require to disable SIP. When I last did that after upgrading to my M1 macbook, I immediately ran into the "No administrator" problem and I had to do a full reinstall and file system clone across a SFTP connection because everything I tried to bring it back to normal failed. 

Is the reason we need to disable SIP because of the old kernel extensions and there is no replacement API for file system drivers? Or is there a replacement and the software just needs to be written? Or is it completely impossible and there is no information coming from Apple on how this can be done in the future and I'm just completely out of luck?

**Comment by NewAlexandria** [comment]
I know this was mentioned on one of the Issues or PRs already.  You don't need to disable SIP if you install it correctly.

**Comment by christhomas** [comment]
I was gonna say I'll go look for that, then I realised that the source is closed and I can't look any of it :P But do you know why SIP needed disabling in the first place?

**Comment by bfleischer** [comment]
> Is the reason we need to disable SIP because of the old kernel extensions and there is no replacement API for file system drivers?

There is no need to disable SIP. https://github.com/macfuse/macfuse/wiki/Getting-Started includes step-by-step instructions for installing macFUSE on Intel and Apple Silicon Macs.

Currently there is no non-kernel API for developing full-featured file systems for macOS.

> Or is there a replacement and the software just needs to be written? Or is it completely impossible and there is no information coming from Apple on how this can be done in the future and I'm just completely out of luck?

There is no official information from Apple when the new non-kernel API for developing full-featured file systems will be made available. macOS 12 already contains traces of this new API, but the API not yet available to the public.
