### ISSUE TITLE
Please renew PGP signing key and post link to it on a public key server

### ISSUE THREAD

**Issue by michaelowenfinoa** [osxfuse/osxfuse#920]
Hi,

I downloaded the latest version of OSXfuse and when I attempt to cryptographically verify it using the PGP signature provided, I am told that the signing key (which I had found a long time ago) has expired.

I am unable to locate a renewed signing key. Is it possible for you to renew your PGP signing key and post a link to the renewed key on a public key server?

Thanks

```
gpg --verify macfuse-4.4.1.sha256.sig 
gpg: assuming signed data in 'macfuse-4.4.1.sha256'
gpg: Signature made Do 18 Aug 2022 23:29:37 CEST
gpg:                using RSA key 135F164B411BAA1F4A4BCD37617A3461802608A1
gpg: Good signature from "Benjamin Fleischer <fleiben@gmail.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 0093 B21E F45D 6352 84F6  A147 53C9 18C1 A281 8875
     Subkey fingerprint: 135F 164B 411B AA1F 4A4B  CD37 617A 3461 8026 08A1
```

**Comment by bfleischer** [comment]
Please see https://github.com/osxfuse/osxfuse/issues/679

Key servers seem to disappear quite frequently, but you can download the key from  https://osxfuse.github.io/static/53C918C1A2818875.asc
