### ISSUE TITLE
Mac osxfuse not compatible with Ventura

### ISSUE THREAD

**Issue by vernodia** [osxfuse/osxfuse#921]
Hi,

Updated to OS Ventura and it says need to update osxfuse.  Where can I download the version that works with Ventura?  

Thanks

**Comment by adamcweiner** [comment]
I had the same issue but then upgraded to the latest stable release (`macFUSE 4.1.1`) and things seem to work now.

**Comment by tuobraun** [comment]
I have exactly the same issue on 4.1.1 saying that the version is no longer supported.

**Comment by bfleischer** [comment]
You can use the integrated update mechanism to upgrade to the latest version. To do so, open System Preferences and go to the macFUSE preference pane. Alternatively, you can download the latest release from the project's website https://macfuse.io or https://osxfuse.github.io. Support for Ventura has been added in version 4.4.0. The latest release, at the time of writing this, is version 4.4.1.
