### ISSUE TITLE
dislocker not compatible with macFUSE

### ISSUE THREAD

**Issue by superbonaci** [osxfuse/osxfuse#922]
I'm trying to run `dislocker` on macOS Ventura but unfortunately the brew.sh formula is not compatible with the closed source version:
[brew install dislocker on macOS Ventura](https://github.com/orgs/Homebrew/discussions/3844)

**Comment by bfleischer** [comment]
Not all components of macFUSE are open source. The Homebrew team decided not to ship macFUSE versions that contain closed source components. That's a political decision of the Homebrew team and there is nothing I can do about that.

If you are interested in the reasons why macFUSE is not completely open source, please see https://github.com/macfuse/macfuse/wiki/Open-Source-Status.
