### ISSUE TITLE
Does not work on macOS Ventura 13.0 !!!

### ISSUE THREAD

**Issue by 4bondarenko** [osxfuse/osxfuse#924]
Macfuse 4.4.1 stopped working after system update to macOS Ventura 13.0
System freezes on drive connection attempt
System: Macbook Air M1

**Comment by bfleischer** [comment]
Please provide more information about what you are trying to do and the actual file system you are using. Did you report the issue to the developer of the actual file system implementation you are trying to use? macFUSE 4.4.1 works fine for me on Ventura.

**Comment by 4bondarenko** [comment]
I tried to connect using version 4.2.1 and failed.
Error 
_Unsupported macOS Version
The installed version of macFUSE is too
old for the operating system. Please
upgrade your macFUSE installation to
one that is compatible with the currently
running version of macOS._
I updated MacFUSE to 4.4.1 restarted system and tried to connect via same SSH command 
sshfs -o allow_other,default_permissions user_name@ip:/var /local_folder
This command freezes my Macbook.

I solved this problem using new connection point at local system
This command solved my problem
sshfs -o allow_other,default_permissions user_name@ip:/var **/local_folder2**

So, Fuse could not connect drive to old local system path.

**Comment by S-AT** [comment]
I had a similar one. My mac did not freeze though, but Finder did.
Moving/renaming the mount points fixed the issue, but it doesn't look as a right way to fix it.

@4bondarenko , thanks for the hint.

**Comment by OliverDrechsler** [comment]
i had the same (were I used it within veracrypt), but I solved it with `brew uninstall macfuse` and installed it again with `brew install mccfuse`.
After a reboot it worked for me

**Comment by woncheol-kim** [comment]
I have a similar, but more complex one: 

At first, I had a system freeze problem after system update to Ventura.

Then I came to know that, for homebrew, macOS Ventura requires Xcode 14.1 which had not been released back then.
Anyway, I had tried to brew update macfuse which looked successful. But I had the same system freeze problem.

Now Apple finally released Xcode 14.1 - but after updating it, rclone does not mount any cloud storage of mine, without any error message.
I tried to brew uninstall and reinstall macfuse, but no use.

**Comment by hellmany** [comment]
Same problem, but when i solve it with different folder - very slow speed on reading writing on fuse partitions.

**Comment by bjnpck** [comment]
Same, pcloud virtual drive is not working anymore due to macfuse incompatibility with Ventura.

**Comment by bfleischer** [comment]
It seems a couple of things are getting mixed up here. First of all, macFUSE includes support for Ventura since version 4.4.0 which was released in June. If you are using an older version, I recommend updating to the latest macFUSE release. The recommended way of installing macFUSE is running the installer from https://macfuse.io.

@bojan-liquity pCloud uses a custom version of macFUSE. This means you will need to update pCloud to a version that adds  support for Ventura. Please raise this issue with pCloud's support team in case the latest pCloud release does not work for you on Ventura.

@4bondarenko Did you check the permissions and ownership of `/local_folder`? If the folder is not owned by the user who runs the sshfs command the mount will fail. This is a security mechanism enforced by macOS. When attempting to mount a volume on the same folder more than once in a row, make sure (between your mount attempts) that there are no lingering macFUSE mounts on the folder. You can use the `mount` command to check. 

The freezes are a bit of a different story. I don't think the SSHFS issues are specifically linked to Ventura. In my tests I was able to mount SSHFS volumes on Ventura under `/Volumes/sshfs` without any issues.

SSHFS mounts virtual volumes before establishing the ssh/sftp connection to the remote host. In case this connection fails for any reasons, SSHFS does not handle incoming file system requests properly. This can freeze Finder. Every mount triggers several file system requests from macOS system components, including Finder. macFUSE relays those file system operations to the sshfs process, which might not respond. macFUSE does not know whether sshfs is simply dealing with a slow network connection or if the connection could not be established at all. It would be better if SSHFS established the connection to the remote host first before mounting the volume. Unfortunately, the sshfs project has been unmaintained for some time and I don't have the resources to maintain both projects, macFUSE and sshfs.

**Comment by 4bondarenko** [comment]
Yes, I had all permissions on `/local_folder`
Folder was owned by user
I'm sure that problem happened because this folder was previously mounted in old Fuse version. 
Problem happened after system upgrade to MacOs Ventura withoout dismounting drive.
And nothing helped me. I tried to restart, dismount drive and so on. (drive looked mounted and command umount -f /Users/$user_name/Desktop/local_folder could not dismount it.
 
Problem was fixed deleting old local path and connecting to new local folder.
---
> @4bondarenko Did you check the permissions and ownership of `/local_folder`? If the folder is not owned by the user who runs the sshfs command the mount will fail. This is a security mechanism enforced by macOS. When attempting to mount a volume on the same folder more than once in a row, make sure (between your mount attempts) that there are no lingering macFUSE mounts on the folder. You can use the `mount` command to check.

**Comment by S-AT** [comment]
@bfleischer , huge thanks for the great job you've done!

@4bondarenko , better way to unmount is
`diskutil unmount force /Users/$user_name/Desktop/local_folder`

**Comment by bjnpck** [comment]
@bfleischer yeah, had just to update pcloud

**Comment by sdobbelaere** [comment]
Updated macfuse, reboot and all was fixed.

**Comment by michaelezra** [comment]
11/19/2022: The latest macfuse  + lates MacOS + latest Veracrypt = ad hoc reboot!
Would appreciate help!

**Comment by bfleischer** [comment]
@michaelezra Please post the corresponding panic log.

**Comment by michaelezra** [comment]
@bfleischer I am a bit new to Mac.. trying to figure out how. The last crash/restart happened yesterday. 
1. can the panic log be retried for the prior date (11/19)?
2. could you please point which steps should I follow to get it?
Thanks!

**Comment by michaelezra** [comment]
Is that it?
<img width="845" alt="image" src="https://user-images.githubusercontent.com/13765421/202906956-b460d480-b2e6-414c-b80b-3d78a505bbff.png">

**Comment by bfleischer** [comment]
Nope, open the Console App and check under Reports. There should be a crash with "Kernel" in its name.

**Comment by michaelezra** [comment]
Crash reports are empty:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/13765421/202907033-43d57a8c-50fb-4e3c-a1ed-027ffbbcacb9.png">

**Comment by michaelezra** [comment]
any of these?
<img width="994" alt="image" src="https://user-images.githubusercontent.com/13765421/202907398-5c9491a0-241b-4c72-9548-b59136bb2ce8.png">

**Comment by michaelezra** [comment]
after the crash and automatic restart there was a prompt to send report to Apple.
I scanned through the text and as I recall I saw macfuse mentioned.
Not sure how to retrieve that now, perhaps its in one of these logs?

**Comment by bfleischer** [comment]
The panic log should be available in the Console app. Panic logs have the ".panic" extension, not ".diag". They should be stored in `/Library/Logs/DiagnosticReports` or `/Library/Logs/DiagnosticReports/Retired`. Please note that this is the global Library folder, not the one in your home directory.

**Comment by michaelezra** [comment]
(zip was here)
does sharing these files here.. introduce any security risk to my device?
Please let me know when you get this, I will delete

**Comment by michaelezra** [comment]
also.. this issue appeared soon after I installed the latest version of macfuse-4.4.1
Version macfuse-4.2.4 was running without issues on MacOS 12.x

**Comment by bfleischer** [comment]
None of the three panics seems to be caused by macFUSE. 

The error strings of the three panics are:

* panic(cpu 1 caller 0xfffffe0014635a18): vm_page_reactivate_local: found vm_page_t(0xfffffe0027d6b350) with wrong cpuid @vm_resident.c:5691
*  panic(cpu 1 caller 0xfffffe00192e97e8): wire_count == 0, m = 0xfffffe002c2ab700, obj = 0xfffffe103a1c9100 @vm_pageout.c:7824
* panic(cpu 0 caller 0xfffffe002a4617e8): wire_count == 0, m = 0xfffffe0033ea2c10, obj = 0xfffffe10527e8500 @vm_pageout.c:7824

Two of the three panics blame `com.apple.driver.DiskImages`: 

```
      Kernel Extensions in backtrace:
         com.apple.driver.DiskImages(493.0)[731C12A5-42DC-3D06-9DFE-F987B6457AF1]@0xfffffe001b3bfff0->0xfffffe001b3ce7fb
            dependency: com.apple.iokit.IOStorageFamily(2.1)[B8A71D32-9627-33F5-83B1-EAC5148E8E72]@0xfffffe001b693b60->0xfffffe001b6b459f 
```

All three panics state that the macFUSE kernel extension was loaded at the time of the panic, but so are close to 200 other kernel extensions. The backtraces show that the code paths that lead to the panics does not involve any macFUSE code. All three panics seems to be related to the virtual memory subsystem. This might be a bug in macOS Ventura.

**Comment by michaelezra** [comment]
[bfleischer](https://github.com/bfleischer), thanks for looking into this. 
By any chance, do you see anything about Veracrypt, as this is what I use to mount the volume.
Other than that.. I submitted to this to Apple, so hopefully they will look into this as well.

I ran MacOs for almost a year and until these incidents its been 100% stable, with macfuse and Veracrypt volume in use.

**Comment by OliverDrechsler** [comment]
@michaelezra : as I stated above https://github.com/osxfuse/osxfuse/issues/924#issuecomment-1301769384 
it worked for me again after uninstall und install again.... with the latest MacOS....
Maybe one thing what you also could check is the permissions  in Settings -> Security -> File System access for Veracrypt....
I have in my mind that after upgrade to Ventura it got lost for Veracrypt... and I had trouble with that as well...
but this this had nothing to do with MacFuse / OSXFuse

**Comment by bfleischer** [comment]
@michaelezra Verycrypt is not a kernel extension, that's why it would not appear in a backtrace of a kernel panic log.

In an ideal world, no user space application (this includes Veracrypt) should not be able to crash the macOS kernel. If this happens nonetheless, it points to a bug in the kernel that needs to be addressed by Apple. Your panics might have been indirectly triggered by a third-party application or a third-party kernel extensions (this would include macFUSE), but the logs do not contain any evidence pointing in that direction. The backtrace leading to the panic only contains Apple kernel extensions. Unless the panic log lists a third-party kernel extension in the backtrace, it is best to report the issue to Apple.

If you can reproduce the panic reliably, you could try performing the same repro steps on your local APFS volume without your Veracrypt container being mounted.

**Comment by woncheol-kim** [comment]
Hi, I got similar problems with the latest versions of macOS, macfuse and rclone. 
Firstly, my sistem info:

OS: macOS 13.0.1 22A400 x86_64 
Host: Macmini8,1 
Kernel: 22.1.0 
CPU: Intel i7-8700B (12) @ 3.20GHz 
GPU: Intel UHD Graphics 630 
Memory: 7964MiB / 16384MiB 


And I've found the logs as below:

"macOSPanicString" : "panic(cpu 2 caller 0xffffff7fa0634aa6): fuse: What kind of a flag is this (8100)?\nPanicked task 0xffffffa519c52638: 3 threads: pid 1656: smbd\nBacktrace (CPU 2), panicked thread: 0xffffff9b88721598, Frame : Return Address\n0xffffffffd97c7730 : 0xffffff80097edf9d \n0xffffffffd97c7780 : 0xffffff800995b786 \n0xffffffffd97c77c0 : 0xffffff800994aa10 \n0xffffffffd97c7810 : 0xffffff8009788951 \n0xffffffffd97c7830 : 0xffffff80097ee27d \n0xffffffffd97c7920 : 0xffffff80097ed929 \n0xffffffffd97c7980 : 0xffffff8009fe0ecb \n0xffffffffd97c7a70 : 0xffffff7fa0634aa6 \n0xffffffffd97c7b50 : 0xffffff7fa06300ba \n0xffffffffd97c7b90 : 0xffffff8009a153dd \n0xffffffffd97c7bd0 : 0xffffff8009a08997 \n0xffffffffd97c7c80 : 0xffffff80099ee767 \n0xffffffffd97c7ee0 : 0xffffff80099ef562 \n0xffffffffd97c7f40 : 0xffffff8009e5606b \n0xffffffffd97c7fa0 : 0xffffff8009788d96 \n      Kernel Extensions in backtrace:\n         io.macfuse.filesystems.macfuse(2113.20)[1BAB409A-4223-365F-AEDB-D9FCC060B458]@0xffffff7fa0629000->0xffffff7fa063cfff\n\nProcess name corresponding to current thread (0xffffff9b88721598): smbd\n\nMac OS version:\n22A400\n\nKernel version:\nDarwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2\/RELEASE_X86_64\nKernel UUID: BF7C9676-EF23-3E8D-A2E2-25DAC63091B6\nroots installed: 0\nKernelCache slide: 0x0000000009400000\nKernelCache base:  0xffffff8009600000\nKernel slide:      0x00000000094dc000\nKernel text base:  0xffffff80096dc000\n__HIB  text base: 0xffffff8009500000\nSystem model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)\nSystem shutdown begun: NO\nHibernation exit count: 0\n\nSystem uptime in nanoseconds: 546170498972\nLast Sleep:           absolute           base_tsc          base_nano\n  Uptime  : 0x0000007f2a4c71f6\n  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000\n  Wake    : 0x0000000000000000 0x00000003ee9e080c 0x0000000000000000\nCompressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space\nZone info:\n  Zone map: 0xffffff904cf00000 - 0xffffffb04cf00000\n  . PGZ   : 0xffffff904cf00000 - 0xffffff904ef01000\n  . VM    : 0xffffff904ef01000 - 0xffffff951b700000\n  . RO    : 0xffffff951b700000 - 0xffffff96b4f00000\n  . GEN0  : 0xffffff96b4f00000 - 0xffffff9b81700000\n  . GEN1  : 0xffffff9b81700000 - 0xffffffa04df00000\n  . GEN2  : 0xffffffa04df00000 - 0xffffffa51a700000\n  . GEN3  : 0xffffffa51a700000 - 0xffffffa9e6f00000\n  . DATA  : 0xffffffa9e6f00000 - 0xffffffb04cf00000\n  Metadata: 0xffffffffd9fee000 - 0xfffffffff9fee000\n  Bitmaps : 0xfffffffff9fee000 - 0xfffffffffffee000\n\nlast started kext at 154995422065: io.macfuse.filesystems.macfuse\t2113.20 (addr 0xffffff7fa0629000, size 81920)\nlast stopped kext at 507299674024: >!AFIVRDriver\t4.1.0 (addr 0xffffff7f9e52b000, size 8192)\nloaded kexts:\nio.macfuse.filesystems.macfuse\t2113.20\n@filesystems.smbfs\t5.0\n>AudioAUUC\t1.70\n>AGPM\t131\n>!APlatformEnabler\t2.7.0d0\n>X86PlatformShim\t1.0.0\n@filesystems.autofs\t3.0\n>!AUpstreamUserClient\t3.6.9\n>!AMCCSControl\t1.16\n>!ABridgeAudio!C\t300.10\n>!AGraphicsDevicePolicy\t7.1.16\n>!AGFXHDA\t200.2\n@AGDCPluginDisplayMetrics\t7.1.16\n>pmtelemetry\t1\n@filesystems.nfs\t1\n|IOUserEthernet\t1.0.1\n>usb.!UUserHCI\t1\n>!AHV\t1\n>!A!IKBLGraphics\t20.0.2\n>!ADiskImages2\t198.40.3\n>!AThunderboltIP\t4.0.3\n>BridgeAudioCommunication\t300.10\n>!AAVEBridge\t6.1\n>!A!IPCHPMC\t2.0.1\n>!A!ISlowAdaptiveClocking\t4.0.0\n>!A!ICFLGraphicsFramebuffer\t20.0.2\n>BCMWLANFirmware4387.Hashstore\t1\n>BCMWLANFirmware4378.Hashstore\t1\n>BCMWLANFirmware4377.Hashstore\t1\n>BCMWLANFirmware4364.Hashstore\t1\n>BCMWLANFirmware4355.Hashstore\t1\n>!AFileSystemDriver\t3.0.1\n@filesystems.tmpfs\t1\n@filesystems.lifs\t1\n@filesystems.hfs.kext\t627.40.1\n@BootCache\t40\n@!AFSCompression.!AFSCompressionTypeZlib\t1.0.0\n@!AFSCompression.!AFSCompressionTypeDataless\t1.0.0d1\n@filesystems.apfs\t2142.41.2\n>!ABCMWLANBusInterfacePCIeMac\t1\n|!ABCM5701Ethernet\t11.0.0\n@private.KextAudit\t1.0\n>!AACPIButtons\t6.1\n>!ASMBIOS\t2.1\n>!AACPIEC\t6.1\n>!AAPIC\t1.7\n$!AUserConsent\t1\n@!ASystemPolicy\t2.0.0\n@nke.applicationfirewall\t403\n|IOKitRegistryCompatibility\t1\n|EndpointSecurity\t1\n@Dont_Steal_Mac_OS_X\t7.0.0\n@kec.Compression\t1\n@kec.!AEncryptedArchive\t1\n@plugin.IOAVBDiscoveryPlugin\t1100.24\n>!ASMBus!C\t1.0.18d1\n>!UAudio\t500.2\n>!AAudioClockLibs\t200.5\n>!AGraphicsControl\t7.1.16\n|IOAudio!F\t400.3\n@vecLib.kext\t1.2.0\n>!A!ILpssUARTv1\t3.0.60\n>!A!ILpssUARTCommon\t3.0.60\n>!AOnboardSerial\t1.0\n@kext.triggers\t1.0\n>IOHIDPowerSource\t1\n|IO!BSerialManager\t9.0.0\n|IO!BPacketLogger\t9.0.0\n|IO!BHost!CUSBTransport\t9.0.0\n|IO!BHost!CUARTTransport\t9.0.0\n|IO!BHost!CTransport\t9.0.0\n>IO!BHost!CPCIeTransport\t9.0.0\n|IOAVB!F\t1100.24\n|CSR!BHost!CUSBTransport\t9.0.0\n|Broadcom!BHost!CUSBTransport\t9.0.0\n|Broadcom!B20703USBTransport\t9.0.0\n>!ARSMChannel\t1\n|IORSM!F\t1\n>!AIPAppender\t1.0\n>!AThunderboltDPOutAdapter\t8.5.1\n|IONDRVSupport\t597\n@!AGPUWrangler\t7.1.16\n|IOSlowAdaptiveClocking!F\t1.0.0\n|IOAccelerator!F2\t475\n@!AGraphicsDeviceControl\t7.1.16\n|IOGraphics!F\t597\n>X86PlatformPlugin\t1.0.0\n>IOPlatformPlugin!F\t6.0.0d8\n@plugin.IOgPTPPlugin\t1110.13\n>driverkit.serial\t6.0.0\n>usb.IOUSBHostHIDDevice\t1.2\n>usb.cdc.ecm\t5.0.0\n>usb.cdc.ncm\t5.0.0\n>usb.cdc\t5.0.0\n>usb.networking\t5.0.0\n>usb.!UHostCompositeDevice\t1.2\n>!AThunderboltPCIDownAdapter\t4.1.1\n>!AThunderboltDPInAdapter\t8.5.1\n>!AThunderboltDPAdapter!F\t8.5.1\n>!AHPM\t3.4.4\n>!A!ILpssI2C!C\t3.0.60\n>!A!ILpssI2C\t3.0.60\n>!A!ILpssDmac\t3.0.60\n>!ABSDKextStarter\t3\n|IOSurface\t334.0.1\n@filesystems.hfs.encodings.kext\t1\n>!ASyntheticGame!C\t10.2.9\n>!AXsanScheme\t3\n>!AThunderboltNHI\t7.2.81\n|IOThunderbolt!F\t9.3.3\n>!ABCMWLANCoreMac\t1.0.0\n|IO80211!F\t1200.13.0\n>IOImageLoader\t1.0.0\n>!AOLYHALMac\t1\n|IOSerial!F\t11\n>corecapture\t1.0.4\n>usb.!UVHCIBCE\t1.2\n>usb.!UVHCICommonBCE\t1.0\n>usb.!UVHCI\t1.2\n>usb.!UVHCICommon\t1.0\n>!AEffaceableNOR\t1.0\n|IOBufferCopy!C\t1.1.0\n|IOBufferCopyEngine!F\t1\n|IONVMe!F\t2.1.0\n>usb.!UHostPacketFilter\t1.0\n|IOUSB!F\t900.4.2\n>usb.!UXHCIPCI\t1.2\n>usb.!UXHCI\t1.2\n>!AEFINVRAM\t2.1\n>!AEFIRuntime\t2.1\n>!ASMCRTC\t1.0\n|IOSMBus!F\t1.1\n|IOHID!F\t2.0.0\n|IOTimeSync!F\t1110.13\n|IOSkywalk!F\t1.0\n>mDNSOffloadUserClient\t1.0.1b8\n|IONetworking!F\t3.4\n>DiskImages\t493.0.0\n|IO!B!F\t9.0.0\n|IOReport!F\t47\n$quarantine\t4\n$sandbox\t300.0\n@kext.!AMatch\t1.0.0d1\n>!ASSE\t1.0\n>!AKeyStore\t2\n>!UTDM\t547\n|IOUSBMass!SDriver\t232\n|IOSCSIBlockCommandsDevice\t476\n|IO!S!F\t2.1\n|IOSCSIArchitectureModel!F\t476\n>!AMobileFileIntegrity\t1.0.5\n$!AImage4\t5.0.0\n@kext.CoreTrust\t1\n>!AFDEKeyStore\t28.30\n>!AEffaceable!S\t1.0\n>!ACredentialManager\t1.0\n|CoreAnalytics!F\t1\n>KernelRelayHost\t1\n|IOUSBHost!F\t1.2\n>!UHostMergeProperties\t1.2\n>usb.!UCommon\t1.0\n>!ABusPower!C\t1.0\n>!ASEPManager\t1.0.1\n>IOSlaveProcessor\t1\n>!AACPIPlatform\t6.1\n>!ASMC\t3.1.9\n|IOPCI!F\t2.9\n|IOACPI!F\t1.4\n>watchdog\t1\n@kec.pthread\t1\n@kec.Libm\t1\n@kec.corecrypto\t12.0\n",

**Comment by geroyche** [comment]
Just to chime in, I too experienced freezes trying to do my "regular olde mounts" after uprading both macOS to Ventura and macFUSE to 4.4.1. In the end I deleted the existing mount point folders thanks to @4bondarenko's findings (permissions looked fine, umount said they were not mounted). They were recreated (I need them to have the same name) on the next mount and everything worked again.

**Comment by cwdsubs** [comment]
I can't install! Where in Security & Privacy preferences can I allow loading software from Ben Fleischer? The prefs dialog has been redesigned in Ventura. Thanks

**Comment by cwdsubs** [comment]
PS:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/57675237/210857470-52efc034-a754-4570-8b2f-294d231e71bc.png">

**Comment by skarekrow** [comment]
@cwdsubs Just reduce your system security to enable user system extensions. Here's a [visual guide](https://iboysoft.com/howto/enable-system-extension-m1-mac.html) for you to help if you're not sure.

**Comment by cwdsubs** [comment]
Thanks @skarekrow 😊

**Comment by AdarshRevankar** [comment]
> i had the same (were I used it within veracrypt), but I solved it with `brew uninstall macfuse` and installed it again with `brew install mccfuse`. After a reboot it worked for me

This solution worked like charm ! Thanks @OliverDrechsler 👏

**Comment by aol-nnov** [comment]
I have the similar issue on Ventura.

I have a raw disk image, which I'm attaching with the following command: `sudo hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount /path/to/raw.img`

the result reads as follows:

```
/dev/disk2          	FDisk_partition_scheme         	
/dev/disk2s1        	Linux 
```

next I'm trying to mount disk2s1 with ext4mount: `sudo ext4fuse -o allow_other,default_permissions,local /dev/disk2s1 /Volumes/ext/`

after that I'm trying to access the mount point, but no dice:

```
aol@Andreys-MacBook-Pro:~$ sudo ls /Volumes/ext 
ls: /Volumes/ext: Input/output error
```

ext4fuse: manually built from mainline (6b23d8d)
macfuse 4.4.1 from dmg
macos: Ventura 13.2 (Intel)

It is worth to mention, that aforementioned raw image mounts without an issue on linux (unfortunately, I'm unable to provide you with it, as it contains internal data)

I'll crosspost to ext4fuse, too.

**Comment by bfleischer** [comment]
@aol-nnov Input/output errors are usually the result of the file system (ext4fuse in your case) not being built against the correct macFUSE library or with incorrect compiler flags. It seems the ext4fuse project has not been updated in quite some time. Maybe recompiling it against the latest version of macUFSE solves the issue. But in any case I think this is something that needs to be looked into from the ext4fuse end.

**Comment by aol-nnov** [comment]
Thank you for a prompt reply, @bfleischer !

I've just rebuilt ext4fuse against macFUSE 4.4.2, but no dice.. Same I/O error after mount...

**Comment by todo** [comment]
I am on ventura 13.2.1 and macfuse 4.4.2. 

Each time after I reboot, I was able to use veracrypt 1.25.9. But if I quit and come back in awhile (sorry, wasn't able to figure out the exact time yet), Veracypt will return "mount_macfuse: the MacFUSE kernel extension is not loaded". 

Before I upgrade to Ventura, I don't have this problem with veracrypt.

It appears macfuse kernel is offloaded. However, when I do "kextstat | grep fuse", I can see

<img width="681" alt="image" src="https://user-images.githubusercontent.com/57632/221629178-88155220-1624-46e9-b581-93e6cf7ac0c6.png">

Anyone know, what's wrong?

Thanks!

**Comment by todo** [comment]
I found a workaround to my own problem. The trick is whenever it doesn't mount, I just need to uninstall macfuse and install it again. (Good thing is, I don't need to reboot.)

**Comment by bfleischer** [comment]
@todo macFUSE 4.4.3 adds a workaround for your issue. See #850 for details.
