### ISSUE TITLE
After mount, not able to view files in finder but visible in terminal

### ISSUE THREAD

**Issue by sk-gaurav** [osxfuse/osxfuse#925]
Mac OS Monterey Version 12.6.1 Apple M1 chip

I am running some infrastructure command which needs mounting support on Mac. Initially when I run the command, I got the following error.

_Error: mount: cannot locate OSXFUSE_

After which I installed macFUSE from https://osxfuse.github.io/ . Now, mounting is done properly when I run the command, but I'm not able to see the files on the finder. Only directory is visible. I need to see those files in finder so I can upload them in a UI. I've tried installing macFUSE 4.4.0 version as well, but no luck.

**Comment by bfleischer** [comment]
Which file system are you using?

Please note: macFUSE is a building block used by third-party developers to build actual file systems. Usually it is best to raise issues like this one with the developer of the actual file system you are trying to use. In most cases the file system developer is best suited for analyzing such issues.

**Comment by stanaka6** [comment]
Hi @bfleischer, 

I'm having a similar issue that @sk-gaurav posted. 

I used the macFuse for several weeks without any issues. However, now when I try to mount using `sshfs` on the Terminal, I cannot see the folder in Finder, but visible in the Terminal. I could not access files in the mounted folder. For example, if I try to access a file in the folder on R, I will get the following error: 

```
`MyObject <- readRDS("/Users/myname/Documents/LocalFolder/MyObject.rds")`
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/Users/myname/Documents/LocalFolder/MyObject.rds', 
probable reason 'Device not configured'
```
- When I mount (`sshfs`) and unmount, there is no error message. 
- I tried adding `-o allow_other`, and ` -o volumename=XXXX`, using a new directory, and reinstalling through `brew uninstall macfuse` followed by `brew install macfuse` according to other issues, but neither solves the problem.      

Could you please provide me with solutions?

macOS: Ventura 13
Processor: 2.3 GHz Dual-Core Intel Core i5
macFUSE: 4.4.1

Thank you very much!

**Comment by jdha** [comment]
> Mac OS Monterey Version 12.6.1 Apple M1 chip
> 
> I am running some infrastructure command which needs mounting support on Mac. Initially when I run the command, I got the following error.
> 
> _Error: mount: cannot locate OSXFUSE_
> 
> After which I installed macFUSE from https://osxfuse.github.io/ . Now, mounting is done properly when I run the command, but I'm not able to see the files on the finder. Only directory is visible. I need to see those files in finder so I can upload them in a UI. I've tried installing macFUSE 4.4.0 version as well, but no luck.

@sk-gaurav I was having similar issues (OSX 12.6.1, M1, macFUSE 4.4.1, SSHFS 2.5) where I could only see the contents of the mounted fs using iterm, but not in Finder. I downgraded to macFUSE 4.2.5 and now I can see all the files and folders in the mounted directory using Finder. Hope that at least gives you a working solution.

**Comment by bfleischer** [comment]
For sshfs you might want to try using the mount option `defer_permissions` (https://github.com/macfuse/macfuse/wiki/Mount-Options#default_permissions-and-defer_permissions) or look into uid/gid mapping.

@jdha Downgrading macFUSE to version 4.2.5 should have no effect at all. The code responsible for checking file permission has not been touched since version 4.2.5. I don't see how any of the changes since 4.2.5 could be responsible for what you are seeing.

I'm going to close the ticket since there has not been any response from the ticket creator.

**Comment by vdudouyt** [comment]
On macOS Sonoma, I had the same problem until I explicitly specified volume name by passing -o volname=MyVolume to my macFUSE client command line options. After that, my macFUSE mount started being visible in Finder by volume name (rather than by the original directory name).
