### ISSUE TITLE
The macFUSE installation package is not compatible with this version of macOS. Ventura 13.0.1

### ISSUE THREAD

**Issue by Mandibul01** [osxfuse/osxfuse#926]
Hello. Just updated to Ventura and MacFUSE begun to give problems.
The error triggers when launching Bitrix24.
I'm a regular user using my Mac to connect to the company services.

Mac system settings has MacFuse 441 ready to install but then return the above error.

Any help would be appreciated.

**Comment by Aswad1979** [comment]
Same here!

**Comment by bfleischer** [comment]
macFUSE 4.4.1 is compatible with Ventura. The error you are seeing is displayed when trying to install an old version of macFUSE on Ventura. Bitrix24 might be including an old version of macFUSE. You can download the latest version macFUSE from https://macfuse.io.

**Comment by robertoandrade** [comment]
getting the same error now running on Tahoe 26.0. perhaps it's hardcoding the maximum version supported?

**Comment by robertoandrade** [comment]
just saw there's a version 5 not exposed in macfuse.io in github: https://github.com/macfuse/macfuse/releases

**Comment by bfleischer** [comment]
@robertoandrade Not sure what you mean, but macFUSE 5.0.5 is currently in developer preview, but it is available on https://macfuse.io as well.
