### ISSUE TITLE
kext not loading on MacOS 13.1 with macFUSE 4.4.1

### ISSUE THREAD

**Issue by rosch100** [osxfuse/osxfuse#927]
One one M1 iMac, macFUSE is not working. Uninstall/Reinstall does not resolve the issue. On a M1 MacBook Pro with the same system settings (OSX 13.1), everything works as expected.

1. When trying to use a FUSE filesystem, I get the following error:
```
kext load failed: -603947007
mount_macfuse: the file system is not available (255)
```
2. Trying to load the kext manually, a strange error message is displayed:
```
sudo kextload /Library/Filesystems/macfuse.fs/Contents/Extensions/13/macfuse.kext
Executing: /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/13/macfuse.kext
Error Domain=KMErrorDomain Code=71 "Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/24E2A8E8-5029-458B-9250-B1DEA07D8947/boot/0AD4D5178396610BDDB688B4AFD24F317D0AFF31AB91680C00BE1C4A273465F04BFC4D738113E65754157674E490DCB6/System/Library/Caches/com.apple.kernelcaches/kernelcache" UserInfo={NSLocalizedDescription=Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/24E2A8E8-5029-458B-9250-B1DEA07D8947/boot/0AD4D5178396610BDDB688B4AFD24F317D0AFF31AB91680C00BE1C4A273465F04BFC4D738113E65754157674E490DCB6/System/Library/Caches/com.apple.kernelcaches/kernelcache}
```

**Comment by bfleischer** [comment]
macOS 13.1 is still in beta. It might not be stable, yet.

> Error Domain=KMErrorDomain Code=71 "Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/24E2A8E8-5029-458B-9250-B1DEA07D8947/boot/0AD4D5178396610BDDB688B4AFD24F317D0AFF31AB91680C00BE1C4A273465F04BFC4D738113E65754157674E490DCB6/System/Library/Caches/com.apple.kernelcaches/kernelcache" UserInfo={NSLocalizedDescription=Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/24E2A8E8-5029-458B-9250-B1DEA07D8947/boot/0AD4D5178396610BDDB688B4AFD24F317D0AFF31AB91680C00BE1C4A273465F04BFC4D738113E65754157674E490DCB6/System/Library/Caches/com.apple.kernelcaches/kernelcache}

This looks more like a macOS issue than a macFUSE issue. Reinstalling macOS might help.

**Comment by bfleischer** [comment]
Closed. I have not been able to reproduce the issue on the final version of macOS 13.1.

**Comment by rosch100** [comment]
The issue is still present in both MacOS 13.1 and MacOS 13.2.

Trying to use sshfs to mount an ssh file system, the command is:
`sshfs user@server:/srv/files /mountpoint`
this error message is:
`kext load failed: -603947007
mount_macfuse: the file system is not available (255)`

**Comment by bfleischer** [comment]
> The issue is still present in both MacOS 13.1 and MacOS 13.2.

Works fine for me. Did you allow loading the macFUSE kernel extension? See https://github.com/macfuse/macfuse/wiki/Getting-Started for details.

If you are still getting the "Unable to get contents of boot kernel collection collection" error, it might be best to raise the issue with Apple or reinstall macOS as this is not caused by macFUSE.

**Comment by rosch100** [comment]
@bfleischer thank you for your suggestion of a possible Apple issue. Searching for the "kernel collection collection" error, I found that this issue is indeed a problem only Apple is able to resolve. 
The issue is with MacOS booting from an external drive, which is the case for my M1 iMac.
[kmutil fails when booted into OS on external drive](https://developer.apple.com/forums/thread/679416?login=true&page=1#744733022)

**Comment by tristan-k** [comment]
> @bfleischer thank you for your suggestion of a possible Apple issue. Searching for the "kernel collection collection" error, I found that this issue is indeed a problem only Apple is able to resolve. The issue is with MacOS booting from an external drive, which is the case for my M1 iMac. [kmutil fails when booted into OS on external drive](https://developer.apple.com/forums/thread/679416?login=true&page=1#744733022)

Any solutions to this? I'm also running a m1 mac mini with an external drive.
