### ISSUE TITLE
SSHFS : Can't write on mounted disk from macOS Ventura except from terminal

### ISSUE THREAD

**Issue by lvancrayelynghe** [osxfuse/osxfuse#928]
On a fresh install from this week, brand new macbook pro 13, with this versions : 
- macOS : 13.0.1
- macFUSE : 4.4.1
- SSHFS : 2.5.0

I have a very strange behavior with the command `sshfs -o allow_other root@my.ip.address:/var/www ~/MyServer`. No particular error on launch, every files from the remote server appears correctly, I can navigate with Finder or anything but : 
- In iTerm, if I run `nano ~/MyServer/path/to/existing/file`, I can edit the file with no problem
- In iTerm, if I run `touch ~/MyServer/path/to/new/file`, I have a "Permission denied" error 
- With any other app, I have a "Permission denied" error with every edit or file creation

Full access to disk has been given to iTerm and TextEdit for the test : it only work in iTerm.

Something stranger, if I use the same `sshfs` command on a macOS 12.3, with up to date macFUSE and SSHFS, I have no permission error.

Am i missing something ? Is this a strange behavior or maybe a bug with macOS Ventura ?

Let me know if you need anymore information. 

Thanks,

**Comment by bfleischer** [comment]
Sounds like this might be a uid/gid mapping issue. Try mounting with the `defer_permissions` mount option. See https://github.com/macfuse/macfuse/wiki/Mount-Options#default_permissions-and-defer_permissions for details.

This ticket is quite old, so I'm closing it. Feel free to open a new ticket, in case this is still an issue.
