### ISSUE TITLE
Authentication after download

### ISSUE THREAD

**Issue by ajay-gh** [osxfuse/osxfuse#929]
My apology, this isn't really an "issue", but I don't know where else to ask. 
I have been looking for a way to independently (with a PGP signature, or at least a hash code like SHA256 or better) authenticate the Fuse installer packages after download. This is mainly because of habit, but also because - unlike other software - it appears that the macos gatekeeper does not display the usual dialog "... and none was detected". In other words I am not sure that it's been checked at all.
Please feel free to close this issue, since it's irrelevant to the development - or may be because I overlooked the file. I can find the sha256 file for version 3.7.1. here on git, but don't get nowhere looking for the signature file for v4.4.1

**Comment by bfleischer** [comment]
You can find SHA-256 hashes for every release on the GitHub releases page at https://github.com/osxfuse/osxfuse/releases. The SHA-256 hash for the 4.4.1 disk image is 2a2d0f37ec5fcff547c5efa7d08539103a0b46bc16080c2b41a7e749f6e65c61.

All `.sha256` files are signed by me using PGP. The signatures are available on the releases page as well. My public key can be downloaded from https://osxfuse.github.io/static/53C918C1A2818875.asc.

> This is mainly because of habit, but also because - unlike other software - it appears that the macos gatekeeper does not display the usual dialog "... and none was detected". In other words I am not sure that it's been checked at all.

All macFUSE releases are signed by me and notarized by Apple. macOS would refuse to load the macFUSE kernel extension in case it was not signed and notarized.
