### ISSUE TITLE
Frequent crash after mounting a Veracrypt drive on MacOS

### ISSUE THREAD

**Issue by usur-10** [osxfuse/osxfuse#930]
Hi, i've recently moved from a Windows machine to the first macbook M1. I've installed Veracrypt, and Macfuse as per the instruction on its website.

It seems to work at first. I can mount my drive and do just about every thing as I had done with Veracrypt on a Windows laptop. However, always some time after a drive is mounted, my Mac would crash and restart by itself.

I've uninstalled Macfuse, Veracrypt, and reinstall them again. I've got the latest version of them all, but the issue still persists.
MacFuse 4.4.1
MacOS Ventura 13.0.1
Veracrypt 1.25.9

I don't know what else to do. I'm new to Mac and to github as well.

Below is a typical Panic crash log I get after the computer restarts by itself. Please help! Thank you!

======================================================

panic(cpu 1 caller 0xfffffe001d5bbd10): busy timeout[0], (90s): 'IOMediaBSDClient' (1,1810001) @IOService.cpp:5663
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 22A400
Kernel version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
Fileset Kernelcache UUID: 45C5EC70B9F83105E3F59CFE0A124F15
Kernel UUID: 0BFE6A5D-118B-3889-AE2B-D34A0117A062
Boot session UUID: B89E1FE6-7B4A-46CF-BB10-83A85A8C5904
iBoot version: iBoot-8419.41.10
secure boot?: YES
roots installed: 0
Paniclog version: 14
KernelCache slide: 0x0000000014b18000
KernelCache base:  0xfffffe001bb1c000
Kernel slide:      0x0000000015d5c000
Kernel text base:  0xfffffe001cd60000
Kernel text exec slide: 0x0000000015e44000
Kernel text exec base:  0xfffffe001ce48000
mach_absolute_time: 0x54cec94db
Epoch Time:        sec       usec
  Boot    : 0x6392fa3d 0x0007c459
  Sleep   : 0x639309cc 0x00080d59
  Wake    : 0x63930b75 0x00097d48
  Calendar: 0x63930bd0 0x00015dec

Zone info:
  Zone map: 0xfffffe10064ec000 - 0xfffffe30064ec000
  . VM    : 0xfffffe10064ec000 - 0xfffffe14d31b8000
  . RO    : 0xfffffe14d31b8000 - 0xfffffe166cb50000
  . GEN0  : 0xfffffe166cb50000 - 0xfffffe1b3981c000
  . GEN1  : 0xfffffe1b3981c000 - 0xfffffe20064e8000
  . GEN2  : 0xfffffe20064e8000 - 0xfffffe24d31b4000
  . GEN3  : 0xfffffe24d31b4000 - 0xfffffe299fe80000
  . DATA  : 0xfffffe299fe80000 - 0xfffffe30064ec000
  Metadata: 0xfffffe3eef0f8000 - 0xfffffe3ef70f8000
  Bitmaps : 0xfffffe3ef70f8000 - 0xfffffe3ef9cf4000

CORE 0 recently retired instr at 0xfffffe001d002ea0
CORE 1 recently retired instr at 0xfffffe001d0017a0
CORE 2 recently retired instr at 0xfffffe001d002ea0
CORE 3 recently retired instr at 0xfffffe001d002ea0
CORE 4 recently retired instr at 0xfffffe001d002ea0
CORE 5 recently retired instr at 0xfffffe001d002ea0
CORE 6 recently retired instr at 0xfffffe001d002ea0
CORE 7 recently retired instr at 0xfffffe001d002ea0
TPIDRx_ELy = {1: 0xfffffe20048de818  0: 0x0000000000000001  0ro: 0x000000016d0870e0 }
CORE 0 PVH locks held: None
CORE 1 PVH locks held: None
CORE 2 PVH locks held: None
CORE 3 PVH locks held: None
CORE 4 PVH locks held: None
CORE 5 PVH locks held: None
CORE 6 PVH locks held: None
CORE 7 PVH locks held: None
CORE 0: PC=0xfffffe001cee355c, LR=0xfffffe001cee355c, FP=0xfffffe8277c73f00
CORE 1 is the one that panicked. Check the full backtrace for details.
CORE 2: PC=0xfffffe001ce9d82c, LR=0xfffffe001ce9d82c, FP=0xfffffe8ff6d8bc60
CORE 3: PC=0xfffffe001cee355c, LR=0xfffffe001cee355c, FP=0xfffffe8ff6cb3f00
CORE 4: PC=0xfffffe001cee3560, LR=0xfffffe001cee355c, FP=0xfffffe8ff6c3bf00
CORE 5: PC=0xfffffe001cee355c, LR=0xfffffe001cee355c, FP=0xfffffe74fd497f00
CORE 6: PC=0xfffffe001cee355c, LR=0xfffffe001cee355c, FP=0xfffffe8ff6ccbf00
CORE 7: PC=0xfffffe001cee355c, LR=0xfffffe001cee355c, FP=0xfffffe8277d3ff00
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Panicked task 0xfffffe1b388679b8: 257 pages, 4 threads: pid 107: watchdogd
Panicked thread: 0xfffffe20048de818, backtrace: 0xfffffe74fd5573f0, tid: 12374
		  lr: 0xfffffe001cea67e8  fp: 0xfffffe74fd557460
		  lr: 0xfffffe001cea6590  fp: 0xfffffe74fd5574e0
		  lr: 0xfffffe001d00992c  fp: 0xfffffe74fd557500
		  lr: 0xfffffe001cffb394  fp: 0xfffffe74fd557570
		  lr: 0xfffffe001cff8c98  fp: 0xfffffe74fd557630
		  lr: 0xfffffe001ce4f7f8  fp: 0xfffffe74fd557640
		  lr: 0xfffffe001cea5f1c  fp: 0xfffffe74fd5579f0
		  lr: 0xfffffe001d6e8c90  fp: 0xfffffe74fd557a10
		  lr: 0xfffffe001d5bbd10  fp: 0xfffffe74fd557ac0
		  lr: 0xfffffe001cfc6700  fp: 0xfffffe74fd557af0
		  lr: 0xfffffe001ceace60  fp: 0xfffffe74fd557b90
		  lr: 0xfffffe001ce7c9c4  fp: 0xfffffe74fd557bf0
		  lr: 0xfffffe001ce97d6c  fp: 0xfffffe74fd557c90
		  lr: 0xfffffe001ce9820c  fp: 0xfffffe74fd557d80
		  lr: 0xfffffe001cfeebf0  fp: 0xfffffe74fd557e50
		  lr: 0xfffffe001cff9044  fp: 0xfffffe74fd557f10
		  lr: 0xfffffe001ce4f7f8  fp: 0xfffffe74fd557f20

last started kext at 7746177172: io.macfuse.filesystems.macfuse	2113.20 (addr 0xfffffe001ba3c000, size 6320)
loaded kexts:
io.macfuse.filesystems.macfuse	2113.20
com.apple.iokit.SCSITaskUserClient	476
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleTopCaseHIDEventDriver	6000.22
com.apple.driver.CoreKDL	1
com.apple.driver.AppleBiometricServices	1
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleAOPVoiceTrigger	200.4
com.apple.driver.BCMWLANFirmware4378.Hashstore	1
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.SEPHibernation	1
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.filesystems.nfs	1
com.apple.filesystems.lifs	1
com.apple.filesystems.apfs	2142.41.2
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	627.40.1
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.ApplePMP	1
com.apple.driver.AppleSmartIO2	1
com.apple.driver.ApplePMPFirmware	1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleMobileDispH13G-DCP	140.0
com.apple.driver.AudioDMAController-T8103	200.21
com.apple.driver.AppleSerialShim	1
com.apple.driver.AppleCS42L83Audio	600.99
com.apple.driver.AppleTypeCRetimer	1.0.0
com.apple.driver.AppleTAS5770LAmp	600.99
com.apple.driver.AppleDPDisplayTCON	1
com.apple.AGXG13G	227.2.40
com.apple.driver.AppleEventLogHandler	1
com.apple.driver.AppleAVE2	630.29.1
com.apple.driver.AppleT8020SOCTuner	1
com.apple.driver.AppleT8103CLPCv3	1
com.apple.driver.AppleT8103PMGR	1
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleAVD	616
com.apple.driver.AppleJPEGDriver	5.2.6
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
com.apple.driver.AppleInterruptController	1.0.0d1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleT8020DART	1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleT8101	1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.usb.AppleUSBUserHCI	1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	198.40.3
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	403
com.apple.kec.InvalidateHmac	1
com.apple.kec.Compression	1
com.apple.kec.AppleEncryptedArchive	1
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.AppleUSBAudio	500.2
com.apple.iokit.IOAudioFamily	400.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.driverkit.serial	6.0.0
com.apple.iokit.IOAVBFamily	1100.24
com.apple.plugin.IOgPTPPlugin	1110.13
com.apple.driver.AppleActuatorDriver	6400.44
com.apple.driver.AppleMultitouchDriver	6400.44
com.apple.driver.AppleHSBluetoothDriver	6000.22
com.apple.driver.IOBluetoothHIDDriver	9.0.0
com.apple.driver.AppleHIDKeyboard	231
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.driver.AppleAOPAudio	200.45
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.driver.AppleXsanScheme	3
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.driver.AppleThunderboltDPInAdapter	8.5.1
com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.1
com.apple.driver.AppleTrustedAccessory	1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.nke.ppp	1.9
com.apple.driver.AppleBSDKextStarter	3
com.apple.kext.triggers	1.0
com.apple.driver.IOHIDPowerSource	1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleSyntheticGameController	10.2.9
com.apple.driver.AppleHIDTransportSPI	6400.40
com.apple.driver.AppleHIDTransport	6400.40
com.apple.driver.AppleInputDeviceSupport	6400.40
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.AGXFirmwareKextG13GRTBuddy	227.2.40
com.apple.AGXFirmwareKextRTBuddy64	227.2.40
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.DCPAVFamilyProxy	1
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.AppleSPMI	1.0.1
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.driver.AppleSART	1
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.driver.AppleSPU	1
com.apple.driver.AppleCSEmbeddedAudio	600.99
com.apple.driver.AppleEmbeddedAudio	600.99
com.apple.iokit.AppleARMIISAudio	200.8
com.apple.iokit.IOGPUFamily	65.0.22
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.driver.ApplePMGR	1
com.apple.driver.AppleH13CameraInterface	7.110.1
com.apple.driver.AppleH10PearlCameraInterface	17.0.8
com.apple.driver.AppleH11ANEInterface	6.101.1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleSynopsysUSBXHCI	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleARMWatchdogTimer	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.81
com.apple.driver.AppleT8103PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.3
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT8103PCIe	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211Family	1200.13.0
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.AppleOLYHAL	1
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleMCA2-T8103	701.14
com.apple.driver.AppleEmbeddedAudioLibs	200.5
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMobileApNonce	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOTimeSyncFamily	1110.13
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	597
com.apple.iokit.IOBluetoothSerialManager	9.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerTransport	9.0.0
com.apple.driver.IOBluetoothHostControllerPCIeTransport	9.0.0
com.apple.iokit.IOBluetoothFamily	9.0.0
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	9.0.0
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	547
com.apple.iokit.IOUSBMassStorageDriver	232
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	476
com.apple.iokit.IOSCSIArchitectureModelFamily	476
com.apple.driver.AppleRSMChannel	1
com.apple.iokit.IORSMFamily	1
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleIISController	200.2
com.apple.driver.AppleAudioClockLibs	200.5
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	334.0.1
com.apple.driver.IODARTFamily	1
com.apple.driver.FairPlayIOKit	68.19.0
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.security.AppleImage4	5.0.0
com.apple.kext.CoreTrust	1
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	12.0

** Stackshot Succeeded ** Bytes Traced 306265 (Uncompressed 788720) **

**Comment by ajay-gh** [comment]
Hi there, not easy to help, and I hope somebody more experienced is going to help. But until then please consider the following:
- when Ventura got released, Vera 1.25.9 was already out,
- I have seen cases before where a major release of osx required some adjustment in Vera (or Vera + fuse),
- so you might consider going back to Monterey with the same versions of Vera and oxfuse (cause I know for sure that this works),
- if this cannot be done, check carefully if you installed other software which interferes with Vera/fuse
- Odrix will probably not respond to your post, but it's not unlikely that Vera sees an update in Jan. or Feb.
No easy solution, sorry pal.

**Comment by usur-10** [comment]
Hi @ajay-gh , thank you for your help.

Apart from Veracrypt, i only had installed a Signal messenger app and an authenticator app. I will uninstall them and see if it helps. If positive, I will update the outcome to this post. 

As I don't have many apps installed yet, and the problem comes with a fresh new M1 laptop, and latest software versions of OS, Veracrypt, Macfuse.  So I thought it would be more common, but unfortunately that I haven't seen any post reporting this problem (and possible solution).

I'm going through a stiff learning curve with MacOS, the prospect of going back to Monterey is quite daunting and unfortunate. I hope someone else had similar problem and was able to solve/ bypass it.

**Comment by bfleischer** [comment]
The panic seems to be triggered in the macOS kernel code, not in the macFUSE code. The macFUSE kernel extension is loaded at the time of the crash, but so are more than 100 other kernel extensions.

From what I can tell, VeraCrypt mounts an auxiliary volume that contains a disk image. This disk image is then mounted using standard macOS tools. It might be that the the disk image becomes unresponsive or gets stuck in a busy state. This could have many causes. I don't remember this panic being reported before for any other macFUSE-based file system. This means, it could be a VeryCrypt bug. I think this is something the VeraCrypt team needs to look into because they know their code best and they should be able to check whether their disk image (or file system) becomes unresponsive/busy prior to the crash.

That being said, I tried reproducing the crash on Ventura using VeryCrypt 1.25.9, but I have not been able to. Can you provide detailed repro steps?

**Comment by usur-10** [comment]
Hi @bfleischer, thank you for looking into this!

First thing after the laptop restarts, I opened Veracrypt and mounted an external SD card. I will then had to enter the laptop's administrator password. The volume mounted successfully.

In the latest mount, I was opening various folders in the mounted volume using Finder.  Some of the folders' content are intact. But in some other folders, the content is blank, none of the files there were shown. (The files were not lost :  when I mounted the SD card on my old Windows laptop afterward to check, those files were still there.) It was during this browsing and checking of the folders that the system crashed and restarted again.  Btw, I had removed all the other apps except for Veracrypt.

In previous mounts, the system would crash usually within 20-60 minutes after the volume is mounted,  either when a file from the mounted volume was being open or not, even when the laptop is left idle with no other app is running except perhaps Chrome some times.

Is that the detailed repro steps you were looking for, or you were referring to some technical log?

**Comment by ajay-gh** [comment]
Just one related note, it may help.
When I moved from High Sierra to Catalina, and kept Vera 1.24.7 (I think) and Fuse 3.3.1, it worked fine.
When I updated Vera to 1.25.9, multiple strange errors occurred, The usual tricks (restart, reinstall etc.) didn't help. Upgrade to Fuse 4.0.1 (at the time the latest release) didn't help either. 

So I had no other option than to go back 1.24.7 and Fuse 3.3.1 (if I wanted to keep Catalina). And guess what, that did NOT work either. Only when I completely removed Vera and Fuse, and all related files, and then installed both the older versions, Vera would work again.

Fast forward 12-18 months. I had to move on to Monterey. When I installed 1.25.9 and Fuse 4.4.1 this time every thing worked fine. Therefor my conclusion. The requirements listed on veracrypt.fr (minimum version requirements, for each osx) are somewhat misleading. This could explain why - when you install what seems needed - you still get an error message.

My conclusion: there is only certain valid combinations of Vera, Fues and osx which work as they should. Other combinations, even when permitted, have problems. And it is of course hard for the devs to check out all possible combinations before release of a new version. My guess, they only test latest releases on the latest osx version.

**Comment by usur-10** [comment]
Thanks @ajay-gh,  you got me trying to do the same thing. I installed older versions of Fuse, and/or older version of Veracrypt. The problem occurred markedly less than before but they didn't go away.

I suspected that it was because my thunderbolt to USB port adapter hub developed some fault randomly. ( My encrypted device was an external HDD with an USB connection, so I had to use the adapter to connect to my M1 laptop) I switched to encrypt a file container on my Mac itself and used that instead of an external hdd. The problem is gone.

I haven't tested my adapter hub yet to confirm if it was definitely the cause. But i'd like to update you all in case someone may find it useful.

Thank you all for your help!

**Comment by bfleischer** [comment]
> I switched to encrypt a file container on my Mac itself and used that instead of an external hdd. The problem is gone.

That's interesting. It means the issue is most likely not caused by macFUSE/VeraCrypt, at least not directly. There are many different components involved when mounting the encrypted container in this particular case: the external drive itself, your adapter/hub, VeraCrypt, macFUSE, the disk image kernel code, ... It's hard to tell what might be causing the issue.

**Comment by TheCorio** [comment]
For me, the mac OS crash was right after physically removing a flash-stick, while the encrypted volume was still mounted. Was able to repro this two times. See the log attached. Windows didn't crash in this scenario.

[panic-full-2023-08-04-152541.0002.panic.txt](https://github.com/osxfuse/osxfuse/files/12260862/panic-full-2023-08-04-152541.0002.panic.txt)
