### ISSUE TITLE
No defined app to open "Install macFUSE.pkg"

### ISSUE THREAD

**Issue by Meddul** [osxfuse/osxfuse#932]
So I just installed Ventura and need macFUSE to install VeraCrypt. I downloaded the latest version and when I double click the InstallmacFUSE.pkg icon I get a Finder pop up which says ' "There's no defined app to open the document "Install macFUSE.pkg" ' (rough translation from spanish). How can I fix that?

It used to work just fine on Big Sur. Now I'm in Venture 13.1, tried older version of macfuse and get the same missing app error. What app am I supposed to install to open the installer?

EDIT: Okay I managed to bypass that warning right clicking the file to see the original, right clicking again the original pkg and selecting Installer.app inside the "open with" menu. I'm pretty sure it's an issue tho and should run normally after double clicking.

**Comment by ajay-gh** [comment]
try https://github.com/osxfuse/osxfuse/releases/download/macfuse-4.4.1/macfuse-4.4.1.dmg
instead,

**Comment by ugachaka-design** [comment]
Same issue here, but after opening .pkg file of the latest 4.4.1 version i get an error message: 
"Unable to instal application macFUSE 4.4.1.pkg; it is not supported on this Mac."

I'v just upgrade macOS to Ventura 13. Help!

**Comment by lordpengwin** [comment]
I have the same problem with https://github.com/osxfuse/osxfuse/releases/download/macfuse-4.4.1/macfuse-4.4.1.dmg

**Comment by lordpengwin** [comment]
Turns out that you have to click on the package under the Extras directory of the DMG file, not the link at the top level.

**Comment by Birat30** [comment]
i am not able to install macfue to use my pcloud.please advise how can i install

**Comment by bfleischer** [comment]
This issue will be resolved in the next release. The "Install macFUSE" item in the root of the distribution disk image is a soft link to the actual installer package in the "Extras" subdirectory. macOS 13.1+ seems to be unable to follow this soft link and open the actual installer package when the soft link is double-clicked. This does not make much sense and I consider this a bug in macOS. Using a hard link instead of a soft link seems to resolve this issue, though.

**Comment by bfleischer** [comment]
@Birat30 Please note that pCloud uses a special version of macFUSE that is integrated into the pCloud app itself. Make sure to use the latest version of the pCloud client app. If this does not resolve the issue, please get in touch with pCloud support.
