### ISSUE TITLE
ENOTCONN issue

### ISSUE THREAD

**Issue by ashitaka3000** [osxfuse/osxfuse#933]
Hi,

We have a bug with our LTO backup system and my search for a solution brought me here.

We're using a software called YoYotta to do the LTO backups, which requires MacFuse: https://yoyotta.com/help/fuse.html.

For some time now we experience the strange behaviour, that writing to the LTO tapes works fine, but when the software tries to read the written data back to verify it, the process is freezing and will abort.

The error log is giving us this:
Verify socket not connected (ENOTCONN) reading file
...
Verify error file size 0 should be 2749153400

I was already speaking to YoYotta, as well as the hardware manufacturers involved, but none can really understand or explain what an ENOTCONN issue might have to do with this.

Could it be the case that this might have something to do with macFuse?
I was searching the issues and found that someone else encountered an ENOTCONN issue using macFUSE.

Here's our system specs:
iMac Pro (2017) 
3 GHz 10-Core Intel Xeon W 
64 GB 2666 MHz DDR4 
Radeon Pro Vega 64 16 GB
Monterey 12.6.1

macFUSE 4.4.1

To eleborate: The LTO drive rack is connected to the iMac via Thunderbolt.
Within the Thunderbolt rack sits a Thunderbolt to ATTO SAS card, which then is connected to the LTO drives.

The source drive of the data written to the LTO tapes is also connected to the iMac via Thunderbolt.
We tried to pull the data from a NAS via LAN as well, which created the same error, BUT, interestingly, also complelety disruted the NAS LAN connection. It was not reachable from any computer any more after the error happenend and we had to cold restart it. Also the LAN of the iMac didn't work any more.

Thanks a lot for any hint!

**Comment by bfleischer** [comment]
`ENOTCONN` is usually returned when the file system is considered dead. This can have various causes. The most likely cause is the file system being unresponsive for too long.

Please know that YoYotta, even though they are using macFUSE commercially, is not paying for macFUSE or supporting the macFUSE project in any way. As such I kindly ask you to raise the issue with the YoYotta support team. If they don't know what's causing the issue, they are free to contact me.
