### ISSUE TITLE
Not working on macOS Ventura 13.2

### ISSUE THREAD

**Issue by Fipsa** [osxfuse/osxfuse#935]
Not working on macOS Ventura 13.2

**Comment by bfleischer** [comment]
I'm sorry, but the issue description is not helpful at all. What exactly is not working for you? macFUSE 4.4.1 works fine for me on macOS 13.2

**Comment by sxlwar** [comment]
It prompt "The application to open the document Install macFUSE is not set " when I click the install button.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/20088392/218358342-db39eb8c-acdd-480e-863d-d9907634e927.png">

**Comment by Mig-Les-Tours** [comment]
Hello,
I have the same problem with the installation, I get the message : 
No application is configured to open the "Install macFUSE" document

for info, I have the version 13.2.1 macOS

**Comment by bfleischer** [comment]
@Mig-Les-Tours @sxlwar Your issue is a duplicate and tracked as ticket https://github.com/osxfuse/osxfuse/issues/932. It will be fixed in the next release. In the meantime, open the "Extras" directory and double click the Installer there.

**Comment by bfleischer** [comment]
@Fipsa Could you please provide a more detailed error description? Otherwise, I'm going to close the issue soon.

**Comment by Mig-Les-Tours** [comment]
I changed the format of my hard drive to exfat
