### ISSUE TITLE
OSXFUSE and MACFUSE - both installed in same MacOS

### ISSUE THREAD

**Issue by sndbbbl** [osxfuse/osxfuse#938]
in the SYSTEM PREFERENCE pane, I have MACFUSE and OSXFUSE. MACFUSE is the current running version, OSXFUSE must be from a (much) earlier installation. When clicking the UNINSTALL BUTTON, nothing happens. GO TO DEVELOPPERS WEB SITE leads to https://osxfuse.github.com/ which is not available.

Can anybody tell us how to UNINSTALL this?

Thank you,
JPC

<img width="652" alt="Screenshot 2023-02-27 at 21 53 25" src="https://user-images.githubusercontent.com/14177299/221683778-51b33d34-9700-430c-940b-637d5a20cd09.png">

<img width="780" alt="Screenshot 2023-02-27 at 21 53 34" src="https://user-images.githubusercontent.com/14177299/221683819-a04e67fe-b561-4598-bc8c-c046f66d053b.png">

**Comment by bfleischer** [comment]
Right-click on the "FUSE for OS X" preferences pane in System preferences and click on "Remove ..." in the context menu to remove the old preference pane.

When installing macFUSE, old "FUSE for OS X" (osxfuse) installations are removed automatically. Most likely, you got into this situation by installing an old "FUSE for OS X" version after installing macFUSE.

**Comment by sndbbbl** [comment]
> Right-click on the "FUSE for OS X" preferences pane in System preferences and click on "Remove ..." in the context menu to remove the old preference pane.
> 
> When installing macFUSE, old "FUSE for OS X" (osxfuse) installations are removed automatically. Most likely, you got into this situation by installing an old "FUSE for OS X" version after installing macFUSE.

Thank you - I have tried that already. But it does not work.

When clicking on the REMOVE OSXFUSE button, MacOS asks me to enter the admin's password. After entering it, there is a dashed spinning wheel in the control panel for approx 1 second, then it stops. Nothing is removed.

When clicking on the UPDATE button which is right next to it, it says: UNABLE TO CONTACT THE SERVER.

So I am stuck with it here...

Any other suggestions? --thank you!

**Comment by sndbbbl** [comment]
Another idea... you said that it is being removed automatically when new versions of macFUSE... I could try to remove macFUSE and reinstall it - that also should remove the old version?

**Comment by bfleischer** [comment]
> When clicking on the REMOVE OSXFUSE button, MacOS asks me to enter the admin's password. After entering it, there is a dashed spinning wheel in the control panel for approx 1 second, then it stops. Nothing is removed.

I think there has been a misunderstanding. Leave the "FUSE for OS X" preference pane. Back in the System preferences overview (your first screenshot), right-click (or control-click) on the "FUSE for OS X" preferences pane and click on "Remove ..." in the **context menu** to remove the old preference pane. 

> Another idea... you said that it is being removed automatically when new versions of macFUSE... I could try to remove macFUSE and reinstall it - that also should remove the old version?

If you want to try this download the installer from https://macfuse.io, double-click it, go to the Extras directory and run the uninstaller. The uninstaller in the disk image *should* remove all installed version of osxfuse/macFUSE. Then run the installer.

**Comment by sndbbbl** [comment]
Ah! yes, I did right-click on the PREFS-Pane, and the PREFS-Pane was gone.

This thread can be closed.

Greetings!
