### ISSUE TITLE
Red dot icon next to files and folders

### ISSUE THREAD

**Issue by Macadict** [osxfuse/osxfuse#939]
Macbook Air M1
OS 13.2
Mac Fuse 4.4.2

I get a red icon with an exclamation mark next to each of my files and folders.
The problem seems to come from MacFuse as last time I ran into the similar problem, I upgraded to the current version and all came back to normal.
![Screenshot 2023-03-01 at 10 40 56](https://user-images.githubusercontent.com/126665797/222220518-c655e9ad-56b3-4940-9b5f-aea49b174b7c.jpg)

**Comment by bfleischer** [comment]
Please raise this issue with the developer of the file system you are using (the application that required you to install macFUSE). macFUSE does not display any badges in Finder. This is most likely a feature of the application that provides the virtual volume.
