### ISSUE TITLE
C++ SDK

### ISSUE THREAD

**Issue by deepanshug** [osxfuse/osxfuse#940]
Hi, 

I very good morning!! I need some guidance on using macFuse using C++. Do you have any samples, references, documentation which can help me starting developing my own FS in mac.

Note: 
1. I am very new to Mac but have used winFSP on windows.

**Comment by bfleischer** [comment]
macFUSE does not include a C++ specific SDK. However, you could use the libfuse C SDK. There might be a third-party C++ wrapper you could use. You can find the macFUSE reference file systems for C, Objective-C and Swift in https://github.com/macfuse/demo.
