### ISSUE TITLE
Install headers to /opt/fuse please

### ISSUE THREAD

**Issue by beren12** [osxfuse/osxfuse#941]
Would it be possible to not dump the headers and shlibs in /usr/local? I noticed some things I build pick up on fuse and then don't work if I copy them to a machine without fuse installed. /opt/fuse would be a far better place as it's impossible to stop gcc/clang from using anything it finds in /usr/loca/ but it's dead simple to add -I /opt/fuse/include when you want to build against the fuse headers. Apple's X11 even does this and nothing has issues with it being there.

**Comment by bfleischer** [comment]
This won't be possible. Moving headers and shared libraries to a different location would break existing software.

That being said, I think it would be a better approach to update/fix the build configuration of the software you are trying to build.

**Comment by beren12** [comment]
Not exactly. Moving the headers and libraries won’t break anything as long as the library has a symlink in the old location. The problem with using /usr/local is there is no real way to not use it. It’s hard coded into gcc/clang. Disabling support in the makefile works yes but there’s a reason /opt/package exists.

**Comment by bfleischer** [comment]
When placing a symlink in /usr/local gcc and clang might pick it up. Moving headers to a different location means that most projects using macFUSE will need to be updated. I'm not going to introduce a breaking change like this to address a Makefile issue of another project. 

> Disabling support in the makefile works yes 

That's probably your best option.
