### ISSUE TITLE
Updating macFUSE triggers unwanted macOS updates

### ISSUE THREAD

**Issue by makramakramakra** [osxfuse/osxfuse#944]
Hi Benjamin,

to start with: What I'm about to describe, happens on unsupported legacy Macs using OpenCore Legacy Patcher. So my issue might have to do with what OpenCore does and I totally understand, if you won't bother reading this.

But maybe someone has an idea: For stability and security reasons I prefer to use Monterey instead of Ventura on those 2012 machines for the time being. I have disabled automatic OTA system updates, but after I update or install macFUSE, a system update starts in the background. So I've ended up with 13.3 several times on machines running Monterey or 13.2.1 before.

Someone else reported at MacRumors that he had experienced the same thing updating Broom, but apart from that it doesn't seem to be a common issue. 

So: Does the macFUSE installing process somehow differ from others?

Cheers
Martin

**Comment by bfleischer** [comment]
Hi Martin, 

the macFUSE installer just copies a bunch of files to `/Library/Filesystems`, `/Library/Frameworks` and `/usr/local` then it tries to load the macFUSE kernel extension. That's about it. There is no code in the macFUSE installer that actively triggers macOS updates. This is the first time an issue like this has been raised here. I don't think macFUSE is to blame for this.
