### ISSUE TITLE
After installing, lost access to ntfs WD My Passport

### ISSUE THREAD

**Issue by vertrek** [osxfuse/osxfuse#945]
I am on Ventura 13.3 on an M1 mac. I was able to read only my WD My Passport before installing macFUSE but wanted to try and get read write access. After installing it and enabling extensions, I couldn't get it to work. So I disabled the extension and uninstalled macFUSE, but now I can't even mount my WD drive. It always gives me the error: (com.apple.DiskManagement.disenter error 49223.)

What can I do to at least get it back to read only? I do not want to erase the drive.

edit: also lost access to my read only ability on my seagate external as well. so it disabled mounting ntfs external drives completely.

**Comment by bfleischer** [comment]
macFUSE is a framework for developing file systems. macFUSE itself does not provide support for reading or writing NTFS volumes. Judging from your description you installed a third-party NTFS driver that is using macFUSE to provide file system integration.

You need to uninstall the third-party NTFS driver. If you have trouble doing so, please raise the issue with the developer of the NTFS implementation you were using.
