### ISSUE TITLE
System Extension Blocked

### ISSUE THREAD

**Issue by 4pastor** [osxfuse/osxfuse#946]
I have used macFUSE with VeraCrypt for several years now on my macOS Ventura 13.2.1; now I am getting this error message saying: 

System Extension Blocked
The system extension required for mounting macFUSE volumes could not be loaded.

Please open the Security & Privacy System Preferences pane, go to the General preferences and allow loading system software from developer "Benjamin Fleischer". A restart might be required before the system extension can be loaded.

Then try mounting the volume again.

I followed the above instruction, but cannot find anything that give me the option to allow loading system software from "Benjamin Fleischer". 

Thanks for your help!

**Comment by bfleischer** [comment]
Please see https://github.com/macfuse/macfuse/wiki/Getting-Started
