### ISSUE TITLE
NTFS-3G: What is the difference between the two commands for manually mounting ntfs volumes in terminal?

### ISSUE THREAD

**Issue by lxne** [osxfuse/osxfuse#948]
On my mac (running Ventura) I tried both commands for manually mounting NTFS volumes:
`sudo /usr/local/bin/ntfs-3g /dev/disk1s1 /Volumes/NTFS -o local -o allow_other -o auto_xattr -o auto_cache
`
alternatively...
`sudo /usr/local/sbin/mount_ntfs /dev/disk1s1 /Volumes/NTFS `

Both work. The only obvious difference is the volume name of the mounted volume.
Are there any other important differences?
Speed/caching/…?

Best wishes

**Comment by bfleischer** [comment]
NTFS-3G and macFUSE are two separate projects. I'm not sure whether the `/usr/local/sbin/mount_ntfs` tool is maintained by the NTFS-3G team, but it might be best to raise your question with them.
