### ISSUE TITLE
SSHFS with sudo -i -u username NOT WRITE FILE or FOLDERS

### ISSUE THREAD

**Issue by LandiLuca** [osxfuse/osxfuse#949]
OSX Ventura 13.3.1
osxfuse update.

If I launch from terminal:
sshfs username@ip:/path/to/folders /path/to/local/folders -o sftp_server="sudo -i -u username /usr/lib/openssh/sftp-server"

it mount the folders in my finder, but if I try to create/edit a file, rename/create folder I can't, permission denied.

The same sshfs works on other mac with osx version <= 12

Is there something else to know?

**Comment by bfleischer** [comment]
Could be related to uid/gid mapping. Try mounting with the `defer_permissions` option (https://github.com/macfuse/macfuse/wiki/Mount-Options#default_permissions-and-defer_permissions).

This ticket has been inactive for a long time, so I'm closing it. Feel free to re-open the ticket in case this is still an issue.
