### ISSUE TITLE
Volume unmounts after 4 seconds

### ISSUE THREAD

**Issue by kondak3** [osxfuse/osxfuse#950]
Hi Team

You mention macFuse 4.4.3 unavailable VFS plugin issue fixed. 
But still getting this issue. After mount within 4 sec volume automatically unmounted.

My MacBook Pro configuration:
- macOS 13.3(Ventura) 
- Apple M1 Chip Processor
- macFuse 4.4.3. 

Please help on this.

**Comment by bfleischer** [comment]
That's a completely different issue. What file system are you using?

**Comment by kondak3** [comment]
We are using "LoopbackFS-Swift" from this demo "https://github.com/macfuse/demo".

**Comment by bfleischer** [comment]
Did you modify the demo?

**Comment by kondak3** [comment]
Yes, Removed NSOpenPanel code and create source folder inside the document directory. 
rootPath assign as source folder path, remaining code same.

**Comment by bfleischer** [comment]
Do you encounter the same unmounts with the unmodified demo project?

**Comment by kondak3** [comment]
Same demo not getting any issue. But only rootPath added statically. It's freezing the system and unmount.
```
self.rootPath = "/Users/XXXX/Downloads"

Got didMount notification.
fuse: writing device: Socket is not connected
Got didUnmount notification.
```

**Comment by kondak3** [comment]
do we have any observer to identify the "fuse: writing device: Socket is not connected" in macfuse.framework
