### ISSUE TITLE
Remotely enabling the kernel extension

### ISSUE THREAD

**Issue by alexbet** [osxfuse/osxfuse#952]
In order to install macFUSE installation, I need to reboot a Mac with an M chip, enter Startup Security Utility and allow the kernel extension. This is all great if I physically have the computer in my hands. However, I work with computers remotely, and enabling the kernel extension seems impossible.

My question is, is there a way for me to enable the kernel extension remotely. I can work in Terminal remotely, so that is not a problem, if this can be done through Terminal.  It would make a world of a difference for me if I can do this remotely.

**Comment by bfleischer** [comment]
I think you can enable kernel extensions remotely, if you enroll the Mac in MDM. See https://support.apple.com/guide/deployment/dep88f99b98a/web.
