### ISSUE TITLE
osxfuse only in read-only mode even with root access

### ISSUE THREAD

**Issue by MoerkyMark** [osxfuse/osxfuse#953]
I am using 13.3.1 (a) (22E772610a) and tried osxfuse for the first time.
I mount a share with `sshfs root@IP:/some/share /Users/markus/someshare/`
which works fine but when I try to change something in that directory
with  `sudo mkdir test`
I get a 
`mkdir: test: Operation not permitted`

**Comment by bfleischer** [comment]
Have a look at the `defer_permissions` mount option:

https://github.com/macfuse/macfuse/wiki/Mount-Options#default_permissions-and-defer_permissions

Alternatively, I recommend looking into mapping uid and gid when using sshfs.
