### ISSUE TITLE
MacOS Ventura where to mount drives

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [osxfuse/osxfuse#955]
Thanks for this great tool!

Under Catalina, I was using `/mount` as a hub for my mounted drives, but with Ventura the root folder is read-only (I don't want to disable SIPS just for this), so I'm unable to create my usual folder.  I also prefer a location outside `/Users` so others can access the shared drive without having to enter my workspace.

What would be a good choice for a mount point at an alternate location? `/Volumes`?

**Comment by kapitainsky** [comment]
You can still use /mount but it has to be created with synthetic firmlink via /etc/synthetic.conf

https://derflounder.wordpress.com/2020/01/18/creating-root-level-directories-and-symbolic-links-on-macos-catalina/

it works with Ventura as well


You can make /mount a symbolic link to /private/mount
 like tmp -> /private/tmp
