### ISSUE TITLE
Failing to mount DMG install Package

### ISSUE THREAD

**Issue by xagudo** [osxfuse/osxfuse#956]
Hi, 
I'm on A Mac Studio (M1) with OS Ventura, and I'm trying to install the newest MacFuse 4.4.3 and I keep getting a "Failed to mount filesystems" error, see screenshot. When I install on an iMacPro I have no problem, so it makes me think it's a n Apple Silicon problem. I have tried in 3 different machines and it's the same. Anyone seen the same issue? I have tried all "fixes" found on the net, but nothing works. Any help would be appreciated, thanks!

<img width="260" alt="Screenshot 2023-05-25 at 09 07 48" src="https://github.com/osxfuse/osxfuse/assets/134589784/245994bd-fb1c-4f5c-9517-280868a47757">

**Comment by bfleischer** [comment]
I've never seen this error message before. Unfortunately, I have no idea what to do about it, but I can assure you that the disk image mounts fine on Intel and Apple Silicon Macs on Ventura. It's even built on an Apple Silicon Mac under Ventura. I think this is probably a localized issue affecting only your Apple Silicon Mac. Maybe some settings are off. The Disk Image file system is HFS+, as it has been for ages.
