### ISSUE TITLE
macOS 14 beta(235257q) Sonoma macfuse fail to load

### ISSUE THREAD

**Issue by fancymemphis** [osxfuse/osxfuse#957]
# Environment

- macOS 14 beta(235257q)
- macfuse 4.4.1

# Problem
**Executing the following cmd on macOS 14 beta Sonoma failed:**

`sudo kextutil /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext `

# Output log:

```
Executing: /usr/bin/kmutil load --bundle-path /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext

Error Domain=KMErrorDomain Code=71 "Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)" 
UserInfo={NSLocalizedDescription=Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)}
```

**Comment by eprisencc** [comment]
MacFuse won't load for me either.

**Comment by pafofi** [comment]
It's shame that an OS which is already 10 hours old is still not supported... OK, just kidding, all the best to the dev for the work to come to make it happen!

**Comment by pole9999** [comment]
Yes, we'd like our version of MacFuse to be compatible with the Sonoma Beta, I'm sure you're already on the problem, I encourage you and thank you;

**Comment by bfleischer** [comment]
The new macFUSE 4.5.0 release adds experimental support for macOS 14.
