### ISSUE TITLE
Support Nix Installation Paths

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [osxfuse/osxfuse#959]
I'm working on improving [Nix](https://nixos.org) support for macOS and will use macFUSE to implement some functionality. I was able to install macFUSE using Nix itself, but there are some hardcoded paths preventing `load_macfuse` and `mount_macfuse` from working inside the Nix Store.

For those unfamiliar with Nix, when you install something with it, all necessary files are stored inside the Nix Store (e.g. `/nix/store/a9gx75367c5rficw9c2vakfcc8r5pz0a-macfuse-4.5.0`). So instead of having `macfuse.fs` placed on `/Library/Filesystems`, it goes to `/nix/store/a9gx75367c5rficw9c2vakfcc8r5pz0a-macfuse-4.5.0/Library/Filesystems` when installed via Nix.

Would it be possible to make macFUSE portable so it can run from different locations? On the open source version, this was possible by defining custom values for `--framework-prefix`, `--fsbundle-prefix`, and `--library-prefix`. But that would need to be changed from compile-time to run-time anyway, given the project is no longer open source.

Something like https://tapesoftware.net/replace-symbol could work, but that would break the code signature...

These are the hardcoded paths:
- `load_macfuse`: `/Library/Filesystems/macfuse.fs/Contents/Extensions`
- `mount_macfuse`: `/Library/Filesystems/macfuse.fs/Contents/Resources/Volume.icns`
- `mount_macfuse`: `/Library/Filesystems/macfuse.fs`
- `mount_macfuse`: `/Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse`

Related: https://github.com/osxfuse/osxfuse/issues/1

**Comment by bfleischer** [comment]
macFUSE is a shared component. From a technical standpoint, it would be possible to install it to a different location, but macOS will only ever load one macFUSE kernel extension at the same time.

* Installing macFUSE to a non-standard location means there could be more than one version of macFUSE installed at the same time. This will result in compatibility issues and third-party tools won't be able to find libfuse.
* It also means that macOS will not be able to look up file system names from the macFUSE file system bundle.
* The macFUSE uninstaller would break.
* The preference pane would not be recognized by macOS.

There are probably more issue.

What would be the benefits of making macFUSE portable?

**Comment by bfleischer** [comment]
I'm closing this issue. Feel free to re-open it case it becomes relevant again.
