### ISSUE TITLE
How to avoid Mac OS scanning the mount directory?

### ISSUE THREAD

**Issue by GeorgeDylanChang** [osxfuse/osxfuse#961]
I use macfuse to mount s3path, but the system always scans the mount directory, which can cause many unnecessary requests...

**Comment by bfleischer** [comment]
I assume you are referring to the generation of icon previews. You should be able to disable this feature in Finder's View options. See https://osxdaily.com/2013/01/10/disable-finder-icon-thumbnails-previews-mac-os-x/.
