### ISSUE TITLE
Executing: /usr/bin/kmutil load -p /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext

### ISSUE THREAD

**Issue by Lucax699** [osxfuse/osxfuse#964]
I am getting this error when using TrueCrypt. I have finished encrypting a file on TrueCrypt. I choose the correct encrypted file to mount, it shows an error like the title. Details as below. Can anyone help me with this error.
   - I use macbook pro m1 13" , OS Monterey 12.6.2 . 
   - TrueCrypt 7.1a download on truecrypt.org

<img width="753" alt="image" src="https://github.com/osxfuse/osxfuse/assets/112509430/f98d2774-bd79-4b07-a3b8-2ede2df893f7">

Error Domain=KMErrorDomain Code=71 "Incompatible architecture: Cannot find arm64e in fat binary
Unsupported Error: one or more extensions are unsupported to load 	Kext com.github.osxfuse.filesystems.osxfusefs v2.3.8 in executable kext bundle com.github.osxfuse.filesystems.osxfusefs at /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext
Unsupported Error: one or more extensions are unsupported to load 	Kext com.github.osxfuse.filesystems.osxfusefs v2.3.8 in executable kext bundle com.github.osxfuse.filesystems.osxfusefs at /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext" UserInfo={NSLocalizedDescription=Incompatible architecture: Cannot find arm64e in fat binary
Unsupported Error: one or more extensions are unsupported to load 	Kext com.github.osxfuse.filesystems.osxfusefs v2.3.8 in executable kext bundle com.github.osxfuse.filesystems.osxfusefs at /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext
Unsupported Error: one or more extensions are unsupported to load 	Kext com.github.osxfuse.filesystems.osxfusefs v2.3.8 in executable kext bundle com.github.osxfuse.filesystems.osxfusefs at /Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext}
the OSXFUSE file system is not available (71)

**Comment by Lucax699** [comment]
Encrypted file I created with TrueCrypt

<img width="253" alt="image" src="https://github.com/osxfuse/osxfuse/assets/112509430/179ebe54-c094-4b88-9619-772456f5f32e">
<img width="730" alt="image" src="https://github.com/osxfuse/osxfuse/assets/112509430/8a9d6f0b-42ec-4766-ae58-2f486e982b31">

**Comment by Lucax699** [comment]
Help meee

**Comment by bfleischer** [comment]
You are trying to use a very outdated version of FUSE on an Apple Silicon Mac. Please update macFUSE to the latest version and you might need to use VeryCrypt instead of TrueCrypt.
