### ISSUE TITLE
Help me fix : could not locate target partition 14 not found

### ISSUE THREAD

**Issue by Lucax699** [osxfuse/osxfuse#965]
I can't boot into win10. I got the error could not locate target partition 14 not found.

I checked D:\EFI\Boot there is file bootx64.efi already

![image](https://github.com/osxfuse/osxfuse/assets/112509430/75b894ae-b568-4b55-97cd-990b10bab868)

**Comment by bfleischer** [comment]
I'm closing this because it is not a macFUSE issue.
