### ISSUE TITLE
macFUSE 4.5.0 - file move breaks Finder access

### ISSUE THREAD

**Issue by dswiss-desktop-app** [osxfuse/osxfuse#967]
Hi, I am not sure if this is a bug in macFUSE or in macOS (KEXT? Finder?). Here is how to reproduce it with the loopback example:
- mount a folder with the loopback app, use standard parameters: 
`./loopback /Users/maciej.kwiatkowski/test -omodules=threadid:subdir,subdir=/tmp/dir -oallow_other,native_xattr,volname=LoopbackFS`
- in the folder create two subfolders and add a text file to one of them,
- open the folder in Finder, open the file double-clicking on it, close the Console app,
- move the file to the other folder and try to open it again from Finder - nothing happens.

The logs show that rename() was called successfully but Finder tries to open the old location of the file! When the file is moved again to the original folder, it still fails to open as now Finder tries to access it from the previous folder.

**Comment by bfleischer** [comment]
I have not been able to reproduce the issue on macOS 13.6.3, 14.2.1 and the upcoming 14.3 using the latest version of the loopback demo file system from https://github.com/macfuse/demo and macFUSE 4.5.0. On which version of macOS have you been running into this issue?

**Comment by dswiss-desktop-app** [comment]
Hello mr Fleischer, thanks for looking into it. We experienced problems on macOS 12 (Monterey). I can confirm the issue seems solved on macOS 14. On macOS 13 we are able to reproduce it only in a virtual machine running on a very specific hardware setup.
