### ISSUE TITLE
Recovery mode not accessible after installing macFUSE 4.5

### ISSUE THREAD

**Issue by amirian** [osxfuse/osxfuse#969]
After installing macFUSE on macbook10,1 with Ventura 13.5.1 and BOOTCAMP, the command-R key combination gets stuck in showing the Apple logo instead of entering recovery mode. I uninstalled macFUSE as it didn't work only showing the app in system settings (even don't know how it should work!) and afterwards I succeeded to enter recovery mode but only once. Would I need to reinstall Ventura?

**Comment by bfleischer** [comment]
macFUSE is completely passive and does not interfere with the boot process of your Mac. There is no way any macFUSE code is executed this early in the boot process. macFUSE is not loaded in recovery mode.

Assuming you tried using macFUSE to mount your Windows volume in read/write mode, you need an actual NTFS driver, like NTFS-3G. NTFS-3G requires FUSE to mount NTFS volume. You cannot mount Windows volumes using macFUSE alone. 

> Would I need to reinstall Ventura?

I have no idea what's going on on your Mac, but I don't think macFUSE is to blame for this. If you are unsure about reinstalling macOS, it might be best to get in touch with Apple support.
