### ISSUE TITLE
Using rclone to access Dropbox results in frequent "Error -36" alerts on macOS 12.6.7

### ISSUE THREAD

**Issue by DarrenPIngram** [osxfuse/osxfuse#971]
Has Apple's legendary software quality and rigorous testing broken parts of OSXFUSE, or made it less reliable? Sometimes you have to try and copy the same set of files several times.

Getting quite frequent error 36's with copying by Finder, that did not exist before the last system upgrade they demanded. It was rock solid to the same endpoints before so my finger is more likely to point at Apple. 

Yes, I know, upgrading with Apple is always risky, sigh...

Not sure if there's any logging I can give to help.

**Comment by bfleischer** [comment]
Which FUSE file system are you using? Did you raise the issue you are running into with the developer of the specific file system?

**Comment by DarrenPIngram** [comment]
Standard MACOS fs [linked to Dropbox]. Dropbox is fine on Linux servers and the issue seems to occur post upgrade in MacOS13. I'm not a developer, so there's only the Apple feedback route and I suspect you need a Ouija board with that, based on past experience of being ignored [and of others saying similar].

But maybe it is some isolated grumpiness but there's no real way to identify it so far other than the less-than-helpful dialog. Nothing seemed to show in the mounted terminal window.

**Comment by bfleischer** [comment]
@DarrenPIngram I'm sorry, but DropBox does use macFUSE at all. I still have no clue how macFUSE might play a role in the issue you are describing. Which macFUSE-based file system are you using? Could you provide more information about the way you are using macFUSE?

**Comment by DarrenPIngram** [comment]
I think you answered this a while back with clarification. Essentially in any case macFUSE mounted [as helper] with rclone for file access. The problem is probably elsewhere then, but it is sporadic. It's not happened for a while.
