### ISSUE TITLE
Duped fd is never sent ENODEV

### ISSUE THREAD

**Issue by griff** [osxfuse/osxfuse#974]
I am using [fuse-backend-rs](https://github.com/cloud-hypervisor/fuse-backend-rs) to talk to MacFUSE and it supports multithreaded channels and so will dup the fd sent from mount_macfuse and blockingly read and write to the copies.

The problem is that when the file system is unmounted only a single copy of the fd receives ENODEV and the others keep blocking on read. On linux all the copies of the fd receive ENODEV.

**Comment by bfleischer** [comment]
Thanks for the bug report. The issue will be fixed in the next release.
