### ISSUE TITLE
macos 13.6 kextutil load error KMErrorDomain Code=71 

### ISSUE THREAD

**Issue by fancymemphis** [osxfuse/osxfuse#976]
- SystemVersion:  M1; macOS 13.6; 
- Fuse： 4.5.0

→ **sudo kextutil /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext**

`2023-10-08 11:56:23+08 MacBook-Air package_script_service[16829]: ./postinstall: Error Domain=KMErrorDomain Code=71 "Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/C394DF95-D923-4EC9-8C7D-9FDAB88BDACE/boot/1F70E07482C12FB085EAC26AC24F9AA88659AF768F3E9E21162B4A0EEC0601A92B67F58B261E2C1F7B0F58178AB59C7F/System/Library/Caches/com.apple.kernelcaches/kernelcache" UserInfo={NSLocalizedDescription=Could not find: Unable to get contents of boot kernel collection collection at /System/Volumes/Preboot/C394DF95-D923-4EC9-8C7D-9FDAB88BDACE/boot/1F70E07482C12FB085EAC26AC24F9AA88659AF768F3E9E21162B4A0EEC0601A92B67F58B261E2C1F7B0F58178AB59C7F/System/Library/Caches/com.apple.kernelcaches/kernelcache}
`

**Comment by bfleischer** [comment]
This is not a macFUSE issue. According to the printout, macOS is unable to get the contents of the boot kernel collection, (which is managed by macOS, not macFUSE). Your macOS installation might be damaged.

**Comment by fancymemphis** [comment]
I would have a check.thanks!
