### ISSUE TITLE
MacFUSE/VeraCrypt not working with OS13 and OS14 (error = kext load failed- -603947007)

### ISSUE THREAD

**Issue by diver1008** [osxfuse/osxfuse#978]
I have the following situation.  I use VeraCrypt (VC) (version 1.25.9) that use MacFUSE (version 4.5.0).  Presently we use OS12 (belt and braces approach learned from Apple Tech People long ago, “Never upgrade to the newest OS, let others test and wait till most bugs are out.”) and want to move to OS 13.

In order to be following the belt and braces approach I am testing all our applications on an external USB SSD connected to a M1 MBP, with the new system installed on the USB SSD.  All applications work as should, except VC that use MacFUSE.

I get the flowing error that I believe is a MacFUSE error.

      kext load failed- -603947007
      mount_macfuse- the file system is not available (255)

I removed and installed MacFUSE, rebooted several times, checked security settings etc. all seems OK.  But maybe I missed something.
We use the latest version of MacFUSE.

Does anybody have any idea as to what I am missing here or why it does not work?  I see in the MacFUSE forum that it is confirmed (a different problem as mine) that MacFUSE works with OS 13 and OS 14.

**Comment by aurdoc** [comment]
I have exact same problem trying to use VeraCrypt 1.26.7 on MacStudio 2022 M1-Max and Sonoma 14.0 beta (23A5312d) and SIP disabled on a clean install (no other apps or other extensions).

**Comment by diver1008** [comment]
Let's hope somebody knows a solution.  I am still testing over-here.

**Comment by aurdoc** [comment]
Update... this problem also persists on Sonoma 14.1 beta 3 (23B5067a)

**Comment by diver1008** [comment]
Thanks aurdoc.

**Comment by diver1008** [comment]
OK folks I solved it.  Due to the limitations Apple puts on KEXT files and the aim to do away with them all together in the future one cannot use KEXT files on a external SSD.

**Comment by aurdoc** [comment]
I will give it a try

**Comment by qinzhenlove** [comment]
> OK folks I solved it. Due to the limitations Apple puts on KEXT files and the aim to do away with them all together in the future one cannot use KEXT files on a external SSD.

Does that mean I will no longer be able to read or write to NTFS formatted hard drives if I install the MacOS on an external SSD?

**Comment by bfleischer** [comment]
@diver1008's findings are correct. Currently Apple prevents you from using third-part kexts when booting macOS from an external volume.
