### ISSUE TITLE
Reads with option -oblocksize=N, with N greater than 4096 fail when reading 4097 byte file.

### ISSUE THREAD

**Issue by CostaRich** [osxfuse/osxfuse#979]
First I fully appreciate this could be me doing something wrong, but I've looked high and low for several days now before opening an issue.  If this is indeed just wrong expectations on my part, apologies in advance.

I wrote a cgofuse client on osx using MacFuse 4.5.0 and Ventura 13.5..  While specifying **-odirect_io** this all worked fine, using whatever **blocksize** I wanted to choose.  I ported to linux and also worked fine.  Going back to my mac, I turned off **direct_io** and started getting problems with macFuse.  

When I run say md5sum file12x.txt,  I typically see reads that look like:

```
// WORKS:  -odirect_io -oblocksize=1048576
Read /file12x.txt offset 0 len 1048576 returning 4097
Read /file12x.txt offset 4097 len 1044479 returning 0

// WORKS:  -oblocksize=4096
Read /file12x.txt offset 0 len 4096 returning 4096
Read /file12x.txt offset 4096 len 1 returning 1

// FAILS:  -oblocksize= any power of 2 greater than 4096.
Read /file12x.txt offset 0 len 4096 returning 4096
Read /file12x.txt offset 0 len 4096 returning 4096
```

As you can see, in the case of a 4097 byte file (there are other cases that fail also, this was just the simplest) we don't get an updated 'offset' value for the second read. We end up getting the same 0 offset twice.

I will have access to a couple of other mac laptops this weekend and can try different versions in case there's an OS dependency.  

I stepped through all of the cgofuse wrapper code and don't see a problem there where we'd be zeroing the offset.  It's pretty thin.  I also tried building an older version of fuse but it no longer builds on Ventura.

Is this just me having the wrong expectation of how read works with these mount options?  

Many thanks in advance.

**Comment by bfleischer** [comment]
Is this still an issue?

**Comment by CostaRich** [comment]
At the time, I spent another few days working on it with several different mac's and as many combinations of options as I could.  It continued to show this behavior as described.  I am working on a different project now, but I can try to find some time to try it out on the newest versions of osxfuse.

**Comment by bfleischer** [comment]
I ran a quick test on macOS 14 using the loopback reference file system and set the blocksize to 8192 bytes.

I created a test file of 4097 bytes. 

    dd if=/dev/zero of=/Volumes/loop/test4097 count=4097 bs=1

I used dd to read the file in 4096 byte chunks just like in your example above. 

    dd if=/Volumes/loop/test4097 of=/dev/null bs=4096

This worked without any issues.

I think it's very odd that you receive read requests for 4096 bytes even though your `blocksize` is greater than 4096 bytes. This looks more like a cgofuse issue (or an issue with your file system implementation) than a macFUSE issue. macFUSE will always use chunk sizes of at least `blocksize` when issuing I/O.

Please raise the issue with the cgofuse team. Feel free to re-open this ticket in case there is any new information.
