### ISSUE TITLE
Advice for GUI / tray app for macFUSE

### ISSUE THREAD

**Issue by jo-chemla** [osxfuse/osxfuse#980]
Hi there,

We have a large count of SFTP servers we mount via sshfs on our mac laptops, via the corresponding terminal CLI commands. macFUSE has been very helpful in that regard, but we'd like to allow this capability to non tech-savvy users.

Is there a recommended GUI or tray application that would work similar to [rclone Tray](https://github.com/dimitrov-adrian/RcloneTray)?

Letting the user mount/unmount sshfs volumes that are stored within a config file would be great, thanks!

**Comment by bfleischer** [comment]
There used to be Macfusion but it is unmaintained and very outdated. Maybe there is a fork that is still maintained.

**Comment by jo-chemla** [comment]
Ok thanks. Rclonetray is useful as-is as well, although outdated as well.
