### ISSUE TITLE
Any ways to check whether the user should manually approve the kext update on macOS?

### ISSUE THREAD

**Issue by fancymemphis** [osxfuse/osxfuse#981]
macfuse is update on macOS 14 Sonoma. 
I want to find out how I can check a state when a user need to open "Security and Privacy" pane and approve the kext update.

I tried:

1. **kextstate | grep fuse** 

-  it shows whether fuse exists only which doesn't meet my requirement.

2. **sudo kextutil /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext**

- It works by checking the return code, but the problem is that it costs about 6s to execute the command which is too slow.

I am considering maybe some code in your source code have fixed it. What's your solution?

**Comment by bfleischer** [comment]
The best way to check whether the kernel extension is able to load is running the macfuse_load binary (located in the file system bundle). It will return `EPERM` in case the user needs to allow loading the kernel extension in the Security and Privacy preference pane.
