### ISSUE TITLE
Needed: Full guide on how to instal macFUSE on Ventura and later

### ISSUE THREAD

**Issue by DeeeDeee** [osxfuse/osxfuse#983]
Hello, community!
I found out this free open-source alternative and that's great! Has just installed in on my Macobook Pro with M2 and Ventura 13.3 OS. Managed to go though all the steps to allow the "Security and Privacy" panel and approve/allow. After a couple of restarts, the macFuse must be installed (I see in in at the bottom of the System Settings pannel). It must work... but not. It does not wants to WRITE on external drives (only reads).

Unfortunately, I am not a geek and a bit scared to do all the fine-tuning in the Terminal in order not to somehting wrong that could damage the OS... I checked people are using also [Homebrew](https://formulae.brew.sh/)... and some other extensions.

Is there any guide on how to install the macFuse for dummies? 
Thanks in advance!

**Comment by jelka71** [comment]
Sounds like it working just fine to me. 
Maybe the mount option "-o idmap=user" is missing - This sets ownership (UID) to the user.

**Comment by enoola** [comment]
Ventura it was working just fine, here is my alias command line :  
sshfs $MYHOST:/home/enola/Workspace $mntpath_medusa -oreconnect,volname=sshfsmedusa,sshfs_sync,no_readahead && cd "$mntpath_medusa" && ls -l && cd -'
user launching this isn't root on remote, nor on my mac.
MYHOST-> hostname/ip of your remote ssh host
mnt_medua->my mount point which is : /Users/enola/MNT_SSHFS/sshfs-medusa/
Now if you look just after mounting I am going to the mounted directory, then ls, then goes back. without doing this I used to have permission denied.

**Comment by bfleischer** [comment]
@DeeeDeee I'm assuming you are trying to access an NTFS-formatted volume. Please see https://github.com/macfuse/macfuse/wiki/Frequently-Asked-Questions
