### ISSUE TITLE
could not mount disk (com.apple.DiskManagement.disenter error -119930868.)

### ISSUE THREAD

**Issue by Glydric** [osxfuse/osxfuse#984]
When I try to mount a fuse-ext2 partition i get the following error
Could not mount “disk4s2”. (com.apple.DiskManagement.disenter error -119930868.)
Macos: 14.1.1 arm (M1 pro)
macfuse: 4.5.0

**Comment by bfleischer** [comment]
I think it might be best to raise the issue with the fuse-ext2 developer(s). I'm not sure if this is even caused by macFUSE and how I could reproduce the issue.
