### ISSUE TITLE
Can Fuse filesystem use ACLs without appledouble ._ files?

### ISSUE THREAD

**Issue by roblarose** [osxfuse/osxfuse#985]
I have a SAN and using Fuse (Projective.io Osiris) to make virtual filesystems from directories on the SAN.

I can apply ACLs to my SAN directories using chmod +a which are honored by macOS / Finder.. show up as ACEs that can be viewed with ls -le

But when I mount the Fuse filesystem, it does not see the ACLs on directories in the structure that are visible on the SAN volume iteslf.

If I run the mount using -oextended_security then I can apply ACLs to the mounted Fuse filesystem which seem to work.  It creates ._ file.  However those ACLs are not visible at the underlying SAN level, and the two are not shared.

Is there a way to have a single set of ACLs that are seen/honored by both the underlying SAN filesystem in MacOS / Finder and also the Fuse filesystem?

**Comment by bfleischer** [comment]
I think this depends on many factors. As far as I know, ACLs rely on extended attributes on macOS. That's why you are seeing those ._ files. Maybe your SAN file system or Osiris do not support extended attributes natively. This is something the Projective.io team would need to look into.

**Comment by roblarose** [comment]
Thanks, Benjamin.  The SAN filesystem does seem to support them just fine (I can apply them using chmod +a when no Fuse filesystem is involved).  I did ask the Projective support folks but they sent me to the bindfs and macfuse mount options to do my own research. Womp-womp.  So I guess I'm hoping there's a recipe to know if the Fuse filesystem should be able to see the ACLs on the underlying files...

**Comment by bfleischer** [comment]
It comes down to implementation details. The macOS kernel stores ACLs in the `com.apple.system.Security` extended file attribute. As far as I know, bindfs renames this attribute to `org.apple.system.Security` before writing the attribute to the backing storage. As a result Finder sees different ACLs depending on how the volume is accessed.

**Comment by bfleischer** [comment]
To answer your original question ...

> Is there a way to have a single set of ACLs that are seen/honored by both the underlying SAN filesystem in MacOS / Finder and also the Fuse filesystem?

Native support for extended attributes needs to be enabled for the bindfs mount (if it's not already the case) and bindfs would need to use the original `com.apple.system.Security` extended attribute instead of renaming it `org.apple.system.Security`.
