### ISSUE TITLE
Upgrade from MacOS 10.15.7--> 11.X, shall I upgrade MacFUse?

### ISSUE THREAD

**Issue by kalthad** [osxfuse/osxfuse#990]
HI
I installed 2 years ago MacFuse (I think it was 4.1.2) on my 10.15.7 MacOS.
It works in the sense that I have mounted three encrypted folders and the appear in my Desktop as MacFuse Folders/Containers.

 (when I reboot, I have to run a script that takes care of this:
the script looks like 
```
#!/bin/bash
ENCFS="/opt/sw/bin/encfs" 
ENCDIR3="$HOME/ALLES/Sod/.cryptstuff_encfs"
DECDIR3="$HOME/ALLES/Sod/cryptstuff"
security find-generic-password -ga encfs 2>&1 >/dev/null | cut -d'"' -f2 | "$ENCFS" -S "$ENCDIR3" "$DECDIR3"
```

but, I cannot find MacFuse in my Applications folder, strange.
I even managed to install macfuse via fink (and may this is why I don't find it any more in my Application folders. I wish I had written down all the steps)

Be it as it may my question concerns an upgrade from 10.15.7--> 11 (I don't dare to use any newer version).
Will I then need to upgrade MacFUse???

Since I do not remember all the steps, I'd rather prefer not do so.

thanks

Uwe Brauer

**Comment by bfleischer** [comment]
> but, I cannot find MacFuse in my Applications folder, strange.

That's because macFUSE is not an application. It's a system extension. This has nothing to do with the way you installed macFUSE.

> Be it as it may my question concerns an upgrade from 10.15.7--> 11 (I don't dare to use any newer version).
Will I then need to upgrade MacFUse???

macOS 11 is supported by all macFUSE releases since version 4.0.0. However, I recommend using the latest version of macFUSE instead of a severely outdated version.
