### ISSUE TITLE
macFUSE 4.5.0 doesn't seem to work on MacOS Sonoma 14.2

### ISSUE THREAD

**Issue by mably** [osxfuse/osxfuse#992]
Keep getting this message:

<img width="314" alt="image" src="https://github.com/osxfuse/osxfuse/assets/385653/3a464e27-da2f-43ec-bd56-4f0414b53981">

But when I check the system preferences there is no reference to "Benjamin Fleischer":

<img width="569" alt="image" src="https://github.com/osxfuse/osxfuse/assets/385653/10476395-b8b3-4cc0-827c-9b53eb2853dd">

**Comment by bfleischer** [comment]
macFUSE 4.5.0 works fine for me on macOS 14.2. This not a general issue. The button to allow macFUSE to load should be in the section located above "Sécurité".

**Comment by mably** [comment]
At least it was working fine before upgrading to 14.2, don't know what have change since then.

macFUSE doesn't appear anywhere above "Securité" on my Mac:

<img width="556" alt="image" src="https://github.com/osxfuse/osxfuse/assets/385653/5372b033-8c16-4a30-ab92-1c256ffd0b13">

**Comment by nikolafamit** [comment]
Not working for me too.
You can just read from the device, not to write.

**Comment by bfleischer** [comment]
@nikolafamit I assume you are talking about an NTFS volume. Is that correct?

**Comment by nikolafamit** [comment]
> @nikolafamit I assume you are talking about an NTFS volume. Is that correct?

Yes.

**Comment by bfleischer** [comment]
@nikolafamit Then this is a completely different issue. macFUSE is a building block for developing file systems. You won't be able to read from or write to your NTFS volume using macFUSE alone. What you might be looking for is NTFS-3G. NTFS-3G is an implementation of the NTFS file system and it relies on macFUSE. Please know that NTFS-3G and macFUSE are independent projects. Setting up NTFS-3G to replace Apple's read-only NTFS implementation is not an easy task, especially for recent versions of macOS. If you want to try, look for a recent how-to.

**Comment by nikolafamit** [comment]
Oh, I see now. Tnx for clarification

**Comment by andreagrandi** [comment]
I just upgraded to MacOS 14.2 (14.2.1) and MacFUSE keeps working as expected. I'm using it with latest version of Cryptomator.

**Comment by mably** [comment]
Upgraded to 14.2.1 (Intel), still says that the system extension is blocked.

**Comment by Ayreonaut** [comment]
I have exactly the same issue that @mably describes.

**Comment by lara-koehler** [comment]
I have exactly the same issue as well

**Comment by denericdeneric** [comment]
I have the same issue.

**Comment by TemaMix** [comment]
Faced with the same issue when run command:
`sudo ntfs-3g -o  /dev/disk2s1 /Volumes/NTFS`

mac osx Ventura 13.4.1

I try any command from this discussion and then restart mac os and then try running  again:
`sudo ntfs-3g -o  /dev/disk2s1 /Volumes/NTFS`
And got the same error and open the system settings and there are I observed a new panel with button Details where were information about approved developers and then I restart mac osx again and it works.

then faced with issue:
macfuse error code 100102

but resolve it such way:
`sudo ntfs-3g -o auto_xattr  /dev/disk2s1 /Volumes/NTFS`

**Comment by runkelruebe** [comment]
When I try to mount a veracrypt-encrypted partition on an external disk I get these error messages on macOS Sonoma 14.2 (23C64):

"mount_macfuse: the file system is not available (2)"

and 

"Unsupported macOS Version
The installed version of macFUSE is too old for the operating system. Please upgrade your macFUSE installation to one that is compatible with the currently running version of macOS."


veracrypt: 1.26.7
macfuse: 4.5.0

This happens with every external partition. It has been a couple of weeks since I last mounted any of these partitions but back then it was working fine.
![Screenshot 2023-12-24 at 16 44 08](https://github.com/osxfuse/osxfuse/assets/11949232/c08c4a26-2c32-47c3-9163-df419bb1a0d0)

**Comment by jzhou77** [comment]
I'm using Intel Mac with Sonoma 14.2.1. The last time I reinstalled MacFuse and restarted. After the restart, I can mount the volume. However, today I had the same problem again. I guess maybe I trusted the developer before, so I don't see the button (or whatever) to add the developer.

Anyway, the fix for me is to reinstall MaFuse 4.5 AGAIN and RESTART. After that, I can mount, e.g.,

```
sudo mkdir /Volumes/NTFS 
sudo /usr/local/bin/ntfs-3g /dev/disk2s2 /Volumes/NTFS/ -o local -o allow_other -o auto_xattr -o auto_cache 
```

Replace `/dev/disk2s2` with your actual device ID.

**Comment by denericdeneric** [comment]
All you guys on here seem to be computer experts. I am not. I have PCloud as my cloud back up and now it does not work correctly because of this problem with macFuse. Why can the makers of macFuse not organise a fix for this problem which a Tech idiot like myself can install with one click? I have a Mac mini M1  running Sonoma 14.2.1 Can anyone including the authors of macFuse tell me a simple way to get my iCloud working again?

**Comment by jzombie** [comment]
I was able to get SSHFS working without using macFUSE (or custom system extensions) as a bit of an experiment.

https://github.com/jzombie/sshfs-mac-docker

It uses Docker as an intermediary and mounts the remote in Finder via Samba.

**Comment by bfleischer** [comment]
@denericdeneric pCloud uses a custom version of macFUSE. Please make sure to use the latest version of pCloud. If this does not resolve your issue, I recommend raising the issue with the pCloud team.

@mably (and other with the same issue) Try running the following command in Terminal. It attempts to load the macFUSE kernel extension manually. You need administrator privileges to run the command and you will need to enter your password.

```
sudo /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
```

Then open the "Privacy & Security" system preferences. Is there an "Allow" button as shown on the screenshot below?

<img width="827" alt="232852468-902cc2fe-34ad-48fc-9e4f-26ec6a647979" src="https://github.com/osxfuse/osxfuse/assets/716336/d827afb8-d9fd-428c-9cb1-dde69f6ffbe2">

**Comment by mably** [comment]
Hi @bfleischer, I can confirm that running the command above fixed the problem on my side, thanks 👍

But I can also confirm that I don't have that "Allow" button in the "Privacy & Security" system preferences as can be seen in my original screenshot.

**Comment by TheChatty** [comment]
> @mably (and other with the same issue) Try running the following command in Terminal. It attempts to load the macFUSE kernel extension manually. You need administrator privileges to run the command and you will need to enter your password.
> 
> ```
> sudo /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
> ```

I'm running macOS 14.2 as well. macfuse was installed on a previous version with brew. Brew just upgraded all packages. But there was no directory named 14... only 13 and below. And I also get this "macFUSE too old" message on mounting. After running `brew reinstall macfuse` this directory `14` appeared and trying to mount again told me to trust you (as developer) again. Then it worked just fine.

**Comment by gregvarghese** [comment]
If anyone else is running into this issue, I was able to fix it by disabling System Integrity Protection(SIP) on the mac. 

1. Reboot into macOS [Recovery mode](https://support.apple.com/en-us/HT201314 )
2. Disable [SIP](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection). 

It should prompt you to allow the extensions now. I will try enabling SIP and verify the extension still works but I'm now able to load MacFuse and NTFS drives successfully.

**Comment by jzombie** [comment]
I haven't tried this, but discovered a kext-less implementation (doesn't require a kernel extension) of FUSE here, that currently has 678 stars: https://github.com/macos-fuse-t/fuse-t

I made a workaround myself, using Docker via OrbStack on Mac:  https://github.com/jzombie/sshfs-mac-docker.  Though it's a bit tricky to set up the first time, it doesn't require messing around w/ FUSE, and you can still access remote mounts via Finder / apps.

**Comment by Rocwhite** [comment]
macFUSE 4.5.0 can work on MacOS 14.2.1 normally after do the below 2step.
1, Disable csrutil.
=> Enter Recovery mode, open shell and send command `csrutil disabe`.
2, Enter Recovery mode, 
![Uploading tempImageKnBxXS.gif…]()

**Comment by gingerbeardman** [comment]
Huge instability for me in Sonoma, so much that I have decided to remove MacFuse. Reading old HFS+Extended Macintosh CD-ROMs.

Maybe I will try the above alternative.

**Comment by LiroyvH** [comment]
@bfleischer Thanks, running the terminal command (On latest Sonoma with 4.6.0) made it show up under "Details" in the Privacy settings on the Mac. It showed up as enabled, but "saving" it prompted for password and then noted a reboot was necessary. After that, MacFuse and software relying on it (such as VC) started working again :)

**Comment by morpson** [comment]
Hi - So, no issues with installing 4.6 on Sonoma 14.3 however, nothing has changed for me. I was always able to read my NTFS drive from macOS and I'm still only able to read the drive after installing macfuse. I'm confused to why installing this is useful if it only enables reading (not writing) which is something I thought macOS was already capable of doing. Please let me know if I'm wrong.. my goal here is to read _**&**_ write to my external NTFS drive.

**Comment by runkelruebe** [comment]
> When I try to mount a veracrypt-encrypted partition on an external disk I get these error messages on macOS Sonoma 14.2 (23C64):
> 
> "mount_macfuse: the file system is not available (2)"
> 
> and
> 
> "Unsupported macOS Version The installed version of macFUSE is too old for the operating system. Please upgrade your macFUSE installation to one that is compatible with the currently running version of macOS."
> 
> veracrypt: 1.26.7 macfuse: 4.5.0
> 
> This happens with every external partition. It has been a couple of weeks since I last mounted any of these partitions but back then it was working fine. ![Screenshot 2023-12-24 at 16 44 08](https://private-user-images.githubusercontent.com/11949232/292679920-c08c4a26-2c32-47c3-9163-df419bb1a0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MzAwMzEsIm5iZiI6MTcwNjYyOTczMSwicGF0aCI6Ii8xMTk0OTIzMi8yOTI2Nzk5MjAtYzA4YzRhMjYtMmMzMi00N2MzLTkxNjMtZGY0MTliYjFhMGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE1NDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWJkYjE1MGI5MjlhZDBkMWY4ODU2MzI4MWYzNjdkOTcwYWFmOTkyMjgzZTM3NjZlMzk0OTEyMGM0NWEzNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ignU9X2QPtyvNLEhdgtO4pzlHMrMWtV2fP4ATsQ5_LY)

Updating through brew and then in the System Settings entry for macFUSE from Version 4.4.0 to 4.6.0 fixed the issue for me.

**Comment by earthsound** [comment]
> I haven't tried this, but discovered a kext-less implementation (doesn't require a kernel extension) of FUSE here, that currently has 678 stars: https://github.com/macos-fuse-t/fuse-t
> 
> I made a workaround myself, using Docker via OrbStack on Mac: https://github.com/jzombie/sshfs-mac-docker. Though it's a bit tricky to set up the first time, it doesn't require messing around w/ FUSE, and you can still access remote mounts via Finder / apps.

Be careful (i.e., don't use it) if you're using fuse-t on Sonoma on Apple silicon. macos-fuse-t/fuse-t#45

**Comment by benoitballester** [comment]
Hi @bfleischer ,

I have done all of this above, and I still don't have that "Allow" button in the "Privacy & Security" system preferences.
I am on sonoma 14.3.1, and installed macFUSE 4.6.0

```
benoit@cubix ~ % sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
benoit@cubix ~ % 
```

If I run this 
<img width="857" alt="Screenshot 2024-02-15 at 14 05 13" src="https://github.com/osxfuse/osxfuse/assets/4662116/c4a45968-ad81-41fb-a602-6a85ff3eb66e">

I get that, like everyone
<img width="372" alt="Screenshot 2024-02-15 at 14 05 55" src="https://github.com/osxfuse/osxfuse/assets/4662116/b7c9cf8a-ea70-4bb3-93db-4f8be3728af3">

I have followed your instructions, wihout much luck

<img width="991" alt="Screenshot 2024-02-15 at 12 53 50" src="https://github.com/osxfuse/osxfuse/assets/4662116/0d66b95c-3521-450b-8d68-f449c15a07f3">

<img width="827" alt="Screenshot 2024-02-15 at 12 54 17" src="https://github.com/osxfuse/osxfuse/assets/4662116/0f1783e9-f2ed-4bef-94df-82e9c747a989">

But I do have the macFUSE pane
<img width="996" alt="Screenshot 2024-02-15 at 14 02 43" src="https://github.com/osxfuse/osxfuse/assets/4662116/84ae88e7-3e0e-42a3-8051-25e91810619a">

**Comment by earthsound** [comment]
@benoitballester 
><img alt="Screenshot 2024-02-15 at 12 54 17" width="827" src="https://private-user-images.githubusercontent.com/4662116/305063816-0f1783e9-f2ed-4bef-94df-82e9c747a989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTMxNTEsIm5iZiI6MTcwODA1Mjg1MSwicGF0aCI6Ii80NjYyMTE2LzMwNTA2MzgxNi0wZjE3ODNlOS1mMmVkLTRiZWYtOTRkZi04MmU5Yzc0N2E5ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMDMwNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzEzMTRlMjRkNjM0NjJmMzQ1YmFlYzRhYmQ2OWJiY2ZjNTM3MjVkZDM4ZDZkZGFiNWE4ZjVlZTExZWRkMTBjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kAe4HQwQS2D3Ye6Sse3CQoy-HiQTshyxTiukuGDd0uA">
What do you get when you click the `Details...` button?

**Comment by benoitballester** [comment]
> @benoitballester
> 
> > <img alt="Screenshot 2024-02-15 at 12 54 17" width="827" src="https://private-user-images.githubusercontent.com/4662116/305063816-0f1783e9-f2ed-4bef-94df-82e9c747a989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTMxNTEsIm5iZiI6MTcwODA1Mjg1MSwicGF0aCI6Ii80NjYyMTE2LzMwNTA2MzgxNi0wZjE3ODNlOS1mMmVkLTRiZWYtOTRkZi04MmU5Yzc0N2E5ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMDMwNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzEzMTRlMjRkNjM0NjJmMzQ1YmFlYzRhYmQ2OWJiY2ZjNTM3MjVkZDM4ZDZkZGFiNWE4ZjVlZTExZWRkMTBjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kAe4HQwQS2D3Ye6Sse3CQoy-HiQTshyxTiukuGDd0uA">
> 
> What do you get when you click the `Details...` button?
<img width="827" alt="Screenshot 2024-02-16 at 09 05 09" src="https://github.com/osxfuse/osxfuse/assets/4662116/afbaf0dc-d3e1-43e1-8051-919892d1cc27">

not much really

**Comment by earthsound** [comment]
@benoitballester if you installed via homebrew (especially on an earlier version of macOS), did you try reinstalling (which helped @TheChatty)?

`brew reinstall macfuse`

**Comment by benoitballester** [comment]
> @benoitballester if you installed via homebrew (especially on an earlier version of macOS), did you try reinstalling (which helped @TheChatty)?
> 
> `brew reinstall macfuse`

Yes I have also tried this method, via brew, without any luck

**Comment by bfleischer** [comment]
I'm going to close this issue since the op's problem and all non-NTFS related problems have been resolved as far as I can tell. Please open a new issue in case you are still running into problems on macOS Sonoma.

**Comment by fpaupier** [comment]
I encounter the same error with a M1 macOS
macOS Sonoma 14.4.1 (23E224)
macFUSE 4.7.1

Trying to write on a FAT32 thumbstick

> I have done all of this above, and I still don't have that "Allow" button in the "Privacy & Security" system preferences.
> I am on sonoma 14.3.1, and installed macFUSE 4.6.0

**Comment by bfleischer** [comment]
@fpaupier macOS supports FAT32 natively. No need to use macFUSE for writing on a FAT32 volume. 

And ...

> Please open a new issue in case you are still running into problems on macOS Sonoma.

**Comment by rullskidan** [comment]
I have the same issue as above and I am using the Sonoma 14.4.1 and latest version macFUSE 4.7.2 

Am trying to use with Cryptomator

**Comment by Trandafialex** [comment]
Password:
sudo: /usr/local/bin/ntfs-3g: command not found
trandafiralex@Trandafirs-Air ~ % /dev/disk2s2
zsh: no such file or directory: /dev/disk2s2
trandafiralex@Trandafirs-Air ~ % sudo /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
trandafiralex@Trandafirs-Air ~ % sudo /usr/bin/kmutil load -p /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
trandafiralex@Trandafirs-Air ~ %
