### ISSUE TITLE
Utils to ease the use of NTFS-3G on OSX

### ISSUE THREAD

**Issue by abourdon** [osxfuse/osxfuse#995]
Hello,
I developed a [command](https://github.com/abourdon/ntfs-3g-mount) to ease the use of NTFS-3G on OSX when needed to mount/re-mount NTFS drives. It includes step-by-step commands from the [installation documentation](https://github.com/osxfuse/osxfuse/wiki/NTFS-3G#installation).
Feel free to reference it in the doc if you want. I can include it in a more official repo if necessary.

**Comment by bfleischer** [comment]
Hi Aurélien,

Thanks for your work. macFUSE and NTFS-3G are separate projects and while I know that many people struggle with installing NTFS-3G and using it as a replacement for Apple's NTFS implementation, providing support for NTFS-3G goes beyond the scope of the macFUSE project. Feel free to reference your script in the NTFS-3G wiki page. You should be able to edit it.
