### ISSUE TITLE
`fuse_lowlevel_notify_inval_inode` get stuck

### ISSUE THREAD

**Issue by leavez** [osxfuse/osxfuse#996]
My question is what's the right time to call  `fuse_lowlevel_notify_inval_inode` API? I found `fuse_lowlevel_notify_inval_inode` gets stuck if a fs operation callback (like `read`) is blocking.

 Here is an example base on the https://github.com/osxfuse/filesystems/tree/master/filesystems-c/clock. In the original demo, it will call `fuse_lowlevel_notify_inval_inode` in another thread periodically. I added a `sleep(10)` in the `read` handler, the notify get stuck during the sleep of a read call.  (here's the demo code [demo.zip](https://github.com/osxfuse/osxfuse/files/14067533/demo.zip). It's a xcode project for convenience)

If the `fuse_lowlevel_notify_inval_inode` inside the callback, it will be a deadlock. Any suggestion for using this API.

**Comment by bfleischer** [comment]
`fuse_lowlevel_notify_inval_inode()` is a synchronous API call, i.e. it returns an error code in case something goes wrong. This means  `fuse_lowlevel_notify_inval_inode()` needs to acquire the node lock synchronously. As long a the node lock is held by another thread (in your case the read callback), `fuse_lowlevel_notify_inval_inode()` will be blocked. That's how it is designed to work.

> If the fuse_lowlevel_notify_inval_inode inside the callback, it will be a deadlock.

Calling `fuse_lowlevel_notify_inval_inode()` synchronously in a file system callback handler is against the FUSE contract. You may never call back into the file system from a file system callback. This will in most cases result in a deadlock.

> Any suggestion for using this API.

The clock file system is a good example for using the API. You are supposed to call `fuse_lowlevel_notify_inval_inode()` when you learn about external/remote file changes that macFUSE is not aware of. It's important to call this function from a non-callback thread to prevent deadlocks.

**Comment by bfleischer** [comment]
Feel free to re-open the issue, in case you believe there is a bug in macFUSE.
