### ISSUE TITLE
Macfuse 4.6.0 not working macOS Sonoma 14.3

### ISSUE THREAD

**Issue by Blu-Dread** [osxfuse/osxfuse#997]
i am stuk in a loop between and acceptance of the system extension then restart I can't use macfuse because of if I try it says the system extension can't load you need accept Benjamin Fleischer as trusted extension again and again

![Schermopname 06-02- ](https://github.com/osxfuse/osxfuse/assets/124017731/98c0d9a2-aac2-4502-83e6-414b546b6e38)

<img width="274" alt="Scherm­afbeelding 2024-02-06 om 07 28 05" src="https://github.com/osxfuse/osxfuse/assets/124017731/d2890e17-bf68-492a-9ca9-1d0f6d4c2c68">

**Comment by emretuna** [comment]
Actually it is running file, please follow these steps;
Open system preferences  ->  Enable system extensions 
It will prompt that you should shut down and boot using startup options, do as the prompt says
When you react recovery screen, use the menu and Utilities -> Startup Security Utility
Select your disk and click Security Policy
In the following screen, select Reduced Security and toggle 'Reduced Security-mode and the Allow user management of kernel extensions from identified developers-options'

Reboot and done. It will work as expected.

**Comment by Blu-Dread** [comment]
I tried this step you suggested but doesn't work for me when I try to open startup security utility it says firmware doesn't support security settings .
but I fiksed it some how by reenabling sip and updating the kernel system kext cache

> When you react recovery screen, use the menu and Utilities -> Startup Security Utility
> Select your disk and click Security Policy
> In the following screen, select Reduced Security and toggle 'Reduced Security-mode and the Allow user management of 
> kernel extensions from identified developers-options'
