### ISSUE TITLE
Empty Mounted folder(/Volume/MountName) using 200GB space in SSD drive.

### ISSUE THREAD

**Issue by kondak3** [osxfuse/osxfuse#998]
Hi,  My system has an SSD, a 500GB hard drive, and 16GB of RAM.
When I created a mount folder using the macfuse Mounted Volume folder, I got the information shown below.
`Capacity: 494.38GB
Available: 299.28GB
Used: 195.1GB`

How to reduce this space. Default how much space it will use for the mount.

**Comment by bfleischer** [comment]
The volume information for the virtual volume is returned by your file system code. You could even return a capacity of multiple terabytes if you wanted to. I assume your file system code simply mirrors the volume information of your Mac's system volume. That should easy to verify.

To avoid any misunderstandings: macFUSE does not use up any space on your system volume (or any other volume for that matter) to mount virtual volumes.
